### ISSUE TITLE
FR: consistent gt fields?

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#1073]
Would be possible (and desirable?) to make the genotype fields consistent in ensemble output for variants picked up by different callers? At least for the GT, AO, and DP fields? 

For example, NR (= DP),  NV (= AO) are used in FORMAT in the ensemble vcf when a variant has been called by platypus only.

cheers

**Comment by chapmanb** [comment]
Pär;
This would be desirable, although we haven't tackled it yet to avoid needing to deal with all of these different ways to represent the same information. Sorry I wish we had something in place but we haven't had time to implement and debug. We can definitely add it to the todo list.

**Comment by naumenko-sa** [comment]
It was always hard to consolidate calls from many callers, I did it at the level of report generation for WES.

What changed in 2020:
- Nowadays there is not much sense to run ensemble calling: variant calling became more standard with open source gatk4, just using gatk4 work fast and well.  The focus shifted towards SV, CNV detection, low frequency variants and CNV in cancer samples.
- To get more calls (and add FP), it is possible to consider all calls, not just PASS, i.e. relax filters
- there are powerful variant analysis systems downstream: https://www.solvebio.com/ and others, they might support any input data.

So closing, as it is unlikely that we are going to prioritize this issue.
