### ISSUE TITLE
Request feature: add ScanIndel indelcallers

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#1332]
Sorry to harass with more questions... 

As I understand the documentation, mutect can be combined with one indelcaller (using the indelcaller setting) but only one. Might it, instead, somehow be possible to run all available indelcallers (scalpel, pindel, and sid) and combine the results in the same fashion as the ensemble method? To be able to utilize more callers.

Also, I saw a new tool for indel detection that at least the authors claim to be superior: ScanIndel (https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-015-0251-2). This is a hybrid method that utilizes a number of other tools for calling (https://github.com/cauyrd/ScanIndel). Would it be of interest to integrate this into bcbio? If so, perhaps I could give it a go? (and practice my python).

-P

**Comment by chapmanb** [comment]
Par;
That's right, you can only use a single indelcaller to supplement the MuTect calls. We don't have an approach to run multiple callers and do an ensemble method. Practically, we didn't find scalpel or pindel performing well relative to other full featured callers like VarDict:

http://bcb.io/2016/04/04/vardict-filtering/

So aren't planning to expend a lot more effort into this approach. We have spent a lot of time trying to tune scalpel (http://imgur.com/a/7Dzd3) without much success.

ScanIndel looks great from the paper validation and we'd certainly accept a contribution implementing it. Practically it looks like it's going to be a lot of effort as the requirements are non-trivial: inchworm/trinity + a blat client and server (which is academic only licensed creating a whole additional challenge). It might be worth evaluating outside of bcbio first to determine if it's finding indels you're missing via other methods.

Hope this helps.

**Comment by parlar** [comment]
Okay, thanks. I saw that Rendong Yang, who develops ScanIndel, forked bcbio. Maybe he is working on something. I just sent him an email to enquire.

cheers

**Comment by roryk** [comment]
Thanks, this request is super old now and there hasn't been other interest in integration it, so closing it out for now. Please re-open if this is actually something folks are still interested in.
