### ISSUE TITLE
FR:support for SomaticSeq ensembl caller

### ISSUE THREAD

**Issue by esebesty** [bcbio/bcbio-nextgen#1384]
Hi!

I noticed that you mention some plans on [using SomaticSeq](https://github.com/chapmanb/bcbio-nextgen/issues/1018#issuecomment-140932124) as an ensembl caller in the future. Any updates on this?

I'm[ trying to make SomaticSeq work](https://github.com/razZ0r/somaticseq) with the bcbio output vcf files at the moment, and the main issue seems to be converting the vcf data (+ some samtools/haplotypecaller output) into a nice tab delimited file for the ada stochastic boosting algorithm. The ada model builder/predictor R script is very simple compared to the previous steps. I was wondering if there are any tools in bcbio that could help. Like a magic vcf2tab function. :)

Thanks for any pointer!

**Comment by chapmanb** [comment]
Endre;
Thanks for checking in on this. Unfortunately we don't have any code written to help with this. It's still something we want to work on but after working through what it would take to implement, we realized it was a pretty large project and would take a big time investment. We'd definitely have interest in any work you do on integration. Thanks again for looking at this.

**Comment by roryk** [comment]
Thanks, closing as this is as it is old, is a nice to have that would take a ton of work.
