### ISSUE TITLE
multiQC features requests

### ISSUE THREAD

**Issue by lpantano** [bcbio/bcbio-nextgen#1456]
List of to-be-fixed-bugs or features we want in multiqc:
- [x] single lines for samples with trimming values alone : @lpantano
- [x] ambiguos ratio and 5 - > 3 in main table : @lpantano
- [ ] Summary table has two names for same samples: BAM file name
  (1_2015-08-17_dream-syn4-sort-downsample) and description (syn4-normal)
- [ ] Coverage table standardized on ACMG56, < 20 reads at Q20 using sambamba output. X-axes : Qs, Y-axes : genes. One dot per sample. @lpantano
- [ ] add qsignature warnings and sync with PED files : @lpantano
- [ ] use file with list of file to avoid long command line (depend on V0.7) : @lpantano

**Comment by roryk** [comment]
Thanks, closing as this is pretty old, and a bunch of stuff has been implemented already!
