### ISSUE TITLE
FR: Combine GVCF

### ISSUE THREAD

**Issue by jimmy1977** [bcbio/bcbio-nextgen#1513]
Hi Guys 

Thanks for providing this awesome tool. I had a quick question on combining multiple gvcf's. I see the input is a BAM file - If I understand the reason behind this is so that you can find a good place to split the processing of combine gvcf and joint calling. 

I was wondering if there is any good algorithm I can find where I can take input gvcf's and run through combine gvcf. And run in parallel, I currently split at the ends of the chromosome - but this seems pretty inefficient - after the initial burst I see most of the threads are idle, expect the ones processing chr1, chr2 and chrX.  I was hoping to find an algorithm where I can cut a chromosome in the middle and processes the chromosomes in parallel.

Thanks 
## 

Jimmy

**Comment by chapmanb** [comment]
Jimmy;
Thanks for the question and glad to hear bcbio is useful. We don't have an approach to do this from gVCFs, only the BAM-based callability logic right now. This would definitely be a useful addition and would be something cool to take on as we work to incorporate new joint calling methods. Sorry to not have anything you can use right now and thanks again for the suggestion.

**Comment by roryk** [comment]
Thanks, closing this issue in favor if #2336 as the catch-all gVCF enhancement issue.
