### ISSUE TITLE
Enhancement proposal: Octopus

### ISSUE THREAD

**Issue by schelhorn** [bcbio/bcbio-nextgen#1591]
Octopus is the new successor to Platypus and looks very good on paper: https://groups.google.com/forum/m/?_escaped_fragment_=topic/platypus-users/ONwG6H5hHVc Github: https://github.com/luntergroup/octopus

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the suggestion. We'd definitely like to explore Octopus, thanks for starting a thread on it. It's should be relatively straightforward to include as a variant caller for germline and somatic calling:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/code.html#variant-caller

and we'll need to run validations after inclusion to evaluate. Thanks again for starting the discussion.

**Comment by schelhorn** [comment]
Great; it supports tumor-only as well.

**Comment by ohofmann** [comment]
+1 for me. I'd love to have a third caller for ensemble calling cancer samples without falling back to samtools. Happy to help.

**Comment by schelhorn** [comment]
By the way, it also accepts BED files for targeted regions, not only regions specified on the command lines as shown in the README; see the whole manual at https://github.com/luntergroup/octopus/blob/master/doc/manuals/user/octopus-user-manual.pdf

**Comment by lbeltrame** [comment]
I caught this by chance and I was interested in exploring this caller: it looks like it's no longer available?

**Comment by chapmanb** [comment]
Luca -- I got in touch with Dan and they're currently resolving some intellectual property issues with the university and it will hopefully be available again soon. We'll definitely take an extended look at it once it's available again.

**Comment by schelhorn** [comment]
Since bcbio aleady supports the similar `strelka2` and the `octopus` repository has vanished from Github I am closing this issue.

**Comment by dancooke** [comment]
Octopus is back [online](https://github.com/luntergroup/octopus). Although improved, somatic mutation calling is still not 100% there.

**Comment by chapmanb** [comment]
Dan -- brilliant news, thanks for making this available again. I'll re-open this and we can definitely explore adding to bcbio.

**Comment by naumenko-sa** [comment]
Actually Brad added it:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/octopus.py
