### ISSUE TITLE
freebayes snp, multiple AO values

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#1593]
I notice that this has been seen before (https://groups.google.com/forum/#!topic/freebayes/yJ7tP49Lpz0). As suggested, I tried running `bcftools view -a` but this did not correct the multiple AO values in this case. But regardless and most importantly, do the multiple values indicate some problem? Any way of knowing which one is correct for the variant at hand?

Kind regards,

Pär

Here is an example:

```
chr17   37883561    .   A   G   7.54    PASS    AC=2;AF=1;AN=2;DECOMPOSED;LEN=1;NS=1;TYPE=snp   GT:GQ:DP:RO:QR:AO:QA:GL 1|1:0:46:9:191:15,13:224,233:-15.4887,-2.56165,-12.5386,-1.13241,0,-11.7155
chr17   37883564    .   T   C   7.54    PASS    AC=1;AF=0.5;AN=2;DECOMPOSED;LEN=1;NS=1;TYPE=snp GT:GQ:DP:RO:QR:AO:QA:GL 1|0:0:46:9:191:15,13:224,233:-15.4887,-2.56165,-12.5386,-1.13241,0,-11.7155
```

**Comment by NeillGibson** [comment]
Hi @parlar  this has to do with multi-allelic haplotype variants that are decomposed to 2 (or more) bi-allelic SNPs.  What is a reference allele and what is an alternative allele changes during decomposition. 

As far as I know the RO:QR:AO:QA:GL values do not make sense anymore in these cases . See also this ticket:
https://github.com/chapmanb/bcbio-nextgen/issues/1334

We recognize these cases by the DECOMPOSED flag combined with the mismatch of the number of AO fields and the number of alternative alleles.  In these cases with discard the RO:QR:AO:QA:GL values. 
This catches most of these cases, a small number of variants slips trough this filter (ie we don't discard the values but they don't make sense anymore). 

There is a ticket open at vcflib (which does the haplotype to SNP decomposition). https://github.com/vcflib/vcflib/issues/147

**Comment by roryk** [comment]
Thanks, this is super old, and may not be a problem anymore, so am closing this.
