### ISSUE TITLE
Support temporary directory for goleft coverage step

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#1628]
goleft can be extremely I/O heavy in short bursts as the temporary BED files are written to disk. With many samples and a shared network resource, this can be a significant cause of bottlenecks.

As the intermediates it generates are small, it would not hurt supporting a temporary directory like with other tools.

**Comment by brentp** [comment]
Hi,
Is it for exome or WGS?
is the load on the disk enough that your CPU's are not keeping busy? 
if so, please open an issue on the goleft repo and I'll consider adding.

**Comment by lbeltrame** [comment]
Sorry, I completely missed the reply here! 
My test was for exome: the file system I use is distributed, and I see high (but not critical) load on the backend storage servers when "goleft" runs. This causes additional network traffic and in the end timeouts, which in turn ends up as a I/O error. 

To make a similar example, GEMINI has a similar problem when having large core numbers and a shared network resource (which is solved by setting a node-local temporary dir).

**Comment by lpantano** [comment]
Hi @lbeltrame and @brentp,

was this resolved?

thanks!

**Comment by roryk** [comment]
Closing, as it is stale. Thanks!
