### ISSUE TITLE
Please add 2-pass STAR in RNA-seq

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#1629]
Hi bcbio developers (Rory)!

Thank you for the excellent system!

I found that RNA-seq pipeline uses 1-pass STAR while 2-pass is highly recommended.
(it allows to calculate reads mapped to novel junctions accurately ).
GATK best practices recommend 2-pass STAR for RNA-seq.

1-pass might undermine the downstream analysis of splicing/expression,
and it also might reduce the precision of variant calling.

Could you please add this step?

https://software.broadinstitute.org/gatk/guide/article?id=3891
First alignment
```
runDir=/path/to/1pass
mkdir $runDir
cd $runDir
STAR --genomeDir $genomeDir --readFilesIn mate1.fq mate2.fq --runThreadN <n>
```
New index
```
genomeDir=/path/to/hg19_2pass
mkdir $genomeDir
STAR --runMode genomeGenerate --genomeDir $genomeDir --genomeFastaFiles hg19.fa \
    --sjdbFileChrStartEnd /path/to/1pass/SJ.out.tab --sjdbOverhang 75 --runThreadN <n>
```
Second pass
```
runDir=/path/to/2pass
mkdir $runDir
cd $runDir
STAR --genomeDir $genomeDir --readFilesIn mate1.fq mate2.fq --runThreadN <n>
```

Thanks,
Sergey

**Comment by naumenko-sa** [comment]
Ok, in the meantime I have added 
`--twopassMode Basic`
 to my copy of bcbio/ngsalign/star.py according to the manual 
https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
because I'm running per sample analysis. It will not work in multi-sample case.

**Comment by roryk** [comment]
Thanks Sergey, what do you mean regarding per-sample and multi-sample?

**Comment by naumenko-sa** [comment]
It is from the STAR manual:
https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
for one sample studies it is sufficient just to add --twopassMode Basic,
for studies with many samples the format is different:

```
For a study with multiple samples, it is recommended to collect 1st pass junctions from all samples.
1. Run 1st mapping pass for all samples with ”usual” parameters. Using annotations is recom-
mended either a the genome generation step, or mapping step.
2. Run 2nd mapping pass for all samples , listing SJ.out.tab files from all samples in
--sjdbFileChrStartEnd /path/to/sj1.tab /path/to/sj2.tab ....
```

**Comment by roryk** [comment]
Gotcha, thanks. I will have this implemented for the new year.

**Comment by naumenko-sa** [comment]
Ok, thanks! People usually do RNA-seq with many samples so the second way is better.

**Comment by ethanbahl** [comment]
Is twoPass mode the default setting or does it have to specified somewhere?

**Comment by naumenko-sa** [comment]
Hi @ethanbahl!
 
According to the STAR manual, by default --twopassMode is None, i.e. OFF and bcbio does not have an option to turn it ON for now.

To turn twopassMode on, you have to run STAR outside of bcbio, and then feed the pipeline with the bam file, or fix your copy of star.py.

I am not sure, whether 2pass STAR is really crucial. It is recommended everywhere, but in my tests 1-pass discovered junctions in the same way as 2pass.

But of course people running splicing analysis will feel more confident with 2-pass in bcbio.

Rory, would it be possible to implement this at some point? 

Sergey

**Comment by roryk** [comment]
Hi everyone,

Thanks, I have tried twopassMode and it didn't seem to make too much of a difference on some test data so I didn't bother implementing support for it. It was simulated data though so might not be the best test. I can add support for this for the next release; it will be off by default though.

**Comment by ethanbahl** [comment]
Hi @naumenko-sa and @roryk !

I appreciate the quick replies and useful information. In the meantime, I was able to simply add '--twopassMode Basic ' into the command in star.py and my data is running currently. 

Thanks for the incredibly useful pipeline!
Ethan

**Comment by roryk** [comment]
Thanks Sergey, looks like we have this implemented now!
