### ISSUE TITLE
RF: Lofreq

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#1638]
With reference to discussions here (https://github.com/chapmanb/bcbio-nextgen/issues/112) , any new thoughts on including lofreq among the callers in bcbio?

**Comment by chapmanb** [comment]
We'd like to look at LoFreq and I've had some success using it for low frequency calling in HIV variants. In terms of priorities, the plans are to first upgrade FreeBayes to the latest version (#1634) and then integration/validate Octopus (#1591) so we won't have resources to work on this in the short term. As always, we'd be happy to help with anyone who wants to work on contributing this (http://bcbio-nextgen.readthedocs.io/en/latest/contents/code.html#variant-caller). Thanks much.

**Comment by parlar** [comment]
Thanks. If I manage to find some time I'll take a look at it. 
Both Octopus and the new version of Freebayes look good!

//Pär

**Comment by roryk** [comment]
Closing this out as it is pretty old; we've done some other work with low frequency variant calling that hopefully should suffice.
