### ISSUE TITLE
hangup - ' returned non-zero exit status 2

### ISSUE THREAD

**Issue by iranmdl** [bcbio/bcbio-nextgen#1757]
Hi there,
I'm trying to run bcbio-nextgen framework with cancer DREAM synthetic 3 dataset, using the data provided along with the tool and the configuration file. It starts running correctly but suddenly at a given point it gets stop with the following error (see bellow). Any help would be appreciated.

```
[2017-01-16T22:45Z] Calculate coverage: syn3-tumor
[2017-01-16T23:46Z] hangup
[2017-01-16T23:46Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/shared/storage/private/001-scripts_dev/004-lib_and_deps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/shared/storage/private/001-scripts_dev/004-lib_and_deps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'goleft depth --windowsize 5000 --q 1 --mincov 4 --reference /shared/storage/private/001-scripts_dev/004-lib_and_deps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -
-processes 3 --stats --ordered --bed /shared/storage/private/001-scripts_dev/004-lib_and_deps/cancer-dream-syn3/work/align/syn3-tumor/syn3-tumor-coverage.depth-tocalculate-windows.bed --prefix /shared/storage/private/001-scripts_dev/004-lib_and_deps/cancer-dream-syn3/work/align/syn3-tumor/tx/tmps0b6AE/syn3-tumor-coverage /shared/storage/private/001-scripts_dev/004-lib_and
_deps/cancer-dream-syn3/work/align/syn3-tumor/syn3-tumor-sort.bam
hangup
' returned non-zero exit status 2
```

**Comment by chapmanb** [comment]
Sorry about the issue and thank you for the report. Is this a reproducible problem if you re-run bcbio? The `hangup` message indicates some type of problem with the shared filesystem. I haven't seen that before but believe that is where it would be coming from. If re-running still fails consistently at the same point, you could also try using a local temporary directory for intermediate files, instead of the shared filesystem:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#temporary-directory

If that's not an option, we'd need more information to diagnose what is happening. What type of filesystem is `/shared/storage`?

Hope this all helps.

**Comment by iranmdl** [comment]
Thank you very much for the quick response.
You're right.  I've just re-runned the script and now it crashes at another point, regarding the GATK tool.

```
subprocess.CalledProcessError: Command 'set -o pipefail; java -Xms500m -Xmx6370m -XX:+UseSerialGC -Djava.io.tmpdir=/shared/storage/private/001-scripts_dev/004-lib_and_deps/cancer-dream-syn3/work/tx/tmpcGTgkv -jar /shared/storage/private/001-scripts_dev/004-lib_and_deps/bcbio/toolplus/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar -T BaseRecalibrator -o /shared/storage/private/001-scripts_dev/004-lib_and_deps/cancer-dream-syn3/work/align/syn3-tumor/tx/tmpz64vtN/syn3-tumor-sort.grp -I /shared/storage/private/001-scripts_dev/004-lib_and_deps/cancer-dream-syn3/work/align/syn3-tumor/syn3-tumor-sort.bam -R /shared/storage/private/001-scripts_dev/004-lib_and_deps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --knownSites /shared/storage/private/001-scripts_dev/004-lib_and_deps/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-147.vcf.gz -L /shared/storage/private/001-scripts_dev/004-lib_and_deps/cancer-dream-syn3/work/bedprep/NGv3.bed --interval_set_rule INTERSECTION -nct 4 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/gatk/engine/CommandLineGATK : Unsupported major.minor version 52.0
```

I'm using **GATK 3.7-0-gcfedb67** version, do you think there is any incompatibility?
Thank you again

**Comment by chapmanb** [comment]
Glad the re-run fixed the filesystem issues and you were able to move on. For your GATK error, what version of bcbio are you running? Older versions relied on an external Java installation and had a different install mechanism but we've now switched over to a new way of handling GATK:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2

Could you try updating bcbio and registering the GATK download:
```
bcbio_nextgen.py upgrade -u stable --tools --data
gatk-register /path/to/your/GATK-3.7-download.tar.bz2
```
Hope that gets it working for you.

**Comment by roryk** [comment]
Thanks, this should be a non-issue now, so closing.
