### ISSUE TITLE
cancer pipeline I/O issues

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#1816]
Hi,

I am working on a cancer pipeline for a customer and its giving me a I/O issue. I am using 8 nodes to parallize the job

[sequencing@ihg-headnode-1 raleigh]$ tail bcbio.stderr
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 63, in align_to_sort_bam
    names, align_dir, data)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 116, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 140, in align_pipe
    ("bwa-mem" in dd.get_tools_off(data) or not _can_use_mem(fastq_file, data, min_size))):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 107, in _can_use_mem
    raise IOError("Failed to check fastq file sizes with: %s" % cmd.format(**locals()))
IOError: Failed to check fastq file sizes with: cat <(grabix grab /mnt/speed/qc/sequencing/ihg-pipeline/raleigh/align_prep/2N_S2_L001_R1_001.fastq.gz 1 20000000) | head -n 8000000 | /mnt/speed/qc/sequencing/bcbio/galaxy/../anaconda/bin/seqtk sample -s42 - 5000 | awk '{if(NR%4==2) print length($1)}' | sort | uniq -c

**Comment by DiyaVaka** [comment]
ok i tried this based on your comment to another use and ii get this error

 cat <(grabix grab /mnt/speed/qc/sequencing/ihg-pipeline/raleigh/align_prep/2N_S2_L001_R1_001.fastq.gz 1 20000000) | head -n 8000000 | /mnt/speed/qc/sequencing/bcbio/galaxy/../anaconda/bin/seqtk sample -s42 - 5000 | awk '{if(NR%4==2) print length($1)}' | sort | uniq -c
-bash: grabix: command not found

**Comment by chapmanb** [comment]
Diya;
Sorry about the issue. To help debug, you'll need to have bcbio and all the executables in your PATH. Specifically you're missing grabix here. Based on your other path I think:
```
export PATH=/mnt/speed/qc/sequencing/bcbio/anaconda/bin:$PATH
```
will do it. Hopefully that gives some insight into why this command fails and we can debug further.

**Comment by DiyaVaka** [comment]
Thank you. I tried that

(data_management_env)[sequencing@ihg-headnode-1 raleigh]$ cat <(grabix grab /mnt/speed/qc/sequencing/ihg-pipeline/raleigh/align_prep/2N_S2_L001_R1_001.fastq.gz 1 20000000) | head -n 8000000 | /mnt/speed/qc/sequencing/bcbio/galaxy/../anaconda/bin/seqtk sample -s42 - 5000 | awk '{if(NR%4==2) print length($1)}' | sort | uniq -c
   5000 101

So why is it failing when it is going through the pipeline.

**Comment by chapmanb** [comment]
Diya;
Do you have the PATH to the bcbio executables, including grabix, set before running the pipeline? My guess is that this is not setup correctly causing grabix to fail in that command and triggering the error. You should be able to run `grabix` from the bcbio installation. Try doing `which bcbio_nextgen.py` to determine the install path you used for bcbio that should get added to your PATH. Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad,

The pipeline progressed well all the way to alignment and when it started mutect2 it gave the following error. bcbio does not come with full version of GATK?

[sequencing@ihg-headnode-1 raleigh]$ tail bcbio.stderr
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 200, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 330, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect2.py", line 86, in mutect2_caller
    "Require full version of GATK 3.5+ for mutect2 calling"
AssertionError: Require full version of GATK 3.5+ for mutect2 calling

**Comment by chapmanb** [comment]
Diya;
GATK requires manual installation due to licensing restrictions. Here are the details about how to add it if you'd like to use GATK or MuTect2:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2

Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad 

We have the gatk jar and the license version of gatk sitting in a place where it is supposed to be. Do we still need to run the gatk-register command?

**Comment by pfujita** [comment]
Hi Brad,

Our situation is that we have a license for GATK v3.4 and that is what our bcbio installation is currently configured to use. Unfortunately, we have a client that wants to run mutect v2 - which as I understand it, is folded into GATK as of v3.5. We need to maintain v3.4 as it is the license we have for now and are using that on samples requiring a licensed version. 

So our next question is - could we set up a second system.yaml within the same bcbio installation that points to a second (newer) version of GATK that includes mutect? Or do we need to set up a second separate bcbio install if we want to be able to use both versions of GATK concurrently?

thanks for your help,

Pauline

**Comment by chapmanb** [comment]
Diya and Pauline;
Thanks for the explanation, You're right that MuTect2 is only available in GATK 3.5+ versions so won't work with the GATK 3.4 you have installed. We don't have a way to cleanly run simultaneous versions of GATK in bcbio. To manually do it, you could copy the bcbio_system.yaml file for your project, edit it to point at at GATK 3.7 jar, and then pass it to the project you're running:
```
bcbio_nextgen.py bcbio_system_gatk37.yaml your_samples.yaml
```
Hope that gets it running for you.

**Comment by DiyaVaka** [comment]
Hi Brad,

Even after pointing it s giving me the same assertion error. Below is the shell script for bcbio

# Set the paths for our installation
BCB_DIR=/mnt/speed/qc/sequencing/bcbio
JAVA_BIN=/home/sequencing/src/jdk1.7.0_25/bin #For Java 1.7
PYTHON_LIB=/home/sequencing/local/lib
export PATH=/opt/sge625/sge/bin/lx24-amd64:/home/sequencing/local/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/sequencing/bin
export PATH=/mnt/speed/qc/sequencing/bcbio/anaconda/bin:/home/sequencing/src/jdk1.7.0_25/bin:$PATH
echo "PATH:"$PATH

PYTHON_LIB=/home/sequencing/local/lib
PYTHONPATH="$BCB_DIR/anaconda/lib/python2.7/site-packages:${PYTHONPATH}"
export PYTHONPATH
echo "PYTHONPATH:" $PYTHONPATH
export LD_LIBRARY_PATH=$PYTHON_LIB:$LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH:" $LD_LIBRARY_PATH

#################################

#The fastq to vcf pipeline
SCRIPT=/mnt/speed/qc/sequencing/bcbio/bin/bcbio_nextgen.py
FLAGS="-n 1"
SYSTEM_YAML="/path/to/bcbio_system.yaml"
SAMPLE_YAML="/path/to/2NT/cancersample.yaml"
OUTPUT_DIR="/path/to/2NT/"
OUTFILE="/path/to/2NT/bcbio.stdout"
ERRFILE="/path/to/2NT/bcbio.stderr"
cd $OUTPUT_DIR
$SCRIPT $FLAGS $SYSTEM_YAML $SAMPLE_YAML > $OUTFILE 2> $ERRFILE

As an alternative I would like to run the samples directly through mutect2 program. For this I need the target_interval_list file. Does bcbio generate this in any intermediate directories that I use?

**Comment by chapmanb** [comment]
Diya;
Sorry about the continued problems. From what I can tell your setup looks okay as long as you're pointing to the right `SYSTEM_YAML` file with GATK 3.7 installed for your MuTect2 runs. Is it possible that you've registered the GATK 3.4 version with `gatk-register`? If so, `gatk --version` would report this. bcbio uses this version by default if registered, so if you're trying to do both 3.7 and 3.4 at the same time you might need to unregister it so it can use the versions in your `bcbio_system.yaml` files.

For running externally, bcbio generates those BED files as part of the run process, split by region. So there is no single pre-generated file to pull from unfortunately.

Hope those ideas help get your analysis running within bcbio.

**Comment by roryk** [comment]
Thanks, I'd be surprised if this problem still exists, so closing. Thank you!
