### ISSUE TITLE
Feature Request: Chip-seq Analysis

### ISSUE THREAD

**Issue by lpantano** [bcbio/bcbio-nextgen#1831]
[X]  Filter blacklist region https://github.com/chapmanb/bcbio-nextgen/issues/1820
[ ] LCR from macs bed peaks. https://github.com/chapmanb/bcbio-nextgen/issues/1828
[ ] deeptools to normalize bw files. https://github.com/chapmanb/bcbio-nextgen/issues/1820

**Comment by lpantano** [comment]
Hi @apastore,

What command you use to filter by insert size?, I would like to implement something that actually somebody is using.

Thanks!

**Comment by apastore** [comment]
samtools view -h foo.bam | perl -lane '$l = 0; $F[5] =~ s/(\d+)[MX=DN]/$l+=$1/eg; print if $l <  50 or /^@/' | samtools view -bS - > bar.bam

**Comment by apastore** [comment]
This is what i am using. I hast ist from https://www.biostars.org/p/12406/

What Would be also nice in the Chip-seq is to Not depend on Input Paired sample. 

What do you think?

My last feature request would be to automatically quantifiy spike in signal (on Dm3)

Thanks!

**Comment by lpantano** [comment]
Hi,

I think I would use `sambamba` because the filtering is quite good. If I understood well, we can use the TLEN column, that for DNA is the fragment size. (What TLEN reports is the distance from the 5'-most to 3'-most position.) If we remove the size of the reads (x2) then we got the distance between the paired reads.

And that distance is what it should be < 50 in this case. 

What do you think?

thanks!

**Comment by apastore** [comment]
Thanks Lorena, That's correct!
( insert size is really small in Atac-seq even less then 20bp)

**Comment by DoaneAS** [comment]
Hi,
In the spirit of bcbio and best-practice pipelines, I'm wondering what is the reference to for filtering reads on insert size in this way.  ENCODE has published a best-practices [ATAC-seq pipeline](https://www.encodeproject.org/atac-seq/).  It is wrapped in an uncommon scripting language, but the underlying code is available.  Our essential ATACseq pipeline uses the same code and is [here](https://github.com/DoaneAS/ATACseq).  Very similar methods are described in many publications.  I'm a big fan of bcbio and hope to contribute more in the future.

best,
Ashley

**Comment by apastore** [comment]
Hi Ashley,

 is not the same of what are u doing here with --maxFragmentLength 150?

My idea was to have a bam file with only short fragment, (and one with all reads), since implementing a full ATAC pipeline would have been required a greater overhaul of the Chip-seq pipeline already implemented In bcbio


bamCoverage --bam $TMPDIR/${Sample}/${Sample}.sorted.nodup.noM.bam --binSize 5 \
-outFileFormat bigwig --smoothLength 150 \
--normalizeUsingRPKM \
--maxFragmentLength 150 \
-o $TMPDIR/${Sample}/${Sample}.smooth150.center.extend.fpkm.max150.bw --centerReads --extendReads --numberOfProcessors ${NSLOTS}
Thanks,
Alessandro

**Comment by lpantano** [comment]
Hi @DoaneAS,

thanks for the link! Are you doing as well this filtering? only working with short reads? If you do, can you  point me to your code? 

As well, We are happy for any PR! :) there is a lot of knowledge in that pipeline, but probably need quite of a time to migrate it :)

**Comment by mjsteinbaugh** [comment]
@lpantano +1 on wanting to update the ChIP-seq pipeline to not depend on an input paired sample

```
phenotype: chip
phenotype: input
```

**Comment by roryk** [comment]
Thanks, we're going to be doing a bunch of development on ChIP-seq in the upcoming weeks, so will open a catch-all issue for the plan for what is going to be implemented and close this one.
