### ISSUE TITLE
get_quality_format() not in bcbio.pipeline.datadict code

### ISSUE THREAD

**Issue by tiehan** [bcbio/bcbio-nextgen#1861]
In bcbio.ngsalign.rtg.py :  
from bcbio.pipeline import datadict as dd
dd.get_quality_format(data).lower()

but get_quality_format not in bcbio.pipeline.datadict.py

**Comment by chapmanb** [comment]
Thanks for the report. Could you provide a bit more context about the error/problem you're having? A traceback from the initial run would be very helpful to try and provide some pointers.

For your question, the `get_*` functionality in datadict.py uses some python magic so the right place to look for these is in the `LOOKUPS` dictionary where `quality_format` is present. So it appears everything is right but seeing your initial error could help identify the problem you're running into. Thanks much.

**Comment by roryk** [comment]
This definitely should be a non-problem now, so closing. Thank you!
