### ISSUE TITLE
downlaod mouse genome for esiting bcbio installation

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#1867]
Hi Brad,

We have a bcbio installation (3.4) for the past two years and we downloaded only GRCh37 at that time. We cannot upgrade as we have locked this version for our clinical studies. Now that we have requests for mouse data and we don't have mm10 genome in our initial installation, I tried getting it but looks like its going to upgrade entire bcbio package.

As an alternative I tried to install it in a different location and it ended up with errors. How can get mm10 on existing installation? If not can you help in fixing the below errors.

mv: cannot stat `master': No such file or directory
Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x2b543bb14a28>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /mnt/speed/qc/sequencing/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
INFO: CentOS setup
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['rtg'], 'genomes': [{'name': 'Mouse (mm10)', 'dbkey': 'mm10', 'annotations': ['problem_regions', 'dbsnp', 'transcripts', 'mirbase']}], 'install_uniref': False}'): Mouse (mm10)
[localhost] local: mkdir -p /coldstorage/vakad/genomes
[localhost] local: mkdir -p /coldstorage/vakad/genomes/Mmusculus/mm10
INFO: Genome preparation method ggd failed, trying next
INFO: Downloading genome from s3: mm10 seq
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: mkdir -p '/home/sequencing/tmp/cloudbiolinux/5f24256c-eecf-3715-aa28-2756cde9a517'
[localhost] local: wget --continue --no-check-certificate -O mm10-seq.tar.xz 'https://s3.amazonaws.com/biodata/genomes/mm10-seq.tar.xz'
--2017-03-15 13:04:50--  https://s3.amazonaws.com/biodata/genomes/mm10-seq.tar.xz
Resolving s3.amazonaws.com... 52.216.66.11
Connecting to s3.amazonaws.com|52.216.66.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 660653188 (630M) [binary/octet-stream]
Saving to: “mm10-seq.tar.xz”

100%[===============================================================================================================================>] 660,653,188  197K/s   in 64m 25s 

2017-03-15 14:09:15 (167 KB/s) - “mm10-seq.tar.xz” saved [660653188/660653188]

[localhost] local: mv mm10-seq.tar.xz /coldstorage/vakad/genomes/Mmusculus/mm10
[localhost] local: rm -rf /home/sequencing/tmp/cloudbiolinux/5f24256c-eecf-3715-aa28-2756cde9a517
[localhost] local: xz -dc mm10-seq.tar.xz | tar -xvpf -
seq/
seq/mm10.fa
seq/mm10.fa.fai
seq/mm10.dict
seq/mm10-resources.yaml
tar: seq: Cannot change mode to rwxrwsr-x: Operation not permitted
tar: Exiting with failure status due to previous errors

Fatal error: local() encountered an error (return code 2) while executing 'xz -dc mm10-seq.tar.xz | tar -xvpf -'

Thanks,

**Comment by chapmanb** [comment]
Diya;
My suggestion would be to install a separate up to date bcbio to use for mm10 runs and any other non-clinical updates you need. That way you avoid any issue with your production version. bcbio can do a data-only install but will also try to update data for your GRCh37 install which I assume you don't want to happen.

The error you saw looks like a filesystem permissions error, so is likely separate from this -- maybe you have the genome directories in your production install read-only? Hope the separate install for new genomes works for you.
