### ISSUE TITLE
_scale_cores_to_memory will return mem_pct = 1 

### ISSUE THREAD

**Issue by tiehan** [bcbio/bcbio-nextgen#1871]
In resources.py 
def _scale_cores_to_memory(cores, mem_per_core, sysinfo, system_memory):

total_mem = "%.2f" % (cores * mem_per_core + system_memory)
 mem_cores = int(math.floor(float(total_mem) / mem_per_core))  # cores based on available memory
 mem_pct = float(out_cores) / float(cores)

because system_memory = 0.10 ,
so mem_Pct will always be 1

**Comment by chapmanb** [comment]
Thanks for discussing this issue. I've been reading the code here and am a bit confused about what issue you're running into. Could you provide some context and error/bad behavior that you're seeing from the core estimation?

Practically, the lines you've cut also have other context where we adjust them. Specifically, the idea is to adjust down mem_pct only if the requested memory is larger than available system resources via this line that resets total mem:
```
    total_mem = min(float(total_mem), float(sysinfo["memory"]) - system_memory)
```
If this isn't the case, then getting mem_pct of 1 from this calculation makes sense. It's essentially saying that everything is good so no need to adjust. Does that help explain what you're seeing?
