### ISSUE TITLE
DangerTrack blacklisted genomic regions

### ISSUE THREAD

**Issue by schelhorn** [bcbio/bcbio-nextgen#1891]
This approach may be of interest as an extension of the ENCODE and Li blacklists: https://f1000research.com/articles/6-443/v1 Anyone interested?

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the pointer, this looks really nice and is a good way to generalize and catch additional problematic regions. I'd love to include this in bcbio. This would be most useful if we could extend to hg38, although I know we won't have as many SV inputs to use for building. @igordot -- have you given any thought to hg38 support with DangerTrack? Thanks again for starting this discussion.

**Comment by igordot** [comment]
Thanks for considering DangerTrack!

DangerTrack is technically genome-agnostic. We ran it for hg19 because we already had the mappability tracks and the GIAB/1KG SV calls. If you have comparable inputs for hg38, it can be repeated for hg38.

**Comment by ohofmann** [comment]
Timely. Been looking at this yesterday as well as a way to unify the ten or so 'problematic' region BED tracks we've been using. Same problem unfortunately, I don't have a good list of hg38 SVs.

**Comment by schelhorn** [comment]
@ohofmann, that sounds like an endeavor that could be of common interest :)

**Comment by schelhorn** [comment]
I'd still be interested in discussing a combined resource for blacklisting genomic regions for SNV/SV calling on hg38; @ohofmann, I believe there may be SV calls somewhere in issue #963, but admittedly _someone_ would have to go through that sprawling list first ;)

**Comment by ohofmann** [comment]
I, uh, have to admit that we are currently stuck with build 37 until GDC / ICGC re-runs all their samples on 38. That _is_ currently ongoing and gives us some breathing space to get other infrastructure work done, but still pains me ;)

**Comment by roryk** [comment]
This still seems like a good enhancement, I'm not sure if we've included anything similar in the interim though.
