### ISSUE TITLE
A problem with AD field in ensemble variant calling?

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#1894]
Hello bcbio developers and users!

With (bcbio-nextgen,1.0.3a-e4eac29,  freebayes v1.1.0-9-g09d4ecf)
I've got an SNP with the weird AD field (I omit most annotations).
It was 3-sample calling:
```
Ensemble-annotated-decomposed.vcf.gz:
1	14930	.	A	G	81.4	PASS	
AC=3;AF=0.5;AN=6;CALLERS=freebayes,gatk-haplotype,samtools,platypus;DECOMPOSED;LEN=1;NS=3;TYPE=snp;rs_ids=rs6682385;
GT:AD:AO:DP:GQ:PL:QA:QR:RO	
0|1:6,5,3:5,3:14:43:92,0,137,32,74,175:140,97:205:6
0|1:1,0,2:0,2:3:6:49,52,59,0,9,3:0,61:31:1
0|1:6,3,2:3,2:11:12:44,0,154,12,114,170:81,62:202:6

gatk-haplotype-annotated-decomposed.vcf.gz
1	14930	rs6682385	A	G	420.5	PASS	
GT:AD:DP:GQ:PL	
0/1:6,5:11:99:141,0,115	
0/1:6,8:14:99:261,0,120	
1/1:0,2:2:6:49,6,0

platypus-annotated-decomposed.vcf.gz
1	14930	.	A	G	38.0	PASS
GT:GL:GOF:GQ:NR:NV	
0|1:-6.4,0,-6.3:5:60:5:1	
0|1:-17.2,0,-12.6:20:99:11:5	
0|1:-0.35,0,-0.25:34:3:2:0

samtools-annotated-decomposed.vcf.gz 
1	14930	.	A	G	299.0	PASS		
GT:DP:PL	
0/1:9:163,0,110	
0/1:2:54,0,6	
0/1:6:117,0,116

freebayes-annotated-decomposed.vcf.gz
1	14930	.	A	G	81.4	PASS	
GT:AD:AO:DP:GQ:PL:QA:QR:RO	
0|1:6,5,3:5,3:14:43:92,0,137,32,74,175:140,97:205:6	
0|1:1,0,2:0,2:3:6:49,52,59,0,9,3:0,61:31:1	
0|1:6,3,2:3,2:11:12:44,0,154,12,114,170:81,62:202:6
```

It has 3 alleles in Ensemble and Freebayes vcfs in AD field. In the bam file there is no evidence of the 3rd allele, and in the decomposed-annotated vcf there is no other variant in this position (1:14930).

Unfortunately, I've deleted intermediate files to check if there is 3-allele SNP in non-decomposed freebayes vcf.

Even if so (then it is, probably, a false call of freebayes), then what is the logic of the ensemble algorithm? Which of AD fields (from freebayes or GATK) does it take and why?

And if there is a 3-allele SNP from FreeBayes indeed,  then variant decomposition failed for AD field?

The particular problem is that some downstream analysis tools (bcftools) 
can't work with incorrect 3-allelic AD field.
```Incorrect number of AD fields (3) at 1:14930, cannot merge.```

Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for the detailed report and sorry about the inconsistencies. This is an unfortunate known problem with the current ensemble approach since we don't try to harmonize outputs. The logic for filling in the FORMAT fields is to take the first caller in order from the `variantcaller` parameter that is available for a given call. So if you have:
```
variantcaller: [freebayes, gatk-haplotype, platypus, samtools]
```
it will pick the first caller with support for that call in order of freebayes, gatk-haplotype, platypus, then samtools.

Since there is no consistency between callers on fields, this will result in different genotype information depending on the support.

FreeBayes definitely has the trickiest behavior and the decomposition and cleanup approaches don't fix things like the AD problem so you'll expect these type of inconsistencies.

Sorry this is not optimal but it's a hard problem to solve and I don't know of any tools that handle it. Your best approach is to assume these are not going to be all correct and that you might need to clean up ensemble post-calling. You may also be able to mitigate some issues by moving FreeBayes down the priority list since it has the most inconsistencies.

Sorry to not have a better answer but hope this helps.

**Comment by naumenko-sa** [comment]
Thanks, Brad!

For the excel report generation step (after bcbio) I do some ALT coverage harmonization between gemini-ensemble, GATK HC, FreeBayes, and Platypus' vcfs. Maybe I should publish this as a small contribution to all of the fantastic work you guys do. 

Do you know any good post-bcbio excel report generation systems for germline variant calling? Everybody should have one :)

Sergey

**Comment by ohofmann** [comment]
Any harmonization work would be good! I've mostly been using CAVA for downstream processing, but would now switch over to https://github.com/sigven/pcgr at least for somatic reports.

**Comment by chapmanb** [comment]
Sergey;
Thanks for offering to share your report generation. If you put it up as a GitHub repository I'd be happy to point to it as a first step towards integration. Thanks again.

**Comment by naumenko-sa** [comment]
Hi, Brad,
https://github.com/naumenko-sa/cre

I'd appreciate any suggestions, how to make it more usable.

Sergey

**Comment by naumenko-sa** [comment]
Thank @ohofmann for these links. I'll try [CAVA](http://www.well.ox.ac.uk/cava)

**Comment by naumenko-sa** [comment]
This variant:
```
12	45797265	.	CAAT	C	1583.44	PASS	AC=1;AF=0.166667;AN=6;CALLERS=freebayes,gatk-haplotype,samtools,platypus;CSQ=inframe_deletion|acAATa/aca|TI/T|ENSG00000177119|ANO6|ENST00000320560|15/20|||609-610/910|protein_coding||CCDS31782.1||||ENST00000320560.8:c.1830_1832delAAT|ENSP00000320087.8:p.Ile611del,inframe_deletion|acAATa/aca|TI/T|ENSG00000177119|ANO6|ENST00000423947|16/21|||630-631/931|protein_coding|YES|CCDS55819.1||||ENST00000423947.3:c.1893_1895delAAT|ENSP00000409126.3:p.Ile632del,inframe_deletion|acAATa/aca|TI/T|ENSG00000177119|ANO6|ENST00000425752|15/20|||609-610/929|protein_coding||CCDS44865.1||||ENST00000425752.2:c.1830_1832delAAT|ENSP00000391417.2:p.Ile611del,non_coding_transcript_exon_variant&non_coding_transcript_variant|||ENSG00000177119|ANO6|ENST00000426898|15/18||||processed_transcript||||||ENST00000426898.2:n.2246_2248delAAT|,inframe_deletion|acAATa/aca|TI/T|ENSG00000177119|ANO6|ENST00000435642|16/21|||609-610/929|protein_coding||CCDS44865.1||||ENST00000435642.1:c.1830_1832delAAT|ENSP00000413840.1:p.Ile611del,inframe_deletion|acAATa/aca|TI/T|ENSG00000177119|ANO6|ENST00000441606|15/20|||591-592/892|protein_coding||CCDS44866.1||||ENST00000441606.2:c.1776_1778delAAT|ENSP00000413137.2:p.Ile593del;DECOMPOSED;LEN=3;NS=3;TYPE=del	GT:AO:DP:GQ:PL:QA:QR:RO	0|1:68:140:99:1662,0,1858:2312:2530:72	0|0:0:169:99:0,509,5331:0:5922:169	0|0:0:173:99:0,518,5375:0:5971:172
```
when loaded to gemini has depth='None', and might be filtered downstream as having low coverage!

So it is better to use gatk-haplotype on the first place for ensemble calling!

**Comment by chapmanb** [comment]
Sergey;
The ensemble method picks the variant to use based on order in the `variantcaller` specification. So if you put `gatk-haplotype` first it should prefer that over FreeBayes and avoid some of these edge case issues (as long as it's also called by HaplotypeCaller). Hope this helps.

**Comment by naumenko-sa** [comment]
Thanks, Brad. Yes, exactly, since April I'm running ensemble calling with gatk-haplotype in the first place. It was an example of the old call  - not just coverage information might be misleading, but the particular variant might be lost because of the filtration on top of that. Just wanted to warn people who are using ensemble method.

**Comment by roryk** [comment]
Thanks, look like this might be a non-issue going forward since it is from old runs. Closing, please reopen if this issue still exists.
