### ISSUE TITLE
RFE: Include sortmerna for RNAseq preprocessing

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#1928]
I've been suggested to use this tool[1] even with kits that employ rRNA depletion because it's not always 100% effective, and 2-3% of rRNA persists in the data. In general, I think support for this wouldn't hurt, but I guess it should be off by default, given that it has the potential of being slow.

It is also Free Software (GPL-3) which means that there shouldn't be any problematic restrictions in its use.

[1] https://github.com/biocore/sortmerna

**Comment by roryk** [comment]
Thanks for posting that, I didn't know about it-- we don't do too much metagenomics work. We calculate rRNA contamination now by looking for rRNA biotypes in the GTF annotation post Salmon quantification and summing those up, but don't actually remove any of the reads. I'm not too sure it would help quantification too much to remove them from the get-go.

**Comment by roryk** [comment]
Thanks, closing this as an enhancement that might be nice but a lot of folks haven't asked for it and we're pretty conservative about adding new tools that might not increase utility as it adds to the support overhead. Happy to revisit if we can get some data that it is very useful, though.
