### ISSUE TITLE
Implement oncofuse -a option for hg38 support?

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#1938]
When using RNAseq fusion detection with STAR and Oncofuse, the [manual](http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html?highlight=fusion_mod) states, that only hg19 and GRCh37 are supported by Oncofuse. 
Indeed, since version the following flag is supported in Oncofuse 
`-a option specifies genome assembly version. Allowed values: hg18, hg19 and hg38. Default value: hg19` (as described over at https://github.com/mikessh/oncofuse)

Wouldn't it be nice to add support for hg38?

**Comment by schelhorn** [comment]
Star doesn't support hg38 alt alignments yet, as far as I know - so it's off limited use right now. Is Hisat2 compatible with Oncofuse, does anyone know?

**Comment by leiendeckerlu** [comment]
Does hisat2 have a fusion detection mode yet? I don't think so, so I don't think it will be compatible. One could use Tophat with hg38 and Oncofuse in bcbio.

**Comment by roryk** [comment]
Thanks, we will be adding support for arriba for both GRCh37 and hg38 in the next few weeks, which crushed everything else in the DREAM challenge.
