### ISSUE TITLE
ExAC priotization

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#1972]
Hi Brad, 
I have a question. If I understand correctly the priorization in Tumor only is done based between other using the ExAC database. 

Since I know that a number of somatic events are present in the original ExAC I am modifying the bcbio ExAC using this list of know somatic event. 

https://github.com/mskcc/vcf2maf/blob/master/data/known_somatic_sites.bed

Does it make sense or are you taking care of those sites in a different way?  

I also do not know if this influence the calling in  tumor normal. 

Thanks a lot!
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
We currently don't pre-process ExAC to remove known somatic sites so doing this manually makes sense for now. Thanks for bringing this up, it would be a good addition to the bcbio prioritization framework. We'd use GEMINI for the ExAC annotation so it would be useful to add this functionality there so we can make us of it generally. Thanks again for the suggestion.

**Comment by apastore** [comment]
Thanks!
