### ISSUE TITLE
/bin/bash: grabix: command not found

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#1973]
Hi there,

when running bcbio with the following yaml config file and ipython enabled: https://gist.github.com/leiendeckerlu/a646dae77e2f2cb397bb08654c7bc0a4

I get the following error:

> IOError: Failed to check fastq file sizes with: cat <(grabix grab DNA_A01_1.fastq.gz 1360000001 1440000000) | head -n 8000000 | bcbio/local/share/bcbio/galaxy/../anaconda/bin/seqtk sample -s42 - 5000 | awk '{if(NR%4==2) print length($1)}' | sort | uniq -c
> 2017-06-10 20:39:50.495 [IPEngineApp] WARNING | apply_request is deprecated in kernel_base, moving to ipyparallel.
> /bin/bash: grabix: command not found

It seems like the $PATH variable is not set properly for grabix? Since the full path is used for seqtk (/bcbio/local/share/bcbio/galaxy/../anaconda/bin/seqtk)  but not for grabix? 

Here's the bcbio-nextgen-debug.log: https://gist.github.com/leiendeckerlu/9c0091cad0e5511a669902e4f3a1585a

Thanks!

**Comment by chapmanb** [comment]
Sorry about the issue, you do need to edit your `PATH` so that all the tools installed by bcbio are available:
```
export PATH=/path_to_bcbio/bin:$PATH
```
http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

We don't consistently use absolute paths (like with `seqtk`) so having all the tools correctly in the PATH will be needed for a lot of downstream steps as well. Hope this helps.

**Comment by leiendeckerlu** [comment]
Yes, I do that, still it does not work, this is my script to submit the run to the cluster:

> #!/usr/bin/env bash
> # -q public.q      # Select the queue
> # -l nodes=4,rpn=24
> # -pe smp 24        # Request an 8-way SMP server
> # -N CNVkit_lule     # Set the job name
> # -j y             # Join stderr and stdout
> #$ -cwd             # Go to current working directory
> 
> export PATH=$PATH:/bcbio/local/bin
> module load gridengine/2011.11
> 
> bcbio_nextgen.py /config/TumorNormal.yaml -t ipython -s sge -n 192 -r pename=smp  -q public.q

So this can't be the issue...

**Comment by leiendeckerlu** [comment]
For us it looks like iPython doesn't distributes the PATH variable to the different nodes in the right way...

**Comment by chapmanb** [comment]
Sorry you still have issues with the PATH set. Is `grabix` present in `/bcbio/local/bin`? It should be symlinked into that directory (with other binaries) from the anaconda install directory, which appears to be ` /bcbio/local/share/bcbio/anaconda/bin`. Did everything finish cleanly with the tool installation, or any other potential issues that would present it from being present?

bcbio does instruct SGE to pass environmental variables through to the worker nodes, inheriting from the parent process, so they should get passed through. I'm confused why you don't see this behavior.

Also, this is not related to the problem but you want the bcbio to be first in your PATH when running, not last, so it will pick up bcbio installed tools instead of other potential system ones (so you'd have the right version of samtools and other binaries that might be present elsewhere).

**Comment by leiendeckerlu** [comment]
Yes, it is present in /bcbio/local/bin and the symlink is also there. Using this particular grabix version from the command line also works. 
It's a indeed a fresh installation, that installed without errors, since the same grabix error also occurred in the old one and we thought that a fresh installation might solve the issue.
So I'm unsure what's going on here...
Apart from that, thanks for the hint, I will set bcbio to be the first in my PATH.

**Comment by leiendeckerlu** [comment]
Also, using other pipeline runs, that start with prealigned bam files and don't use bwa/grabix during their run, work without hassle. Suggesting that it might be indeed a bwa alignment/grabix specific issue.

**Comment by chapmanb** [comment]
Sorry again about the continued issues. I'm still not sure what is going wrong here, but pushed a fix that will explicitly set the PATH for this whole command to hopefully avoid the problem. If you update to the latest development (`bcbio_nextgen.py upgrade -u development`) and re-run, I hope it will get past this and run cleanly for you. If you still have problems downstream please let us know and we can investigate more.

**Comment by leiendeckerlu** [comment]
I didn't try the development version yet (will do that soon), but I did some additional debugging: This issue only occurs if I use iPython to submit jobs. "Normal" job submissions (using only one node) work properly. Also, samtools seems to have the same problem as grabix:

> [2017-06-11T17:07Z] compute-6-26: Unexpected error
> Traceback (most recent call last):
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
>     yield config
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 205, in process_alignment
>     return ipython.zip_args(apply(sample.process_alignment, *args))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 135, in process_alignment
>     out_bam = cleanbam.fixrg(fastq1, data["rgnames"], dd.get_ref_file(data), data["dirs"], data)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/cleanbam.py", line 28, in fixrg
>     "Create empty RG header: %s" % dd.get_sample_name(data))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
>     _do_run(cmd, checks, log_stdout, env=env)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; samtools view -H /M_1/final/M_1N/M_1N-ready.bam | grep -v ^@RG > /clustertmp/$
> /bin/bash: samtools: command not found
> ' returned non-zero exit status 1

We tried to solve this by setting in ipengine_config.py: (/log/ipython/ directory)

c.IPEngineApp.startup_script = u'/path/to/my/startup.py'

With startup.py being a python script that sets the $PATH variable:

> import os
> os.environ['PATH'] = '/bcbio/local/bin'

Is this the right place to add this modification or is there somewhere a master 'ipengine._config.py' file that I have to edit?

**Comment by chapmanb** [comment]
Thanks for following up. I'm not 100% sure about the IPython fix, but we do create a `log/ipython` every time so you'd have to manually apply this, so I don't think it's a great solution for you long term.

The issue I'd like to try to identify is why the cluster does not pass the local PATH on to the worker engines which should happen as part of the process for all schedulers. What scheduler are you using to run this?

Practically, I'd suggest starting with one of the `bcbio_ipengine*` files created during submission and manually edit it to just echo the $PATH. Then you could try submitting to your cluster and determine under what circumstances the PATH gets correctly translated and when it is lost. Perhaps there is a different option we need to set to maintain the parent PATH environment on your cluster? Thanks for the help debugging this.

**Comment by leiendeckerlu** [comment]
Sorry for the delay in response, but we now came up with a solution for the missing pass-on of the $PATH variable. With this submission script to SGE/iPython:

> #!/usr/bin/env bash
> 
> export PATH=/bcbio/local/bin:$PATH
> module load gridengine/2011.11
> 
> bcbio_nextgen.py /clustertmp/CNVkit/config/TumorNormal.yaml -t ipython -s sge -n 192 -r pename=smp  -q public.q

It is necessary to create the following folder structure before submission of the script above via "qsub CNVkit.sh":

/CNVkit/work/log/ipython/startup/ and within the startup folder create the following file 01-loadEnv.py:

> import os
> os.environ['PATH'] = "/bcbio/local/bin:" + os.environ['PATH']

This file is then picked-up by iPython during the startup and the PATH is correctly set.

Maybe you can implement this? I think it is anyway now hassle since I can include the creation of this py file in my qsub script, but it would be more convenient.

**Comment by chapmanb** [comment]
Thanks for following up and all the additional details. I'd like to avoid IPython hacking as part of the bcbio run since this should be getting handled by the scheduler itself. Everything should be set on SGE to pass along environmental variables to the child processes so I'm still confused as to why it doesn't happen on your system. If you're able to do any debugging of the ipengine files as suggested in my last message that would be helpful for us to figure out how to resolve this more generally. Thanks again.

**Comment by roryk** [comment]
Thanks, we've fixed a bunch of these issues where we aren't looking up the executables, so this should be fixed now.
