### ISSUE TITLE
10x sc rna-seq support in bcbio

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#1986]
Hi Brad, Hi Rorky, I was wodering are planing to add 10x to the supported Platform for scRNA-Seq?

Thanks!
Alessandro

**Comment by roryk** [comment]
Hi Alessandro,

Yes-- I just need the list of possible cellular barcodes from 10x and we can add support for it.

**Comment by apastore** [comment]
Thanks! I will inquire 10x for this if anybody already have a list available.

That's amazing !
Alessandro

**Comment by ro6ert** [comment]
Hello Rory,

I was wondering if this is available in a development branch. I didn't see 10x among the bcbio/data/ directory.

Thankyou for all your work on this pipeline.

Best,
-Rob

**Comment by mjsteinbaugh** [comment]
Hi @ro6ert, we're still testing 10X Chromium barcode support, but this is planned on being added in a future release. In the meantime, you can use [cellranger](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger) to generate the counts. I've been using that along with our [bcbioSingleCell](https://github.com/hbc/bcbioSingleCell) R package (see [`readCellRanger()`](http://bioinformatics.sph.harvard.edu/bcbioSingleCell/reference/readCellRanger.html) function) to load up 10X data and run QC/clustering.

**Comment by roryk** [comment]
Thanks-- cellranger is really easy to run, and bcbio isn't doing anything super special with 10x support, so we've defaulting to running cellranger for 10x data and working downstream from that. We are planning on improving single-cell and may end up adding 10x support as part of that, but for now I'd just stick with what we do: run cellranger.
