### ISSUE TITLE
New variation fingerprinting paper for detecting related/duplicated samples

### ISSUE THREAD

**Issue by schelhorn** [bcbio/bcbio-nextgen#1991]
As the title says; like qsignature but possibly faster: see PDF preprint by @gglusman on the arxiv [here](http://biorxiv.org/content/biorxiv/early/2017/06/27/130807.full.pdf).

At our organization we really need these methods since about 5% of the samples we get from CROs are usually swapped or duplicated (yes, I know about QA, but that's the reality folks). Speed is important because we compare each new sample against all our (thousands of) old samples to identify these issues (we redo relevant samples with different vendors and libraries to identify sample swaps, so it's not sufficient to compare within a batch). 

I have approached the first author concerning the implementation (which is supposed to be released on Github) and will report back. Anyone else having an interest/best core practises to share in this domain?

**Comment by mjafin** [comment]
+1
Hopefully a nice licence

**Comment by chapmanb** [comment]
Sven-Eric and Miika;
Agreed, the method looks great and would be great to explore compared to qsignature. It doesn't look like the code is available yet. Gustavo, we'd be happy to explore including this in bcbio once it's made public. As an aside, Figure 2 is depressing: so much disparity in looking at a single sample.

**Comment by ohofmann** [comment]
+1 from here as well. The 5% sample swap rate sounds about right for us, too. I like the concept of being able to build up a reference set and compare these over time, but want to see what they release code-wise.

**Comment by gglusman** [comment]
Thanks for the interest! I'm preparing the code for release. License will be free for non-profit use.

Brad, re:figure 2 - it isn't so bad. The upper-right half of the table shows very high correlation among all versions, which were produced over many years using different technologies... including some very early Complete Genomics tech and pipeline code. The lower-left half looks much worse, but those are the binary fingerprints, which keep just 144 bits per person.

**Comment by schelhorn** [comment]
Thanks, @gglusman. Any chance allowing commercial entities the free use of the software for research purposes? Otherwise it wouldn't make much sense to include it in bcbio since we have multiple pharma users and the remainder of the codebase is free for commercial use (well `kallisto` isn't, but I hope they will change their mind since GATK is now free as well).

**Comment by ohofmann** [comment]
Can I second Sven's request? I'd love to give this a try for projects that involve commercial partners, both locally and for the Cancer Gene Trust.

**Comment by mjafin** [comment]
Seconded too.

**Comment by roryk** [comment]
Thanks everyone! Looks like this does what qsignature does, but has a more restrictive license so closing this out.
