### ISSUE TITLE
Downloading prepared genomes outside of bcbio

### ISSUE THREAD

**Issue by jrderuiter** [bcbio/bcbio-nextgen#2000]
I was wondering if it is possible to download the genomes used by bcbio outside of bcbio (using wget or similar), so that we can easily incorporate the use of these references in other workflows/pipelines. Being able to download these files automatically would improve reproducibility.

Is it possible to download these files somewhere? (I was unable to find anything in the documentation, other than references to an AWS bucket.)

Or are these files downloaded from various sources and prepped on demand by the installer?

**Comment by schelhorn** [comment]
I'd recommend looking at the source of the installer script and/or executing the installer. The URLs can be extracted like this. There is some postprocessing being done as regards indexes and genome annotations. I personally don't see value in providing this functionality explicitly as a service for other workflow systems, though - but of course others may well differ in their opinion. 

On a side note, 2k issues processed is just awesome. Thank you @chapmanb and crew.

**Comment by jrderuiter** [comment]
Of course, I understand the hesitation in providing this as a service. However, I do think it might be a valuable resource, as you are effectively generating a relatively clean reference with matched annotation files (such as dbsnp, known indels etc.). 

I find it disappointing that it is quite hard to find a set of reference files (particularly for human references) that work well together without running into issues stemming from differences between references (e.g., different naming conventions).

**Comment by chapmanb** [comment]
Julian -- thanks for the question. As Sven-Eric mentioned, everything is available for download so could be used in other contexts. It's no problem if you want to use them for personal projects. However it's not something we'd like to encourage on a large scale right now for a couple of reasons. Downloads cost us money and our small core at Harvard Chan School provides this as a service for the community, so the AWS bills can add up. It also adds an additional support burden if folks start using it in different contexts and run into issues.

I agree entirely with your comment about having organized sets of reference files and that's exactly the kind of community resource bcbio hopes to provide. Maybe we could offer more useful suggestions if we understood your use case and why bcbio as is doesn't work for you. Thanks again for the discussion.

**Comment by roryk** [comment]
Asked and answered.
