### ISSUE TITLE
RNA protocol to generate BigWiggle file

### ISSUE THREAD

**Issue by lfaino** [bcbio/bcbio-nextgen#2026]
Dear Developper,
I have a request but i do not know if you can help me. 
I'm working on generating RNA-seq tracks in BigWiggle format to display in JBrowse. I looked a bit around and I see that in BCBIO there are all the tools that i need. However, there is no complete protocol for it. I was wondering if you develop such a protocol. I'm willing to help. 

The protocoll should include:
1. STAR mapping
2. Conversion of the BAM in BigWiggle.

STAR is present in BCBIO and in the folder scripts/utils/ there is a bam_to_wiggle.py script that can be used to transform the BAM file to BigWiggle.

Can you please help?

Best regards
Luigi

**Comment by chapmanb** [comment]
Luigi;
Thanks for the mail and questions. bcbio doesn't have a workflow for generating BigWig files from BAM but feel free to run the tools in bcbio independently. My suggestion would be to run a standard RNA-seq workflow with STAR, starting from an example (http://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#rnaseq-example), on your inputs. Then you can run the bam_to_wiggle.py script manually on the BAM outputs. Hope this helps with getting started and happy to answer more specific questions if you run into problems.

**Comment by roryk** [comment]
Thanks, what Brad said is what I would do too.
