### ISSUE TITLE
RFC: Generate "bamouts" from MuTect 2 outputs?

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2030]
Those are described in https://us.v-cdn.net/5019796/uploads/FileUpload/f0/e1687d793974cf6494aae9f676cf7b.pdf (handout for MuTect 2, grabbed from https://gatkforums.broadinstitute.org/gatk/discussion/9985/gatk-4-beta-clustered-events-in-mutect2-filtermutectcalls).

The definition is

> .​ Manual review extends from deciphering call record annotations to the nitty-gritty of
reviewing read alignments using a visualizer. To review read alignments, we must generate
those that reflect MuTect2’s graph-assembly results. We call these bamouts for the parameter
we invoke. 

Those may help in reviewing "difficult" somatic variants. However with large callsets, that may generate large files, I assume.

Opinions?

**Comment by chapmanb** [comment]
Luca;
Thanks for bringing this up. HaplotypeCaller also has a similar option to produce files like this for debugging. The general recommendation from the GATK team is that these are only useful for digging into a problem region and too big to produce generally. From bcbio's perspective the best bet would be to have folks generate these themselves for regions they need, but if there is anything we can do to make it easier to do happy to consider that. Thanks much.

**Comment by roryk** [comment]
Thanks, closing this out as Brad's suggestion of doing it downstream makes the most sense to me too.
