### ISSUE TITLE
UMI analysis in bcbio

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2070]
Hi Brad,

I'm interested in performing UMI analysis. Does bcbio supports this type of barcoding and umi scheme? My read looks like this:
@K00151:215:HHNMKBBXX:7:1101:23581:1384 BC:Z:CGCACTAAACACCAAG   QT:Z:AAFFFJJJAAFFFJJJ   ZU:Z:ATTGGGCA   ZQ:Z:JJJJJJJF
CACTGAGATCACTGGCACACAAGCAGAGCCCTCTTGCTGTGTTTGTTCTTCCCTTTGGATCTCCTGGCCCTCCCTCGCAGGGAAGCGAGTGTGCCAGTGTTCATGGACTCCTGATGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACC
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJFJJJJAFJ<JJJJJJJFF<AJAAFJJAJFJJFJJJJ<F<JJJJ

where BC: barcode; QT: barcode quality; ZU: Umi; ZQ: Umi quality

Thanks!

**Comment by chapmanb** [comment]
We definitely have UMI support, but it might take some massaging of your input files to get them in a form that bcbio deals with. Is this a variant calling or RNA-seq experiment? We support several different RNA-seq schemes. For variant calling the best approach would be to adjust these the inputs so the barcode is in the read name:
```
@k00151:215:HHNMKBBXX:7:1101:23581:1384:UMI_ATTGGGCA
```
and then use `umi: fastq_name` in the your configuration:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#umis

Happy to provide more specific advice if you can give us more details about your data analysis. Thanks much.

**Comment by phu5ion** [comment]
Hi Brad,

Thanks for your reply. My reads come in this form for both variant calling and RNAseq because of our in-house script that post-processes the data as it comes out of the sequencer. I can do some bash scripting to adjust the inputs into the specific format you specified above and use umi: fastq_name in my config file. Can bcbio accept this configuration for normal RNAseq runs as well, or must it be 1 of the 3 schemes [harvard-indrop, harvard-indrop-v2, cel-seq]?

Thanks!

**Comment by chapmanb** [comment]
For single cell RNAseq, it does have to match one of the supported schemas so you'd have to do a bit of input transformation to match a supported schema (https://github.com/chapmanb/bcbio-nextgen/tree/master/bcbio/data/umis) or we could add support for your approach. @roryk might have more specific suggestions if you can describe your UMI tagging approach. Hope this helps.

**Comment by roryk** [comment]
Great-- if you can adjust your reads to have a format like this:

```
@NS500233:572:H25VKBGX2:1:11101:10465:1041:CELL_AAGAGTAT:UMI_NNNNNN
```

and send along a snippet of the data, I can add support for handling pre-transformed reads to the single-cell RNA-seq pipeline.

**Comment by phu5ion** [comment]
Hi @chapmanb and @roryk ,

Thanks a lot for your replies. My experiment is just plain RNA-seq (not single cell RNA-seq). UMIs are added as a portion of custom adaptors/dual barcodes during the PCR amplification step in a Script-Seq protocol to account for PCR bias. 

Looking at @NS500233:572:H25VKBGX2:1:11101:10465:1041:CELL_AAGAGTAT:UMI_NNNNNN
does CELL_AAGAGTAT refer to the barcode? Mine is 16bp long and is the same for the entire sample, not sure how this feeds into the single-cell RNA-seq pipeline...

**Comment by roryk** [comment]
Hi @phu5ion,

Gotcha-- is Script-Seq tag based? Does it just get the 3' end of the transcripts? If so running it through the single-cell pipeline will be the way to go, it doesn't actually have to be single cell data. We run DGE analyses through that same pipeline, it just does tag based RNA quantification. 

That's right CELL_foo is for a cell/well/whatever with a barcode foo. The samples will get quantitated by separating out on CELL_.

**Comment by phu5ion** [comment]
[sample.zip](https://github.com/chapmanb/bcbio-nextgen/files/1367392/sample.zip)
Hi @roryk 

Sorry for taking a while to get back. Yes it's tag-based. Sounds good! I've attached a short snippet of my files here.

**Comment by roryk** [comment]
Closing this stale issue!
