### ISSUE TITLE
bamsormadup()[0x417762] ' returned non-zero exit status 1

### ISSUE THREAD

**Issue by npbhavya** [bcbio/bcbio-nextgen#2078]
Hi, 

I am running into an error when the command "bamcat level=0 tmpfile=/home/bhnala/bcbiotx/tmp15W5z8/bcbiotx/tmphM6NLy/syn3-tumor-sort.bam-bammerge `cat /home/bhnala/bcbiotx/tmp15W5z8/bcbiotx/tmphM6NLy/syn3-tumor-sort.list` | bamsormadup threads=1 tmpfile=/home/bhnala/bcbiotx/tmp15W5z8/bcbiotx/tmphM6NLy/syn3-tumor-sort.bam-bamsormaduptmp indexfilename=/home/bhnala/bcbiotx/tmp15W5z8/bcbiotx/tmphM6NLy/syn3-tumor-sort.bam.bai > /home/bhnala/bcbiotx/tmp15W5z8/bcbiotx/tmphM6NLy/syn3-tumor-sort.bam" is run. 

The log file is available at https://gist.github.com/npbhavya/c8b30c2736d1f9b1e7b5c6b789ff9f69. I am running bcbio- nextgen on a VM (Jetstream instance: https://jetstream-cloud.org/. I went through a previous issue https://github.com/chapmanb/bcbio-nextgen/issues/1741, and did "bcbio_conda install -c bioconda biobambam" and increased the ulimits to the following 

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 120544
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 200000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 120544
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Can you take a look at this and tell me how I can work around this error.

Thank you, 
Bhavya Papudeshi 
National Center for Genome Analysis Support

**Comment by chapmanb** [comment]
Bhavya;
Sorry about the issue. It appears as if bamsomadup is running into some kind of filesystem issue here but the error message itself is not very informative. A couple of quick thoughts:

- Does re-running the pipeline fail in the same place? A restart should begin in the same place and it would be useful to know if it's reproducible.
- How much memory does the VM have? It's possible we're running into memory issues with this sample and allocating to a larger VM might help.

Sorry to not know exactly what is happening but hope this helps.

**Comment by npbhavya** [comment]
Hi,

Rerunning the analysis does give the same error at the same place. I moved
all the results and reran the analysis but it stops at the same place.

The VM currently has 30 GB memory and 120 GB disk space. I will move to
60GB memory and higher disk space to see if that may help.

Hopefully, this solves the issue.

Thank You,

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by phu5ion** [comment]
I seem to have the same problem. I've been running my samples as parallel jobs in a distributed cluster but after it ran into this error I ran them as single jobs instead. Solves my problem so I suspect it's either a memory or I/O issue.
Hope your analysis is successful too.

**Comment by npbhavya** [comment]
Once I moved to a larger memory VM, I was able to run the analysis
successfully. I believe it was a memory issue.



Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)
