### ISSUE TITLE
genotype given SNPs from amplicon data

### ISSUE THREAD

**Issue by asaki1986** [bcbio/bcbio-nextgen#2079]
Hi Team,

Bcbio is a great tool to manipulate the NGS data.
Our lab used multiplex PCR to enrich the target regions, and then get them sequenced on illumina platform.

Our goal is to look at the specific variants we concerned.

We applied GATK GGA mode in both UnifiedGenotyper and HaplotypeCaller. UG takes shorter time, but with large proportion providing wrong callings, while HC provides more accuate results but takes long time.

As suggested, freebayes has similar performance with HC but can save great time.
I tried "freebayes -f ref.fa -@ in.vcf.gz input.bam > out.vcf" to force genotype the given SNPs.

In this in.vcf, I gave 8 variants, therefore, I expected to obtain exact same variants in the out.vcf. However, I get all SNP that can be genotype within my amplicons.

This troubles me a lot, I am wondering any suggestions that can make me forward?

Great thanks.

**Comment by chapmanb** [comment]
Thanks for using bcbio and starting this discussion. In my experience the `-@` parameter for genotyping given VCFs with FreeBayes is not reliable. We shouldn't use it in bcbio, and it sounds like you may be running it outside of bcbio -- is that correct? If so you could either use FreeBayes and then subset to only your calls of interest, or revert to using GATK HaplotypeCaller which should be much faster if only calling on specific variants. Hope this helps.
