### ISSUE TITLE
PDX blacklist

### ISSUE THREAD

**Issue by schelhorn** [bcbio/bcbio-nextgen#2082]
We have made a (rather trivial but fully reproducible) VCF blacklist of artifactual PDX variants by aligning a couple of mouse strains to the human reference using bcbio. The resulting VCF can be used by vcfanno to mark such artifactual variants in PDX samples that remain (due to high human-mouse homology) even after disambiguation. Perhaps it is of interest to others as well.

Paper: https://www.biorxiv.org/content/early/2017/08/25/180752

Repository: https://github.com/MaxSalm/pdxBlacklist

**Comment by chapmanb** [comment]
Sven-Eric -- nice, thank you for sharing this. This would be great to integrate for PDX runs and I know @mjafin should have a lot of interest. Sorry if I missed this, but are the VCFs publicly available in addition to the pipeline? Thanks again for this work.

**Comment by roryk** [comment]
Hi Sven-Eric, this is so awesome.

**Comment by mjafin** [comment]
+1

**Comment by mjafin** [comment]
Sven-Eric, just double checking, have you seen these variants in multiple captures (or other confounders) because different captures have different artefacts?

**Comment by schelhorn** [comment]
No, it's really a rather basic approach that just looks at publicly available sequencing data from mice lines (some of which are used for PDX) to generate variants that are being called from their alignment to the human reference. 

The data mostly is from various WES kits but we also have WGS for some of the most important lines. However, we did not include the latter here due to size. 

I agree that there are obvious ways to improve the product much and more like a mini-gnomad for artifactual mice variants in humans, but that wasn't in they budget for this iteration.

A next step could be to make VCFs for specific caller+reference combinations and add `vcfanno` definitions to have these annotations automatically added to disambiguation variant calls. Would that make sense to you, @mjafin, or would you recommend another course of action?

**Comment by lbeltrame** [comment]
> A next step could be to make VCFs for specific caller+reference combinations and add vcfanno definitions to have these annotations automatically added to disambiguation variant calls.

IMO that would be a great start. One of the lines of research at my institution relies heavily on PDX, and this would help a lot in reducing the noise.

**Comment by schelhorn** [comment]
Great; I could contribute VCFs for caller+reference combinations of interest. Anyone volunteering for writing the `vcfanno` config files?

**Comment by roryk** [comment]
Can do.

**Comment by schelhorn** [comment]
We're on this and I'll report back once we're done.
