### ISSUE TITLE
Make qsignature thresholds configurable

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2083]
It appears to me that the thresholds that are hard-coded for qsignature are valid for whole genome only, is that correct? I obtain different scores for targeted panels and WES. It appears that the qsignature score is not normalized and that the thresholds depend on the specific target enrichment configuration. Would it be possible to make those thresholds configurable?

**Comment by lpantano** [comment]
Hi @gabeng 

It's a very good idea, I'll work on that today/tomorrow to add an option in resources in the YAML file to allow this configuration.

Thanks!

**Comment by gabeng** [comment]
Thanks, @lpantano, for picking this up so quickly.

**Comment by gabeng** [comment]
Now that VerifyBamId has been integrated into bcbio this may not be such an important feature anymore.
