### ISSUE TITLE
kallisto bam for qualimap/multiqc

### ISSUE THREAD

**Issue by schelhorn** [bcbio/bcbio-nextgen#2087]
Hi There,

Thanks @roryk and @pmelsted for all the awesomeness that is `kallisto` in bcbio. I know that the implementation is work in progress; may I suggest using the `kallisto` [pseudo bam output](https://pachterlab.github.io/kallisto/pseudobam.html) for making a QC bam for `qualimap`/`multiqc`? 

In that manner, we could eventually move away from `star` (and it's memory requirements/hg38-alt incompatibility) for RNA-Seq analyses where QC is desired but no RNA variant calling is required.

**Comment by roryk** [comment]
Thanks Sven-Eric for all the awesome suggestions-- you, read my mind, I'm working on doing exactly this.

**Comment by schelhorn** [comment]
In that case it's you who's awesome, @roryk ;)

**Comment by schelhorn** [comment]
Another wish: can the BAM be used for the existing DEXSeq quantitation as well? In that case we'd have exon counts as well. That would complete the feature set of `kallisto`, in my opinion, and could make user of the existing code for doing so.

**Comment by schelhorn** [comment]
BTW, `multiqc` also has a [`kallisto` module](https://github.com/ewels/MultiQC/blob/master/docs/modules/kallisto.md), but it doesn't contain information from genomic regions.

**Comment by schelhorn** [comment]
It seems as if DEXSeq should work automatically with `kallisto` if the pseudo-alignment BAM produced by the latter is set as `work_bam`; I suspect that `qualimap` should then work with that BAM as well. So we'd 'only' need the pseudo-bam being built and referred to in the global data structure; however, there is a conflict if the user also specifies STAR to be used in the same run, as each aligner produces it's own BAM (not that I see much use for STAR if everything works out). @chapmanb, how are such conflicts handled best?

**Comment by roryk** [comment]
Awesome, thanks for looking into it. I'm with you that it would be nice to drop STAR entirely, I'm running out of reasons to run it. We could prioritize one over the other and stash the non-priority one into its own slot.

**Comment by chapmanb** [comment]
Sven-Eric and Rory -- this sounds awesome, having a direct path to a BAM from kallisto would be brilliant. In terms of conflicts, I'd suggest adding a linting step to run_info.py that raises an error if STAR and kallisto are both set so folks would know they don't need to run STAR in this case. Thanks again for pushing this.

**Comment by schelhorn** [comment]
Another special case just came to my mind (sorry): in case of activated disambiguation, the resulting `kallisto` BAM may file may have to be filtered to exclude the host (e.g., mouse) alignments, woudn't it? I'm assuming that the `kallisto` quantitations are already disambiguated by means of the `kallisto` index and some postprocessing.

**Comment by schelhorn** [comment]
Anyway, I just did test-drive the current state of disambiguated `kallisto` and bcbio doesn't seem to like my configuration; basically, if `aligner` is left away from the sample configuration YAML (since I would like to use only `kallisto` and `pizzly` and do away with `star`), I need to enable `kraken` else the initial sample check in `pipeline.sample` complains that I have FASTQ files by nothing to process them (failing to recognize that `kallisto` can directly process FASTQ as well). 

If I re-enable `kraken` I instead fail in `pipeline.disambiguate` since that piece of code checks for the existence of an aligner as well (although `kallisto` uses the `sailfish` code to generate a pooled transcriptome, which should disambiguate as well). The challenge is that `kallisto` can act as an aligner (if pseudo-BAM is implemented) as well as a expression quantifier; in addition, bcbio simplements at least two modes of disambiguation (BAM-based and pooled-transcriptome-based); last, users can specify both traditional aligners and pseudo-aligners in the same run.

Would it perhaps make sense to somewhere list the capabilities of the aligners/quantifiers in terms of producing BAMs (can/can't), mode of disambiguation (BAM-based or pooled transcriptome-based), and allowed inputs (FASTQ/BAM) and then decide in the code what to do priority-wise based on these capabilities?

**Comment by naumenko-sa** [comment]
STAR is back as of 2020 :)
