### ISSUE TITLE
qsignature: variable overlap in bcbio 1.0.6a compared to 1.0.3

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2134]
The qsignature score seems to be not normalized in the sense that its value depends on the number of SNPs that can be used to compare samples. In the qsignature version used in bcbio 1.0.3 this could be calibrated against the size of the panel that was used. 
When moving to bcbio 1.0.6a from bcbio 1.0.3 I noticed that now there is huge fluctuation of how many SNPs are used to calculate the qsignature score (all samples are from the same panel, qc scores are very homogeneous). This renders the qsignature score unusable. 
Is anybody else experiencing these issues?

**Comment by chapmanb** [comment]
Ben - thanks for reporting this. I wanted to cc in @lpantano to see if she has any thoughts. I don't think we had intentional changes here but would like to get to the bottom of what is going on so we can provide useful output. I haven't been following closely enough to know all the changes but hopefully Lorena has some insight.

**Comment by lpantano** [comment]
Hi,

Specifically for this issue, I didn’t change anything in the code, not sure if the tool has been updated or not.


About the analysis (that hasn’t changed in a while):

It’s true that the score from qsignature aren’t normalized by the number of SNPs, basically we are outputting the values the tool calculate. As well, we hard-code some cutoff to define samples, what is not good either for the same problem.

I agree that it would be good to have this in a better shape, but for that, we need data that we now what they are and then play with using the whole genome, only exomes, or less. And define a way to normalize the scores so it’s independent of number of SNPs.

Cheers

**Comment by ohofmann** [comment]
That's odd. I don't think qSignature changed in a long time -- how were those scores normalized before? I've only used it for WGS runs and some experimental exomes, and score distributions did differ a bit between the two technologies.

**Comment by gabeng** [comment]
Just to give you an example of the difference that I see between bcbio 1.0.3 and bcbio 1.0.6a, here the results from the same sequencing run that I repeated with both versions.

qsignature.xml from bcbio 1.0.3:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<qsignature>
<files>
<file coverage="9228" id="1" name="/bioinf-data/01_S1.qsig.vcf"/>
<file coverage="9292" id="2" name="/bioinf-data/02_S7.qsig.vcf"/>
<file coverage="9445" id="3" name="/bioinf-data/03_S13.qsig.vcf"/>
<file coverage="9300" id="4" name="/bioinf-data/04_S19.qsig.vcf"/>
<file coverage="9528" id="5" name="/bioinf-data/05_S25.qsig.vcf"/>
<file coverage="9508" id="6" name="/bioinf-data/06_S31.qsig.vcf"/>
<file coverage="9431" id="7" name="/bioinf-data/07_S37.qsig.vcf"/>
<file coverage="9519" id="8" name="/bioinf-data/08_S43.qsig.vcf"/>
<file coverage="9356" id="9" name="/bioinf-data/09_S2.qsig.vcf"/>
```

bcbio 1.0.6a:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<qsignature>
<files>
<file coverage="1220" id="1" name="/bioinf-data/01_S1.qsig.vcf"/>
<file coverage="1228" id="2" name="/bioinf-data/02_S7.qsig.vcf"/>
<file coverage="1552" id="3" name="/bioinf-data/03_S13.qsig.vcf"/>
<file coverage="1231" id="4" name="/bioinf-data/04_S19.qsig.vcf"/>
<file coverage="292" id="5" name="/bioinf-data/05_S25.qsig.vcf"/>
<file coverage="1244" id="6" name="/bioinf-data/06_S31.qsig.vcf"/>
<file coverage="291" id="7" name="/bioinf-data/07_S37.qsig.vcf"/>
<file coverage="1234" id="8" name="/bioinf-data/08_S43.qsig.vcf"/>
<file coverage="1545" id="9" name="/bioinf-data/09_S2.qsig.vcf"/>
```

**Comment by chapmanb** [comment]
Ben -- thanks so much for checking on this. I've looked through the history of qsignature (https://github.com/chapmanb/bcbio-nextgen/commits/master/bcbio/qc/qsignature.py) and I can't see any obvious changes here. The major changes have been swapping out parsing to avoid import errors but there hasn't been a new version of qsignature.

If you look at the qsignature command logs for the two versions in `log/bcbio-nextgen-commands.log` are there any differences in how it's invoked? Any ideas of how to start digging for differences would be really helpful. Thanks for the help debugging.

**Comment by lpantano** [comment]
And just to double check, I would check the BAM files are similar.

**Comment by gabeng** [comment]
We identified a bug in qsignature as the cause when using GRCh37 (instead of hg19). See this sourceforge thread: https://sourceforge.net/p/adamajava/discussion/general/thread/e9fdfc07/?limit=25#67b7

**Comment by chapmanb** [comment]
Ben -- thank so much for tracking this down. It sounds like we need to ping them about having a new release version of qsignature to fix the problem? It doesn't look like there are any new releases including Roland's patch at this point. Or have you found an alternative way to work around the issue? Thanks again for being on top of this.

**Comment by gabeng** [comment]
Brad,
I am not sure if qsignature has been fixed. I am using my own patched version. Closing this issue now, since you can do nothing about it. I will check out VerifyBamId when I have some spare time to see if it could be a replacement.
