### ISSUE TITLE
Chinese Hamster genome

### ISSUE THREAD

**Issue by drj11** [bcbio/bcbio-nextgen#2142]
we would like to add Chinese Hamster https://en.wikipedia.org/wiki/Chinese_hamster genome to bcbio.

Do you have any documentation of what's involved? and how much effort it might be?

**Comment by chapmanb** [comment]
David;
We have a script, `bcbio_setup_genome.py` which automates the process of installing a new genome in a bcbio installation given the sequence and transcripts:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#adding-custom-genomes

That's probably the best place to get started and hopefully will work fairly cleanly. Please let us know if you run into any problems.

**Comment by drj11** [comment]
That looks perfect!
