### ISSUE TITLE
can you support a yaml file of single-cell RNA-seq

### ISSUE THREAD

**Issue by hyystvar** [bcbio/bcbio-nextgen#2153]

**Comment by hyystvar** [comment]
I want to use bcbio pipeline for single-cell RNA-seq. But I cannot find a yaml script for it. can you support a template?

**Comment by roryk** [comment]
Hi @hyystvar,

What type of single cell are you looking to run? single-cell ends up being pretty complex because everybody uses different ways of inserting the cellular barcodes and what not, we might need to add support for your setup. If you can describe what you are trying to do we can help out getting set up to do it.

**Comment by hyystvar** [comment]
Thank you for you template!
And I have another questions. Is sample_barcodes necessary? If I donot put the parameter in the script, can it recognize the barcodes correctly?

**Comment by chapmanb** [comment]
You do need to specify the barcodes you're using since there is not a reliable way to detect these automatically from the sequences themselves. Hopefully if you discuss with the folks who ran the experiment that can help identify the UMI method used. Hope this helps.

**Comment by roryk** [comment]
Hi @hyystvar,

+1 on you have to figure out what method was used. Whether or not there are sample barcodes  depends on the chemistry you are using. Some chemistries do not have separate sample barcodes, others do. Some have only one set of cellular barcodes, and they can be anything, others have up to three from a pre-defined set. Some have the biological sequence on read 1. Some on read 2. Some it is combined with the UMI, etc, etc.

**Comment by roryk** [comment]
Asked and answered.
