### ISSUE TITLE
Cannot install bcbio

### ISSUE THREAD

**Issue by ybiobb** [bcbio/bcbio-nextgen#2174]
I got this error

$ python bcbio_nextgen_install.py /home/ipdat/bcbio --tooldir=/usr/local --genomes GRCh37 --aligners bwa
Checking required dependencies
Installing isolated base python installation
PREFIX=/home/ipdat/miniconda2
installing: python-2.7.14-hc2b0042_21 ...
Miniconda2-latest-Linux-x86_64.sh: line 353: /home/ipdat/miniconda2/pkgs/python-2.7.14-hc2b0042_21/bin/python: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 252, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    anaconda = install_anaconda_python(args)
  File "bcbio_nextgen_install.py", line 101, in install_anaconda_python
    (os.path.basename(url), anaconda_dir), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash Miniconda2-latest-Linux-x86_64.sh -b -p /home/ipdat/bcbio/anaconda' returned non-zero exit status 1

What is the problem?

**Comment by chapmanb** [comment]
Thank you for the report and sorry about the install issue. It seems like something maybe problematic about your initial miniconda download -- it should not be trying to install/work from `/home/ipdat/miniconda2`, instead it should have `/home/ipdat/bcbio/anaconda`. Do you have a partial/problematic install of miniconda in `/home/ipdat/miniconda2`? If so, you could try removing that. If not, could you remove `tmpbcbio-install` and re-run in case there is something corrupt about your miniconda installer? Hopefully either will work but if not could you paste a full traceback from running with a clear `tmpbcbio-install` so we can identify if something else is going on? Thanks for the help debugging.

**Comment by roryk** [comment]
Definitely is resolved, just not closed.
