### ISSUE TITLE
Include 3D PCA of genotypes as QC result

### ISSUE THREAD

**Issue by NeillGibson** [bcbio/bcbio-nextgen#2178]
Hi, 

Do you think it makes sense to include a 3D PCA of genotype results in the final QC output of each bcbio analysis?

For example the code below could be used. But also Plink or another piece of code more efficient than R could be used to craete the PCA matrix. 

The plotly 3D pca plot would like this, and would show sample sames up on hovering above each dot. 
https://plot.ly/~ptocca/19/_3d-pca/

This would for example be useful to detect sample swaps.  The 3D PCA could maybe go into the multiqc report. Or be a separate QC html output. 

Thank you. 

```
#Create a minimal VCF file, faster to parse.
bcftools annotate -x  FMT input.vcf.gz  -O v -o input_minimal.vcf.gz -za
 
# R code
library(gdsfmt)
library(SNPRelate)
library(plotly)
 
# Convert VCF to GDS
snpgdsVCF2GDS("input_minimal.vcf.gz", "input_minimal.gds")
 
# print summary of the creatd GDS file
snpgdsSummary("input_minimal.gds")
 
#open the GDS file
genofile <- openfn.gds("input_minimal.gds")
 
# Create the PCA table
sample.id <- read.gdsn(index.gdsn(genofile, "sample.id"))
pop_code <- read.gdsn(index.gdsn(genofile, "sample.id"))
RV <- snpgdsPCA(genofile, autosome.only=FALSE, num.thread=4)
pca<- data.frame(sample.id = sample.id, pop = factor(pop_code),EV1 = RV$eigenvect[,1],  EV2 = RV$eigenvect[,2],  EV3 = RV$eigenvect[,3],   stringsAsFactors = FALSE)
 
# Plot the 3D PCA
labels <- paste0(pca$sample.id)
 
p <- plot_ly(x = pca$EV1, y = pca$EV2, z = pca$EV3, text = labels)
p
```

**Comment by chapmanb** [comment]
Neill;
Thanks for the suggestion, this is a great idea and it would be really useful to include. My preferred way to include this would be directly within MultiQC which would involve generating outputs that we could push into a MultiQC plot, rather than including another output file/format. Is that something that seems do-able from your perspective?

A similar idea we've been discussing is predicting ethnicity of human sample inputs using reference panels, which would help flag swaps if you know ethnicities or flag outliers as due to being under-represented in the standard reference.

Thanks again for starting this discussion.

**Comment by NeillGibson** [comment]
Hi Brad. I would also prefer to have the 3D PCA in the MultiQC report if possible. 

I think the PCA matrix can be created with both Plink of SNPRelate in R.  I don't know if the plotyly output display of the 3D PCA matrix can easilly be included in MultiQC.  Maybe that would be a question for the MultiQC developers. 

I am btw fine with any tool to create the PCA matrix and to  visualize the 3D PCA. Which ever is easier to get the data into the mutliQC report. It would be extra nice if there was an option do dynamic zoom in and out in PCA display, to be able to zoom in to dense clustered together samples. 

Predicting the species and the strain would be very useful for us. 

For example `Rattus norvegicus` +  `ACI` .  Or `Rattus rattus` + `M520`.  
Sometimes very closely related individuals are sequences, so I am not sure this always helps. 
i.e. all samples are  `Rattus rattus` + `M520`, or  `Rattus rattus` + `M520` +  `Rattus rattus` + `M521` where there is almost no genotypic difference plus `M520` and `M521`.  In the last case it would also be difficult to predict a distinct `M520`  or `M521` strain label based on the genotypes. 

I am also wondering how to computationally predict the species + strain, and how computational difficult this is. 
 
For sure in some cases this would be very helpful.
