### ISSUE TITLE
UnboundLocalError: local variable 'target_bed' referenced before assignment

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2181]
This happened during `normalize_sv_coverage`. 

This happened in `regions.py` (https://github.com/chapmanb/bcbio-nextgen/blob/2876b8a889489ca8a265d5f2af490c6ea1d0f34c/bcbio/structural/regions.py#L207):

```python
for d in inputs:
            if tz.get_in(["depth", "bins", "target"], d):
                target_bed = tz.get_in(["depth", "bins", "target"], d)
                antitarget_bed = tz.get_in(["depth", "bins", "antitarget"], d)
```

Somehow `tz.get_in` is never true, so the following line, which references `target_bed` fails. Note: This is not a fully up to date pipeline but the code looks the same in the version I have (just a few lines of offset).

```
bcbio_nextgen.py --version
1.0.7a
```

**Comment by chapmanb** [comment]
Luca;
Thanks for the report and sorry about the issue. From reading the code I'm not sure why this would fail, it should always generate and add these files, in `calculate_sv_coverage`, for samples where we're running CNVkit. Would you be able to share your configuration that triggers this problem so we can try to reproduce? Thanks much.

**Comment by roryk** [comment]
Stale, and likely to not still be an issue, so closing it.
