### ISSUE TITLE
Converting GTF files to SAM RNA-seq pipeline 

### ISSUE THREAD

**Issue by kuikuisven** [bcbio/bcbio-nextgen#2187]
Dear all,

I m running the RNA seq pipeline on human data with Hisat2 on hg38 and after the mapping phase, cuffmerge seems to be blocked. 
This is the latest output I get and nothing os happening so far for 4 days:

```
[2017-12-14T21:53Z] [Thu Dec 14 22:53:26 2017] Beginning transcriptome assembly merge
[2017-12-14T21:53Z] -------------------------------------------
[2017-12-14T21:53Z] [Thu Dec 14 22:53:26 2017] Preparing output location /data/nrapin/test_RNA_seq/hiseq_info/work/bc
/cuffmerge/
[2017-12-14T21:53Z] [Thu Dec 14 22:53:40 2017] Converting GTF files to SAM

```

Digging into the logs in the cuff merge folder, I see this:

`/home/nrapin/bcbio/tools/bin/cuffmerge -o /data/nrapin/test_RNA_seq/hiseq_info/work/bcbiotx/tmpGrpkLd/cuffmerge --ref-gtf /data/nrapin/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf --num-threads 8 --ref-sequence /data/nrapin/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa /data/nrapin/test_RNA_seq/hiseq_info/work/bcbiotx/tmpFGrvmZ/tmpYR8vn8
sort -k 3,3 -k 4,4n --temporary-directory=/data/nrapin/test_RNA_seq/hiseq_info/work/bcbiotx/tmpGrpkLd/cuffmerge/tmp/ > /data/nrapin/test_RNA_seq/hiseq_info/work/bcbiotx/tmpGrpkLd/cuffmerge/tmp/mergeSam_fileyrJDVZ`

any help would be appreciated.

**Comment by roryk** [comment]
Hi Nicolas,

Sorry about that-- is the job still running on your cluster? There should be log files in the main directory that might tell you what is happening. That step shouldn't be taking that long.

**Comment by roryk** [comment]
Closing as this should be stale, and I'm Marie Kondoing the issues.
