### ISSUE TITLE
ChIP-Seq: new version of the pipeline does not support disambiguation with Bowtie2

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#2197]
Hi,
 I ran a ChIP-Seq analysis on 20 November using bowtie2 and disambiguation (hg19/mm10), and it worked. However, yesterday I ran a second ChIP-Seq analysis and the current version does not support botwie2 and disambiguation anymore. 
Is there a way to match botwie2 and disambiguation again? Unfortunately, I can not compare experiments analysed with two different approaches.

This is a side effect of the latest disambiguation revert.

Thanks

**Comment by chapmanb** [comment]
Laura -- thanks much for the report and sorry about the issue. Unfortunately the current behavior is the correct one and the `ngs_disambiguate` tool we use doesn't support bowtie2. It only handles tophat, hisat2, bwa and star so swapping over to either hisat2 or bwa would be the best possible fix at this point.

I'm sorry about the mistake in letting this through in your previous run. Looking at the ngs_disambiguate code I'm confused how it could have worked, they explicitly check for the supported aligners and should error out if not. Is it possible something errored out or is problematic about your old version?

Sorry again about the mistake and hope this helps.

**Comment by LMannarino** [comment]
Hi,
actually I don't remember any specific error with that run. However, I think I will analyze it again using the latest version of the pipeline and avoiding disambiguation.

Thank you.

Laura

**Comment by roryk** [comment]
Thanks, looks like this got resolved!
