### ISSUE TITLE
Bubbletree crashes bcbio

### ISSUE THREAD

**Issue by choosehappy** [bcbio/bcbio-nextgen#2211]
Bit strange, I’ve run bubbletree via bcbio (updated today) on 8+ samples from a cohort without error. 

Using the same installation, one of the samples kicks up an R error:

```
5 0.08823529 0.06496308      75 1.1485669384
6 0.10847154 0.06133024      68 1.2260297256
Error in if (uc.cov > 0.5 & uc.hds < 1/6 & cfg$high.ploidy) { : 
  missing value where TRUE/FALSE needed
Calls: btpredict -> btpredict -> getPloidyAdj -> getPloidyAdj
In addition: Warning message:
In limma::weighted.median(lrr, seg.size, na.rm = TRUE) :
  All weights are zero
Execution halted
' returned non-zero exit status 1

```

I put the contents of the respective /heterogeneity/PID/bubble directory here: 

https://www.dropbox.com/sh/5r40ns1fodwafzn/AAA1iq7GUL6PZMPRPGoMJkiXa?dl=0

Not urgent, but might need to be addressed for robustness

**Comment by chapmanb** [comment]
Thanks much for the report. For clarity, you ran the exact same analysis with the same inputs and code and it worked one time and failed the next? I didn't realize there was stochastic behavior built into BubbleTree. If this is the case we should try and discuss with the authors to see how we can avoid this in bcbio. If things changed between runs it would be useful to understand what happened so we can try to debug the fixes from the bcbio side. Thanks much for the help debugging this.

**Comment by choosehappy** [comment]
sorry that wasn't what i meant.

i used the pipeline on 8 samples, it worked successfully for 7 but produced the above error for the 8th.

rerunning produces the same error on the same sample (deterministically)

**Comment by roryk** [comment]
Thanks, this looks stale and hasn't been any action-- I think this is probably a non-problem now.
