### ISSUE TITLE
GATK4 GermlineCNVCaller

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2245]
Hi,

Did you by any chance already test the GermlineCNVCaller that is included in GATK4? 
And can it already be used from bcbio?   

The best practice documentation for germline CNV calling is still empty.
https://software.broadinstitute.org/gatk/best-practices/workflow?id=11148

According the gatk4-4.0.0.0-0 JAR file germline CNV calling tools are already included. 

```
java -jar ./gatk4-4.0.0.0-0/gatk-package-4.0.0.0-local.jar
USAGE:  <program name> [-h]--------------------------------------------------------------------------------------
Copy Number Variant Discovery:                   Tools that analyze read coverage to detect copy number variants.
    AnnotateIntervals                            (BETA Tool) Annotates intervals with GC content
    CallCopyRatioSegments                        (BETA Tool) Calls copy-ratio segments as amplified, deleted, or copy-number neutral
    CombineSegmentBreakpoints                    (EXPERIMENTAL Tool) Combine the breakpoints of two segment files and annotate the resulting intervals with chosen columns from each file.
    CreateReadCountPanelOfNormals                (BETA Tool) Creates a panel of normals for read-count denoising
    DenoiseReadCounts                            (BETA Tool) Denoises read counts to produce denoised copy ratios
    DetermineGermlineContigPloidy                (BETA Tool) Determines the baseline contig ploidy for germline samples given counts data.
    GermlineCNVCaller                            (BETA Tool) Calls copy-number variants in germline samples given their counts and the output of DetermineGermlineContigPloidy.
    ModelSegments                                (BETA Tool) Models segmented copy ratios from denoised read counts and segmented minor-allele fractions from allelic counts
    PlotDenoisedCopyRatios                       (BETA Tool) Creates plots of denoised copy ratios
    PlotModeledSegments                          (BETA Tool) Creates plots of denoised and segmented copy-ratio and minor-allele-fraction estimates
```

It would be nice to be able to run the GATK4 for both germline SNP and germline CNV calling in a single bcbio analysis. 

Thank you.

**Comment by chapmanb** [comment]
Thanks much for the suggestion. We'd like to work on support for GATK4's new CNV calling but haven't yet started working on it. Practically I'd been hoping for the tools to stabilize some and get documentation prior to investing the time into supporting.

As a solution until someone initiates working on integration we fully support CNVkit (http://cnvkit.readthedocs.io/en/stable/) for both germline and somatic CNV calling. It benefits from having multiple samples ideally in a case/control design to use a realistic, rather than flat, background. Hope this would work for your immediate analysis needs.

**Comment by WimSpee** [comment]
Hi Brad. Thank you very much for the information. I have tried CNVkit via bcbio in the past but couldn't get it to work on our data. I could try CNVKit again, with GATK4 GermlineCNVCaller I would at least have two methods that I could try to get working on our data. 

We have whole genome re-sequenced cohorts (100+ samples) in which we would like to discover and/or genotype copy number variation.  We don't always have case/control phenotypes for any, or fall all samples.  

I opened a ticket at GATK forum to ask them about the status of the GATK4 germline CNV tools and the best practices document:
https://gatkforums.broadinstitute.org/gatk/discussion/11344/current-status-of-gatk4-germlinecnvcaller-tools-and-best-practices

**Comment by chapmanb** [comment]
Thanks much for doing this. Improving WGS CNV calling, both through CNVkit and additional callers like GATK4's approach is definitely something we'd like to work on. I'll ping this issue as we improve things from our side and happy to hear about experiments as you're working on it. Thanks again.

**Comment by WimSpee** [comment]
Hi @chapmanb  @roryk 

The GATK4 GermlineCNVCaler tool documentation and documents describing the best practices are out. 

See the qouted accepted answers  that I got here. 
https://gatkforums.broadinstitute.org/gatk/discussion/11344/current-status-of-gatk4-germlinecnvcaller-tools-and-best-practices


> You can find the documentation here:https://software.broadinstitute.org/gatk/documentation/tooldocs/current/


> As for the best practices,
> 
> A more recent CNV tutorial using v4.0.1.1 has been posted in two parts here and here
https://software.broadinstitute.org/gatk/documentation/article?id=11682
https://software.broadinstitute.org/gatk/documentation/article?id=11683
> The first part mostly recapitulates the workflow on this page, while the second part adds detection of allelic ratios.
> 
> The official workflow has algorithmic improvements to the GATK4.beta workflow illustrated here.
https://software.broadinstitute.org/gatk/documentation/article?id=9143
> 
> A newer version should be available soon. Keep an eye on the tool docs section of GATK.

The whole genome GermlineCNVCaller pipeline looks like it could be wrapped in bcbio:
1. run GATK4 PreprocessIntervals  on the reference genome fasta to create a 1000bp interval file for the reference
2. for each bam file in the analysis create count file using the interval file (using GATK4 CollectReadCounts)
3. Run GATK4 DetermineGermlineContigPloidy to determine the baseline ploidy per chromosome for each bam file
4. Run the GermlineCNVCaller in cohort mode: Calls copy-number variants in germline samples given their counts (from CollectReadCounts ) and the corresponding output of DetermineGermlineContigPloidy. 

I am current trying to run this analysis using the GATK4 installed via the latest bcbio development version. 
I get stuck at step 3 (DetermineGermlineContigPloidy ) because the required `gcnvkernel ` python module is not installed in the bcbio GATK4 environment.

```
org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException:
python exited with 1
Command Line: python -c import gcnvkernel

Stdout:
Stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gcnvkernel'
```
The GATK4 readme on github describes how to install the  'gcnvkernel' module. 
https://github.com/broadinstitute/gatk/blob/master/README.md

> Python Dependencies:
> 
>     GATK4 uses the Conda package manager to establish and manage the Python environment and dependencies required by GATK tools that have a Python dependency. The gatk environment, requires hardware with AVX support for tools that depend on TensorFlow (e.g. CNNScoreVariant). The GATK Docker image comes with the gatk environment pre-configured.
>     To establish the environment when not using the Docker image, a conda environment must first be "created", and then "activated":
>         First, make sure Miniconda or Conda is installed (Miniconda is sufficient).
>         To "create" the conda environment:
>             If running from a zip or tar distribution, run the command conda env create -f gatkcondaenv.yml to create the gatk environment, or the command conda env create -f gatkcondaenv.intel.yml to create the gatk-intl environment.
>             If running from a cloned repository, run ./gradlew localDevCondaEnv. This generates the Python package archive and conda yml dependency file(s) in the build directory, and also creates (or updates) the local gatk conda environment. (To create the gatk-intel conda environment once the files have been generated, run the command conda env create -f gatkcondaenv.intel.yml).
>         To "activate" the conda environment (the conda environment must be activated within the same shell from which GATK is run):
>             Execute the shell command source activate gatk to activate the gatk environment, or source activate gatk-intel to activate the gatk-intel environment.
>         See the Conda documentation for additional information about using and managing Conda environments.

Can you advise on how to install the  'gcnvkernel' module within bcbio?
And maybe add this installation to the automatic bcbio installer? 

I am not sure which conda to use and also could not find the 'gatkcondaenv.intel.yml' or 'gatkcondaenv.yml'  files within the bcbio installation. 

Thank you very much for any help in getting GATK4 GermlineCNVCaller to work from the bcbio installation. (just as the executables, or as a bcbio pipeline)!

**Comment by WimSpee** [comment]
Hi @roryk  I was able to get the GAKT4 GermlineCNVCalling pipeline to work outside of bcbio. 

The GATK4 GermlineCNVCalling tools and documentation are good enough to get everything to work. 
Quite some scripting is needed though to run all the tools in the correct order and for when required in parallel for all the samples or for all the genome 'shards'. And then to reduce per chromosome or per sample results again to a single result. 

**So my immediate issue is fixed, I can run GATK4 GermlineCNVCaller outside of bcbio.** 
It still would be nice if it could be integrated into bcbio, at some time when it makes sense for you to do this, resource and priority wise. 

For this I can at least already share two of the things that I stumbled upon:

1. For the GATK4 gcnvkernel and all related python modules to work you currently need  a python 3.6.6 which is compiled with gcc 5.4.0,  . See issue  number 5766  on GATK4 github. 
2. The GermlineCNVCalling command needs to be run per 10Mb to 50Mb 'shard' of the reference genome. Each shard is still split further into 1 Kbp intervals, for which the read counts were also collected. Running a single GermlineCNVCalling  command over all the chromosomes does not finish, running many very small shards does not pick up any CNVs.

**Comment by amizeranschi** [comment]
Hi @WimSpee and @chapmanb,

By any chance, is there any update on supporting GATK's GermlineCNVCaller?

**Comment by amizeranschi** [comment]
The Broad institute appear to be working on this: https://gatk.broadinstitute.org/hc/en-us/articles/360035531152--How-to-Call-common-and-rare-germline-copy-number-variants

Does anyone have any experience with their `GermlineCNVCaller`?
