### ISSUE TITLE
Installation stalled

### ISSUE THREAD

**Issue by gnvalbuena** [bcbio/bcbio-nextgen#2273]
I've been following the instructions for ansible cloud usage on AWS running off an r4.2xlarge instance, and my bcbio install appears to have stalled. The last thing displayed has been

> Running GGD recipe: GRCh37 dbsnp 150-20170710-1
--2018-02-16 17:56:10--  ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/GATK/All_20170710.vcf.gz
           => ‘variation/dbsnp-150-orig.vcf.gz’
Resolving ftp.ncbi.nih.gov... 130.14.250.12, 2607:f220:41e:250::10
Connecting to ftp.ncbi.nih.gov|130.14.250.12|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /snp/organisms/human_9606_b150_GRCh37p13/VCF/GATK ... done.
==> SIZE All_20170710.vcf.gz ... 7554058973
==> PASV ... done.    ==> RETR All_20170710.vcf.gz ... done.
Length: 7554058973 (7.0G) (unauthoritative)
>
>All_20170710.vcf.gz 100%[===================>]   7.04G  18.1MB/s    in 6m 39s  
>
>2018-02-16 18:02:51 (18.1 MB/s) - ‘variation/dbsnp-150-orig.vcf.gz’ saved [7554058973]

And there has been nothing for an hour since then. Is this expected?

**Comment by chapmanb** [comment]
Thanks for the question. If you look at `top` on the machine, are there processes running? In this step it needs to gunzip and re-prepare the VCF file (bgzipped and indexed), so can take a while. Depending on the machine type you're using an hour isn't unusual. It's worth checking to see if things are running to confirm, but the install shouldn't hang/stall and we'd expect it to error out if something problematic happened. Hope this helps.

**Comment by gnvalbuena** [comment]
I seem to have regressed and have come up to a different issue. Now unable to use an instance from bcbio.

when I enter `ansible-playbook -i 'localhost,' -vvv launch_aws.yaml `, it starts making the instance, and then hits this error at the end:

```
PLAY [launched] *************************************************************** 

TASK: [raw sudo apt-get update && sudo apt-get -y install python-simplejson] *** 
<xxx-west-1.compute.amazonaws.com> ESTABLISH CONNECTION FOR USER: ubuntu
<xxx.eu-west-1.compute.amazonaws.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/gabriel/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 xxx.eu-west-1.compute.amazonaws.com sudo apt-get update && sudo apt-get -y install python-simplejson
The authenticity of host 'xxx.eu-west-1.compute.amazonaws.com (52.213.9.57)' can't be established.
ECDSA key fingerprint is xxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [xxx.eu-west-1.compute.amazonaws.com] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/gabriel/launch_aws.yaml.retry

xxx.eu-west-1.compute.amazonaws.com : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=5    changed=1    unreachable=0    failed=0 
```

When I check my ec2 dashboard, it does actually start an instance, but when I try to ssh into it, it won't let me in. I get 

>Permission denied (publickey).

I've tried recreating my keypairs, recreating vpc, but those haven't worked.

**Comment by brainstorm** [comment]
Which ssh command are you using to try to log into it manually? Are you using `ubuntu@` as user or sth else like `ec2-user`?

**Comment by chapmanb** [comment]
Sorry about the connection issues. These are a bit difficult to diagnose remotely but my guess is that there is a mismatch between the key referenced in your ansible `project_vars.yaml` file and the local key that you reference in your `.ssh/config`:

https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible#amazon-web-services

Sorry I know this process is a bit manual, but it's likely one of those keys changed so they're no longer synced, leading to the inability to connect. Hope this helps explain the problem.

**Comment by roryk** [comment]
Should be solved, just the issue wasn't closed. Thank you!
