### ISSUE TITLE
Problem with the reference genome files when submitting for parallel execution on SGE

### ISSUE THREAD

**Issue by Wixaros** [bcbio/bcbio-nextgen#2277]
Hi, first of all, thank you for all the amazing help you have provided me with. Now we once again have a running pipeline, using multicores on a single machine, however I'm having some problems with the parallel execution step that tries to download the hg19 reference genome, although it has been installed.

Our code for submitting:
`bcbio_nextgen.py ../config/test4.yaml -t ipython -s sge -q all.q -r h_vmem=5.3G -r pename=smp -n 24 >> logging.txt 2>&1 &`

It is a SGE cluster, and it queues fine and begins to run, however it then tries to download the reference genome and fails because the clusters are not connected to the internet. However, submitting the following script with `qsub`:
```
#$ -S /bin/sh
#$ -l h_vmem=5.3G
#$ -pe smp 12
#$ -cwd
bcbio_nextgen.py ../config/test4.yaml -n 12
```

runs fine on just one of the nodes, and detects everyting.

Attached is the log file from the run, the .yaml-file, the ip-log files, and the bcbio logs
[bcbio-nextgen.log](https://github.com/chapmanb/bcbio-nextgen/files/1736331/bcbio-nextgen.log)
[bcbio-nextgen-debug.log](https://github.com/chapmanb/bcbio-nextgen/files/1736332/bcbio-nextgen-debug.log)
[ipcluster-981def71-6376-4a9f-b52e-7de90627ddcb-12225.log](https://github.com/chapmanb/bcbio-nextgen/files/1736325/ipcluster-981def71-6376-4a9f-b52e-7de90627ddcb-12225.log)
[ipcontroller-981def71-6376-4a9f-b52e-7de90627ddcb-25767.log](https://github.com/chapmanb/bcbio-nextgen/files/1736326/ipcontroller-981def71-6376-4a9f-b52e-7de90627ddcb-25767.log)

[bcbio-e.o25016.1.txt](https://github.com/chapmanb/bcbio-nextgen/files/1736320/bcbio-e.o25016.1.txt)
[test4.yaml.txt](https://github.com/chapmanb/bcbio-nextgen/files/1736312/test4.yaml.txt)
[logging.txt](https://github.com/chapmanb/bcbio-nextgen/files/1736306/logging.txt)

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issues. bcbio tries to do the reference data download as a last resort when it can't find it present locally. Given your description of the issue and when it runs and doesn't, my best guess is that there is different availability of the reference genomes on different nodes in your cluster. Is it possible that on the failing run machine (`compute-21-3.local`) the paths to bcbio and the reference data, which appear to be:
```
/state/partition1/apps/local/share/packages/bcbio
```
are different than when you run with single job submission?

Hope this helps some with identifying the issue.

**Comment by Wixaros** [comment]
Hi again

Well, the .loc files all point to the correct path, however, the path being `/usr/local/share/packages/bcbio/etc`. We had a similiar problem with the single node setup, when bcbio gets installed by the admin (#2219) however we solved this by changing all the .loc files and it runs like a charm. However, submitting through `bcbio_nextgen.py` directly, it then seems, based on you comment that it looks at `/state/partition1/apps/local/share/packages/bcbio` instead, and from the calculation nodes this can't be reached. Can we modify bcbio primary lookup to look in `/usr/local/share`?

Best

Nicolai

**Comment by chapmanb** [comment]
Nicolai;
In general you'll have to change the bcbio .loc files to point at a path that is consistently accessible across your cluster machines. I don't have a full picture of your setup and accessible paths on different machines, but is there any consistent path you can always ensure exists? Hope this would work for your cluster setup.

**Comment by roryk** [comment]
This is a cluster-specific problem, and Brad's answer is spot on. Should be fixed, so closing. Thank you!
