### ISSUE TITLE
Standardization of use of sample and analysis names in all bcbio final output files. 

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2290]
Hi, 

The final output files that we get from bcbio analysis we store in an object store and some of them we then load into diverse end user facing applications. In some of these applications end users search or select based on the file names (or actually the files that match with their analysis ID or sample name). 

Some of these output files include the sample and / or the analysis (batch)ID in the file names.
For example:
- BAM file names always include the sample name (e.g. `DA_1083_05-ready.bam`)
- Joint VCF files always include the analysis ID (e.g. `DA_1090-gatk-haplotype-annotated.vcf.gz`)

It would be nice if a standard naming scheme could be used for all sample level or analysis level output files. 

The situation could for example be improved in the output or RNAseq analysis:
- The feature counts file already includes the sample name (e.g. `DA_1083_05-ready.counts`)
- The Salmon file does not yet include the sample name but always is named `quant.sf`
- Per sample GTF files are just called `stringtie-assembly.gtf` or `cufflinks-assembly.gtf` without use of sample names
- The merged analysis GTF files is called `assembled.gtf` without the analsysis ID. 

We could also do this in our code before pushing the files to the object store. But it might also make sense to have the sample names and analysis IDs already included in bcbio generated output file names. 

Please let me know what you think. Thank you.

**Comment by chapmanb** [comment]
Thanks much for this discussion. Renaming some of the RNA-seq outputs to be more consistent with sample and project/batch naming makes a lot of sense. @roryk, what do you think about adding sample identifiers to these outputs? There is always a concern with breaking downstream scripts that expect certain names but normalizing these some would help a lot to avoid confusion.

**Comment by roryk** [comment]
Thanks, sorry for not responding. I agree it stinks the way it is. Some downstream tools need the files named in a certain way and some don't. Standardizing this would be good, but is likely to open up a host of other problems. I think I'm down for leaving it as is, despite the fact it is gross.
