### ISSUE TITLE
Support for organisms with large chromosomes up to current BAM spec (=2.1GigaBase)

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2295]
Hi, 

I am currently processing re-sequencing data against 2 organisms that have a chromosome with a lenght above the older BAM specification limit of 2^29 (=536,870,912). 

BWA mem alignment works fine via bcbio but some other tools and aspects of the bcbio code do not yet support the current BAM specification chromosome size  limit of 2^31 (=2,147,483,648).

See also the current BAM specification page 5, section 1.4 The alignment section: mandatory fields
https://samtools.github.io/hts-specs/SAMv1.pdf

Specifically I ran in to 2 issues: 

biobambam2 input checks (is now fixed ): 
https://github.com/gt1/biobambam2/issues/66

samtools index needs CSI index instead of BAM index
https://github.com/samtools/samtools/issues/241

The bcbio samtools BAI index process currently fails silently, but subsequent `mosdepth` fails on the incomplete BAI index. 
```
CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 16 -F 1804 -Q 1 --no-per-base --by /data/run/Projects/
/DA-1115/DA_1115_samples-merged/work/coverage/SXS_102294_04/target-genome.bed --quantize 0:1:4: /data/run/Projects/DA-1115/DA_1115_samples-merged/work/bcbiotx/tmp1qwaAe/SXS_102294_04-variant_regions /data/run/Projects/DA-1115/DA_1115_samples-merged
/work/align/SXS_102294_04/SXS_102294_04-sort.bam
index not found for:/data/run/Projects/DA-1115/DA_1115_samples-merged/work/align/SXS_102294_04/SXS_102294_04-sort.bam
' returned non-zero exit status 2
```

I am not sure how many other tools still implement the  2^29 limit in some way or are incompatible with CSI indexes. A lot / most tools nowadays depend on HTS-JDK/HTSLIB for reading BAM files so they should support CSI indexes?

Do you think it is possible to update the bcbio code to generate CSI index files, by default, or for BAM files on references with large chromosomes?

Thank you very much.

**Comment by WimSpee** [comment]
The first issue with biobambam2 is already fixed. Could you please also use this updated biobambam2 version in bcbio. Thank you.

**Comment by WimSpee** [comment]
Mhm, HTSJDK does not yet seem to support CSI indexes.
https://github.com/samtools/htsjdk/pull/980 

At least according to this pull request.....

**Comment by chapmanb** [comment]
Thank you for this discussion and all the work testing out various tools. We'd be happy to support this but practically haven't worked with larger genomes so don't know all of the ins and outs of the tools. All of the main team's day to day work is on human or human-like genomes so we haven't ventured into this area. 

I'll definitely update biobambam to the most recent release with your fixes and we can start to think about ways to support CSI indices. As a first pass my thought would be to generate these instead of bai based on the reference genome size -- perhaps we can infer directly from the fai file sizes. We'd be happy to accept contributions for this or can try to allocate time to work through it and the issues.

Thanks again for starting this discussion and all the work so far.

**Comment by WimSpee** [comment]
Hi Brad. Thank you for your thoughts on this. Without HTS-JDK support for CSI indexes there is for instance no GATK or IGV support for BAM files with CSI indexes. (and probably also no support from all/most other bioinformatics software that runs on the JVM)

So I think it might be better to wait here until HTS-JDK supports CSI indexes. Until then I'll probably just split the chromosome in to 2 pieces as a workaround ......

Since HTSLIB support CSI indexes since 2014 I assumed HTS-JDK would also support it by now.

**Comment by chapmanb** [comment]
Thanks for this, I'm agreed that getting the tooling to support the indices should be step one and then we can look to generate them automatically as part of bcbio. I updated the bioconda package to the latest biobambam build so we should have support on that side, and can continue to update tools as they gain support. Thank you again for driving this and please let us know what else we can do to help.

**Comment by roryk** [comment]
Thanks, closing for now as it seems we've stalled on it but made some progress. re-open if there is still some action going on please.
