### ISSUE TITLE
Skipping GATK BaseRecalibrator because no VCF file of known variants was found.

### ISSUE THREAD

**Issue by alongalor** [bcbio/bcbio-nextgen#2300]
Hi,

I noticed this notice: `Skipping GATK BaseRecalibrator because no VCF file of known variants was found.` in my `bcbio-nextgen-debug.log` file and realized it must be because I am using a custom genome (hs37d5), as specified in my template (
[PreProcessing-template.yaml.txt](https://github.com/chapmanb/bcbio-nextgen/files/1772710/PreProcessing-template.yaml.txt)
which includes 3 folders in its directory (`/bcbio/share/bcbio-nextgen/genomes/hs37d5/hs37d5`) : `bcbiotx  bwa  seqdoes` - not including the `variation` directory which exists in the GRCh37 directory (`bcbio/share/bcbio-nextgen/genomes/Hsapiens/GRCh37`).

I was wondering if it would be sufficient to just copy over the `variation` folder into my `/bcbio/share/bcbio-nextgen/genomes/hs37d5/hs37d5` directory to avoid the `Skipping GATK BaseRecalibrator because no VCF file of known variants was found.` issue? Also, following Alignment and Alignment postprocessing, I will be performing variant calling. Are there any other directories that I should copy over to the `/bcbio/share/bcbio-nextgen/genomes/hs37d5/hs37d5` directory to avoid any such issues where a pipeline stage is skipped? 

Also, I was wondering if there is any way to still perform BQSR on these files as I intended without starting the pipeline again from scratch after copying the `variation` directory into `/bcbio/share/bcbio-nextgen/genomes/hs37d5/hs37d5`, assuming that is the only thing I have to do to avoid future complications.

Thanks so much,

Alon

P.S. I installed hs37d5 using the following command: `bcbio_setup_genome.py -f /n/data1/hms/dbmi/park/alon/software/gatk/human_g1k_v37_decoy.fasta -i bwa -n hs37d5 -b hs37d5
`

**Comment by chapmanb** [comment]
Alon;
Sorry about the issue with this. GATK's recalibration does require a dbSNP file. Copying over the variation directory and then specifying it in the resources YAML file will make it available:

https://github.com/chapmanb/bcbio-nextgen/blob/8e2859ed80d501008e27fab493bf0f1871e922d5/config/genomes/GRCh37-resources.yaml#L9

If you're doing VQSR you'll also need the training data for that as well. Beyond that, you might want the a transcript GTF file for annotations of structural variant calls:

https://github.com/chapmanb/bcbio-nextgen/blob/8e2859ed80d501008e27fab493bf0f1871e922d5/config/genomes/GRCh37-resources.yaml#L25

and that should provide most of what you need. Hope this helps and please let us know if you run into any other issues.

**Comment by alongalor** [comment]
Hi Brad, thanks a lot for your help!

To be safe would you recommend just copying all the directories in `bcbio/share/bcbio-nextgen/genomes/Hsapiens/GRCh37`, with the exception of `seq` to `/bcbio/share/bcbio-nextgen/genomes/hs37d5/hs37d5`?

Thanks again!

Alon

**Comment by chapmanb** [comment]
Alon -- some of the other directories like aligner and ucsc indices, match the reference genome being used so I wouldn't copy/symlink everything. Some of the additional directories like coverage and validation are more for convenience but wouldn't hurt to copy/symlink if they're useful and match the genome reference you're using. Hope this helps.

**Comment by alongalor** [comment]
Very helpful, Brad. Very much appreciated! All the best, Alon

**Comment by roryk** [comment]
This was answered, so closing. Thank you!
