### ISSUE TITLE
Upgrading Issue SSL Protocol

### ISSUE THREAD

**Issue by TheGatsbyofMars** [bcbio/bcbio-nextgen#2305]
Hello, 

I'm trying to update bcbio to the latest development using the below command. Even though I never had trouble with upgrading, this time I'm running into this issue. I searched for this issue and apparently this issue relates to git (below). What can I do to upgrade to development ? Thanks for all your hard work. 

https://githubengineering.com/crypto-removal-notice/

one@login0:~>`bcbio_nextgen.py upgrade -u development`
Upgrading bcbio

# All requested packages already installed.
# packages in environment at /home/one/bcbio/anaconda:
#
bcbio-nextgen             1.0.9a                   py27_4    bioconda
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/one/bcbio/anaconda:

The following NEW packages will be INSTALLED:

    libgcc-ng: 7.2.0-h7cc24e2_2

Upgrading bcbio-nextgen to latest development version
Collecting bcbio-nextgen from git+https://github.com/chapmanb/bcbio-nextgen.git#egg=bcbio-nextgen
  Cloning https://github.com/chapmanb/bcbio-nextgen.git to /tmp/pip-build-xy6xB0/bcbio-nextgen
fatal: unable to access 'https://github.com/chapmanb/bcbio-nextgen.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Command "git clone -q https://github.com/chapmanb/bcbio-nextgen.git /tmp/pip-build-xy6xB0/bcbio-nextgen" failed with error code 128 in None
Collecting bcbio-nextgen from git+https://github.com/chapmanb/bcbio-nextgen.git#egg=bcbio-nextgen
  Cloning https://github.com/chapmanb/bcbio-nextgen.git to /tmp/pip-build-aCbCLM/bcbio-nextgen
fatal: unable to access 'https://github.com/chapmanb/bcbio-nextgen.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Command "git clone -q https://github.com/chapmanb/bcbio-nextgen.git /tmp/pip-build-aCbCLM/bcbio-nextgen" failed with error code 128 in None
Traceback (most recent call last):
  File "/home/one/bcbio/tools/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/one/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 63, in upgrade_bcbio
    "git+%s%s#egg=bcbio-nextgen" % (REMOTES["gitrepo"], git_tag)]], anaconda_dir)
  File "/home/one/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 118, in _pip_safe_ssl
    subprocess.check_call(cmd)
  File "/home/one/bcbio/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/one/bcbio/anaconda/bin/pip', 'install', '--upgrade', '--no-deps', 'git+https://github.com/chapmanb/bcbio-nextgen.git#egg=bcbio-nextgen']' returned non-zero exit status 1

Thanks,

Ali

**Comment by roryk** [comment]
Hi Ali,

What version of git are you running? (`git --version`). I think this is an issue with some outdated versions of git; if you upgrade to a newer version, does it fix this issue?

**Comment by TheGatsbyofMars** [comment]
I'm using version git version 2.9.3
I've done upgrades before and never had a problem, but for some reason I'm getting this error now .
I got the same error when trying to upgrade git 
fatal: unable to access 'https://github.com/git/git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by roryk** [comment]
Gotcha-- huh.  It might be worth pinging the sysadmin folks on your cluster and asking if anything changed. Having the git problem as a test case would be helpful.

**Comment by TheGatsbyofMars** [comment]
I'll do that and get back to you 

Much appreciated 👍

**Comment by roryk** [comment]
Thanks! Let us know what the resolution is.

**Comment by roryk** [comment]
Closing as there hasn't been any action.
