### ISSUE TITLE
Unclear sv-prioritize output

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#2307]
cc @lbeltrame 

Hi,
 I have a question regarding the sv-prioritize output (e.g. samplename-sv-prioritize.tsv).

I attach here the first line of the file with the header.

[ex_bcbio_issue.txt](https://github.com/chapmanb/bcbio-nextgen/files/1780439/ex_bcbio_issue.txt)

What is unclear to me is how to interpret the output: "lof" (loss of function) refers to multiple genes which actually belong to that region, however in the "annotation" column it has been reported only the deletion of the exon of LRRC47 gene. Which is the real deletion?

Thanks

**Comment by chapmanb** [comment]
Laura -- thanks for the question. The `annotation` column is the initial report on the event from snpEff and the `lof` column is our attempt during prioritization to make it more complete. The actual event that CNVkit is calling is quite large (2Mb) so covers multiple genes. snpEff often just reports likely events around the end points to avoid incredibly large output lines for larger deletion type events. So the real deletion affects all the genes listed in `lof` while the endpoint hits in the `LRRC47` gene mentioned in `annotation`. Hope this helps.

**Comment by LMannarino** [comment]
Hi Brad,
 now it's clear.

Thank you so much.
