### ISSUE TITLE
Mutect2: error

### ISSUE THREAD

**Issue by lemdcock** [bcbio/bcbio-nextgen#2309]
Dear B. Chapman, 

I was trying to run Mutect2 in combination with CNVkit and TitanCNA. However this resulted in a rather large error output from Mutect2, I'll include the first part. Note I'm using GATK v3.8, for comparison with prior results. 

First part of error output:
```
[2018-03-05T12:02Z] Filtering MuTect2 calls with allele fraction threshold of 0.1
Traceback (most recent call last):
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 146, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 194, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
joblib.my_exceptions.JoblibValueError: JoblibValueError
___________________________________________________________________________
Multiprocessing exception:
```

My input yaml was: 
```
#!yaml
---
details:
  - analysis: variant2
    description: sample-1
    files:
      - sample-1.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: mutect2
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: tumor
  - analysis: variant2
    description: sample-2
    files:
      - sample-2.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: mutect2
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: normal
upload:
  dir: /home/lemdcock/output/
```

**Comment by lemdcock** [comment]
Is it a problem with my version of GATK or is there another underlying problem, for instance my system configuration? 

Kind regards,
Laurenz

**Comment by chapmanb** [comment]
Laurenz;
Thanks for the report and apologies about the issue. Unfortunately the traceback you posted doesn't have enough information to let us diagnose the underlying error. Would you be able to post the full traceback from `log/bcbio-nextgen.log` as a gist (https://gist.github.com/) and link to it from here? That might give us some idea how to diagnose what is going on. Thanks for the help debugging.

**Comment by lemdcock** [comment]
Dear B. Chapman, 

I've created a gist with the entire error. I hope it helps. My apologies for the delayed reply.
https://gist.github.com/lemdcock/718afaa52ce2fff075496e5c2a6e8833

Let me know of the link does not work, then I will try something else. 

Kind regards,
Laurenz

**Comment by chapmanb** [comment]
Laurenz;
Thanks for the detailed error message. It looks like we're running into an issue with your pre-aligned BAM files, specifically we're not finding `sample-1` in the pre aligned `sample-1.bam` file. If you do:
```
samtools view -H sample-1.bam | grep RG
```
what does it report? bcbio should be checking for issues with mismatching read group and sample names but is missing your case somehow.

If you match `description` to the input BAM file sample name in SM or specify `bam_clean: fixrg` that should hopefully avoid the issue. Hope this helps some with identifying the issues.

**Comment by lemdcock** [comment]
Dear B. Chapman, 

I tried the command you suggested and this resulted in the following output: 
‘‘‘
@RG	ID:sample-1	SM:sample-1	PU:run-1	PL:illumina
‘‘‘
This is thus correct and should not give any errors. I am however working with a symlink, could this result in an error? 

If not, I could still try to run Mutect2 with the ‘‘‘bam_clean: fixrg‘‘‘ option and see whether for now that fixes the issue. 

Kind regards, 
Laurenz

**Comment by chapmanb** [comment]
Laurenz;
Thanks for confirming that the sample looks as expected.  I'm not 100% sure how GATK3 generates a problematic VCF here but modified the code to avoid failing when the sample is missing. If you update to the latest development and re-run in place it should hopefully work for you. Thanks again for the help debugging.
