### ISSUE TITLE
Small RNA pipeline

### ISSUE THREAD

**Issue by ahsen1402** [bcbio/bcbio-nextgen#2311]
Hi All,

First thanks for this great tool. I have just discovered it. I would like to run the smallRNA pipeline but I am confused with the parameters to set. Per my library preparation i need to run the following command:

cutadapt -m 15 -u 3 -a AAAAAAAAAA input.fastq > output.fastq

Basically, trim the first 3 bases from 5' end and remove the polyA tail from the 3'. I think the atropos trimmer in the bcbio is fully compatable with cutadpt so that same parameters would run perfectly with it. But I am not sure how to specify these parameters in the configuration file? I think the 'trim_ends' parameter is what I am looking for but it is mentioned that it is Only implemented for variant calling pipelines. Any help is appreciated. If this is not possible is there a way to skip trimming for the smallRNA pipeline if I wish to input already trimmed reads? Thanks in advance.

**Comment by lpantano** [comment]
Hi,

Thanks for giving it a try. 

One question first, normally there is a 3’ end adapter that you need to remove, that is normally what ever primer used during library preparation. That is where normally adapter parameter is used to. And this is the first trimming the pipeline will do. If you want to add something after that step, you can use resources option and add

resources:
  atropos:
    options: [“-u 3 -a AAAAAAAAA"]

Mentioned here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#smallrna-sequencing <https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#smallrna-sequencing>

But you need to specify adapters option if you have another adapter at 3’. Or you can specify this AAAAAAAAAA as the adapter to remove. 

However you can skip trimming, just not adding `adapters` and `trim_reads` in the yams file.

Hope this helps. Let me know if not.

Cheers

**Comment by ahsen1402** [comment]
Many many thanks for the help. According to http://www.clontech.com/xxclt_ibcGetAttachment.jsp?cItemId=117292 slide number 14, if you remove the polyA tail the adapters are removed automatically, please correct me if I am wrong. I am still trying to install the bcbio package and will see how it goes. By the way great tool seqcluster, just a question the required annotation/genome files come with the bcbio installation or do you have them somewhere? (I checked the mirRQC data you presented and would like to replicate in on my data)

**Comment by lpantano** [comment]
The seems right. If that is what they used as the primer, then you can put that in the `adapters` option and the other in the resources and it should work.

As a note, this will mean sometimes you will remove real nts for the miRNA sequences. I don’t know if you are really aware of isomiRs, but one of the main modification that happens is addition of A or U at the end of the sequences. In this case, you will detect Us additions with bcbio but As addition will be removed if the protocol is using this as the adapter.

For seqcluster, if you are using human or mouse, sure thing, It comes with bcbio.

As well, be aware of this: https://github.com/lpantano/bcbioSmallRna <https://github.com/lpantano/bcbioSmallRna>

It is meant to work with the output of bcbio small RNAseq pipeline.

Cheers

**Comment by ahsen1402** [comment]
Thanks a lot for help. After a lot struggle I installed and tried using this unfortunately after fastqc, i got the error I opened #2335 do you have any guidance on that?

Thanks
