### ISSUE TITLE
can't find the file "hg38-noalt-twobit.tar.xz" on s3

### ISSUE THREAD

**Issue by jich-MCTP** [bcbio/bcbio-nextgen#2312]
Hi,

I try to download hg38-noalt data via the command line:
bcbio_nextgen.py upgrade  --genomes hg38-noalt --datatarget gemini

On the screen I found one message:
...
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: wget --continue --no-check-certificate -O hg38-noalt-twobit.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-noalt-twobit.tar.xz'
--2018-03-05 20:11:45--  https://s3.amazonaws.com/biodata/genomes/hg38-noalt-twobit.tar.xz
Resolving s3.amazonaws.com... 52.216.230.29
Connecting to s3.amazonaws.com|52.216.230.29|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-05 20:11:45 ERROR 404: Not Found.

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O hg38-noalt-twobit.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-noalt-twobit.tar.xz''

INFO: Moving on to next genome prep method after trying s3
Failure to retrieve remote file: https://s3.amazonaws.com/biodata/genomes/hg38-noalt-twobit.tar.xz
INFO: Preparing genome hg38-noalt with index twobit
...

But the data seems to download to local, can I skip this error message?

Thanks!

**Comment by chapmanb** [comment]
Sorry about the confusing message. That is fine to ignore, bcbio tries to download pre-built indices and if they don't exist than falls back to generating locally so everything is as expected. Please feel free to reopen if you run into any issues.
