### ISSUE TITLE
GATK4 GenotypeGVCFs: allow in YAML user defined 'max_alternate_allele' parameter

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2315]
Hi, 

Would it be possible to allow user defined `GATK4 GenotypeGVCF` `max_alternate_allele`' setting in the bcbio YAML?

The default value `GATK4 GenotypeGVCF` `max_alternate_allele=6`  setting runs too slow for some of our species and cohorts and even incoming batches of samples. Lowering this parameter improves variants/per minute significantly and decreases memory requirement also significantly.  

I also noticed that for `GATK3 GenotypeGVCFs`  this parameters already is hard coded to `max_alternate_allele=4 in bcbio:
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/gatkjoint.py#L105

Could you share thoughts on the optimal setting of this parameter. We are still exploring the optimal performance cost and sensitivity trade off of this parameter.

Thank you.

**Comment by WimSpee** [comment]
Hi @chapmanb . I also opened a forum post at GATK about the slow performance about GenotypeGVCFs at `max_alternate_allele=6`. 

https://gatkforums.broadinstitute.org/gatk/discussion/11471/performance-troubleshooting-tips-for-genotypegvcfs/p1

This post has now been escalated to a developer ticket (see last few comments of the forum post).

It turns out hat using the `-new-qual` optoin with GATK4 GenotypeGVCFs improves the performance a lot. Even with `max_alternate_allele=6`, which is the GATK4 default.

Hopefully Sheila in that forum post can confirm there are now downsides to that option.

So instead of making `max_alternate_allele` user configurable in bcbio, it might be better to implement `-new-qual` as a user configurable or default option for GATK4 GenotypeGVCFs. 

Thank you.

**Comment by chapmanb** [comment]
Thanks much for your work diagnosing the issue and discussing with the GATK4 team. I swapped over to use the newer quals option as a default, which is an umabiguous win here. I've tested the new qualities in the past and they validated great but I believe the GATK team decided to stick with the older as default to try and match GATK3 as much as possible.

Please let us know if you run into any scaling issues after the change. Thanks again.
