### ISSUE TITLE
CWL: add support for Cromwell runner

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2317]
Hi Brad,

Are you planning to add support for Cromwell and/or WDL to the bcbio_vm.py script? Cromwell seems to be compatible with both WDL and CWL now, and supports a lot of different back ends, which makes it a good candidate IMO.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
We definitely plan to support Cromwell when their work on CWL support is ready. We've been discussing closely with the Cromwell team and they're testing with the bcbio CWL workflows, so on our side we're waiting patiently. When it's available we'll absolutely plan to wrap into bcbio_vm.py and test support.

**Comment by matthdsm** [comment]
Allright! Great to hear!

Thanks for all the work on this!
Cheers
M
