### ISSUE TITLE
RFE: Copy CNVkit background cnn to upload directory

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2318]
Rationale: it's useful when you're building "shared references" to be later re-used. I just did this for 51 samples and I'd rather not redo the whole thing again. ;)

I assume it's the file called `background-0-cnvkit.cnn` present in the sample directories under `structural`?

**Comment by chapmanb** [comment]
Luca -- thanks much for the suggestion. The latest development version now outputs this file as `batch-cnvkit-background.cnn` so it will be available for later re-use. Thanks again for the idea and please let us know if you run into any issues.
