### ISSUE TITLE
RFE: Rename -scatter.pdf CNVkit plot file to show it refers to svprioritize

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2319]
cc @LMannarino

I found this to be the case because I was looking at a freshly-finished run and noticed that the scatter plots were referring to genes present in the `svprioritize` panel I had chosen.

`-scatter.pdf` isn't terribly helpful on what it contains, perhaps `-scatter-prioritize-regions.pdf` or something similar might be more useful.

**Comment by roryk** [comment]
Thanks, agree our naming could be better but we're unlikely to do this so closing.
