### ISSUE TITLE
Specifying sample-specific ref genome files

### ISSUE THREAD

**Issue by RiNiculous93** [bcbio/bcbio-nextgen#2320]
Having some difficulty with our cluster's latest install of 1.0.8: bcbio being unable to locate the reference genome files. I've noticed this problem posted a few times and none of the solutions have applied to me so far. I've requested our system architect takes a look as I don't have permissions to alter the installation, but this could take some time. 

In the meantime, is it possible for me to download the required reference genome files locally and point to them in the sample.yaml?

If this is possible, how would I go about this? 

FYI this is the error I'm trying to get around, it's been posted before, if there's any obvious issue you can see please let me know. 

<img width="1270" alt="screen shot 2018-03-07 at 11 33 33" src="https://user-images.githubusercontent.com/25953685/37156893-3c786f7c-22df-11e8-82c2-26574c38bc4a.png">

Thanks so much.

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. It's a bit tough to debug this remotely without understanding your installation and what went wrong. The likely problem is that your bcbio installation is missing references to the genome data locations in the `loc` files under galaxy. If you're able to supply more details about the installation that could probably point us in the right direction.

bcbio does not require any root privileges so could be installed outside of your packaged environment into any directory you have install rights and sufficient space if you need a workaround.

Hope this helps.

**Comment by roryk** [comment]
Thanks, this is stale and should be a non-bcbio related problem, so closing.
