### ISSUE TITLE
optitype dependency missing (fixed)

### ISSUE THREAD

**Issue by choosehappy** [bcbio/bcbio-nextgen#2324]
after using upgrade -u development had a similar behavior as to #2136 and i used the same procedure to debug

i got this error:

```
root@cbc6fb3a9444:/tmp/opti# OptiTypePipeline.py -v --dna -o test_dir -i ~1/888_PD18810a-sort.bam.hla.HLA-A.fq -c config.ini
mapping with 1 threads...                                                                                                               
0:00:01.69 Mapping 888_PD18810a-sort.bam.hla.HLA-A.fq to GEN reference...                                                             

/usr/local/share/bcbio-nextgen/anaconda/bin/razers3: error while loading shared libraries: libgomp.so.1: cannot open shared object file
: No such file or directory 
```
which was easily resolved in ubuntu with:

`apt-get install libgomp1`

and then things worked perfectly.

Not sure if something needs to be modified in the bcbio packaging process for others?

Cheers,
Andrew

**Comment by choosehappy** [comment]
it actually seems to be there:

```
root@cbc6fb3a9444:/# bcbio_conda list | grep libgcc-ng
libgcc-ng                 7.2.0                h7cc24e2_2
root@cbc6fb3a9444:/#

```

maybe there was just an error with the upgrade process?

**Comment by chapmanb** [comment]
Thanks much for following up, this is useful to know and we'd seen similar problems with libraries shared by libgcc and this. libgcc gets uninstalled, removing the overlapping libraries, even though the newer libgcc-ng is present. I added a check for this to the installer so if you run two upgrades:
```
bcbio_nextgen.py upgrade -u development
bcbio_nextgen.py upgrade -u development
```
It should get the install fix on the first and apply it on the second. Hope this helps resolve the issue and thanks again for helping to track it down.

**Comment by choosehappy** [comment]
Sorry, not sure if i was clear

Using the apt-get install command i showed above installed the missing library and everything worked fine after that, no errors.

So, in fact, i resolved the error, but others may have it which is why i thought bringing it to your attention might be important

**Comment by chapmanb** [comment]
Definitely, sorry I meant help resolve it inside of bcbio so you don't need the external dependency. If you're all good no need to run an update and thanks again for helping to fix this for other people.

**Comment by choosehappy** [comment]
@chapmanb  not sure if this is related, but in the same instance, i ended up having the same issue again as #2136 and resolved it the same way:

`bcbio_conda install -c conda-forge -c bioconda razers3=3.5.0`

it says it had a later version:

`    razers3:        3.5.3-1                       bioconda    --> 3.5.0-1                     bioconda`

maybe the 3.5.3 version still has the same bug as before?

**Comment by chapmanb** [comment]
Thanks for the report and sorry about this. This is unexpected, since bcbio still pins to 3.5.0 during the automated install. I think the likely cause is that manually updating packages ended up bumping razers3. If you run into other issues, you might want to update with `bcbio_nextgen.py upgrade -u development` and hopefully that will continue to put razers3 in the right state with other dependencies. Hope this helps.
