### ISSUE TITLE
RFE: svprioritize for multiple lists

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2325]
Sometimes more than one list is interesting (for example in our case, all cancer lists might be useful), but currently you can specify just one of them, meaning you need to rerun the step every time you change the list (aside from deleting files).

NOTE: I'm not advocating an "ensemble" approach, but rather running prioritization on each list sequentially.

**Comment by chapmanb** [comment]
Luca -- would it work to specify a meta-list with all your cancer lists of interest and then subset these into individual components as a post-analysis step from bcbio? This would require less infrastructure change and keep what happens inside of bcbio relatively simple. If you'd like to host a more meta cancer list inside of bcbio for automatically specifying this on the command line, that is definitely something we could do to make this easier. Would that work for your analyses?

**Comment by lbeltrame** [comment]
Whoops, this slipped under my radar. Yes, a combined list would work (it would be even better!).
