### ISSUE TITLE
Generating CWL for local/cluster run

### ISSUE THREAD

**Issue by skanwal** [bcbio/bcbio-nextgen#2328]
Hi Brad,

I am trying to generate a CWL representation of RNA-seq workflow using `bcbio_vm`.
I have a sample configuration file for a bcbio test RNA-seq workflow that ran successfully on Spartan. I am trying to evaluate current state of this workflow (in reference to CWL).
Following the instructions from http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html, the command `bcbio_vm.py cwl --systemconfig ../../bcbio/galaxy/bcbio_system.yaml ./config/seqc.yaml` returns the following error:

```[2018-03-09T00:50Z] INFO: Using input YAML configuration: ./config/seqc.yaml
[2018-03-09T00:50Z] INFO: Checking sample YAML configuration: ./config/seqc.yaml
/data/cephfs/punim0010/extras/sehrish/CWL/install/bcbio-vm/anaconda/lib/python2.7/site-packages/gffutils/interface.py:161: UserWarning: It appears that this database has not had the ANALYZE sqlite3 command run on it. Doing so can dramatically speed up queries, and is done by default for databases created with gffutils >0.8.7.1 (this database was created with version 0.8.6.1) Consider calling the analyze() method of this object.
  "method of this object." % self.version)
Preparing CWL input tarball: /data/cephfs/punim0010/extras/sehrish/bcbio/genomes/Hsapiens/GRCh37/star-wf.tar.gz
Preparing CWL input tarball: /data/cephfs/punim0010/extras/sehrish/bcbio/genomes/Hsapiens/GRCh37/seq-wf.tar.gz
Traceback (most recent call last):
  File "/data/cephfs/punim0010/extras/sehrish/bcbio/bin/bcbio_vm.py", line 334, in <module>
    args.func(args)
  File "/data/cephfs/punim0010/extras/sehrish/CWL/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/main.py", line 12, in run
    create.from_world(world, run_info_yaml, integrations=integrations, add_container_tag=args.add_container_tag)
  File "/data/cephfs/punim0010/extras/sehrish/CWL/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/create.py", line 36, in from_world
    prep_cwl(samples, workflow_fn, out_dir, out_file, integrations, add_container_tag=add_container_tag)
  File "/data/cephfs/punim0010/extras/sehrish/CWL/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/create.py", line 425, in prep_cwl
    for cur in workflow.generate(variables, steps, wfoutputs):
  File "/data/cephfs/punim0010/extras/sehrish/CWL/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/workflow.py", line 62, in generate
    inputs, parallel_ids, nested_inputs = _get_step_inputs(step, file_vs, std_vs, parallel_ids)
  File "/data/cephfs/punim0010/extras/sehrish/CWL/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/workflow.py", line 168, in _get_step_inputs
    for orig_input in [_get_variable(x, file_vs) for x in _handle_special_inputs(step.inputs, file_vs)]:
  File "/data/cephfs/punim0010/extras/sehrish/CWL/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/workflow.py", line 287, in _get_variable
    raise ValueError("Did not find variable %s in \n%s" % (vid, pprint.pformat(variables)))
ValueError: Did not find variable config__algorithm__expression_caller in
```

I wonder why are these tar files being generated (looking at their size, these are quite big) and what does the error signify? My initial understanding was the command will generate a .`cwl` file and `.json` files for the RNA_seq workflow.
The sample workflow (seqc.yaml) that I am using in the command and the complete error message are provided at the following gist https://gist.github.com/skanwal/e8ad6abcdfd8726d995325bdb1e61045, for your reference.

Thanks for all your work and time.

**Comment by chapmanb** [comment]
Sehrish;
Thanks much for trying this out and apologies about the issues. If you add:
```
expression_caller: [salmon]
```
to your YAML configuration, that will avoid the issue you're seeing. I also pushed a fix to make this the default so in the future you won't need to add it explicitly.

The tarballs it creates are for complex directory indices like bwa and snpEff that are difficult to represent in CWL in a consistent way across multiple platforms. We now pass the tarball around to individual steps in CWL and unpack it as necessary. Right now this entails a disk space penalty since we use packed for CWL and unpacked for non-CWL but eventually they'll converge and we can avoid the issue.

Thanks again for testing this out and hope this gets your analysis running.

**Comment by skanwal** [comment]
Thank you so much for the reply. Adding the `expression_caller` solves the issue.
