### ISSUE TITLE
Installation via pip -> bcbio_nextgen.py -h fails

### ISSUE THREAD

**Issue by kmpf** [bcbio/bcbio-nextgen#2329]
I did install bcbio-nextgen via pip using Python2 and Python3 virtualenv, via

```$ pip install bcbio-nextgen==1.0.8```

That's what I got for Python2:

```
$ python --version
Python 2.7.12
$ bcbio_nextgen.py -h
Traceback (most recent call last):
  File "/home/user/develop/wms/bcbio/venv2/bin/bcbio_nextgen.py", line 33, in <module>
    from bcbio.setpath import prepend_bcbiopath
  File "/home/user/develop/wms/bcbio/venv2/local/lib/python2.7/site-packages/bcbio/setpath.py", line 7, in <module>
    from bcbio import utils
  File "/home/user/develop/wms/bcbio/venv2/local/lib/python2.7/site-packages/bcbio/utils.py", line 12, in <module>
    from six.moves import configparser
ImportError: No module named six.moves
```

And this for Python3:

```
$ python --version
Python 3.5.2
$ bcbio_nextgen.py -h
  File "/home/user/develop/wms/bcbio/venv/bin/bcbio_nextgen.py", line 202
    print version.__version__
                ^
```

Eventhough installation via pip is not the recommended way to do the installation, I think this should be fixed.

**Comment by chapmanb** [comment]
Christoph -- thanks much for the report and bringing this up. We currently recommend installing bcbio by the automated installer which makes use of conda dependencies:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

We're currently not able to support installation via pip. Similarly we haven't yet ported over bcbio and the dependencies to support Python 3. These are things we'd like to tackle at some point but we're focused now on improving the analysis pipelines and moving to use the Common Workflow Language for parallelization.

If you're running into issues with the automated installer we'd be happy to try and fix them to make it work better for your environment. Thanks again for the report and discussion.

**Comment by micromania2** [comment]
pip installation should be standard 2019. I am having issues with the automated installer as well. It can not find the path for bcbio_nextgen_install.py

**Comment by roryk** [comment]
Hi @micromania2,

Sorry for the troubles. We agree pip is standard. But installing bcbio via pip is not useful at all because you will just get the code and none of the tools, and nothing will work without the tools. The automated installer installs all of the tools in addition to the code.

Regarding the `bcbio_nextgen_install.py` The first line here https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated has you download it, if you do that you should be all set.
