### ISSUE TITLE
Completely remove bcbio-nextgen

### ISSUE THREAD

**Issue by omigueles** [bcbio/bcbio-nextgen#2331]
Hi bcbio community,

Is there an automated way, maybe from one of the python scripts included in the installation, to remove bcbio-nextgen from linux?

Kind regards,
Oscar

**Comment by chapmanb** [comment]
Oscar;
We don't have an automated remove method but the full installation is isolated to the install directory, so just doing a `rm -rf /path/to/bcbio` will remove bcbio, the tools, and associated data. Hope this works for your needs.
