### ISSUE TITLE
Recurring conda error with clean install

### ISSUE THREAD

**Issue by aadamk** [bcbio/bcbio-nextgen#2333]
I get the following error when attempting a clean install of bcbio (as I was encountering issues with the multiarray module from numpy related to libquadmath.so.0 in my previous install that I could not resolve):

UnsatisfiableError: The following specifications were found to be in conflict:
  - bcbio-nextgen 1.0.8
  - libcurl
Use "conda info <package>" to see the dependencies for each package.

Traceback (most recent call last):
  File "./bcbio_nextgen_install.py", line 260, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "./bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "./bcbio_nextgen_install.py", line 81, in install_conda_pkgs
    "--file", os.path.basename(REMOTES["requirements"])])
  File "/home/aadam/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/aadam/bcbio/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', '--file', 'requirements-conts-conda.txt']' returned non-zero exit status 1.

Running 'conda info' on the respective packages as instructed results in 'NoPackagesFoundError: Package missing in current linux-64 channels'.  However, when searching 'libcurl' in my bcbio directory, I find an entire libcurl directory under 'anaconda/pkgs'.   Not sure how to continue with installation.

**Comment by chapmanb** [comment]
Sorry for the issue and thanks for the report. Can you provide more details about how you're installing bcbio? It looks from the traceback like you're trying to manually install bcbio inside of a python3 conda environment. bcbio only supports python2 and we recommend using the automated installer:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

which will setup the correct conda environment. Does that help explain the issues you're seeing?

**Comment by aadamk** [comment]
Thanks for your reply.  I commented out miniconda3 from my .bashrc profile and loaded a python 2.7.9 environment module on a new cluster node,  I used the following command:  
python ./bcbio_nextgen_install.py ~/bcbio --tooldir=~/bcbio/

And still get the following error, though without the conda environment error.  

UnsatisfiableError: The following specifications were found to be in conflict:
  - bcbio-nextgen 1.0.8
  - libcurl
Use "conda info <package>" to see the dependencies for each package.

Traceback (most recent call last):
  File "./bcbio_nextgen_install.py", line 260, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "./bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "./bcbio_nextgen_install.py", line 81, in install_conda_pkgs
    "--file", os.path.basename(REMOTES["requirements"])])
  File "/opt/software/python/2.7.9/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/aadam/bcbio/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', '--file', 'requirements-conda.txt']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks much for following up and the help debugging. I tried to replicate this on a clean machine and can't seem to replicate the issue. My guess is that an environmental variable set in your bashrc or modules is injecting a different conda environment with an incompatible libcurl. Unfortunately the error message doesn't give much idea where this might come from. You could try exploring with `conda env list` which might provide a clue about overlapping environments:

https://conda.io/docs/user-guide/tasks/manage-environments.html#activating-an-environment

Hope this helps some to help identify the issue. Thanks again.

**Comment by oharismendy** [comment]
I am having the exact same issue on CentOS citrus machine from our private cloud, after clean install, and trying to run: 

bcbio_nextgen.py upgrade -u stable --tools --data

UnsatisfiableError: The following specifications were found to be in conflict:
  - bcbio-nextgen 1.0.8
  - libcurl
Use "conda info <package>" to see the dependencies for each package.

Traceback (most recent call last):
  File "/scratch/bcbio/anaconda/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 66, in upgrade_bcbio
    _update_conda_packages()
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 241, in _update_conda_packages
    "-c", "bioconda", "-c", "conda-forge", "--file", req_file])
  File "/scratch/bcbio/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/scratch/bcbio/anaconda/bin/conda', 'install', '--quiet', '--yes', '-c', 'bioconda', '-c', 'conda-forge', '--file', 'bcbio-update-requirements.txt']' returned non-zero exit status 1

I hope you can help

**Comment by chapmanb** [comment]
Thanks for the additional report and sorry about these issues. I'm confused as to what is going on and not sure why I can't replicate this, but I just pushed a new 1.0.9 release with some conda resolution fixes that might avoid the issue. Would you be able to retry and see if that helps avoid the problem? If not, it would be useful to know exactly how you installed the initial version so I can see if I'm missing something in my attempt to reproduce? Thanks much for the help debugging.

**Comment by Raey2014** [comment]
Hi chapmanb,

Thanks for providing us bcbio pipeline. I'm trying to re-install it after removing my previous installation, but I got this error as well.
[nohup.txt](https://github.com/bcbio/bcbio-nextgen/files/1899426/nohup.txt)

**Comment by oharismendy** [comment]
version 1.0.9 solved the conda issue for me. Thanks for addressing this.
