### ISSUE TITLE
zebrafish fastrna-seq

### ISSUE THREAD

**Issue by wenbinwei** [bcbio/bcbio-nextgen#2338]
I tried to run zebrafish fastrna-seq using the following template:
details:
  - analysis: fastrna-seq
    genome_build: GRCz10
    algorithm:
      transcriptome_fasta: ../ensembl/v91/Danio_rerio.GRCz10.cdna.all.fa
upload:
  dir: ../final

However, I got the following error:
File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 120, in run_salmon_index
    assert file_exists(gtf_file), "%s was not found, exiting." % gtf_file
AssertionError: None was not found, exiting.

**Comment by roryk** [comment]
Hi Wenbin,

This looks like a bug in the fast RNA-seq pipeline-- I'll push a fix for it, but you can get going if you download the Danio_rerio GTF file from Ensembl and pass it with the `transcriptome_gtf` option.

**Comment by wenbinwei** [comment]
Hi, Rory,
Thank you. By the way, somehow the transcriptome_gtf option is not working in this configuration. I just tried the transcriptome_gtf option with the following template and still have the same error message.
details:
  - analysis: fastrna-seq
    genome_build: GRCz10
    algorithm:
      transcriptome_fasta:  ../ensembl/v91/Danio_rerio.GRCz10.cdna.all.fa
      transcriptome_gtf: ../ensembl/v91/Danio_rerio.GRCz10.91.gtf
upload:
  dir: ../final

**Comment by roryk** [comment]
Thanks Wenbin,

Sorry about that, we were doing some stringent checking for an installed GTF, which is unnecessary if a transcriptome_fasta file is being supplied to the fast RNA-seq pipeline. I relaxed those checks so this bug should be squashed. Thanks!

**Comment by wenbinwei** [comment]
Thanks Rory,
It works now.
