### ISSUE TITLE
GATK  failed after updation to development version

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2342]
Hi, I just updated the bcbio installation to the latest development version. Then I test the RNA-seq pipeline using the following yaml file:

> upload:
>   dir: upload
> details:
>   - analysis: RNA-seq
>     algorithm:
>       fusion_caller: [oncofuse]
>       variantcaller: [gatk-haplotype]
>       #transcriptome_align: True
>       aligner: hisat2
>       quality_format: standard
>       #trim_reads: read_through
>       #adapters: [truseq, polya]
>       #tools_on: [gatk4]
>       expression_caller: [cufflinks, stringtie, sailfish, dexseq, kallisto, express]
>       transcript_assembler: [cufflinks, stringtie]
>       #spikein_fasta: ../data/spikeins/spikeins.fa
>     metadata:
>       batch: TestBatch1
>     description: Test1
>     genome_build: hg38
> 

The pipeline failed in the step `RNA-seq variant calling` and the error information is as below:
> 
> ipyparallel.error.CompositeError: one or more exceptions from call to method: concat_variant_files
> [1:apply]: CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/app/smartngs/bcbio/anaconda/bin:$PATH && gatk-launch --java-options '-Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmpVrEHZQ' GatherVcfs -I /app/datamart/RNAseq-example/seqc_3/work/joint/gatk-haplotype-joint/TestBatch1/TestBatch1-joint-files.list -O /app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmprmOTXR/TestBatch1-joint.vcf.gz
> Using GATK jar /app/smartngs/bcbio/anaconda/share/gatk4-4.0.2.1-0/gatk-package-4.0.2.1-local.jar
> Running:
>     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmpVrEHZQ -jar /app/smartngs/bcbio/anaconda/share/gatk4-4.0.2.1-0/gatk-package-4.0.2.1-local.jar GatherVcfs -I /app/datamart/RNAseq-example/seqc_3/work/joint/gatk-haplotype-joint/TestBatch1/TestBatch1-joint-files.list -O /app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmprmOTXR/TestBatch1-joint.vcf.gz
> 17:16:48.898 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/app/smartngs/bcbio/anaconda/share/gatk4-4.0.2.1-0/gatk-package-4.0.2.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
> [Tue Mar 20 17:16:48 CST 2018] GatherVcfs  --INPUT /app/datamart/RNAseq-example/seqc_3/work/joint/gatk-haplotype-joint/TestBatch1/TestBatch1-joint-files.list --OUTPUT /app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmprmOTXR/TestBatch1-joint.vcf.gz  --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 1 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX true --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
> [Tue Mar 20 17:16:48 CST 2018] Executing as root@cnode01 on Linux 3.10.0-514.6.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Deflater: Intel; Inflater: Intel; Picard version: Version:4.0.2.1
> INFO    2018-03-20 17:16:48     GatherVcfs      Checking inputs.
> INFO    2018-03-20 17:16:49     GatherVcfs      Checking file headers and first records to ensure compatibility.
> [Tue Mar 20 17:16:49 CST 2018] picard.vcf.GatherVcfs done. Elapsed time: 0.00 minutes.
> Runtime.totalMemory()=460259328
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
> java.lang.IllegalArgumentException: First record in file /app/datamart/RNAseq-example/seqc_3/work/joint/gatk-haplotype-joint/TestBatch1/chr11/TestBatch1-chr11_0_135086622.vcf.gz is not after first record in previous file /app/datamart/RNAseq-example/seqc_3/work/joint/gatk-haplotype-joint/TestBatch1/chr8/TestBatch1-chr8_0_145138636.vcf.gz
>         at picard.vcf.GatherVcfs.assertSameSamplesAndValidOrdering(GatherVcfs.java:128)
>         at picard.vcf.GatherVcfs.doWork(GatherVcfs.java:74)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
>         at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
>         at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:159)
>         at org.broadinstitute.hellbender.Main.mainEntry(Main.java:202)
>         at org.broadinstitute.hellbender.Main.main(Main.java:288)
> ' returned non-zero exit status 3
> 

I remeber that the RNA-seq pipeline work smooth using gatk-3.8， and I also noticed that the new version use gatk4 as default runner for HaplotypeCaller or MuTect2, then how to tackle this problem?

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. I'm not sure what is going on but the step that combined individual VCFs is complaining about out of order records in two files from after scattering. Would you be able to share the outputs from:
```
 zcat /app/datamart/RNAseq-example/seqc_3/work/joint/gatk-haplotype-joint/TestBatch1/chr8/TestBatch1-chr8_0_145138636.vcf.gz | grep -v ^# | head -1
 /app/datamart/RNAseq-example/seqc_3/work/joint/gatk-haplotype-joint/TestBatch1/chr11/TestBatch1-chr11_0_135086622.vcf.gz | grep -v ^# | head -1
```
This might help us identify what is going on and figure out why the outputs aren't ordered as expected. Thanks for the help debugging this.

**Comment by hliu2016** [comment]
Hi @chapmanb,
I doubt that my hisat2 index for hg38 may be problematic, so I change the aligner to star and hg19 assembly. The yaml file is as below:

> upload:
>   dir: upload
> details:
>   - analysis: RNA-seq
>     algorithm:
>       fusion_caller: [oncofuse]
>       variantcaller: [gatk-haplotype]
>       #transcriptome_align: True
>       aligner: star
>       quality_format: standard
>       #trim_reads: read_through
>       #adapters: [truseq, polya]
>       #tools_off: [gatk4]
>       expression_caller: [cufflinks, stringtie, sailfish, dexseq, kallisto, express]
>       transcript_assembler: [cufflinks, stringtie]
>       #spikein_fasta: ../data/spikeins/spikeins.fa
>     metadata:
>       batch: TestBatch1
>     description: Test1
> 

However, the GATK 4 still failed in calling RNA-seq variants. Please help me to work through out this problem. Thanks very much. The error information 

> Traceback (most recent call last):
>   File "/app/smartngs/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
>     main(**kwargs)
>   File "/app/smartngs/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
>     run_main(**kwargs)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
>     fc_dir, run_info_yaml)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
>     for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 260, in rnaseqpipeline
>     samples = rnaseq.rnaseq_variant_calling(samples, run_parallel)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 56, in rnaseq_variant_calling
>     samples = run_parallel("run_rnaseq_ann_filter", samples)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 137, in run
>     for data in view.map_sync(fn, items, track=False):
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 344, in map_sync
>     return self.map(f,*sequences,**kwargs)
>   File "<decorator-gen-137>", line 2, in map
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 52, in sync_results
>     ret = f(self, *args, **kwargs)
>   File "<decorator-gen-136>", line 2, in map
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 37, in save_ids
>     ret = f(self, *args, **kwargs)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1114, in map
>     return pf.map(*sequences)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 299, in map
>     return self(*sequences, __ipp_mapping=True)
>   File "<decorator-gen-119>", line 2, in __call__
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 80, in sync_view_results
>     return f(self, *args, **kwargs)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 285, in __call__
>     return r.get()
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 169, in get
>     raise self.exception()
> ipyparallel.error.CompositeError: one or more exceptions from call to method: run_rnaseq_ann_filter
> [2:apply]: CalledProcessError: Command 'set -o pipefail; /app/smartngs/bcbio/galaxy/../anaconda/bin/tabix -f -p vcf /app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmpwYiqis/TestBatch1-joint-annotated-rnaedit.vcf.gz
> tbx_index_build failed: /app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmpwYiqis/TestBatch1-joint-annotated-rnaedit.vcf.gz
> ' returned non-zero exit status 1
> Exception in thread Thread-1 (most likely raised during interpreter shutdown):

**Comment by hliu2016** [comment]
Hi @chapmanb,
The error is caused by the problem that GATK4 can not run on slurm cluster. As I continue this analysis based on the current results, using only 16 local cores.

Could you help to address this problem?

**Comment by chapmanb** [comment]
Thanks for testing out different run configurations and following up on this. The failure you're reporting above is during indexing of a VCF file so appears separate from GATK4 or hisat2. This is the failing command:
```
/app/smartngs/bcbio/galaxy/../anaconda/bin/tabix -f -p vcf /app/datamart/RNAseq-example/seqc_3/work/bcbiotx/tmpwYiqis/TestBatch1-joint-annotated-rnaedit.vcf.gz
```
I don't have a good error message here to see why it fails but it might be worth running it outside of bcbio to see if you run into issues.

Are you seeing consistent failures at the same step when you run on your cluster, or always at the same position? The fact that is runs cleanly on the same inputs on a single machine lead me to suspect you might be hitting filesystem errors when running under load. Is this a possibility?

Hope this helps some with debugging.

**Comment by roryk** [comment]
Thanks, we don't recommend using GATK4 for RNA-seq right now, since GATK3 seems to perform better, so closing this out.
