### ISSUE TITLE
Can I use the prebuilt  hisat2 index in bcbio？

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2348]
Hi, I try to build the hisat2 index for hg38, but the building failed due to my memory is less than 128G. Although the index files produced by bcbio is not finished, I still found that the number of these files are quite more than those index files downloaded from hisat2 ftp (ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/data/). So, can I use the index prebuilt by hisat2 in bcbio?

**Comment by chapmanb** [comment]
Thanks for the question. I don't have much context on the pre-built hisat2 genomes to know if they include the same alts as the bcbio hg38 distribution, so I'd suggest trying to stick with the native build. If you're able to provide additional memory and re-run the hisat2 build, hopefully this'll get things working cleanly for you. Please let us know if you run into any other issues at all.
