### ISSUE TITLE
No reference found when running BaseRecalibratorSpark for mouse

### ISSUE THREAD

**Issue by stkdlmr** [bcbio/bcbio-nextgen#2349]
Hello,

I'm using the gatk-variant pipeline to call variants in mouse (mm10) WGS samples. When I get to the BaseRecalibibratorSpark step, I get the error:
``java.lang.IllegalArgumentException: Not a reference API source URL: None``
Looking at the command in the log file, I see that that the `--reference` parameter is set to `None`.

My colleague suggested that this might be because there is no `/ucsc/mm10.2bit` file available within the `/tools/bcbio/genomes/Mmusculus/mm10/` directory like there is for Hsapiens.

I was wondering whether you are planning on adding the mm10.2bit file to the genomes folder? If not, could you please suggest what I should do to run base recalibration for mouse? Or would you suggest omitting base recalibration before running HaplotypeCaller?

Thanks very much!  

Stephanie

**Comment by chapmanb** [comment]
Stephanie;
Apologies about the issue. We'd added support for 2bit index creation for mm10 and other supported genomes a few days ago. If you update your bcbio data with:
```
bcbio_nextgen.py upgrade --data
```
it should generate these, and then you can re-run your analysis and it will pick up where it left off and hopefully run smoothly. Please let us know if you run into any other issues.
