### ISSUE TITLE
java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2354]
GATK4 report this errors in the variant calling for RNA-seq data. I noticed that the developer of GATK4  stated to sovle this problem. But in my case this problem still occurred. bcbio has not updated to the latest GATK version? or other problem exist in GATK4?

> java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
>      at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.setPosition(SAMRecordToGATKReadAdapter.java:89)
>      at org.broadinstitute.hellbender.utils.clipping.ClippingOp.applyHARDCLIP_BASES(ClippingOp.java:381)
>      at org.broadinstitute.hellbender.utils.clipping.ClippingOp.apply(ClippingOp.java:73)
>      at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:147)
>      at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:128)
>      at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:332)
>      at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:335)
>      at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:84)
>      at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:238)
>      at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:478)
>      at org.broadinstitute.hellbender.tools.HaplotypeCallerSpark.lambda$regionToVariants$580(HaplotypeCallerSpark.java:203)

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. bcbio does ship with the latest GATK4 but the version you have will depend on your last update. You can check with:
```
$ bcbio_conda list | grep gatk4
gatk4                     4.0.3.0                       0    bioconda
```
If you don't have `4.0.3.0` perhaps an update will resolve the issue. Hope this works for you.

**Comment by hliu2016** [comment]
Hi @chapmanb,
I have updated bcbio to the latest version, and now the GATK version is exactly 4.0.3.0. However, the RNA-seq pipeline still failed by the same error: java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1.  

I use the fastq files of the example RNA-seq pipeline and my yaml file is as below:

> upload:
>   dir: upload
> resources:
>   star:
>     cores: 12
>     memory: 5G
> details:
>   - analysis: RNA-seq
>     algorithm:
>       fusion_caller: [oncofuse]
>       variantcaller: [gatk-haplotype]
>       #transcriptome_align: True
>       aligner: star
>       quality_format: standard
>       #trim_reads: read_through
>       #adapters: [truseq, polya]
>       #tools_off: [gatk4]
>       expression_caller: [cufflinks, stringtie, sailfish, dexseq, kallisto, express]
>       transcript_assembler: [cufflinks, stringtie]
>       #spikein_fasta: ../data/spikeins/spikeins.fa
>     metadata:
>       batch: TestBatch1
>     description: Test1
>     genome_build: hg19
> 

I checked the file named by bcbio-ipengine.err.845_X and found the error information is as follows:

> 20:03:34.414 INFO  SplitNCigarReads - Shutting down engine
> [April 9, 2018 8:03:34 PM CST] org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads done. Elapsed time: 297.58 minutes.
> Runtime.totalMemory()=2414415872
> java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
>         at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.setMatePosition(SAMRecordToGATKReadAdapter.java:197)
>         at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.setPredictedMateInformation(OverhangFixingManager.java:435)
>         at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.splitNCigarRead(SplitNCigarReads.java:221)
>         at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.secondPassApply(SplitNCigarReads.java:184)
>         at org.broadinstitute.hellbender.engine.TwoPassReadWalker.lambda$traverseReads$0(TwoPassReadWalker.java:62)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>         at java.util.Iterator.forEachRemaining(Iterator.java:116)
>         at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
>         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>         at org.broadinstitute.hellbender.engine.TwoPassReadWalker.traverseReads(TwoPassReadWalker.java:60)
>         at org.broadinstitute.hellbender.engine.TwoPassReadWalker.traverse(TwoPassReadWalker.java:49)
>         at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
>         at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
>         at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
>         at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
>         at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
>         at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
>         at org.broadinstitute.hellbender.Main.main(Main.java:289)
> ' returned non-zero exit status 3
> 2018-04-09 20:04:54.110 [IPEngineApp] WARNING | No heartbeat in the last 5010 ms (1 time(s) in a row).
> slurmstepd: error: *** JOB 847 ON cnode01 CANCELLED AT 2018-04-09T20:47:11 DUE TO TIME LIMIT ***
>

**Comment by chapmanb** [comment]
Thank you for following up. It sounds like we're finding additional cases triggering problems with GATK and our best approach at this point would be to try and prepare a reproducible test case so that they can address the underlying issue. Are you able to share the input BAMs that trigger the problem? You can look in `log/bcbio-nextgen-commands.log` for the command line that causes the issue to run outside of bcbio. Ideally we could also limit the BAM file down to a smaller region that demonstrates the issue. Happy to help with this and getting the bug report together if you're able to share the files and commands.

**Comment by chapmanb** [comment]
Thanks for the test case and making the data available. Unfortunately for debugging, that subset of the file works in my tests so doesn't seem to demonstrate the issue. The BAM itself appears to have some issues with being truncated, but once I converted to SAM, fixed and converted back, it runs cleanly and doesn't show the error you've seen.

It's likely we're hitting some specific issues with reads in the input BAM so might need either the full BAM or for you to dig into the region that is failing you can subset to just those reads. Thanks again for the help debugging this.

**Comment by hliu2016** [comment]
Hi @chapmanb,
Thank you very much. I also think this failure is caused by some specific reads in the BAM file. It seems that the bcbio-ipengine.err.XXX files give some hints, as gatk failed when tackle some unmapped reads. I uploaded the bcbio-ipengine.err.XXX files, hope this is helpful to solve this problem.

**Comment by chapmanb** [comment]
Thanks for the the debugging work. This does help in trying to reduce the original BAM to a reproducible case. My suggestion would be to extract the unmapped reads:
```
samtools view -b -f 4 orig.bam > unmapped.bam
```
and then feed this to the GATK command outside of bcbio to see if it also has the issue. If so, you can share this and we can work to put together a reproducible test case for the GATK team. Thanks much.

**Comment by roryk** [comment]
Closing as this is stale, GATK has been updated a bunch since then so this bug is unlikely to still exist.

**Comment by vguerracanedo** [comment]
Hi guys! 

I'm having the sample problem with the GATK version 4.1.2. Any tips on how to fix it?
Best, 
Vanessa

===
13:51:58.235 INFO  ProgressMeter -             unmapped            223.8             263964000        1179366.7
13:52:08.237 INFO  ProgressMeter -             unmapped            224.0             264938000        1182837.5
INFO	2020-04-28 13:52:12	SortingCollection	Creating merging iterator from 291 files
13:58:31.162 INFO  SplitNCigarReads - Shutting down engine
[April 28, 2020 1:58:31 PM PDT] org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads done. Elapsed time: 230.47 minutes.
Runtime.totalMemory()=8340373504
java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
	at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.setMatePosition(SAMRecordToGATKReadAdapter.java:197)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.setPredictedMateInformation(OverhangFixingManager.java:445)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.splitNCigarRead(SplitNCigarReads.java:222)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.secondPassApply(SplitNCigarReads.java:185)
	at org.broadinstitute.hellbender.engine.TwoPassReadWalker.lambda$traverseReads$0(TwoPassReadWalker.java:72)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.TwoPassReadWalker.traverseReads(TwoPassReadWalker.java:70)
	at org.broadinstitute.hellbender.engine.TwoPassReadWalker.traverse(TwoPassReadWalker.java:59)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1039)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Using GATK jar /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/gatk/4.1.2.0/gatk-package-4.1.2.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/gatk/4.1.2.0/gatk-package-4.1.2.0-local.jar SplitNCigarReads -R /home/vguerra/project/Hart_Lab/Patiria_transcriptome_IMA-Project/data/gDNA/GCA_000285935.1_Pmin_1.0_genomic.fna -I /home/vguerra/project/Hart_Lab/Patiria_transcriptome_IMA-Project/Validation_bam_files/dedupped.valid_SRR573709.bam -O dedupped.valid_SRR573709_SplitNCigarReads.bam --read-validation-stringency LENIENT
===

**Comment by roryk** [comment]
Hi Vanessa,

Hope you are well-- it looks like this is a general GATK problem and not something related to bcbio. You can get support for GATK itself on their website: http://www.broadinstitute.org/gatk.
