### ISSUE TITLE
boto error with bcbio upgrade on GCP

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2355]
Im trying to upgrade bcbio to install additional tools and I can't quite get out of the starting gate.  I'm working on an ubuntu GCE instance

sudo -H bcbio_nextgen.py upgrade -u development --distribution ubuntu --tools --data --datatarget gemini --datatarget gnomad --datatarget cadd --datatarget vep

........

Upgrading bcbio

# All requested packages already installed.
# packages in environment at /usr/local/share/bcbio/anaconda:
#
bcbio-nextgen             1.0.9a                   py27_9    bioconda
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /usr/local/share/bcbio/anaconda:

The following NEW packages will be INSTALLED:

    libgcc-ng: 7.2.0-hdf63c60_3

Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /usr/local/share/bcbio/anaconda:

The following NEW packages will be INSTALLED:

    libgcc-ng: 7.2.0-hdf63c60_3

Upgrading bcbio-nextgen to latest development version
Collecting bcbio-nextgen from git+https://github.com/bcbio/bcbio-nextgen.git#egg=bcbio-nextgen
  Cloning https://github.com/bcbio/bcbio-nextgen.git to /tmp/pip-build-t14K7p/bcbio-nextgen
Installing collected packages: bcbio-nextgen
  Found existing installation: bcbio-nextgen 1.0.9a0
    Uninstalling bcbio-nextgen-1.0.9a0:
      Successfully uninstalled bcbio-nextgen-1.0.9a0
  Running setup.py install for bcbio-nextgen ... done
Successfully installed bcbio-nextgen-1.0.9a0
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Upgrade of bcbio-nextgen development code complete.
Upgrading third party tools to latest versions
--2018-04-04 14:51:03--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com... 192.30.255.113, 192.30.255.112
Connecting to github.com|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2018-04-04 14:51:04--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com... 192.30.255.120, 192.30.255.121
Connecting to codeload.github.com|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5168548 (4.9M) [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 60% 45.4M 0s
  3072K ........ ........ ........ ......                    100% 75.3M=0.09s

2018-04-04 14:51:04 (53.7 MB/s) - written to stdout [5168548/5168548]

WARN [__init__.py(380)]: cloudbio.deploy.plugins.cloudman rule module could not be loaded: 'module' object has no attribute 'plugin'
Setting up virtual machine
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 82, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 446, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home/patrickjenningsreed/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/patrickjenningsreed/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 94, in _setup_vm
    from .volume import attach_volumes, make_snapshots, detach_volumes
  File "/home/patrickjenningsreed/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/volume.py", line 3, in <module>
    from boto.exception import EC2ResponseError
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: 'module' object has no attribute 'plugin'

**Comment by chapmanb** [comment]
Patrick;
Sorry about the continued issues. I tried to fix this earlier with hiding the imports but looks like they didn't get nested deep enough. I pushed a fix just now I think will resolve so if you remove the cached cloudbiolinux (`rm -rf /home/patrickjenningsreed/tmpbcbio-install`) and re-run hopefully it'll run cleanly now. Please let me know if you still hit issues and we can investigate and fix more. Thanks for the help debugging this.

**Comment by PatrickJReed** [comment]
Thanks Brad, working great!
![a88](https://user-images.githubusercontent.com/4350664/38321600-dfaa77a4-37ec-11e8-9085-be8c8699d817.jpg)
