### ISSUE TITLE
RFC: Parameters for MuTect2 tumor-only mode

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2357]
According to https://gatkforums.broadinstitute.org/gatk/discussion/10157/gatk4-beta-no-filter-passing-variants-in-mutect2-tumor-only-runs-using-default-parameters and in particular https://gatkforums.broadinstitute.org/gatk/discussion/comment/46725/#Comment_46725 some parameters can be tuned when using MuTect 2 in tumor-only mode, because it's fairly more stringent.

This is IMO important for samples where you don't have a matched normal, for example due to historical samples, or because your normal sample was of too poor quality to be sequenced (I've had both happen to me recently). The net effect with the current situation is that you have all your variants removed by filters (either from the GATK or by prioritization).

Can arbitrary parameters be passed to MuTect2? IIRC, it was not possible last time I looked at it. Perhaps people that use MuTect 2 in tumor-only mode should chime in with their experience when using bcbio.

**Comment by lbeltrame** [comment]
In my preliminary testing (currently going through a confirmation re-analysis) the default parameters set by bcbio are too stringent and end up discarding most (if not all) variants. I'll go through the thread again after this run is done and see how I can tweak things.

**Comment by chapmanb** [comment]
Luca -- thanks fo this, I'd be keen to get your experience and happy to tweak this. I'd also like to do an investigation into this from my side once we get the additional test sets in place. Thanks for helping.

**Comment by chapmanb** [comment]
Luca;
While digging into #2464 I explored the current state of tumor-only calling in MuTect2 and it appears as if the current suggestion is to not tweak parameters and let MuTect2 determine outputs: https://github.com/broadinstitute/gatk/issues/4745 I'll work on validation of this with some tumor only truth sets but would be curious about your experiences with more recent versions of MuTect2.

**Comment by lbeltrame** [comment]
My last run in tumor-only mode is kind of old, so I'm not sure how the updated version fares. In my experience on exome-level datasets the tumor-only callsets are definitely more noisy: the prioritization by bcbio definitely helps (I also prepared a panel of normals according to the MuTect 2 docs) but there is still some noise left. In fact I did a quick bootstrapped t-test between the tumor only and the matched groups I had in the same set and the mean number of variants was definitely higher in the tumor only groups (bootstrapped p < 0.01).  

Same for a quick evaluation of SNVs/Mbp: compared to the mean of the other sample population, it's definitely higher (I've taken steps to ensure it wasn't due to the samples being outliers).Most of the added variation is noise, as far as I can see (I didn't do anything comprehensive, but this included SNPs with low frequency in the population, so the prioritization filter missed them).

On this topic, VarDict in tumor only mode is even more noisy than MuTect 2, up to the point that I've had to exclude it from that specific analysis.

**Comment by chapmanb** [comment]
Luca;
Thanks for this, I'd definitely appreciate any feedback on tumor-only testing. Most callers error on the side of sensitivity for tumor-only calling with the idea that you'll subsequently filter down by some criteria but happy to help reduce that by filtering and prioritization. We've been working on tumor-only validations and the current sensitivity/specificities for different callers are here:

https://github.com/bcbio/bcbio_validations/tree/master/somatic-lowfreq

I'll work to include MuTect2 in here as well, I've been behind and didn't realize it was now tuned for tumor-only calling as well. Thanks again for this discussion and testing.

**Comment by gabeng** [comment]
A quick question: I wanted to check out `mutect2` with a cohort of tumor-only samples. It seems that I have to assign `phenotype: tumor` to these samples to use `mutect2`. However, bcbio complains if I assign the samples to different batches. Why is that?

**Comment by chapmanb** [comment]
Ben;
Thanks for the report. Could you post an example of your configuration and the error you're seeing? It should work as you describe, so happy for any specifics so we can replicate the issue. Thanks much.

**Comment by gabeng** [comment]
Brad,
I now ran into this known bug in Mutect2 https://github.com/bcbio/bcbio-nextgen/issues/2636. Once I figure out how to get a running version, I will check again regarding phenotype/batch configuration.

**Comment by roryk** [comment]
Hey all, closing this as Brad included a comparison with Mutect2 in the somatic low frequency example by doing what the Broad folks suggested, leaving the parameters at the defaults. Please re-open if there is something we could be doing that is better. Thank you everyone for the awesome discussion, it is so helpful.
