### ISSUE TITLE
Bcbio engine dies error

### ISSUE THREAD

**Issue by alongalor** [bcbio/bcbio-nextgen#2359]
Hello!

The same pipeline I posted about before has failed. (The LSF-based Orchestra cluster was retired so I . had to switch and run this job on O2) Just as a refresher here is the command I submit:

```
#!/bin/bash
#SBATCH -n 1
#SBATCH -t 30-00:00:00
#SBATCH -p park
#SBATCH --mem-per-cpu=1G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=alon_galor@hms.harvard.edu
/n/data1/hms/dbmi/park/alon/software/bcbio/bin/bcbio_nextgen.py /n/data1/hms/dbmi/park/DATA/BSMCommonExperiment/ReferenceTissueProject/.Pipeline/GATK4/config/GATK4.yaml -t ipython -n 512 -s slurm -q park -r t=30-00:00 --timeout 43200
```

Looking through the logs, the debug log looks completely fine. The slurm.out file indicates the following error:

```
ipyparallel.error.CompositeError: one or more exceptions from call to method: postprocess_alignment
[Engine Exception]EngineError: Engine '9f00d508-f8f841b21499158005a547da' died while running task '173a0c4b-3372ada20f445cc01ff8185a'
[Engine Exception]EngineError: Engine '240bf628-6adc75efe43b1f61d1dec265' died while running task '89820a0f-415dc49393c6f86922f6998c'
[Engine Exception]EngineError: Engine 'bdf5d3fb-393ada2586c039391e343843' died while running task '61fad78b-88fd2d0db52c9006a2dabbd6'
[Engine Exception]EngineError: Engine '3c4e31ca-54c8eb4f90e7c31713c5d540' died while running task '243d366a-7d73997533f31721be121084'
.... 10 more exceptions ...
```

Any help here would be much appreciated.

Thanks a lot,

Alon

[bcbio-nextgen-debug.log.zip](https://github.com/bcbio/bcbio-nextgen/files/1885113/bcbio-nextgen-debug.log.zip)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/1885114/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/1885115/bcbio-nextgen-commands.log)
[slurm-11754135.out.zip](https://github.com/bcbio/bcbio-nextgen/files/1885116/slurm-11754135.out.zip)
[bcbio-ipengine.err.11754214_2.log](https://github.com/bcbio/bcbio-nextgen/files/1885124/bcbio-ipengine.err.11754214_2.log)
[bcbio-ipengine.err.11754214_3.log](https://github.com/bcbio/bcbio-nextgen/files/1885125/bcbio-ipengine.err.11754214_3.log)
[bcbio-ipengine.err.11754214_4.log](https://github.com/bcbio/bcbio-nextgen/files/1885126/bcbio-ipengine.err.11754214_4.log)
[bcbio-ipengine.err.11754214_5.log](https://github.com/bcbio/bcbio-nextgen/files/1885127/bcbio-ipengine.err.11754214_5.log)
[bcbio-ipengine.err.11754214_6.log](https://github.com/bcbio/bcbio-nextgen/files/1885128/bcbio-ipengine.err.11754214_6.log)
[bcbio-ipengine.err.11754214_7.log](https://github.com/bcbio/bcbio-nextgen/files/1885129/bcbio-ipengine.err.11754214_7.log)
[bcbio-ipengine.err.11754214_8.log](https://github.com/bcbio/bcbio-nextgen/files/1885130/bcbio-ipengine.err.11754214_8.log)

**Comment by roryk** [comment]
Hi Alon,

These engine died messages are showing that the engines that run the code died. Usually this is a symptom of something else happening. There should be log files for the engine and the controllers that might have some more information in them. The engines could have died for a number of reasons; they could have been killed by the scheduler, the nodes may have died or some other thing happened that caused them to die. O2 was taken down earlier this week for a day, do the jobs overlap with that time?

**Comment by alongalor** [comment]
Hey Rory,

Thanks for the message. This job was submitted after O2 was taken down for a day. I can check with Research Computing to see if this could be a problem on their end – but is there anything else that might cause you to think this could be an issue with bcbio? I just attached the relevant error logs in my comment.

Thanks so much for your help,

Alon

**Comment by chapmanb** [comment]
Alon;
Sorry about the memory issues, SLURM requires staying within memory bounds while SGE is much more liberal, hence the new issues on switching to 02.

It looks from the commands log like BaseReacalibratorSpark runs with 16 cores and 66Gb of memory allocated but this doesn't match the memory that the engine gets allocated from your specification above.

I pushed a fix which I believe will resolve this by correctly ensuring `gatk` resource parameters also get considered when setting memory and CPUs for this part of the engine run. If you update to the latest development version (`bcbio_nextgen.py upgrade -u development`) or put those `jvm_opts` under `default` in your `bcbio_system.yaml` file, it should hopefully do the right thing with allocating and using memory.

Thanks much for the help debugging this and hope this gets your analysis running smoothly.

**Comment by alongalor** [comment]
Thanks for the help Brad! 

So just to be clear - I should execute the following command: `bcbio_nextgen.py upgrade -u development` and then edit the `gatk` section in my `bcbio_system.yaml` to read 

```
gatk:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
```

Is that right? 

Thanks a lot,

Alon

**Comment by alongalor** [comment]
Thanks Brad. I actually already had it set to 

```
resources:
   gatk:
      jvm_opts: ["-Xms1g", "-Xmx5g"]
```

when the most recent run failed. 

I will upgrade and change the `bcbio_system.yaml` to read:

```
resources:
   gatk:
      jvm_opts: ["-Xms1g", "-Xmx5g"]
```

Thanks a lot,

Alon

**Comment by alongalor** [comment]
Hi @chapmanb just wanted to follow up on this! Thanks a lot!

**Comment by chapmanb** [comment]
Alon;
Sorry about missing this earlier. I think you do need an upgrade to get GATK parameters recognized here. The issue with the development version missing is fixed now so if you re-run the update and then re-run with your same configuration, I hope it will do the right thing. If not, can you let me know where you're hitting issues now and I can help debug further.
