### ISSUE TITLE
Can switch off the log of cufflinks in transcript assembly?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2361]
Hi, I noticed that cufflinks outputs too many log information in the step of transcript assembly. This leads to the bcbio-nextgen-debug.log file in the log folder is more than 1G. The log information is as below:

> [2018-04-07T05:21Z] master: Timing: transcript assembly
> [2018-04-07T05:21Z] master: ipython: cufflinks_assemble
> [2018-04-07T05:22Z] master: Converting MAPQ scores in /app/datamart/RNAseq-example/seq/work/align/UHRR_rep2/UHRR_rep2_star/UHRR_rep2.bam to be Cufflinks compatible.
> [2018-04-07T05:22Z] cnode01: Converting MAPQ scores in /app/datamart/RNAseq-example/seq/work/align/UHRR_rep3/UHRR_rep3_star/UHRR_rep3.bam to be Cufflinks compatible.
> [2018-04-07T05:22Z] cnode02: Converting MAPQ scores in /app/datamart/RNAseq-example/seq/work/align/HBRR_rep3/HBRR_rep3_star/HBRR_rep3.bam to be Cufflinks compatible.
> [2018-04-07T06:26Z] cnode01: Assembling transcripts with Cufflinks using /app/datamart/RNAseq-example/seq/work/align/UHRR_rep3/UHRR_rep3_star/UHRR_rep3-cufflinks.bam.
> [2018-04-07T06:27Z] cnode01: Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu
> ).
> [2018-04-07T06:27Z] cnode01: [14:27:04] Inspecting reads and determining fragment length distribution.
> [2018-04-07T06:41Z] master: Assembling transcripts with Cufflinks using /app/datamart/RNAseq-example/seq/work/align/UHRR_rep2/UHRR_rep2_star/UHRR_rep2-cufflinks.bam.
> [2018-04-07T06:41Z] master: Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu)
> .

> [2018-04-07T06:41Z] master: [14:41:24] Inspecting reads and determining fragment length distribution.
> > Processing Locus chr1:793210-794956          [                         ]   1%
> > Processing Locus chr1:813690-810968          [                         ]   1%
> > Processing Locus chr1:836907-837113          [                         ]   1%
> > Processing Locus chr1:906510-911465          [                         ]   1%
> > Processing Locus chr1:921050-921163          [                         ]   1%
> > Processing Locus chr1:926595-926737          [                         ]   1%
> > Processing Locus chr1:930688-930557          [                         ]   1%
> > Processing Locus chr1:935896-1004041         [                         ]   1%
> > Processing Locus chr1:1008114-1008261        [                         ]   1%
> > Processing Locus chr1:1015692-1015799        [                         ]   1%
> > Processing Locus chr1:1059664-1059837        [                         ]   1%
> > Processing Locus chr1:1071435-1071345        [                         ]   1%
>  .............................................

Too many log lines such as "Processing Locus chr1...... " make it hard to find the useful debug information in the case of error occurred. So, could you switch off the verbose mode of cufflinks in transcript assembly?

**Comment by roryk** [comment]
Thank you. Sorry about that, that is an oversight, we have it turned off for quantification but not for assembly. I added `--quiet` to the assembly call.
