### ISSUE TITLE
Errors while downloading VEP data

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2363]
```
--2018-04-09 09:36:51--  ftp://ftp.ensembl.org/pub/release-92/variation/VEP/homo_sapiens_merged_vep_92_GRCh37.tar.gz
           => ‘homo_sapiens_merged_vep_92_GRCh37.tar.gz’
Resolving ftp.ensembl.org... 193.62.193.8
Connecting to ftp.ensembl.org|193.62.193.8|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/release-92/variation/VEP ... done.
==> SIZE homo_sapiens_merged_vep_92_GRCh37.tar.gz ... done.

==> PASV ... done.    ==> RETR homo_sapiens_merged_vep_92_GRCh37.tar.gz ... 
No such file ‘homo_sapiens_merged_vep_92_GRCh37.tar.gz’.
```

Occurs with up-to-date version (from master) even with a clean tmpbcbio-install.

**Comment by lbeltrame** [comment]
The reason is that apparently version 92 is not suploed for GRCh37.

**Comment by chapmanb** [comment]
Luca -- thanks for the heads up on this. You're right on that version 91 had 38 and 37 releases but 92 does not. @matthdsm do you know if this is an oversight or if Ensembl is no longer supporting build 37 going forward with VEP? Any thoughts if keeping that at build 91 is the best thing to do?

**Comment by lbeltrame** [comment]
I've been reading the docs and at least in what's online there's the claim that 92 still has hg19, however those pages may be as well been updated by a script, so there's no definitive proof.

**Comment by lbeltrame** [comment]
Hm, it looks it was an oversight:

https://github.com/Ensembl/ensembl-vep/issues/184

**Comment by chapmanb** [comment]
Thanks Luca, it looks like they're up now so hopefully all is working cleanly again. Sorry about the issues with this.
