### ISSUE TITLE
configuration file of gemini, cadd and gnomad

### ISSUE THREAD

**Issue by jich-MCTP** [bcbio/bcbio-nextgen#2364]
Hi, 

I have installed gemini, cadd and gnomad data to bcbio. If I want to run with these data, how can I change configuration file? I did't find a templates config file for them? 

Thanks!

**Comment by jich-MCTP** [comment]
Thank you!
Is it possible I run only exac, cosmic, cadd or gnomad? Thanks!

**Comment by chapmanb** [comment]
This all uses vcfanno so you can create your own configuration file that annotates with just the things you want and then pass this to the `vcfanno` input referenced in the documentation above. The starting configuration files we have pre-built are here:

https://github.com/bcbio/bcbio-nextgen/blob/master/config/vcfanno/

Hope this helps.
