### ISSUE TITLE
How to pass parameters to star alinger from yaml?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2368]
Hi, I want to pass the option --alignEndsType EndToEnd to the star aligner, and I edit the yaml file as below:

> 
> upload:
>   dir: ../final
> details:
>   - analysis: RNA-seq
>     algorithm:
>       fusion_caller: [pizzly]
>       variantcaller: [gatk-haplotype]
>       transcriptome_align: True
>       aligner: star
>       quality_format: standard
>       #trim_reads: read_through
>       #adapters: [truseq, polya]
>       #tools_on: [gatk4]
>       expression_caller: [stringtie, salmon]
>       transcript_assembler: [cufflinks, stringtie]
>       #spikein_fasta: ../data/spikeins/spikeins.fa
>     metadata:
>       batch: TestBatch1
>     description: Test1
>     resources:
>       star:
>         options: ["--alignEndsType", "EndToEnd"]
>         cores: 12
>         memory: 5G
>     genome_build: rn6
> 

The config file is successfully generated, but this options are not passed to the star aligner. I checked the commands in the log/bcbio-nextgen-commands.log file and the alignment command did not include this options. Please see the following command:
```
 /app/smartngs/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /app/smartngs/bcbio/genomes/Rnorvegicus/rn6/star/ --readFilesIn <(gunzip -c /ap
p/datamart/jieyi_bio/input/3_21D_rep1_R1.fastq.gz) <(gunzip -c /app/datamart/jieyi_bio/input/3_21D_rep1_R2.fastq.gz) --runThreadN 12 --outFileNamePrefix /app/datamart/j
ieyi_bio/rat_star2/work/bcbiotx/tmp5JRnxX/3_21D_rep1/3_21D_rep1 --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd BAM_Unsorted  --limitOutSJcollapsed 2000000
 --outSAMtype BAM Unsorted --outSAMmapqUnique 60 --outSAMunmapped Within --outSAMattributes NH HI NM MD AS  --sjdbGTFfile /app/smartngs/bcbio/genomes/Rnorvegicus/rn6/rn
aseq/ref-transcripts.gtf  --sjdbOverhang 150  --outSAMattrRGline ID:3_21D_rep1 PL:illumina PU:3_21D_rep1 SM:3_21D_rep1  --chimSegmentMin 12 --chimJunctionOverhangMin 12
 --chimScoreDropMax 30 --chimSegmentReadGapMax 5 --chimScoreSeparation 5 --chimOutType WithinBAM  --outSAMstrandField intronMotif  --quantMode TranscriptomeSAM  | /app/
smartngs/bcbio/galaxy/../anaconda/bin/samtools sort -@ 12 -m 1G  -T /app/datamart/jieyi_bio/rat_star2/work/bcbiotx/tmp5JRnxX/3_21D_rep1/3_21D_rep1_star/3_21D_rep1-sortt
mp -o /app/datamart/jieyi_bio/rat_star2/work/bcbiotx/tmp5JRnxX/3_21D_rep1/3_21D_rep1_star/3_21D_rep1.bam /dev/stdin > /app/datamart/jieyi_bio/rat_star2/work/bcbiotx/tmp
5JRnxX/3_21D_rep1/3_21D_rep1_star/3_21D_rep1.bam

```

Is there any other way to pass options to star aligner, or my yaml is not correctly configured? Thanks a lot.

**Comment by chapmanb** [comment]
Thanks much for the suggestion and apologies about the issue. We didn't have the ability to pass custom options to STAR like this, but added support for it in the latest development version. If you update (`bcbio_nextgen.py upgrade -u development`) and then re-run with your same YAML it should work as you expect. Thank you again for the report.
