### ISSUE TITLE
Installing bcbio error

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2376]
Hi, I tried to install bcbio using the `python bcbio_nextgen_install.py` command. However, the installation failed because some packages can be download. But in fact I can download these packages via browser. How to work through this problem?

> CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/conda-forge/linux-64/bokeh-0.12.15-py27_0.tar.bz2>
> Elapsed: 01:01.070696
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/phylowgs-20180317-py27_1.tar.bz2>
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/conda-forge/linux-64/r-mvtnorm-1.0_6-r3.4.1_0.tar.bz2>
> Elapsed: 01:10.281952
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> 
> 
> 
> Fatal error: local() encountered an error (return code 1) while executing '/app/smartngs/bcbio/anaconda/bin/conda install -y  -c conda-forge -c bioconda age-metasv bamtools=2.4.0 bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-................

**Comment by hliu2016** [comment]
Sorry, I have solved this problem.

**Comment by chapmanb** [comment]
Thanks for following up, glad it's working now. Feel free to re-open if you hit other problems.
