### ISSUE TITLE
Salmon quant.sf expression files are not combined, but the featurecount and stringtie files are combined?

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2378]
Hi,

I am processing RNAseq data with bcbio 1.0.8. 

```
The yaml that I used is:
# Template for  RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: my_reference
    algorithm:
      aligner: star
      strandedness: unstranded
      transcript_assembler: [stringtie, cufflinks]
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
upload:
   dir: ../final
```

Featurecount, Salmon and stringtie I think where run for quantification.  Per sample I end up with these output files in the final directory.

```
DA_1165_01/
DA_1165_01/qc
DA_1165_01/qc/fastqc
DA_1165_01/qc/fastqc/fastqc_report.html
DA_1165_01/qc/fastqc/fastqc_data.txt
DA_1165_01/qc/fastqc/DA_1165_01.zip
DA_1165_01/qc/fastqc/Per_base_sequence_quality.tsv
DA_1165_01/qc/fastqc/Per_sequence_quality_scores.tsv
DA_1165_01/qc/fastqc/Per_base_sequence_content.tsv
DA_1165_01/qc/fastqc/Per_sequence_GC_content.tsv
DA_1165_01/qc/fastqc/Per_base_N_content.tsv
DA_1165_01/qc/fastqc/Sequence_Length_Distribution.tsv
DA_1165_01/qc/fastqc/Sequence_Duplication_Levels.tsv
DA_1165_01/qc/samtools
DA_1165_01/qc/samtools/DA_1165_01.txt
DA_1165_01/qc/samtools/DA_1165_01-idxstats.txt
DA_1165_01/DA_1165_01-ready.bam
DA_1165_01/DA_1165_01-ready.bam.bai
DA_1165_01/DA_1165_01-transcriptome.bam
DA_1165_01/DA_1165_01-ready.counts
DA_1165_01/stringtie
DA_1165_01/stringtie/DA_1165_01.fpkm
DA_1165_01/stringtie/t_data.ctab
DA_1165_01/stringtie/e_data.ctab
DA_1165_01/stringtie/i_data.ctab
DA_1165_01/stringtie/e2t.ctab
DA_1165_01/stringtie/i2t.ctab
DA_1165_01/stringtie/stringtie-assembly.gtf
DA_1165_01/stringtie/DA_1165_01.isoform.fpkm
DA_1165_01/DA_1165_01-gatk-haplotype.vcf.gz
DA_1165_01/salmon
DA_1165_01/salmon/logs
DA_1165_01/salmon/logs/salmon_quant.log
DA_1165_01/salmon/libParams
DA_1165_01/salmon/libParams/flenDist.txt
DA_1165_01/salmon/aux_info
DA_1165_01/salmon/aux_info/bootstrap
DA_1165_01/salmon/aux_info/bootstrap/bootstraps.gz
DA_1165_01/salmon/aux_info/bootstrap/names.tsv.gz
DA_1165_01/salmon/aux_info/fld.gz
DA_1165_01/salmon/aux_info/expected_bias.gz
DA_1165_01/salmon/aux_info/observed_bias.gz
DA_1165_01/salmon/aux_info/observed_bias_3p.gz
DA_1165_01/salmon/aux_info/obs_gc.gz
DA_1165_01/salmon/aux_info/exp_gc.gz
DA_1165_01/salmon/aux_info/meta_info.json
DA_1165_01/salmon/aux_info/ambig_info.tsv
DA_1165_01/salmon/cmd_info.json
DA_1165_01/salmon/quant.sf
DA_1165_01/salmon/lib_format_counts.json
DA_1165_01/salmon/abundance.h5
```

In the project final directory I have these files.
```
2018-04-12_DA_1165_samples-merged/
2018-04-12_DA_1165_samples-merged/programs.txt
2018-04-12_DA_1165_samples-merged/bcbio-nextgen.log
2018-04-12_DA_1165_samples-merged/bcbio-nextgen-commands.log
2018-04-12_DA_1165_samples-merged/project-summary.yaml
2018-04-12_DA_1165_samples-merged/multiqc
2018-04-12_DA_1165_samples-merged/multiqc/multiqc_report.html
2018-04-12_DA_1165_samples-merged/multiqc/report
2018-04-12_DA_1165_samples-merged/multiqc/report/metrics
2018-04-12_DA_1165_samples-merged/multiqc/multiqc_config.yaml
2018-04-12_DA_1165_samples-merged/multiqc/multiqc_data
2018-04-12_DA_1165_samples-merged/multiqc/multiqc_data/multiqc_data_final.json
2018-04-12_DA_1165_samples-merged/multiqc/list_files_final.txt
2018-04-12_DA_1165_samples-merged/DA_1165-gatk-haplotype-annotated.vcf.gz
2018-04-12_DA_1165_samples-merged/DA_1165-gatk-haplotype-annotated.vcf.gz.tbi
2018-04-12_DA_1165_samples-merged/combined.counts
2018-04-12_DA_1165_samples-merged/annotated_combined.counts
2018-04-12_DA_1165_samples-merged/combined.fpkm
2018-04-12_DA_1165_samples-merged/combined.isoform.fpkm
2018-04-12_DA_1165_samples-merged/merged.gtf
2018-04-12_DA_1165_samples-merged/tx2gene.csv
2018-04-12_DA_1165_samples-merged/transcriptome
2018-04-12_DA_1165_samples-merged/transcriptome/my_reference.fa
```

I guess that the following two files are based on the per sample FeatureCount `-ready.counts `expression files:
- annotated_combined.counts
- combined.counts

And that the following two are based on the per sample stringtie `isoform.fpkm`  files:
- combined.fpkm
- combined.isoform.fpkm

I don't see any merged `quant.sf` or `combined.tpm` files. 

This function in the bcbio code indicates that there also should be a combined TPM output file. 
https://github.com/bcbio/bcbio-nextgen/blob/112d2550fffbfbad108ef3094563c0081714db57/bcbio/pipeline/rnaseq.py#L232

Is there a way to also get the combined Salmon TPM file by default from bcbio? 

Also it might be useful to make a more explicit connection between which input tool was used for which combined output expression file.  

Now this has to be 'guessed' base on the extension (quant, tpm or fkpm).  I am also wondering what happens if multiple quantification tools are ran that have the same fkmp or tpm normalized output.   Using the name of the quantification tool in the file name or as a subdirectory name might be useful. 

Thank you.

**Comment by roryk** [comment]
Hi @WimSpee,

Thanks for the note, sorry I know it is confusing. We stopped combining the output from Salmon because we lose information that way. The proper way to produce a similar table from the Salmon files is to load them into R with tximport (https://bioconductor.org/packages/3.7/bioc/vignettes/tximport/inst/doc/tximport.html). If we jam everything into a count table we'll lose the ability to do estimated length correction and to make use of the bootstrap replicates. Since featureCount and StringTie don't have that extra information it makes sense to combine them at the count level.

We're working on automatically running the quality control in bcbioRNASeq at the end of a bcbio RNA-seq run, which will do this tximport step automatically as well as make a bunch of useful quality control figures (see https://github.com/hbc/bcbioRNASeq and https://f1000research.com/articles/6-1976/v1). Hopefully we'll have that all set for the next release.
