### ISSUE TITLE
Issue with chip-seq analysis in bcbio

### ISSUE THREAD

**Issue by evchambers** [bcbio/bcbio-nextgen#2385]
Hello!

I am having an issue where there seems to be an error in my bcbio chip-seq analysis.  I am running the standard chip-seq pipeline on some Chinese hamster (CHOK1GS_HDv1) data.

It seems to be carrying out alignments OK but then stops with an error during clean_chipseq_alignment . Does anyone know what the issue might be? The last lines of the log file are

  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 363, in clean_chipseq_alignment
    return chipseq.clean_chipseq_alignment(*args)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/chipseq/__init__.py", line 34, in clean_chipseq_alignment
    data["bigwig"] = _bam_coverage(dd.get_sample_name(data), dd.get_work_bam(data), data)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/chipseq/__init__.py", line 60, in _bam_coverage
    size = int(get_genome(dd.get_genome_build(data)))
TypeError: int() argument must be a string or a number, not 'NoneType'

The .yaml template I am using is

# Chipseq template
---
details:
    analysis: chip-seq
    genome_build: CHOK1GS_HDv1
    metadata:
     batch: #sample information
     phenotype: #chip or input
    algorithm:
     aligner: bowtie2
     adapters: [truseq]
     trim_reads: atropos
     peakcaller: [macs2]
    resources:
     macs2:
       options: ["--broad", "-q 0.05"]

**Comment by roryk** [comment]
Hi Emily,

Thanks for the super good bug report and sorry about the problem. We were only supporting a few common genomes for ChIP-seq; there is a calculation that macs2 needs which is the effective size of the genome which we have hard-coded for the few supported genomes. I added functionality to replace this metric with just the number of bases in genome if it is not one of the hard-coded ones. Let me know how this works on your hamster samples.

**Comment by evchambers** [comment]
Thanks Rory, I will give it a go and let you know!
