### ISSUE TITLE
How to maximise efficiency?

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#2391]
Hi,

I've been having trouble figuring out how to get bcbio to parallelise efficiently on the system I'm using, and I'm hoping you can give me some advice.

The system is a cluster of four machines with 62, 62, 46 and 44 cpus and a shared filesystem for working data and applications. I initially set `cores: 20` so that users could then set `-n 60` or `-n 40` depending which machine they were running their jobs on. This resulted in jobs running at about half the efficiency I'd expect (i.e. load averages maxing out around 20 with `-n 40`). I then tried setting `cores` to a smaller number, which has increased efficiency somewhat, but load averages are still not as high as I'd expect, particularly when running GATK.

Do you have any recommendations on how to configure bcbio for this kind of system? Or would you not expect more efficient resource use?

Thanks in advance,
Bennet

**Comment by chapmanb** [comment]
Bennet;
Thanks for the question and sorry for the efficiency issues. It sounds like you have a good general approach to maximizing your cluster usage, allocating 20 cores for multicore processes and then scaling cores with `-n` to match the number of samples makes good sense. When you're finding bcbio running under efficiency, how many samples were you processing? It sounds like you're running GATK germline variant calling, is that correct? Are these WGS or exome samples? What types of overall runtimes are you seeing? If you only have a single sample around 20 cores is reasonable for what you could max out. Most of the efficiency has been designed around getting larger numbers of samples through rather than a single sample as quick as possible with a ton of cores. The later requires more aggressive splitting of regions to parallelize more, and most of the cases we deal with require overall sample throughput rather than single sample maximum speed turnaround.

Does this help somewhat with your evaluations? If you provide more details about what you're running happy to provide more specific suggestions.

**Comment by DrMcStrange** [comment]
Thanks for your help.

Mostly we're running WGS germline variant calling, on anywhere from about 5 to 100-odd samples. FreeBayes runs much faster than GATK, but has its own issues in terms of post-processing (with its weird AD fields). One of our students recently ran variant calling jobs on a few small genomic regions with 240 samples, using both GATK and FreeBayes. The FreeBayes run took just under 11 hours; GATK took a week.

I kicked off a couple of test runs today, again calling with both GATK and FreeBayes, on 10 WGS samples, with `-n 40`, and they've both now reached the calling stage. According to top, the GATK job is running two processes, `bcbio_nextgen.py` using 100% cpu, and one java process also using 100% cpu but occasionally spiking briefly to around 1000%. The FreeBayes job was at the other extreme a few minutes ago, with a large number of processes using about 10% cpu each (most with status D at any given time), and load average around 300 (on a 62-core machine). Now it's running a bunch of bedtools processes, with load average around 40, which seems much more sensible!

I did notice a warning message early on in STDOUT when I started both these jobs:

> /gd/apps/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
>   **self._backend_args)

Could this be related, or is it a red herring?

Anyway, sorry if this is all a bit muddled, and thanks again for your help.

**Comment by DrMcStrange** [comment]
Thanks Brad. We're running multicore, so that explains at least some of the inefficiency with the GATK runs. Still, I'm surprised that it only seems to run one job at a time. Anyway, I look forward to the CWL implementation, but I'll look into getting a scheduler set up in the meantime.

However, I'm now more concerned about the blow-out that's happening with the FreeBayes run! I've done a full FreeBayes variant calling run on 70 WGS samples before without any issues, but for some reason this test run on ten samples cranked the load up to 300 and crashed the machine. I suppose a scheduler would fix that too, but again it's not the sort of behaviour I'd expect.

**Comment by chapmanb** [comment]
Bennet;
Thanks for exploring using your cluster scheduler, I hope that will help with more efficiently scheduling jobs and is the general way we recommend as you get larger numbers of samples.

For FreeBayes, the overscheduling is definitely unexpected and I'm not sure why you're seeing that behavior. How many simultaneous FreeBayes processes do you see running? FreeBayes has a pretty big pipe with a lot of cleanup jobs so you'll have multiple programs running but the overall load for each should be around 1 since they pipe into each other. Could that explain the multiple processes or do you see more than 40 simultaneous FreeBayes jobs happening? Regarding load I'm not sure why this is but could be filesystem IO bottlenecks. Is that a possibility?

Hope this helps some and thanks for the work debugging.

**Comment by DrMcStrange** [comment]
I suspect you're right about IO bottlenecks - it fits with most of the processes being in D. I restarted the run just now, and load got up to 360 with 37 FreeBayes processes running (plus lots of other assorted processes) before I killed it. I'll have a chat with our sysadmin, but it's strange that it worked smoothly for a full run before.

Thanks for your help.

**Comment by DrMcStrange** [comment]
Hi Brad,

The issues above seem to have worked themselves out - I've got a couple of full-scale runs going now, one on about 240 exomes with GATK and one on 70 whole genomes with FreeBayes, and they're using resources at full efficiency now that they've reached the variant calling stage.

However, the alignment processing step was very slow, only processing two BAMs at a time (using a single core each, on a 60-core machine). The resource requests for the GATK run were as follows (and very similar for the FreeBayes job). At the start of the run:

`[2018-06-25T23:57Z] Resource requests: sambamba, samtools; memory: 8.00, 8.00; cores: 20, 20
[2018-06-25T23:57Z] Configuring 2 jobs to run, using 20 cores each with 160.1g of memory reserved for each job
`

And then before the variant calling:

`[2018-06-29T12:48Z] Resource requests: gatk, gatk-haplotype, picard; memory: 8.00, 8.00, 8.00; cores: 1, 20, 20
[2018-06-29T12:48Z] Configuring 57 jobs to run, using 1 cores each with 8.00g of memory reserved for each job
`

Is there a good reason for it to be setting up 20-core samtools jobs and then only using one core each?

**Comment by chapmanb** [comment]
Bennet and Paulo;
Thanks for the details and additional debugging. Bennet, in your initial setup it looks like bcbio correctly allocates 2 20-core jobs as requested in your configuration so the important question is to figure out why it's not using more cores. If you look at the commands being run in `log/bcbio-nextgen-commands.log`, is bwa supplied with multiple cores? What commands did you see running with a single core that seemed to be taking a long time. Not all steps in all processes can use multiple cores but in general it should be trying to allocate all the cores you made available. If you could provide more details about what you see running single core I'd be happy to provide more specific advice. Thanks again for the help debugging this.

**Comment by DrMcStrange** [comment]
Thanks Paulo, that did help a lot!

I set core usage for samtools and sambamba to 1 in the resources section of the config for the run, and now it's using one core per sample, which is nice. I'm not sure I want to set the defaults globally before having a good look at whether it will mess with other types of run (or other steps in the run).

Brad, the commands that are using a single core are:

```
[2018-07-01T13:31Z] samtools view -h /home/bennetm/cataract/bcbio_gatk/cataract-new/work/bcbiotx/tmpiktlcP/CGW73-02.churchill.bam chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY | /gd/apps/bcbio/anaconda/bin/python -c 'from bcbio.pipeline import cleanbam; cleanbam.fix_header("/gd/apps/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa")' | samtools view -u - | samtools addreplacerg -r '@RG\tID:CGW73-02\tPL:illumina\tPU:CGW73-02\tSM:CGW73-02' -m overwrite_all -O bam -o /home/bennetm/cataract/bcbio_gatk/cataract-new/work/bcbiotx/tmpiktlcP/CGW73-02-noextras.bam - 
```

and

```
[2018-07-02T04:05Z] /gd/apps/bcbio/galaxy/../anaconda/bin/samtools index -@ 20 /home/bennetm/cataract/bcbio_gatk/cataract-new/work/bamclean/CGW73-02/CGW73-02-noextras.bam /home/bennetm/cataract/bcbio_gatk/cataract-new/work/bcbiotx/tmp7Pvex7/CGW73-02-noextras.bam.bai
```

That second one looks to me like it should be using 20 cores, but it doesn't.

Anyway, it's working for me now, but it may still be worth looking at why resources aren't being allocated optimally by default.

**Comment by chapmanb** [comment]
Bennet;
Thanks much for the details and feedback. Allocating less cores for pre-aligned BAM inputs makes a lot of sense. These end up being IO bound so potentially running multiple in parallel will go faster than trying to do one at a time with more allocated cores. It might take some testing to see what gives you the best throughput on your system as disk access will probably be the limiting factor.

I've pushed a fix to use multiple cores for the samtools view and addreplacerg commnds, which should hopefully help some with speed when allocating multiple cores. Thanks for identifying that as a potential bottleneck.

For the index command, it is correctly allocated 20 cores for running. If you don't see that in practice maybe it's saturated reading from the BAM from disk, or you were watching in part of the process where the algorithm itself isn't effectively using cores. It's a bit hard to say remotely but I'd definitely have interest in finding out what you find by tweaking and if there is anything we can do to improve it.

Glad to hear your analysis runtimes are improved with the core allocation change and thanks again for all the helpful feedback. Please let us know if there are any other tweaks that might be useful to help.

**Comment by DrMcStrange** [comment]
Thanks for that fix, and I'm glad this has been useful.

Yes, it does make sense that IO would be limiting when processing BAMs. Allocating a single core per job certainly sped up the process overall by processing many more samples in parallel, but the individual jobs took about 50% longer to run. I'll do some testing as you suggest, but it will have to wait until the current runs have finished - my servers are all working hard right now! I suspect optimisation will be rather system-specific though.

**Comment by roryk** [comment]
Looks like this discussion has run its course, so closing. Thank you!
