### ISSUE TITLE
featureCount --minOverlap seems not functioning

### ISSUE THREAD

**Issue by yiyimanew** [bcbio/bcbio-nextgen#2394]
From the IGV, I have seen one read only has 1bp overlap with the feature I am interested in. So, without setup any integer value to the --minOverlap, the output count report 1 read for that feature. However, even after I change the --minOverlap to 5 or 10, the output count file still reported 1 read for that feature, which should be filtered out.

Does this meant that the --minOverlap in featureCount is not functioning. 

Thank you!
Yiyi

**Comment by chapmanb** [comment]
Yiyi;
Thanks much for the report. Can you provide a bit more context about how you're making use of featureCounts in bcbio and tweaking the minOverlap parameter? Your description sounds right in that is what `--minOverlap` is meant to do, but it strikes me that maybe the parameter is not applied in bcbio as intended depending on how specify it.

**Comment by roryk** [comment]
Closing, as this is stale and there wasn't any followup.
