### ISSUE TITLE
CWL: Support also soft-link localizations with Cromwell

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2396]
Unless it's default along with hard-link: with my early attempts, I get lots of log spam due to invalid cross-device links (analysis folders are bind-mounted from another share, and bcbio stays on a completely different shared resource).

**Comment by chapmanb** [comment]
Luca -- thanks for the heads up on the logging noise. Cromwell will fall back to soft-linking, then copying, if the hard-link fails but I agree that a ton of logging noise can be a problem. I swapped over bcbio to only use soft-linking here, which to me is more understandable and should hopefully work consistently everywhere. I'll follow up in the biovalidation thread (https://groups.google.com/d/msg/biovalidation/ejKh_hd-mvE/pC3JPRQ5BwAJ) when the package and everything is updated.
