### ISSUE TITLE
GRCz10 (zebrafish) rnaseq problem.

### ISSUE THREAD

**Issue by drj11** [bcbio/bcbio-nextgen#2397]
We're having a problem with rnaseq analyses for `GRCz10`.

It may be similar to https://github.com/bcbio/bcbio-nextgen/issues/2338

At some point it looks like bcbio is trying to pass `None` as the name of a file to STAR aligner.

```
[2018-04-09T09:32Z] Running STAR aligner on /shared/bioinformatics_core1/Shared/wip/henriques_rnaseq/merged_fastq/B11.fastq.gz and /usr/local/community/bcbio-nextgen/2017-08/data/genomes/Drerio_Zebrafish/GRCz10/star/
[2018-04-09T09:32Z] FATAL error, could not open file sjdbGTFfile=None
```

log file and yaml file attached.

[bcbbio.log](https://github.com/bcbio/bcbio-nextgen/files/1983354/bcbbio.log)

[project-merged.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/1983357/project-merged.yaml.txt)

**Comment by lpantano** [comment]
Hi,

sorry for the issue. Can you tell me if you have a rnaseq folder in  /usr/local/community/bcbio-nextgen/2017-08/data/genomes/Drerio_Zebrafish/GRCz10?

As well, how did you install that data?

Thanks

**Comment by drj11** [comment]
We don't have an `rnaseq` folder, and I had intended to mention that.

after a previous install, I installed that genome with:

```
/usr/local/extras/bcbio-nextgen/2017-08/tool/bin/bcbio_nextgen.py upgrade -u stable --tools --data --datatarget variation --datatarget rnaseq --datatarget smallrna --genomes GRCz10
```

Apparently because I was skeptical that the default was installing the rnaseq for that genome.

**Comment by lpantano** [comment]
Hi,

Thanks for the information.

It seems with the standard installation we don’t have the RNAseq.

You may want to follow the instructions here to setup a genome with RNASeq data:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#adding-custom-genomes <https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#adding-custom-genomes>

You mainly need the GTF for that species.

Are you planning to run small RNA pipeline as well?

Cheers

**Comment by drj11** [comment]
ah, great. Already added CHO as a custom genome so I can probably do the same for _Danio rerio_. Thanks for the pointers!

**Comment by drj11** [comment]
(I don't think we're planning on doing smallrna, that was for completeness)

**Comment by chapmanb** [comment]
David -- thanks much for the report on this and hope the custom genome approach worked for you. I pushed support for the latest Zebrafish build, GRCz11, including the input files for RNA-seq. So if you're stuck with the custom build or want to migrate, the new version should have RNA-seq support and transcript information included. Please let us know if you run into any issues at all, and thanks again for letting us know about the problem.
