### ISSUE TITLE
NotWritableError during installation

### ISSUE THREAD

**Issue by genome1** [bcbio/bcbio-nextgen#2398]
The bcbio-nextgen installation script worked on the same system before about several months ago, but now I am encountering this error with the current version. This is a conda issue, but because bcbio depends on conda for installation, I think there must be a workaround in the bcbio install script. When I run bcbio_nextgen_install.py standalone, it runs OK until it is killed by the server due to the time limit. So I have to schedule a job with SLURM. The problem with it is only the work directory is writable, and conda gets into an error while trying to write onto the home folder. Changing permissions following the suggestion below does not work, because the running job is not supposed to write outside the working directory. Even with creating a conda environment under the work directory, conda still tries to write in ~/.conda under home folder. Following is the error message I got.

NotWritableError: The current user does not have write permissions to a required path.
  path: /home/user/.conda/environments.txt
  uid: 2026
  gid: 11181

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 2026:11181 /home/user/.conda/environments.txt

In general, it's not advisable to use 'sudo conda'.

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 260, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 76, in install_conda_pkgs
    subprocess.check_call([anaconda["conda"], "install", "--yes", "conda>=4.4"])
  File "/home/user/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/work/user/parallel/bcbio/anaconda/bin/conda', 'install', '--yes', 'conda>=4.4']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the install issue. I've been trying to dig into resolving this issue and am not sure it's currently possible with conda. The issue looks to be that the environments.txt file is hard coded to the user home directory:

https://github.com/conda/conda/blob/9d792a1995ea960f85012f07a27d7dde2b832cf2/conda/core/envs_manager.py#L20

and then conda runs a `touch` on this and fails if it can't access:

https://github.com/conda/conda/blob/9d792a1995ea960f85012f07a27d7dde2b832cf2/conda/core/path_actions.py#L851

There are a couple of relevant discussions and some partial fixes here:

https://github.com/conda/conda/issues/6748
https://github.com/conda/conda/issues/5388

and we can move some of the directories away from `~/.conda`, which I've done, but I don't see a way currently to avoid needing access to this file.

My best suggestion would be to raise an issue upstream in conda (https://github.com/conda/conda/issues) and reference this thread and digging so far. Feel free to cc me there and I'm happy to provide any more detail or try out changes if it's possible to work around this limitation.

Sorry to not have a definite fix for your issue but hopefully working upstream will help us resolve the issues. Thanks again.

**Comment by genome1** [comment]
I tried to change the conda environment while running the installation but the script still tries to access ~/.conda and could not solve the problem. I posted the issue on conda site (https://github.com/conda/conda/issues/7267) referring to bcbio_nextgen, so please keep watching on it. I appreciate you and your group for prompt and kind support.

**Comment by roryk** [comment]
Thanks, installation issues are likely to be solved at this point, so closing this.
