### ISSUE TITLE
Support options for CNVkit segmentation

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2402]
Use case: using other segmentation methods which may perform better on smaller targeted panels, for example.
I think the usual approach like done for other tools would fit, that is having to add the relevant bits to the YAML configuration.

**Comment by chapmanb** [comment]
Luca;
Thanks so much for the suggestion, the latest development version of bcbio now supports:
```
resources:
  options:
    cnvkit_segment: [--method, haar]
```
This is undocumented as I'd rather not have this used in people's production environments but agree it can be useful for exploring and tweaking. If you find options that work better for different input types, I'd love to incorporate test cases and make these different segmentation approaches happen automatically within bcbio logic. Thanks again for exploring this.
