### ISSUE TITLE
STAR aligner wrapper does not handle old encoding 'fastq-illumina' fastq files.

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2404]
Hi,

I am trying to process a set of RNA-seq samples, some of which are encoded using the Illumina 1.3/1.5 fastq standard. 

This I determined with this script. 
https://github.com/brentp/bio-playground/blob/master/reads-utils/guess-encoding.py

The STAR alignment wrapper script currently does not handle old style fastq files but just invokes STAR, which then crashes with an error about the fastq format. 
The STAR error is something like read names should always start with @ or >. 
All reads names do start with @, I checked this, so I think the real cause of error is the fastq format.

There is a function in the STAR wrapper to determine the input fastq file format:
https://github.com/bcbio/bcbio-nextgen/blob/4fe08f28b39d3cfc9c451d26dff8d7436994f15a/bcbio/ngsalign/star.py#L165

But this function is not called (anymore) in the align function which creates the STAR command. 
https://github.com/bcbio/bcbio-nextgen/blob/4fe08f28b39d3cfc9c451d26dff8d7436994f15a/bcbio/ngsalign/star.py#L23

I added this piece of code to the bcbio STAR align function to convert old style fastq files to the current format.

```
config = data["config"]
    logger.info("determining quality format")
    logger.info("quality format is %s"  %  _get_quality_format(config).lower()  )
    if _get_quality_format(config).lower() == "fastq-illumina":
        logger.info("star does not support the phred+64 quality format, "
                    "converting %s and %s to phred+33.")
        fastq_file = fastq.groom(fastq_file, data, in_qual="fastq-illumina")
        if pair_file:
            pair_file = fastq.groom(pair_file, data, in_qual="fastq-illumina")
```

I inserted this code at exact this place
https://github.com/bcbio/bcbio-nextgen/blob/4fe08f28b39d3cfc9c451d26dff8d7436994f15a/bcbio/ngsalign/star.py#L30

This seems to work.  (still converting now the fastq encoding now) . 

Could you please add this functionality to the bcbio STAR wrapper align function (as it already is for the BWA wrapper). 

Thank you.

**Comment by chapmanb** [comment]
Thanks for the heads up on the problem and for working through the method for fixing this. We were relying on format conversion as part of trimming and wouldn't be switching over when that was not enabled.

I pushed a more general version of your fix that should apply to all aligners by providing grooming when retrieving the fastq files for processing. Please let us know if you run into any other issues and thanks again for catching the problem.

**Comment by WimSpee** [comment]
Thank you Brad for fixing this.

**Comment by WimSpee** [comment]
I b.t.w. copied the piece of code that I inserted from the BWA wrapper. 
https://github.com/bcbio/bcbio-nextgen/blob/9b7b99efdefa1a7ff7702c91a0a2590ef1428af1/bcbio/ngsalign/bwa.py#L246

Maybe that  piece of code in the BWA wrapper now also is redundant with your latest commit.
