### ISSUE TITLE
how do we configure bcbio to support for new barcode mode of single cell sequencing?

### ISSUE THREAD

**Issue by xiaochuanle** [bcbio/bcbio-nextgen#2405]
we producted some datasets using split-pool barcoding method accordding to the published science paper (http://science.sciencemag.org/content/360/6385/176) and this paper and barcode table were added in this message supplementary file . the read1 file（R1.fastq）have only cDNA information and the read2 file (R2.fastq) contain round 1,2,3 and UMI information (please note that UMI and round1,2,3 position and length is fixed). the flowing information from two fastq, how do we configure bcbio to support for new barcode mode of single cell sequencing?
[aam8999_TableS12.zip](https://github.com/bcbio/bcbio-nextgen/files/2044268/aam8999_TableS12.zip)

Read1：                      cDNA sequence
[NTCAAAATACTGCTTTTACAAAAGCAGAATAAAAGCGAAAAGAAATGAAAATGTTACACTACATTAATCCTGGAATAAAAGAAGCCGAAATAAATGAGAGATGAGTTGGGATCAAGGGGCGAGGATGGCGAATGCTCTGGCCTCTCAAGC]

Read2： 
     【UMI】                             【 round 3 index】                     【round 2 index】
[CCTTGTTGCG] [AATGTTGCGTGGCCGATGTTTCG] [CATCGGCGTACGACTGCGAGTAA
                                              【round 1 index 】
ATCCACGTGCTTGAG]  [AGGCCAGAGCATTCGCCATCCTC][GCCCCTTGATCCCAACTCA
               cDNA sequence
TCTCTCATTTATTTCGGCTTCTTTTATTCCAGGATTA]

**Comment by mjsteinbaugh** [comment]
Thanks @xiaochuanle, I'm looking into this barcoding method. We currently provide support for the popular droplet-based methods (e.g. inDrops, Drop-seq) but we'll work on adding split-pool support as well.

**Comment by lpantano** [comment]
Hi @xiaochuanle, @roryk is the one who knows more about it and he probably has an idea how to add it. However he is on holidays, so it may takes some days to get into that. I think he uses this for the UMIs identification: https://github.com/vals/umis.

Thanks!

**Comment by xiaochuanle** [comment]
Thank you for your reply ! We should look forward to hearing from your furture information about this project!

**Comment by roryk** [comment]
Thanks, so, so sorry we dropped the ball on this. Please re-open if there is a new barcoding scheme you want to use, and I will help you write the proper transformation file to use it.
