### ISSUE TITLE
Integrate all GiaB samples for validation

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2408]
NA24149 and NA24143 have not yet been integrated into the standard bcbio installation. This would be so convenient for testing.

**Comment by chapmanb** [comment]
Ben;
Great suggestion, thank you. I've added these to the install so they're now included in the standard installation. Please let me know if you run into any problems at all, and thanks again.

**Comment by gabeng** [comment]
Great, thanks so much!

**Comment by gabeng** [comment]
Hi Brad,

I am trying to install the new validation data sets via `bcbio_nextgen.py upgrade -u development --data --datatarget variation --aligners bwa`, but this does not seem to trigger the installation.
Any hints how I can add these data sets to bcbio?

**Comment by chapmanb** [comment]
Ben;
Apologies, this is my mistake. I'd forgotten to also update the data targets. If you re-run a `--data` install it should now add these. Please let me know if you hit any other issues and thanks much for testing this out.
