### ISSUE TITLE
Should GTF be used with STAR indexing ?

### ISSUE THREAD

**Issue by biocyberman** [bcbio/bcbio-nextgen#2415]
Currently build STAR index(bcbio-nextgen version 1.0.9) does not use GTF information. Please check the log.
[bcbiostar.txt](https://github.com/bcbio/bcbio-nextgen/files/2089471/bcbiostar.txt)

I can run this manually:

 ```
export PATH=/mnt/bcbio/bin:$PATH && STAR --genomeDir /mnt/bcbio/genomes/Hsapiens/hg38/star --genomeFastaFiles /mnt/raidlv16t/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --runThreadN 10 --limitGenomeGenerateRAM 30000000000 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 
14 --sjdbGTFfile /mnt/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf 
```

I can make a PR for this if it is something should be generalized. What do you think Brad @chapmanb ?

Vang

**Comment by roryk** [comment]
Hi Vang,

We don't build the STAR index with the GTF anymore, and instead use the option to include it while mapping. See https://github.com/bcbio/bcbio-nextgen/blob/7a82611b94786689e4c5668a1c7340b440c96240/bcbio/ngsalign/star.py#L117 for the function that does this step.
