### ISSUE TITLE
Feature Request: Add AD tag to samtools mpileup

### ISSUE THREAD

**Issue by mbootwalla** [bcbio/bcbio-nextgen#2416]
Hello bcbio team,

I would like to request the addition of the AD tag to the -t option in the call to samtools mpileup within bcbio/variation/samtools.py. Addition of the AD tag makes the output for the total depth and allelic depths standard with that from other variant callers and is useful for downstream processing with gemini. Without the AD tag the allelic depths for variants called by samtools are not reported and this results in gemini assigning a value of -1 for the DP and AD fields when storing the variants in the gemini db (refer to following issue for more details https://github.com/arq5x/gemini/issues/880).

Thanks,

Moiz

**Comment by chapmanb** [comment]
Moiz;
Thanks for the great suggestion. I added this in the latest development version so if you update with `bcbio_nextgen.py upgrade -u development` it now produces AD fields and will hopefully integrate better with GEMINI. Thank you again and please let us know if you run into any problems.

**Comment by mbootwalla** [comment]
Thank you Brad for the quick update. I will test and report back if I run into any issues.
