### ISSUE TITLE
altering gatk haplotypeCaller parameters 

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2418]
Does anyone know how to adjust the haplotypeCaller parameters when runnign bcbio? For example, this is a default for gatk 3.8:
standard_min_confidence_threshold_for_calling=10.0 

How do I change it to 0? 

Is this hard coded in a bcbio config file somewhere? Can we change it in the sample yaml file for example? 

thanks - Robert

**Comment by chapmanb** [comment]
Robert;
You can change custom parameters for HaplotypeCaller with resources options in your sample YAML file:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#sample-or-run-specific-resources

So having:
```
resources:
  gatk-haplotype:
    options: [--standard_min_confidence_threshold_for_calling=0.0]
```
Practically that's going to generate a ton of noise as you'll be emitting a lot of low quality calls.

Hope this helps.

**Comment by RobertWBaldwin** [comment]
yes thank please close ticket
