### ISSUE TITLE
BQSR with GATK with bcbio: SPARK warning

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2419]
Hi,

I just downloaded and used bcbio with whatever GATK4 was in there. I'm analyzing WGS data. I got this message when doing BQSR:  

Warning: BaseRecalibratorSpark is a BETA tool and is not yet ready for use in production

I'm running clinical samples here and don't want to mess around. What happened to normal BQSR? Why is it defaulting to SPARK ( whatever that is )? And which should I use? Or should I Just not use BQSR and go right to haplotypeCaller? 

thnaks - Robert

**Comment by chapmanb** [comment]
Robert;
Sorry about the confusion with this. BaseRecalibratorSpark is the parallelized version of BaseRecalibrator in GATK4. The non-parallel version is also there but is so slow that I don't think it's of practical use for most workflows.

The warning comes from the Broad team and I think is meant as a reflection of the newness of the tools. Our validations with it showed no concerns for test cases:

https://github.com/bcbio/bcbio_validations/tree/master/gatk4#germline-joint-calling

but I guess they have concerns about edge cases to label it beta.

Practically we don't BQSR in our runs and only try it when we have data quality issues we think it might resolve. So my suggestion would be to skip it and run directly with HaplotypeCaller if you have concerns about the beta classification. Hope this helps.
