### ISSUE TITLE
GATK memory issue

### ISSUE THREAD

**Issue by Addicted-to-coding** [bcbio/bcbio-nextgen#2421]
Hi,
When I try to run your tool using the command : 
java -jar <path to GenomeAnalysisTK.jar> -T CountReads -R exampleFASTA.fasta -I exampleBAM.bam 
I get the error:
 Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes
I tried to increase the heap memory by doing:
java -Xmx128G -jar ~/GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar -T CountReads -R ~/reference.genome/chr19_new.fa -I ~/reference.genome/LP_J.chr19.1.25p.5_sorted.bam

But I still got the error:
Error occurred during initialization of VM
Could not reserve enough space for 134217728KB object heap

**Comment by roryk** [comment]
Sorry @Addicted-to-coding, I think you might have the wrong repo-- https://software.broadinstitute.org/gatk/documentation/topic?name=faqs has some information on the GATK forums, you'd have to ask there. 

You're asking for 128 gigabytes of memory and it can't be allocated. If you turn down the -Xmx128G to something more reasonable you'll probably be able to fix this problem.
