### ISSUE TITLE
Single-cell RNA-seq example templates

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2422]
bcbio needs more detailed example configuration templates for single-cell RNA-seq, in this directory:
https://github.com/bcbio/bcbio-nextgen/tree/master/config/templates

In particular, I think we need to explain clearly how to match sample index barcodes in the configuration template, and how to tweak the bcbio YAML if there are multiple multiplexed FASTQs for a project.

**Comment by roryk** [comment]
Thanks, Sergey updated the documentation recently with how to get for inDrops going. Improving documentation is on a list of things to do, so will close this in favor of a bigger documentation issue.
