### ISSUE TITLE
Provide an updated GATK 4 with installation

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2430]
Currently bcbio installs 4.0.3.0, but the latest changes in 4.0.5.2 and before (https://github.com/broadinstitute/gatk//releases) offer quite a number of improvements in particular with MuTect2 specificity and sensitivity. It would be probably worthwhile to have 4.0.5.2 provided when installing.

FTR, I'm mostly interested in the improved active region determination at low allele fractions (useful for cfDNA) but the other improvements are also worthwhile.

**Comment by chapmanb** [comment]
Luca;
Thanks for this. I have a fix ready to go supporting the latest GATK4 release, but the script name changed after 4.0.3.0 in bioconda. GATK4 moved from `gatk-launch` to `gatk` and GATK3 from `gatk` to `gatk3`, so we need to coordinate the update with the next release to avoid breaking things for people working from release versions. We're aiming to have a new release soon and will close this issue when it's updated. Thanks again.
