### ISSUE TITLE
png file from validation 

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2440]
Hi,

I'm wondering how the png file is generated from the validation results using rtg vcfeval? 

I see this in the log file:

export PATH=/hpf/tools/centos6/bcbio/20180613/anaconda/bin:$PATH &&  export RTG_JAVA_OPTS='-Xms750m' && export RTG_MEM=38220m && 
rtg vcfeval 
--threads 6 
-b /hpf/tools/centos6/bcbio/20180613/genomes/Hsapiens/GRCh37/validation/giab-NA12878/truth_small_variants.vcf.gz 
--bed-regions /hpf/largeprojects/pray/rbaldwin/WGS/NA12878/NA12878_REP/work/validate/Undetermined_S0_NA12878/gatk-haplotype/Undetermined_S0_NA12878-sort-callable_sample-Undetermined_S0_NA12878-gatk-haplotype-wrm.bed 
-c /hpf/largeprojects/pray/rbaldwin/WGS/NA12878/NA12878_REP/work/validate/Undetermined_S0_NA12878/gatk-haplotype/Undetermined_S0_NA12878-effects-annotated-combined.vcf.gz 
-t /hpf/tools/centos6/bcbio/20180613/genomes/Hsapiens/GRCh37/rtg/GRCh37.sdf 
-o /hpf/largeprojects/pray/rbaldwin/WGS/NA12878/NA12878_REP/work/validate/Undetermined_S0_NA12878/gatk-haplotype/rtg 
--vcf-score-field='INFO=VQSLOD'

But that doesn't get the png file that I see in the bcbio output. Just wondering how that png file is generated and where the command is located. Thank You - Robert 

![undetermined_s0_na12878-validate](https://user-images.githubusercontent.com/16197088/42529286-0f2d8d08-844c-11e8-97cb-bba09747704e.png)

**Comment by chapmanb** [comment]
Robert;
These get created using matplotlib and the code that does them is here: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/validateplot.py

Hope this helps and please let us know if you have any specific questions as you look through it.

**Comment by RobertWBaldwin** [comment]
Hi,

Where can we get the exact FDR and FNR as they appear on the png files? I don't want to estimate from the graph but I haven't been able to find them in the output. Some details on  how they calculated would be helpful as well. thanks - Robert

**Comment by chapmanb** [comment]
Robert -- there is an equivalent CSV grading file with the png file that has the raw values for true positives, false positives and false negatives. The wikipedia page has the formulas for calculating these (and all the other related metrics) from these: https://en.wikipedia.org/wiki/Precision_and_recall. Beyond that we use rtg vcfeval for calculating the comparisons that go into these numbers (https://github.com/RealTimeGenomics/rtg-tools). Hope that gives you enough background information for recalculating and understanding the outputs.

**Comment by RobertWBaldwin** [comment]
Hi,
I sequenced the whole genome of NA12878 to ~76x coverage and down sampled the bam file to various depths ( 30x, 40x, 50x, and 60x ). I then ran each bam through bcbio using the validate step (see config below). I've included the results below. The FDR and FNR in the png files correspond to the %FP and %FN in the tables. Things look o.k but I noticed that the number of truth set calls ( TP + FN ) changes with the level of coverage. Specifically, higher coverage results in more truth set calls. This is a bit different than the method I have been using for exome data where there's a capture bed file and we simply do the benchmarking using all the truth set variants in that region regardless of what the level of coverage is in the bam. Below is the rtg command from bcbio log file. As each validation uses the exact same -b option however the only difference must be the bed file, the "callable" regions. I'm not quite clear on how that bed file is generated however. Will you please explain that to me? Thanks. 

It seems to me that it must be based on the bam file but the details are unclear. Fore example, I investigated what regions were excluded by the callable regions bed by intersecting with our gene panel bed file and found that ~5% of our panels was not included. The excluded intervals all seemed to occur within exons known problematic but it's not clear if they were excluded because of no coverage (no bam records for these regions) or because the mapping qualities were too low or something like that. I suppose I could look at the bams in IGV but in my experience you should have at least some coverage in these intervals so I'm kind of thinking that these were excluded because the mappings  were too poor. 


###RTG COMMAND
 rtg vcfeval --threads 6 
-b /hpf/tools/centos6/bcbio/20180613_hg38/genomes/Hsapiens/GRCh37/validation/giab-NA12878/truth_small_variants.vcf.gz
 --bed-regions /work/validate/L004/gatk-haplotype/L004-prealign-callable_sample-L004-gatk-haplotype-wrm.bed 
-c L004/gatk-haplotype/batch1-effects-annotated-ploidyfix-combined.vcf.gz 
-t /hpf/tools/centos6/bcbio/20180613_hg38/genomes/Hsapiens/GRCh37/rtg/GRCh37.sdf 
-o /NA12878-45-validate/L004_BAM/work/validate/L004/gatk-haplotype/rtg 
--vcf-score-field='INFO=VQSLOD'

  
###VALIDATION RESULTS
SNPs
            TP |       FN       | FP    |% FP   | %FN   | Sensitivity
30X | 3207710 | 2259 | 24020 | 0.743 | 0.070 | 99.930
40X | 3208408 | 1593 | 23592 | 0.730 | 0.050 | 99.950
50X | 3208662 | 1359 | 23440 | 0.725 | 0.042 | 99.958
60X | 3208728 | 1304 | 23207 | 0.718 | 0.041 | 99.959
68X | 3208793 | 1245 | 23220 | 0.718 | 0.039 | 99.961
  | 
INDELs 
30X | 447097 | 33646 | 5075 | 1.122 | 6.999 | 93.001
40X | 450878 | 29898 | 2419 | 0.534 | 6.219 | 93.781
50X | 453316 | 27473 | 1595 | 0.351 | 5.714 | 94.286
60X | 454412 | 26388 | 1136 | 0.249 | 5.488 | 94.512
68X | 454287 | 26523 | 954 | 0.210 | 5.516 | 94.484












- analysis: variant2
    genome_build: GRCh37
    description: 'L004'
    files: [L004.bam]
    algorithm:
      tools_on:
      - svplots
      - qualimap
      aligner: false
      clinical_reporting: true
      coverage_interval: genome
      variantcaller: gatk-haplotype
      validate: platinum-genome-NA12878/truth_small_variants.vcf.gz
      validate_regions: platinum-genome-NA12878/truth_regions.bed
      ploidy: 2
      coverage_depth_max: 1000
    resources:
      default:
        memory: 7G
        cores: 7
    upload:

**Comment by RobertWBaldwin** [comment]
I'm not able to find the goleft depth command in the log files. Just to confirm it's being used with default settings right? Also if someone knows where it would be located that would be helpful. thnaks

**Comment by chapmanb** [comment]
Robert;
Thanks for the discussion and questions. Your intuition and research is exactly right: the number of variants we can look at during validation is moderated by which regions have enough coverage depth to be able to call.

Practically, goleft depth has been replaced by mosdepth since that discussion. The actual approach is the same, but mosdepth is faster and parallelizes better, so that's the command to look for. Here's the implementation:

https://github.com/bcbio/bcbio-nextgen/blob/3f436afe0f737a3e5eb6ea3ddd4967008681d30d/bcbio/variation/coverage.py#L73

and it would run as is with your inputs. Hope this helps explain the underlying mechanisms going on here. Thanks again for the discussion.

**Comment by RobertWBaldwin** [comment]
thanks for your help. I have a related question so I'll just post it here.
I did the bench-marking for NA12878 for the whole genome using bams with 30X, 40X, 50X and 60X coverage. I'd now like to do the benchmarking using these bams for both our exome capture regions bed and a gene panel bed files so that I can compare how the different BAMs do across these different regions. The ideal starting point for this type on analysis would obviously be the whole genome VCF files that I already have from bcbio. I could subset these by selecting the variants within the targeted regions and then use this vcf in bcbio to do the benchmarking. I'm just not sure how this would work because bcbio uses a bam to get the callable regions. I mean can you run bcbio in validate mode but turn off mapping and variant calling/filtering and just do the validation step? How would bcbio get the callabale regions in this case? Thanks - Robert

**Comment by chapmanb** [comment]
Robert;
We don't have a good current input for subsetting the VCFs and then re-submitting them through for validation. My suggestion here would be to re-use your existing aligned bams, passing those as the `files` input for each sample, and turn off alignment with `aligner: false`. Then supply your BED exome region for `variant_regions` and validation inputs as before. bcbio will have to re-run variant calling, but only in the exome regions you defined, and then will generate a comparison against these. Sorry about the additional work in these cases, and hope this will fit your needs.

**Comment by RobertWBaldwin** [comment]
than you for the explanation. So if I pass in a bed file like this in the csv config file:

samplename,description,batch,phenotype,sex,variant_regions
NA12878,L004,batch1,normal,female,S06588914_Covered.sort.merged.bed

Then it will restrict calling and validation only to the regions  in the bed file? But it will also only use the callable regions in those intervals in the bed file, at least that's what I see in the log file because I'm looking at the log file and it's still using mosdepth and appears to be using the output from that to restrict the calling? If that's the case, then is there some way to have the validation done across the entire bed file so that the number of truth set variants is the same for each comparison?

**Comment by chapmanb** [comment]
Robert;
It always uses callable regions, unfortunately, so won't be a one to one comparison across different depths like you want. Practically, I think it's worth separating these things in your comparisons and not glossing over the fact that lower coverage can't assess some regions. We try to combine the validation reports with the coverage reports in MultiQC to summarize both what we actually cover across a panel/exome/genome, and then within the things that we cover how we do in terms of calling variants. I know it's not as neat of a summary but reflects more the reality of varying coverage and capture across samples. Hope this helps and works okay with your needs.
