### ISSUE TITLE
Install error with ggd-run.sh

### ISSUE THREAD

**Issue by hmkim** [bcbio/bcbio-nextgen#2444]
Hello. Can I get some hint for this error ?

```
$ pwd
/home/brandon

$ python bcbio_nextgen_install.py /BiO/BioPeople/brandon/bcbio --tooldir=/BiO/BioPeople/brandon/bcbio/local --genomes GRCh37 --aligners bwa --aligners bowtie2

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 266, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/home/brandon/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/BiO/BioPeople/brandon/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/BiO/BioPeople/brandon/bcbio/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1.


```

**Comment by lpantano** [comment]
Hi @hmkim 

sorry about that.

Is that the only error you see?

We have this other issue: https://github.com/bcbio/bcbio-nextgen/issues/2443 but is related to genome hg19. So not sure if it was the same.

Can you post the full log you got from the installation, at least some more lines from the traceback?

**Comment by hmkim** [comment]
@lpantano Thank you.

I removed tmp directory and I'm installing again.

I'll post after trying.

**Comment by hmkim** [comment]
![2018-07-13 17 30 11](https://user-images.githubusercontent.com/4966343/42681360-6dd9a0a8-86c2-11e8-9d43-672280f2743a.png)

How can I get the log for install?

**Comment by lpantano** [comment]
Hi,

Can you check whether the gg-run.sh file is still there and try to run it to see if we get better idea of what is failing?

Thanks

**Comment by roryk** [comment]
Stale and an installation issue, so should be solved now.
