### ISSUE TITLE
What to do about Y calls for NA12878? 

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2446]
Hi,

We sequenced NA12878 on Illumina platform and ran it through bcbio wgs pipeline using the validation method (sample yaml config below). The results looked good but I noticed that there are Y chromosome calls and these being represented as haploid calls ( see below ) which creates problems for other programs. For example, when I take the vcf and run a different validation method using gatk 3.6  GenotypeConcordance there's some discrepancy with the truth set vcf that I'm using and I get this message:

ERROR MESSAGE: Concordance Metrics is currently only implemented for DIPLOID genotypes, found eval ploidy: 1, comp ploidy: 0
   
I suppose I could just remove all the Y calls from the vcf. But I'm curious, why are there Y calls for NA12878? Is it just the PAR? I didn't specify the sex in the metadata. Should I have? Thanks - Robert  

[rbaldwin@qlogin5 config]$ cat NA12878_REP.yaml
details:
- algorithm:
    aligner: bwa
    clinical_reporting: true
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - svplots
    - qualimap
    - noalt_calling
    validate: giab-NA12878/truth_small_variants.vcf.gz
    validate_regions: giab-NA12878/truth_regions.bed
    variantcaller:
    - gatk-haplotype
  analysis: variant2
  description: Undetermined_S0_NA12878
  files:
  - /localhd/40606778/WGS/Undetermined_S0_NA12878_R1_001.fastq.gz
  - /localhd/40606778/WGS/Undetermined_S0_NA12878_R2_001.fastq.gz
  genome_build: GRCh37
fc_name: gatk4
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final

Y	58982324	rs35023792	T	A	8688	VQSRTrancheSNP99.99to100.00	AC=1;AF=1;AN=1;ANN=A|intergenic_region|MODIFIER|PARP4P1-CTBP2P1|ENSG00000237917-ENSG00000235857|intergenic_region|ENSG00000237917-ENSG00000235857|||n.58982324T>A||||||;DP=221;FS=0;MLEAC=1;MLEAF=1;MQ=51.4;MQ0=0;QD=26.99;SOR=0.974;VQSLOD=-6.180e+01;culprit=DP	GT:AD:DP:GQ:MMQ:PL	1:0,187:187:99:60:8727,0

Y	58977910	rs372611781	G	T	8010	VQSRTrancheSNP99.99to100.00	AC=1;AF=1;AN=1;ANN=T|intergenic_region|MODIFIER|PARP4P1-CTBP2P1|ENSG00000237917-ENSG00000235857|intergenic_region|ENSG00000237917-ENSG00000235857|||n.58977910G>T||||||;BaseQRankSum=5.308;ClippingRankSum=0;DP=652;FS=3.481;MLEAC=1;MLEAF=1;MQ=53.32;MQ0=0;MQRankSum=-7.722;QD=16.05;ReadPosRankSum=3.133;SOR=0.953;VQSLOD=-7.078e+02;culprit=DP	GT:AD:DP:GQ:MMQ:PL	1:167,332:499:99:60:8040,0

Y	58976507	rs112103033	T	C	5769	VQSRTrancheSNP99.99to100.00	AC=1;AF=1;AN=1;ANN=C|intergenic_region|MODIFIER|PARP4P1-CTBP2P1|ENSG00000237917-ENSG00000235857|intergenic_region|ENSG00000237917-ENSG00000235857|||n.58976507T>C||||||;DP=232;FS=0;MLEAC=1;MLEAF=1;MQ=47.48;MQ0=0;QD=25.1;SOR=0.862;VQSLOD=-6.892e+01;culprit=DP	GT:AD:DP:GQ:MMQ:PL	1:0,132:132:99:60:5808,0

**Comment by chapmanb** [comment]
Robert;
Thanks for the question and sorry about the confusion. If you specify:
```
metadata:
  sex: female
```
(https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#sample-information)

then bcbio will remove Y chromosome calls:

https://github.com/bcbio/bcbio-nextgen/blob/50349e6a72f68278eb08dcaa29be4e45003f0798/bcbio/variation/ploidy.py#L68

 If this isn't present than it tries to do the best it can for non-gendered samples and will return a diploid X and haploid Y to allow you to post filter as needed. Hope this helps.

**Comment by RobertWBaldwin** [comment]
yes thanks
