### ISSUE TITLE
bcbiornaseq: error with annotationhub

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2449]
This happens with the state of the pipeline from about a week ago:

```r
summarizing abundance
summarizing counts
summarizing length
Making GRanges from Ensembl with AnnotationHub 2.6.0 (2018-06-27)
Error: 'AH57757' not available in this version of the package; use biocLite()
  to update?
In addition: There were 12 warnings (use warnings() to see them)
Execution halted
' returned non-zero exit status 1
```

Do I need to update or is there some dependency that fell behind?

**Comment by roryk** [comment]
Thanks Luca, do you have bcbiornaseq turned on as one of the options, by any chance?

@mjsteinbaugh do you know how we should be handling genomes like this?

**Comment by lbeltrame** [comment]
Yes, turned on by purpose as the metrics collected are useful at a glance (I was able to run it locally later).

**Comment by roryk** [comment]
Hi Luca,

Oh I see. Gotcha-- which was working locally, the bcbioRNASeq object loading, or the quality report generation? That will help figure out where the dependency is out of date. I totally think you are right that we are missing one somewhere.

**Comment by lbeltrame** [comment]
No, it breaks during loading. Locally both the loading and the QC report work.

**Comment by roryk** [comment]
Thanks! Will poke into it to see where the problem is.

**Comment by mjsteinbaugh** [comment]
Hi @lbeltrame can you provide some additional detail about the organism / genome build you want to load up, and your R `sessionInfo()`? That issue is related to AnnotationHub, which is the Bioconductor structure infrastructure we use to handle gene metadata (it's the replacement for biomaRt).

**Comment by mjsteinbaugh** [comment]
PS the current version of AnnotationHub is 2.12 for Bioconductor 3.7. Updating to that version may fix your issue.

**Comment by mjsteinbaugh** [comment]
For example, here's what our code does internally to get *Homo sapiens* annotations:

```r
> hs <- makeGRangesFromEnsembl("Homo sapiens")
Making GRanges from Ensembl with AnnotationHub 2.12.0 (2018-04-30)
Ensembl 92 EnsDb for Homo Sapiens
id: "AH60977"
organism: "Homo sapiens"
build: "GRCh38"
release: "92"
format: "genes"
Standardizing the metadata columns
Using geneName instead of symbol
Setting geneBiotype as factor
Setting seqCoordSystem as factor
Defining broadClass using: geneName, geneBiotype, seqnames
```

If your installation is working correctly, you should see a message like that.

**Comment by roryk** [comment]
We can't go to 3.7 because it's not in bioconda yet, is there some way to fix it so it will work with R 3.4 and bioconductor 3.6?

**Comment by roryk** [comment]
Here's the two run templates with and without organism being specified:

```
    load_template = Template(
        ('bcb <- bcbioRNASeq(uploadDir="$upload_dir",'
         'interestingGroups=$groups,'
         'organism="$organism")'))
    load_noorganism_template = Template(
        ('bcb <- bcbioRNASeq(uploadDir="$upload_dir",'
         'interestingGroups=$groups,'
         'organism=NULL)'))
```

**Comment by roryk** [comment]
Is that how you called it to get it to load locally Luca? We might be missing a parameter.

**Comment by mjsteinbaugh** [comment]
R 3.4 / Bioconductor 3.6 should work also. Here's what *Homo sapiens* looks like using conda r-base on the O2 cluster:

```r
> hs <- makeGRangesFromEnsembl("Homo sapiens")
Making GRanges from Ensembl with AnnotationHub 2.10.1 (2017-10-27)
Ensembl 90 EnsDb for Homo Sapiens
id: "AH57757"
organism: "Homo sapiens"
build: "GRCh38"
release: "90"
format: "genes"
Standardizing the metadata columns
Using geneName instead of symbol
Setting geneBiotype as factor
Setting seqCoordSystem as factor
Defining broadClass using: geneName, geneBiotype, seqnames
```

The issue seems to be due to an old version of AnnotationHub (2.6 instead of 2.10+)

**Comment by roryk** [comment]
Awesome, thanks Mike and Luca. Luca if you do a `bcbio_nextgen.py upgrade --tools` does it pull in the newer AnnotationHub?

**Comment by roryk** [comment]
Thanks, this should be all set now.
