### ISSUE TITLE
Query on RNA-seq duplicates

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2452]
Hi,

I have a query on Bcbio's handling of duplicates on RNA-seq data. 

I have been trying to call fusions with STAR-Oncofuse. While visualising through IGV, I thought my reads looked suspiciously like PCR duplicates (starting from the same position, etc), and therefore decided to filter out the duplicates on the next round.

I specified mark_duplicates: true in the config file and thought that it should be equivalent to STAR's --bamRemoveDuplicatesType or perhaps some other duplicate removal software. However I realised that the duplicates weren't marked at all.
```
samtools flagstat ../SGH_18_0031_50ng/SGH_18_0031_50ng-ready.bam
54860102 + 0 in total (QC-passed reads + QC-failed reads)
575582 + 0 secondary
148678 + 0 supplementary
0 + 0 duplicates
48068626 + 0 mapped (87.62% : N/A)
54135842 + 0 paired in sequencing
27067921 + 0 read1
27067921 + 0 read2
46235872 + 0 properly paired (85.41% : N/A)
47344366 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
3124 + 0 with mate mapped to a different chr
3124 + 0 with mate mapped to a different chr (mapQ>=5)
```
And the only area where the duplicate rate was reflected was in the QC summary.

I realise that usually the general consensus is NOT to mark PCR duplicates in RNA-seq data but I was wondering whether Bcbio has the option to go against this default instead? Or does Bcbio support STAR-fusion (https://github.com/STAR-Fusion/STAR-Fusion/wiki) which seems to support duplicate removal instead?

Thanks and appreciate any advice given!

**Comment by roryk** [comment]
Thank you, sorry we didn't give you an answer, we must have missed this one. We don't have an option in bcbio to mark duplicates or have support for STAR-fusion. Generally it's not particularly helpful to do duplicate marking and what not with RNA-seq, so we haven't supported it.
