### ISSUE TITLE
Disable VerifyBamID2 for high depth datasets

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2454]
I have a number of amplicon based runs that have a median coverage of 2500X. In these case the generation of the mpileup from samtools is quite slow (takes ~2 hours), and then the resulting data is useless for VerifyBamID2 as there are not enough SNPs. 

Perhaps it would be worth allowing this to be disabled with tools_off.

**Comment by chapmanb** [comment]
Luca -- thanks much for the feedback and suggestion. I pushed a fix to the latest development to automatically skip high depth panels and avoid the calculations. Please let me know if you run into any other issues at all. Much appreciated.

**Comment by lbeltrame** [comment]
Well, the main problem is that mpileup is terribly slow even for exome or quasi-exome (Agilent OneSeq) level datasets: a sample set that is made up by few samples is taking days to process due to that (median depth 150X). The fact that the mpileup runs single core doesn't help.
I would still strongly suggest to have the possiblity of turning this tool off with `tools_off`.

**Comment by chapmanb** [comment]
Luca;
Thanks for testing this and sorry for the continued problems. I'm trying to avoid additional configuration parameters and have this be reasonable without additional tweaking, so had another pass at improving it. The latest version only does a pileup at the positions used in the VerifyBamID comparison, which should speed it up substantially. Would you be able to update to the latest development and try this to see if it now works in a resonable time? Thanks again for all the feedback and patience with this.

**Comment by lbeltrame** [comment]
I'll give it a try after the current run is done and report back.

**Comment by lbeltrame** [comment]
Thanks, it works better now, both for runtime and disk space usage.

**Comment by gabeng** [comment]
Brad,

I am running bcbio most frequently with targeted panels and WES for development and validation purposes. It appears that VerifyBamID exits with error most of the time not finding enough SNPs, so it just eats processing time and clogs the log. 
From my point of view I would prefer an option in the `bcbio.yaml` in a similar way as for qsignature.

**Comment by chapmanb** [comment]
Ben;
You can turn off the VerifyBamID step with:
```
tools_off: [contamination]
```
Apologies, this has only been documented recently but you can turn off any QC step with `tools_off`:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#changing-bcbio-defaults
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#docs-config-qc

Thanks so much for the question and hope this does what you need.

**Comment by gabeng** [comment]
Thanks for the links! It is hard to keep up with your pace of improving bcbio.
