### ISSUE TITLE
convert gvcf to vcf for vep annotation

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2455]
Hi,

Is there a way to convert the gvcf created in variation step to be converted to vcf within the pipeline? I am trying to annotate the vcf using VEP but have to use a regular vcf as input:

This is what I have right now in the variation folder:

```
[rathik@reslnrefo01 bcbio_out]$ ls -lt variation/rnaseq/gatk-haplotype/
total 940881
-rw-r--r--. 1 rathik reslnusers    409273 Jul 14 16:58 Sample_1__CDL-634-13P-gatk-haplotype-annotated-rnaedit-annotated-gemini.vcf.gz.tbi
-rw-r--r--. 1 rathik reslnusers 327075804 Jul 14 16:57 Sample_1__CDL-634-13P-gatk-haplotype-annotated-rnaedit-annotated-gemini.vcf.gz
-rw-r--r--. 1 rathik reslnusers    337251 Jul 14 13:55 Sample_1__CDL-634-13P-gatk-haplotype-annotated-rnaedit.vcf.gz.tbi
-rw-r--r--. 1 rathik reslnusers 194570252 Jul 14 13:54 Sample_1__CDL-634-13P-gatk-haplotype-annotated-rnaedit.vcf.gz
-rw-r--r--. 1 rathik reslnusers    350716 Jul 14 13:52 Sample_1__CDL-634-13P-gatk-haplotype.vcf.gz.tbi
-rw-r--r--. 1 rathik reslnusers 272929235 Jul 14 13:51 Sample_1__CDL-634-13P-gatk-haplotype.vcf.gz
-rw-r--r--. 1 rathik reslnusers      9515 Jul 14 13:51 Sample_1__CDL-634-13P-gatk-haplotype-files.list
-rw-r--r--. 1 rathik reslnusers     29924 Jul 14 13:51 Sample_1__CDL-634-13P-1_0_62094793-gatk-haplotype-fixheader.vcf.gz.tbi
-rw-r--r--. 1 rathik reslnusers   7682458 Jul 14 13:51 Sample_1__CDL-634-13P-1_0_62094793-gatk-haplotype-fixheader.vcf.gz
drwxr-xr-x. 2 rathik reslnusers     14556 Jul 14 13:51 regions
-rw-r--r--. 1 rathik reslnusers   1400215 Jul 14 01:47 ref-transcripts-transcripts_w0-sortmerge.bed
-rw-r--r--. 1 rathik reslnusers   1828568 Jul 14 01:47 ref-transcripts-transcripts_w0.bed
```

I have tried to convert the gvcf to vcf like this:

```
gzip -dc Sample_1__CDL-634-13P-gatk-haplotype.vcf.gz | extract_variants | bgzip -c > Sample_1__CDL-634-13P.vcf.gz
```

But even after this, vep is throwing an error so I was wondering if you have a step in the pipeline that generates a regular vcf besides the gvcf.

Thanks
Komal

**Comment by roryk** [comment]
Hi Komal,

The output files from the pipeline will be in VCF format, it looks like these are some of the intermediate files. There are still VCF files in this directory, the file:

Sample_1__CDL-634-13P-gatk-haplotype-annotated-rnaedit-annotated-gemini.vcf.gz is a regular VCF file, so you don't need to convert it.

**Comment by roryk** [comment]
Hi Komal,

Those are VCF files, the Sample_1__CDL-634-13P-gatk-haplotype-annotated-rnaedit-annotated-gemini.vcf.gz is a VCF file, not a gVCF file.

Best,

Rory

**Comment by komalsrathi** [comment]
Hi Rory,

Sorry I am still confused because of my lack of inexperience with these file formats. Hopefully it won't take much of your time to clarify this for me. Here are a few lines from the above file:

```
zless variation/rnaseq/gatk-haplotype/Sample_1__CDL-634-13P-gatk-haplotype-annotated-rnaedit-annotated-gemini.vcf.gz

# skipping few lines above this block
##GVCFBlock0-10=minGQ=0(inclusive),maxGQ=10(exclusive)
##GVCFBlock10-20=minGQ=10(inclusive),maxGQ=20(exclusive)
##GVCFBlock20-30=minGQ=20(inclusive),maxGQ=30(exclusive)
##GVCFBlock30-40=minGQ=30(inclusive),maxGQ=40(exclusive)
##GVCFBlock40-60=minGQ=40(inclusive),maxGQ=60(exclusive)
##GVCFBlock60-80=minGQ=60(inclusive),maxGQ=80(exclusive)
##GVCFBlock80-100=minGQ=80(inclusive),maxGQ=100(exclusive)
##source=HaplotypeCaller
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Sample_1__CDL-634-13P
1       11870   .       T       <NON_REF>       .       .       END=14470;fitcons=0.0784;encode_consensus_gm12878=R;encode_consensus_h1hesc=R;encode_consensus_helas3=unknown;encode_consensus_hepg2=R;encode_consensus_huvec=unknown;encode_consensus_k562=T;dgv=CopyNumber;hapmap1=2.9818;hapmap2=0   GT:DP:GQ:MIN_DP:PL      0/0:0:0:0:0,0,0
1       14471   .       C       <NON_REF>       .       .       END=14474;fitcons=0.263;encode_consensus_gm12878=R;encode_consensus_h1hesc=R;encode_consensus_helas3=CTCF;encode_consensus_hepg2=R;encode_consensus_huvec=R;encode_consensus_k562=T;dgv=CopyNumber;hapmap1=2.9818;hapmap2=0     GT:DP:GQ:MIN_DP:PL      0/0:5:12:4:0,12,180
```

When I tried to look up the difference between a gvcf and vcf file, this GATK article came up: https://software.broadinstitute.org/gatk/documentation/article?id=4017. Am I interpreting it wrong that `##GVCFBlock` in the header as well as the presence of `<NON_REF>` and `END tag in the INFO field` are specific to a gvcf file?

**Comment by roryk** [comment]
Guh, you are totally right-- I was mistaken, that file is a gVCF file. Downstream we combine all of the gVCF files into one VCF file, which is the step that looks like it is failing in the other issue. If we fix that you should be all set.

**Comment by snijesh** [comment]
I think you can load gvcf files to `gatk GenotypeGVCFs` as
`gatk GenotypeGVCFs -R $reference --variant 1.gvcf.gz -O 1.vcf`
