### ISSUE TITLE
bcftools filter and freebayes VEP

### ISSUE THREAD

**Issue by aleferna** [bcbio/bcbio-nextgen#2462]
Hi, I'm having some problems with freebayes, the variant2 pipeline is crashing on this line: 

set -o pipefail; /DATA/BCBio_Data/anaconda/bin/bcftools filter -O v -T /RAIDT/Projects/TCER/WORK/BCBio/TEST/work.DNA/bedprep/cleaned-Protein-Coding.1-22,X,Y.bed.gz --soft-filter 'FBQualDepth' -e '(AF[0] <= 0.5 && (DP < 4 || (DP < 13 && %QUAL < 10))) || (AF[0] > 0.5 && (DP < 4 && %QUAL < 50))' -m '+' TEST/work.DNA/freebayes/TEST-vepeffects-annotated.vcf.gz  | bgzip -c > TEST/work.DNA/bcbiotx/tmpyqXIIw/TEST-vepeffects-annotated-filter.vcf.gz
-bash: TEST/work.DNA/bcbiotx/tmpyqXIIw/TEST-vepeffects-annotated-filter.vcf.gz: No such file or directory
Both INFO/DP and FORMAT/DP exist, which one do you want?

It seems the TEST/work.DNA/freebayes/TEST-vepeffects-annotated.vcf.gz has both a INFO/DP and FORMAT/DP making the bcftools filter for DP ambiguos, is there a way to patch this up?

**Comment by aleferna** [comment]
from the afformentioned vcf: 
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">

**Comment by chapmanb** [comment]
Alejandro -- apologies about the issue and thanks for the report. This is due to a change in bcftools 1.9 and was fixed yesterday (https://github.com/bcbio/bcbio-nextgen/commit/b021a12a5935528cef5e1e4e27150ee70d742630). If you update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
it should work cleanly for you. Please let us know if you run into any other issues.

**Comment by aleferna** [comment]
thanks Brad (I think we were in a few conference calls, I was a bioinformatician at AZ Gothenburg a few years ago), found a workaround, added this to the vfilter.py for the time being, but will try it out when the full new version comes out. 

  filters = ('(AF[0] <= 0.5 && (FORMAT/DP < 4 || (FORMAT/DP < 13 && %QUAL < 10))) || '
               '(AF[0] > 0.5 && (FORMAT/DP < 4 && %QUAL < 50))')
