### ISSUE TITLE
vcfanno somatic looks in wrong path for dbSNP and COSMIC

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2463]
I saw a command being executed as 

```
/opt/bcbio/anaconda/bin/vcfanno -p 7  -base-path /opt/bcbio/gemini_data /opt/bcbio/genomes/Hsapiens/hg19/config/vcfanno/somatic.conf /path/to/my/vcf
```

`somatic.conf` contains paths to `variation/dnbsnp-150.vcf.gz` and similar other files like COSMIC. However, the base path does not, because it points to the GEMINI install directory and thus vcfanno bails out with an error. 
Simply symlinking `variation` from the hg19 genome directory makes this issue disappear, but it's just a hack (and something I made to keep the analysis running).

**Comment by chapmanb** [comment]
Luca;
Thanks so much for the heads up on this and apologies about the issue. We've been working on generalizing and improving vcfanno in the development version and missed this need to set different basepaths for vcfanno when we have both gemini and somatic annotations. I've pushed a fix which should resolve this by running these separately. Please let us know if you run into any other problems at all.
