### ISSUE TITLE
TitanCNA: unclear approach on selecting heterozygous variants

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2464]
FTR, I'm referring to `prep_vrn_file` in `bubbletree`, which is used by bcbio to run TitanCNA.

I say "unclear" because if using, for example, MuTect 2, heterozygous calls won't necessarily be very frequent, especially after filtering. In addition, they will only be present in the tumor sample if `PASS`. At least on a naive level, I don't expect frequency in the normal to be particularly high, if any, so a sample done like that will likely get discarded for no data points.

Since TitanCNA usually calls LOH by itself, what I historically did was to run a germline caller on both the tumor and the normal sample, then select the HET variants. I'm not sure how this would fit in the current design, though.

Other callers might be more suited than MuTect2, perhaps, like VarDict (filter `LikelyLOH`) but in this case the current code would discard those loci.

**Comment by etal** [comment]
CNVkit does the same, and has the same problem with Mutect2 inputs. I considered another approach to force-call variant allele frequencies in the unpaired tumor sample at a given set of known SNP sites, e.g. 1000 Genomes Omni: https://github.com/etal/cnvkit/blob/master/scripts/snpfilter.sh

**Comment by chapmanb** [comment]
Luca and Eric;
Thanks for this discussion. You're right that MuTect2 output, which doesn't generate germline filtered calls in the VCF, are not the best option here. So far we've been testing this primarily with VarDict and will use calls from it if also present along with MuTect2 in your somatic callers. We have a list here of callers prioritized by preference:

https://github.com/bcbio/bcbio-nextgen/blob/82fb2a01a068c35c2380aae7b35a673f9d721570/bcbio/heterogeneity/__init__.py#L31

The logic in the selection of sites is to find things that are heterozygous in the normal (including germline filtered records):

https://github.com/bcbio/bcbio-nextgen/blob/82fb2a01a068c35c2380aae7b35a673f9d721570/bcbio/heterogeneity/bubbletree.py#L303

and then report the tumor and normal counts at those sites.

Would including VarDict in your callers be an option for your tests? This should be relatively equivalent to what you're doing with germline calling on tumor and normal, but will work automatically with the current pipeline. Thanks again for this discussion.

**Comment by chapmanb** [comment]
Luca;
Thanks for this feedback, I agree that it's better right now to skip than to produce non-useful output. I've implemented this and re-organized the priority to emphasize callers that produce filtered germline outputs we've tested. Thanks again for this great discussion.
