### ISSUE TITLE
TitanCNA: genomes with chr prefix need an additional command line switch

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2465]
<strike>NOTE: This might not be a bcbio bug, it may lie in TitanCNA itself or in my input data, however it is hard to tell at this point, and I'm looking for input:</strike>

```python
[0:apply]: CalledProcessError: Command 'set -o pipefail; unset R_HOME && unset R_LIBS && export PATH=/opt/bcbio/anaconda/bin:$PATH && titanCNA.R --id 20614_tumor --hetFile /bioinformatics/einar/heterogeneity_titan/work/structural/20614_tumor/titancna/20614_tumor_vs_normal-effects-annotated-ploidyfix-vardict-prep.csv --cnFile /bioinformatics/einar/heterogeneity_titan/work/structural/20614_tumor/titancna/20614_tumor-normalized.cn --numClusters 1 --ploidy 2 --numCores 7 --outDir /scratch/tmpPCJMFe
There were 22 warnings (use warnings() to see them)
Running TITAN...
titan: Loading /data/bioinformatics/einar/heterogeneity_titan/work/structural/20614_tumor/titancna/20614_tumor_vs_normal-effects-annotated-ploidyfix-vardict-prep.csv
titan: Loading GC content and mappability corrected log2 ratios...
titan: Extracting read depth...
Removed Chrs: 
titan: Loading default parameters
Model selection: Using 7 cores.
Error in chrsI[[i]] <- which(data$chr == chrs[i]) : 
  attempt to select less than one element in integerOneIndex
Calls: runEMclonalCN
Execution halted
' returned non-zero exit status 1
```

Apparently the data is not proper for TitanCNA, but I'm not sure where to look to find the error.

**Comment by lbeltrame** [comment]
I had a hunch, and it turns out I was right: TitanCNA by default uses chromsomes without the `chr` prefix. To make it work with genomes with the prefix like hg19 and hg38, one needs to add the `--genomeStyle UCSC` command line parameter.

**Comment by lbeltrame** [comment]
Note that this won't fix all the issues I'm seeing, there's another problem with the solution selection:

```
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1, 2, 3
Calls: getParamAllClusters -> cbind -> cbind -> data.frame
Execution halted
```

I'm sure I hit this one somewhere before... Time for more digging then.

**Comment by pdiakumis** [comment]
This might be related: https://github.com/bcbio/bcbio-nextgen/issues/2304
I might actually try and dig into the R code in the coming days, and see where it could be choking.

**Comment by lbeltrame** [comment]
I just tried patching the script locally, and I'm running it now. Let's see what happens.

**Comment by chapmanb** [comment]
Thanks for debugging this. Apologies, I hadn't realized Titan was so far out of date. I've updated the bioconda package to the latest so if you run `bcbio_nextgen.py upgrade --tools` you should get the most recent version which will hopefully work cleanly. Thanks again for the help tracking this down.
