### ISSUE TITLE
FastQC crashing with internal java

### ISSUE THREAD

**Issue by jasonwood** [bcbio/bcbio-nextgen#2474]
Hi, recently all of my runs have been failing/hanging during the QC step in fastqc with java errors about missing fonts. If I run the offending command manually, using my system java (8u66), it completes fine. If I use the java in bcbio instead, it crashes. I have tried setting BCBIO_JAVA_HOME, but to no avail, the program appears to ignore that env variable and run its own java no matter what. For now I have used the tools_off: fastqc switch to get it to complete, but it would be nice to have this again.

**Comment by chapmanb** [comment]
Jason;
Sorry about the difficulties and thanks for the report. The Java fonts problem is a known issue that we've fixed in bcbio if you update to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
If you don't want to update everything you can manually install the fixed version of fastqc:
```
bcbio_conda install -y -c conda-forge -c bioconda 'fastqc=0.11.7=4'
```
Hope this works and gets your analysis running.

**Comment by jasonwood** [comment]
Thanks for the help and the quick response!

**Comment by gabeng** [comment]
Brad,
I am running into this exact issue in the fastqc step when testing the `1.1.2` release on a stand-alone docker image. `fastqc=0.11.7=5` was installed. 
I did not have any such issues with previous bcbio versions installed in docker (e. g. build from Nov 13th).
This is the error message:
```
[2018-12-13T17:06Z] Approx 100% complete for NA12878-L1-can2_S23-sort.bam
[2018-12-13T17:06Z] Analysis complete for NA12878-L1-can2_S23-sort.bam
[2018-12-13T17:06Z] Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.
[2018-12-13T17:06Z] 	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1236)
[2018-12-13T17:06Z] 	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
...
```

When updating to the newest `fastqc` version, fonts are installed and the issue goes away:
```
bcbio_conda install -y -c conda-forge -c bioconda 'fastqc=0.11.8'
Solving environment: done

## Package Plan ##

  environment location: /usr/local/share/bcbio-nextgen/anaconda

  added / updated specs:
    - fastqc=0.11.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fastqc-0.11.8              |                1         9.6 MB  bioconda
    font-ttf-dejavu-sans-mono-2.37|       h6964260_0         386 KB
    ------------------------------------------------------------
                                           Total:        10.0 MB

The following NEW packages will be INSTALLED:

    font-ttf-dejavu-sans-mono: 2.37-h6964260_0

The following packages will be UPDATED:

    fastqc:                    0.11.7-5        bioconda --> 0.11.8-1 bioconda
```
Any idea why this is? Would bumping up the fastq version solve the issue in `112`?

**Comment by chapmanb** [comment]
Ben;
Thanks for the follow up report and for checking the new version. The bioconda team updated the package to include the fonts explicitly and it sounds like this is working better than trying to pin to specific versions of java. I updated the install to get this newer version so hopefully it'll keep working cleanly in your environment. Thank you again.

**Comment by gabeng** [comment]
Perfect! I appreciate your quick responses so much!
