### ISSUE TITLE
Mosdepth multithread SIGSEGV error

### ISSUE THREAD

**Issue by kclem** [bcbio/bcbio-nextgen#2488]
When running the template [gatk variant2 pipeline](https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/gatk-variant.yaml) with multiple threads (bcbio_nextgen.py 
-n 44 -t local ../config/bcbio_project_multhread.yaml) I get the error from mosdepth:
```
  File "bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 238, in run_mosdepth
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 44 -F 1804 -Q 1 --no-per-base --by bcbio_project_multicore/work/coverage/SAMPLE-1/target-genome.bed --quantize 0:1:4: bcbio_project_multicore/work/bcbiotx/tmphwmctq/SAMPLE-1-variant_regions bcbio_project_multicore/work/align/SAMPLE-1/SAMPLE-1-sort.bam
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
' returned non-zero exit status 1
```
It appears that this could have been [arising from an old version of htslib](https://github.com/brentp/mosdepth/issues/44)  but my bcbio installation is using htslib 1.9. 

In addition, I added the following to the end of my run config yaml file:
```
...
upload:
  dir: ../final
resources:
  mosdepth:
    cores: 1
```
but when I bcbio_nextgen.py with -n 44, it still runs mosdepth with 44 cores despite my specification that mosdepth should be run with 1 core. I would prefer not to run my whole project with 1 core. Am I doing something wrong?

**Comment by chapmanb** [comment]
Kendall;
Apologies about the issue. I haven't seen this problem with mosdepth before and have been trying to reproduce on different installs and can't seem to replicate. Would you be able to describe the system you're running on and the versions of mosdepth and htslib in your install?
```
$ bcbio_conda list | grep mosdepth
$ bcbio_conda list | grep htslib
```
It does seem like it's having problem with your shared filesystem but I'm not yet sure how to track down and fix. Does this happen consistently on every run, or is it dependent on how busy the filesystem is?

Apologies about the confusion with `core` configuration as well. Those are meant as hints to determine maximum cores for allocation, rather than specifications for defining exactly how many cores to use. We could try and provide a workaround if we can't isolate and fix the underlying problem. Thanks again for the report and help debugging.

**Comment by kclem** [comment]
Hi Brad,

Thanks for looking into this. We're running on a single machine with a local, high-speed hard drive. 
I ran it three times with multiple cores, and it failed every time with this same error. I then ran it with only one core and it finished (albeit very slowly).

Here are the outputs from the commands you listed:
```
$ bcbio_conda list | grep mosdepth
mosdepth                  0.2.3                h99d1a69_0    bioconda
$ bcbio_conda list | grep htslib
hts-nim-tools             0.1.5               htslib1.7_1    bioconda
htslib                    1.7                           0    bioconda
```
However, if I run 
```
$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
$ which samtools
/bcbio/software/bin/samtools
```
So it appears that conda's htslib 1.7 may be causing this error?

**Comment by chapmanb** [comment]
Kendall;
Thanks for following up. I'm agreed that updating the latest mosdepth with htslib 1.9 would be the next thing to try to see if it helps. I just fixed a package blocking this so if you now do:
```
bcbio_conda install -c conda-forge -c bioconda mosdepth=0.2.3=he527e40_1
```
It should hopefully give you the latest version along with upgrading other tools built against htslib 1.9.

Fingers crossed this will avoid the issue and get you a clean run. Thanks for the help debugging this.

**Comment by roryk** [comment]
Thanks, this is old and is an install issue so should be all set now.
