### ISSUE TITLE
Unexpected error during align_prep

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2492]
I just updated bcbio to the latest state (previous state was early August) and rerunning a previous job to make it complete (it errored elsewhere due to a temporary FS problem) fails in the `align_prep` stage (which was already completed at the time):

```python
    688             elif is_remote:
    689                 bgzip = "| bgzip -c" if (needs_convert or dd.get_trim_ends(data)) else ""
    690                 do.run("cat {in_file} {bgzip} > {tx_out_file}".format(**locals()), "Get remote input")
    691             else:
    692                 raise ValueError("Unexpected inputs: %s %s %s %s" % (in_file, needs_bgzip,
--> 693                                                                      needs_gunzip, needs_convert))
        needs_gunzip = False
        needs_convert = False
    694     return out_file
    695 
    696 def _bgzip_multiple_files(in_files, work_dir, data):
    697     out_file = os.path.join(work_dir, "%s-combined-%s" % (dd.get_sample_name(data),

ValueError: Unexpected inputs: / False False False
```

I guess this occurs because I have some samples that needed alignment (`aligner: bwa`) and some that were prealigned and did not need doing that again (`aligner: false`) in my configuration.

**Comment by chapmanb** [comment]
Luca;
Thanks much for this report and apologies about the issue. The latest development has new code to handle multiple file inputs during alignment preparation and this was a bug in handling the standard older case for prepping a single file. I pushed a fix so if you update with `bcbio_nextgen.py upgrade -u development` and then re-run it should do the right thing now. Sorry about the issue and please let us know if you run into anything else.

**Comment by lbeltrame** [comment]
You're too fast. ;) I was about to say that reverting 45f3746b437fdda0f538627682e510a316fc9446 fixed the issue, but I guess you had a nicer fix queued up.
