### ISSUE TITLE
Theta and CNVkit

### ISSUE THREAD

**Issue by davidmasica** [bcbio/bcbio-nextgen#2494]
Hello, 

I am trying to get Theta hetcalls, and encountering a few errors. The first occurred in the export_theta function of cnvkit.py. The error was "unknown argument: path/file.cnr". Looking at the CNVKit manual, it seemed as tho CNVkit didn't need this file to export data formatted for theta input. So, I commented that out (see snippet 1, below),  and indeed a theta input file was generated, but this time I get the following error (see snippet 2, below). Looking at the empty dict in convert.SUBSET_BY_SUPPORT, and the functions in convert.py, it isn't clear to me how this dict gets populated. Any thoughts on this? Have I broken the code? And if so, why does CNVKit not recognize the .cnr file as a filetype it should be reading as an argument. Thanks in advance! 

1)
#original
#cmd = [_get_cmd(), "export", "theta", cns_file, cnr_file, "-o", tx_out_file]
#new
cmd = [_get_cmd(), "export", "theta", cns_file, "-o", tx_out_file]

2)
convert.SUBSET_BY_SUPPORT["cnvkit"]]
KeyError: 'cnvkit'

**Comment by chapmanb** [comment]
David;
Sorry about the issues with theta support. We didn't have a lot of success with theta so haven't worked on this in a while and it appears to have gotten out of sync with changes in cnvkit. We'd have to investigate or happy to accept patches if you're able to dig into it more. Alternatively I'd suggest different approaches like TitanCNA for heterogeneity if you have tumor/normal samples. Thanks again for reporting this.

**Comment by davidmasica** [comment]
Hi Brad,

Thank you for the quick reply! I will dig in more and let you know if I
find an easy fix. Thanks for the tip on TitanCNA... I am going to test that
now. I already have bubbletree working, and just wanted to have two methods
for comparison sake... so, Titan might do the trick. Either way, I'll let
you know if I have luck with Theta.

Cheers!

**Comment by roryk** [comment]
Thanks, we still haven't worked much on Theta, so closing this issue. Thank you!
