### ISSUE TITLE
Update adds dbSNP 151 to hg19 resources but does not download it

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2495]
As the subject says, dbSNP 151 was added to the genome resources the last time I did an upgrade, but the actual file is not there in the genome directory. Repeating an update did not install it, either. 
hg38 is unaffected, as far as I can see.

This causes problems with vcfanno, which tries to load a non-existent dbSNP. For now I adjusted the vcfanno configuration and the genome resources to use the latest I have there (150).

**Comment by chapmanb** [comment]
Luca -- apologies about this. We'd updated GRCh37 and hg38 but not hg19. I just pushed a fix to install the updated 151 as well, so if you do `bcbio_nextgen.py upgrade --data` it should now give you a working system without needing to manually adjust in vcfanno. Sorry again about the problem and thank you for the report.
