### ISSUE TITLE
RNA-seq pipeline: a problem with overriding STAR options

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2501]
Hello, bcbio developers and users!

Thanks for the great pipeline!

When trying to override STAR parameters according to https://github.com/bcbio/bcbio-nextgen/issues/2368
with
```
resources:
  star:
    options: ["--outSAMattributes", "NH NI NM MD AS XS"]
```
I've got an error:
```
EXITING: FATAL INPUT ERROR: duplicate parameter "outSAMattributes" in input "Command-Line"
SOLUTION: keep only one definition of input parameters in each input source
```
Of course, it is not the most frequent use case, when somebody needs to override parameters, but maybe it would be worth adding at some point?

Sergey

**Comment by roryk** [comment]
Thanks-- is XS tag useful? We can add that in as one if the ones that get added by default so you don't have to specify this downstream.
