### ISSUE TITLE
Filtering bam files using sambamba without losing primary alignment of multimapping reads

### ISSUE THREAD

**Issue by DerekWilkinson42** [bcbio/bcbio-nextgen#2506]
Hi
I tried samabamba filtering using [AS] > [XS] but sambamba does not seem to like this. The reason I tried was that I wanted to retain the primary alignment of multimapping reads (i.e. where one alignment has a better score: see Devon Ryan's comments at http://seqanswers.com/forums/showthread.php?t=39206). In the end I did a separate filter using [AS] == 0 and [XS] < 0 together with a mapping quality filter to pull out primaries for multimappers and then concatenated the bam file with a filtered bam file, made using [XS] == null.  It would be great to be able to carry out one filter step instead. If I am missing something here, any advice would be greatly appreciated. By the way, scavenging the multimappers makes a big difference when it comes to enzymes with paralogs and to sub-telomeric loci.

**Comment by amizeranschi** [comment]
Just to clarify: this relates to BAM files produced using the ChIP-seq pipeline. The relevant filter line seems to be this one: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/ngsalign/bowtie2.py#L91

**Comment by chapmanb** [comment]
Derek and Alex;
Thanks much for the report and details. I'm happy to adjust this to match your needs but not entirely sure what you're proposing. Do we need a tweak to the ChIP-seq pipeline when running bowtie2? If this is more of a general sambamba question it might be best to ask on their issue tracker (https://github.com/biod/sambamba/issues) as I'm not entirely familiar with the sambamba logic here and they'd be a better source of suggestions.

**Comment by DerekWilkinson42** [comment]
Thanks Brad,
Alex encountered this problem while using the pipeline and I came across it while using sambamba on a Mac. I will drop a line to the sambamba people as you suggest and see if they can sort this out.
Regards,
Derek
