### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ponomarevsy** [bcbio/bcbio-nextgen#2507]
Dear BCBIO experts,

I am getting this error when installing the latest BCBIO on our Linux system (for details please see below):

"OSError: [Errno 2] No such file or directory"

Do you have any ideas why this is happening? Thank you in advance!

***System info***
```
(bcbioenv) [appbuild@host]» lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:	7.2
Codename:	Maipo

(bcbioenv) [appbuild@host]» python -V                                           
Python 2.7.15

(bcbioenv) [appbuild@host]» pip -V                                              
pip 18.0 from /path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv/lib/python2.7/site-packages/pip (python 2.7)

(bcbioenv) [appbuild@host]» conda -V                                            
conda 4.5.10
```
***Downloading BCBIO installer***
```
(bcbioenv) [appbuild@host]» wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
--2018-09-10 11:11:42--  https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
Resolving raw.github.com (raw.github.com)... 151.101.200.133
Connecting to raw.github.com (raw.github.com)|151.101.200.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py [following]
--2018-09-10 11:11:42--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.200.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.200.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12796 (12K) [text/plain]
Saving to: ‘bcbio_nextgen_install.py’

100%[==============================================================>] 12,796      --.-K/s   in 0.002s

2018-09-10 11:11:43 (6.47 MB/s) - ‘bcbio_nextgen_install.py’ saved [12796/12796]
```

***Installing BCBIO***
```
(bcbioenv) [appbuild@host]» python bcbio_nextgen_install.py /path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv/lib/python2.7/site-packages/bcbio --genomes GRCh37 --aligners bwa --aligners bowtie2
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2018-09-10 11:28:40--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.200.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.200.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

100%[==============================================================>] 20          --.-K/s   in 0s

2018-09-10 11:28:40 (2.31 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Solving environment: done

## Package Plan ##

  environment location: /path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv

  added / updated specs:
    - bcbio-nextgen


The following packages will be REMOVED:

    bcbio-nextgen: 1.1.0-py27_0 bioconda

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done

## Package Plan ##

  environment location: /path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv

  added / updated specs:
    - bcbio-nextgen==1.1.0


The following NEW packages will be INSTALLED:

    bcbio-nextgen: 1.1.0-py27_0 bioconda

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 265, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by chapmanb** [comment]
Thanks for the detailed report and apologies about the install issue. I'm not entirely sure what happened here, as the failure is happening when the installer calls the installed `bcbio_nextgen.py` from the first step to add the tools and data. The main issue appears to be that you're installing this inside of an existing conda environment, `bcbioenv` that is in `/path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv` Is that a correct summarization of your setup environment?

The bcbio installer will download and install it's own isolated conda environment, and what I believe it happening here is that it is getting confused with your currently active environment. Can you avoid having a conda environment turned on and avoid installing inside the existing environment? Doing something like:
```
python bcbio_nextgen_install.py /path/Anaconda/bcbio --genomes GRCh37 --aligners bwa --aligners bowtie2
```
should hopefully get things installed correctly. Hope this helps.

**Comment by ponomarevsy** [comment]
Thanks for your feedback, Brad. Yes, you are correct about my setup, it was complaining about the PYTHONPATH during the install:
```
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda2.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda2: /path/Anaconda/2.3.0Linux-x86_64/envs/bcbioenv/lib/python2.7/site-packages/bcbio/anaconda
```
I always create a Conda environment first, because it is very easy to screw up other packages when installing directly into Anaconda. Since bcbio installer will create its own environment, it should be ok. Thanks for your help, I will give it a try. The question is, which Python to use? Can I still use the Anaconda's Python and install inside Anaconda? What would be the name of the new bcbio environment, would it install dependencies inside the new env, or directly into Anaconda's Python (that would be problem!!!).

**Comment by chapmanb** [comment]
Thanks for following up with this. You only need a very minimal Python to bootstrap the installation, so even just a basic system python or anything you have should work. You can use the full path to an Anaconda python if you don't have all of the environmental variables loaded as well, but really just using the plain system python is the easiest plan. From there bcbio will install it's own miniconda and environment and can add everything else needed. bcbio installs everything under the directory passed as the first argument to `bcbio_nextgen_install.py` so point that to something not conflicting with your existing Anaconda python. The installer doesn't try to install inside existing Anaconda installations and I'd advise against doing that, instead giving bcbio it's own unique path on the filesystem separate from your current Anaconda libraries. Hope this helps.

**Comment by ponomarevsy** [comment]
I did finish successfully this time! Thanks for all your help, Brad.
