### ISSUE TITLE
merged fastq but bams not the right size??

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2508]
Hi,

I've got two jobs each one required merging the fastq together before running. One worked: I had three pair of fastq and the total size of the merged fastq was around 80G X 2 file. The second merge also appeared to work and was around 80G. Actually, the two pairs of files were exactly the same size. However the bam file produced by the first job was ~126G and the second was around half the size. 
Even though the fastq files I give both jobs are the same size????
I noticed that the index for the fastq that gave the 126 G bam was about 6mb per file while for the one that produced the smaller bam was about 3mb. Does anyone recognize this problem? Thanks. 

load bcbio/20180613_hg38 && \
export TMPDIR=/localhd/`echo $PBS_JOBID | cut -d. -f1 ` && \
mkdir $TMPDIR/WGS/ && \
echo $TMPDIR/WGS/;
cp L004_R1.fastq.gz L004_R2.fastq.gz $TMPDIR/WGS/; \
cd /WGS/XTEN/; \
bcbio_nextgen.py -w template config/wgs-template.yaml L004_MERGED-merged.csv $TMPDIR/L004_R1.fastq.gz $TMPDIR/L004_R2.fastq.gz; \
cd XTEN/L004_MERGED-merged/;
bcbio_nextgen.py L004_MERGED-merged.yaml -n 7; \

**Comment by roryk** [comment]
There could be many reasons for this-- I recommend looking at the BAM files with `samtools flagstat` and seeing if the BAM files have similar number of alignments; it could be one of the samples has multimappers and the other does not.  I'd also look at the FASTQ files with FASTQC and see if there are similar reads. The command you are running looks like it is only looking at one of the samples by itself, so there could be configuration differences between the two runs as well.

**Comment by RobertWBaldwin** [comment]
Below is the output from samtools flagstat. There's twice as many reads in one of the bam files.
 As I said, the size of the fastq file pair passed in was the same (83 GB). So, still no sure why one bam is twice as large as the other. The numbers come from bam generated in the bcbio pipeline. They were generated with the same sample.yaml template. I also did a merging step with bcbio before hand, because each sample was sequence on 2 lanes so there were more than 1 fastq. It did not appear to me that anything in the output below would suggest the problem, so I'm trying fastqc as well. thanks


[rbaldwin@qlogin5 WGS]$ cat 42726367.out
1906975667 + 0 in total (QC-passed reads + QC-failed reads)
11525939 + 0 secondary
0 + 0 supplementary
245096126 + 0 duplicates
1869907942 + 0 mapped (98.06% : N/A)
1895449728 + 0 paired in sequencing
947724864 + 0 read1
947724864 + 0 read2
1819179186 + 0 properly paired (95.98% : N/A)
1854557526 + 0 with itself and mate mapped
3824477 + 0 singletons (0.20% : N/A)
24098364 + 0 with mate mapped to a different chr
13292877 + 0 with mate mapped to a different chr (mapQ>=5)
[rbaldwin@qlogin5 WGS]$
[rbaldwin@qlogin5 WGS]$
[rbaldwin@qlogin5 WGS]$
[rbaldwin@qlogin5 WGS]$
[rbaldwin@qlogin5 WGS]$
[rbaldwin@qlogin5 WGS]$
[rbaldwin@qlogin5 WGS]$
[rbaldwin@qlogin5 WGS]$ cat 42725802.out
930479610 + 0 in total (QC-passed reads + QC-failed reads)
6583450 + 0 secondary
0 + 0 supplementary
118284866 + 0 duplicates
904690350 + 0 mapped (97.23% : N/A)
923896160 + 0 paired in sequencing
461948080 + 0 read1
461948080 + 0 read2
875123060 + 0 properly paired (94.72% : N/A)
895736164 + 0 with itself and mate mapped
2370736 + 0 singletons (0.26% : N/A)
14150204 + 0 with mate mapped to a different chr
8178109 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by chapmanb** [comment]
Robert;
Thanks for helping debug this issue. It does look like the second sample (`42725802`) has ~1/2 the reads of the first. Since you mention they're both split into two fastqs and then combined, my initial thought would be that something is problematic about combining the input fastqs for the second case. If you used `bcbio_prepare_samples.py` it does a `cat` to combine multiple gzipped input files together. This typically works and then unzipped reads through both, but I've had it end up with truncated inputs in some cases where the initial fastqs were strangely gzipped in some way. In these cases I fixed it by explicitly gunzipping both files and re-bgzipped:
```
gunzip -c f1.fq.gz f2.fq.gz | bgzip -c > f.fq.gz
```
This is how the current development versions support for multiple input files works to be extra safe/paranoid (https://github.com/bcbio/bcbio-nextgen/blob/fd4dc6f15427daf9877f2e87bfd96578afcdf124/bcbio/ngsalign/alignprep.py#L698). This takes longer but might resolve the issue you're seeing.

Hope this helps.

**Comment by RobertWBaldwin** [comment]
thank you chapmanb ! I merged the fastq using your command above and then ran the bcbio pipeline and the output was what I was expecting.

**Comment by chapmanb** [comment]
Robert -- thanks for following up. I'm glad this fixed the issue for you. It might be worth investigating how the problem input gzipped fastq was generated to be able to catch this issue for other runs of your pipeline. Thanks much for the work debugging.
