### ISSUE TITLE
bcbio installation on aws ec2

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#2512]
Hi brad,

This time I am trying to do our 3rd bcbio installation on aws ec2. I am getting the below error. can you please help?

ERROR conda.core.link:_execute(502): An error occurred while installing package 'bioconda::genesplicer-1.0-1'.
LinkError: post-link script failed for package bioconda::genesplicer-1.0-1
running your command again with `-v` will provide additional information
location of failed script: /data/bcbio/anaconda/bin/.genesplicer-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

LinkError: post-link script failed for package bioconda::genesplicer-1.0-1
running your command again with `-v` will provide additional information
location of failed script: /data/bcbio/anaconda/bin/.genesplicer-post-link.sh
==> script messages <==
<None>

Fatal error: local() encountered an error (return code 1) while executing '/data/bcbio/anaconda/bin/conda install -y  -c conda-forge -c bioconda age-metasv bamtools=2.4.0 bamutil bbmap bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcftools=1.8 bedtools=2.27.1 bio-vcf biobambam bowtie bowtie2=2.2.8 break-point-inspector bwa bwakit cage cancerit-allelecount chipseq-greylist cnvkit coincbc cpat cramtools crossmap cufflinks cutadapt cyvcf2 deeptools delly dkfz-bias-filter ensembl-vep=93.* express extract-sv-reads fastp fastqc=0.11.7=5 fgbio freebayes=1.1.0.46 gatk gatk4=4.0.7.0 gemini geneimpacts genesplicer gffcompare goleft grabix gridss gsort gvcf-regions gvcftools h5py hap.py hisat2 hmmlearn hts-nim-tools htseq htslib impute2 kallisto>=0.43.1 kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv minimap2 mintmap mirdeep2=2.0.0.7 mirge mirtop moreutils mosdepth multiqc multiqc-bcbio ngs-disambiguate novoalign octopus oncofuse optitype parallel pbgzip peddy perl-sanger-cgp-battenberg phylowgs picard pindel pizzly platypus-variant preseq pyloh pysam>=0.13.0 pytabix pythonpy qsignature qualimap rapmap razers3=3.5.0 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation singlecell-barcodes smoove snap-aligner=1.0dev.97 snpeff=4.3.1t solvebio spades star strelka stringtie subread survivor svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java=1.5.1 variantbam varscan vawk vcf2db vcfanno vcflib verifybamid2 viennarna vt wham anaconda-client awscli bzip2 ncurses nodejs p7zip readline s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer bioconductor-titancna r-basejump>=0.5.8 r-bcbiornaseq=0.2.4a r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-ggrepel>=0.7 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-viridis>=0.5 r-wasabi r=3.4.1'

Aborting.

**Comment by chapmanb** [comment]
Diya;
Sorry about the issue. I haven't seen this problem before and am not sure what to suggest. The post-link script for genesplicer that's failing is only printing out a message:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/genesplicer/post-link.sh

So I'm not sure what is causing it to fail. If you re-run does it fail consistently? If so, can you try the suggestion of running with verbose enabled to see if that provides any additional information about what is failing?
```
/data/bcbio/anaconda/bin/conda install --yes -v genesplicer
```
Thanks for the help debugging.

**Comment by DiyaVaka** [comment]
Hi Brad,

I tried it on anew ec2 instance and this time it worked. I guess i am almost at the final stage where i encountered the below error. can you please help

[localhost] local: wget --continue --no-check-certificate -O chromFa.zip 'ftp://hgdownload.cse.ucsc.edu/goldenPath/mm10/bigZips/chromFa.zip'
--2018-09-26 18:11:22--  ftp://hgdownload.cse.ucsc.edu/goldenPath/mm10/bigZips/chromFa.zip
           => ‘chromFa.zip’
Resolving hgdownload.cse.ucsc.edu... 128.114.119.163
Connecting to hgdownload.cse.ucsc.edu|128.114.119.163|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /goldenPath/mm10/bigZips ... done.
==> SIZE chromFa.zip ... done.

==> PASV ... done.    ==> RETR chromFa.zip ... 
No such file ‘chromFa.zip’.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O chromFa.zip 'ftp://hgdownload.cse.ucsc.edu/goldenPath/mm10/bigZips/chromFa.zip''

[localhost] local: rm -rf /root/tmp/cloudbiolinux/5ee83fd3-81cf-3eda-a875-284a4f2cb7a9
[localhost] local: unzip chromFa.zip
unzip:  cannot find or open chromFa.zip, chromFa.zip.zip or chromFa.zip.ZIP.

Fatal error: local() encountered an error (return code 9) while executing 'unzip chromFa.zip'

Aborting.
INFO: Moving on to next genome prep method after trying raw
1
INFO: Moving on to next genome prep method after trying raw
1
Traceback (most recent call last):
  File "/data/bcbio/anaconda/bin/bcbio_nextgen.py", line 223, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 100, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 308, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/data/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/data/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 109, in _setup_vm
    configure_instance(options, actions)
  File "/data/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 269, in configure_instance
    setup_biodata(options)
  File "/data/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 251, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/data/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 340, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/data/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 482, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index seq for mm10 by any method
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 265, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/data/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/data', '--genomes', 'GRCh37', '--genomes', 'mm10', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Diya;
Sorry about the issue and thanks for the additional report. I'm not positive what is going wrong here as the mm10 sequences in the UCSC ftp site exist and are retrievable when I test here. Is it possible there were temporary issues connecting to the site and a re-try would fix the issue? Sorry to only have "try again" as a suggestion but hope this works for getting your install finished.

**Comment by DiyaVaka** [comment]
thank you

**Comment by roryk** [comment]
Looks like "try again" was the answer! :)
