### ISSUE TITLE
run_tests.sh failed

### ISSUE THREAD

**Issue by gandalfone** [bcbio/bcbio-nextgen#2515]
```
===================================================== FAILURES ======================================================
_____________________________________________ TestRunInfo.test_programs _____________________________________________

self = <tests.integration.test_pipeline.TestRunInfo object at 0x7fd362df1710>
data_dir = '/home/user/Git/bcbio-nextgen/tests/data/automated'

    @pytest.mark.speed1
    def test_programs(self, data_dir):
        """Identify programs and versions used in analysis.
            """
        from bcbio.provenance import programs
        with make_workdir() as workdir:
            config = load_config(get_post_process_yaml(data_dir, workdir))
>           print(programs._get_versions(config))

integration/test_pipeline.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

config = {'galaxy_config': '/home/user/Git/bcbio-nextgen/tests/data/automated/universe_wsgi.ini', 'resources': {'default': {'cor...'3G'}, 'dexseq': {'memory': '10g'}, 'express': {'memory': '8g'}, 'gatk': {'jvm_opts': ['-Xms500m', '-Xmx3500m']}, ...}}

    def _get_versions(config=None):
        """Retrieve details on all programs available on the system.
        """
        try:
            from bcbio.pipeline import version
            bcbio_version = ("%s-%s" % (version.__version__, version.__git_revision__)
>                            if version.__git_revision__ else version.__version__)
E                            AttributeError: 'module' object has no attribute '__git_revision__'

../bcbio/provenance/programs.py:171: AttributeError
=============================== 1 failed, 10 passed, 70 deselected in 915.28 seconds ================================
```

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the report. Can you provide more details about how you installed bcbio and are running the tests? This is complaining about not having git revision information in `bcbio/pipeline/version.py` but this should get added as part of standard installs:

https://github.com/bcbio/bcbio-nextgen/blob/master/setup.py#L9

Perhaps it's picking up a non-installed version or something else problematic is happening with your install. More details about your setup could help us figure this out. Thanks much.

**Comment by gandalfone** [comment]
Thanks for your reply.  My installation command is:
python bcbio_nextgen_install.py /Users/me/local/share/bcbio --tooldir=/Users/me/local --genomes GRCh37 --aligners bwa --aligners bowtie2

To run tests, I did following:
git clone https://github.com/bcbio/bcbio-nextgen.git
cd bcbio-nextgen/tests
./run_tests.sh

**Comment by chapmanb** [comment]
Thanks much for the additional details, this is really helpful in tracking down the issue. What was happening is that the tests were importing a blank `versions.py` file from the local close causing the failure. I pushed a fix to work around this. If you re-clone the bcbio-nextgen repository and re-run the tests it should now effectively avoid this issue and hopefully run cleanly for you. Thanks again for reporting and helping debug the issue.

**Comment by gandalfone** [comment]
Thanks much for the quick fix.
After git pull, I re-run ./run_tests above and it went through without any issue.
However, I ran ./run_tests.sh cancer, and it failed.  Here are details:
======================================================== FAILURES =========================================================
______________________________________________________ test_7_cancer ______________________________________________________

install_test_files = None, data_dir = '/opensource_proj/bcbio-nextgen/tests/data/automated'

    @pytest.mark.speed2
    @pytest.mark.cancer
    @pytest.mark.cancermulti
    @pytest.mark.install_required
    def test_7_cancer(install_test_files, data_dir):
        """Test paired tumor-normal calling using multiple
        calling approaches: MuTect, VarScan, FreeBayes.
        """
        with make_workdir() as workdir:
            cl = ["bcbio_nextgen.py",
                  get_post_process_yaml(data_dir, workdir),
                  os.path.join(data_dir, "run_info-cancer.yaml")]
>           subprocess.check_call(cl)

integration/test_automated_analysis.py:243:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['bcbio_nextgen.py', '/opensource_proj/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/opensource_proj/bcbio-nextgen/tests/data/automated/run_info-cancer.yaml'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_nextgen.py', '/opensource_proj/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/opensource_proj/bcbio-nextgen/tests/data/automated/run_info-cancer.yaml']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the Popen constructor.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           CalledProcessError: Command '['bcbio_nextgen.py', '/opensource_proj/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/opensource_proj/bcbio-nextgen/tests/data/automated/run_info-cancer.yaml']' returned non-zero exit status 1

/Users/me/local/share/bcbio/anaconda/lib/python2.7/subprocess.py:190: CalledProcessError
_________________________________________________ test_7_cancer_nonormal __________________________________________________

install_test_files = None, data_dir = '/opensource_proj/bcbio-nextgen/tests/data/automated'

    @pytest.mark.cancer
    @pytest.mark.cancerpanel
    @pytest.mark.install_required
    def test_7_cancer_nonormal(install_test_files, data_dir):
        """Test cancer calling without normal samples or with normal VCF panels.
        Requires MuTect and GATK.
        """
        with make_workdir() as workdir:
            cl = ["bcbio_nextgen.py",
                  get_post_process_yaml(data_dir, workdir),
                  os.path.join(data_dir, "run_info-cancer2.yaml")]
>           subprocess.check_call(cl)

integration/test_automated_analysis.py:257:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['bcbio_nextgen.py', '/opensource_proj/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/opensource_proj/bcbio-nextgen/tests/data/automated/run_info-cancer2.yaml'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_nextgen.py', '/opensource_proj/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/opensource_proj/bcbio-nextgen/tests/data/automated/run_info-cancer2.yaml']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the Popen constructor.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           CalledProcessError: Command '['bcbio_nextgen.py', '/opensource_proj/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/opensource_proj/bcbio-nextgen/tests/data/automated/run_info-cancer2.yaml']' returned non-zero exit status 1

/Users/me/local/share/bcbio/anaconda/lib/python2.7/subprocess.py:190: CalledProcessError
======================================== 2 failed, 79 deselected in 535.03 seconds ========================================

**Comment by chapmanb** [comment]
Glad to hear the base tests are passing and thanks for reporting the additional errors in the cancer run. Unfortunately I don't have enough information to offer any advice from the snippet you've posted. The end lines of the tests just tell you which tests failed, but the actual informative errors about why they failed are earlier up in the logs where the pipeline is run. You can either dig for those in your output to try and identify the cause or post the entire test output as a gist (https://gist.github.com/) and we can try to debug more. Thanks much.
