### ISSUE TITLE
Problems starting bcbio run on fresh ec2 install

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2522]
Im trying to run bcbio with a custom installed genome (hs37d5) and its crashing during align_prep, im guessing im missing a package on my ubuntu image?
[nohup.out.txt](https://github.com/bcbio/bcbio-nextgen/files/2409124/nohup.out.txt)

**Comment by chapmanb** [comment]
Patrick;
Sorry about the issue. You're right that it appears as if the install is missing something, but it's a bit hard to identify from this traceback. Are you able to re-run the pipeline without parallelization (using `-n 1`) and reproduce the error? If so, the traceback from that should tell us exactly what is missing and we can try and determine why it's not present in the install. Thanks much for the help debugging.

**Comment by PatrickJReed** [comment]
Thanks Brad, One 1 core, it is currently running fine, it past align prep and bwa is running on the first sample.

**Comment by chapmanb** [comment]
Patrick;
Thanks for confirming, that is frustrating it's not reproducible. If you run with multiple cores does it always fail at the same point? Sorry to suggest all these manual re-runs but I'm not sure how best to debug with what we have now. If it's a transient issue hopefully the analysis will finish cleanly.
