### ISSUE TITLE
Typo in "conflict"

### ISSUE THREAD

**Issue by ahwanpandey** [bcbio/bcbio-nextgen#2523]
Should this be "conflict"?

https://github.com/bcbio/bcbio-nextgen/blob/9fb4ab7b65ec41313a88d7f788b1d09dcf531349/bcbio/variation/strelka2.py#L179

**Comment by chapmanb** [comment]
Thanks much for catching this, you're exactly right. I pushed a fix for this typo. Much appreciated.
