### ISSUE TITLE
TypeError: can only concatenate list (not "str") to list

### ISSUE THREAD

**Issue by ahwanpandey** [bcbio/bcbio-nextgen#2524]
trying to concatenate list and string?
[ref] = list
alt = string

maybe need to remove brackets from ref?

https://github.com/bcbio/bcbio-nextgen/blob/9fb4ab7b65ec41313a88d7f788b1d09dcf531349/bcbio/variation/strelka2.py#L186

**Comment by chapmanb** [comment]
Thanks for looking at this. Could you post the full error you're seeing? This should concatenate two lists as `alt` is passed in a list of possible alternative alleles:

https://github.com/bcbio/bcbio-nextgen/blob/9fb4ab7b65ec41313a88d7f788b1d09dcf531349/bcbio/variation/strelka2.py#L292

Maybe with the full error message we can track down what is happening. Thanks for the help debugging.

**Comment by ahwanpandey** [comment]
Ah you are absolutely correct that the input has to be (ref -> string, alt -> list_of_strings)

I was just using the definition to retrieve the standard genotype encoding of a strelka VCF file so there isn't really a full log of the bcbio pipe.

Perhaps have an expected input types for at least the ref and alt in the function description?

Thanks for this conversion method! I still don't understand why the main developer is hesitant to include AD,AF and GT values in the final VCF.

**Comment by chapmanb** [comment]
Thanks for this, it could definitely be better documented for external use and I added that in to make it's usage more clear. I'm glad it's useful and appreciate your feedback.
