### ISSUE TITLE
ensemble error on aws ec2

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#2528]
Hi Brad,

I am trying to run platinum sample on aws installation and I am having issues with ensemble. Can you please hepl?

subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/mnt/bcbio/anaconda/bin:$PATH &&  /mnt/bcbio/anaconda/bin/bcbio-variation-recall ensemble --cores=4 --numpass 1 --names gatk-haplotype,freebayes,vardict --nofiltered /mnt/testrun/work/bcbiotx/tmpxAkvAs/NA12877-ensemble.vcf.gz /mnt/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /mnt/testrun/work/gatk-haplotype/NA12877-effects-annotated-filterSNP-filterINDEL-noeff-nomultiallelic.vcf.gz /mnt/testrun/work/freebayes/NA12877-effects-annotated-filter-noeff-nomultiallelic.vcf.gz /mnt/testrun/work/vardict/NA12877-effects-annotated-noeff-nomultiallelic.vcf.gz
2018-10-02 21:21:06 ip-172-31-31-90 INFO [bcbio.run.itx] - Note: -w option not given, printing list of sites...
2018-10-02 21:21:09 ip-172-31-31-90 ERROR [bcbio.variation.recall.main] -
java.lang.Exception: Problem retrieving reference variant for {:chr "2", :start 127413614, :refa "AG", :alta ["."], :end 127413616, :vc-indices (0)}: []
   bcbio.variation.ensemble.intersect/get-rep-vc/fn       intersect.clj:   58
                               clojure.core/comp/fn            core.clj: 2438
                                clojure.core/map/fn            core.clj: 2624
                          clojure.lang.LazySeq.sval        LazySeq.java:   40
                           clojure.lang.LazySeq.seq        LazySeq.java:   49
                                clojure.lang.RT.seq             RT.java:  507
                                   clojure.core/seq            core.clj:  137
                                clojure.core/map/fn            core.clj: 2616
                          clojure.lang.LazySeq.sval        LazySeq.java:   40
                           clojure.lang.LazySeq.seq        LazySeq.java:   49
                             clojure.lang.Cons.next           Cons.java:   39
                               clojure.lang.RT.next             RT.java:  674
                                  clojure.core/next            core.clj:   64
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj:  189
                         clojure.lang.RestFn.invoke         RestFn.java:  573
bcbio.variation.ensemble.intersect/ensemble-vcfs/fn       intersect.clj:   88
   bcbio.variation.ensemble.intersect/ensemble-vcfs       intersect.clj:   86
           bcbio.variation.ensemble.intersect/-main       intersect.clj:  140
                        clojure.lang.RestFn.applyTo         RestFn.java:  137
                                 clojure.core/apply            core.clj:  630
               bcbio.variation.recall.main/-main/fn            main.clj:   34
                  bcbio.variation.recall.main/-main            main.clj:   33
                        clojure.lang.RestFn.applyTo         RestFn.java:  137
                   bcbio.variation.recall.main.main                    :
' returned non-zero exit status 1

**Comment by DiyaVaka** [comment]
Running below returned empty (no results). 

[ec2-user@ip-172-31-31-90 work]$ tabix ./gatk-haplotype/NA12877-effects-annotated-filterSNP-filterINDEL-noeff-nomultiallelic.vcf.gz chr2:127413614-127413619
[ec2-user@ip-172-31-31-90 work]$ tabix /mnt/testrun/work/freebayes/NA12877-effects-annotated-filter-noeff-nomultiallelic.vcf.gz chr2:127413614-127413619
[ec2-user@ip-172-31-31-90 work]$ tabix /mnt/testrun/work/vardict/NA12877-effects-annotated-noeff-nomultiallelic.vcf.gz chr2:127413614-127413619

**Comment by chapmanb** [comment]
Diya;
Thanks for the detailed report and apologies about the issue. I'm not positive what is happening here, the ensemble method should be getting calls to look up from the input files and it's strange there are no variants in any file in those regions. My guess is that there's some unexpected/problematic variant in one of those files that we're not correctly dealing with.

My best suggestion would be to try expanding your tabix query to see if you can pick up any variants that are triggering the issue. I think if you decrease the start of these you'll pick up a deletion in one of the callers and we might have more information to work with. Thanks so much for the help debugging.

**Comment by chapmanb** [comment]
Diya;
Ivan reported a similar issue on the biovalidation mailing list and provided some example problem calls that appear to demonstrate the issue (https://groups.google.com/forum/#!msg/biovalidation/LcYsAkWebIs/tVywrb7DBAAJ).It appears as if MuTect2 is outputting some
problematic calls: reference only calls without an ALT allele. Since these
overlap the VarDict called variants it causes a lookup failure. I pushed a fix
to remove these calls prior to doing the ensemble call, which should resolve
the issue. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
remove the problem ensemble directory (`rm -rf ensemble`) and re-run, it
should re-normalize the inputs and hopefully work cleanly for you. Let us know if
you run into any other issues.
