### ISSUE TITLE
validation results for genome vs exome

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2537]
Hi,

I've used bcbio to run some WGS data and perform validation with NA12878 for the genome ( callable bed) and exome ( our target file ). I was a bit surprised by the results as the analysis was identical in both cases except for the "validate_regions" bed file that was used. The genome validation results looked really good, but the exome results had a much higher false discovery rate. Is this normal? Thanks - Robert

**Comment by chapmanb** [comment]
Robert;
Thanks for the discussion. Would you be able to share the numbers/graphs that you're seeing when comparing the genome and exome regions? The false discovery rate is relative to the total true positives so with lower true positives in restricted regions the percentages can be higher. If the targeted regions have relatively higher number of tricky regions relative to total regions (compared to the whole genome) this could explain the difference. Practically, if things look off to me in a validation I normally have to in and look at the calls in the `rtg` directory under `validation` to see if I can isolate regions or patterns causing the differences. Hope this helps with digging into your results.

**Comment by RobertWBaldwin** [comment]
At 30X WGS Callbale regions:
3207710 TP SNP; 2259 FN SNP; 24020 FP SNP
447097 TP INDEL; 33646 FN INDEL; 5075 FP INDEL

At 30X WGS validate_regions set to exome target regions:
38950 TP SNP; 30 FN SNP; 8934 FP SNP
2982 TP INDEL; 161 FN INDEL; 1236 FP INDEL

So for INDELS the FP went from ~1% to >25% and for SNPs from <1% to >15%. The FN rate decreased however. So it's very sensitive, too sensitive actually for my purposes. It's just seems odd that the exome target would vary so much from the genome as a whole. And we're talking about the callable exome too, right, because bcbio is still using mosdepth to exclude problem regions.

**Comment by RobertWBaldwin** [comment]
Here's my template in case it helps. The start point is the bam that I generated with the first run of bcbio, which had about ~30x coverage. So I'm not remapping. And I'm passing in the bed file for validation. That's the only difference. And the FP for genome was around 1%. 


# Template for whole genome variant calling only with validation
details:
  - analysis: variant2
    genome_build: GRCh37
    description: 'L004'
    files: [NA12878-30x.bam]
    algorithm:
      tools_on:
      - svplots
      - qualimap
      aligner: false
      clinical_reporting: true
      coverage_interval: genome
      variantcaller: gatk-haplotype
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: /hpf/largeprojects/pray/llau/internal_databases/baits/SS_clinical_research_exomes/S06588914.MT/S06588914_Covered.sort.merged.bed
      ploidy: 2
      coverage_depth_max: 1000
    resources:
      default:
        memory: 7G
        cores: 7
    upload:
      dir: ../final

**Comment by chapmanb** [comment]
Robert;
Thanks much for following up and posting your configuration. This helps identify right away the key difference. You want to set `variant_regions` as your `S06588914_Covered.sort.merged.bed` exome BED file, and leave `validate_regions: giab-NA12878/truth_regions.bed` as before. The Genome in a Bottle truth regions exclude difficult genomic regions enriched in false positives, which is why you see such a relative increase here. bcbio will then do your comparison as the intersection of three sets of regions: the exome regions in your BED, the callable regions within those exome targets, and the non-problematic Genome in a Bottle regions within those. That should hopefully give you more comparable numbers. Hope this helps.

**Comment by RobertWBaldwin** [comment]
o.k this is making sense now. I had intersected the FP from the callable genome with the exome target and found that very few of the FP in the exome validation appeared in the genome validation so obviously things were not working the way I had thought. thanks so much for your help - Robert

**Comment by RobertWBaldwin** [comment]
sorry I'm still trying to understand this.
I intersected the exome target file bed, bcbio truth_regions bed, and the callable_regions at 30x genome, and found that the amount of overlap between truth_regions and callable was 100%, that is, callable had 2,574,337,224 bp and truth regions had 2,575,064,465 bp and the intersection of these intervals amounted to 2,574,337,224 bp. Is this right to you? Because bcbio restricts calling to "callable" right, so how could validation have been done outside of truth if call all callable are in truth? I obviously am very confused - Robert

**Comment by chapmanb** [comment]
Robert;
I'd expect the callable regions to get reduced by intersection with the truth regions. Typically we can call in regions that are not in the truth regions, but they're just not reliable. So what you're seeing is confusing to me as well. Did you run the analysis with `variant_regions` and `validation_regions` as I described above and find things still didn't make sense? Or are you just trying to manually look at the overlaps? It's a bit hard to debug remotely on the later without actually having the files and commands your running, but at this point it would be useful to determine if the automated runs give you results that match your intuition. Thanks for the help debugging and hope this is useful.

**Comment by RobertWBaldwin** [comment]
Thanks for your help. My new results with the config below worked well and are consistent with what I got for the whole genome.

#########  
aligner: false
      clinical_reporting: true
      coverage_interval: genome
      variantcaller: gatk-haplotype
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: target.bed

But I did not see callable regions reduced by intersection with truth regions. 
The callable regions was 50,149,291 bp and truth_regions was 2,575,064,465 bp. The intersection was 50,149,291 bp. So no reduction. The target was 53,985,347 bp and the intersection of target with callable was 50,149,291 bp.

I used bedtools intersect to calculate the overlap between bed files using this command:
bedtools intersect -wo -a target.bed -b NA12878-30x-dedup-callable_sample-L004-gatk-haplotype-wrm.bed

The truth regions file I used was here: 
bcbio/20180111/genomes/Hsapiens/GRCh37/validation/giab-NA12878/truth_regions.bed and does not change from one config to the other. 

The callable regions I got here:
/30X/12878EX/work/validate/L004/gatk-haplotype/NA12878-30x-dedup-callable_sample-L004-gatk-haplotype-wrm.bed

The callable bed changed in size compared to the whole genome validation. From what I understand this  is because I did not actually call over the whole genome this time around when using the variant_regions option with my exome target file. But even calling over the whole genome, I still found callable to be in truth_regions. Perhaps I'm doing something wrong? But isn't truth regions 2,575,064,465 bp? That's quite large.

**Comment by gabeng** [comment]
Robert,
it is highly unlikely that your entire exome should be located inside truth_regions. Only 92% of CCDS is contained in truth_regions. What is the result of intersecting your target.bed with truth_regions?

**Comment by RobertWBaldwin** [comment]
target:                     53,985,347
target x truth:          50,168,872
target x callable:     50,149,291
truth:                  2,575,064,465
callable:                  50,149,291
truth x callable:       50, 149,291

From what I understand, there should be a region that is callable, on target, and not in truth. But I can't find it.

**Comment by chapmanb** [comment]
Robert;
Thanks for following up on this. If you're using the callable regions BED file from within the validate directory, that has already been subset by the truth regions. That's why it's smaller than `target x truth` (since it's within those two regions) and why you don't see further subsets when comparing it. Apologies, I'd thought you were referring to the original callable file; this validation one gets pre-prepared with all the intersections you're doing by hand.

Glad the results make sense now in the validation and hope this helps explain your results.

**Comment by RobertWBaldwin** [comment]
Thanks that makes sense. So I need the prealigned-callable-sample.bed then for just the callable regions. I can see it in the log file but can't seem to find it in the directory afterwards. Does it go by a different name once the analysis is finished?

**Comment by RobertWBaldwin** [comment]
o.k thanks. So the callable region is here:
L004-dedup-callable_sample.bed

and the intersection of truth and callable is the L004-dedup-callable_sample-L004-gatk-haplotype-wrm.bed file. 

I was looking over the output of mosdepth and it looks like callable at least temporarily goes by the name:

L004-variant_regions.quantized-vrsubset-callableblocks-merged.bed.gz

though I can't actually find that file in the output though I do have L004-variant_regions.quantized-vrsubset-callableblocks.bed. The merge step I guess is just to merge overlapping intervals. Is it just renamed to L004-dedup-callable_sample.bed in the final output? thanks!

**Comment by chapmanb** [comment]
Robert;
That's perfect, you've got the right file now. There are some intermediates during the processing steps from the raw mosdepth output. Hope this all helps explain the validation results and regions. Please let us know if you have any other questions.

**Comment by roryk** [comment]
Thanks, look like this got asked and answered. Thanks everyone!
