### ISSUE TITLE
HDF5 error message associated with R 3.4.1

### ISSUE THREAD

**Issue by xinweihan** [bcbio/bcbio-nextgen#2545]
When running the RNA-seq pipeline with Salmon, I got the following error message on STDERR:
Error in on.exit(H5Sclose(h5spaceMem), add = TRUE, after = FALSE) :
  unused argument (after = FALSE)

This error seems to be minor, as I got all the output files, such as TPM, correctly. After some google search, this error is likely due to R version <3.5.
https://support.bioconductor.org/p/112131/

In my instance of bcbio, the R version is 3.4.1.

Just want to make sure this error would not impact the analysis, and also bring it to your attention if you have not noticed it.

Many thanks,
Xinwei

**Comment by roryk** [comment]
Thanks-- good diagnosis. Could you tell me which version of hdf5 is installed for your R that is in bcbio? If you load up that R and do:

```r
library(wasabi)
sessioninfo::session_info()
```

could you paste the output?

**Comment by roryk** [comment]
I'm thinking we might have to pin the rhdf5 package to a something like 2.22.0 while we're waiting on R 3.5 support to be finished up in bioconda. RIght now we can't switch over yet, but should be able to soon.

**Comment by xinweihan** [comment]
It is rhdf 2.24.0 as shown below.

─ Session info ──────────────────────────────────────────────────────
 setting  value
 version  R version 3.4.1 (2017-06-30)
 os       Red Hat Enterprise Linux
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       America/New_York
 date     2018-10-24

─ Packages ────────────────────────────────────────────
 package     * version date       source
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.4.1)
 data.table    1.11.4  2018-05-27 CRAN (R 3.4.1)
 rhdf5         2.24.0  2018-10-10 Bioconductor
 Rhdf5lib      1.2.1   2018-10-10 Bioconductor
 rjson         0.2.20  2018-06-08 CRAN (R 3.4.1)
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.1)
 wasabi      * 0.2     2017-09-18 local
 withr         2.1.2   2018-03-15 CRAN (R 3.4.1)

**Comment by roryk** [comment]
Thanks-- do you happen to have an R 3.5 install somewhere that could be getting picked up? I can only seem to get 2.20.0 with R 3.4.1 installed.

**Comment by xinweihan** [comment]
Yes, the system R (/usr/bin/R) is 3.5. After installation of bcbio, the R in path is 3.4.1 .

**Comment by roryk** [comment]
Thanks-- is anything set in your .Renvironment, .Rprofile or .bashrc that is adding the system R libraries to your path? We added in the recent version for R to ignore the .Renvironment file, but there are other ways it can leak in.

**Comment by xinweihan** [comment]
I created a clean account (under Azure Redhat linux) for bcbio installation. There is no .Renvironment or .Rprofile file. In .bashrc, /usr/bin is in the path, and thus the system R (/usr/bin/R) is in the path by default.

**Comment by roryk** [comment]
Thanks-- hm. Could you send the output of running `set` so we can see which environment variables are set? I'm super confused how its picking up 2.24.0.

**Comment by xinweihan** [comment]
Sorry, I can no longer log onto that VM, due to change of working environment. But thank you for the following up.

**Comment by mjsteinbaugh** [comment]
@roryk I can confirm this error goes away with the bcbio v1.1.1 update. Isolating the conda r-base used internally by bcbio fixes the issue (as mentioned in Slack).

**Comment by mjsteinbaugh** [comment]
Actually scratch that, I'm still seeing this in the rnaseq unit tests. It runs through fine, just warnings are returned.

**Comment by roryk** [comment]
Thanks-- we've moved on to R 3.5, and R 3.6 is on the way, so this should be a non-issue now.
