### ISSUE TITLE
KeyError: 'rawumi_avg_cov' in a UMI analysis

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2554]
Like the subject says, it fails in the QC step:

```python
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 303, in pipeline_summary
    return ipython.zip_args(apply(qcsummary.pipeline_summary, *args))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 70, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 162, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/umi.py", line 63, in run
    out["umi_raw_avg_cov"] = data["config"]["algorithm"]["rawumi_avg_cov"]
KeyError: 'rawumi_avg_cov'
```

**Comment by chapmanb** [comment]
Luca;
Thanks much for the report. Would you be able to share your configuration and a brief description of your inputs? Is it a standard paired end UMI run? Any other information to help me try to reproduce? This value should always be present when the UMI consensus gets generated (https://github.com/bcbio/bcbio-nextgen/blob/7a4cd102d8b455250c127015cbfb76b9f9890b45/bcbio/pipeline/sample.py#L133), but I'm clearly missing a case. I pushed a work around to avoid the error so you can get your analysis finished but would also like to try and understand the underlying cause. Thanks again for the help debugging.

**Comment by lbeltrame** [comment]
It's a single end UMI run (it doesn't come from an Illumina instrument) where the UMIs are on the first 8bp of each read. I'll get you a configuration shortly.

**Comment by lbeltrame** [comment]
Excerpt with some data redacted:

```yaml
details:
- algorithm:
    aligner: bwa
    coverage: my_regions
    coverage_interval: amplicon
    mark_duplicates: true
    umi_type: fastq_name
    ensemble:
      numpass: 1
    min_allele_fraction: 0.5
    platform: illumina
    quality_format: Standard
    recalibrate: false
    trim_reads: false
    effects: snpeff
    variant_regions: my_regions
    variantcaller:
    - vardict
    - mutect2
    - gatk-haplotype
  analysis: variant2
  description: Sample
  files:
  - /bioinformatics/platform/Sample.fastq.gz
```

**Comment by chapmanb** [comment]
Luca;
Thanks much for the example configuration. The underlying issue is that we don't currently support UMIs for single end reads. fgbio consensus calling uses dual indexes from pairs and we don't have a workflow to collapse from single reads. Apologies, we haven't run across this type of data before and it was silently skipping over using the UMIs. I pushed a fix to at least report an error so you would know it's not working.

Do you know of any single end UMI workflows we should be using here? I don't have any experience with non-paired UMIs so trying to understand what we should work to support in bcbio. Thanks again for the report and sorry to not be able to handle this right now.

**Comment by lbeltrame** [comment]
> Do you know of any single end UMI workflows we should be using here?

I don't know in detail at the moment, I know that the QIAGEN GeneReader uses this single-read, 8bp 5' UMI in front of each of their (variable-length) reads. Most of the stuff is being done in their custom analysis program so currently I'm trying to figure out (and if I *can* figure out) what is the process being done there.

**Comment by lbeltrame** [comment]
I've looked into it more and it seems like stuff like UMI tools (https://github.com/CGATOxford/UMI-tools/) can handle the tagging of single-end reads. I'll likely do alignment and tagging manually and then check what happens downstream with bcbio.

**Comment by chapmanb** [comment]
Luca;
Thanks for this. Tagging should not be a problem, but the main issue is we don't have a way to process these inside of bcbio once you have the tags. fgbio, the tool we currently use, builds consensus reads from the shared UMI reads at the same position, but requires paired reads. For single end we'd need to come up with a similar approach to collapse duplicates by both position and UMI. If you come up with a good approach to handle this then we can spec out including in bcbio. Thanks again.
