### ISSUE TITLE
move installation to different account/location

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2556]
I've kept a bcbio installation under a local account but would like to transfer it to a new location under a different account. Is there any convenient way of doing this?

I tried copying the whole thing, modified ownership and paths wherever I could find them using  
``` sed -i 's/oldpath/newpath/' ``` on the whole thing. Didn't work.

Would anyone know if it would work by listing installed conda packages, reinstalling them again in the new location?

**Comment by chapmanb** [comment]
Pär;
Thanks for the question. Unfortunately you can't move conda directories as they contain hard coded paths, so this could break your software installation under `anaconda`. My suggestion would be to move the data directory (`/oldpath/genomes`) into the new location and then run a clean install against this. It'll need to reinstall the tools but can make use of the existing genome data which is typically most of the download time. Hope this works for your needs.

**Comment by parlar** [comment]
Thanks! 

(and please excuse my slow response.)
