### ISSUE TITLE
delete the input fast.gz and restart a run 

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2559]
Hi Brad, Is possible to restart a run  if the initial fast (or bam file) has been removed if the allign and align_prep are presents. I am just wondering would be the best way to save some space but still be able to update a project with new samples.

Thanks a lot!
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
My recommendation would be to keep the pre-aligned bcbio BAMs after the initial run, and then use those as input into a new project run with `aligner: false` so you don't need to re-run the alignment step but can include these along with your new samples. I think removing the initial files and replacing with an empty fastq placeholder will work, as you suggest, but that much custom work seems like something might accidentally do wrong. Re-creating a project and having everything explicit will help avoid any mistakes and give you an easy path to cleaning up older projects. Hope this works for you.
