### ISSUE TITLE
Cannot install bcbio

### ISSUE THREAD

**Issue by LeeNicha** [bcbio/bcbio-nextgen#2560]
Hi

I got an error during running this command: python bcbio_nextgen_install.py /home_sbi_cold/onnicha/program/fix_bcbio --tooldir=/home_sbi_cold/onnicha/program/fix_bcbio/ --genomes hg19 --aligners bwa

Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --only-deps
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 265, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 82, in install_conda_pkgs
    "-c", "conda-forge", "-c", "bioconda", "--only-deps", "bcbio-nextgen"], env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home_sbi_cold/onnicha/program/fix_bcbio/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', '--only-deps', 'bcbio-nextgen']' returned non-zero exit status 2

Could you help me, please?
Thank you in advance.

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the detailed report. The error message looks like you might be installing into an existing conda environment in `/home_sbi_cold/onnicha/program/fix_bcbio/anaconda`. If you run:
```
/home_sbi_cold/onnicha/program/fix_bcbio/anaconda/bin/conda --version
```
what does it resport? We should be currently getting conda 4.5 or better but if you had an older existing version there bcbio don't try to update it. You could upgrade the current conda there:
```
/home_sbi_cold/onnicha/program/fix_bcbio/anaconda/bin/conda install -c conda-forge conda
```
or remove the `/home_sbi_cold/onnicha/program/fix_bcbio/anaconda` directory altogether and let bcbio recreate it.

If you do either of those and then re-run the `bcbio_nextgen_install.py` command it should hopefully proceed and finish the install. Hope this gets it going for you.
from inside a loaded conda environment, as the installer should be using the `conda` from `/home_sbi_cold/onnicha/program/fix_bcbio/anaconda/bin/conda` but instead picks it up from an external location: `

**Comment by roryk** [comment]
Closing this, as it's stale and should be working. Thanks!
