### ISSUE TITLE
CVMFS for bcbio-docker implementation

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2561]
Hi Brad,

Just a quick question. Have you considered using CVMFS with `autofs` to mount reference data to the bcbio docker image when using CWL? The Galaxy docker image uses this to host reference data for jobs etc. Perhaps something like this could help solve the issues with VEP caches and the likes.

Cheers
M

**Comment by matthdsm** [comment]
Hi Brad, 
I don't think cromwell, or any jobrunner supporting images should influence this, as it is something thats done inside the docker image, so it should be runnner agnostic.
Perhaps @bgruening could elaborate on this.

Björn, If you don't mind, could you discuss some of your experiences with docker and autofs for CVMFS? The idea is we could mount the FS with reference data on a docker image in order to run CWL jobs. Is this within the scope of the CVMFS? I think galaxy does this too?

Thanks
M

**Comment by bgruening** [comment]
Yes Galaxy does this and its working for us great. Anything you need to know more specific?

**Comment by matthdsm** [comment]
Hi Björn,

Thanks for the reply. Do you think CVMFS would scale well for a bigger number of jobs?
Am I correct when I say the performance is independent of job runners?

Thanks again
Matthias

**Comment by bgruening** [comment]
> Thanks for the reply. Do you think CVMFS would scale well for a bigger number of jobs?

We do run big jobs and we did not had problems with it.
BUT, this all depends on how you setup CMVFS. CVMFS is at first just a FS with a lot of deployment options. Put in a large cache and you should not see a difference in performance.

> Am I correct when I say the performance is independent of job runners?

The performance of the CVMFS? After the file is downloaded its more or less a local access.

**Comment by chapmanb** [comment]
Matthias and Björn;
Thanks much for this background. Right now I really don't have a good grasp of how you setup CMVFS and what tweaks you need to Docker to make this happen. Practically, with the move to CWL bcbio itself no longer does any explicit mounting of external data and it all happens as part of the runners themself which is why I mentioned Cromwell. If you could walk me through what needs to happen to support this we can try to explore more. Thanks again.

**Comment by roryk** [comment]
Let us know if you're running into any issues from this not being implemented-- we've put CWL work on ice for the time being while we do a bunch of other maintenance work, so we're unlikely to explore this unless there is a big demand for it. Thanks so much!
