### ISSUE TITLE
callable vs not callable

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2562]
I have a question about the mosdepth step in the bcbio pipeline. Specifically, I'd like to know why the mapping quality threshold is set at 1 ( i.e., reads with MQ < 1 are not considered ). Apparently HaplotypeCaller has a read filter that it applies using a MQ of 10, so reads with MQ < 10 are not used for assembly. If that's the case, then why do we need reads with MQ < 10 when using HC at all? Why not just define callable as 4 or more reads with MQ >= 10? Thanks !

**Comment by RobertWBaldwin** [comment]
As I've been investigating the various regions created by the intersection of target, callable, and truth regions I also have a question about the not-callable regions. I went back and generated a vcf using the same haplotypeCaller settings as bcbio but did not exclude any regions. I then looked at what calls were in the not-callable X not-truth regions for different coverages (40, 50 and 60X). In the truth set provided by bcbio I found there were a few snps in these regions but that's all, and no calls were made by HC in my data at any level of coverage. 

Is this to be expected? I mean for 0 coverage obviously you're not going to get anything. But I thought some sites with 1-3 goods reads might produce something. If you can't get calls in these regions anyways then why take the time to exclude them before running HC? Thanks!

**Comment by roryk** [comment]
Sorry for not answering this question Robert, let us know if you still need it answered and I'll answer it.
