### ISSUE TITLE
bcbio not picking up jvm_opts from system config file

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2565]
Dear Bcbio team,

I am running bcbio gatk-variant pipeline. By default it generates vcf and I modified run specific configuration file with gvcf as result and I can see the option was picked up in commands.log.
Job was failing with java heap space error
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

When I gone through bcbio issues, it was mentioned to change jvm_opts in system config file. I updated the same like below.

  gatk:
    dir: /gpfs/software/genomics/bcbio-v1.0.8/bin/
    jvm_opts:
    - -Xms5g
    - -Xmx15g

I tried with and without "dir" line, but still jvm_opts were not picked by haplotypecaller and giving same error.
Here is the command from run:

Command 'set -o pipefail; unset JAVA_HOME && export PATH=$PATH && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=tmpRP1Jwd' HaplotypeCaller -R Hsapiens/GRCh37/seq/GRCh37.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I brain-sort.bam -L 10:1-111572172 --interval-set-rule INTERSECTION --disable-read-filter NotDuplicateReadFilter --annotation ClippingRankSumTest --annotation DepthPerSampleHC --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 --output brain-10_0_111572172.vcf.gz

Could you please help me to resolve this error.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the report and apologies about the issue. That specification should work, but it also needs to be nested under resources, either in your sample YAML file or `bcbio_system.yaml` file:
```
resources:
  gatk:
    jvm_opts: [-Xms5g, -Xmx15g]
```
Does that nesting match what you have in your configuration file? You do not need the `dir` specification since gatk4 is now installed with bcbio. Hope this fixes it for you.

**Comment by Fazulur** [comment]
Dear Brad Chapman,

Thanks a lot for your quick response. I modified in both sampe YAML and bcbio_system.yaml file. Still I am having the same error and it's not picked up by HaplotypeCaller.

Please below  bcbio_system.yaml  and sample YAML file 

galaxy_config: universe_wsgi.ini
resources:
  default:
    cores: 8
    jvm_opts:
    - -Xms750m
    - -Xmx3500m
    memory: 3G
  dexseq:
    memory: 10g
  express:
    memory: 8g
  **gatk:
    jvm_opts:
    - -Xms5g
    - -Xmx15g**
  macs2:
    memory: 8g
  qualimap:
    memory: 4g
  seqcluster:
    memory: 8g
  snpeff:
    jvm_opts:
    - -Xms750m
    - -Xmx3g

And Sample YAML file

details:
- algorithm:
    aligner: bwa
    recalibrate: gatk
    **tools_on:
    - gvcf**
    variantcaller: gatk-haplotype
  analysis: variant2
  description: brain
  files:
  - brain_1.fastq
  - brain_2.fastq
  genome_build: GRCh37
fc_name: project_brain
upload:
  dir: ../final
**resources:
  gatk:
    jvm_opts: [-Xms5g, -Xmx15g]**

Could you please correct me If I am missing something in configuration files.

Thanks In Advance
Fazulur Rehaman

**Comment by RobertWBaldwin** [comment]
Below is my config file using jvm opts. It works. Try to formatting your file similarly. - Robert 



###########


details:
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    validate: giab-NA12878/truth_small_variants.vcf.gz
    validate_regions: giab-NA12878/truth_regions.bed
  analysis: variant2
  description: 'gatk4_validation'
  files:
  -WGS_NA12878_1.fq.gz
  - WGS_NA12878_2.fq.gz
  genome_build: GRCh37
fc_name: gatk4
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final

**Comment by RobertWBaldwin** [comment]
`
details:
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    validate: giab-NA12878/truth_small_variants.vcf.gz
    validate_regions: giab-NA12878/truth_regions.bed
  analysis: variant2
  description: 'gatk4_validation'
  files:
  - /hpf/largeprojects/ccmbio/naumenko/validation/WGS_NA12878/input/WGS_NA12878_1.fq.gz
  - /hpf/largeprojects/ccmbio/naumenko/validation/WGS_NA12878/input/WGS_NA12878_2.fq.gz
  genome_build: GRCh37
fc_name: gatk4
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
`

**Comment by Fazulur** [comment]
Dear Brad Chapman,

After changing default jvm_opts in bcbio_system.yaml configuration, it worked.

galaxy_config: universe_wsgi.ini
resources:
default:
cores: 8
**jvm_opts:
- -Xms5g
- -Xmx15g**

Thanks for helping me to resolve this issue.

Is there any way we can bypass resources like gatk jvm_opts or number of cores etc in run specific YAML file so that it will overwrite the values in bcbio_system.yaml and use them for that run specifically. I tried adding resources in run specific yaml file without changing bcbio_system.yaml, but it's not working.

Please let me know your suggestions.

Thanks In Advance
Fazulur Rehaman

**Comment by Fazulur** [comment]
Dear Brad and Robert Baldwin,

Thanks a lot. Issue was resolved after adding default under resources section of run specific YAML file.
resources:
defaults:
    jvm_opts: [-Xms5g, -Xmx15g]

Now I want to change output extension from vcf to g.vcf. i have checked issues section for relevant thread and didn't found anything.

Could you please suggest me.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Glad to hear the resources specification fixed the memory issues, thank you for your persistence in working through the issues. We don't have a way to change or configure output file naming. In general we avoid trying to have configuration at this level of detail as it leads to having too many options for tweaking. Most users with custom needs handle by renaming/moving outputs after bcbio finishes. Hope this works for your needs.
