### ISSUE TITLE
Installation fails cause of missing package version 1.1.1

### ISSUE THREAD

**Issue by moritzschaefer** [bcbio/bcbio-nextgen#2566]
conda still only lists version 1.1.1a, while your requirements-conda.txt requires version 1.1.1

**Comment by chapmanb** [comment]
Moritz;
Apologies about the issue. You caught us in the middle of building a new release. If you update or install now with:
```
bcbio_nextgen.py upgrade -u stable
```
the package is now available in conda and should work cleanly. Please let us know if you run into any other issues.
