### ISSUE TITLE
adding GnomAD to gemini config

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2570]
Hi Brad,

how would you feel about supplanting ExAC with Gnomad Exome in the default gemini config? This would remove the need for some `postannotation` scripting, and the users would get updated frequencies.
Alternatively, instead of removing ExAC, we could just add GnomAD?

Cheers
M

**Comment by chapmanb** [comment]
Matthias and Luca;
Thanks for starting this conversation. I'm definitely open to replacing ExAC with GnomAD. My main concern is around file sizes and how to manage hg38 support. Right now I believe it's still build 37 only (http://gnomad.broadinstitute.org/downloads) and I didn't see any hg38 liftover resources prepared for release 2.1 with a quick search. For sizes, are you thinking of just the exomes (60Gb)? Annotating in genomic regions is definitely useful, but the genomes are pretty unwieldy (464Gb). What were your thoughts about what we'd provide and support? Thanks again.

**Comment by lbeltrame** [comment]
Considering I'd use it mostly to evaluate variants, I'd be in support of using the exomes only.

**Comment by matthdsm** [comment]
Hi Brad,

I'd suggest using the VCFs hosted by Ensembl (v2.0.1), since there's no real effort towards hg38 compatibility from Broad. As for the ExAc replacement, I'd stick to the exomes and leave the gemomes optional (as it is now). If you're okay with this, I've already got a PR ready to implement these changes.

Cheers
M

**Comment by chapmanb** [comment]
Matthias and Luca;
Thanks, using the Ensembl resources makes good sense. Nice catch, I should have thought of that. Keeping up to date would be useful if Ensembl will be synchronizing soon. There are a number of calling improvements in 2.1 (https://macarthurlab.org/2018/10/17/gnomad-v2-1/). To me, the most useful are the subsets excluding cancer, case genomes, and neurology studies. This could help a lot with avoiding low frequency events from gnomAD samples correlated with different experimental conditions. Thanks so much for looking at this.

**Comment by matthdsm** [comment]
I've sent an e-mail to the Ensembl helpdesk to ask if they plan to update their resources. Is it ok for now if we stick to v2.0.1? I'll submit a PR replacing ExAC with GnomAD shortly.
I this it's safe to remove the ExAC GGD recipe after this, since I don't think it'll be used anymore.

Cheers
M

**Comment by matthdsm** [comment]
The PR have been made. The annotations should be as similar as possible to the ExAC ones (barring the field names). I've also added some extra fields we feel are important for variant interpretation (GC's, HOM/HET counts, ...)

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for all this work. Using Ensembl makes great sense, and we can take advantage of all the work they do harmonizing and updating these. I've merged all your PRs and synchronized so think this is good to go now. Please let me know if you run into any issues.

Right now we're duplicating with ExAC annotations as I'm worried about breaking folks downstream scripts. I'll probably do in parallel for now and then move off ExAC over time to give time to adapt.

Thanks again.
