### ISSUE TITLE
AssertionError: Pisces supports tumor-only variant calling

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2574]
Brad,
thanks for the tremendous work on benchmarking somatic callers. I wanted to try Pisces on a tumor only sample and got an error message (with development version `520fad7`). Does Pisces support only paired tumor-normal samples?

**Comment by chapmanb** [comment]
Ben;
Thanks for the question and for trying out Pisces. In addition to the error you're getting, it does require manual installation of the dotnet runtime to use, as that's not currently packaged into the conda installs.

Pisces only supports tumor-only variant calling, so the code has a check for this and is reporting the error you're seeing. It should error out if your sample either has a normal associated with it, or if the tumor only input isn't labelled as `phenotype: tumor`.  Do either of those cases apply to your configuration? Hope this helps get it running for you.

**Comment by gabeng** [comment]
Brad,
ok, dotnet is certainly not installed, hence the error. I will check how to install dotnet by hand.
Thanks for the hint!

**Comment by chapmanb** [comment]
Ben;
I added a link to the .NET install from the documentation on optional requirements: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

To be clear, this isn't the source of your issue, which has something to do with how your tumor-only sample is organized, but I just wanted to avoid you hitting another error immediately after fixing that.

Thanks for exploring Pisces and hope this helps

**Comment by gabeng** [comment]
Brad, 
you are right, I have a number of other issues with this sample that are not related to bcbio at all. Thanks for the link. It should be easy to bake this into the docker image.
