### ISSUE TITLE
bcbio I/O error with lsf pending jobs

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2576]
Dear bcbio team,

I am getting I/O errors when I am submitting job using lsf as scheduler. I observe when job goes to pending state, it waits for 15minutes (defaults timeout)  and kills the job if still in pending state. I have gone through --timeout parameter of bcbio and implemented. When I check cluster log, it is not able to pick --timeout value and still showing default 960.
Command 
**bcbio_nextgen.py test.yaml -t ipython -s lsf -q normal --timeout 20000 -n 64**

Here is the lsf_engine file during run

**#BSUB -q normal
#BSUB -J test-e[1-1]
#BSUB -oo bcbio-ipengine.bsub.%%J
#BSUB -n 1
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=1024]"
#BSUB -P bcbio-test

export IPYTHONDIR=scratch/log/ipython
bcbio-v1.0.8/anaconda/bin/python -E -c 'import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from ipyparallel.apps.ipengineapp import launch_new_instance; launch_new_instance()' --timeout=960 --IPEngineApp.wait_for_url_file=960 --EngineFactory.max_heartbeat_misses=120 --profile-dir="scratch/log/ipython" --cluster-id="53978dca-9083-43bf-a7e7-30ea843987b3"**

Could you please suggest me how can I resolve this type of error.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the detailed report and sorry about the issues. The two `--timeout` values you're referencing are not connected, which is probably leading to confusion here:

- `--timeout` for `bcbio_nextgen.py` specifies how long the main bcbio process should wait for the controller and engines for IPython to launch.
- `--timeout` in the LSF engine file specifies when the engine should exit if it can't contact the controller.

Practically, the controller for IPython should launch first, followed by the engines, so you shouldn't have to worry about the later parameter.

For debugging, I'm not entirely sure what error you're seeing initially. Would you be able to provide more details about that and we might be able to help identify what is going wrong? Thanks for the help debugging.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for your quick response and sorry for not giving details about the error.

Here is the error when submitted jobs went to PENDING state for more than 15minutes. bcbio_nextgen.py launches the script and jobs also submitted to LSF scheduler. 
Somehow I deleted today's error. Since I have free nodes I cannot generate the same error again. Here is the same error which generated earlier.

**2018-11-05 14:50:46.236 [IPClusterStop] Stopping cluster [pid=23560] with [signal=2]
Traceback (most recent call last):
  File "bcbio-v1.0.8/bin/bcbio_nextgen.py", line 242, in <module>
    main(**kwargs)
  File "bcbio-v1.0.8/bin/bcbio_nextgen.py", line 47, in main
    run_main(**kwargs)
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 53, in run_main
    fc_dir, run_info_yaml)
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 123, in variant2pipeline
    multiplier=alignprep.parallel_multiplier(samples)) as run_parallel:
  File "bcbio-v1.0.8/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 55, in start
    with ipython.create(parallel, dirs, config) as view:
  File "bcbio-v1.0.8/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 1146, in cluster_view
    wait_for_all_engines=wait_for_all_engines)
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 1101, in __init__
    """)
IOError:** 

And I tried to use --timeout option with bcbio_nextgen.py run, it is giving same error again and not sure which file to check whether it is picking up the --timeout value. Please let me know which file to check?

And also I checked with our LSF admin, in general PENDING jobs will not be terminated by cluster on its own. Jobs will be in pending state only till they get free nodes.

Could you please help me what options do I include to bcbio_nextgen.py in order to make jobs wait till they get free nodes.

Thanks In Advance
Fazulur Rehaman

**Comment by Fazulur** [comment]
Hi Roryk,

Thanks for your quick response.

Yes, I had submited bcbio_nextgen.py command as lsf job. It is communicating with execute nodes without issues. 

Here is the command

echo "bcbio_nextgen.py test.yaml -t ipython -s lsf -q normal --timeout 20000 -n 64" | bsub -P test -J bcbio-test -e bcbio-test.e -o bcbio-test.o 

Could you please help me how can I proceed further.

**Comment by roryk** [comment]
Thanks-- could you try submitting like you did before and post up the error log from today so we can see what the error looks like? A lot of times the errors look the same, but they are caused by something different so it would be helpful to have it with the --timeout command set properly to look at.

**Comment by roryk** [comment]
Awesome! Glad that that worked.
