### ISSUE TITLE
Conda packages bcbio-nextgen and eagle in conflict

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2581]
Hello,

Is there some way of installing both bcbio-nextgen and eagle from conda, simultaneously? The packages appear to be in conflict:

```
conda install --yes -c conda-forge -c bioconda bcbio-nextgen gatk4 ensembl-vep eagle
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - bcbio-nextgen
  - eagle
Use "conda info <package>" to see the dependencies for each package.
```

Running `conda info <package>` doesn't produce any additional info for neither `eagle`, nor `bcbio-nextgen`.

**Comment by amizeranschi** [comment]
Note: when having installed bcbio-nextgen and bcbio-vm, and trying to additionally install the eagle package from bioconda, the following happens:

```
conda install -c bioconda eagle
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - azure-mgmt-resource
  - eagle
Use "conda info <package>" to see the dependencies for each package.
```
Again, `conda info <package>` doesn't provide any additional info for any of the conflicting packages.

**Comment by amizeranschi** [comment]
Thanks for the advice. I created a new Conda environment and tried installing some extra tools, but it still runs into an `UnsatisfiableError`:

```
bash Miniconda2-latest-Linux-x86_64.sh -b -p ${bcbio_path}/extra
[...]
mv ${bcbio_path}/extra/bin/conda ${bcbio_path}/extra/bin/extra_conda
${bcbio_path}/extra/bin/extra_conda install --yes -c conda-forge -c bioconda gatk4 ensembl-vep eagle
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - eagle
  - enum34
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by chapmanb** [comment]
It looks like eagle is a python3 only package so will need a separate environment with python3 installed (`conda create --name eagle python=3 eagle`) or a python3 version of Miniconda. This might restrict the other packages you can install alongside it since some will be python2 only. Hope this helps get it working for you.

**Comment by amizeranschi** [comment]
Thanks, the python3 requirement was the problem indeed.
