### ISSUE TITLE
Adding X to sampleID name starts with zero

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2583]
Dear Bcbio team,

I upgraded bcbio and ran variant calling pipeline and my sampleId's starts with '0' Eg: 002018. bcbio adding "X" to sampleId (X002018). I haven't observed this with earlier version.

Could you please suggest me how can I get rid of this leading "X" to sampeId.

Thanks In Advance
Fazulur Rehaman

**Comment by roryk** [comment]
Hi @Fazulur,

This is intended behavior-- the reason is that having a sample starting with a number can break any R-based downstream tool folks are using, and people often use R tools, so we fix that up front.

**Comment by roryk** [comment]
Hi Fazulur,

This is intended behavior-- bcbio adds an X in front of names starting with a number because it breaks a lot of tools that use R.

**Comment by Fazulur** [comment]
Hi Roryk,

Thanks a lot for your confirmation. 

Thanks & Regards
Fazulur Rehaman

**Comment by roryk** [comment]
No problem!
