### ISSUE TITLE
mutect2  output vcf gives wrong AF for tumor normal pair sample

### ISSUE THREAD

**Issue by dormeight** [bcbio/bcbio-nextgen#2586]
Hi， I'm using bcbio version 1.1.1a0 and gatk3.8  for tumor/normal pair sequencing data, the final vcf file gives some records with somatic AF is one, when checked in the IGV, it is apparently wrong. I can't figure out where is the problem.  Here is some example:
```
chr4    169612461       .       GTT     G       .       PASS    DP=193;ECNT=1;FS=0;HCNT=2;MAX_ED=.;MIN_ED=.;MQ=60;MQ0=0;NLOD=9.09;TLOD=16.27  GT:AD:AF:DP      0/1:51,16:1:67  0/0:84,1:1:85
chr5    161494990       .       GAA     G       .       PASS    ClippingRankSum=0;DP=306;ECNT=1;FS=0;HCNT=4;MAX_ED=.;MIN_ED=.;MQ=60;MQ0=0;MQRankSum=0;NLOD=12.87;ReadPosRankSum=0.498;TLOD=24.67       GT:AD:AF:DP     0/1:62,37:0.952:99      0/0:130,2:1:132
chr7    33217071        .       CTT     C       .       PASS    DP=175;ECNT=1;FS=0;HCNT=1;MAX_ED=.;MIN_ED=.;MQ=60;MQ0=0;NLOD=3.15;TLOD=15.56  GT:AD:AF:DP      0/1:63,25:1:88  0/0:72,3:1:75
```
Can anyone tell me whether these outputs normal or not? Many thanks!

**Comment by chapmanb** [comment]
Thanks for the report and detailed examples. I agree that the AF calculations on the first and third example don't look correct. My guess is that there is some type of filtering happening prior to calculating AFs that is not reflected in the raw depth numbers, but I'm not familiar enough with the MuTect2 algorithms to know the underlying cause.

Practically, you could raise an issue with the GATK team to try and get more clarity, although I suspect they will suggest moving to GATK4 and the updated and improved version of MuTect2. For your analysis now, you might want to recalculate AF from the AD field. Hope this helps.

**Comment by dormeight** [comment]
I rerun the analysis with gatk4, the AF field looks fine for all samples. Thank you！
