### ISSUE TITLE
bcftools filter error after upgrade with gVCF

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2588]
Dear Bcbio team,

We upgraded bcbio recently and ran gatk-variant pipeline with tools_on: [gvcf] and tools_off: [vqsr].
Pipeline is giving error at bcftools filter.
**[filter.c:2278 filters_init1] Error: the tag "MQ" is not defined in the VCF header**

SInce we are generating gVCF where we have homozygous reference calls, MQ will be missing in header. 

Eventhough it is generating cram file, in logs I had seen archive_to_cram error below

**[E::bgzf_read] Read block operation failed with error 2 after 55 of 186 bytes
[main_samview] truncated file.
' returned non-zero exit status 1**

Please help me to resolve this errors.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the report and sorry about the issues. Would you be able to share the configuration you're using that's causing issues? What is your goal with this gVCF run, joint calling or just generating raw gVCFs? Additionally, I'm trying to understand if you're using GATK3 or GATK4 for the variant calling. We do skip MQ in some gVCF cases already (https://github.com/bcbio/bcbio-nextgen/blob/d2810ad49ce00c155f87e151c3c8ca1b28806436/bcbio/variation/vfilter.py#L213) but must be missing what is happening with you.

For `archive: cram` we try to 8-bin compress CRAM files with BamSqueeze but if this fails just fall back to standard CRAM without the quality compression (https://github.com/bcbio/bcbio-nextgen/blob/d2810ad49ce00c155f87e151c3c8ca1b28806436/bcbio/variation/vfilter.py#L213) which is likely what you're seeing in the logs. We'd like to have more robust binning here but I don't know of any existing tools to swap in. You can see the larger discussion here: https://github.com/bcbio/bcbio-nextgen/issues/2531

Thanks for the help debugging and hope this helps.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for your quick response.
I am generating raw gVCF files using gatk4.
Here is the config yaml which i used.

**details:
- algorithm:
    aligner: bwa
    recalibrate: gatk
    tools_on: [gvcf]
    tools_off: [vqsr]
    variantcaller: [gatk-haplotype]
  analysis: variant2
  description: ‘test’
  files:
  - test_R1.fastq.gz
  - test_R2.fastq.gz
  genome_build: GRCh37
fc_name: ‘test’
resources:
  default:
    cores: 8
    jvm_opts: [-Xms5g, -Xmx15g]
upload:
  dir: ../final**

Please correct me if I am missing anything in configuration.

And also thanks for sharing me discussion link on CRAM support. I will go through it.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the example, this was really helpful to reproduce the problem. I pushed a fix to the latest development which should correctly skip running this filter when dealing with raw gVCF files. If you update and re-run in place it should hopefully work cleanly for you now. Thanks again for the report and help debugging.

**Comment by Fazulur** [comment]
Dear Brad,

As per your mail, I upgraded bcbio today and still I am facing "MQ" annotation issue with gVCF.

Here is the upgrade command I used

bcbio_nextgen.py upgrade –u stable  —cores [number of cores] —tools —data  —cwldata —datatarget gemini —datatarget gnomad —datatarget dbnsfp —datatarget vep —datatarget battenberg —datatarget cadd --aligners bwa --aligners bowtie2 --aligners star –aligners hisat2 

Could you please correct me If I am missing anything.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for upgrading. This is only available in the development version, so doing:
```
bcbio_nextgen.py upgrade -u development
```
will get the updated version with the fix. 

As an aside, all of the other upgrade commands for data should be saved in the bcbio config so don't need to be specified on the command line each time. You can just add `--data` when you want a data upgrade.

Hope this gets it working for you.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for command. It's working now.

Thanks & Regards
Fazulur Rehaman
