### ISSUE TITLE
Update mosdepth version to 0.2.4

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2590]
Brad,

could you bump up the mosdepth version to 0.2.4? It contains some bugfixes.
https://github.com/brentp/mosdepth/releases/tag/v0.2.4

Thanks!

**Comment by chapmanb** [comment]
Ben;
Thanks for the suggestion, I updated the bioconda package so 0.2.4 is now available. I'd like to explore the new `--fast-mode` parameter for mosdepth input for CNV and coverage analysis as well. Thanks again.
