### ISSUE TITLE
Generating CWL with the minimal installation

### ISSUE THREAD

**Issue by TMiguelT** [bcbio/bcbio-nextgen#2592]
I want to use bcbio to generate some CWL that I will then submit to a Cromwell server. I don't want to install any biological data, any tools or anything like that, because I already have the data in the cloud.

However, the "automated" installation (which installs the `bcbio-nextgen-vm` package) pulls in about 50 conda packages:
```
appdirs
arvados-cwl-runner
arvados-python-client
avro-python2
azure
azure-common
azure-mgmt
azure-mgmt-common
azure-mgmt-compute
azure-mgmt-network
azure-mgmt-nspkg
azure-mgmt-resource
azure-mgmt-storage
azure-nspkg
azure-servicebus
azure-servicemanagement-legacy
azure-storage
backports.csv
bcbio-nextgen-vm
bd2k-python-lib
cachecontrol
cgcloud-lib
ciso8601
cromwell
cwl2wdl
cwltest
cwltool
dill
docker-py
docker-pycreds
docutils
dx-cwl
dxpy
findutils
fusepy
future
galaxy-lib
gcs-oauth2-boto-plugin
gettext
google-api-python-client
google-cloud-sdk
html5lib
httplib2
isodate
junit-xml
keepalive
libmagic
lockfile
mistune
nodejs
oauth2client
packaging
pyasn1-modules
pycurl
pyhocon
python-gflags
python-magic
rabix-bunny
rdflib
rdflib-jsonld
retry_decorator
rsa
ruamel.ordereddict
ruamel.yaml
schema-salad
sevenbridges-python
shellescape
socksipy-branch
sparqlwrapper
ssl_match_hostname
synapseclient
toil
typing
uritemplate
webencodings
websocket-client
ws4py
xattr
```

I really truly don't want all this installed on my tiny laptop, since I'll never use it. Is there any way to just generate CWL without all this stuff?

**Comment by chapmanb** [comment]
Thanks much for starting this discussion. Unfortunately that's as minimal as the CWL generation gets currently. We haven't split out CWL generation from automation of CWL runs, so don't have an even more minimal installation. Several of those resources are used for referencing remote files, supporting CWL generation with inputs on Arvados, DNAnexus, GCP and AWS. The remainder are used for automating the setup and actual CWL runs.

Sorry to not have something smaller for local use but hope this will work reasonably well for your needs.

**Comment by TMiguelT** [comment]
So if there isn't a minimal way of generating CWL, what is contained in the CWL test repo? https://github.com/bcbio/test_bcbio_cwl

Is that usable by itself, or is that strictly for testing purposes?

**Comment by chapmanb** [comment]
Thanks for the follow up. The pre-generated CWL in the test repository is useful by iteself and could be run without bcbio-vm: you'd just need a CWL runner of your choice and Docker to pull in bcbio for doing the actual compute. The actual generation of the CWL in this repo happens with a bcbio-vm install, however, with the same dependencies in place.

I'm not entirely sure about your goals so not sure what best to suggent, but hope this helps some with the current status.

**Comment by TMiguelT** [comment]
Well, maybe that CWL is the best option for this use case then. I'm coming from the angle where I've used CWL a lot, and I'd rather use it directly than have to generate it using `bcbio-vm`. As I mentioned, I want to run it using Cromwell, so I'd rather skip over the bcbio-specific metadata and config.

**Comment by chapmanb** [comment]
Sounds great. You don't need bcbio-vm at all if you already know what you're doing with CWL and the runners and just want to use bcbio generated CWL. The wrappers in bcbio handle generating the CWL itself and making running a bit easier by setting up configuration files and other inputs, but are fully optional if you already have experience with this. Hope those pre-generated CWLs work for you.

**Comment by TMiguelT** [comment]
Great, thanks!
