### ISSUE TITLE
Why is MAPQ>0 threshold not applied to coverage histogram

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2598]
Brad,

When I compared the various coverage files generated by mosdepth I noticed that not all of them are generated with the same options. The coverage distribution histograms `*-coverage.mosdepth.region.dist.txt` are generated without the `mapq_arg` which means that also reads with MAPQ=0 are considered for coverage calculation. 
https://github.com/bcbio/bcbio-nextgen/blame/689fa167cd1a94b75905b30dff8462bd0cd69122/bcbio/variation/coverage.py#L225
Is there a reason for this? From my point of view it would be better, if all coverage files would be generated considering the same data.

**Comment by chapmanb** [comment]
Ben;
Thanks for this discussion. I believe we were wanting to be more inclusive with the regional coverage since that gets used downstream by CNV callers, and keeping the reporting consistent with what we did before. This is consistent with how we'd been doing it previously (before it was merged into the current function):

https://github.com/bcbio/bcbio-nextgen/blame/2d91bfac6899dbe1335852250063781910d56674/bcbio/variation/coverage.py#L270

@vladsaveliev do you remember our motivation here? I'm open to trying to make this consistent but also concerned about changing expected behavior that's been in place for a while.

**Comment by vladsaveliev** [comment]
Brad,

I think we wanted to report usable coverage, i.e. those reads that are used for variant calling. Thus excluding secondary alignments, duplicates, etc.

But I’m happy with any change here. Consistency is good.

Vlad

**Comment by gabeng** [comment]
Brad,
I was not aware that these files are used for CNV calling. If that is the case, it probably makes sense to include MAPQ=0 reads. 
However, I suggest that these intermediate CNV files should not be stored in the QC subdirectory together with SNV related files, at least not without context information or specific naming.

**Comment by chapmanb** [comment]
Ben and Vlad;
Thanks for this, it sounds like sticking with what we have for CNV depth inputs makes sense but we need some cleanup in terms of the presentation. Ben, I'm not entirely sure which files are causing the issue; would you be able to enumerate a specific example where the file is providing confusing QC feedback? That would help figure out the best way to clean up and improve this to avoid confusion. Thanks again.

**Comment by gabeng** [comment]
Brad,
maybe I am just confused and some clarification will do. 

I set `per-base` coverage in the config yaml. Therefore I have two files in the sample directory that represent information regarding coverage.
```
NA12878N3_S16-callable.bed
NA12878N3_S16-depth-per-base.bed.gz 
```
The `depth-per-base` file was generated not counting `MAPQ=0` reads (`-Q 1`) , so much I know. How about the `callable.bed`? 

Then, for every sample, there is a `qc/coverage` subdirectory which contains these files:
```
NA12878_S1-coverage.mosdepth.region.dist.txt
NA12878_S1-coverage.regions.bed.gz
NA12878_S1-coverage.thresholds.bed.gz
```
The `mosdepth.region.dist.txt` and the `regions.bed.gz` were created counting `MAPQ=0` reads. How about the `thresholds.bed.gz`?

Then, there are the `multiqc` statistics. If I read the log files correctly, they are generated using `hts_nim_tools count-reads` without the `-Q` flag, therfore counting `MAPQ=0` reads. 

For purposes of QC I, personally, disregard reads with `MAPQ=0`. It looks like I should be using the `depth-per-base-bed.gz` file only and derive all other values from that. Is that correct?

**Comment by chapmanb** [comment]
Ben;
Thanks for the examples. Definitely understood this is confusing; it's evolved over time so we've just been trying to keep previous behavior while adding new functionality.

`-Q 1` gets applied if a mosdepth call has either per-base output (as you asked for) or if you're calculating coverage blocks (quantize, in mosdepth terms). If you're not, than it uses the `-Q 0` output.

So for the first two examples, they're both consistently `-Q 1` and for the coverage estimation in QC in your second, it uses `-Q 0` for everything. It's one mosdepth call creating all of the files simultaneously.

So you're right, if you want to avoids 0 mapping quality reads entirely for QC, using the per-base files is the right way to go.

Hope this gives you what you need for consistent QC and let us know if there is anything we can tweak.

**Comment by gabeng** [comment]
Brad,
thanks for the clarification. It's good to have this documented here. 
I would suggest to use the `-Q 1` option for the files in `qc/coverage` as well, but I do not know, if this has impact on some other process.
