### ISSUE TITLE
Bump hg38 VEP version to 94

### ISSUE THREAD

**Issue by pfpjs** [bcbio/bcbio-nextgen#2601]
Hi @chapmanb, @matthdsm 

The following line needs to be changed to `ensembl: homo_sapiens_merged_vep_94_GRCh38`, otherwise hg38 runs will fail when VEP annotations are enabled:
https://github.com/bcbio/bcbio-nextgen/blob/cf727ffa48937bd9d1063dfe320fdb6b304e5b8b/config/genomes/hg38-resources.yaml#L6

Thank you in advance!

In a somewhat related matter, any tips on how to have a local `bcbio` repo I can tweak, test, and then maybe submit a PR? Currently, any change I make to my local installation is thrown away on every `bcbio` upgrade. Is there a development guide I may have missed?

Thank you again!
-- Paulo

**Comment by chapmanb** [comment]
Paulo;
Thanks much for the fix on the VEP versions in resources.

For development, we suggest making a fork and installing into either a separate non-tool environment or directly into your test environment with `bcbio_python setup.py install`:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/code.html#development-infrastructure

Since the changes are outside of the installation, this avoids overwriting your updates so you can apply them after an update.

Please let us know if we can improve the documentation or help with any development issues. Thanks again.

**Comment by pfpjs** [comment]
Thank you @chapmanb for accepting my PR, and for the pointer to the development docs, somehow I had totally missed that!

Cheers!

**Comment by pfpjs** [comment]
Hi @chapmanb,

I'm having some trouble getting my local changes propagate to my development bcbio installation. Specifically:

1. I made some changes/tweaks to the file `bcbio-nextgen/config/vcfanno/hg38-gnomad_genome.conf` in my forked repo (some variants in the gnomad VCF have more than one value, I need to change `ops` from `self` to `first` or `vcf2db` will crash with a SQAlchemy error).
2. I deleted the bcbio python eggs from my dev installation `/path/to/dev/bcbio/anaconda/lib/python2.7/site-packages/bcbio*` and reinstalled from my local forked repo with `bcbio_python setup.py install`, all OK.
3. Checking my local dev bcbio installation, the file `/path/to/dev/bcbio/genomes/Hsapiens/hg38/config/vcfanno/gnomad_genome.conf` is left unchanged.

Is there something I may have missed?

Thank you for your help!
-- Paulo

**Comment by chapmanb** [comment]
Paulo;
Thanks for the question and sorry for the confusion. `setup.py` only installs the python code, so won't change the data files. There isn't an automated way to do this, so copying the updated file into your install would be the best path. Practically, could we include your fixes into bcbio itself so they get pulled for everyone? This sounds like a good general fix others would benefit from as well. Thanks again.

**Comment by pfpjs** [comment]
Thank you the usual swift answer @chapmanb! I will test these changes first and if all is OK, I'll submit a pull request. Slowly setting up my development environment here (in a diagnostics lab) so I can contribute to bcbio more easily and frequently. Thank you!
