### ISSUE TITLE
Can't find bcbio-prioritize in quay.io/bcbio/bcbio-vc running CWL workflow

### ISSUE THREAD

**Issue by tmooney** [bcbio/bcbio-nextgen#2609]
I made a fresh install of bcbio last week to generate an updated CWL.  The workflow got pretty far along when running with cromwell in `quay.io/bcbio/bcbio-vc@sha256:244ad9ee02ec55612c5462adc859fabc2bed276cd05117fe40df80204ca5e534`, but all of my twelve runs have crashed in the summarize_sv.cwl step.

The backtrace points to the call on 115 here:
https://github.com/bcbio/bcbio-nextgen/blob/8ca1625f479e9ceb9560d19c5b878268cdf29342/bcbio/structural/prioritize.py#L113-L115

The error message:
```
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/usr/local/share/bcbio-nextgen/anaconda/bin:$PATH &&  bcbio-prioritize -Xms1000m -Xmx3072m known -i /cromwell-executions/main-50729-template.cwl/663a8e0e-94ab-4dc9-9439-5086a30d5884/call-summarize_sv/inputs/-274831346/38838-svs-smoove.genotyped-duphold-filter-effects.vcf.gz -o /cromwell-executions/main-50729-template.cwl/663a8e0e-94ab-4dc9-9439-5086a30d5884/call-summarize_sv/execution/bcbiotx/tmpuZj9ZL/38838-lumpy-prioritize.vcf.gz  -k /cromwell-executions/main-50729-template.cwl/663a8e0e-94ab-4dc9-9439-5086a30d5884/call-summarize_sv/inputs/1608558071/civic-2018-12-27.bed.gz
/bin/bash: bcbio-prioritize: command not found
```
I didn't see this command inside the image, either, so I'm hoping it's something simple like #2516 was.

**Comment by chapmanb** [comment]
Thomas;
Thank you for this report and apologies about the issue. I hadn't included bcbio-prioritize in the Docker container after adding support for this during SV calling, and just created a new container that includes it and should work cleanly. If you re-run with the updated image, I hope things will work as expected and you can finish your run.

**Comment by tmooney** [comment]
That did the trick; thank you for the swift fix!
