### ISSUE TITLE
BAM index file naming

### ISSUE THREAD

**Issue by mjafin** [bcbio/bcbio-nextgen#261]
It looks like the working directories contain `.bam.bai` files but in the final output there are `-ready.bam` and `-ready.bai` files. I know some programs recognise either way, and it's a small thing, but what are your thoughts on also producing the `.bam.bai` file in the final directory?

**Comment by sarmadym** [comment]
I wanted to bump this issue up. Example is "s134-tumor-ready-bam.bai" where it should be "s134-tumor-ready.bam.bai". This is in the final directory.

**Comment by chapmanb** [comment]
Thank you for the report and sorry about the issue. This was a bug in naming I introduced when adding support for CNVkit output files. I pushed a fix to the latest development so if you update with:
```
bcbio_nextgen.py upgrade -u development
```
it should now copy over the files with the correct naming. Thanks again for letting us know about the problem.
