### ISSUE TITLE
Is hg38 same to GRCh38 in bcbio?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2610]
Hi, I notice that bcbio supports hg38 and hg19/GRCh37. I also find that hg38 uses the variation annotation of GRCh38 version, such as VEP and snpeff annotations. But GRCh38 can not be installed by bcbio install program. I wonder if bcbio does not distinguish hg38 and GRCh38 or not?

**Comment by chapmanb** [comment]
Thanks for the question. hg38 and GRCh38 refer to the same genome build with the same coordinates and contigs. The only difference is the chromosome naming: either chr1, chr2, chr3... or 1, 2, 3... style. bcbio only supports for the former chr-prefixed naming style, which we're calling hg38, and we convert all resources we use to match this. We supported two styles for build 37 and want to simplify and focus on more science and less contig naming with build 38. Hope this helps.
