### ISSUE TITLE
NameError: global name 'bamprep' is not defined

### ISSUE THREAD

**Issue by tkoomar** [bcbio/bcbio-nextgen#2611]
Running joint variant calling with platypus threw the following error from `bcbio/variation/joint.py`:
```
File "/Dedicated/jmichaelson-wdata/bcbio-dna/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 229, in _square_batch_bcbio_variation ["-c", cores, "-r", bamprep.region_to_gatk(region)]
NameError: global name 'bamprep' is not defined
```
[Full error log is at this gist](https://gist.github.com/tkoomar/996b9b290f78102edc2abf924e2c14b8)

**Background**
Initially, I  ran into the gatk-framework problem referenced by [this issue on  bcbio-nextgen-vm](https://github.com/bcbio/bcbio-nextgen-vm/issues/171#issue-375324058). 

I ran a `bcbio_nextgen.py upgrade -u stable --tools` since the error seemed to have to do with using an older version of bcbio-variation-recall, but that resulted in the new error. 

In an interactive python session, there is no apparent reason for the error, as `bamprep` seems to be loaded properly from `bcbio.variation`: 
```
>>> from bcbio.variation import bamprep
>>> bamprep
<module 'bcbio.variation.bamprep' from '/Dedicated/jmichaelson-wdata/bcbio-dna/anaconda/lib/python2.7/site-packages/bcbio/variation/bamprep.pyc'>
```

**Comment by chapmanb** [comment]
Tanner;
If you have a large enough sample size to want joint calling I'd generally skip ensemble calling and use a single approach. You can get some marginal gains in sensitivity with multiple callers but we find it generally not worth all of the extra compute and pipeline management. If you find things a GATK only approach misses definitely happy to investigate and discuss more, we're always looking to improve recommendations. Thanks again for this discussion.
