### ISSUE TITLE
ERROR_CHROMOSOME_NOT_FOUND error by snpeff

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2612]
Hi, I am running the variant pipeline to annotate the variant detected by freebayes, gatk and varscan. My yaml file is as below:
```
> upload:
>   dir: ../final
> details:
>   - files: [../input/NA12878_1.fastq.gz, ../input/NA12878_2.fastq.gz]
>     description: NA12878
>     metadata:
>       batch: ceph
>       sex: female
>     analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       #align_split_size: 5000000
>       mark_duplicates: true
>       recalibrate: gatk
>       realign: false
>       effects: snpeff
>       variantcaller: [freebayes, gatk-haplotype, varscan]
>       ensemble:
>         numpass: 2
>         use_filtered: false
>       #remove_lcr: true
>       #validate: giab-NA12878/truth_small_variants.vcf.gz
>       #validate_regions: giab-NA12878/truth_regions.bed
> 
```
We checked the output file in the ensemble diretory and found that all annotations by snpeff included the ERROR_CHROMOSOME_NOT_FOUND entries. I known this error means the chromosome names do not match between input vcf and snpeff files. I just want to known how to fix this problem? Thanks a lot.

**Comment by chapmanb** [comment]
Thanks much for the report and apologies about the issue. Would you be able to share one of the problematic snpEff lines from the VCF? For hg38 snpEff can report this on some of the supplemental contigs, but it's definitely unexpected that you'd see it on every line with the standard chromosomes. My only guess is that something is problematic about the snpEff database install. If you look in the install:
```
ls -lh bcbio/genomes/Hsapiens/hg38/snpeff/GRCh38*`
```
are the input files correctly available? Thanks for the help debugging and hope this helps.

**Comment by hliu2016** [comment]
@chapmanb 
Thanks very much. A few lines of the snpEff annotated vcf file are list as below:

> chrM    1438    rs2001030       A       G       435262.0        PASS    AB=0;ABP=0;AC=3;AF=1;AN=3;AO=17509;CALLERS=freebayes,gatk-haplotype,varscan;CIGAR=1X;DP=17521;DPB=17521;DPRA=0;EPP=350.134;EPPR=3.32051;GTI=0;LEN=1;MEANALT=2.33333;MQM=51.2147;MQMR=45.8571;NS=3;NUMALT=1;ODDS=7180.76;PAIRED=0.979211;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=522401;QR=94;RO=7;RPL=9088;RPP=58.1856;RPPR=10.7656;RPR=8421;RUN=1;SAF=2814;SAP=17509.5;SAR=14695;SRF=2;SRP=5.80219;SRR=5;TYPE=snp;technology.illumina=1;ANN=G||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND    GT:AD:AO:DP:GQ:PL:QA:QR:RO      1:2,7966:7966:7970:99:207164,0:237747:12:2      1:0,23:23:23:99:421,0:495:0:0   1:5,9520:9520:9528:99:247304,0:284159:82:5
> chrM    16278   rs41458645      C       T       435.0   PASS    AB=0;ABP=0;AC=1;AF=0.333333;AN=3;AO=23;CALLERS=freebayes,gatk-haplotype;CIGAR=1X;DP=71;DPB=71;DPRA=0.958333;EPP=24.253;EPPR=11.8771;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=58.6667;NS=3;NUMALT=1;ODDS=67.0455;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=660;QR=1290;RO=48;RPL=19;RPP=24.253;RPPR=11.8771;RPR=4;RUN=1;SAF=23;SAP=52.9542;SAR=0;SRF=48;SRP=107.241;SRR=0;TYPE=snp;technology.illumina=1;ANN=T||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND     GT:AD:AO:DP:GQ:PL:QA:QR:RO      0:13,0:0:13:99:0,290:0:320:13   1:0,23:23:23:99:597,0:660:0:0   0:35,0:0:35:99:0,874:0:970:35
> chrM    16519   rs3937033       T       C       44364.2 PASS    AB=0;ABP=0;AC=1;AF=0.333333;AN=3;AO=2777;CALLERS=freebayes,gatk-haplotype;CIGAR=1X;DP=8366;DPB=8366;DPRA=0;EPP=5741.48;EPPR=11671.5;GTI=0;LEN=1;MEANALT=3;MQM=49.4843;MQMR=52.3684;NS=3;NUMALT=1;ODDS=10145.7;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=82232;QR=165066;RO=5556;RPL=34;RPP=5741.48;RPPR=11680;RPR=2743;RUN=1;SAF=2777;SAP=6033.19;SAR=0;SRF=5553;SRP=12041.7;SRR=3;TYPE=snp;technology.illumina=1;ANN=C||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND    GT:AD:AO:DP:GQ:PL:QA:QR:RO      0:2958,11:11:2985:4:0,74180:126:88160:2958      1:1,2759:2759:2764:99:67981,0:82010:20:1        0:2597,7:7:2617:4:0,64093:96:76886:2597
> 

Also, we checked a few lines in the vcf file outputted by gatk-haplotype, and found that the chromosome name has chr prefix.

> 
> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878 NA12891 NA12892
> chrM    152     .       T       C       97886.87        .       AC=2;AF=0.667;AN=3;BaseQRankSum=-1.467;ClippingRankSum=1.815;DP=4996;FS=0.000;MLEAC=2;MLEAF=0.667;MQ=60.00;MQ0=0;MQRankSum=0.000;QD=34.33;ReadPosRankSum=0.576;SOR=0.723        GT:AD:DP:GQ:MMQ:PL      1:0,1411:1411:99:60:48414,0     0:2135,2:2137:99:60:0,73411     1:0,1440:1440:99:60:49505,0
> chrM    195     .       T       C       74126.87        .       AC=1;AF=0.333;AN=3;BaseQRankSum=-0.813;ClippingRankSum=-0.056;DP=5006;FS=0.000;MLEAC=1;MLEAF=0.333;MQ=60.00;MQ0=0;MQRankSum=0.000;QD=34.37;ReadPosRankSum=2.437;SOR=0.700       GT:AD:DP:GQ:MMQ:PL      0:1344,0:1344:99:0:0,46274      1:1,2156:2157:99:60:74159,0     0:1494,0:1494:99:0:0,51660
> chrM    263     .       A       G       190064.64       .       AC=3;AF=1.00;AN=3;DP=4526;FS=0.000;MLEAC=3;MLEAF=1.00;MQ=60.00;MQ0=0;QD=27.92;SOR=0.773 GT:AD:DP:GQ:MMQ:PL      1:0,1289:1289:99:60:51939,0     1:0,1855:1855:99:60:83190,0     1:0,1381:1381:99:60:54963,0
> chrM    302     .       A       AC      99068.60        .       AC=3;AF=1.00;AN=3;BaseQRankSum=0.645;ClippingRankSum=0.117;DP=4142;FS=0.000;MLEAC=3;MLEAF=1.00;MQ=60.00;MQ0=0;MQRankSum=-0.080;QD=27.41;ReadPosRankSum=0.907;SOR=0.857  GT:AD:DP:GQ:MMQ:PL      1:10,1127:1137:99:60:33377,0    1:22,1374:1396:99:60:33419,0    1:5,1076:1081:99:60:32309,0
> chrM    310     .       T       TC      180441.60       .       AC=3;AF=1.00;AN=3;DP=3919;FS=0.000;MLEAC=3;MLEAF=1.00;MQ=60.00;MQ0=0;QD=29.14;SOR=1.663 GT:AD:DP:GQ:MMQ:PL      1:0,1220:1220:99:60:55984,0     1:0,1523:1523:99:60:70374,0     1:0,1175:1175:99:60:54120,0
> chrM    513     .       G       GCA     67012.83        .       AC=1;AF=0.333;AN=3;BaseQRankSum=-1.522;ClippingRankSum=-3.522;DP=4998;FS=0.000;MLEAC=1;MLEAF=0.333;MQ=60.00;MQ0=0;MQRankSum=0.000;QD=27.44;ReadPosRankSum=-0.096;SOR=0.744      GT:AD:DP:GQ:MMQ:PL      0:1204,1:1205:99:60:0,46674     1:18,1768:1786:99:60:67054,0    0:1337,2:1339:99:60:0,51653
> chrM    606     .       A       G       70157.87        .       AC=1;AF=0.333;AN=3;BaseQRankSum=0.356;ClippingRankSum=-0.549;DP=4941;FS=1.139;MLEAC=1;MLEAF=0.333;MQ=59.61;MQ0=0;MQRankSum=-1.384;QD=34.37;ReadPosRankSum=0.497;SOR=0.576       GT:AD:DP:GQ:MMQ:PL      0:1302,2:1304:99:60:0,44823     1:0,2041:2041:99:60:70190,0     0:1579,0:1579:99:0:0,54488
> chrM    750     .       A       G       171524.64       .       AC=3;AF=1.00;AN=3;BaseQRankSum=10.877;ClippingRankSum=-0.288;DP=4998;FS=0.000;MLEAC=3;MLEAF=1.00;MQ=58.99;MQ0=0;MQRankSum=-0.795;QD=34.33;ReadPosRankSum=0.205;SOR=0.755        GT:AD:DP:GQ:MMQ:PL      1:2,1443:1445:99:60:49620,0     1:1,2072:2073:99:60:71106,0     1:3,1476:1479:99:60:50826,0
> chrM    1438    .       A       G       170824.64       .       AC=2;AF=1.00;AN=2;DP=5008;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=51.92;MQ0=0;QD=34.11;SOR=2.561 GT:AD:DP:GQ:MMQ:PL      1:0,2687:2687:99:60:91807,0     .:.:.:.:0       1:0,2321:2321:99:60:79045,0
> chrM    16278   .       C       T       591.87  .       AC=1;AF=0.333;AN=3;BaseQRankSum=1.138;ClippingRankSum=-0.970;DP=48;FS=0.000;MLEAC=1;MLEAF=0.333;MQ=60.00;MQ0=0;MQRankSum=0.000;QD=32.88;ReadPosRankSum=0.761;SOR=0.319  GT:AD:DP:GQ:MMQ:PL      0:24,0:24:99:0:0,832    1:0,18:18:99:60:624,0   0:6,0:6:99:0:0,173
> chrM    16519   .       T       C       19067.87        .       AC=1;AF=0.333;AN=3;BaseQRankSum=1.718;ClippingRankSum=0.465;DP=1699;FS=0.000;MLEAC=1;MLEAF=0.333;MQ=55.61;MQ0=0;MQRankSum=-5.287;QD=34.29;ReadPosRankSum=-0.729;SOR=0.682       GT:AD:DP:GQ:MMQ:PL      0:502,1:503:99:60:0,17186       1:0,556:556:99:60:19100,0       0:633,3:636:99:60:0,21627
> 

The snpEff database is installed in the /bio/bcbio/genomes/Hsapiens/hg38/snpeff/GRCh38.86 fold, in which there are 745 files. What's is the problem?

**Comment by chapmanb** [comment]
Thanks for the examples. Are you only seeing this on the mitochondrial and other non-primary chromosomes? I believe these are not present in the snpEff database, so having them missing isn't an issue. snpEff does the chr, no chr prefix mapping so that's not a problem. If all your primary chromosomes have annotations then things should be working as expected. Hope this helps.

**Comment by snehkant** [comment]
Hi, I am running the SnpEff tool for annotating the variant file (.vcf) file. I am getting following errors in output file. please do suggest me how to fix this error.  i know will have to change the chromosome name but dont know how to chnge and in which file i should change.

CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1
NZ_ANIH01000001.1	64	.	G	A	83.0	.	DP=18;VDB=0.0305072;SGB=-0.651104;MQSB=0.600535;MQ0F=0;AC=1;AN=1;DP4=0,0,5,3;MQ=46;ANN=A||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND	GT:PL	1:113,0
NZ_ANIH01000001.1	493	.	A	T	225.0	.	DP=63;VDB=0.589032;SGB=-0.693147;MQSB=0.990906;MQ0F=0;AC=1;AN=1;DP4=0,0,22,39;MQ=59;ANN=T||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND	GT:PL	1:255,0
NZ_ANIH01000001.1	799	.	A	T	225.0	.	DP=46;VDB=0.141532;SGB=-0.693147;MQSB=0.675652;MQ0F=0;AC=1;AN=1;DP4=0,0,22,23;MQ=46;ANN=T||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND	GT:PL	1:255,0
NZ_ANIH01000001.1	859	.	T	C	225.0	.	DP=53;VDB=0.430053;SGB=-0.693147;MQSB=0.992528;MQ0F=0;AC=1;AN=1;DP4=0,0,25,26;MQ=41;ANN=C||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND	GT:PL	1:255,0
NZ_ANIH01000001.1	908	.	G	A	225.0	.	DP=54;VDB=0.615204;SGB=-0.693147;MQSB=0.746279;MQ0F=0;AC=1;AN=1;DP4=0,0,26,27;MQ=39;ANN=A||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND	GT:PL	1:255,0
NZ_ANIH01000001.1	974	.	G	A	225.0	.	DP=49;VDB=0.583597;SGB=-0.693147;MQSB=0.221226;MQ0F=0;AC=1;AN=1;DP4=0,0,23,22;MQ=38;ANN=A||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND	GT:PL	1:255,0
NZ_ANIH01000001.1	990	.	A	G	219.0	.	DP=49;VDB=0.330012;SGB=-0.693147;MQSB=0.0843414;MQ0F=0;AC=1;AN=1;DP4=0,0,23,24;MQ=39;ANN=G||MODIFIER|||||||||||||ERROR_CHROMOSOME_NOT_FOUND	GT:PL	1:249,0
