### ISSUE TITLE
How do I turn on oncofuse in the configuration file?

### ISSUE THREAD

**Issue by maxabruzzi** [bcbio/bcbio-nextgen#2615]
Dear support team,

I used "fusion_mode: ture" under the algorithm section to turn on the fusion detection and had an exception handling message "``fusion_mode`` is deprecated in favor of turning on callers with ``fusion_caller``. It will run pizzly and oncofuse for now, but will eventually have support dropped."
So I replaced the fusion_mold line with "fusion_caller: oncofuse" in the algorithm section but it seemed like the pipeline ignored it and did not do anything about calling pizzly and oncofuse. So I'm not sure if I used the the fusion_caller parameter properly. Can you please advise? 

BTW, it seems there are a lot of parameters available for the pipeline configuration, but the documentation does not seem to have had a comprehensive description. Where would be a good place to start to get to know all of them? Thanks a lot!

Max

**Comment by roryk** [comment]
Hi Max, sorry for the problems. The readthedocs should have the list of the configuration variables: https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html let me know if you spot any that are missing.

Which genome build were you trying to run oncofuse on?

**Comment by maxabruzzi** [comment]
Hi Rory, thanks for your reply! I'm using GRCh37. The following is my configuration file:

details:
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: read_through
    fusion_caller: oncofuse
    #fusion_mode: True
    transcriptome_align: True
    expression_caller: salmon
  analysis: RNA-seq
  description: K00350R
  files:
  - /home/xix137/bcbioRuns/MCC-18C/RNA/input/18SEQ16384_1R_T_S_C_RS_T_1.fastq.gz
  - /home/xix137/bcbioRuns/MCC-18C/RNA/input/18SEQ16384_1R_T_S_C_RS_T_2.fastq.gz
  genome_build: GRCh37
fc_name: K00350R
metadata:
  phenotype: tumor
  tissue: EPI
upload:
  dir: ../final

The fusion_mode still works, but the tissue type (EPI) cannot be passed to oncofuse, it runs with the default AVG. If I comment out the fusion_mode and put fusion_caller in place, oncofuse would not be called. 

Max

**Comment by roryk** [comment]
Hi Max,

Sorry for being slow about getting back to you. I can't reproduce these issues-- it looks like EPI gets passed on for me and it works both with `fusion_mode: True` and `fusion_caller: oncofuse`. Could you post your input YAML file so I can look at it; the formatting kind of got destroyed here.

**Comment by maxabruzzi** [comment]
Hi Rory, 

Thanks a lot for looking into this! It's also likely that I've done something wrong that I did not realized. Sorry about it! The YAML file is attached. I'm using bcbio1.1.2. Not sure if it is the latest. 

Max
[oncofuse.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/2751041/oncofuse.yaml.txt)

**Comment by roryk** [comment]
Gotcha, I see the issue-- the metadata is outside of the details block, so it isn't applying to any sample. I attached a fixed version which shows where it should go.

[oncofuse.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/2751049/oncofuse.yaml.txt)

**Comment by roryk** [comment]
I'm like 95% sure this should fix it, feel free to reopen the issue if it doesn't. Thanks for the followup!

**Comment by maxabruzzi** [comment]
Great catch! Thank you so much!
So the way I put fusion_caller should actually do, right?

**Comment by roryk** [comment]
Yup, it should run oncofuse.
