### ISSUE TITLE
Null values instead of numeric values in multiqc_data_final.json

### ISSUE THREAD

**Issue by roland-ewald** [bcbio/bcbio-nextgen#2616]
[A recent change to `qc/multiqc.py`'s `_work_path_to_rel_final_path`](https://github.com/limbus-medtec/bcbio-nextgen/commit/ed8ccdb6a9a49524076a210ff7b165623a32d436#diff-7e97be75fbfe2fe0ba2f56111d713646R190) makes it return `None` whenever `path` is not a string, which means that [`utils.walk_data` invocations walking over the `multiqc` JSON data](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/qc/multiqc.py#L148) will replace all numeric values by `None`.

**Comment by chapmanb** [comment]
Fixed in #2617
