### ISSUE TITLE
bcbio errors with bwa mem

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#2622]
Hi Brad,

I am trying to do tumor normal analysis and below is the error. Can you please help

/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py in _do_run(cmd='set -o pipefail; unset JAVA_HOME && /mnt/bcbio/g...iotx/tmpN4t6rS/NG08-sort-80000001_160000000.bam -', checks=[<function check>, <function check>], log_stdout=False, env=None)
     98                 error_msg = " ".join(cmd) if not isinstance(cmd, basestring) else cmd
     99                 error_msg += "\n"
    100                 error_msg += "".join(debug_stdout)
    101                 s.communicate()
    102                 s.stdout.close()
--> 103                 raise subprocess.CalledProcessError(exitcode, error_msg)
        exitcode = 137
        error_msg = 'set -o pipefail; unset JAVA_HOME && /mnt/bcbio/g...otx/tmpN4t6rS/NG08-sort-80000001_160000000.bam -\n'
    104             else:
    105                 break
    106     s.communicate()
    107     s.stdout.close()

CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /mnt/bcbio/galaxy/../anaconda/bin/bwa mem   -c 250 -M -t 4  -R '@RG\tID:NG08\tPL:illumina\tPU:NG08\tSM:NG08' -v 1 /mnt/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(grabix grab /mnt/align_prep/NG-01_8_R1.fastq.gz 80000001 160000000) <(grabix grab /mnt/align_prep/NG-01_8_R2.fastq.gz 80000001 160000000)  | /mnt/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 4 -m 1G -O bam -T /mnt/bcbiotx/tmpN4t6rS/NG08-sort-80000001_160000000-sorttmp-namesort -o /mnt/bcbiotx/tmpN4t6rS/NG08-sort-80000001_160000000.bam -
/bin/bash: line 1: 14519 Killed                  /mnt/bcbio/galaxy/../anaconda/bin/bwa mem -c 250 -M -t 4 -R '@RG\tID:NG08\tPL:illumina\tPU:NG08\tSM:NG08' -v 1 /mnt/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(grabix grab /mnt/align_prep/NG-01_8_R1.fastq.gz 80000001 160000000) <(grabix grab /mnt/align_prep/NG-01_8_R2.fastq.gz 80000001 160000000)
     14520 Done                    | /mnt/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 4 -m 1G -O bam -T /mnt/bcbiotx/tmpN4t6rS/NG08-sort-80000001_160000000-sorttmp-namesort -o /mnt/bcbiotx/tmpN4t6rS/NG08-sort-80000001_160000000.bam -
' returned non-zero exit status 137

**Comment by chapmanb** [comment]
Diya;
Thanks for the report and sorry about the issues. It appears that your operating system is stopping the job, which causes the failure:
```
/bin/bash: line 1: 14519 Killed
```
This is typically due to using more memory than available on the system or going over some time limits or other system checks. Is it possible this is a low memory node and you're hitting the available memory limits, or processes are time or resource restricted on your system?

Hope this helps for debugging further.

**Comment by DiyaVaka** [comment]
thanks. it got fixed.
