### ISSUE TITLE
Error with ChIP-seq pipeline

### ISSUE THREAD

**Issue by lijinyangthu** [bcbio/bcbio-nextgen#2626]
Hi,

I have used the bcbio pipeline for ATAC-seq analysis and it went really well. Recently, I have been trying to use the bcbio pipeline for ChIP-seq analysis. However, after several try, I realize that I'm faced with one problem with peak calling. 

For example, I have two samples (one input and one chip). It seems like that the pipeline cannot complete the peak calling step. After I check the generated files in the work directory, I found files in for the chip sample in the macs2 directory but no file for the input sample in the macs directory. Besides, when I check the log files, I don't really see command for the macs2 step. 

Thanks a lot for your help!

Best,

Jinyang

Here is my example yaml file:

details:
- analysis: chip-seq
  metadata:
     batch: group1
     phenotype: chip 
  genome_build: mm10
  description: hippo_H3K9ac
  files:
  - /home/jinyangl/ChIP-seq/Hippocampus/hippo_H3K9ac.R1.fastq.gz
  - /home/jinyangl/ChIP-seq/Hippocampus/hippo_H3K9ac.R2.fastq.gz
  algorithm:
    aligner: bowtie2
    adapters: [truseq]
    trim_reads: read_through
    chip_method: chip
    peakcaller: [macs2]
  resources:
    macs2:
      options: ["--broad", "-q 0.05"]
- analysis: chip-seq
  metadata:
     batch: group1
     phenotype: input 
  genome_build: mm10
  description: hippo_input
  files:
  - /home/jinyangl/ChIP-seq/Hippocampus/hippo_input.R1.fastq.gz
  - /home/jinyangl/ChIP-seq/Hippocampus/hippo_input.R2.fastq.gz
  algorithm:
    aligner: bowtie2
    adapters: [truseq]
    trim_reads: read_through
    chip_method: chip
    peakcaller: [macs2]
  resources:
    macs2:
      options: ["--broad", "-q 0.05"]
fc_date: '2019-01-14'
fc_name: project_hippo-ChIPseq
upload:
  dir: ../final

**Comment by roryk** [comment]
Hi Jinyang,

It's hard to debug without seeing the log files-- do you think you could put up your log files and your sample configuration file up somewhere where we can take a look?

**Comment by lijinyangthu** [comment]
Thanks a lot for your quick reply!!! I updated the bcbio pipeline this morning one more time and I'm running the chipseq analysis again. I will update to you once I get some results from it.

By the way, do you see any problem with the yaml file?

Thanks again! 

Best,

Jinyang

> Hi Jinyang,
> 
> It's hard to debug without seeing the log files-- do you think you could put up your log files and your sample configuration file up somewhere where we can take a look?

**Comment by lijinyangthu** [comment]
I have tried running the pipeline several times in the past two days and always get stuck at one step.
In each of the run, the program seems like to stop at the "flushing read ends lists...done." line forever.
Based on my understanding of the bcbio pipeline, following this step might be the bamsormadup process.

Here is the end of my bcbio-nextgen-debug.log:
......
[2019-01-15T22:24Z] 95.04% overall alignment rate
[2019-01-15T22:24Z] [V] 17734808	16:18:99785199	MemUsage(size=3402.47,rss=1596.32,peak=3784.68)	AutoArrayMemUsage(memusage=3036.7,peakmemusage=3166.38,maxmem=1.75922e+13)	fina
l
[2019-01-15T22:24Z] [V] flushing read ends lists...done.

Thanks a lot for your help!

Best,

Jinyang



> Great-- that looks fine, so having the log files will be helpful in figuring out what to do.

**Comment by lijinyangthu** [comment]
Good morning, I solved the above problem by changing the parameter of CPU number and memory for the job submission. It seems like that memory/CPU is key to this process (not just total memory).

Thanks!

**Comment by lpantano** [comment]
Hi Jinyang,

You are correct. We use the input as the control during macs2 call.

Cheer

Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th

**Comment by lijinyangthu** [comment]
Thanks, Lorena!
