### ISSUE TITLE
Galaxy tool to run BCBio RNASeq

### ISSUE THREAD

**Issue by andreyto** [bcbio/bcbio-nextgen#2627]
We decided to write a Galaxy tool(s) to let our users run BCBio RNASeq pipeline through the Galaxy UI. It seems like a fairly straightforward exercise in terms of the input fields, but the execution and dependency management present quite a few choices. I wanted to ask for any pointers before we commit to a specific design. I have searched for the existing Galaxy BCBio Tools, but could not find any. There is a lot of false positive hits coming back in the search results because BCBio relies on Galaxy-formatted reference data.
- Are there any existing Galaxy tools to run BCBio?
- What is the best way to run BCBio workflows from Galaxy? Our primary target is a cluster, no Docker, and we can run Docker containers through uDocker as long as they do not do "root"-like things. The execution options that I see are:
  - Single job from Galaxy that starts BCBio in single node multi-core mode. That is the most reliable option, and probably OK for our typical RNASeq runs. We have fat nodes with 72 cores and up to 1TB of RAM. One BCBio job will process all samples.
  - The extension of the above approach, but we can let Galaxy perform its implicit scatter over all samples in a Galaxy dataset collection, resulting in one Galaxy job per sample. We would need to build a Galaxy native workflow by adding a combiner job that merges together the results of individual per-sample BCBio runs. That is a bit of extra work if one takes into account QC outputs etc. This would also lose the efficiency of the native BCBio batching, but I do not think that one is actually used for the RNASeq?
  - Same as above, but some CLI workflow language like CWL or WDL is used to scatter and merge.
  - Single job from Galaxy that starts BCBio in IPython mode multi-node. That intermittently fails on our cluster on larger runs with missing files exceptions, likely due to the NFS lack of cache coherency across nodes.
  - Single job from Galaxy that starts BCBio in CWL mode under Cromwell or Toil. That would be the preferred option for scalability and future portability, but the BCBio docs imply that RNASeq is not yet CWL-ready. I see the "cwl-ready" container on [quay](https://quay.io/repository/bcbio/bcbio-rnaseq) though. What is the status of the CWL for RNASeq?
- Each of the execution modes above can be considered for the on-host local install, or for a containerized run (uDocker). Container looks attractive. Can we use any of the existing containers? I assume we would have to bind-mount the reference directory anyway?

I am assuming above that we do not care about sharing any of the reference data between Galaxy and BCBio installs, and treat BCBio as a self-contained package, for simplicity.

Thanks!

**Comment by chapmanb** [comment]
Andrey;
Thanks much for working on this. I don't believe there are any bcbio Galaxy wrappers so this would definitely be a useful contribution. As you've identified, the main difficulty is that bcbio and Galaxy have different approaches for submitting to the cluster. We've been patiently waiting for Galaxy native CWL support hoping that it would bridge that gap and make this integration more seemless.

My suggestion would be to start with the multicore approach and see how far that takes you. For RNA-seq it should be pretty performant for single or small sample sizes, and you can use Galaxy itself to manage larger sample batches.

Hope this helps confirm what it sounds like you were learning towards. Thanks again.

**Comment by andreyto** [comment]
Thanks, Brad! So the "cwl-ready" container on quay cannot be used yet with Cromwell or Toil?
We will start with the basic single-node multicore backend.

**Comment by chapmanb** [comment]
Andrey;
The CWL is functional with Cromwell as a runner, although for RNA-seq doesn't contain everything the standard pipeline does. However it doesn't do any special integration with Galaxy in terms of workflow or tool conversion from CWL into standard Galaxy workflows and tools, so everything would happen outside of Galaxy in a separate run environment, much like the older bcbio specific IPython approach. I'll definitely recommend the CWL once it has tighter Galaxy integration, since you wouldn't have to maintain two parallelization approaches. Hope the multicore single node approach works well for you as a starting point.
