### ISSUE TITLE
bcbio 1.1.2 only copy multi-sample Lumpy VCF once to final project dir 

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2632]
The single multi-sample Smoove/Lumpy VCF file should only be copied once to the final dir. 
See the explanation below:

Single multi-sample Smoove/Lumpy VCF file in the work dir:
```
./work/structural/S_101913_04/lumpy/S_101913_04-DA_1336-svs-smoove.genotyped-filter.vcf.gz
```

Current situation: Redundant identical multi-sample SV VCF files in the final dir. Also identical to the single multi-sample Smoove/Lumpy VCF file in the work dir. 
```
./final/S_101913_01/DA_1336-lumpy.vcf.gz
./final/S_101913_02/DA_1336-lumpy.vcf.gz
./final/S_101913_03/DA_1336-lumpy.vcf.gz
./final/S_101913_04/DA_1336-lumpy.vcf.gz
./final/S_101913_05/DA_1336-lumpy.vcf.gz
./final/S_102292_01/DA_1336-lumpy.vcf.gz
./final/S_102292_03/DA_1336-lumpy.vcf.gz
./final/S_102292_17/DA_1336-lumpy.vcf.gz
./final/DA_1251_03/DA_1336-lumpy.vcf.gz
./final/DA_1251_10/DA_1336-lumpy.vcf.gz
./final/DA_1251_11/DA_1336-lumpy.vcf.gz
./final/DA_1251_12/DA_1336-lumpy.vcf.gz
./final/DA_1251_13/DA_1336-lumpy.vcf.gz
./final/DA_1251_14/DA_1336-lumpy.vcf.gz
./final/DA_342_11/DA_1336-lumpy.vcf.gz
./final/DA_342_13/DA_1336-lumpy.vcf.gz
./final/DA_342_15/DA_1336-lumpy.vcf.gz
./final/DA_575_01/DA_1336-lumpy.vcf.gz
./final/DA_575_03/DA_1336-lumpy.vcf.gz
./final/DA_956_03/DA_1336-lumpy.vcf.gz
./final/DA_956_04/DA_1336-lumpy.vcf.gz
./final/DA_956_05/DA_1336-lumpy.vcf.gz
./final/DA_956_06/DA_1336-lumpy.vcf.gz
./final/DA_956_14/DA_1336-lumpy.vcf.gz
./final/DA_956_15/DA_1336-lumpy.vcf.gz
./final/DA_956_16/DA_1336-lumpy.vcf.gz
./final/DA_956_17/DA_1336-lumpy.vcf.gz
```

Expected situation: Single copy of the SV VCF file from the work dir to the final project dir. 
```
./final/2019-01-17_DA_1336_samples-merged/DA_1336-svs-smoove.genotyped-filter.vcf.gz
```

The expected situation matches how the multi-sample VCF files are copied to the final dir for WGRS and RNAseq. 
For WGRS and RNAseq only the sample specific GVCF files are stored in the sample sub directory of the final dir. 
As far as I know there are no SV GVCF files produces by the Smoove/Lumpy analysis. 

Could the code that does the upload for the Lumpy SV file file be fixed to store the file only once in the final project directory. 

Thank you.

**Comment by chapmanb** [comment]
Wim;
Thanks much for the report. We used to separate the multi-sample lumpy files into individual samples but stopped doing this to avoid extra processing work for larger files, but didn't take care of this redundancy. The latest development now fixes this by checking and uploading only a single copy into a sample folder for all items batched together. The project folder upload would be more consistent with what happens in variant calling, but I don't want to entirely change location for users who have downstream processes that use the bcbio outputs by location.

Hope this works for you and thanks again.
