### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#2633]
terminate called after throwing an instance of 'libmaus2::exception::LibMausException'
  what():  PosixOutputStreamBuffer::doSync(): write() failed: No space left on device
/mnt/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7f28d4ab1f8c]
bamsormadup(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41fc10]
bamsormadup(libmaus2::aio::PosixFdOutputStreamBuffer::doWrite(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*, unsigned long, long, unsigned long)+0x255)[0x427e35]
bamsormadup(libmaus2::aio::PosixFdOutputStreamBuffer::doSync()+0x51)[0x427f31]
bamsormadup(libmaus2::aio::PosixFdOutputStreamBuffer::sync()+0x12)[0x428172]
/mnt/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libstdc++.so.6(std::ostream::flush()+0x1e)[0x7f28d3f054be]
/mnt/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(std::_Sp_counted_ptr<libmaus2::aio::PosixFdOutputStream*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()+0x57)[0x7f28d4a95cc7]
bamsormadup()[0x41790a]
bamsormadup()[0x418548]
bamsormadup()[0x46e818]
bamsormadup()[0x46e892]
bamsormadup()[0x41790a]
bamsormadup()[0x49ecc8]
bamsormadup()[0x4bfa1e]
bamsormadup()[0x4c0499]
bamsormadup()[0x514ec8]
bamsormadup()[0x41afce]
bamsormadup()[0x41524f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f28d1473445]
bamsormadup()[0x416f22]
/bin/bash: line 1:  6461 Segmentation fault      bamcat level=0 tmpfile=/mnt/bcbiotx/tmpWV7hU3/bcbiotx/tmpG6BaBr/NG14-sort.bam-bammerge `cat /mnt/bcbiotx/tmpWV7hU3/bcbiotx/tmpG6BaBr/NG14-sort.list`
      6462 Aborted                 | bamsormadup threads=16 tmpfile=/mnt/bcbiotx/tmpWV7hU3/bcbiotx/tmpG6BaBr/NG14-sort.bam-bamsormaduptmp indexfilename=/mnt/bcbiotx/tmpWV7hU3/bcbiotx/tmpG6BaBr/NG14-sort.bam.bai > /mnt/bcbiotx/tmpWV7hU3/bcbiotx/tmpG6BaBr/NG14-sort.bam
' returned non-zero exit status 134

**Comment by roryk** [comment]
Hi @DiyaVaka, are you running out of space in `/mnt/bcbiotx`? The key error here is `terminate called after throwing an instance of 'libmaus2::exception::LibMausException'
what(): PosixOutputStreamBuffer::doSync(): write() failed: No space left on device`

**Comment by roryk** [comment]
Closing as this seems like a specific issue which is outside of bcbio.
