### ISSUE TITLE
Bcbio 1.1.2: RNAseq: No bcftools stats on disk and also not  in the MultiQC report for the variant table made with GATK

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2641]
Another minor issue. Would it be possible to create the bcftools stats for the RNAseq variant calling table made with GATK? And also then include the bcftools stats  in the MultiQC report?

**Comment by roryk** [comment]
Hi @WimSpee,

Thanks, good suggestion. I'll add that in so its ready for the next release.

**Comment by roryk** [comment]
Hi @WimSpee,

I have finally gotten out from under a huge workload and implemented support for this. Thanks for the suggestion!

**Comment by WimSpee** [comment]
Hi @roryk  Thank you for this.
