### ISSUE TITLE
Incompatible cutadapt version for mirge2.0

### ISSUE THREAD

**Issue by rdocking** [bcbio/bcbio-nextgen#2649]
Hi there (probably @lpantano):

I was testing the mirge2.0 integration in the bcbio small-RNA pipeline, and came across this issue:

I'd have a mirge command like so:

```
/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/bin/miRge2.0 annotate -s /projects/karsanlab/rdocking/KARSANBIO-1229_isomirs/KARSANBIO-1651_reprocessing/two_libs_all_callers/work/bcbiotx/tmpIMfPIp/sample_file.txt -o /projects/karsanlab/rdocking/KARSANBIO-1229_isomirs/KARSANBIO-1651_reprocessing/two_libs_all_callers/work/bcbiotx/tmpIMfPIp -pb /projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/bin -lib /projects/rdocking_prj/software/tool_testing/mirge_libraries -sp human   -di -ai -gff
```

Which crashed with this error:

```
[2019-01-24T23:56Z] n225: Running miRge2.0.
[2019-01-24T23:56Z] n225: Performing quantitation analysis of SRR5234257.trimmed.clean.fastq...
[2019-01-24T23:56Z] n225: Process Worker-2:
[2019-01-24T23:56Z] n225: Traceback (most recent call last):
[2019-01-24T23:56Z] n225:   File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
[2019-01-24T23:56Z] n225:     self.run()
[2019-01-24T23:56Z] n225:   File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/mirge/utils/trim_file.py", line 54, in run
[2019-01-24T23:56Z] n225:     read = modifier(read)
[2019-01-24T23:56Z] n225: TypeError: __call__() takes exactly 3 arguments (2 given)
```

I re-ran the mirge command outside bcbio and saw the same issue. Looking at the mirge github, it looks like the issue is due to an incompatible version of cutadapt:

https://github.com/mhalushka/miRge/issues/17

miRge wants cutadapt 1.16, and bcbio has moved up to cutadapt 1.18:

```
> cutadapt --version
1.18
```

This will prevent miRge from working in bcbio for now. Note that we're pretty happy here with seqbuster/seqcluster - was just interested in testing miRge for a 'second opinion' on our data. Hope this helps!

**Comment by lpantano** [comment]
Thanks for reporting this. It seems the new version of cutadapt is not
compatible.

I am happy to debug this, but I will need some time. I really want to have
mirge integrated.

Meanwhile, since we are not using cutadapt for anything else, you can try
to install that version with `bcbio_conda` and see if it works. So you can
just try it. If that is the case, I can force to install cutadapt 1.16
until I help with that bug.

Let me know what you find out.

**Comment by rdocking** [comment]
Thanks - good idea! I downgraded cutadapt and it looks like I'm past the step that crashed previously:

```
/> bcbio_conda install cutadapt=1.16
```

**Comment by rdocking** [comment]
Noting that mirge ran successfully to completion.

**Comment by lpantano** [comment]
cool! I will pin that version to be install with bcbio then for now.

Thanks for tell us this.
