### ISSUE TITLE
feature request: simple flowcharts of common pipelines

### ISSUE THREAD

**Issue by mchimenti** [bcbio/bcbio-nextgen#2650]
Hello:

It would be really nice if the page,
https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html

linked to some pages with flowcharts outlining the steps that occur. Would be nice to know what to expect beforehand without having to browse the code base on github.   

A recent example is when I ran the ChIP-Seq pipeline and saw that QC showed 100% alignment rates and 0% duplicate rates.  I spent a few hours chasing this down only to discover that samtools stats runs on the filtered BAM file rather than the raw BAM file.  A schematic could have illustrated this in a few seconds.  

I realize the pipelines are always changing, so all the details can't be there, but just a broad, flow-chart style overview for each pipeline would be super helpful when planning and carrying out analyses and trying to explain to colleagues and advisors what exactly happened with their data.  It would also allow us to see how new versions of common pipelines like RNA-seq differ from previous when bcbio is updated.  

Thanks.

**Comment by lpantano** [comment]
Hi,

Definitely, that would be awesome.

I am curious where did you look at the duplicate rates, since we switch a
while ago to use the bam file prior filtering.

Can you check whether the file under qc/samtools for one sample if you see
that the line with read duplicates is 0 or not? I know that we run
fastqc as well and it gets a similar metric, and maybe there is when we use
the filtered file.

It would help to know where to fix the code, I think for chipseq is very
useful to run the QC from the primary BAM file.

Thanks a lot!

**Comment by mchimenti** [comment]
Hi Lorena,  I will check that for you.  In the meantime, know that this was bcbio 1.0.8.

**Comment by naumenko-sa** [comment]
Hi Michael!

Do you think this tool might be helpful: https://github.com/guillermo-carrasco/bcbio-nextgen-monitor?
I have not tried it by myself, but I am interested to learn about its usability.

Sergey

**Comment by mchimenti** [comment]
https://www.michaelchimenti.com/2019/03/bcbio-rna-seq-under-the-hood/
^^^
Regarding my original post above, it's not a flow chart but it is a list of the commands in the RNA-seq pipeline.  

@chapmanb  I have not had a chance to try the pipeline again with the latest version.

**Comment by chapmanb** [comment]
Michael;
Awesome, thanks much for writing this up. From our side, we're totally agreed with your assessment of wanting full traceability of commands. This was one of the motivations for starting to move bcbio workflows to use the Common Workflow Language (CWL) for describing the runs. As you get more complex and general workflows it gets more challenging to represent and display these in a useful way, but definitely we're always working towards traceability and understandability of what's happening. Thanks again.
