### ISSUE TITLE
LOH summarization for arbitrary genes

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2651]
I ask in case, but feel free to close if it's already implemented.

A lot of my data deal with domain-specific genes that may not be in the CIVIC list that can be used currently with `svprioritize` to calculate LOH. Since one can already supply lists of interest with `svprioritize`, do these list also work with LOH summarization like with CIVIC?

**Comment by chapmanb** [comment]
Luca;
Nice idea, thanks much for the suggestion. We can't get fine grained segmentation by event or cancer type as we're doing with CIViC, but could at least pass along reporting of genes of interest from an input BED file. The latest development version should now do this, keying on the gene name in the 4th column of the svprioritize BED if you use a non-CIViC input. Please let us know if you run into any issues and thanks again.
