### ISSUE TITLE
Peddy fails although an 'allowed error' is encountered

### ISSUE THREAD

**Issue by roland-ewald** [bcbio/bcbio-nextgen#2653]
Some [errors are allowed in `peddy.py`](https://github.com/bcbio/bcbio-nextgen/blob/b2d86371764a5cf048b2dd8d5609f40c70231cdb/bcbio/variation/peddy.py#L107), but it seems they these are [now printed differently in `scikit-learn`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/decomposition/pca.py#L485) (introduced by [this commit](https://github.com/scikit-learn/scikit-learn/commit/787d5d2af8c9f91adfd7719ba07f6e7594ae5efb#diff-4143e2be661b19bdff49616c76de91c3R476))?

Should these be updated in `peddy.py`? I'm happy to provide a PR.

**Comment by roryk** [comment]
Thank you for noticing this. A PR would be awesome. Do the errors not get allowed with the scikit-learn version that we are installing because of this? I'm wondering if we'll have to support both versions or if we're already on the new version so we can just dump the old one.

**Comment by chapmanb** [comment]
Roland;
Thanks much for the heads up on this. Are you finding this is still an issue with the latest development version? I pushed a fix for this a few days ago (https://github.com/bcbio/bcbio-nextgen/commit/79c18668f3ab95211350e1784aef9b70f042fae5) and was hoping to have caught all the cases. We're aiming for a new release so would love to make sure we've got all of these before it goes out. Thanks again.

**Comment by roland-ewald** [comment]
Hi Rory , hi Brad; 
Sorry for the confusion, I did not realize this has already been fixed. The changes in https://github.com/bcbio/bcbio-nextgen/commit/79c18668f3ab95211350e1784aef9b70f042fae5 look exactly right. Closing the issue.
Many thanks!
