### ISSUE TITLE
Is it possible to omit 'InbreedingCoeff'?

### ISSUE THREAD

**Issue by SarahBeecroft** [bcbio/bcbio-nextgen#2655]
Hi, 

Is there a way to omit 'InbreedingCoef' from the GATK pipeline? Some downstream applications can't seem to parse it, so it would be good to know if this is possible. 

thanks!

**Comment by chapmanb** [comment]
Sarah;
Thanks for the report. What type of issues are you running into? We don't currently have a way to exclude this annotation but can definitely work on a plan if you can provide more details about your needs.

**Comment by roryk** [comment]
Closing as there wasn't any follow up-- please reopen if this is something that would be helpful. Thanks!
