### ISSUE TITLE
"No such file or directory" error in joint-calling run

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#2657]
Hi,

I'm running into errors with a GATK joint-calling run on 416 whole exome samples. It crashes at the `prep_align_inputs` stage with the following:

```
    383
    384 def _prep_grabix_indexes(in_files, data):
    385     """Parallel preparation of grabix indexes for files.
 
...........................................................................
/gd/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py in symlink_plus(orig='/home/semlucas/WES/KC_ANZRAG_WES_GATK/fastqs/AG0030_R1.fastq.gz', new='/home/semlucas/WES/KC_ANZRAG_WES_GATK/work/align_prep/AG0030_AG0030_R1.fastq.gz')
    340     orig = os.path.abspath(orig)
    341     if not os.path.exists(orig):
    342         raise RuntimeError("File not found: %s" % orig)
    343     for ext in ["", ".idx", ".gbi", ".tbi", ".bai", ".fai"]:
    344         if os.path.exists(orig + ext) and (not os.path.lexists(new + ext) or not os.path.exists(new + ext)):
--> 345             with chdir(os.path.dirname(new)):
        new = '/home/semlucas/WES/KC_ANZRAG_WES_GATK/work/align_prep/AG0030_AG0030_R1.fastq.gz'
    346                 remove_safe(new + ext)
    347                # Work around symlink issues on some filesystems. Randomly
    348                # fail to symlink.
    349                 try:
 
...........................................................................
/gd/apps/bcbio/anaconda/lib/python2.7/contextlib.py in __enter__(self=<contextlib.GeneratorContextManager object>)
     12     def __init__(self, gen):
     13         self.gen = gen
     14
     15     def __enter__(self):
     16         try:
---> 17             return self.gen.next()
        self.gen.next = <method-wrapper 'next' of generator object>
     18         except StopIteration:
     19             raise RuntimeError("generator didn't yield")
     20
     21     def __exit__(self, type, value, traceback):
 
...........................................................................
/gd/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py in chdir(new_dir='/home/semlucas/WES/KC_ANZRAG_WES_GATK/work/align_prep')
    193 def chdir(new_dir):
    194     """Context manager to temporarily change to a new directory.
    195
    196     http://lucentbeing.com/blog/context-managers-and-the-with-statement-in-python/
    197     """
--> 198     cur_dir = os.getcwd()
        cur_dir = undefined
    199     safe_makedir(new_dir)
    200     os.chdir(new_dir)
    201     try:
    202         yield
 
OSError: [Errno 2] No such file or directory
```

Could this have something to do with running on a shared filesystem?

**Comment by chapmanb** [comment]
Bennet;
Thanks for the detailed report and sorry about the issue. This does look like a shared filesystem problem, as it's having trouble finding the current working directory on the filesystem. It's hard to tell from just this snippet if it's some kind of race condition or the shared filesystem was overworked and too slow to propagate a directory to the filesystem. Are you seeing this consistently? If so, would you be able to share the full traceback. It's confusingly failing when making symlinks but I'm not sure in exactly what process from the information we have so far. Thanks for the help debugging.

**Comment by DrMcStrange** [comment]
Hi Brad,
It does seem to be consistently giving the same error consistently with this dataset, although I've run similar jobs recently without running into this. Anyway, full traceback attached. Any help getting it running will be much appreciated.

[bcb_traceback.txt](https://github.com/bcbio/bcbio-nextgen/files/2815741/bcb_traceback.txt)

**Comment by chapmanb** [comment]
Bennet;
Thanks much for the full traceback, this does help isolate where it's happening. I'm still unsure of what causes this, since it's failing on finding the working directory. However, I added a speculative fix which can recover from this and wait for the filesystem to recover if it's not returning the directory. I hope this will make it work reliably for you even with the larger datasets.

**Comment by DrMcStrange** [comment]
Thanks Brad, just confirming that this worked. It's made it through to the alignment stage at any rate.
