### ISSUE TITLE
bcbio 1.1.3: install error

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2658]
Hi Brad,

I'm trying to install the latest bcbio release using the install script, but I keep running into the following error:
```
Upgrading third party tools to latest versions
--2019-01-30 09:25:32--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 140.82.118.3, 140.82.118.4
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2019-01-30 09:25:32--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........  250K
  3072K ........ ........ ........ ......                      419K=17s

2019-01-30 09:25:50 (297 KB/s) - written to stdout [5175457]

Traceback (most recent call last):
  File "/home/galaxy/bcbio/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/galaxy/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/home/galaxy/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 520, in upgrade_thirdparty_tools
    cbl_deploy = __import__("cloudbio.deploy", fromlist=["deploy"])
  File "/home/galaxy/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 9, in <module>
    from cloudbio.utils import _setup_logging, _configure_fabric_environment, _parse_fabricrc
  File "/home/galaxy/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/utils.py", line 7, in <module>
    from fabric.main import load_settings
ImportError: cannot import name load_settings
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 287, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/galaxy/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--isolate', '--tooldir', '/home/galaxy/bcbio/tools', '-u', 'stable']' returned non-zero exit status 1
```

Any ideas? I've already tried using several python versions, completely removing the directory before installing, ...

Thanks 
M

**Comment by matthdsm** [comment]
Could this have something to do with the recent py3 work? It seems to me the fabric module for cloudbiolinux isn't installed correctly.

Cheers
M

**Comment by matthdsm** [comment]
Error makes sense however,
when checking the code from fabric, there is no 'load_settings' attr

M

**Comment by matthdsm** [comment]
Problem can be fixed by pinning fabric to the latest `1.*` version. The method was removed in 2.*

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for this report. The goal is to remove the fabric requirement for the next release. We're no longer making use of most of fabric's infrastructure and the incompatibilities and changes on moving to python 3 will be blocker.

In the short term, do you know where/how fabric 2.x got installed. We should be getting from conda-forge which has 1.14 (https://anaconda.org/conda-forge/fabric/files) and hasn't changed recently. If we can isolate what happened we can either pin or adjust to avoid having it happen to others. Thanks for the help debugging this.

**Comment by matthdsm** [comment]
As far as I can see, fabric was downloaded from the default channels. After I manually changed that to the conda-forge channel, everything worked a-ok. No idea where the issue came from, but I must admit we've been having some troubles with our conda envs lately, so it's possible that a wrong version got in there by accident.

M

**Comment by chapmanb** [comment]
Matthias;
Thanks for this. If you end up reproducing in the standard bcbio install I'd be happy to fix. We should always use conda-forge in bcbio installs so that'll avoid pulling in the default anaconda channel version. Hopefully this'll all be out soon and we won't have to worry about it going forward. Thanks again.
