### ISSUE TITLE
bcbio for specific chromosome alignment

### ISSUE THREAD

**Issue by pengxiao78** [bcbio/bcbio-nextgen#2660]
I have some targeted deep-sequencing data for just one specific gene region. Could I queue specific hg38 chromosome as genome_build for alignment?

**Comment by chapmanb** [comment]
Thanks for the question. For targeted analyses you should align to the entire genome to avoid misplacing off-target reads and then limit your analysis regions to the capture with `variant_regions`:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#analysis-regions

Hope this works for your analysis.
