### ISSUE TITLE
bcbio 1.1.3: Update Smoove from 0.1.9 to 0.2.3

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2666]
Hi, 

I just noticed that smoove in bcbio 1.1.3 is still on version 0.1.9 while smoove version 0.2.3 is out. 

There should be quite some sensitivity/specificity, performance and (duphold automatic) annotation improvement in version 0.2.3 v.s. version 0.1.9.
https://github.com/brentp/smoove/releases

Could you please update the smoove version in bcbio? All the other related executables seem already up to date (lumpy, mosdepth, svtyper, svtools).

This relates somewhat to the other Smoove population calling issue that I opened  (being able to use the executables from bcbio saves me from having to make a duplicate install.)
https://github.com/bcbio/bcbio-nextgen/issues/2652

The improved functionality from version 0.2.3. should also be useful for the batch mode SV calling as it now is already implemented in Bcbio.

**Comment by WimSpee** [comment]
At least one bug, END<POS has also been fixed in bcbio 0.2.3. 
https://github.com/brentp/smoove/issues/56

**Comment by chapmanb** [comment]
Thanks much for the heads up this was out of date. The conda recipe is now updated to 0.2.3 so if you update with `bcbio_nextgen.py upgrade --tools` it should include this as part of the standard install. Thanks again.

**Comment by WimSpee** [comment]
Thank you for the quick update.

**Comment by WimSpee** [comment]
The `bcbio_nextgen.py upgrade --tools` command says in the standard out that smoove is updated to version 0.2.3

```
Downloading and Extracting Packages

smoove-0.2.3         | 8.5 MB    | ################################################################################################################################################################################################### | 100% 
```

But the Smoove executable is not updated. 
```
ls -lh  /Tools/bcbio/1.1.3/anaconda/bin/smoove
-rwxrwxr-x+ 2 701 701 15M Jun  8  2018 /Tools/bcbio/1.1.3/anaconda/bin/smoove
/Tools/bcbio/1.1.3/anaconda/bin/smoove
smoove version: 0.1.9
```

Is the smoove executable maybe packaged via another way in Bcbio? That blocks the anaconda update?

Or do I need a different update command or a fresh install of the latest bcbio version?

**Comment by chapmanb** [comment]
Wim;
Sorry about the problems with referencing the old version. Could you try running one more upgrade command: `bcbio_nextgen.py upgrade --tools` to see if that resolves the issue? We've been working on the install to provide compatibility with python 3 and smoove got moved into a separate conda environment due to requiring python 2 because of the lumpy dependency. The latest install code should remove the old version from the base environment in addition to adding it to the new environment. Hope this helps resolve the issue for you.

**Comment by WimSpee** [comment]
Running the update once more did not fix the issue. 

I could find the smoove 0.2.3 executable in another subdirectory. In the main bin directory there still is smoove 0.1.9
```
find  /Tools/bcbio/1.1.3/ -name smoove
/Tools/bcbio/1.1.3/anaconda/pkgs/smoove-0.2.3-0/bin/smoove
/Tools/bcbio/1.1.3/anaconda/pkgs/smoove-0.1.9-0/bin/smoove
/Tools/bcbio/1.1.3/anaconda/bin/smoove
/Tools/bcbio/1.1.3/anaconda/envs/python2/bin/smoove
```

I also did a fresh install of the latest bcbio development version. There the smoove 0.2.3 executable does end up in the main bin directory. 
```
find  /workspace/my_user/tmp_bcbio_1.1.3_development/  -name smoove
/workspace/my_user/tmp_bcbio_1.1.3_development/tools/bin/smoove
/workspace/my_user/tmp_bcbio_1.1.3_development/data/anaconda/pkgs/smoove-0.2.3-1/bin/smoove
/workspace/my_user/tmp_bcbio_1.1.3_development/data/anaconda/envs/python2/bin/smoove
```

I'll either:
* manually remove the bcbio 0.1.9 executable and symlink the 0.2.3 executable
* use the fresh bcbio latest development install for now, until bcbio 0.1.4 is released. 

Maybe the above is useful for you or anybody else who would like to run the latest smoove version within bcbio.

**Comment by chapmanb** [comment]
Wim;
Thanks so much for testing this out and apologies about the continued problems. Both of your workarounds are totally workable, but it was a bug that the switch didn't happen automatically when upgrading. I just pushed a fix for the problem so now if you upgrade again it should move over any other packages with the same issue from an existing install. Thanks again for your patience testing and working on this.
