### ISSUE TITLE
Error installing data with bcbio_nextgen.py

### ISSUE THREAD

**Issue by pprieto** [bcbio/bcbio-nextgen#2668]
Hi

While trying to follow the automated installation, I got intro some troubles by the end when installing the genome reference data.

Seems to be related to the issue from here: chapmanb/cloudbiolinux#283

In principle fixing that issue resolves the issue. I am creating this issue here as well in case anybody faces the same as me. Sorry for the issue duplication in both repos 

Cheers

**Comment by chapmanb** [comment]
Thanks for the report, fixed with your PR: https://github.com/chapmanb/cloudbiolinux/pull/282
