### ISSUE TITLE
atropos: Command not found after fresh install

### ISSUE THREAD

**Issue by pprieto** [bcbio/bcbio-nextgen#2669]
Hi,

Although I have performed a fresh install, when I try to run the workflow it doesn't seem to be able to find the tools.

When I tried:

`bcbio_nextgen.py ../config/config.yaml`

I receive:

```
/usr/bin/bash: atropos: command not found
' returned non-zero exit status 127
```

I can see that atropos is located in the local installation path: 

`~/local/share/bcbio/anaconda/envs/python3/bin/atropos`

Is there anything I have to set in the environment so can bcbio can find all tools/packages ?

Cheers

**Comment by chapmanb** [comment]
Pablo;
Sorry about the issue. bcbio should link executables from subdirectories into the global `--tooldir` bin so they're all available for a single PATH adjustment. I've just checked in some work to improve how it handles linking: could you try a `bcbio_nextgen.py upgrade --tools` to see if that correctly adds it? If not, are there any references to atropos in your `/path/to/tooldir/bin` directory? Hope the updates fix it and thanks for the help debugging.

**Comment by pprieto** [comment]
Yes!

Running `bcbio_nextgen.py upgrade --tools` does the trick, thanks a lot !

If I want to download only the rnaseq data, can I just run:

`bcbio_nextgen.py upgrade --datatarget rnaseq --genomes hg38`

And only download the data for the rnaseq analysis? Or there is no way to avoid the rest of the data (i.e. validation, annotation, ... ) ?

Cheers

**Comment by chapmanb** [comment]
Great, glad the update fixed the problematic atropos link. For RNA-seq only data installation, that's exactly the way to do it. Hope this all works for what you need and let us know if you run into any issues.

**Comment by pprieto** [comment]
@chapmanb That doesn't seem to happen right now. If I try to run that command: `bcbio_nextgen.py upgrade --datatarget rnaseq --genomes hg38`

I see it starts to download all the entries that exist in `hg38` entry from `biodata.yaml` found in `tmpbcbio-install`. The only way I have to avoid those is to resume the upgrade after editing the `biodata.yaml` file.

Do you think I am doing something wrong ?

**Comment by chapmanb** [comment]
Pablo;
That's definitely unexpected behavior. Is it possible you've run an install/upgrade previously in this install for other genomes where you didn't specify datatarget? If so, bcbio might be picking up the previous datatarget values from `/path/to/bcbio/config/install-params.yaml`. It uses this to cache targets so you don't have to re-specify them every time you update. If this explains it and you want to change the defaults for your install, you could edit this file to match what you want. Hope this helps explain what is happening.

**Comment by pprieto** [comment]
Just tried it out with a fresh pull of the base container from here:

https://quay.io/repository/bcbio/bcbio-base

Should I avoid it ?

**Comment by lento2002** [comment]
on ... bcbio_nextgen.py upgrade --tools is there anyway to tell the installer to ignore upgrading GATK?

**Comment by chapmanb** [comment]
There isn't an automated way to ping gatk during bcbio upgrades but you can adjust to the version you want with:
```
bcbio_conda install -c conda-forge -c bioconda gatk4=4.1.0.0
```
pinning to whatever version you would like to remain with. Hope this helps.

**Comment by lento2002** [comment]
In a SLURM environment with bcbio on the workers getting atropos not found.  Version is latest dev version, also tried 
bcbio_nextgen.py upgrade --tools   ...  out of ideas currently
slurm-job.out.txt
[2019-03-01T12:42Z] Trimming with atropos: pact-normal
[2019-03-01T12:42Z] /bin/bash: atropos: command not found
[2019-03-01T12:42Z] Uncaught exception occurred
Traceback (most recent call last):


[root@ip-10-0-3-70 centos]# which atropos
/usr/local/bin/atropos
[root@ip-10-0-3-70 centos]# 

[root@ip-10-0-3-70 centos]# bcbio_nextgen.py -v
1.1.4a

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the comand issues. This is a bit hard to debug remotely with the information provided but a couple of suggestions:

- Does `/usr/local/bin/atropos` resolve to an existing version of atropos? This should be a symlink to the executable in the `envs/python3` directory in your bcbio install.
- Is `/usr/local/bin` part of the distributed filesystem on your SLURM cluster? If it's local to the login nodes (or where every you installed and are testing) it won't be available on compute nodes. You'll want to have the bcbio bin directory in a path on the shared filesystem so it's accessible from all machines, and also have this directory in your PATH.

Hope this helps.

**Comment by lento2002** [comment]
Thanks,  replies inlined.

* Yes, at moment each local worker has it's own copy of bcbio on the root volume.

* Is `/usr/local/bin` part of the distributed filesystem on your SLURM cluster? Right now the bcbio is local to each worker.  There is no bcbio of any type on the head node.  There is a /home and /scratch Lustre system exposed to the head node and all workers.  That currently doesn't have bcbio binaries or libraries.  So if these need to be exposed via /scratch and a PATH annotation is it only a few directories in bcbio or the whole structure?  in my mind i'm thinking just /bin and /envs perhaps?

**Comment by chapmanb** [comment]
Thanks for following up. The only requirement is that bcbio can find the code and tools on the system it's running on. Typically the best way to do this is install bcbio on a shared filesystem that all nodes in the cluster can access, and then adjust your PATH to point at this.

So you've installed bcbio separately on every machine in the cluster? This should work, although seems like a painful thing to keep up to date and synchronized as you could run into node specific issues depending on what machine you land on. It's a bit hard for me to debug without machine access but my suggestion would be to look on the machine where it fails and determine if the atropos install there is correct and linked from `/usr/local/bin`; my guess is that there is something problematic on that specific node that needs adjustment.

Hope this helps.
