### ISSUE TITLE
Missing VEP 95 cache for hg19

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2670]
As the subject says. I'm up to date, but it was not downloaded.

**Comment by chapmanb** [comment]
Luca -- sorry about the issue. When you ran the update, did this include a `--data` update? Did your `hg19/seq/hg19-resources.yaml` file get updated to version 51 with 95 specified? If you re-run, does it give any indication about what might be happening? What are the contents of your `vep` directory? We haven't changed anything substantial here, so trying to track down what might have happened. Thanks for the help debugging.

**Comment by lbeltrame** [comment]
FTR, `hg38` was updated. I'm in the process of updating the code, and I indeed added both `--data` and `--datatarget vep`. My resources file did *not* get updated to 95, though. Is it sufficient to change it to trigger a download?

**Comment by chapmanb** [comment]
Updating the resources file should fix the problem. Sorry about the issue, I'm not sure why hg38 would work cleanly and not hg19, but hope that fixes it for you.

**Comment by lbeltrame** [comment]
Indeed a manual updated started the download. Thanks.
