### ISSUE TITLE
feature request: pedigree info in vcf header

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2672]
Hi Brad,

I was wondering if it would be possible to add some pedigree headers to the output vcfs?
Since gemini db's are non standard anymore, we'd have to keep ped files around to identify family relations in a multisample vcf. It'd be handy (and up to spec) to keep this info handy in the VCF header.

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the suggestion. We have skeleton code to add pedigree information for tumor/normal samples with the idea that it could eventually extend to more complex setups:

https://github.com/bcbio/bcbio-nextgen/blob/8f1d4cac6f8e1442b658522288b028ffde0ed5f1/bcbio/variation/annotation.py#L99

We'd welcome contributions here if you understand how to best encode information from PED files in the header. Thanks again for the discussion.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks for the pointers. I've already opened a thread on the [vcftools-help mailinglist](https://sourceforge.net/p/vcftools/mailman/message/36580138/), but I don't think that'll be of much use, since the last post there was about 6 years ago..

I'm not sure if there's a set way to encode pedigree info, but I'm looking into it.
Thanks
M

**Comment by roryk** [comment]
Thanks-- @matthdsm did you ever figure out how folks encode pedigree information in the header?

**Comment by matthdsm** [comment]
Hi Rory, 

Nope, I've scoured the spec's for some concrete info, asked the forums and opened issues in the spec repo's, but I haven't got any answers to date.
All I know for sure is that it's possible, but there's no clear source on how to do it exactly 😞
