### ISSUE TITLE
can't upgrade to 1.1.3 due to conda being unable to solve environment

### ISSUE THREAD

**Issue by wresch** [bcbio/bcbio-nextgen#2676]
Hi there,

I know this isn't really a bcbio bug, but I wanted to let you guys know that due to the recent issues with conda performance i've been unable to upgrade bcbio in place since conda tried to solve some of the environments for 2 full days before I gave up.

I'm going to try and deploy as a singularity container and give up on in-place upgrades. If you are interested I can share the definition file if/once I make it work.

Wolfgang

**Comment by chapmanb** [comment]
Wolfgang;
Thanks for the report and apologies about the slow conda install times. There are two separate things happening right now with install speeds:

- Some of the recent conda versions had quite slow resolve times, conda 4.6.0 was the biggest culprit in my testing. If you were unlucky enough to have that version for an initial solve it would have a slow initial update on the first pass, and then should get you a more recent version that is not as slow. Just doing a `bcbio_conda install -c conda-forge conda` before installing if you have a problem version could help here.
- We're migrating to use python3 as the default python for bcbio in the next release, which will allow us to be future compatible as many projects drop python2 support. This makes for more complicated solutions as we move python2 only tools into a separate environment. This is a one time install operation but will make things take longer.

In cases where either of these is especially bad, a clean install of bcbio conda dependencies by removing your current `anaconda` directory and using `bcbio_nextgen_install.py` to point at the existing tool and data directories might be a faster option.

Hope some of these tips help if you decide to work with upgrading your non-singularity versions. Please let us know if it's still really slow and happy to debug more.

**Comment by wresch** [comment]
Hi Brad,

Thanks for the reply even though this really isn't a bcbio problem. I've tried a few different versions of conda and the supposedly faster pycryptosat solver to no avail.  I don't think i tried conda from conda-forge.  I did not realize conda-forge had its own conda package implementation.  Will give that a try and resort to deleting just the anaconda directory if that does not work before going to a complete re-install. I'll let you know how it went.

I maintain a large centrally installed conda tree on our cluster so conda has been a source of much frustration for me lately and I'm sure it has been for you as well.

-W

**Comment by chapmanb** [comment]
Wolfgang;
It sounds like you might have the latest fixes so I'm not sure if my suggestions will help, but would be great to hear how it goes. Practically, large local single environment installs coupled with the growing size of conda-forge does create issues. The most promising idea I read about was meta channels to restrict the search space:

https://medium.com/@marius.v.niekerk/conda-metachannel-f962241c9437

But I haven't yet played with it so don't know if it could help in your case. Hope this is useful and thanks again for testing out the different approaches.

**Comment by wresch** [comment]
Update:  I tried conda-forge::conda but that did not help. As I'm writing this, the `bcbio_nextgen_install.py` after deleting the anaconda directory is ongoing and the conda parts finished fairly quickly.

One question about this - does bcbio clean up older (unused?) datasets after updates?

And thanks for that pointer to the metachannels.  I'll look into adapting that for our internal use.

**Comment by chapmanb** [comment]
Wolfgang;
Thanks for checking this, I'm glad the clean update works relatively quickly. The on the fly conversion of packages into new environments does make for slower lookups but luckily it's only a single time process and then all should be back to normal.

bcbio doesn't do cleanup of older datasets but does replace for a lot of associated datasets rather than accumulating so hopefully won't collect too much older cruft. It doesn't try to clean up older conda packages so those will still be present in an install. Thanks again.

**Comment by wresch** [comment]
OK - we are back in business. The "new" install over the existing directory worked and now an update actually runs in a reasonable time as well.  A test RNASeq pipeline finished. Thanks for the help. The bcbio issue tracker is always a very pleasant place.

The reason I asked about cleaning up old data (if there was any) was b/c our current install now weights in at 0.5TB.

**Comment by roryk** [comment]
Should be faster now-- the upgrades are still slow, but not forever slow.
