### ISSUE TITLE
bcbio with ipython not all the submitted jobs to a cluster are completed

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2680]
Hello Team,

We have launched a torque pbs cluster with 440 cpus in compute nodes available.  Test runs for 8 jobs (ranging 30 - 96 samples) each requesting 128 cpus  were submitted, but only 5 of them got completed.  Each run involves bwa alignment, ensemble variant calling by gatk, mutect, and vardict and roughly it would take 4-6 hours to complete. By looking at the three incomplete runs, I find the the engines were not started.  Are there any time limit that bcbio ipython jobs can automatically be terminated?

**Comment by roryk** [comment]
Hi Segun,

If you look in the log file from the scheduler, I think you will see a paragraph describing what happened. In short, bcbio waits for 15 minutes for the engines to start before shutting down by default. You can increase that time by passing `--timeout` to your `bcbio_nextgen.py ... ... ` call, which will make it wait that number of seconds. The reason why we have it set so low is when folks are initially getting started, a lot of times some kinks need to get worked out with the scheduler and its better for folks to not have to wait a long time to get feedback that something is wrong. If the other jobs finished then it should be working fine on your scheduler, so you can just add that `--timeout` parameter to your runs and you'll be all set.

**Comment by dauss75** [comment]
Hi Rory, 

Thanks! That  totally makes sense.  I will give another try with the parameter added.

**Comment by roryk** [comment]
Awesome-- if that gets you going, let us know and close the issue. Thanks!
