### ISSUE TITLE
Question about the variant regions and LCR 

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2686]
Hi, I have taken a look into the commands in the log folder, and found that bcbio uses `bedtools subtract` command to remove the regions overlapped in LCR. However, the variant regions displayed in the command differ a litter from those defined in the bed file by variant_regions paramter. For example, the command for chr 2 I found the command is `bedtools subtract -nonamecheck -a /ngs/zhengu/liuqf/final/vardict/chr2/liuqingfeng-chr2_29220713_211424290-regions.bed -b /bio/bcbio/genomes/Hsapiens/hg38/coverage/problem_regions/repeats/LCR.bed.gz > /ngs/zhengu/liuqf/final/bcbiotx/tmpK2Dw2J/liuqingfeng-chr2_29220713_211424290-regions-nolcr.bed`, while my regions defined in the bed file related to chr2 is 

> chr2    29192773        29921566
> chr2    211375716       212538841 

The start coordinate 29220713 locates after the first region of interest, while 211424290 locates in the middle of the second region of interest. What is the logic for the determinat of the regions? Is there any problem of my running? Thanks in advance.

**Comment by chapmanb** [comment]
Thanks for the question and sorry about the issues. The documentation describes the intentions of the LCRs and links to the original paper where they're derived:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html?highlight=lcr#analysis-regions

It's worth manually checking the LCR regions (`/bio/bcbio/genomes/Hsapiens/hg38/coverage/problem_regions/repeats/LCR.bed.gz`) to see if they're doing the removal, or if you sample doesn't have coverage in the regions of interest.

If the LCRs falling into your regions of interest, you don't need to exclude them and can avoid adding them to `exclude_regions` which should hopefully avoid this. Hope this helps.

**Comment by hliu2016** [comment]
@chapmanb 
Thanks for your prompt reply. I removed the exclude_regions parameter, i.e. using no LCRs regions, and rerun the pipeline. I found the chr2 are still split into three sub-region in the variant calling process. They are:

> chr2_0_29209876
> chr2_29220713_211424290
> chr2_211665307_242193529

I also found that the coordinates of these regions are same to those of the running used LCRs. I guess this depends on my sample coverage or other things.

**Comment by chapmanb** [comment]
Thanks for investigating. bcbio picks splits based on coverage calculations so it does sound like there is no coverage in some regions you might be expecting. You could look at either the bcbio coverage calculations from mosdepth or the BAM file itself in a viewer like IGV to confirm that it's doing the right thing. Let us know if you find any issues and hope this helps for your analysis.

**Comment by roryk** [comment]
Asked and answered.
