### ISSUE TITLE
Feature request: exclude_regions BED file

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2687]
I've just come across the `exclude_regions` configuration and got a bit confused by the `lcr` option, where it states that it "requires an organism with a defined lcr file in genome resources.". How is this meant to be set up exactly?

Would it be possible to also add support for specifying a BED file with the regions to be excluded, in a similar way to how it's done with `variant_regions` and `sv_regions`?

**Comment by naumenko-sa** [comment]
Hi @amizeranschi!

I think it is ```exclude_regions: lcr```. You can find the definition of lcr in your ```bcbio/genomes/Hsapiens/hg38-resources.yaml```

Would it be an option to generate a complementary bed file for the regions you need to exclude with 
bedtools subtract https://bedtools.readthedocs.io/en/latest/content/tools/subtract.html?
```bedtools subtract -a all_chomosomes.bed -b exclude_regions.bed > include_regions.bed```

SN

**Comment by amizeranschi** [comment]
Hi Sergey,

Thanks for the clarification with the lcr genome setup. And yes, using bedtools subtract to produce the `variant_regions` could be a simple solution to my problem.
