### ISSUE TITLE
ERROR: SIFT not available

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2690]
Hi, the VEP annotations can not run after I updated the gemini to Ensemble 95， but it works well before. The error information is as below:
```

-------------------- EXCEPTION --------------------
MSG: ERROR: SIFT not available
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::check_sift_polyphen /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:168
STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::Transcript::new /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/Transcript.pm:121
STACK Bio::EnsEMBL::VEP::CacheDir::get_all_AnnotationSources /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/CacheDir.pm:150
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:121
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:175
STACK Bio::EnsEMBL::VEP::Runner::init /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /bio/bcbio/anaconda/share/ensembl-vep-95.1-0/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel /bio/bcbio/anaconda/bin/vep:225
Date (localtime)    = Thu Feb 21 08:58:26 2019
Ensembl API version = 95
---------------------------------------------------
```

**Comment by chapmanb** [comment]
Sorry about the issues here. @matthdsm -- have you encountered this with the updates you pushed? Was SIFT removed or changed for any reason in the latest release? We'd appreciate any pointers to help debug.

**Comment by matthdsm** [comment]
Hi Brad,

No idea, I've been using vep95 since before the latest release and haven't encoutered any issues. Perhaps something went wrong during the installation of the cache?
Removing the cache and updating to the latest version (vep 95.2) could do the trick I suppose.
```
#remove cache
rm -rf  /bio/bcbio/genomes/Hsapiens/*/vep/homo_sapiens_merged/95_*/  

#update to latest stable and update tools and data
bcbio_nextgen.py upgrade --tools --data
```

I'm assuming here you're working with human data. Caches for other species do not include SIFT scores (among others).

Cheers
M

**Comment by hliu2016** [comment]
@chapmanb  @matthdsm 
Hi, I run the upgrade command `bcbio_nextgen.py upgrade --tools --data ` but failed because of installing of deepvariant package can not finished.

> Executing transaction: failed
> ERROR conda.core.link:_execute(543): An error occurred while installing package 'bioconda::deepvariant-0.7.2-py27h5d9141f_1'.
> LinkError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
> running your command again with `-v` will provide additional information
> location of failed script: /bio/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
> ==> script messages <==
> <None>
> 
> Attempting to roll back.
> 
> Rolling back transaction: done
> 
> LinkError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
> running your command again with `-v` will provide additional information
> location of failed script: /bio/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
> ==> script messages <==
> <None>
>

**Comment by chapmanb** [comment]
Sorry about the update issues with deepvariant. We've been working on making this more stable but are trying to isolate the issues that people have been hitting with the install. It's trying to download DeepVariant models and is failing for some reason, but unfortunately this doesn't give us enough information to know why. We have a thread with some additional debugging tips here:

https://github.com/bcbio/bcbio-nextgen/issues/2613

But as a first pass does retrying work? It might be running into network issues. Sorry about the problems and thanks for the help debugging.

**Comment by hliu2016** [comment]
@chapmanb 
I have run the command using -v option, and got the traceback. Hope this help your debug. 

[nohup.txt](https://github.com/bcbio/bcbio-nextgen/files/2898806/nohup.txt)

**Comment by chapmanb** [comment]
Thanks much for following up with this. It looks like your machine is timing out retrieving the DeepVariant files from Google Cloud:
```
++ /bio/bcbio/anaconda/envs/dv/bin/gsutil cp 'gs://deepvariant/models/DeepVariant/0.7.2/DeepVariant-inception_v3-0.7.2+data-wgs_standard/*' /bio/bcbio/anaconda/envs/dv/share/deepvariant-0.7.2-1/models/DeepVariant/0.7.2/DeepVariant-inception_v3-0.7.2+data-wgs_standard/
INFO 0225 07:14:57.960994 retry_util.py] Retrying request, attempt #1...
INFO 0225 07:16:00.547887 retry_util.py] Retrying request, attempt #2...
INFO 0225 07:17:05.537183 retry_util.py] Retrying request, attempt #3...
INFO 0225 07:18:15.135942 retry_util.py] Retrying request, attempt #4...
INFO 0225 07:19:29.627160 retry_util.py] Retrying request, attempt #5...
INFO 0225 07:21:01.755207 retry_util.py] Retrying request, attempt #6...
INFO 0225 07:22:33.875566 retry_util.py] Retrying request, attempt #7...
INFO 0225 07:24:05.994828 retry_util.py] Retrying request, attempt #8...
INFO 0225 07:25:38.115278 retry_util.py] Retrying request, attempt #9...
INFO 0225 07:27:10.235709 retry_util.py] Retrying request, attempt #10...
INFO 0225 07:28:42.356185 retry_util.py] Retrying request, attempt #11...
INFO 0225 07:30:14.452574 retry_util.py] Retrying request, attempt #12...
INFO 0225 07:31:46.581526 retry_util.py] Retrying request, attempt #13...
INFO 0225 07:33:18.701343 retry_util.py] Retrying request, attempt #14...
INFO 0225 07:34:50.827855 retry_util.py] Retrying request, attempt #15...
INFO 0225 07:36:22.954531 retry_util.py] Retrying request, attempt #16...
INFO 0225 07:37:55.076652 retry_util.py] Retrying request, attempt #17...
INFO 0225 07:39:27.172441 retry_util.py] Retrying request, attempt #18...
INFO 0225 07:40:59.293113 retry_util.py] Retrying request, attempt #19...
INFO 0225 07:42:31.382630 retry_util.py] Retrying request, attempt #20...
INFO 0225 07:44:03.492747 retry_util.py] Retrying request, attempt #21...
INFO 0225 07:45:35.612027 retry_util.py] Retrying request, attempt #22...
Traceback (most recent call last):
  File "/bio/bcbio/anaconda/envs/dv/share/google-cloud-sdk-235.0.0-0/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
[...]
  File "/bio/bcbio/anaconda/envs/dv/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
```
If you run the `gsutil` command quoted above outside of the install does it fail consistently in the same way? I'm not entirely sure why you can't connect and pull the file. Is there anything different about your install machine that would prevent access to Google Cloud? Thanks again for the help debugging.

**Comment by hliu2016** [comment]
@chapmanb 
I think I know the cause, because Google Cloud is blocked in China. Is there any other site to  store DeepVariant? I am sorry for my network access restriction.

**Comment by chapmanb** [comment]
Unfortunately we don't have a mirror of this, the data is hosted by the Google team on GCP. Are there any workarounds for accessing Google Cloud in China? I'm not sure about how extensive the restrictions are. If you want to manually work around you could uncomment the deepvariant line:

https://github.com/chapmanb/cloudbiolinux/blob/79f4b83bd13c318d5ed0b185e8d10974302e5ce0/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L48

from your local cloudbiolinux cache in `tmpbcbio-install/cloudbiolinux` and it'll proceed without it. I'd like to try and figure out a longer term fix but this could at least unblock your current problem. Thanks again for the patience debugging.

**Comment by hliu2016** [comment]
@chapmanb 
Thank you very much. I will try to work around deepvariant.

**Comment by hliu2016** [comment]
@chapmanb 
Thank you very much. I will try to work around deepvariant.
