### ISSUE TITLE
Adapter trimming in exomeSeq

### ISSUE THREAD

**Issue by audyavar** [bcbio/bcbio-nextgen#2694]
I am having issues with adapter contamination in tumor samples from my exomeSeq data. But I don't see an option to trim adapters in exomeSeq config files. When I add the following lines to the config file, it gives the error "yaml.scanner.ScannerError: mapping values are not allowed here
  in "/arcusdata/au/pact131_exomeseq/config/exomeseq_config.yaml"
1 trim_reads: atropos
2      adapters: [nextera2]

But I do have adapter content in more than 10% of my sequences. Is this not a high enough number where adapter trimming will be needed?
![fastqc_adapter_content_plot](https://user-images.githubusercontent.com/2364625/53278660-64d75d80-36bf-11e9-9650-1f229f805acb.png)

_Originally posted by @audyavar in https://github.com/bcbio/bcbio-nextgen/issues/308#issuecomment-466594931_

**Comment by roryk** [comment]
The error you are getting is because your YAML file is malformed, I think you might not be adding the lines in the right way. https://github.com/bcbio/bcbio-nextgen/blob/master/tests/data/automated/run_info-rnaseq.yaml#L15-L16 has an example of how they should be added.

**Comment by roryk** [comment]
Closing this as this definitely should be the problem. Hope you got it working!
