### ISSUE TITLE
scRNA-seq rapmap --selAln option

### ISSUE THREAD

**Issue by zji90** [bcbio/bcbio-nextgen#2695]
I am running scRNA-seq pipeline with rapmap and get the following message. It seems that selAln option is not turned on for rapmap. I wonder whether it should not be turned on for rapmap or this can be turned on in configuration file?

Message:
NOTE: It appears you are running rapmap without the selective-alignment (`--selAln`) option.
Selective alignment can generally improve both the sensitivity and specificity of mapping, with only a moderate increase in use of computational resources. Unless there is a specific reason to do this (e.g. testing on clean simulated data), `--selAln` is generally recommended.

**Comment by roryk** [comment]
Hi Zhicheng,

There's a couple of new flags in RapMap/Salmon that we haven't investigated the effects of setting yet, so we haven't done it. The setting seems innocuous from that message, but if you look through the Salmon/Rapmap docs there are a bunch of parameters that control that setting so it might not be as straightforward as the message suggests. It's on our list of things to look at-- we could use help investigating it. If you compare with and without that setting we'd love to know.

**Comment by zji90** [comment]
Thanks!
