### ISSUE TITLE
How to submit a bam file for gatk variant calling

### ISSUE THREAD

**Issue by handomsu** [bcbio/bcbio-nextgen#2699]
I want to call variant given the input as a bam file. I used the following command, but seems that it asked for file project1.csv. I don't know how to create this file (project1.csv). Could anyone help?
Thank you! 

./tool/bin/bcbio_nextgen.py  -w template gatk-variant project1.csv data/46-G0452.dedup.bam 
Traceback (most recent call last):
  File "./tool/bin/bcbio_nextgen.py", line 232, in <module>
    setup_info = workflow.setup(kwargs["workflow"], kwargs.pop("inputs"))
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/workflow/__init__.py", line 12, in setup
    return workflow.setup(args)
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/workflow/template.py", line 525, in setup
    project_name, metadata, global_vars, md_file = _pname_and_metadata(args.metadata)
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/workflow/template.py", line 324, in _pname_and_metadata
    raise ValueError("Did not find input metadata file: %s" % in_file)
ValueError: Did not find input metadata file: project1.csv

**Comment by lpantano** [comment]
Hi,

Maybe this link can help. It would tell you how to create the project1.csv.

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#automated-sample-configuration

The documentation is huge so it is difficult to find the right information.

I hope this helps.

Cheers

**Comment by handomsu** [comment]
Thank you Lorena, 
As I don't have any specific region, do you know how to generate such bed file? 
/path/to/regions.bed

**Comment by lpantano** [comment]
You can ignore it, the most important columns are the first two. The others are optional. 

After that command, you will need to check the yaml file is generated has the correct information, like the genome version etc.

cheers
