### ISSUE TITLE
Multiple cores

### ISSUE THREAD

**Issue by handomsu** [bcbio/bcbio-nextgen#2700]
This is my configuration, but I see bwa just uses one core. I have 128 GB machine, with 32 cores
# - jvm_opts: specify details
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 3G
    cores: 16
    jvm_opts: ["-Xms750m", "-Xmx3500m"]
  gatk:
    jvm_opts: ["-Xms500m", "-Xmx3500m"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
  qualimap:
    memory: 4g
  express:
    memory: 8g
  dexseq:
    memory: 10g
  macs2:
    memory: 8g
  seqcluster:
    memory: 8g

# Location of galaxy configuration file, which has pointers to reference data
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#reference-genome-files
galaxy_config: universe_wsgi.ini

# -- Additional options for specific integration, not required for standalone usage.

**Comment by lpantano** [comment]
Hi,

can you give us a little more information on how you are running bcbio? By default it will run only with 1 core, you need to give it extra information to run parallel processes.

More information here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html

**Comment by roryk** [comment]
No action, but looks like is probably all
