### ISSUE TITLE
population frequency

### ISSUE THREAD

**Issue by handomsu** [bcbio/bcbio-nextgen#2702]
Dear all,
I used the gatk variant template to call variant for a sample, and I want to filter the variants with low frequency in 1000 genome project. Do you know how can I do that? Seems that in the "final" directory, I have mysample-gatk-haplotype.vcf.gz files, but no information about population frequency (how frequent the variant appears in G1000 or EXAC data base)

Thank you very much

**Comment by chapmanb** [comment]
Glad your analysis ran successfully and thanks for the question. bcbio can annotate the VCF with these external databases but they are not installed by default. You can add them to your install with:
```
bcbio_nextgen.py upgrade --datatarget gemini
```
More details are here:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#customizing-data-installation

If you then re-run your analysis in place it will annotate the final called output files with these and you can query the VCF for population frequency parameters. Hope this helps.

**Comment by handomsu** [comment]
Thank you Brad, 
I ran your command, and it seems to give some error(?)
Running GGD recipe: hg38 exac 0.3
--2019-02-26 20:27:00--  http://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype/ExAC.0.3.GRCh38.vcf.gz
decompose v0.5

options:     input VCF file        -
         [s] smart decomposition   true (experimental)
Resolving ftp.ensembl.org...          [o] output VCF file       -

193.62.193.8
Connecting to ftp.ensembl.org|193.62.193.8|:80... > gsort version 0.0.6
connected.
HTTP request sent, awaiting response... 200 OK
Length: 3173088944 (3.0G) [application/x-gzip]
Saving to: ‘STDOUT’

-                     0%[                    ]  37.54K  62.0KB/s               [W::vcf_parse] contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
-                     9%[>                   ] 293.70M   381KB/s    eta 2h 20m [W::vcf_parse] contig 'chr10' is not defined in the header. (Quick workaround: index the file with tabix.)
-                    13%[=>                  ] 405.24M   416KB/s    eta 2h 10m [W::vcf_parse] contig 'chr11' is not defined in the header. (Quick workaround: index the file with tabix.)
-                    19%[==>                 ] 590.19M   455KB/s    eta 1h 55m [W::vcf_parse] contig 'chr12' is not defined in the header. (Quick workaround: index the file with tabix.)
-                    24%[===>                ] 751.50M   448KB/s    eta 1h 43m [W::vcf_parse] contig 'chr13' is not defined in the header. (Quick workaround: index the file with tabix.)
-                    26%[====>               ] 798.79M   440KB/s    eta 1h 40m [W::vcf_parse] contig 'chr14' is not defined in the header. (Quick workaround: index the file with tabix.)
-                                                   27%[==============================>                                                                                  ] 835.59M   450KB

**Comment by naumenko-sa** [comment]
@handomsu, thanks for testing and reporting, sorry about the issue. 
I introduced this one when fixing something else. @chapmanb, here is PR:
https://github.com/chapmanb/cloudbiolinux/pull/288. Could you please merge?
Sergey

**Comment by roryk** [comment]
Thanks for the fix Sergey!

**Comment by handomsu** [comment]
Seems that the command I ran, while yielding some errors while running, still finished successfully. Should I rerun the command "
bcbio_nextgen.py upgrade --datatarget gemini"?

**Comment by handomsu** [comment]
Thank you everyone, I reran the update command, and reran the pipeline, the final directory contains the following. It doesn't contain any db files created by gemini...

sample-gatk-haplotype-annotated-gemini-combine.conf  sample-gatk-haplotype-annotated-gemini.vcf.gz      sample-gatk-haplotype.vcf.gz
sample-gatk-haplotype-annotated-gemini-combine.lua   sample-gatk-haplotype-annotated-gemini.vcf.gz.tbi  sample-gatk-haplotype.vcf.gz.tbi

**Comment by chapmanb** [comment]
Glad to hear the installation and annotation work for you. By default, bcbio will only annotate the VCF with population allele frequencies so you can extract them directly from there. If you'd like a gemini database created you can do by adding:
```
tools_on: [gemini]
```
to your configuration:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html?highlight=gemini#changing-bcbio-defaults

Hope this helps.

**Comment by handomsu** [comment]
I entered the following, but seems that it doesn't produce db file for gemini
details:
- algorithm:
    aligner: bwa
    recalibrate: gatk
    tools_on: [gemini]
    variantcaller: gatk-haplotype
  analysis: variant2
  description: sample
  files:
  - /raid/sp/haprin/data/sample.dedup.bam
  genome_build: hg38
fc_name: project1
upload:
  dir: ../final

**Comment by chapmanb** [comment]
Thanks for following up. Your configuration looks correct, and if you also have the gemini data installed it should be running it. Your `log/bcbio-nextgen-debug.log` file should have a message that starts with `Not running gemini` that will provide details about why gemini gets skipped for your analysis. This would be the best way to help identify when it doesn't create the database. Thanks for the help debugging and hope this helps.

**Comment by naumenko-sa** [comment]
Hello everyone!

I think before loading variants into gemini, variants have to be annotated. I usually do:

```
effects: vep
effects_transcripts: all
tools_on:
    - gemini
    - vep_splicesite_annotations
vcfanno:
    - [my custom vcfanno config]
```

The result vcf file should have name [project]-gatk-haplotype-annotated-decomposed.vcf.gz, and have CSQ field from VEP.

Sergey
