### ISSUE TITLE
cutadapt pinned version not in python2 conda environment

### ISSUE THREAD

**Issue by rdocking** [bcbio/bcbio-nextgen#2703]
Hi there - 

  This is a followup to https://github.com/bcbio/bcbio-nextgen/issues/2649 - I ended up seeing a similar issue once I re-installed a bunch of things and upgraded to 1.1.3 . To recap quickly, when I ran the small RNA pipeline, I saw the same issue as in the linked issue - miRGe2.0 seemed convinced that the wrong version of cutadapt was being found (the version that works is cutadapt 1.16, which is the pinned version for bcbio).

  bcbio seemed to be reporting that the proper version of cutadapt was installed:

```
2019-02-26 09:15:04]{rdocking@clingen01}/projects/rdocking_prj/software/bcbio-nextgen/> bcbio_conda list cutadapt
# packages in environment at /projects/rdocking_prj/software/bcbio-nextgen/data/anaconda:
#
# Name                    Version                   Build  Channel
cutadapt                  1.16                     py27_2    bioconda
``` 

  But when I dug a bit farther, it looks like the `python2` env within the bcbio conda install had the 1.18 version installed:

```
[2019-02-26 09:44:41]{rdocking@clingen01}/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2/lib/python2.7/site-packages/cutadapt-1.18.dist-info/> head METADATA
Metadata-Version: 2.1
Name: cutadapt
Version: 1.18
Summary: trim adapters from high-throughput sequencing reads
Home-page: https://cutadapt.readthedocs.io/
```

I was able to confirm this in my other bcbio install:

```
[2019-02-26 10:21:40]{rdocking@clingen01}/projects/karsanlab/software/linux-x86_64-centos6/bcbio-stable/> bcbio_conda list -n python2 cutadapt
# packages in environment at /projects/karsanlab/software/linux-x86_64-centos6/bcbio-stable/data/anaconda/envs/python2:
#
# Name                    Version                   Build  Channel
cutadapt                  1.18             py27h14c3975_1    bioconda
```

To try resolving this, I tried installing cutadapt=1.16 explictly into the `python2` env:

```
[2019-02-26 10:18:58]{rdocking@clingen01}/projects/rdocking_prj/software/bcbio-nextgen/> bcbio_conda install -n python2 --strict-channel-priority --verbose cutadapt=1.16
```  

This seems to install the correct version of the cutadapt library that mirge2.0 is importing, and lets the small-RNA pipeline work again.

One thing I'm not sure about is whether this issue was an issue specific to my install, or if it's a more general issue for bcbio with the recent change to multiple environments. Can you confirm? Thanks!

**Comment by chapmanb** [comment]
Thanks much for the report and sorry about reintroducing this issue with the multiple environment install. Your diagnosis is exactly right, we should be putting the cutadapt pinning into the python2 environment with mirge. I pushed a fix to cloudbiolinux to do this, so if you update with:
```
bcbio_nextgen.py upgrade --tools
```
it should do the right thing by default going forward. Thanks again for the report and detailed diagnosis.
