### ISSUE TITLE
bam file problem using merged fastq files  

### ISSUE THREAD

**Issue by zzupmc** [bcbio/bcbio-nextgen#2704]
Hi, 
I have a trio undergone WES.  Each sample has one library but sequenced on two different machines, A and B. Then I merged fastq files for the same sample from A and B. I checked the resulting fastq file, the reads number equals to A+B, and read1 read2 are properly paired. Then I followed the template https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/freebayes-variant.yaml for variant calling. The resulting bam file only includes reads from A, and the bam file is not truncated. This is true for the three samples. I checked the log files, and cannot find where is the problem. I also ran bwa local not inside bcbio using the same parameter, the resulting bam file seems OK (including reads from sequencing machine A and B). 

`bwa mem -c 250 -M -t 16 -R '@RG\tID:100148-01\tPL:illumina\tPU:100148-01\tSM:100148-01' /public/home/pmi/local/share/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa ../../1shenbing/merged/100148-01_R1.fastq.gz ../../1shenbing/merged/100148-01_R2.fastq.gz |samtools view -bS -o test.bam`

thanks,
Hongen

**Comment by lpantano** [comment]
Hi,

can you share the bcbio_nextgen_commands.log from that run where you are
seeing the issue, please?

Thanks

>

**Comment by zzupmc** [comment]
please see the file below
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/2912927/bcbio-nextgen-commands.log)


thanks,
Hongen

**Comment by chapmanb** [comment]
Hongen;
How did you initially merge the A and B reads into the fastq you fed to bcbio? If you just concatenated two gzipped files (`cat A.fq.gz B.fq.gz > combined.fq.gz`) that can sometimes result in a file that looks perfectly fine but that downstream tools will not be able to read into the second file. This happens inconsistently and I'm not sure how to detect for it so always gunzip and recompress: `zcat A.fq.gz B.fq.gz | bgzip -c  > combined.fq.gz`. Hope this helps explain what is going on.

**Comment by zzupmc** [comment]
thanks. it solves the problem.

**Comment by zzupmc** [comment]
thanks. it solves the problem.
