### ISSUE TITLE
Installation: non-existent folder will not prompt a redownload of the files

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2705]
I was trying to regenerate the RNA transcript file for hg19 to workaround issue #2103, but the script from cloudbiolinux I used wiped out the whole `rnaseq` folder in my genome directory (I mean, it replaced it, but it does not contain all the required files).

Trying to force a redownload with `bcbio_nextgen.py -u skip --data --datatarget rnaseq --genomes hg19` does not fix the issue, even if the `rnaseq` folder is removed completely. It states that all data files are correctly present.

**Comment by lpantano** [comment]
Hi Lucas,

I agree this is not the desired outcome, can you check if removing the line
that contains transcripts from Hsapiens/hg19/versions.csv and re-start the
installation fix the issues?

What files are missing in the rnaseq after you used the cloudbiolinux
script?

Cheers

**Comment by lbeltrame** [comment]
The missing files were a red herring (my SSH session crashed halfway during the work). In the end I did not need to redownload things as I managed to prepare the data correctly. Follow up in #2103.
