### ISSUE TITLE
HDF5 I/O locks, Lustre, and iPython

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2707]
On current system getting below HDF5 error:

Few questions:
1.  Are HDF5 locks necessary for bcbio to work well in a parallel environment?
2.  Currently using Lustre as scratch and have set HDF5 locking to false as environment variable.
3.  Plan is to always map one job RNA-Seq or Exome-Seq to one AWS worker via SLURM, is iPython still a requirement in this context?  Thanks!

IOError: HDF5 error back trace
  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1615, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 939, in H5FD_sec2_lock
    file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented'
End of HDF5 error back trace
Unable to open/create file '/mnt/
Unable to open/create file '/mnt/fsx/bcbio-artifacts/usr/local/share/bcbio/anaconda/envs/python2/share/optitype-1.3.2-3/data/alleles.h5'

**Comment by chapmanb** [comment]
Thanks for the question and sorry about the issue. From the traceback it looks like this is an issue when running optitype for HLA calling. It's a third party tool requirement so not something bcbio is enforcing, but you'll need to work around it by either:

- Not using optitype HLA calling in your pipeline.
- Having bcbio available on a filesystem that supports HDF5 locks.

Hope one of those will work for you.
