### ISSUE TITLE
Errors with Toil v. 3.14.0 installed through Bioconda and v. 3.18.0 installed through pip

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2708]
Hello,

I posted this on Toil's GitHub page, but I thought I'd link it here as well in case anyone can help: https://github.com/DataBiosphere/toil/issues/2528

**Comment by chapmanb** [comment]
Thanks, this is a Toil issue and I'm closing it here and will follow up on the Toil issue tracker.
