### ISSUE TITLE
How to configure bcbio for Amplicon Sequencing?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2714]
Hi, I have noticed the post #922 of tuning VarDict for Amplicon sequencing. Except for the  `variant_regions` and `coverage_interval` options, I wonder if there are other special parameters should be set for Amplicon sequencing, such as demultiplexing, read clustering and barcode removal?

**Comment by matthdsm** [comment]
Hi @hliu2016 

We've been doing amplicon analysis using bcbio for a while now. Apart from setting `coverage_interval: amplicon` and `variant_regions` to a proper bed file, we do use Atropos to trim the reads. It isn't really necessary, but we noticed the demultiplex from our MiSeq does leave some barcodes behind.

Hope this helps
Cheers
M

**Comment by lbeltrame** [comment]
As @matthdsm said, nothing else special is required. I've been doing so since 2014 without particular issues. In case your library preparation kit uses UMIs, depending on the kit you may need to do some additional preprocessing before feeding data to bcbio.

**Comment by roryk** [comment]
Thanks for answering this questions everyone, it is really helpful for everyone with expertise to chime in. Sorry for not giving you props earlier, just noticed this when I went on a close the stale issues spree.
