### ISSUE TITLE
feature request: cwl - detect default bcbio_system.yaml

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2715]
Hi Brad,

Would it be possible to let the `bcbio_vm.py` executable auto-detect the `bcbio_system.yaml` file in the galaxy subdir? This way, it'd be possible to add a default input repo and default dir for reference data, without having to add extra args when invoking the script (lazy, I know).

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks much for this suggestion. The default currently is to use the installed bcbio_system.yaml if you don't specify one on the command line. Are you seeing different behavior? Happy to fix if you can describe what you're seeing when you leave the argument out and how you'd like it to work.

**Comment by matthdsm** [comment]
Hi Brad,

When calling then `bcbio_nextgen.py` the default system config is found, but when calling `bcbio_vm.py`, sourced from the `tools/bin` directory I get the following error:
```
-bash-4.2$ bcbio_vm.py cwl --systemconfig samples_1812KNO-0232/config/samples_1812KNO-0232.yaml
usage: bcbio_vm.py cwl [-h] [--systemconfig SYSTEMCONFIG]
                       [--add-container-tag ADD_CONTAINER_TAG]
                       sample_config
bcbio_vm.py cwl: error: too few arguments
-bash-4.2$ bcbio_vm.py cwl samples_1812KNO-0232/config/samples_1812KNO-0232.yaml
Traceback (most recent call last):
  File "/data/gent/vo/000/gvo00082/bcbio/tools/bin/bcbio_vm.py", line 354, in <module>
    args.func(args)
  File "/data/gent/vo/000/gvo00082/bcbio/anaconda/envs/bcbiovm/lib/python2.7/site-packages/bcbio/cwl/main.py", line 9, in run
    dirs, config, run_info_yaml = run_info.prep_system(args.sample_config, args.systemconfig)
  File "/data/gent/vo/000/gvo00082/bcbio/anaconda/envs/bcbiovm/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 1158, in prep_system
    config, config_file = config_utils.load_system_config(bcbio_system, work_dir)
  File "/data/gent/vo/000/gvo00082/bcbio/anaconda/envs/bcbiovm/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 70, in load_system_config
    (config_file, os.path.join(base_dir, "galaxy")))
ValueError: Could not find input system configuration file bcbio_system.yaml, including inside standard directory /kyukon/data/gent/vo/000/gvo00082/bcbio/anaconda/envs/galaxy
```

As far as I can see, this has something to do with the way the config is looked up based on the location of the conda env (`bcbiovm` in this case).

Cheers
M

**Comment by roryk** [comment]
Thanks, is this issue still happening with `bcbio_vm.py`? I have never used it so I'm not sure if this is intended usage or not.

**Comment by matthdsm** [comment]
It's been a while since I played around with CWL. We're on a new bcbio version now, so I'll give it a go and let you know if this still comes up.

Thanks for following up!
Cheers
M
