### ISSUE TITLE
Reference genome index error

### ISSUE THREAD

**Issue by yancylo** [bcbio/bcbio-nextgen#2716]
Hi,

I am trying to add a reference genome to bcbio *Version 1.0.9) using the following command:
```
bcbio_setup_genome.py -f hvolcanii.fa --gff3 hvolcanii.gff -i bwa -n HVolcanii -b hvds2
```
And I got the following error
```
TypeError: _index_bwa() takes exactly 2 arguments (1 given)
```

Could you let me know how I can resolve this? Thank you!

**Comment by roryk** [comment]
Heya— your bcbio version is super stale, could you upgrade it and try
again?

**Comment by roryk** [comment]
Closing this out-- I'm positive this is due to the bcbio version being super stale.

**Comment by ethanbahl** [comment]
Hi Rory,

I seem to be running into this same issue for STAR with a fresh install. Any tips?

Thanks,
Ethan


```
bcbio_setup_genome.py -f GRCm38.primary_assembly.genome.fa -g gencode.vM20.primary_assembly.annotation.gtf -i star -n Mmusculus -b mm10m20 --cores 56
```

```
Traceback (most recent call last):
  File "/path/to/bcbio_rna/bin/bcbio_setup_genome.py", line 305, in <module>
    indexed[index] = index_fn(fasta_file)
  File "/path/to/cloudbiolinux/cloudbio/biodata/genomes.py", line 441, in decorator
    return func(*args, **kwargs)
TypeError: _index_star() takes exactly 2 arguments (1 given)
```

**Comment by chapmanb** [comment]
Ethan;
Sorry about the issues. Would it be possible to upgrade to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
which I hope will fix the problem. Apologies, we're planning to push a new release in the next couple of days so that the stable version will avoid these issues. Thanks much.

**Comment by ethanbahl** [comment]
Hi Brad,

That solved the issue. Thanks!
