### ISSUE TITLE
bcbio fails to install (package nomkl not available)

### ISSUE THREAD

**Issue by eyalbenda** [bcbio/bcbio-nextgen#2717]
Trying to install bcbio_nextgen today, my installation fails due to the following error

> subprocess.CalledProcessError: Command '/home/ebendavid/bcbio/anaconda/bin/conda create --no-default-packages -y --name python3 python=3 nomkl' returned non-zero exit status 1
> Traceback (most recent call last):
>   File "bcbio_nextgen_install.py", line 287, in <module>
>     main(parser.parse_args(), sys.argv[1:])
>   File "bcbio_nextgen_install.py", line 44, in main
>     subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
>   File "/home/ebendavid/anaconda25/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/home/ebendavid/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--cores', '22', '--tooldir', '/home/ebendavid/bcbio/tools', '-u', 'stable', '--aligners', 'hisat2', '--aligners', 'minimap2', '--aligners', 'bwa', '--aligners', 'star', '--aligners', 'bowtie2', '--genomes', 'hg38', '--genomes', 'sacCer3', '--genomes', 'TAIR10', '--genomes', 'WBcel235', '--data']' returned non-zero exit status 1

Trying the failed command manually I get the following error:

> /home/ebendavid/bcbio/anaconda/bin/conda create --no-default-packages -y --name python3 python=3 nomkl
> Collecting package metadata: done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - nomkl
> 
> Current channels:
> 
>   - https://conda.anaconda.org/bioconda/linux-64
>   - https://conda.anaconda.org/bioconda/noarch
>   - https://conda.anaconda.org/conda-forge/linux-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://conda.anaconda.org/base/linux-64
>   - https://conda.anaconda.org/base/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. It looks like you might have adjusted your conda configuration in `~/.condarc` to exclude the `default` channel which contains `nomkl`. What does this report?
```
$ /home/ebendavid/bcbio/anaconda/bin/conda config --show channels
channels:
  - defaults
```
If you add `defaults` back into the channels if you're custom configuring in some way, that should hopefully resolve the issue. Thanks again.

**Comment by eyalbenda** [comment]
Thanks, you were right! This was a last ditch effort to make my regular conda less slow, didn't think it affected bcbio as well.
