### ISSUE TITLE
cromwell torque arg issue

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2718]
Hi Brad,

I'm running into the following issue when using CWL with Torque:
```
qsub: -d arg is longer than 256 characters
```

Apparently, the path to the workdir used by cromwell is too long.. 🙄
Do you know any tricks to shorten the path?(Aside from starting the jobs from a dir with a shorter path)

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks much for the report and sorry about this issue. Unfortunately I don't know how to adjust this other than shorter directory paths. You could ask the Torque community if this is a hard limit or adjustable, and that might be the best place to start. Re-architecting Cromwell work directory paths seems like a bigger project, although you could ask on their issue tracker as well. Sorry to not have a good idea but hope this helps.

**Comment by matthdsm** [comment]
Hi Brad
No problem, I just wanted to check if you've encountered this before.

Thanks anyway!
Cheers
M
