### ISSUE TITLE
bcbio_nextgen.py fails to install, run output from install  looks like a success

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2720]
after installation with bcbio_nextgen_install.py /mnt/fsx/usr/local/share/bcbio --tooldir=/mnt/fsx/usr/local --genomes hg38

there is actually no bcbio_nextgen.py file in ..anaconda/bin . the link in ../usr/local points to a file that doesnt exits

[root@ip-10-0-3-59 bin]# ./bcbio_nextgen.py
bash: ./bcbio_nextgen.py: No such file or directory
[root@ip-10-0-3-59 bin]# ls -l bcbio_nextgen.py 
lrwxrwxrwx 1 root root 60 Mar 11 09:42 bcbio_nextgen.py -> /mnt/fsx/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py
[root@ip-10-0-3-59 bin]# ls -l /mnt/fsx/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py
ls: cannot access /mnt/fsx/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py: No such file or directory
[root@ip-10-0-3-59 bin]# 

end of output from successful run below

  inflating: data/GRCh38.86/sequence.19.bin
  inflating: data/GRCh38.86/sequence.1.bin
  inflating: data/GRCh38.86/sequence.20.bin
  inflating: data/GRCh38.86/sequence.21.bin
  inflating: data/GRCh38.86/sequence.22.bin
  inflating: data/GRCh38.86/sequence.2.bin
  inflating: data/GRCh38.86/sequence.3.bin
  inflating: data/GRCh38.86/sequence.4.bin
  inflating: data/GRCh38.86/sequence.5.bin
  inflating: data/GRCh38.86/sequence.6.bin
  inflating: data/GRCh38.86/sequence.7.bin
  inflating: data/GRCh38.86/sequence.8.bin
  inflating: data/GRCh38.86/sequence.9.bin
  inflating: data/GRCh38.86/sequence.bin
  inflating: data/GRCh38.86/sequence.X.bin
  inflating: data/GRCh38.86/sequence.Y.bin
  inflating: data/GRCh38.86/snpEffectPredictor.bin
 extracting: data/GRCh38.86/cytoBand.txt.gz
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.
Finished: bcbio-nextgen, tools and data installed
 Genome data installed in:
  /mnt/fsx/usr/local/share/bcbio
 Tools installed in:
  /mnt/fsx/usr/local
 Ready to use system configuration at:
  /mnt/fsx/usr/local/share/bcbio/galaxy/bcbio_system.yaml
 Edit configuration file as needed to match your machine or cluster
[root@ip-10-0-3-59 bcbio]# cd /mnt/fsx/usr/local/share/bcbio

**Comment by chapmanb** [comment]
Sorry about this issue. bioconda and conda-forge recently did a number of upgrades to package dependencies and this appears to trigger a conflict with the bcbio 1.1.3 package causing it to be removed. You can manually fix your install with:
```
./anaconda/bin/conda install -c conda-forge -c bioconda bcbio-nextgen=1.1.3
```
which will re-install 1.1.3 and downgrade the packages that caused the conflict.

The latest development version avoids this problem and an alternative for installation that avoids the manual fix step is to add: `-u development` to your install command.

Sorry about these issues. We're working to have a new release soon to avoid these problems.

**Comment by BoPeng** [comment]
Right now `-u development` leads to error

```
Installing data and third party dependencies
Traceback (most recent call last):
  File "/rsrch3/scratch/bcb/bpeng1/bcbio/anaconda/bin/bcbio_nextgen.py", line 34, in <module>
    from bcbio.setpath import prepend_bcbiopath
  File "/rsrch3/scratch/bcb/bpeng1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/setpath.py", line 8, in <module>
    from bcbio import utils
  File "/rsrch3/scratch/bcb/bpeng1/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 19, in <module>
    import toolz as tz
ImportError: No module named toolz
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 287, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/home/bpeng1/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/rsrch3/scratch/bcb/bpeng1/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/rsrch3/scratch/bcb/bpeng1/bcbio/share', '--genomes', 'GRCh37', '--genomes', 'mm10', '--aligners', 'bwa', '--aligners', 'star', '--aligners', 'bowtie2', '-u', 'development', '--data']' returned non-zero exit status 1.
```

Manually installing `toolz` leads to another bunch of similar errors.
