### ISSUE TITLE
Normalization options for bamCoverage

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2725]
Is possible to pass or set a normalization option in bamCoverage for the:
def _bam_coverage in the chip-seq pipeline? At the moment I am not sure are the bw are normalized. ?

Thanks a lot!
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks for the question. This is the current commandline used to run bamCoverage:

https://github.com/bcbio/bcbio-nextgen/blob/8e57647b6c5bf622a332c956a1c0d88e6e87e9cd/bcbio/chipseq/__init__.py#L86

and here is the documentation on different normalization options:

https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html#Read%20coverage%20normalization%20options

We currently don't have any normalization specified so it looks like it defaults to no normalization. Would it be useful for your needs to be able to pass in a custom `--normalizeUsing` parameter using `resources`? What usage would you like to see? Thanks again for this discussion.

**Comment by apastore** [comment]
Hi Brad,

I normally  use —normalizeUsing RPGC for chip-seq (but for sure other may have different preferences). So I bellied the best option would be to pass normalizeUsing as an option, but have a normalization set as default (RPKM or RPGC).

What do you think?
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks for the follow up. I don't want to change the default without more input from folks doing ChIP-seq but it does make sense to allow you to customize this as you'd like, so added a fix that will allow you to add a `resources` section to samples or runs (https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#sample-or-run-specific-resources) to specify this:
```
resources:
   bamCoverage:
     options: [—normalizeUsing, RPGC]
```
Hope this works for your needs. Thanks again for the suggestion.

**Comment by apastore** [comment]
Thanks! This is perfect!
