### ISSUE TITLE
Missing bcbio_nextgen.py after successful installation.

### ISSUE THREAD

**Issue by BoPeng** [bcbio/bcbio-nextgen#2727]
After fixing the missing download file (#2726), I was able to install bcbio-nextgen. However, the `bcbio_nextgen.py` under the tool directory is a link to a file under the installation directory, which does not exist.
```
$ ls -l /home/bpeng1/bcbio/bin/bcbio_nextgen.py 
lrwxrwxrwx. 1 bpeng1 bpeng1 73 Mar 14 01:17 /home/bpeng1/bcbio/bin/bcbio_nextgen.py -> /rhel7/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py

$ ls /rhel7/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py
ls: cannot access /rhel7/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py: No such file or directory
```

As far as I can tell, the installation process called `bcbio_nextgen upgrade` to install the resources so it must have been installed but somehow removed later. Has anyone else experienced this?

Anyway, I tried to install bcbio-nextgen individually using command

```
$ /rhel7/bcbio-nextgen/anaconda/bin/conda install bcbio-nextgen==1.1.4a -c bioconda
```
`bcbio_nextgen.py` was installed and seemed working but I am not sure if anything else is missing.

**Comment by chapmanb** [comment]
Sorry about this, the incompatibility between the bcbio 1.1.3 release and bioconda's conversion to openssl 1.1.x is causing this issue. More details are here:

https://github.com/bcbio/bcbio-nextgen/issues/2720#issuecomment-471555043

Your fix is exactly right and we're working on a new release that addresses this. Hope things are working cleanly for you now after the manual fix.
