### ISSUE TITLE
Replace firewalled git protocol with ssh in installer script

### ISSUE THREAD

**Issue by andreyto** [bcbio/bcbio-nextgen#2728]
In our organization, most destination ports are blocked for outgoing connections by the central firewall. That includes `git` protocol. This is likely the case for many other companies. 

When running the installation of the dev version `-u development`, the step that git-clones BCbio code fails with timeout. Replacing the URL with the one based on `https` protocol works fine. HTTPS is usually opened everywhere.

https://github.com/bcbio/bcbio-nextgen/blob/6425cd368115133b9dbc2baf1350cd687c98ecef/scripts/bcbio_nextgen_install.py#L26

**Comment by chapmanb** [comment]
Andrey;
Thanks much for the report and fix. It looks like Rory included a fix for this here:

https://github.com/bcbio/bcbio-nextgen/commit/5fde7ed5c581705a672a777e762f8592699dc823#diff-0fbc5ca64bdacca541df9d00ac73ce5bR26

so if you get the latest hopefully it will work cleanly in your environment. Let us know if you hit any other firewall issues and thanks again.
