### ISSUE TITLE
_work_path_to_rel_final_path in multiqc.py is very inefficient

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2729]
@LMannarino found out that some of her analyses were apparently stuck in the MultiQC step. When I looked at it, I saw that `_work_path_to_rel_final_path` does

```
if not path or not isinstance(path, str):
        return path
    upload_path = None
    for work_path, final_path in upload_path_mapping.items():
        if os.path.isfile(work_path) and path == work_path:
            upload_path = final_path
        elif os.path.isdir(work_path) and path.startswith(work_path):
upload_path = path.replace(work_path, final_path)
```

In this case in `_save_uploaded_file_list`, it tests 2184 paths, and the map contains 4268 keys. This means that it will do 4268 * 2184 `stat` calls = 9321312 total calls.

In my specific case, since the filesystem is currently under pressure, it means that a single call of this function will take 10 seconds. Assuming the same for all the elements, this means 364 hours (!!!).

It is inefficient because the paths (`isfile` and `isdir`) are checked every time for each path that is being tested, while the keys of `upload_path_mapping` will not change during this iteration. It should be somehow cached to avoid repeatedly hitting the filesystem.

**Comment by lbeltrame** [comment]
At the very least, if it assumes a single hit in all the mapping, it should `break` early if found.

**Comment by chapmanb** [comment]
Luca;
Thanks for the report and investigation, and apologies for the issue. I've pushed a speculative fix which swaps around the checks so the isfile and isdir checks will only happen on matches, which I think should greatly reduce the number of filesystem calls. Let us know if this doesn't help and we can investigate other approaches like caching or breaking early. Thanks again.

**Comment by lbeltrame** [comment]
You've been too fast ;) I have a PR ready to submit that should probably reduce the number of calls to almost non existent, taking the advantage that the mapping is a dictionary.

I'll put it up in the next few minutes.
