### ISSUE TITLE
GEMINI data not updated?

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2733]
It looks like the GEMINI data were not updated:

```
IOError: Gemini cannot open this annotation file: /opt/bcbio/gemini_data/dbsnp.151.20180423.tidy.vcf.gz.
```

This makes it non-functional, because the program was updated, but the data files weren't. `upgrade --data --datatarget gemini` will not download the new data, suggesting it needs an update.

**Comment by chapmanb** [comment]
Luca;
Thanks for the report. The latest bcbio versions moved to using the vcfanno/vcf2db based approach for gemini annotations to synchronize across build 37 and 38 with annotations supported. As a result it no longer automatically runs the gemini update for the old approach. You can run:
```
gemini update --dataonly
```
to re-sync those if you're using the older approach for running, but we don't do it by default to prevent all the duplicated larger files. Hope that fixes it for you.

**Comment by lbeltrame** [comment]
I did exactly that, mainly because I've had a few issues with vcf2db in the past. This works for now, thanks.
