### ISSUE TITLE
Feature request: Automatic BAM-to-CRAM conversion

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2734]
Can we add an option to convert BAM output files into CRAM automatically? BAM-to-CRAM conversion is already supported in bcbio (see [`cram.py`](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/bam/cram.py)), but as far as I can tell there's no way to set this to run automatically for the RNA-seq pipeline.

**Comment by roryk** [comment]
Heya, we probably won't implement this unless more people ask for it. Can you just do it downstream?

**Comment by mjsteinbaugh** [comment]
Ah OK, I'm seeing that this is supported as a [post-processing step](https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#post-processing).

From the [`run_info-bam.yaml`](https://github.com/bcbio/bcbio-nextgen/blob/master/tests/data/automated/run_info-bam.yaml) unit test, for example:

```
# `cram` or `cram-lossless`
details:
  - algorithm:
      archive: cram-lossless
```

**Comment by mjsteinbaugh** [comment]
Hey @roryk yeah I can run it downstream, I was just wondering if it's easy to config directly in the bcbio YAML.

**Comment by roryk** [comment]
I see, have you tried setting that option and seeing if it saves the BAM files that way?

**Comment by mjsteinbaugh** [comment]
I haven't yet but I'm going to be reprocessing some old RNA-seq data next week and can give it a shot. I'll try to post an update here.

**Comment by roryk** [comment]
Heya-- did this end up working?

**Comment by mjsteinbaugh** [comment]
@roryk Haven't had a chance to work on this yet but I'll keep it on my todo list

**Comment by matthdsm** [comment]
Hi,

I can confirm the `archive` option works, we use it on the daily without any issues.
Cheers
M

**Comment by roryk** [comment]
Hi @matthdsm,

Thank you for answering! The best kind of feature request: one that is already implemented.

**Comment by mjsteinbaugh** [comment]
Nice thanks @matthdsm ! I'll try that out
