### ISSUE TITLE
Running qualimap_full ignores the temporary directory 

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2735]
NOTE: This is partially a guess from a failed analysis. 

Some RNAseq runs started to fail due to lack of disk space, although the nodes of the cluster they run on have plenty of scratch space. In fact, the monitoring system warned about disk usage of a different mountpoint.

Upon inspection, `/tmp` was full of temporary BAM files, which ended up then on the system disks and even filled them.  This was caused by `qualimap_full` being run on them. I'm not sure whether it is a bug in qualimap or in bcbio, but qualimap should use the defined `tmp` directory from `bcbio_system.yaml` even for temporary files, in the same manner other tools do.

**Comment by chapmanb** [comment]
Luca -- apologies about the issue and thanks for the diagnosis. I pushed a fix to qualimap to use the bcbio local temporary directory via the standard `java.io.tmpdir` flag which will hopefully fix this problem. Please let us know if you have any other problems. Thanks again.
