### ISSUE TITLE
TypeError: can only concatenate list (not "zip") to list

### ISSUE THREAD

**Issue by jessie-wangjie** [bcbio/bcbio-nextgen#2747]
File "anaconda/lib/python3.6/site-packages/bcbio/pipeline/run_info.py", line 243, in _fill_validation_targets
    for vtarget in [list(xs) for xs in [["validate"], ["validate_regions"], ["variant_regions"]] + sv_targets]:
TypeError: can only concatenate list (not "zip") to list

**Comment by roryk** [comment]
Thanks, sorry we have a bunch of python3 migration issues and this is one of them-- python3 makes a zip object which isn't treated as a list, so we have to coerce it to a list first. We should have a new release soon with these fixes.
