### ISSUE TITLE
hg38 error re: 1.1.4 install

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2749]
A generic hg38 error on an upgrade (see below).  Any insight much appreciated thanks!

root@ip-10-0-0-44 bcbioadmin]# bcbio_nextgen.py upgrade --data --genomes hg38 --aligners hisat2 --aligners star --aligners bwa --cores 8                    |
Upgrading bcbio                                                                                                                                              |
Upgrading bcbio-nextgen data files                                                                                                                           |
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'hg38', 'name': 'Human (hg38) full', 'indexes': ['seq', 'twobit', 'bwa', 'hisat2'], '|
annotations': ['ccds', 'capture_regions', 'coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', |
'1000g_indels', 'clinvar', 'qsignature', 'genesplicer', 'effects_transcripts', 'varpon', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'rmsk', 'mirbase'], 'val|
idation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', '
dream-syn3-crossmap', 'giab-NA12878-NA24385-somatic', 'giab-NA24143', 'giab-NA24149']}], 'genome_indexes': ['hisat2', 'star', 'bwa', 'bowtie2', 'rtg'], 'inst
all_liftover': False, 'install_uniref': False}'): Human (hg38) full                                                                                          
Updating hg38 genome resources configuration
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 105, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 349, in upgrade_bcbio_data
    _upgrade_snpeff_data(galaxy_home, args, remotes)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 418, in _upgrade_snpeff_data
    if os.path.exists(snpeff_db_dir) and _is_old_database(snpeff_db_dir, args):
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 445, in _is_old_database
    version_info = in_handle.readline().strip().split("\t")
TypeError: a bytes-like object is required, not 'str'
[root@ip-10-0-0-44 bcbioadmin]#

**Comment by chapmanb** [comment]
Thanks much for this report and sorry about the additional install problems. We just pushed a fix for this to correctly handle opening gzip files on python 3. If you re-run the upgrade:
```
bcbio_nextgen.py upgrade -u development
bcbio_nextgen.py upgrade --data
```
Hopefully it should finish cleanly for you now. Thank you again.
