### ISSUE TITLE
GATK4 variantrecalibration ressource parameter

### ISSUE THREAD

**Issue by tcezard** [bcbio/bcbio-nextgen#2757]
It seems that the `--resource` command line option in GATK variant recalibrator are not constructed correctly.
https://github.com/bcbio/bcbio-nextgen/blob/0f3667f149a5bff6a38dc743f33db6b677d3c415/bcbio/variation/gatkfilter.py#L159
The option should be `["--resource", "%s:%s %s" % (name, train_info, fname)]` 
See [the gatk doc](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.1.1.0/org_broadinstitute_hellbender_tools_walkers_vqsr_VariantRecalibrator.php)

It seems Bcbio silently falls back to hardfilter if the variant recalibration fails which might be why it's not poped up before

**Comment by chapmanb** [comment]
Timothee;
Thanks much for this report and sorry about the problem. It looks like the syntax for this changed again in the recent GATK 4.1 release (https://github.com/broadinstitute/gatk/releases/tag/4.1.0.0). The latest development version fixes to the correct new syntax and should hopefully work correctly for VQSR usage. Thank you again for identifying the issue and letting us know.
