### ISSUE TITLE
use_filtered option

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2761]
Hello Team,

In my yaml file, I use three variants and set 
 ensemble:
      numpass: 1
      use_filtered: true

With the use_filtered: true option,
one variant (9       139417376       .       CTG     TCA) called by mutect2 is marked as bad_haplotype and three variants are appeared in ensemble vcf as follows:
9       139417376       .       C       T       0.0     PASS
9       139417377       .       T       C       0.0     PASS
9       139417378       rs764758073     G       A       0.0     PASS

By looking at the bam file in IGV, I don't see any supporting mutations.

Then, I set use_filtered: false and these variants disappeared.  Could you please help me how to interpret this?

I use three variant callers to generate ensemble vcf with numpass: 1

Besides that particular mutation, here are some metrics w/ and w/o use_filtered.

use_filtered: true
SN      0       number of samples:      1
SN      0       number of records:      8054
SN      0       number of no-ALTs:      0
SN      0       number of SNPs: 7540
SN      0       number of MNPs: 0
SN      0       number of indels:       506
SN      0       number of others:       8
SN      0       number of multiallelic sites:   0
SN      0       number of multiallelic SNP sites:       0

use_filtered: false
SN      0       number of samples:      1
SN      0       number of records:      6360
SN      0       number of no-ALTs:      0
SN      0       number of SNPs: 5903
SN      0       number of MNPs: 0
SN      0       number of indels:       450
SN      0       number of others:       7
SN      0       number of multiallelic sites:   0
SN      0       number of multiallelic SNP sites:       0

I am curious about what makes the numbers different?  That seems to be huge for me between these two.

Thanks a lot!
Segun

**Comment by dauss75** [comment]
Maybe I was wrong.   It looks like the variant decomposioin was done by the vcfallelicprimitives tool.  

Could I still hear the different numbers w/ and w/o using the use_filtered option?

**Comment by chapmanb** [comment]
Thanks for the question. `use_filtered` tells the ensemble method to use all calls in the original files including those that have been soft filtered in the `FILTER` column (https://gatkforums.broadinstitute.org/gatk/discussion/1268/what-is-a-vcf-and-how-should-i-interpret-it). These are sites that the caller thinks are not correct so you generally want to exclude them. In some cases including them can be useful if you're combining multiple callers with numpass > 1, but with `numpass: 1` you will end up with all the filtered noise from all of the callers in your output.

My suggestion here is to remove `use_filtered: true` and you'll get a more useful set of variants. Hope this helps.

**Comment by dauss75** [comment]
Thanks!
