### ISSUE TITLE
Handle mirdeep crash for case when there are many potential precursors

### ISSUE THREAD

**Issue by rdocking** [bcbio/bcbio-nextgen#2762]
At this issue: 

https://github.com/lpantano/mirdeep2_core/issues/3

I figured out the underlying cause of why mirdeep2 was halting prematurely when run with large miRNA datasets. The fix is described at the linked issue - briefly, there is a hard-coded limit to the number of miRNA precursors that needs to be over-ridden to allow for processing large data sets. I'll submit a pull request that addresses the issue.

**Comment by lpantano** [comment]
thanks!
