### ISSUE TITLE
Variantanalysis c(mutect2, freebayes) crashes

### ISSUE THREAD

**Issue by thommohr** [bcbio/bcbio-nextgen#2764]
Dear developer,

sorry for showing up again - the fastq.bz2 read works, however, the pipeline now throws andother error, namely:

[2019-04-08T15:04Z] Annotate VCF file: Pt38-tumor-PD1Cell2016-WES, freebayes
[2019-04-08T15:04Z] Filtering for Pt38-tumor-PD1Cell2016-WES, freebayes
[2019-04-08T15:04Z] Prioritization for Pt38-tumor-PD1Cell2016-WES, freebayes
[2019-04-08T15:04Z] Finalizing variant calls: Pt38-tumor-PD1Cell2016-WES, mutect2
[2019-04-08T15:04Z] Calculating variation effects for Pt38-tumor-PD1Cell2016-WES, mutect2
[2019-04-08T15:04Z] Annotate VCF file: Pt38-tumor-PD1Cell2016-WES, mutect2
[2019-04-08T15:04Z] Filtering for Pt38-tumor-PD1Cell2016-WES, mutect2
[2019-04-08T15:04Z] Prioritization for Pt38-tumor-PD1Cell2016-WES, mutect2
[2019-04-08T15:04Z] multiprocessing: split_variants_by_sample
[2019-04-08T15:04Z] Timing: prepped BAM merging
[2019-04-08T15:04Z] Timing: validation
[2019-04-08T15:04Z] multiprocessing: compare_to_rm
[2019-04-08T15:04Z] Timing: ensemble calling
[2019-04-08T15:04Z] multiprocessing: combine_calls
[2019-04-08T15:04Z] Ensemble consensus calls for 1: freebayes,mutect2
[2019-04-08T15:05Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/srv/opt/bcbio/anaconda/bin:"$PATH" &&  /opt/bcbio/anaconda/bin/bcbio-variation-recall ensemble --cores=6 --numpass 2 --names freebayes,mutect2 --nofiltered /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/bcbiotx/tmpozwlo6l3/1-ensemble.vcf.gz /srv/opt/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/ensemble/1/freebayes/1-effects-annotated-filter-noeff-nomultiallelic.vcf.gz /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/ensemble/1/mutect2/1-effects-annotated-noeff-nomultiallelic.vcf.gz
                   mbcbio.variation.recall.main.main                         
                                                m...                         
                  mbcbio.variation.recall.main/#[1;33m-main            main.clj:  30
                  mbcbio.variation.recall.main/#[1;33m-main            main.clj:  33
               mbcbio.variation.recall.main/-main/#[1;33mfn            main.clj:  34
                                 mclojure.core/#[1;33mapply            core.clj: 665
                                                m...                         
           mbcbio.variation.ensemble.intersect/#[1;33m-main       intersect.clj: 116
           mbcbio.variation.ensemble.intersect/#[1;33m-main       intersect.clj: 140
   mbcbio.variation.ensemble.intersect/#[1;33mensemble-vcfs       intersect.clj:  86
mbcbio.variation.ensemble.intersect/ensemble-vcfs/#[1;33mfn       intersect.clj:  88
                                                m...                         
mbcbio.variation.variantcontext/#[1;33mwrite-vcf-w-template  variantcontext.clj: 165
mbcbio.variation.variantcontext/#[1;33mwrite-vcf-w-template  variantcontext.clj: 186
                                                m...                         
#[1;31mjava.lang.IllegalArgumentException: #[3mNo matching method writeHeader found taking 1 args for class htsjdk.variant.variantcontext.writer.VCFWriter
' returned non-zero exit status 1.

================
Anyone any hint what is going on ?
best, and thanks a lot,
Thomas

**Comment by chapmanb** [comment]
Thomas;
Sorry about the additional problems and thanks much for this report. I'm confused about what is going on, as the error message is in a part of the htsjdk and bcbio.variation.recall code that hasn't changed in a quite a while. What version of bcbio.variation.recall is in your install?
```
$ bcbio_conda list | grep bcbio-variation-recall
bcbio-variation-recall    0.2.4                         0    bioconda
```
If you have an old version, updating that with:
```
bcbio_conda install -c conda-forge -c bioconda bcbio-variation-recall
```
and re-running will hopefully run it cleanly for you. Hope this helps explain the issue.

**Comment by thommohr** [comment]
Hi chaomanb, thanks again for the quick reply. We are running bcbio-nextgen 1.1.5a in a fresh install, the version of bcbio-variation-recall is 2.40.

**Comment by chapmanb** [comment]
Thomas;
Apologies, I'm stuck on how to debug this from our side as I'm not sure what change or difference in your analysis triggers this. Are you able to reproduce by running the command by hand:
```
/opt/bcbio/anaconda/bin/bcbio-variation-recall ensemble --cores=6 --numpass 2 --names freebayes,mutect2 --nofiltered 1-ensemble.vcf.gz /srv/opt/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/ensemble/1/freebayes/1-effects-annotated-filter-noeff-nomultiallelic.vcf.gz /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/ensemble/1/mutect2/1-effects-annotated-noeff-nomultiallelic.vcf.gz
```
If so, is it possible to provide a minimal example with small input VCFs that has the same problem so we could try to reproduce? Thanks much for the help debugging.

**Comment by thommohr** [comment]
Hi Brad,

If I run the command by hand, it produces following error:

 bcbio.variation.recall.main.main                     
                                                   ...                     
                     bcbio.variation.recall.main/-main       main.clj:   30
                     bcbio.variation.recall.main/-main       main.clj:   33
                  bcbio.variation.recall.main/-main/fn       main.clj:   34
                                    clojure.core/apply       core.clj:  665
                                                   ...                     
              bcbio.variation.ensemble.intersect/-main  intersect.clj:  116
              bcbio.variation.ensemble.intersect/-main  intersect.clj:  140
      bcbio.variation.ensemble.intersect/ensemble-vcfs  intersect.clj:   82
   bcbio.variation.ensemble.vcfsample/consistent-order  vcfsample.clj:   60
                                    clojure.core/first       core.clj:   55
                                                   ...                     
                                   clojure.core/map/fn       core.clj: 2755
   bcbio.variation.ensemble.intersect/ensemble-vcfs/fn  intersect.clj:   82
   bcbio.variation.ensemble.intersect/maybe-nofiltered  intersect.clj:   69
bcbio.variation.ensemble.intersect/maybe-nofiltered/fn  intersect.clj:   69
                               bcbio.run.itx/check-run        itx.clj:  168
java.lang.Exception: Shell command failed: bcftools view -f 'PASS,.' /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/ensemble/1/freebayes/1-effects-annotated-filter-noeff-nomultiallelic.vcf.gz -O z -o /home/tmohr/1-ensemble-work/txtmp9566868756534497476/1-effects-annotated-filter-noeff-nomultiallelic-nofilter.vcf.gz
                     /home/tmohr/1-ensemble-work/txtmp9566868756534497476/run.sh: line 2: bcftools: command not found

the 1-ensemble-work directory is created in the directory the command is run from, but it is empty.
best and thanks for your help, Thomas

**Comment by roryk** [comment]
Hi @thommohr,

Could you add `/opt/bcbio/anaconda/bin` to your PATH before running? It looks like `bcftools` is not being found when it is run manually.

**Comment by thommohr** [comment]
How stupid of me, sorry. If the path is added. The error now is:

bcbio.variation.recall.main.main                         
                                                ...                         
                  bcbio.variation.recall.main/-main            main.clj:  30
                  bcbio.variation.recall.main/-main            main.clj:  33
               bcbio.variation.recall.main/-main/fn            main.clj:  34
                                 clojure.core/apply            core.clj: 665
                                                ...                         
           bcbio.variation.ensemble.intersect/-main       intersect.clj: 116
           bcbio.variation.ensemble.intersect/-main       intersect.clj: 140
   bcbio.variation.ensemble.intersect/ensemble-vcfs       intersect.clj:  86
bcbio.variation.ensemble.intersect/ensemble-vcfs/fn       intersect.clj:  88
                                                ...                         
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj: 165
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj: 186
                                                ...                         
java.lang.IllegalArgumentException: No matching method writeHeader found taking 1 args for class htsjdk.variant.variantcontext.writer.VCFWriter

**Comment by chapmanb** [comment]
Thomas;
Thanks much for helping debug. I was able to reproduce this error when using java 11. A number of java tools, including GATK and the underlying htsjdk are not yet compatible with that version and using java 8 is probably the easiest way to fix. Running:
```
bcbio_conda install -c conda-forge -c bioconda 'openjdk=8.0'
```
should get you java 8 in your bcbio environment and hopefully resolve the issue. Please let us know if this doesn't fix the problem and hope this gets your analysis finished.
