### ISSUE TITLE
would like to auto-test offline only

### ISSUE THREAD

**Issue by smoe** [bcbio/bcbio-nextgen#2775]
Debian has this principle to guarantee full use of the distribution when offline on some island (or somewhere deeply remote visiting collaborators). It hence does not allow packages that need internet access while being built. And this includes tests.

Until this gets all somewhat relaxed and rejuvenated, is there an easy way to reduce the testing to offline components only?

**Comment by roryk** [comment]
Thanks @smoe, are you talking about a debian package for bcbio? The trouble with a debian package is you won't get everything else that you need to run bcbio so having the package itself will end up being pretty useless. We are recommending to folks that they install via the automated installer which should work almost everywhere and won't require the user to have root to install.

**Comment by smoe** [comment]
I cannot help the requirement to install Debian packages as root (if not using containers / other VM tech). But I can help to bring it all to some use. Seriously, I very much support the idea of bcbio to have key workflows prepared for the masses in a way that is technically as easy as possible: It is everyone's genomic data and everyone should be put in the position to follow instructions to analyse it. And to have bcbio shipping with Debian will not be disadvantagous for your aims. There is also some technical beauty in having everything from scratch rebuilt with no separation from the Linux distribution underneath - like for all the extra effort to only have one version of every library installed. And I guess you are already sensing where this is going: Many extra eyeballs, many extra tests. How many users the package will have is a complete side issue for now. I use Conda myself on my Mac or for our University's HPC environment. This Debian package is more about bringing bcbio to new audiences - some very technical ones on one end and maybe a highschool student or pensioneer on the other.

From reading through the bcbio documentation I came to the conclusion that Debian has all the tools it needs, except for a few for interpreting structural variations (see https://blends.debian.org/med/tasks/bio) and (which may be a bit trickier) a series of libraries (https://salsa.debian.org/med-team/bcbio/blob/master/debian/TODO).  The community will address these over the next weeks. Some others are non-free and would need to be installed in just the very same way that you describe their installation today.

There are two Debian packages associated with bcbio. The first is the package 'python3-bcbio' that is very much like what you said - the bcbio Python code put into its place - pretty much useless. But there is also the package 'bcbio' that has a dependency on python3-bcbio and to about all the tools I found mentioned in your documentation - useful! It should already allow to run all the workflows of bcbio, albeit with less of a flexibility than with the non-free (and a few missing) tools/libraries added. But this yet needs to be proven by automated testing.

The immediate plan for the bcbio package in Debian is to have some core functionality with small data sets CI-tested. This should work offline. The true functionality shall be tested independently in some automated fashion, by implementing the example worklows.

**Comment by roryk** [comment]
Hi Steffen,

I see, theoretically, I'm all for it. But practically, it doesn't make very much sense for us to have a separate Debian package. The automated installer should work everywhere a Debian package would work. If we provide Debian package then we'll end up having to support, answer questions, debug issues with the packages, etc which just adds to our already overwhelmed support requests. 

There aren't really stable 'releases' of bcbio because we often find bugs in the code after release, or tools themselves upgrade and we need to update the code to keep up with it, and keeping all of that in sync is very hard. Having something with such a heavy overhead as a Debian package isn't really a great fit and it would only apply to a minority of the users. It is hard enough debugging all the library conflicts with bioconda, adding another set of problems from a different version of everything is the last thing we want to do.

Sorry again, we try to aim for saying yes to folks but this one we can't do. Thanks for all of the doc fixes and I hope you keep contributing, we need more of that,

**Comment by smoe** [comment]
Hi Rory,

> I see, theoretically, I'm all for it. But practically, it doesn't make very much sense for us to have a separate Debian package. The automated installer should work everywhere a Debian package would work. If we provide Debian package then we'll end up having to support, answer questions, debug issues with the packages, etc which just adds to our already overwhelmed support requests.

Just to prevent a missunderstanding. The packaging work is already done and Debian already ships a bcbio package since January. I am one of the package's maintainers.

> There aren't really stable 'releases' of bcbio because we often find bugs in the code after release, or tools themselves upgrade and we need to update the code to keep up with it, and keeping all of that in sync is very hard. Having something with such a heavy overhead

You pretty much describe how I think about Brew or Conda :o) Debian may be a bit formal at times, but once a package is accepted, updates are mostly instant, partly automated. No worries, really.  We also have backports.debian.org and, most underrated, snapshot.debian.org.

> as a Debian package isn't really a great fit and it would only apply to a minority of the users. It is hard enough debugging all the library conflicts with bioconda, adding another set of problems from a different version of everything is the last thing we want to do.

And you should not. Just send the disclaimer that unless installed the way your automated installer installs it all, there is no support from you. Wrt to library conflicts, it is exactly where I think the Debian packaging is most useful also to you. Identifying and communicating them back upstream is important to us - we cannot duck away into installing two versions of the same library - the soname becomes part of the package name. And you now guess why Debian is a bit behind with its Java packaging.

> Sorry again, we try to aim for saying yes to folks but this one we can't do. Thanks for all of the doc fixes and I hope you keep contributing, we need more of that,

Yes, there is at least another "s" coming to the docs :o)  I will have a look at the test routines myself for offline testing, which hopefully becomes another acceptable patch for you. And then we'll see if we cannot tweak the one or other workflow, too :o)

**Comment by roryk** [comment]
Thanks-- I didn't realize you were the package maintainer, I thought you were just trying to get the package to work. The tests under the tests directory need data in order to run so there needs to be a step in there where the data/indices get downloaded. Is there a way around that?

**Comment by smoe** [comment]
We are talking about
```
    download_data = [
        DlInfo("110106_FC70BUKAAXX.tar.gz", None, None),
        DlInfo("genomes_automated_test.tar.gz", "genomes", 34),
        DlInfo("110907_ERP000591.tar.gz", None, None),
        DlInfo("100326_FC6107FAAXX.tar.gz", None, 12),
        DlInfo("tcga_benchmark.tar.gz", None, 3),
        DlInfo("singlecell-rnaseq-test-data.tar.gz", "Harvard-inDrop", 1)
    ]
```
from http://chapmanb.s3.amazonaws.com/ as declared in bcbio/tests&conftest.py with a total of ... ~50MB maybe? If these are integral to too many tests then I shall just go and create an additional bcbio-data-tests package as a build dependency.
When I initially asked, my hope was that there would be a quick way to disable all tests with demands on these files and to only rely on what the tests/data directory https://github.com/bcbio/bcbio-nextgen/tree/master/tests/data already provides. I found that to be very impressive already.
For a quick sanity check I thought the files redistributed with the source tree may already be indicative enough.

**Comment by roryk** [comment]
I see-- having a separate data package makes sense; the tests depend on that data so you definitely need it. Yep, there are a bunch of lower level 'unit' tests in there, but they are pretty useless for the most part. The useful tests are the integration tests on mini datasets that try to make sure the tools are at least functional and giving output, our CI runs the tests in `tests/run_tests.sh`.

**Comment by chapmanb** [comment]
Steffen and Rory;
Thanks so much for looking into this. Running the full set of integration tests is going to be hard since it would require packaging of all the dependencies as well. Sticking with the unit tests, which don't require a download, or a minimal test of running the `bcbio_nextgen.py` commands like we do for bioconda (https://github.com/bioconda/bioconda-recipes/blob/5b92f92cce89058426df64641cb3404c18b36a38/recipes/bcbio-nextgen/meta.yaml#L78) should work great. Thanks again.

**Comment by smoe** [comment]
To give you a bit of an update - you were completely right with Debian missing tons of libraries. We hence placed this bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928076 and ever since package what is missing. Admittedly, I very much understimated how much work this means. It is not the number of packages but the dependencies of those packages and their dependencies that are rather diverse.

To help keeping spirits up, I digressed into packaging the [PIGx RNAseq ](https://github.com/BIMSBbioinfo/pigx_rnaseq) for which I now need to investigate some failing tests but we have something NGS workflowish with Debian at least. It seems easier to package the other workflows of theirs than to complete the work on hts-nim (for mosdepth), so it may take another while until you hear back from me.

I just learned that next ISMB is in Montreal again. How would you feel about organising an ISMB premeeting on bcbio in Boston and we then all take a train (or whatever) up north? My personal aim would be to get some stamp of approval from your side that we are properly testing (a subset of) bcbio workflows. We are not there, yet. Admittedly. But if we cannot make it within that year then we never will.

**Comment by roryk** [comment]
Thanks for the update! We definitely understand the dependency pain-- before bioconda it was a nightmare, now handling that stuff is more like a bad dream.

That's great about PIGx RNAseq-- I think a lot of RNA-seq workflows should be simpler to package up than bcbio so good idea to switch over to something more manageable. 

I'm definitely going to ISMB next year, and usually a bunch of the other folks that work on bcbio go that meeting as well. We're happy to meet up and chat and plan about bcbio for sure. Thanks for all your help improving bcbio, we super appreciate it!
