### ISSUE TITLE
A short summary on issue  #2764 mutect2 resp. freebayes crashing

### ISSUE THREAD

**Issue by thommohr** [bcbio/bcbio-nextgen#2778]
Dear community, since this may be of general interest to all

Issue  #2764 reported that mutect2 resp. freebayes crashed. The issue was tracked down by Brad to a software incompatibility in java. The command

/opt/bcbio/anaconda/jre/bin/java -version

gave:
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)

which means that anaconda seems to install java 1.8.0

However, if there is an install of a newer version of java *on the server*, the pipeline crashes. even setting BCBIO_JAVA_HOME to a java 1.8.0 directory does not ameliorate the issue.

In our case only removing the newer java versions resp. setting the java_home to java 1.8.0 resolved the issue.

bcbio-nextgen version is 1.1.5a, our server is an opensuse leap 15.1

**Comment by chapmanb** [comment]
Thomas;
Thanks for following up on this. I'm not sure how the external java is getting used in preference to the bcbio installed one. We should be adjusting the PATH to avoid this. Did you have `JAVA_HOME` set to point at your Java 11 installation? That's my guess as to how that gets preferentially used here. Does having the alternative Java on your system and unsetting that environmental variable avoid this? Thanks again for helping debug.

**Comment by roryk** [comment]
I think Brad fixed this issue, so closing it out. Thanks for the bug report!
