### ISSUE TITLE
fgbio passing multiple options

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2780]
Hello,

I am trying to pass multiple options, but passing only one (options: [--min-reads, 2]) does work so far.
Could you give me an example of what format it should be?
I thought this example would work, but didn't:
options: [--min-reads, 2, --max-reads, 500000]

**Comment by dauss75** [comment]
I thought it didn't work, but later I find that the option I provided was correct and worked.

**Comment by roryk** [comment]
Thank you for following up!
