### ISSUE TITLE
bcbio with LSF pending jobs

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2782]
Dear Bcbio team,

I ran bcbio gatk pipeline on 200 whole exome samples using LSF as scheduler. I am submitting each sample separately.

Bcbio started running for 20 samples and I have seen bcbio main job, control and engine jobs were in run state. Due to limited resources for remaining samples, jobs went to PEND state. Only main bcbio job was in run state.

After bcbio finished processing 20 samples, we have enough resources to start PEND jobs. But jobs freezed for some hours and after that it started processing.

Here is the sample configuration 
details:
- algorithm:
    aligner: bwa
    recalibrate: gatk
    variant_regions: BCBIO/v1.1.3/genomes/Hsapiens/GRCh37/coverage/capture_regions/Exome-Agilent_V6.bed
    variantcaller: [gatk-haplotype]
  analysis: variant2
  description: ‘test’
  files:
  - test_R1_001.fastq.gz
  - test_R2_001.fastq.gz
  genome_build: hs37d5
fc_name: ‘test’
resources:
  default:
    cores: 4
    jvm_opts: [-Xms5g, -Xmx15g]
upload:
  dir: test/results

Could you please suggest me how we can enable LSF pend jobs to go to RUN state immediately after its find resources?

And also I observed cpu efficiency is very low. We are reserving a lot of cpu (-n 128)  for each sample.
bcbio_nextgen.py test.yaml -t ipython -s lsf -n **128** -q normal -r "P=bcbio""

We need to submit more jobs with less number of cores. Could you please what is the optimal number of cpu we can provide?

Thanks In Advance
Fazulur Rehaman

**Comment by naumenko-sa** [comment]
Hello Fazulur!

Unfortunately, I cannot help with LSF issue, hopefully, someone from the community has experience running bcbio on LSF.
As a quick workaround, you can configure each project separately, as they are independent, and run your 200 WES as a job array, here is an example for torque scheduler:
https://github.com/naumenko-sa/cre/blob/master/bcbio.array.pbs

As for CPU per WES project, I came to 50G RAM/7 threads. I agree that on averagy you need much less RAM, especialy when using gatk4, but I had a few samples out of many that failed with less than 7G/java thread.

Sergey

**Comment by roryk** [comment]
Hi @Fazulur,

bcbio won't use all of the resources all of the time-- we try to make a compromise between queueing many jobs and using all of the resources. Each step in bcbio has several different sub-steps, and within a sub-step it may not be using all of the resources it requested but in general for each step, we ask the scheduler for appropriate resources for that job. It's hard to know what you mean by jobs freezing for many hours, but if it eventually started processing then its likely there were some steps that were running during that time.

**Comment by Fazulur** [comment]
Hi Sergey & Rory,

Thanks a lot for your comments.

@Rory I agree with you. bcbio won't use all resources at a time. And even I don't have any idea why jobs didn't start for few hours. Please let me know how you deal samples more than 100? 

And , What will be the optimal number of cores should we provide for one WGS sample to complete. Right now we are providing -n as 128 and job taking 16hours to complete the run. If we provide less core it will run for long. I feel we are reserving too many cores for one sample. 

If we run in batch it will generate only one vcf for all samples. We need gvcf for each sample. Thats why we need to run sample wise.

Here is the command i used
bcbio_nextgen.py test.yaml -t ipython -s lsf -n 128 -q normal --timeout 20000

Could you please let me know what is best way of building bcbio configuration when dealing with more than 200 samples? 

Thanks In Advance
Fazulur Rehaman

**Comment by roryk** [comment]
Hi @Fazulur,

The jobs going from PEND to RUN is controlled by your scheduler, not bcbio so I'm not sure what to suggest as it depends on how your cluster has LSF configured.

bcbio can only use cores on one machine for a single sample, so to get a single sample processed you want to ask for the maximum amount of cores on a machine. bcbio tries to figure that out already and will adjust the number of cores downward that it is using.

It is tough to give an estimate about the timing since it depends on how deep your sequencing is, how fast your compute is, how subscribed your scheduler is, how fast the hard drives are, what options you have turned on, etc. https://bcbio.wordpress.com/2014/12/19/awsbench/ has a link to some old benchmarking we did for variant calling a WGS sample and you can see there is substantial differences running the same pipeline on different hardware. All that said, 16 hours for a single WGS sample to run through sounds reasonable.

**Comment by Fazulur** [comment]
Hi @rory,

Thanks a lot for your quick response and suggestions. I will discuss with our LSF administrator regarding the issues. 
And thanks for bcbio benchmarking link, I will go through it and it will help us a lot to benchmark our data as well.

Thanks & Regards
Fazulur Rehaman

**Comment by roryk** [comment]
I'm guessing what is happening on your scheduler is you are seeing the main bcbio job running and the controller running which are the things that orchestrate the work and don't take up many resources but also don't do any actual work. The engines, which do the heavy lifting and all of the actual work, ask for more resources and so those jobs pend for a while before starting.
