### ISSUE TITLE
Upgrade tries to install nbconvert 5.3.0 and fails because it's not compatible with Tornado 6.0

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2783]
As the subject says. I tried a plain upgrade from bcbio and got the whole install in an inconsistent state because the post install scripts from conda failed, because of nbconvert 5.3.0 being incompatible with Tornado 6.x.  I'm not sure why it wasn't updated to the latest version, which is compatible. 

Now I'm trying to fix things (and dealing with conda's 40 minutes long dependency checks)... I'll report back if I find a proper solution (and see if it's a local issue or not).

**Comment by chapmanb** [comment]
Luca;
Sorry about the issue with the upgrade. tornado got removed as a bcbio dependency so I think what happened here is that you started with an older version that used it and it didn't get an upgrade or refresh to latest versions and conda ended up detecting a conflict. You should be able to remove it with `bcbio_conda uninstall tornado` which will hopefully resolve it. You could add `--force` if it tries to remove a ton of dependent packages to just get rid of it. Let us know if you're still stuck and thanks for the help debugging.
