### ISSUE TITLE
bcbio 1.1.5a fails with GATK with previously ok options re: ExomeSeq

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2784]
bcbioadmin@ip-10-0-0-44> bcbio_nextgen.py -v
1.1.5a

bcbioadmin@ip-10-0-0-44> tail bcbio-nextgen.log

[2019-04-15T16:57Z] multiprocessing: calculate_sv_bins
[2019-04-15T16:57Z] multiprocessing: calculate_sv_coverage
[2019-04-15T16:57Z] multiprocessing: normalize_sv_coverage
[2019-04-15T16:57Z] Timing: hla typing
[2019-04-15T16:57Z] multiprocessing: call_hla
[2019-04-15T16:57Z] Timing: alignment post-processing
[2019-04-15T16:57Z] multiprocessing: piped_bamprep
[2019-04-15T16:57Z] Timing: variant calling
[2019-04-15T16:57Z] multiprocessing: variantcall_sample
bcbioadmin@ip-10-0-0-44> 

***********************************************************************
A USER ERROR has occurred: p is not a recognized option
***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
Using GATK jar /mnt/fsx/share/bcbio/anaconda/share/gatk4-4.1.1.0-0/gatk-package-4.1.1.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/home/bcbioadmin/X175_exomeseq/config/bcbiotx/tmpegxznm3c -jar /mnt/fsx/share/bcbio/anaconda/share/gatk4-4.1.1.0-0/gatk-package-4.1.1.0-local.jar Mutect2 -R /mnt/fsx/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --annotation ClippingRankSumTest --annotation DepthPerSampleHC --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage --read-validation-stringency LENIENT -I /home/bcbioadmin/X175_exomeseq/config/align/X-tumor/X-tumor-sort.bam --tumor-sample X-tumor -I /home/bcbioadmin/X175_exomeseq/config/align/X-normal/X-normal-sort.bam --normal-sample X-normal -L /home/bcbioadmin/X175_exomeseq/config/mutect2/chr4/X1-chr4_64352556_112622646-regions-nolcr.bed --interval-set-rule INTERSECTION --disable-read-filter NotDuplicateReadFilter -ploidy 2 -O /home/bcbioadmin/X175_exomeseq/config/bcbiotx/tmpegxznm3c/X1-chr4_64352556_112622646-raw.vcf.gz
' returned non-zero exit status 1.X

**Comment by naumenko-sa** [comment]
Hello, @lento2002 !

Thanks for reporting and sorry about the issues.

Could you please provide a yaml configuration file from your bcbio project?

Sergey

**Comment by lento2002** [comment]
Sure, see below.  Many thanks! 
---
#fc_date: '2015-11-18'
fc_name: final
upload:
  dir: ../output
details:
- algorithm:
    aligner: 'bwa'
    trim_reads: atropos
    adapters: [illumina]
    recalibrate: false
    realign: false
    remove_lcr: true
    variantcaller: [mutect2, strelka2, varscan]
    ensemble:
      numpass: 2
    svcaller: [lumpy, manta]
    hlacaller: optitype
  analysis: variant2
  description: XX-normal
  files: [ /mnt/fsx/XXdata/XX-XX-share/XX_data/XX175.017/DNA_XX175_N_11001-017N_normal_dna_reads1.fastq.gz ,  /mnt/fsx/XXdata/XX-XX-share/XX_data/XX175.017/DNA_XX175_N_11001-017N_normal_dna_reads2.fastq.gz]
  genome_build: hg38
  metadata:
    batch: XX1
    phenotype: normal
    #sex: female
- algorithm: 
    aligner: 'bwa'
    trim_reads: atropos
    adapters: [illumina]
    recalibrate: false
    realign: false
    variantcaller: [mutect2, strelka2, varscan]
    ensemble:
      numpass: 2
    svcaller: [lumpy, manta]
    hlacaller: optitype
    remove_lcr: true 
  analysis: variant2
  description: XX-tumor
  files: [ /mnt/fsx/XXdata/XX-XX-share/XX_data/XX175.017/DNA_XX175_T_11001-017F_tumor_dna_reads1.fastq.gz,  /mnt/fsx/XXdata/XX-XX-share/XX_data/XX175.017/DNA_XX175_T_11001-017F_tumor_dna_reads2.fastq.gz]
  genome_build: hg38
  metadata:
    batch: XX1
    phenotype: tumor
    #sex: female

**Comment by naumenko-sa** [comment]
Thanks!
Could you please try to upgrade to the latest stable version (1.1.5) ( it looks like you are on 1.1.5a).

There was a change in MUTECT syntax:
https://github.com/bcbio/bcbio-nextgen/commit/bd13a5683a346a54f3dec048b23b52482109332a

SN

**Comment by roryk** [comment]
Thanks, this should definitely solve the problem so closing it.
