### ISSUE TITLE
any issues with forklifting out GATK and replacing with 3.8

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2785]
Wondering if there is any 'secret sauce' here if I were to want to 're-wire' the GATK used by bcbio to 3.8.  Currently using bcbio-version 1.1.5a.  Wondering what config files need to be modified to downgrade.

bcbioadmin@ip-10-0-0-44> ls -l gatk4-4.1.1.0-0/
total 276473
-rwxrwxr-x 1 root root     19515 Apr  3 22:19 gatk
-rw-rw-r-- 2 root root 282832421 Mar 29 22:30 gatk-package-4.1.1.0-local.jar
bcbioadmin@ip-10-0-0-44> bcbio_nextgen.py -v
1.1.5a
bcbioadmin@ip-10-0-0-44> pwd
/mnt/fsx/share/bcbio/anaconda/share
bcbioadmin@ip-10-0-0-44>

**Comment by naumenko-sa** [comment]
Hi @lento2002 !

Please try this:

1. Install gatk3.8:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#extra-software
2. Use the option: tools_off: gatk4 
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#changing-bcbio-defaults

SN

**Comment by roryk** [comment]
Thanks for the answer Sergey!
