### ISSUE TITLE
bamtofastq -> bamToFastq ?

### ISSUE THREAD

**Issue by smoe** [bcbio/bcbio-nextgen#2792]
Hello,

I observed an inconsistency in bcbio wrt the invocation of bamtofastq. It could be with the prefix "bedtools " as in

https://github.com/bcbio/bcbio-nextgen/blob/8ba6c5e7bc69aaab1ca272f66cf390f0240cf2c1/bcbio/ngsalign/bwa.py#L48

or directly as in 

https://github.com/bcbio/bcbio-nextgen/blob/8ba6c5e7bc69aaab1ca272f66cf390f0240cf2c1/bcbio/qc/viral.py#L38

which fails for me since my Linux setup is case sensitive. The invocation as bamToFastq I could not grep in bcbio. Knowing bcbio CI-tested on Linus, I must miss something. Could you please pass me a pointer? Many thanks!

This is how bamToFastq works for me:

```
$ bedtools bamtofastq

Tool:    bedtools bamtofastq (aka bamToFastq)
Version: v2.27.1
Summary: Convert BAM alignments to FASTQ files.

Usage:   bamToFastq [OPTIONS] -i <BAM> -fq <FQ>

Options:
        -fq2    FASTQ for second end.  Used if BAM contains paired-end data.
                BAM should be sorted by query name is creating paired FASTQ.

        -tags   Create FASTQ based on the mate info
                in the BAM R2 and Q2 tags.

Tips:
        If you want to create a single, interleaved FASTQ file
        for paired-end data, you can just write both to /dev/stdout:

        bedtools bamtofastq -i x.bam -fq /dev/stdout -fq2 /dev/stdout > x.ilv.fq

$ bamToFastq

Tool:    bedtools bamtofastq (aka bamToFastq)
Version: v2.27.1
Summary: Convert BAM alignments to FASTQ files.

Usage:   bamToFastq [OPTIONS] -i <BAM> -fq <FQ>
[.....]
```

**Comment by roryk** [comment]
bam2fastq is from biobambam, so it's different than the bedtools bamtofastq. This is probably failing because the tool directory is not in your PATH. Most of the places we look up specifically the bcbio-installed command and use the full path to it, but in some places we are not so you need to have the tool directory in your PATH.

**Comment by smoe** [comment]
Thank you tons.
