### ISSUE TITLE
RFC: repeat expansions

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2797]
Hi,

I hope I'm not blind but I do not see any tools in bcbio-nextgen for calling repeat expansions. I'm thinking of TREDPARSE, exSTRa, ExpansionHunter, STRetch. (ref:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6008857/ )

Are there any plans to include this functionality in the future?

**Comment by chapmanb** [comment]
Pär;
Thanks for starting this discussion. We don't have tools for repeat expansion calling in bcbio and would definitely welcome contributions if you have interest in working on this. From my perspective, a key component would be identifying test cases to use for validations and comparing different available methods. Thanks again for looking into this.

**Comment by parlar** [comment]
I'll give it a try!

**Comment by parlar** [comment]
On it. But I need to get the conda installation of ExpansionHunter 3  to work first. 

Have opened an issue: https://github.com/bioconda/bioconda-recipes/issues/14970
