### ISSUE TITLE
bcbio GitHub organization

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2798]
Hi Brad,

Since bcbio has been moved to a separate organization, are you planning on adding more people/groups?
I think it would be a good idea to create a "contributors" group, without any commit or merge rights. That way, regular contributors could get an invite which would:
- expand the visibility of bcbio, as the organization would be displayed on the users homepage.
- provide a token of appreciation to regular committers

Just an idea I've been thinking about.
Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Absolutely, definitely happy to have you included. Invite sent. Thank you for all the contributions and suggestions.

**Comment by matthdsm** [comment]
Thanks! Invite accepted!
M
