### ISSUE TITLE
Lumpy failure 

### ISSUE THREAD

**Issue by audyavar** [bcbio/bcbio-nextgen#2801]
Hello - 

I am running Lumpy within bcbio as part of the exomeseq pipeline. It seems to be failing the exomeseq pipeline. Please see the dump below. Any advice? 

  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 324, in detect_sv
    return structural.detect_sv(*args)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 205, in detect_sv
    for svdata in caller_fn(items):
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 172, in run
    lumpy_vcf, exclude_file = _run_smoove(full_bams, sr_bams, disc_bams, work_dir, items)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 62, in _run_smoove
    do.run(cmd.format(**locals()), "smoove lumpy calling", items[0])
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export TMPDIR=/mnt/fsx/scratch_home/bcbioadmin/PACT132/exomeseq/config/bcbiotx/tmpb715tth7 && smoove call --processes 16 --genotype --removepr --fasta /mnt/fsx/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --name pact-tumor-pact1-svs --outdir /mnt/fsx/scratch_home/bcbioadmin/PACT132/exomeseq/config/bcbiotx/tmpb715tth7 --exclude /mnt/fsx/scratch_home/bcbioadmin/PACT132/exomeseq/config/structural/pact-tumor/lumpy/pact-tumor-pact1-svs-smoove.genotyped-exclude.bed --excludechroms '~^GL,~^HLA,~_random,~^chrUn,~alt,~decoy,chrEBV' /mnt/fsx/scratch_home/bcbioadmin/PACT132/exomeseq/config/bcbiotx/tmpb715tth7/pact-tumor.bam /mnt/fsx/scratch_home/bcbioadmin/PACT132/exomeseq/config/bcbiotx/tmpb715tth7/pact-normal.bam
[smoove] 2019/04/25 17:48:47 starting with version 0.2.3
[smoove] 2019/04/25 17:48:47 calculating bam stats for 2 bams
[smoove] 2019/04/25 17:48:58 done calculating bam stats
[smoove] 2019/04/25 17:49:26 removed 640116 alignments out of 843674 (75.87%) with low mapq, depth > 1000, or from excluded chroms from pact-normal.split.bam in 28 seconds
[smoove] 2019/04/25 17:49:26 removed 52436 alignments out of 843674 (6.22%) that were bad interchromosomals or flanked-splitters from pact-normal.split.bam
[smoove] 2019/04/25 17:49:28 removed 80956 singletons of 151122 reads (53.57%) from pact-normal.split.bam in 1 seconds
[smoove] 2019/04/25 17:49:28 70166 reads (8.32%) of the original 843674 remain from pact-normal.split.bam
[smoove] 2019/04/25 17:50:30 removed 1208918 alignments out of 2154980 (56.10%) with low mapq, depth > 1000, or from excluded chroms from pact-normal.disc.bam in 92 seconds
[smoove] 2019/04/25 17:50:30 removed 61056 alignments out of 2154980 (2.83%) that were bad interchromosomals or flanked-splitters from pact-normal.disc.bam
[smoove] 2019/04/25 17:50:39 removed 609382 singletons and isolated interchromosomals of 885006 reads (68.86%) from pact-normal.disc.bam in 9 seconds
[smoove] 2019/04/25 17:50:39 275624 reads (12.79%) of the original 2154980 remain from pact-normal.disc.bam
[smoove] 2019/04/25 17:54:00 removed 5027236 alignments out of 8104642 (62.03%) with low mapq, depth > 1000, or from excluded chroms from pact-tumor.disc.bam in 302 seconds
[smoove] 2019/04/25 17:54:00 removed 351987 alignments out of 8104642 (4.34%) that were bad interchromosomals or flanked-splitters from pact-tumor.disc.bam
[smoove] 2019/04/25 17:54:28 removed 2012733 singletons and isolated interchromosomals of 2725419 reads (73.85%) from pact-tumor.disc.bam in 28 seconds
[smoove] 2019/04/25 17:54:28 712686 reads (8.79%) of the original 8104642 remain from pact-tumor.disc.bam
panic: no sa tag
goroutine 67398 [running]:
github.com/brentp/smoove/lumpy.getCigars(0xc00557dce0, 0xc05610bb70, 0xc05610bb78, 0x8e1724, 0xc00557dce0)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/badsplit.go:71 +0x5a1
github.com/brentp/smoove/lumpy.badSplitter(0xc00557dce0, 0xc06602d200)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/badsplit.go:120 +0x42
github.com/brentp/smoove/lumpy.remove_sketchy(0xc00010e230, 0x61, 0x3e8, 0x7ffe89c9b0b7, 0x36, 0x7ffe89c9b16a, 0x86, 0xc0002096c0, 0x7, 0x7, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/depthfilter.go:293 +0x588
github.com/brentp/smoove/lumpy.remove_sketchy_all.func1(0xc000447620, 0x3e8, 0x7ffe89c9b0b7, 0x36, 0x7ffe89c9b16a, 0x86, 0xc0002096c0, 0x7, 0x7, 0x1, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/depthfilter.go:373 +0x234
created by github.com/brentp/smoove/lumpy.remove_sketchy_all
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/depthfilter.go:371 +0x191
' returned non-zero exit status 2.

**Comment by naumenko-sa** [comment]
Hi Akshata!

I think lumpy does now work for exome data (WES). 
To call structural variants you need genomes (WGS).

SN

**Comment by chapmanb** [comment]
Akshata;
This looks like a similar problem to #2800 in that Lumpy doesn't like something about this particular sample. Specifically it is complaining about a data problem (`panic: no sa tag`). In general, lumpy can run on WES data (but won't pick up all of the events you'd get with WGS) but there is something specifically problematic about this input. Were these aligned with bcbio or in some other manner? My best suggestion would be to isolate the failing command, reproduce outside of bcbio, and see if you can debug the problem with your data. Hope this helps.

**Comment by audyavar** [comment]
Yes this sample was also run on bcbio just like the other samples. So which structural variant callers do you recommend using for WES data? Also do any of them provide copy number variations as well?

Sincerely,

Akshata

**Comment by chapmanb** [comment]
Akshata;
For exome copy number calling, we recommend using `cnvkit`. `manta` also can be a useful structural variant caller for exomes. Practically you might want to look at this sample QC and alignment to see if there are any issues with it causing the failures, especially if other callers error out on it. Hope this helps get you a useful set of calls.

**Comment by audyavar** [comment]
Thanks! CNVkit and Manta ran without any problems on all my samples in bcbio. It was only lumpy that was complaining for a couple of them. Based on all the recommendations, I will proceed to using manta and CNVkit in the future.

Does the ensemble approach also work for structural variants? Do snpeff and/or vep also annotate structural variants effectively?

Thanks for all the help. Structural variants is a new area for us.

Best

Akshata

________________________________

**Comment by naumenko-sa** [comment]
Akshata and Brad, thanks for the discussion!

It is a popular request to get SVs from exomes, just because there are so much WES data accumulated and resequencing with WGS is not easy. 

I'm interested in validating SV calling with NA12878 and HuRef with cnvkit, similarly to this validation:
https://github.com/bcbio/bcbio_validations/tree/master/huref_sv. I was not aware that lumpy calls SV with exomes, see what the authors say here https://github.com/arq5x/lumpy-sv/issues/225

In my very limited experience of calling SVs with exomes, the only tool that gave at least some results was https://atgu.mgh.harvard.edu/xhmm/tutorial.shtml, and cnvkit once picked up a deletion we were aware of before.

S.

**Comment by roryk** [comment]
Thanks for the discussion, looks like some good advice was given.
