### ISSUE TITLE
featureCounts future warning

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2805]
I'm seeing a new pandas warning pop up, related to `read_table`:

```
bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/featureCounts.py:82: FutureWarning: read_table is deprecated, us
e read_csv instead.
  df = pd.io.parsers.read_table(count_file, sep="\t", index_col=0, header=1)
```

Line 82 just needs to be updated with `pd.io.parsers.read_csv`.

**Comment by roryk** [comment]
Pull requests welcome! :)

**Comment by mjsteinbaugh** [comment]
@roryk On it! I'll test that out on one of my VMs

**Comment by roryk** [comment]
Thanks Mike!

**Comment by roryk** [comment]
I saw this existed in a bunch of other places so I went ahead and fixed them all, thanks for the heads up!
