### ISSUE TITLE
 Bus error (core dumped) 

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2809]
Hi Brad, I am receving a bus error from bcbio 1.1.4. just at the begging of the  ipython: variantcall_sample. run-ing with -n 1 avoid the issues and bcbio work fine, but If I restart I get always the same error. I have relaunch many time but I always receive the same error message. Do you have any idea how to debug this? should I update to 1.1.6 develop version ? is this stable?

sorry for all the question!

Thansk a lot!
Alessandro 

```
[2019-04-30T18:02Z] lt15: Timing: alignment post-processing
[2019-04-30T18:03Z] lt15: ipython: piped_bamprep
[2019-04-30T18:08Z] lt15: Timing: variant calling
[2019-04-30T18:09Z] lt15: ipython: variantcall_sample
/scratch/lsftmp/1556647123.8822457.shell: line 8: 45712 Bus error               (core dumped) bcbio_nextgen.py ../config/MRD.yaml -t ipython -n 128 -s lsf -q cpuqueue -r W=150:00 --timeout 999 --retries 3 -p Project_07951
```

```
-bash-4.2$ cat /scratch/lsftmp/1556647123.8822457
#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#BSUB -W 150:00
#BSUB -R "rusage[mem=32]"
#BSUB -J Project_07951

#bcbio_nextgen.py -w template --only-metadata MRD-template.yaml MRD.csv input/*.gz

cd MRD/work
bcbio_nextgen.py ../config/MRD.yaml -t ipython -n 128 -s lsf -q cpuqueue -r W=150:00 --timeout 999 --retries 3 -p Project_07951

echo all done

_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
$LSB_JOBFILENAME.shell
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
```

**Comment by apastore** [comment]
I also have tried with -n 4 and I got the same Bus error (core dumped) error.

**Comment by roryk** [comment]
Hi @apastore,

I see you have rusage=32 in your submission script, what is the units in that? bus error from schedulers is usually telling you something ran out of memory, and I'm guessing it is that.

**Comment by apastore** [comment]
Hi Rorky the unit on our cluster is GB. The submission Jobs does not get kill is still there the same is true for the controller and the engine jobs.

**Comment by roryk** [comment]
The core is dumping from the main bcbio process, so it really looks like it is that. It could also be an issue with the compute and something independent of bcbio. I would try running that process in local mode without ipython to see if I saw the same result.

**Comment by apastore** [comment]
Yes I have tried with 32GB and bcbio -n 1 option as a single lsf job and run fine. I can definitively increase the 32 GB if you think that’s the issue.

**Comment by roryk** [comment]
Hi @apastore, did that end up fixing the issue?
