### ISSUE TITLE
Uninstalling a custom genome

### ISSUE THREAD

**Issue by eyalbenda** [bcbio/bcbio-nextgen#2812]
Couldn't find it in a search. I'd like to uninstall a custom genome. I'd imagine deleting the directory will not be enough since it is referenced in various loc files throughout the program etc.
Is there an easy way to cleanly remove a genome? Would it be possible to add that to bcbio_setup_genome?

**Comment by roryk** [comment]
Hi @eyalbenda,

Just deleting the directories should be good enough, you'll have some detritus in the config files but it won't affect anything.

**Comment by eyalbenda** [comment]
Cool, thanks!
