### ISSUE TITLE
Extremely slow conda install step (--tools) during upgrade

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2814]
As the subject says, it stayed up almost 24 hours and kept on being in the "solving" phase. I can't upgrade bcbio until this step terminates, so it's kind of a problem. 

I'm sure it has to do with the botched upgrade I had last months (there are several "inconsistent" packages printed). What can I try as I do not want to wipe the installation?

**Comment by lbeltrame** [comment]
FTR, the list of inconsistent pacakges:

```
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::_nb_ext_conf==0.3.0=py27_0
  - conda-forge/linux-64::ansible==2.7.10=py36_0
  - bioconda/linux-64::bcbio-nextgen-vm==0.1.0a=py27_87
  - <unknown>/linux-64::r-rmpi==0.6_9=r351h96ca727_1000
  - bioconda/linux-64::dx-cwl==0.1.0a20180119=py27_0
  - bioconda/linux-64::arvados-cwl-runner==1.0.20160502202716=py27_0
  - defaults/linux-64::nb_conda==2.0.0=py27_0
  - conda-forge/linux-64::shade==1.28.0=py27_0
  - bioconda/linux-64::toil==3.14.0=py27_1
  - defaults/linux-64::pymc==2.3.6=np111py27_nomkl_2
  - conda-forge/linux-64::azure-mgmt==0.20.1=py27_0
  - conda-forge/linux-64::python-ironicclient==2.3.0=py27_0
  - <unknown>/linux-64::cnv_facets==0.12.1=r351_0
  - defaults/linux-64::nbpresent==3.0.2=py27_0
  - bioconda/noarch::sbg-cwl-runner==2018.11=py_0
  - bioconda/linux-64::elasticluster==0.1.3bcbio=py27_11
  - conda-forge/linux-64::azure==1.0.3=py27_0
```

**Comment by lbeltrame** [comment]
(A couple aren't part of bcbio, they were installed as extras)

**Comment by chapmanb** [comment]
Luca;
Apologies for the slowness. We don't have a lot of control over this from the bcbio side, if things get in an inconsistent state it can take the solver a long time to resolve. The options are to wait it out, re-install just the tools from scratch, or to try custom `bcbio_conda` installs for problematic packages. It looks like your bcbio environment has a lot of extra packages and specifically having bcbio-vm in the same environment with bcbio will introduce a number of extra dependencies. Is it possible to remove bcbio-vm and the associated dependencies from the base environment and either install it into a custom environment or separate conda repository (https://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html?highlight=bcbio-nextgen-vm#install-bcbio-vm-with-a-local-bcbio)? Sorry about the conda issues and hope this helps.

**Comment by lbeltrame** [comment]
bcbio_vm is likely a leftover from my early experiments with CWL, before the separate environment. I'll try to clean it up and report.

**Comment by roryk** [comment]
Thanks, there have been a bunch of speedups with conda dependency resolutions, so upgrading, while painful, isn't as bad as it was.
