### ISSUE TITLE
ApplyBQSRSpark exits with memory error even after updating in YAML (using example exome data)

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#2821]
Hi,

Firstly thanks for all the work on this pipeline, it looks like a fantastic tool. I am trying to get this setup and running. At present I have the following error when running the example exome data "NA12878-exome-eva". 

I have tried changing the memory in bcbio_system.yaml. Initially I think it was a bit low but now in the file I set it as follows:

` gatk:
    jvm_opts: ["-Xms400m", "-Xmx40g"]`

 In the call below it is set to ` -Xms500m -Xmx22932m` which I'm guessing is plenty ? Also I notice the value here is lower than I set but I believe this is due to a downsampling done by the pipeline? Is this what is causing the issue? 

Any help would be greatly appreciated! 

edit: below is the config file. I just noticed that it only has recalibration active for the first sample. could this be causing the trouble? 

> upload:
>   dir: ../final
> details:
>   - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
>     description: NA12878-1
>     metadata:
>       sex: female
>     analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       variantcaller: [freebayes, gatk-haplotype, samtools]
>       recalibrate: gatk
>       validate: giab-NA12878/truth_small_variants.vcf.gz
>       validate_regions: giab-NA12878/truth_regions.bed
>       variant_regions: capture_regions/Exome-NGv3.bed
>       ensemble:
>         numpass: 2
>   - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
>     description: NA12878-2
>     metadata:
>       sex: female
>     analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       variantcaller: [freebayes, gatk-haplotype, samtools]
>       validate: giab-NA12878/truth_small_variants.vcf.gz
>       validate_regions: giab-NA12878/truth_regions.bed
>       variant_regions: capture_regions/Exome-NGv3.bed
>       ensemble:
>         numpass: 2
> 

Below is the output from debug.log:

> 

> 19/05/14 15:55:54 INFO BlockManagerInfo: Removed broadcast_7_piece0 on localhost:41236 in memory (size: 207.5 KB, free: 11.8 GB)
> 19/05/14 15:59:39 INFO SparkUI: Stopped Spark web UI at http://localhost:4040
> 19/05/14 15:59:39 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
> 19/05/14 15:59:41 INFO MemoryStore: MemoryStore cleared
> 19/05/14 15:59:41 INFO BlockManager: BlockManager stopped
> 19/05/14 15:59:41 INFO BlockManagerMaster: BlockManagerMaster stopped
> 19/05/14 15:59:41 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
> 
> 19/05/14 15:59:41 INFO SparkContext: Successfully stopped SparkContext
> 
> 15:59:41.929 INFO  ApplyBQSRSpark - Shutting down engine
> 
> [May 14, 2019 3:59:41 PM UTC] org.broadinstitute.hellbender.tools.spark.ApplyBQSRSpark done. Elapsed time: 20.63 minutes.
> Runtime.totalMemory()=14418968576
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
> 	at htsjdk.samtools.AbstractBAMFileIndex.query(AbstractBAMFileIndex.java:274)
> 	at htsjdk.samtools.CachingBAMFileIndex.getQueryResults(CachingBAMFileIndex.java:159)
> 	at htsjdk.samtools.BAMIndexMerger.processIndex(BAMIndexMerger.java:43)
> 	at htsjdk.samtools.BAMIndexMerger.processIndex(BAMIndexMerger.java:16)
> 	at org.disq_bio.disq.impl.file.IndexFileMerger.mergeParts(IndexFileMerger.java:90)
> 	at org.disq_bio.disq.impl.formats.bam.BamSink.save(BamSink.java:132)
> 	at org.disq_bio.disq.HtsjdkReadsRddStorage.write(HtsjdkReadsRddStorage.java:225)
> 	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:155)
> 	at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSink.writeReads(ReadsSparkSink.java:120)
> 	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:361)
> 	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:349)
> 	at org.broadinstitute.hellbender.tools.spark.ApplyBQSRSpark.runTool(ApplyBQSRSpark.java:90)
> 	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:528)
> 	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:31)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
> 	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
> 	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
> 	at org.broadinstitute.hellbender.Main.main(Main.java:291)
> 19/05/14 15:59:41 INFO ShutdownHookManager: Shutdown hook called
> 19/05/14 15:59:41 INFO ShutdownHookManager: Deleting directory /shared/pipeline-user/examples/NA12878-exome-eval/work/bcbiotx/tmprk0b_ltt/spark-735cbfb2-e5b6-4d66-932d-e6020241a7f5
> Using GATK jar /shared/pipeline-user/bcbio/anaconda/share/gatk4-4.1.2.0-1/gatk-package-4.1.2.0-local.jar
> Running:
>     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms500m -Xmx22932m -Djava.io.tmpdir=/shared/pipeline-user/examples/NA12878-exome-eval/work/bcbiotx/tmprk0b_ltt -jar /shared/pipeline-user/bcbio/anaconda/share/gatk4-4.1.2.0-1/gatk-package-4.1.2.0-local.jar ApplyBQSRSpark --input /shared/pipeline-user/examples/NA12878-exome-eval/work/align/NA12878-1/NA12878-1-sort.bam --output /shared/pipeline-user/examples/NA12878-exome-eval/work/bcbiotx/tmprk0b_ltt/NA12878-1-sort-recal.bam --bqsr-recal-file /shared/pipeline-user/examples/NA12878-exome-eval/work/align/NA12878-1/NA12878-1-sort-recal.grp --static-quantized-quals 10 --static-quantized-quals 20 --static-quantized-quals 30 --spark-master local[8] --conf spark.local.dir=/shared/pipeline-user/examples/NA12878-exome-eval/work/bcbiotx/tmprk0b_ltt --conf spark.driver.host=localhost --conf spark.network.timeout=800 --jdk-deflater --jdk-inflater
> ' returned non-zero exit status 1.

**Comment by chapmanb** [comment]
Warren;
Thanks for the report and apologies about the issue. Based on the traceback, it looks like the memory issue happens during BAM index creation which is causing some issues in GATK 4.1+. See #2806 for the full discussion. We just pushed a fix for this which will hopefully handle your case as well. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run your pipeline, it should pick up at this step and hopefully work cleanly.

Practically, the `jvm_opts` settings refer to memory usage per core, rather than total (https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#tuning-core-and-memory-usage). So your settings are likely too high for your hardware which is why bcbio tries to scale them down.

Hope this helps get your analysis running.

**Comment by waemm** [comment]
Thanks Brad, really appreciate the fast response. This seems to have done the trick! I've corrected the memory settings as well.

**Comment by chapmanb** [comment]
Thanks so much for following up and confirming that worked.
