### ISSUE TITLE
bcbio hangs at "summarize fastqc" step

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#2822]
Hi,

We've had a WES variant calling run hang repeatedly at the "summarize fastq" step. We've tried restarting in place a few times, but it just hangs at the same point each time.

I've attached the tail of the traceback from the initial run, and the full traceback of the second attempt (subsequent attempts look much the same).

[traceback-tail.txt](https://github.com/bcbio/bcbio-nextgen/files/3184991/traceback-tail.txt)
[traceback2.txt](https://github.com/bcbio/bcbio-nextgen/files/3184992/traceback2.txt)

All the actual results are present in the work directory, but obviously it would be nicer if we could get the run to finish cleanly!

Thanks,
Bennet

**Comment by chapmanb** [comment]
Bennet;
Sorry about the issues with hanging. It's tough to tell here what process is taking a long time from just these tracebacks, as they are generic and only tell us we're working in parallel on the QC steps. Would it be possible to run with a single core (`-n 1`) and then monitor what process (if any) is running when it hangs using top? Then if you exit out with ctrl-c and post the result it should tell us specifically what step bcbio is running. Thanks much for the help debugging.

**Comment by roryk** [comment]
Closing as this hasn't gotten any action and I think this might be a cluster problem and not something with bcbio. Please re-open if the runs didn't finish or you are still seeing this issue and can provide some more feedback.
