### ISSUE TITLE
RNA-Seq Variant Caller Limitation

### ISSUE THREAD

**Issue by ssaif** [bcbio/bcbio-nextgen#2826]
From an error that was generated while processing an RNA-Seq dataset for calling variants, it seems like only one variant caller is supported at this time. I had specified VarDict and GATK 3, but will change it to VarDict only to proceed with processing and analysis, but wanted to report this.

Error message - Only one variantcaller can be run for RNA-seq at this time. Post an issue here (https://github.com/bcbio/bcbio-nextgen/issues) if this is something you need to do.

Thanks,
Sakina

**Comment by roryk** [comment]
Hi Sakina,

Thanks-- there isn't a lot of clamoring for implementing multiple callers, so we'll probably punt on doing this unless it is something that is going to come up a lot.
