### ISSUE TITLE
bam index missing error

### ISSUE THREAD

**Issue by yfukasawa** [bcbio/bcbio-nextgen#2828]
Dear all,

Thank you for maintaining this nice pipeline!
Although I'm now trying to call variants using star and GRCh37, I've encountered a bam.bai file missing issue.

> index not found for:/path/to/file/Example1_GRCh37/Example1_GRCh37_star/Example1_GRCh37.bam. Invalid argument
> [mosdepth] error alignment file must be indexed

The log file for commands does not have samtools index or whatever equivalent (I confirmed sort step).
After making index manually pipeline restarted work properly, so I feel bam index step is missing at least for my protocol. star configuration is missing index making step perhaps?

Yoshi

**Comment by naumenko-sa** [comment]
Hi Yoshinori!

Could you please share your version of bcbio and your yaml file? I ran recently several samples of RNA-seq, and they went ok.

Sergey

**Comment by yfukasawa** [comment]
Hi Sergey,

Thank you for your response!
versions is 1.1.5.

>bcbio_nextgen.py -v
>1.1.5

Re. yaml, please see below (sorry for messy indentation).
I'm trying to call somatic variants using RNA-seq to answer my friend's request.
Although I changed the ref to GRCh37, the same error happened.

> details:
>\- analysis: variant2
>  genome_build: hg38-noalt
>  description: Example1
>  files:
>    \- /path/to/R1_001.fastq.gz
>    \- /path/to/R2_001.fastq.gz
>  algorithm:
>    aligner: star
>    strandedness: unstranded
>    variantcaller:
>      somatic: vardict
>\#      quality_format: Standard
>\#      trim_reads: read_through
>\#      adapters: [truseq, polya]
>  metadata:
>    phenotype: tumor
>upload:
>  dir: /path/to/final

**Comment by roryk** [comment]
Hi @yfukasawa,

RNA-seq doesn't support tumor-normal calling at the moment-- if you have tumor normal samples, the best you can do is to call them together with GATK3 by setting:

`variantcaller: [gatk-haplotype]` and `tools_off: [gatk4]`

Id also put them in the same `batch` under the metadata.

**Comment by yfukasawa** [comment]
Hi @roryk,

Thank you for reply. Unfortunately, this is tumor only sample.
This case, GATK3 is still the best?

Thanks!

**Comment by naumenko-sa** [comment]
Hi @yfukasawa!

Generally, in validations for DNA variant calling Gatk4 is better, however, we found problems with GATK4 in RNA-seq variant calling: https://github.com/bcbio/bcbio-nextgen/issues/2410
We still don't know, why even FDR for SNPs is so low for GATK4. So we recommend using gatk3.8 to call variants in RNA-seq.  If you could shed some light at the problem, that would be a great contribution!

Sergey
