### ISSUE TITLE
where to find GATK .dict files

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2834]
Hi,

I am using the RNA-seq workflow and GATK4 for variant calling. Can you tell me where I can find all the GATK reference input files e.g. .fa, .fai and specifically the `.dict` files?

Thanks
Komal

**Comment by roryk** [comment]
Hi Komal,

I think you want to stick to GATK3 for doing RNA-seq variant calling, you can switch back to GATK3 by adding:

tools_off: [gatk4]

in the algorithm part of your YAML file.

The reference input files are wherever you installed the genomes to, in the seq folder for that genome build.

**Comment by komalsrathi** [comment]
Gotcha, I found the reference in the genomes folder. Thanks! 

As far as GATK3 vs GATK4 is concerned, I am using GATK4 because my GATK3 installation is somehow not working (the tool is correctly installed) but GATK4 is and I am opening another issue for that.
