### ISSUE TITLE
question: extra GATK args

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2837]
Hi

I have a project where I need GATK to output to basepair resolution. Is there an option to add this to the config somewhere? Or do I have to edit the code?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Would passing additional parameters to HaplotypeCaller work for you? You can use specific options (https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#sample-or-run-specific-resources) with:
```
resources:
  gatk-haplotype:
    options: [your, tweak, options]
```
I'm not entirely sure what all needs changes to provide base pair resolution. In my experience, gVCF is probably what you want in this case to strike a balance between having information at all positions and output file size. Hope this helps.

**Comment by matthdsm** [comment]
Hi Brad,

Great! Thanks, exactly what I needed!
I'm just calling about 30 SNP's and I need GATK to also output the HOM REF variants, hence the basepair resolution. Added `-ERC BP_RESOLUTION` should do the trick.

Cheers
M
