### ISSUE TITLE
bcbio v1.1.5 (stable) - tools_on: damage_filter - FileNotFoundError: 'dkfzbiasfilter.py'

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#2838]
Hi everyone,

I was running a somatic variant calling analysis on matched tumor-normal samples, using bcbio v1.1.5 (stable). I enabled `tools_on: damage_filter` in the configuration file, but bcbio apparently cannot find the `dkfzbiasfilter.py` script.

```
FileNotFoundError: [Errno 2] No such file or directory: 'dkfzbiasfilter.py': 'dkfzbiasfilter.py'
```

How could I fix this issue?

Thanks a lot!
Federico

**Comment by roryk** [comment]
Hi Federico,

We try to find the full path to executables in the code, but there are places where we've missed doing that-- this looks like one of them. If you add the `your-bcbio-install/anaconda/bin` directory to your PATH, it should pick up the executable when it runs. I'll leave this open until I fix that issue here though.

**Comment by FedericoComoglio** [comment]
Thank you, @roryk for looking into this - will do. Yes, it would be nice if this can be fixed in the next release.

**Comment by FedericoComoglio** [comment]
Hi @roryk, to follow up on this - adding `my-bcbio-install/anaconda/bin` to PATH does not seem to help. I could not find `dkfzbiasfilter.py` in this directory. Am I wrong in assuming it should be installed by default?

Thank you!
Federico

**Comment by roryk** [comment]
Thanks, if you do a `find my-bcbio-install dkfzbiasfilter.py` does that appear anywhere in that tree?

**Comment by roryk** [comment]
Thanks, I pushed a fix for this so it should find it like it finds all of the other programs, but I'm worried that somehow dkfzbias is not installed on your system.

**Comment by FedericoComoglio** [comment]
Hi @roryk,

I can find `dkfzbiasfilter.py` in `my-bcbio-install`. However, it is not located in `my-bcbio-install/anaconda/bin`

```
find my-bcbio-install -name dkfzbiasfilter.py
my-bcbio-install/anaconda/envs/python2/bin/dkfzbiasfilter.py
my-bcbio-install/anaconda/pkgs/dkfz-bias-filter-1.2.3a-py27_7/bin/dkfzbiasfilter.py
```

Thanks,
Federico

**Comment by chapmanb** [comment]
Federico;
Thanks for all the work debugging this. dkfzbiasfilter.py should get symlinked into your `/path/to/bcbio/tools/bin` PATH as well and I'm not sure why that doesn't happen during the install. I pushed a supplement to Rory's fix to lookup the path within this conda environment, which should fix your issue and avoid the problem. You could also manually symlink to make it available on your PATH if you prefer not to update. Hopefully one of these two approaches gets things working for you.

**Comment by FedericoComoglio** [comment]
Thank you, @chapmanb

**Comment by FedericoComoglio** [comment]
Hi @chapmanb and @roryk,

sorry for re-opening this issue, but I have not been able to solve it, yet. Enabling `tools_on: [damage_filter]` returns (bcbio devel 1.1.16a0, pulled on 2019.09.03):

```
    raise CmdNotFound(" ".join(map(repr, (fn.__name__ if six.PY3 else fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'dkfzbiasfilter.py' {} None
```

Could you please help me getting this to work?
Thanks a lot!

**Comment by FedericoComoglio** [comment]
To add to it, I do see a symlink in `<bcbio_installation>/tools/bin`:

`dkfzbiasfilter.py -> ../../data/anaconda/envs/python2/bin/dkfzbiasfilter.py`
