### ISSUE TITLE
run_tests.sh doesn't work for v1.1.5+

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2840]
I'm seeing this error when attempting to check my installation using `./tests/run_tests.sh rnaseq` for bcbio v1.1.5+:

```
ImportError while loading conftest '/home/mike/git/bcbio-nextgen/tests/conftest.py'.
py._path.local.LocalPath.ImportMismatchError: ('tests.conftest', '/bcbio/git/tests/conftest.py', local('/home/mike/git/bcbio-nextgen/tests/conftest.py'))
```

v1.1.3 installed on my VM works fine though -- seems to be a Python 3 issue correct?

**Comment by roryk** [comment]
I've run the tests multiple times today and there isn't an issue so I think it has something to do with yoursetup. It looks like /bcbio/git is conflicting with /home/mike/git/bcbio-nextgen/tests/conftest.py somehow.

**Comment by mjsteinbaugh** [comment]
Thanks I'll take a look at that.

**Comment by roryk** [comment]
Great! Thanks for following up, glad it was an easy fix.
