### ISSUE TITLE
missing Cufflinks output files 

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#2841]
Hello,
 I have run a RNA-Seq analysis using Cufflinks for transcripts analysis. From Cufflinks documentation _cuffdiff_ gives four FPKM tracking files named as:

- isoforms.fpkm_tracking

- genes.fpkm_tracking

- cds.fpkm_tracking

- tss.fpkm_tracking

However, I don't find _cds.fpkm_tracking_ and _tss.fpkm_tracking_ in the output folder.

Is there any reason for this?

Thanks,
Laura

**Comment by roryk** [comment]
Hi Laura, did you run bcbio to get the Cufflinks output? I think you might be on the wrong repository for Cufflinks-specific requestions.

You'll only get the CDS and TSS tracking files if your GTF input file has the TSS and CDS labelled-- I'm guessing the one you used does not.

More generally, we don't recommend using Cufflinks, it is a pretty old tool, it has been superceded by tools that perform much better. Pretty much every bake-off type paper has it performing poorly, see https://paperpile.com/shared/LS2ND5 for example.
