### ISSUE TITLE
ensemble of structural variants

### ISSUE THREAD

**Issue by audyavar** [bcbio/bcbio-nextgen#2842]
I am running somatic structural variant calling with 3 callers - lumpy, manta and cnvkit on paired tumor-normal exomeSeq samples. When bcbio finishes running, I don't get an ensemble vcf like I see for the germline and somatic snv callers. If I add the line 'ensemble: numpass: 2' below the structural variants line in the yaml file, bcbio throws an error and does not run. Am I doing something wrong here or is this functionality removed from bcbio 1.1.6? Also, structural variants is a new area for me. What are the best ways to filter and visualize structural variants from these 3 variant callers?

fc_date: '2019-02-23'
fc_name: final
upload:
  dir: ../output
details:
- algorithm:
    aligner: 'bwa'
    trim_reads: atropos
    adapters: [illumina]
    recalibrate: false
    realign: false
    remove_lcr: true
    variantcaller: 
      somatic: [mutect2, strelka2, varscan]
      germline: [varscan, gatk-haplotype, strelka2]
    ensemble:
      numpass: 2
    svcaller: [lumpy, manta, cnvkit]
    hlacaller: optitype
  analysis: variant2
  description: pact-normal
  files: [normal_dna_reads1.fastq.gz, normal_dna_reads2.fastq.gz]
  genome_build: hg38
  metadata:
    batch: batch1
    phenotype: normal
- algorithm: 
    aligner: 'bwa'
    trim_reads: atropos
    adapters: [illumina]
    recalibrate: false
    realign: false
    remove_lcr: true
    variantcaller: [mutect2, strelka2, varscan]
    ensemble:
      numpass: 2
    svcaller: [lumpy, manta, cnvkit]
    hlacaller: optitype
  analysis: variant2
  description: pact-tumor
  files: [tumor_dna_reads1.fastq.gz, tumor_dna_reads2.fastq.gz]
  genome_build: hg38
  metadata:
    batch: batch1
    phenotype: tumor

**Comment by naumenko-sa** [comment]
Hi @audyavar !

- SV calling is separate from small variant calling. Ensemble algorithm is only for small variants;
- To merge SV calls you may try metasv. (svcaller: [lumpy, manta, cnvkit, metasv]. However, it is very slow (it does the reassembly of every SV locus from the raw reads with spades. Currently, there is no good method of SV consolidation in bcbio;
- please note, that while you still can call some variants using exomes, strictly speaking, only cnvkit supports SV calling from exome data; 
- to consolidate SVs from different callers you may try to use methods described in https://www.biorxiv.org/content/10.1101/578674v1 and related articles. 

Sergey

**Comment by audyavar** [comment]
Thanks Sergey for the detailed information. Much appreciated. My plan was to stick to CNVkit only for now, glad you confirmed it.

**Comment by audyavar** [comment]
@naumenko-sa  - any ideas on how to filter the SV output from CNVkit? Most of the SVs I have obtained from our samples are IMPRECISE variants.

**Comment by amizeranschi** [comment]
@audyavar 

You can try [GATK's VariantsToTable](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.2.0/org_broadinstitute_hellbender_tools_walkers_variantutils_VariantsToTable.php) to extract the relevant fields into a tab-delimited file, then filter those as needed.
