### ISSUE TITLE
Chr22 missing in esp.vcf.gz of build hg38

### ISSUE THREAD

**Issue by mmoisse** [bcbio/bcbio-nextgen#2844]
It seems that chr22 is missing from the esp.vcf.gz file in build hg38 but not in build hg19

    bcftools view /software/local/share/bcbio/genomes/Hsapiens/hg38/variation/esp.vcf.gz chr22 | grep -v '#' | wc -l
    # 0
    bcftools view /software/local/share/bcbio/genomes/Hsapiens/hg19/variation/esp.vcf.gz chr22 | grep -v '#' | wc -l
    # 48315

**Comment by roryk** [comment]
Hi @mmoisse,

Thank you! You are right; the ESP VCF comes split into multiple VCFs which we combine into one, and it looks like somehow we missed chr22.

**Comment by roryk** [comment]
Hi @mmoisse,

I found the issue and fixed it. The ESP variants have been updated on the bucket-- if you do an update with '--data' I think it should pull in the new ones.

Alternatively, if you go into your bcbio-data/genomes/Hsapiens/hg38 directory and do:

```bash
rm variation/esp*
url=https://s3.amazonaws.com/biodata/hg38_bundle/ESP6500SI-V2-hg38.vcf.gz
mkdir -p variation
wget -c -O variation/esp.vcf.gz $url
wget -c -O variation/esp.vcf.gz.tbi $url.tbi
```

It will grab the new ones with chr22. Thanks for noticing this!
