### ISSUE TITLE
Bcbio nextgen defaults to earler version of Python

### ISSUE THREAD

**Issue by DerekWilkinson42** [bcbio/bcbio-nextgen#2845]
Hi
I installed bcbio nextgen on a Linux computer and it worked perfectly for my first project but seemed to default to Python 2 rather than Python 3 in the 2nd run and could no longer locate various packages. In the installation guide it is stated that Python 2.7 or Python 3 may be used to install nextgen but I saw a 2018 post in which Brad Chapman said nextgen did not support Python 3. I am confused by this and also by the Conda environment setup. It would help to know if a formal Conda environment needs to be set up, where Python/miniconda needs to be installed (in the Local directory?) whether this needs to be linked in some way to the bcbio directory, the best way to create all of the directories (and the order in which they should be created) and exactly how to set the PATH(s). I have repeated the installation and each time the first run is fine and the second is not. As I am not computer-savy, an "idiot-proof" guide would be great!  Grateful for any advice you can offer.

**Comment by chapmanb** [comment]
Derek;
Thanks for this report and sorry about the issues. Either python 2 or python 3 can be used for installation, and bcbio now uses python 3 in an isolated conda environment to actually run the analyses.

During the install bcbio takes care of installing a conda environment and you should only need to adjust your path to point at the install tool directory:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

Could you describe the install approach you're using? You shouldn't need a large number of manual steps, so hopefully just the script run and path adjustment are all you need.

If you're still having issues, could you please post the error message you're getting? That might give us some additional insight into what is going on. Thanks for the help debugging.

**Comment by DerekWilkinson42** [comment]
Thanks for responding so quickly, Brad.
The installation process I used is in the attached Word doc. We modified some steps when we were unable to get nextgen to install and we based these modifications on https://steinbaugh.com/posts/install-bcbio.html
I'd be grateful if you could let me know if you see any obvious mistakes before I go through the process again. 

Regards,
Derek

**Comment by DerekWilkinson42** [comment]
Forgot the word doc. Please see attached!
[bcbioInstall.docx](https://github.com/bcbio/bcbio-nextgen/files/3256644/bcbioInstall.docx)

**Comment by roryk** [comment]
Hi Derek,

The install process we use is really simple and described here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

You shouldn't have to make any modifications to anything. If the install didn't work for you, it would be helpful if you could open up an issue with the error so we can look into it. It should just work without any problems. I looked at your document and I'd just install python via apt-get if you can do that which will save you a step.

**Comment by DerekWilkinson42** [comment]
Hi Rory
Thanks for the advice.
I removed everything and started again. I used apt-get to install Python. Then I used the commands in the installation guide to install nextgen. The installation failed. Please see below. Hope you can advise.

Regards,
Derek


derek@ota-KubuntuPC:~$ sudo apt-get install python3.7  
Reading package lists... Done 
Building dependency tree        
Reading state information... Done 
python3.7 is already the newest version (3.7.1-1~18.04). 
0 to upgrade, 0 to newly install, 0 to remove and 4 not to upgrade.


wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local
  --genomes GRCh37 --aligners bwa --aligners bowtie2

derek@ota-KubuntuPC:~$ wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py 
--2019-06-05 16:56:02--  https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py 
Resolving raw.github.com (raw.github.com)... 151.101.112.133 
Connecting to raw.github.com (raw.github.com)|151.101.112.133|:443... connected. 
HTTP request sent, awaiting response... 301 Moved Permanently 
Location: https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py [following] 
--2019-06-05 16:56:02--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py 
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133 
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected. 
HTTP request sent, awaiting response... 200 OK 
Length: 13528 (13K) [text/plain] 
Saving to: ‘bcbio_nextgen_install.py’ 

bcbio_nextgen_install.py                         100%[=========================================================================================================>]  13,21K  --.-KB/s    in 0,007s   

2019-06-05 16:56:03 (1,91 MB/s) - ‘bcbio_nextgen_install.py’ saved [13528/13528] 

derek@ota-KubuntuPC:~$ python bcbio_nextgen_install.py /usr/local/share/bcbio –tooldir=/usr/local --genomes sacCer3 --aligners bwa --aligners bowtie2

derek@ota-KubuntuPC:~$ python bcbio_nextgen_install.py /usr/local/share/bcbio –tooldir=/usr/local --genomes sacCer3 --aligners bwa --aligners bowtie2 
usage: bcbio_nextgen_install.py [-h] [--cores CORES] [--tooldir TOOLDIR] 
                               [--toolplus TOOLPLUS] 
                               [--datatarget {variation,rnaseq,smallrna,gemini,cadd,vep,dbnsfp,battenberg,kraken,ericscript,gnomad}] 
                               [--genomes {GRCh37,hg19,hg38,hg38-noalt,mm10,mm9,rn6,rn5,canFam3,dm3,galGal4,phix,pseudomonas_aeruginosa_ucbpp_pa14,sacCer3,TAIR10,WBcel235,xenTro3,GRCz10,GRCz11,S
scrofa11.1,BDGP6}] 
                               [--aligners {bbmap,bowtie,bowtie2,bwa,minimap2,novoalign,rtg,snap,star,ucsc,hisat2}] 
                               [--nodata] [--isolate] [--minimize-disk] 
                               [-u {stable,development}] 
                               [--revision REVISION] 
                               [--distribution {ubuntu,debian,centos,scientificlinux,macosx}] 
                               datadir 
bcbio_nextgen_install.py: error: unrecognized arguments: –tooldir=/usr/local

**Comment by roryk** [comment]
Hi @DerekWilkinson42,

 `bcbio_nextgen_install.py: error: unrecognized arguments: –tooldir=/usr/local` is telling you the error. If you look close, you'll see there's only one dash in front of `-tooldir`, if you add another one it will work.

**Comment by DerekWilkinson42** [comment]
Thanks Rory,
Can't believe I missed that. When I left the computer yesterday it was installing all the packages. I have reached this stage before but I hope that sticking with the instructions will yield a better result this time. The computer is in a colleague's office and I will continue when it is free for further use. I'll let you know how it goes.
Thanks again,
derek

**Comment by DerekWilkinson42** [comment]
Hi again Rory

The program installed a huge amount of packages and since I forgot to change from the human to the yeast genome it also installed the yeast genome build. However, at the end it returns an error message and I see that there is still only a tmpbcbio install directory with various sub-directories.
Hope you can make more sense of it than I.

So the command was
sudo python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes GRCh37 --aligners bwa --aligners bowtie2

and the end of the blurb on the terminal reads

human_ancestor.fa.gz.fai                         100%[=========================================================================================================>]     736  --.-KB/s    in 0s      

2019-06-05 19:00:31 (16,8 MB/s) - ‘human_ancestor.fa.gz.fai’ saved [736/736]

--2019-06-05 19:00:31--  https://s3.amazonaws.com/bcbio_nextgen/human_ancestor.fa.gz.gzi
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.104.125
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.104.125|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 766344 (748K) [binary/octet-stream]
Saving to: ‘human_ancestor.fa.gz.gzi’

human_ancestor.fa.gz.gzi                         100%[=========================================================================================================>] 748,38K  1,36MB/s    in 0,5s    

2019-06-05 19:00:32 (1,36 MB/s) - ‘human_ancestor.fa.gz.gzi’ saved [766344/766344]

Running GGD recipe: GRCh37 qsignature 20140703
--2019-06-05 19:00:32--  http://downloads.sourceforge.net/project/adamajava/qsignature.tar.bz2
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://netix.dl.sourceforge.net/project/adamajava/qsignature.tar.bz2 [following]
--2019-06-05 19:00:33--  https://netix.dl.sourceforge.net/project/adamajava/qsignature.tar.bz2
Resolving netix.dl.sourceforge.net (netix.dl.sourceforge.net)... 87.121.121.2
Connecting to netix.dl.sourceforge.net (netix.dl.sourceforge.net)|87.121.121.2|:443... failed: Connection refused.
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 348, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/derek/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/derek/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/derek/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 850, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/derek/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/derek/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 4.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
derek@ota-KubuntuPC:~$

**Comment by chapmanb** [comment]
Derek;
Thanks for the detailed report and apologies for getting stuck again. It looks like there was a temporary network error retrieving one of the data packages for qSignature:
```
Connecting to netix.dl.sourceforge.net (netix.dl.sourceforge.net)|87.121.121.2|:443... failed: Connection refused.
```
If you rerun the upgrade command:
```
/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py upgrade --tooldir=/usr/local --genomes GRCh37 --aligners bwa --aligners bowtie2 --data
```
It will pick up where it left off and hopefully sourceforge will be happier and it'll continue on to finish. Hope this gets it installed for you.

**Comment by DerekWilkinson42** [comment]
Thanks Brad and Rory for the help. The trial run went perfectly and now I'm trying an ensemble call. 
Regards,
Derek

**Comment by roryk** [comment]
Great, thanks for following up!
