### ISSUE TITLE
RFE: Mutect2: use the new strand orientation bias filter in 4.1.1.0

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2846]
According to [this tutorial](https://gatkforums.broadinstitute.org/gatk/discussion/24057/how-to-call-somatic-mutations-using-gatk4-mutect2#latest) it's very useful and, according to Broad people, has not much of a performance impact and can help when handling FFPE samples.

As a downside requires one more file to track. Before I think whether to add this to bcbio, I ask, does it make sense to add this option?

**Comment by chapmanb** [comment]
Luca;
Thanks for the suggestion. I agree it does make sense to look at and would be a good complement/replacement for DKFZ bias filter for detecting potential strand bias issues due to FFPEs or prep artifacts. Thanks much for looking into this.

**Comment by roryk** [comment]
Thanks for the contribution Luca!
