### ISSUE TITLE
Strelka2: Uncaught exception with exclude_regions: [lcr]

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#2848]
Hi everyone,

I ran into the following error while calling somatic variants with strelka2 from WES data. My run was using exclude_regions: [lcr, polyx]

```
[2019-05-10T15:05Z] multiprocessing: variantcall_sample
[2019-05-10T17:01Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/mnt/data/anaconda/envs/python2/bin/python /data/[...]/work/bcbiotx/tmpyi_b0sfv/pat_met-Y_59228291_59373566-work/runWorkflow.py -m local -j 1 --quiet
' returned non-zero exit status 1.
```

This error occurred after all other chromosomes were successfully processed, and was reproducible for multiple samples, pointing to the chromosome chunk `Y_59228291_59373566`. While debugging the error, I figured that the BED files for region `Y_59228291_59373566`:

```
pat_test-chrY_57082142_57227415-raw-regions-nolcr.bed
pat_test-chrY_57082142_57227415-raw-regions-nolcr-nopolyx.bed
```

are both empty, while the unfiltered file 

```
pat_test-chrY_57082142_57227415-raw-regions-nolcr.bed
```

contains 16 regions.

Importantly, when removing the filtering of low complexity regions from the config, the process successfully completes and a valid vcf file is generated for `Y_59228291_59373566` in `work/strelka2/chrY`. 

This is therefore likely a bug. Would it be possible to check whether the input region is empty and in case, skip the call to the `runWorkflow.py` for that chunk?

Thanks a lot,
Federico

**Comment by chapmanb** [comment]
Federico;
Thanks much for the report and apologies about the issue. The latest development version of bcbio will now skip running strelka2 for a region if the BED file is empty, which hopefully will avoid your issue when including removal of LCRs. Please let us know if you run into any other problems and thanks again.

**Comment by FedericoComoglio** [comment]
@chapmanb, thank you. I will let you know if I run into any issue. When do you plan to bring this feature into the stable release?

**Comment by FedericoComoglio** [comment]
Hi @chapmanb - to follow up on this issue, I installed the latest development version of bcbio, which now correctly skips running strelka2 for the empty BED file. However, immediately after, the following error is raised:

```
FileNotFoundError: [Errno 2] No such file or directory: '/data/[...]/work/strelka2/chrY/pat_test-chrY_57082142_57227415-work/results/variants/somatic.snvs.vcf.gz'
```

It seems strelka2 is nevertheless looking for the output of the variant calling despite that region has been skipped.

How can we fix this issue?
Thanks a lot!

Federico

**Comment by chapmanb** [comment]
Federico;
Thanks for testing this out and sorry for the additional problems. It looks like I didn't correctly avoid the post-processing that only happens when you can run a workflow, causing the error you saw. Could you try updating one more time and running? Hopefully with all the additional fix in place it'll now skip and continue processing correctly. Please let us know if you have any other issues.

**Comment by FedericoComoglio** [comment]
Thanks @chapmanb - I will update immediately to the latest devel, and let you know as soon as I tested it.
