### ISSUE TITLE
dbnsfp manual outdated

### ISSUE THREAD

**Issue by mmoisse** [bcbio/bcbio-nextgen#2855]
The manual is outdated it states that

> effects Method used to calculate expected variant effects; defaults to snpEff. Ensembl variant effect predictor (VEP) is also available with support for dbNSFP and `dbscSNV`_ annotation, when downloaded using Customizing data installation. [snpeff, vep, false]

while it should same something like this:
>    vcfanno: [dbnsfp, dbscsnv]

**Comment by roryk** [comment]
Thanks, it is helpful to have folks looking at and fixing the documentation. For this one, though, these are two different, but related steps-- the effects prediction does the actual predicting of the effects. vcfanno layers extra metadata about the variants on top of the effects predictor. The manual looks right to me!

**Comment by mmoisse** [comment]
But reading the manual it suggest that when installing dbNSFP or dbscSNV, VEP will automatically add the info from these two databases to the vcf file, while it does not do so.

> VEP will use dbNSFP for annotation of VCFs if included.

**Comment by chapmanb** [comment]
Thanks for the feedback and sorry about the confusion here. I've tried to remove references to VEP and dbNSFP usage from the docs since I believe this has all switched over to vcfanno usage rather than VEP. Thanks again for pointing it out.

**Comment by mmoisse** [comment]
Thank you
