### ISSUE TITLE
PureCN.R: no such file or directory

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2857]
Note, this is probably an issue in the PureCN bioconda package rather than bcbio itself.

PureCN is invoked with

```
export R_LIBS_USER=/opt/bcbio/anaconda/lib/R/library && unset R_HOME && unset R_LIBS && export PATH=/opt/bcbio/anaconda/bin:"$PATH" && PureCN.R
```

Except there is no such command in the PATH. It looks like it's not even symlinked in the package (it's in `./library/PureCN/extdata/PureCN.R`) , and lacks a shebang.

**Comment by roryk** [comment]
Thanks Luca-- huh, I'm confused how this ever worked.

**Comment by chapmanb** [comment]
Luca and Rory;
Thanks much for the heads up. It looks like the automated bioconda updates removed the script changes we had in place to install these files. This is the latest build script:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-purecn/build.sh

and the steps we need to stick back in to prepare and symlink the right files into the bin path:

https://github.com/bioconda/bioconda-recipes/blob/8ad5f8a743dce362a3229eb753f7aac7149aadc2/recipes/bioconductor-purecn/build.sh

**Comment by roryk** [comment]
Thanks Brad! I'll fix the bioconda package to restore those steps.

**Comment by roryk** [comment]
Looks like purecn is on the blacklist because some of the dependencies need R 3.6 which isn't supported by bioconda yet, so we might need to work around this in bcbio for the time being.

**Comment by lbeltrame** [comment]
In addition, the script is called with the non-existent segmentation function `Hclust`, I guess that got removed?

**Comment by roryk** [comment]
Hi Luca,

I opened a pull request for the PureCN recipe here: https://github.com/bioconda/bioconda-recipes/pull/16045 where I restored the linking of the scripts. I had to unpin some of the dependencies, and don't have test data to check if it is working right, so if/when that gets merged in it would be sweet if you could test it out.

**Comment by roryk** [comment]
Sorry, it looks like we're going to be stuck on this until R3.6 is available: https://github.com/bioconda/bioconda-recipes/pull/16045

**Comment by roryk** [comment]
I updated PureCN this week but we're still waiting on full R 3.6 support in bioconda.

**Comment by lbeltrame** [comment]
Is there a tracking issue for R 3.6 support in bioconda? Might be useful to keep watch of that one.

**Comment by roryk** [comment]
Sorry about the long delay, we finally were able to fix this, so we should be all good now.
