### ISSUE TITLE
Vardict filtering fails on bcftools AF subfield issue

### ISSUE THREAD

**Issue by ameynert** [bcbio/bcbio-nextgen#2858]
bcbio-1.1.5, running Vardict in tumor-only config.

Failing with error:
```
The FORMAT tag AF can have multiple subfields, run as AF[sample:subfield]
```

Fixed in variation/vardict.py line 220 (_lowfreq_linear_filter definition):

```
           """-e  'FORMAT/AF[{tumor_index}:0] < 0.02 && FORMAT/VD[{tumor_index}] < 30 """
```

I'm not sure if my fix is the correct behaviour, but I'm getting past the error now.

**Comment by roryk** [comment]
Heya, Brad fixed that issue here:

https://github.com/bcbio/bcbio-nextgen/commit/1a5343c094b7a5cd79b7b4eebd527b92392831c6

if you update to the latest development version you should be all set.

**Comment by mjafin** [comment]
@roryk @chapmanb long time no see, hope you're well. 

We came across this same issue running through bcbio_vm on Google Cloud. Is there a way to get the new version of VarDict into the vm Docker(?) image?

**Comment by roryk** [comment]
Hi Miika! I am glad to see you. :)

@chapmanb how do you update the docker image? It would be helpful for me to figure out how you are doing that.

**Comment by chapmanb** [comment]
Miika -- great to hear from you. Hope things are going well.

Rory -- thanks for looking at this. I just pushed the necessary change to bcbio_docker to rebuild the Docker image. All you need to do is bump the git hash it references and everything else happens as part of the TravisCI build. Hope this fixes it and gives you a path for updating going forward.

**Comment by roryk** [comment]
Hi Brad, thanks! Made a note for myself.
