### ISSUE TITLE
Python 3 porting error in multiqc.py

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2863]
Around line 486 in `_merge_metrics` (`bcbio/qc/multiqc.py`) we have:

```python

        m = tz.get_in(['summary', 'metrics'], s)
        if isinstance(m, six.string_types):
            m = json.loads(m)
        if m:
            for me in m.keys():
                if isinstance(m[me], list) or isinstance(m[me], dict) or isinstance(m[me], tuple):
                    m.pop(me, None)
            sample_metrics[dd.get_sample_name(s)].update(m)
```

However this doesn't work in Python 3 because `keys()` is no longer a list (it's an iterator) so `pop` will try to change the dictionary size in-place during the iteration, causing a runtime error. A quick solution is to cast to `list`:

```python
for me in list(m): 
```

**Comment by chapmanb** [comment]
Luca;
Thanks for the detailed bug report and the fix. The latest development resolves this, and hopefully now works cleanly for you. If you're able to submit PRs for these, we'd be happy to merge them so you get formal credit in the history for finding and fixing the issue. Thanks again.
