### ISSUE TITLE
Batch name not uniq

### ISSUE THREAD

**Issue by caballero** [bcbio/bcbio-nextgen#2865]
hi, I am doing some RNA-seq analysis but I got this error if in my configuration (bcbio_fastRNAseq.yaml) when the Description is equal to the Batch Name:

2019-06-27 16:14:55,856 INFO -- [wu225job674_main] File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/run_info.py", line 467, in _check_for_batch_clashes
2019-06-27 16:14:55,856 INFO -- [wu225job674_main] "Clashing batch names: %s" % sorted(list(dups)))
2019-06-27 16:14:55,856 INFO -- [wu225job674_main] ValueError: Batch names must be unique from sample descriptions.
2019-06-27 16:14:55,856 INFO -- [wu225job674_main] Clashing batch names: ['B09119TB02', 'B09143TB02']
2019-06-27 16:14:55,856 INFO -- [wu225job674_main] """

For the moment I just modify the Description value to add "Sample XXX" to be different, but I am not sure why bcbio is complaining about non-unique batch names if the values are different.

Here is the file causing the problem:

details:
- algorithm:
    aligner: hisat2
    strandedness: unstranded
    quality_format: standard
    trim_reads: False
    expression_caller: salmon
  analysis: fastrna-seq
  genome_build: hg38
  description: B09119TB02
  files:
  - "/scratch/inputresources/B09119TB02_R2.fastq.gz"
  - "/scratch/inputresources/B09119TB02_R1.fastq.gz"
  metadata:
    batch: "B09119TB02"
- algorithm:
    aligner: hisat2
    strandedness: unstranded
    quality_format: standard
    trim_reads: False
    expression_caller: salmon
  analysis: fastrna-seq
  genome_build: hg38
  description: B09143TB02
  files:
  - "/scratch/inputresources/B09143TB02_R2.fastq.gz"
  - "/scratch/inputresources/B09143TB02_R1.fastq.gz"
  metadata:
    batch: "B09143TB02"

Here is how we fixed:

details:
- algorithm:
    aligner: hisat2
    strandedness: unstranded
    quality_format: standard
    trim_reads: False
    expression_caller: salmon
  analysis: fastrna-seq
  genome_build: hg38
  description: Sample B09119TB02
  files:
  - "/scratch/inputresources/B09119TB02_R2.fastq.gz"
  - "/scratch/inputresources/B09119TB02_R1.fastq.gz"
  metadata:
    batch: "B09119TB02"
- algorithm:
    aligner: hisat2
    strandedness: unstranded
    quality_format: standard
    trim_reads: False
    expression_caller: salmon
  analysis: fastrna-seq
  genome_build: hg38
  description: Sample B09143TB02
  files:
  - "/scratch/inputresources/B09143TB02_R2.fastq.gz"
  - "/scratch/inputresources/B09143TB02_R1.fastq.gz"
  metadata:
    batch: "B09143TB02"

**Comment by chapmanb** [comment]
Juan;
Thanks for the message and sorry for any confusion. bcbio requires you to have separate sample and batch names, which is the error you're getting:
```
ValueError: Batch names must be unique from sample descriptions.
```
and the error message lists the two cases where that occurs to try and make them easier to identify and fix. Prefixing either the sample or batch name to make them different works great to resolve this. Hope this helps.
