### ISSUE TITLE
Recommended hardware for RNA-seq

### ISSUE THREAD

**Issue by caballero** [bcbio/bcbio-nextgen#2866]
I was wondering if you can suggest some hardware recommendations for RNA-seq analysis, we have a few hundred samples in Illumina paired-ends fastqs (from 1-8 GB each fastq.gz) and I'm doing some testing but I was wondering if anyone has experience how this scale up regarding a single machine or in a HPC enviroment (Slurm) for optimal processing. Thanks

**Comment by roryk** [comment]
Hi Juan,

Each sample will take several hours to finish, most of that time is taken up by doing whole genome alignments and calculating quality control metrics from them. If you assign 8 cores per sample and give it 80 cores, you can do 10 every several hours, so about 30 a day, so it will take you three days to do 100. If you have more cores available you can do more samples simultaneously. Hope that helps get you started!
