### ISSUE TITLE
mapDamage on `bcbio`

### ISSUE THREAD

**Issue by fgvieira** [bcbio/bcbio-nextgen#2867]
Dear all,

I've been thinking of using `bcbio` on ancient samples, and was wondering if it includes [mapDamage2](https://github.com/ginolhac/mapDamage). Ancient samples have some specific muational patters and `mapDamage2` allows to inspect and quantify them.

Furthermore, it also allows to rescale base quality scores of likely damaged positions in the reads. A new BAM file is constructed by downscaling quality values for misincorporations likely due to ancient DNA damage according to their initial qualities, position in reads and damage patterns.

If not inlcuded, how difficult do you think it would be to incorporate it?
thanks,

**Comment by chapmanb** [comment]
Filipe;
Thanks for starting this discussion. bcbio doesn't currently include mapDamage2 and we'd be happy for you to explore it's utility on your samples and helping to contribute. For starting places, the current damage filters are a good reference for how this could be integrated: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/damage.py. Thanks again for looking into this.
