### ISSUE TITLE
Restarting bcbio reduced the number of cores per job

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#2868]
Hi guys,

We running bcbio using ipython on a SGE cluster. 

> bcbio_nextgen.py ../config/tn-bcbio_129323_120082.yaml -t ipython -n 61 -s sge --timeout 480

I've had a relatively strange thing where we had to stop all jobs, running on 15 cores, when we reran the pipeline it suddenly had reduced all jobs to 7 cores using exactly the same command. I haven't changed the bcbio/galaxy/bcbio_system.yaml, currently set at 15 cores and 4gb per core. Just curious if there is something I'm missing here or a way to reset this?

Thanks!

**Comment by roryk** [comment]
Hi Warren,

Not all of the tools that bcbio uses support multicore use, so there are steps that will only use one core per sample. bcbio will also use less cores if there are other reasons to constrain the core usage; for example if a node does not have a lot of memory available it will reduce the number of cores used so it won't run out of memory, that sort of thing. See https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#memory-management for the blurb about it in the documentation.

**Comment by waemm** [comment]
Thanks @roryk , this was due to some changes to the cluster nodes halfway through analysis. An unlikely event at the best of times! I added the machine: memory:  tags to the config file and it resume correctly. As always thanks for your response!
