### ISSUE TITLE
Features that are available in CWL

### ISSUE THREAD

**Issue by schelhorn** [bcbio/bcbio-nextgen#2872]
Hi @roryk,

is there an overview about which bcbio features are available in the CWL flavour and which are not? More specifically, is PDX disambiguation available in CWL? Thanks!

**Comment by roryk** [comment]
Hi @schelhorn,

Brad pretty much wrote all of that, so I'm not super sure where it is at. In the docs down the bottom here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html#common-workflow-language-cwl there is a TODO list which mentions that disambiguation isn't supported in by the bcbio CWL yet. Brad would know for sure but I'm guessing it isn't implemented.

**Comment by schelhorn** [comment]
I see, thank you. Is there any roadmap for CWL development at all now that Brad is gone (or less involved)? The missing disambiguate functionality is what hinders us moving to CWL at the moment.

**Comment by roryk** [comment]
Thanks, unfortunately, we aren't planning on doing any CWL development right now-- Brad is pretty impossible to replace, we'd probably need to hire an entire team of people to work on everything he was doing.

**Comment by chapmanb** [comment]
Rory is right on, we unfortunately hadn't tackled disambiguation as part of CWL. It's a bit tricky to do since it requires a separate workflow with multiple alignments and splitting of files so we hadn't prioritized it. Sorry to not have this already in place.

**Comment by schelhorn** [comment]
No worries; while we'd really appreciate an implementation since missing CWL disambiguation currently hinders us from switching to CWL, I of course realize that this is quite an effort especially since you now have other commitments as well 😉

If it helps: there already is a CWL wrapper for `disambiguate` that uses a helper shell script at https://github.com/ding-lab/MouseTrap2/blob/master/cwl/disambiguate_filter.cwl (the shell script being located in `./src`).

As a bounty I am handing out a nice dinner at BOSC in Basel for anyone doing a bcbio CWL implementation of this (realizing that this will only cover a small part of the actual effort).
