### ISSUE TITLE
TitanCNA requires bioconductor-snpchip

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2874]
But I don't think it's installed by default.

**Comment by roryk** [comment]
Hi Luca,

It isn't listed on the dependencies: https://bioconductor.org/packages/release/bioc/html/TitanCNA.html where are you seeing that it requires that?

**Comment by lbeltrame** [comment]
The package doesn't, but the script which bcbio uses does:

https://github.com/gavinha/TitanCNA/blob/9c45b4eb9e2e3a5cfd1e1be245b767186d6972d3/scripts/R_scripts/titanCNA.R#L29

Note that I have no idea whether it is actually *used* or not, but it is loaded at startup.

**Comment by roryk** [comment]
Thanks Luca, good catch, I'll add it to the dependencies and rebuild the formula in bioconda.

**Comment by roryk** [comment]
The movement to R 3.6 has been started, once this packages gets updated we can fix the missing dependency.

**Comment by lbeltrame** [comment]
While we're at it, once R 3.6 lands I would suggest to update also TitanCNA itself (which requires 3.6 in its newest versions) because it carries important fixes for LOH / CN estimation.

**Comment by roryk** [comment]
Thanks Luca, I agree.

**Comment by roryk** [comment]
Thanks for the patience. I just added the package as one bcbio installs; updating the recipe every time it updates on bioconda isn't something I was too interested in doing.
