### ISSUE TITLE
scalpel-0.5.4 to 0.5.3

### ISSUE THREAD

**Issue by widfa11** [bcbio/bcbio-nextgen#2876]
Hi,
I used bcbio-nextgen v1.1.6a and tried to use scalpel-0.5.4 but got the following error. and I can bypass the issue if I use scalpel 0.5.3, can I downgrade the scalpel version in bcbio envirment if possible? thank you.

Command failure: microassembly (/home/xx/bcbio/anaconda/share/scalpel-0.5.4-1/Microassembler/Microassembler -R -I -C -F 10000 -k 25 -K 90 -M 3 -l 25 -c 3 -x 0.01 -d 1 -u 10000 -b 1 -p /home/r514c/TQ3/work/bcbiotx/tmpj2y9hj6y/47_TruQ-3-chr12_40619356_56474166-scalpel-work -m bamfile.bam -g readgroups.txt  -r regions-0-293.fa >/home/r514c/TQ3/work/bcbiotx/tmpj2y9hj6y/47_TruQ-3-chr12_40619356_56474166-scalpel-work/logs/regions-0-293.fa.log 2>&1)...

**Comment by chapmanb** [comment]
Thanks for the note. Scalpel hasn't gotten much development either on the original project side or in bcbio for a while. In bcbio we typically use callers with indel calling and local assembly embedded, like HaplotypeCaller and FreeBayes for germline and MuTect2 and VarDict for somatic calling. If you need to work around it for your pipeline you can do:
```
bcbio_conda install -c conda-forge -c bioconda scalpel=0.5.3
```
to downgrade to the version that's working for your analysis. Hope this helps.
