### ISSUE TITLE
fgbio stuck

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2880]
Hello,

fgbio seems to be stuck with (I guess) a memory issue that bcbio no longer prints/generates any output.

I have tried different memory  settings, but in bcbio_system.yaml currently using:
  default:
    memory: 8g
    cores: 32
    jvm_opts: ["-Xms750m", "-Xmx7g"]

I find in the bcbio-nextgen-commands.log that these parameters "fgbio -Xms750m -Xmx83g" were passed.

Below are the last few lines printed in bcbio-nextgen-debug.log. 

Please let me know if you see anything incorrect.

Thanks,
Segun

[2019-07-16T22:42Z] irvdvm-ubuntu0: [2019/07/16 15:42:24 | SamWriter | Info] Wrote      8,000,000 records.  Elapsed time: 02:02:04s.  Time for last 2,000,000: 2,693s.  Last read position: 1:204,518,643
[2019-07-16T22:42Z] irvdvm-ubuntu0: [2019/07/16 15:42:24 | CallMolecularConsensusReads | Info] processed     8,000,000 records.  Elapsed time: 02:02:01s.  Time for last 500,000: 1,205s.  Last read position:
 1:204,518,643
[2019-07-16T22:42Z] irvdvm-ubuntu0: [2019/07/16 15:42:34 | FilterConsensusReads | Info] Filtered and masked     5,000,000 records.  Elapsed time: 02:02:10s.  Time for last 1,000,000: 2,295s.  Last read posi
tion: */*

**Comment by roryk** [comment]
Hi Segun,

If you log into irvdvm-ubuntu0 and look at the output of top, is it doing something? It looks like it is still processing. fgbio takes a long time to run, this step can take hours and hours if you have very large WGS-size files. We have on our list to speed this up but haven't gotten around to it yet.

**Comment by dauss75** [comment]
Hi Rory,

Thanks for the quick reply.
I do see java is running, but only one or two samples out of 48 have been an issue. I took those out and then reran in separate, but the runs do get stuck again at the same step (by looking at the log file).
The reason I started checking them was because I once let it run over the weekend, but found no progress.  I also look at the bcbio temp directory but notice that fgbio does not generate files at some point. I work with WES so I thought something is not right. 

By the way, do you find the memory setting looks okay?

Thanks a lot for your help.
Segun

**Comment by roryk** [comment]
Hi Segun,

Is java running and consuming CPU, or it is sitting and doing nothing at 0% CPU? If it is at 100% CPU then it is still working on the files, but otherwise the diagnosis that it is hung seems right.

**Comment by dauss75** [comment]
OK jave was at 100% CPU and it has been three days now. I almost thought fgbio is not working anymore, to my surprise it is working (but very slowly).  At least, it's not a bug so I will close this thread.
Thanks Rory for the help.

**Comment by roryk** [comment]
Thanks-- sorry about that, it is on our list of things to do to parallelize the fgbio stuff by chromosome so this step goes much faster for very large files, but we haven't gotten to it yet.

**Comment by dauss75** [comment]
That must be a very nice option to have. Looking forward to seeing the update hopefully soon.

**Comment by dauss75** [comment]
FYI, just saw an update on fgbio git repo noting "Speeding up CallDuplexConsensusReads."  Don't know yet if fgbio will have a new release anytime soon, but if this works I thought that would be a good update in bcbio.
