### ISSUE TITLE
VEP data download link needs to be updated.

### ISSUE THREAD

**Issue by jxshi** [bcbio/bcbio-nextgen#2883]
Hi,

I tried to upgrade bcbio-nextgen recently. But it encountered the following error.
```
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'rn6', 'name': 'Rat (rn6)', 'indexes': ['seq', 'twobit'], 'annotations': ['transcripts', 'mirbase']}], 'genome_indexes': ['bwa', 'bowtie2', 'star', 'hisat2', 'rtg', 'twobit', 'bowtie'], 'install_liftover': False, 'install_uniref': False}'): Rat (rn6)
--2019-07-18 14:16:49--  http://ftp.ensembl.org/pub/release-97/variation/VEP/homo_sapiens_merged_vep_97_GRCh37.tar.gz
Resolving ftp.ensembl.org... 193.62.193.8
Connecting to ftp.ensembl.org|193.62.193.8|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-18 14:16:54 ERROR 404: Not Found.
```
I found that the link to vep data needs to be updated. (```VEP``` should be in lower case in current link).

Previous link: http://ftp.ensembl.org/pub/release-97/variation/VEP/homo_sapiens_merged_vep_97_GRCh37.tar.gz

Current link: http://ftp.ensembl.org/pub/release-97/variation/vep/homo_sapiens_merged_vep_97_GRCh37.tar.gz

Thank you!

Cheers!

Jianxiang

**Comment by jxshi** [comment]
Hi,

I have replaced ```VEP``` with ```vep```  in line 445 of the following file to solve this.

```~/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py```

Cheers!

Jianxiang

**Comment by roryk** [comment]
Thanks, it looks like they switched from `VEP` to having both `VEP` and `vep` to only having `vep`, so it seems like maybe they were transitioning off of VEP and moving to just`vep`. I added a check to check for the release version being >= 97, and if so using `vep`. Thanks!

**Comment by erinijapranckeviciene** [comment]
Hi @jxshi , @roryk  

I just reinstalled bcbio_nextgen less than 9 days ago  and was upgrading vep. I came across the same as jxshi , but in my case it is line 99 of effects.py :

  url = "http://ftp.ensembl.org/pub/release-%s/variation/VEP/%s.tar.gz" % (eversion, ensembl_name)

Changing manually from VEP to vep fixed the issue.  So perhaps  this is still in the code.

**Comment by roryk** [comment]
Hi @erinijapranckeviciene,

If you upgrade to the development version with `-u development` you'll pull in this fix, I think you might be operating on the `-u stable` branch.

**Comment by erinijapranckeviciene** [comment]
Hi @roryk , yes, this is the case, thank you.

**Comment by roryk** [comment]
Great! Thanks for following up.
