### ISSUE TITLE
R needs improved isolation

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2885]
Currently, we're using `--no-environ` internally for some Rscript calls to isolate the R environment. This can be improved by using the `--vanilla` flag instead, which avoids potential issues with package library configuration defined in `~/.Rprofile`.

Here's a search of files that we may want to patch:
https://github.com/bcbio/bcbio-nextgen/search?q=rscript&type=Code

I'm working on patching this in my development fork of bcbio.

**Comment by roryk** [comment]
Thanks!

**Comment by roryk** [comment]
I fixed all these and will push a fix once I can make sure it actually works, probably tomorrow.

**Comment by mjsteinbaugh** [comment]
Awesome thanks!
