### ISSUE TITLE
Non-fatal error encountered during upgrade

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2886]
```
ERROR: Encountered corrupt package tarball at /opt/bcbio/anaconda/pkgs/reportlab-3.5.23-py36he686d34_0.conda. Conda has left it in place.  
```

I've seen that in two different installs of bcbio. I believe, however, that it prevents updates of some packages.

**Comment by lbeltrame** [comment]
This was also reported as  https://github.com/ContinuumIO/anaconda-issues/issues/11109.

**Comment by chapmanb** [comment]
Luca -- thanks much for the report. Is conda continuing through this, or dying at this point? I'm not able to reproduce the cache error trying to install reportlab now, so I wonder if this was a temporary issue resulting in a bad download. If you remove the problem download and re-run, does it consistently error/fail? Thanks again for the help debugging.

**Comment by lbeltrame** [comment]
It happened a few weeks ago and today when I updated bcbio. I'm not sure if it's transient or not, I remember consistently getting that though.

**Comment by roryk** [comment]
Thanks, the conda-forge version is not mangled, so if you install that one, it should work okay:

```
bcbio_conda install -c conda-forge reportlab==3.5.23
```

will install one that works.

**Comment by roryk** [comment]
Thanks, Mike at Anaconda fixed the broken package: https://github.com/ContinuumIO/anaconda-issues/issues/11109, so this should be all set. Thanks for reporting the problem!
