### ISSUE TITLE
[requirement.txt] No module named toolz

### ISSUE THREAD

**Issue by shouldsee** [bcbio/bcbio-nextgen#2888]
Is the requirement.txt maintained?

**Comment by roryk** [comment]
Hi @shouldsee, we recommend installing via the automated installer, which will install all of the dependencies and tools needed via bioconda.

**Comment by shouldsee** [comment]
Hi @roryk. Thanks for the info but I cannot bear the slowness of conda install. Can I find the python dependency anywhere in this repo?

**Comment by roryk** [comment]
bcbio won't work without the tools installed as well, just installing the code won't really get you very far. https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#installation has the information on how to install bcbio.

**Comment by shouldsee** [comment]
Okay I was actually only wanting to test `scripts/utils/bam_to_wiggle.py` and git clone was actually the simplest installation... 

Would still be good to maintain some level of python dependencies tho, or is there no intention to expose  python modules at all?

**Comment by chapmanb** [comment]
The `bam_to_wiggle.py` script is standalone so doesn't rely on a bcbio installation, although you do need `wigToBigWig` installed.

Practically, if you want to convert BAMs to bigWigs I'd suggest using using cgpBigWig (https://anaconda.org/bioconda/cgpbigwig) which is also available from bioconda: https://anaconda.org/bioconda/cgpbigwig

Hope this helps.

**Comment by shouldsee** [comment]
@chapmanb Thanks for introducing cpgbiwig. Might give it a try when I have some time but its setup.sh did not compile straight away.

**Comment by shouldsee** [comment]
@chapmanb  I managed to got it compiled, with an ugly change to its MakeFile. 

Do you guys happen to know how to avoid ".so.30" in the following line? I got an `ld` error if the `.30` is omitted.
```
LIBBWLIBS=-lBigWig -lz -lbz2 -llzma -lcurl -lm -l:libgnutls.so.30 -l:libtasn1.so.6 -lhogweed ...
```

**Comment by roryk** [comment]
Thanks-- looks like this got resolved. Let us know if we can help with anything else!
