### ISSUE TITLE
upgrade failure

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2891]
Hello,

Simply, upgrade failed and I deleted  the "tmpbcbio-install" directory and retried, but the problem still persists.

bcbio_nextgen.py upgrade -u stable --tools --data
Upgrading bcbio
Traceback (most recent call last):
  File "/isilon/RnD/tool-data/bcbio/anaconda/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
Traceback (most recent call last):
  File "/isilon/RnD/tools/bcbio/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/isilon/RnD/tool-data/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 69, in upgrade_bcbio
    _update_conda_packages()
  File "/isilon/RnD/tool-data/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 277, in _update_conda_packages
    channels = _get_conda_channels(conda_bin)
  File "/isilon/RnD/tool-data/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 262, in _get_conda_channels
    config = yaml.safe_load(subprocess.check_output([conda_bin, "config", "--show"]))
  File "/isilon/RnD/tool-data/bcbio/anaconda/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/isilon/RnD/tool-data/bcbio/anaconda/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/isilon/RnD/tool-data/bcbio/anaconda/bin/conda', 'config', '--show']' returned non-zero exit status 1.

**Comment by roryk** [comment]
Hi Segun,

Sorry about that, we are having some problems with upgrading and installing right now, I've been trying to fix them the past few days but I'm still working on it.

**Comment by dauss75** [comment]
OK thanks.  I can see the conda module is there, but it's broken not finding it.  Hope to hear the problem gets resolved soon.

**Comment by chapmanb** [comment]
Thanks so much for this report, hopefully we have these issues fixed although they will require a reinstall of the code and tools to easily fix a broken system. More details on the issues we found and how to fix are here:

https://github.com/bcbio/bcbio-nextgen/issues/2889#issuecomment-515842898

**Comment by dauss75** [comment]
Thank you. I had to reinstall and upgrade, but the pipeline is back to alive now.

**Comment by roryk** [comment]
Thanks for following up!

**Comment by dauss75** [comment]
Would this now be okay to try?  
When trying this a few days ago, it broke the bcbio with errors and thus I am somehow nervous to give another shot. I want to add ericscript database for hg38 to perform fusion detection. 

bcbio_nextgen.py upgrade -u stable --data --datatarget ericscript --genomes hg38

**Comment by chapmanb** [comment]
You should be fine with updating in this way, although a couple of thoughts:

- I'm not sure how well ericscript works with hg38, and @roryk might have a better recommendation for fusion detection.
- You don't need a code update if you want to add new data targets and can just do:
```
bcbio_nextgen.py upgrade --data --datatarget ericscript --genomes hg38
```
Hope this helps

**Comment by ohofmann** [comment]
The only approach that worked for us with hg38 was Kallisto/Pizzly (mostly because Star doesn't handle hg38 well).

**Comment by roryk** [comment]
Hi everyone,

I have on my list of things to do to add STAR support for hg38 by stripping off the ALTs when we make the index, that way we can still use the fusion callers that rely on the STAR output for GRCh37. At the same time I'll be implementing support for the arriba caller, which crushed everything else in the DREAM challenge.

**Comment by dauss75** [comment]
Thanks Rory and Brad.  I understand you guys have a lot of things on the table, but any ETA on arriba?

RE ericscript with hg38, gdc.sh (?) failed and thus downloaded the hg38 database manually from ericscript website to put in the genomes directory and then updated the tool-data in galaxy. I am about to check the ericscript result, but it did finish in a couple of days.  The bottlenect is in the blat program that may be parallelized in the R script (the wrapper).

**Comment by roryk** [comment]
Hi Segun,

I'm aiming to have support for GRCh37 this week-- hg38 is going to take a little bit longer since we need to support STAR in order to use arriba, and STAR won't work on hg38 with the alt alleles.

**Comment by dauss75** [comment]
Thank you!
GRCh37 would be sufficient. 👍
