### ISSUE TITLE
Dots in ped are problematic

### ISSUE THREAD

**Issue by mmoisse** [bcbio/bcbio-nextgen#2895]
When using samples with dots in it, the pipeline crashes at the creation of a gemini database

```
[2019-07-30T10:17Z] GEMINI: create database with vcf2db
[2019-07-30T10:17Z] name_disp None
[2019-07-30T10:17Z] Traceback (most recent call last):
[2019-07-30T10:17Z]   File "/local/bin/vcf2db.py", line 924, in <module>
[2019-07-30T10:17Z]     impacts_extras=a.impacts_field, aok=a.a_ok)
[2019-07-30T10:17Z]   File /local/bin/vcf2db.py", line 228, in __init__
[2019-07-30T10:17Z]     self.samples = self.create_samples()
[2019-07-30T10:17Z]   File "/local/bin/vcf2db.py", line 598, in create_samples
[2019-07-30T10:17Z]     vals = [r[i] for r in rows]
[2019-07-30T10:17Z] IndexError: list index out of range
[2019-07-30T10:17Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/software/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/software/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/local/bin/vcf2db.py /analysis/CW136MW/work/gemini/CW136-freebayes-nomultiallelic-annotated-dbnsfp.vcf.gz /analysis/CW136MW/work/gemini/CW136-freebayes-nomultiallelic.ped /analysis/CW136MW/work/bcbiotx/tmp0k2nspxr/CW136-freebayes.db
name_disp None
Traceback (most recent call last):
  File "/local/bin/vcf2db.py", line 924, in <module>
    impacts_extras=a.impacts_field, aok=a.a_ok)
  File "/local/bin/vcf2db.py", line 228, in __init__
    self.samples = self.create_samples()
  File "/local/bin/vcf2db.py", line 598, in create_samples
    vals = [r[i] for r in rows]
IndexError: list index out of range
' returned non-zero exit status 1.
```

My input ped looks like this
```
#family_id	name	paternal_id	maternal_id	sex	phenotype	name_ID	name_disp
CW136	import_CW136P.gatk	import_CW136F.gatk	CW136M	2	2	42	CW136P
CW136	CW136M	0	0	2	1	43	CW136M
CW136	import_CW136F.gatk	0	0	1	1	44	CW136F
```

while the ped file generated for gemini import looks like this
```
#Family_ID	Individual_ID	Paternal_ID	Maternal_ID	Sex	Phenotype	Ethnicity	name_disp
CW136	import_CW136F_gatk	-9	-9	1	1	-9
CW136	CW136M	0	0	2	1	43	CW136M
CW136	import_CW136P_gatk	-9	-9	2	2	-9
```

**Comment by roryk** [comment]
Hi @mmoisse,

Thanks-- what do the sample names in your VCF look like? The PED file names are different because we do some cleaning up of sample names before running bcbio. Do the sample names in the PED file for GEMINI import match the sample names in the header?

**Comment by mmoisse** [comment]
In the vcf header all dots have been replaced by _ so these are the sample names
`CW136M`, `import_CW136F_gatk` and `import_CW136P_gatk`

**Comment by roryk** [comment]
Thank you, is there any way you could pass on the VCF and the PED file so we can look at it to try to figure out what the problem is?

**Comment by mmoisse** [comment]
Please find attached the input ped file and a subset of the vcf file.
Tx

[CW136MW.ped.zip](https://github.com/bcbio/bcbio-nextgen/files/3455580/CW136MW.ped.zip)

[CW136-freebayes-nomultiallelic-annotated-dbnsfp.subset.vcf.zip](https://github.com/bcbio/bcbio-nextgen/files/3455577/CW136-freebayes-nomultiallelic-annotated-dbnsfp.subset.vcf.zip)

**Comment by roryk** [comment]
Hi @mmoisse,

If you switch the . to _ in the PED file like bcbio did and use that to load the database, this seems to work fine. Does it not work if you do that?

**Comment by mmoisse** [comment]
Hi @roryk,

Indeed switching `.` to` _` does work, but it seems a bit weird because in your yaml and csv file you can use `.` in the name but in the ped you can not, and then I would need to use other names in the ped then in the yaml and csv files. 
Would it be possible to give a warning or also clean the sample names in de ped file?

Kind regards,
Matthieu

**Comment by roryk** [comment]
Hi Matthieu,

Hm-- we do clean up the names, which is why in the PED file generated for the GEMINI import has dashes in it. 

`/local/bin/vcf2db.py /analysis/CW136MW/work/gemini/CW136-freebayes-nomultiallelic-annotated-dbnsfp.vcf.gz /analysis/CW136MW/work/gemini/CW136-freebayes-nomultiallelic.ped foo.db`

That's the command that is failing, but it works with the files you gave me. I'm guessing that the . vs _ isn't the problem, since in that command they've been converted to dashes in the PED and the VCF file. Can you confirm that the above command gives you the error? If so, can you send along the entire VCF file or at least a subset that fails with the same error?

**Comment by mmoisse** [comment]
I believe the issue occurs here:
First it reads the original ped file, with the `.` in the file name and sets that as key

https://github.com/bcbio/bcbio-nextgen/blob/90c156d5e5b6c5e99a4d8280965c2e7580fac41d/bcbio/variation/population.py#L253-L259

Then you get the cleaned sample names from the vcf file

https://github.com/bcbio/bcbio-nextgen/blob/90c156d5e5b6c5e99a4d8280965c2e7580fac41d/bcbio/variation/population.py#L263

To then query the original ped file with cleaned sample names, which fails in case of `.` in the sample name.

https://github.com/bcbio/bcbio-nextgen/blob/90c156d5e5b6c5e99a4d8280965c2e7580fac41d/bcbio/variation/population.py#L269-L272

**Comment by roryk** [comment]
Thanks-- does the pipeline fail somewhere else then? It looks like in the original issues the failure is calling out to `vcf2db.py`, is that not where the failure is actually happening?

**Comment by roryk** [comment]
Ok, I figured out where the original problem is coming from. The PED file has extra columns in it, I see there are columns for name_ID and name_DISP which I think is what is causing the problem. If I keep those columns in, I get the original problem but if drop those columns from the PED file it works fine.

**Comment by mmoisse** [comment]
Thank you.
I will test it and come back to you, probably not before Monday.

**Comment by mmoisse** [comment]
> Thanks-- does the pipeline fail somewhere else then? It looks like in the original issues the failure is calling out to `vcf2db.py`, is that not where the failure is actually happening?

Yes the issue occurs in vcf2db.py. But I believe, this is due to an issue in the conversion of the input ped-file to the gemini ped-file. In the input file `import_CW136P.gatk` has a father and a mother while in the gemini ped-file the both parents are set to -9 (unknown). Additionally, if a sample is not found in the input ped-file 7 column are write to the gemini ped-file, while if the sample is found the same number of columns as in the input ped-file are written to the gemini ped-file. Probably this mismatch in the number of columns per row is the cause of the crash of vcf2db.py ?

Thank you for your time.

**Comment by roryk** [comment]
Thanks, I checked and this definitely is due to the extra columns in the input PED file-- if you limit them to just the normal columns this should work fine. Thanks!
