### ISSUE TITLE
Community update?

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2898]
Hi Brad/Rory

Would it be possible to post some kind of community update? 
I've gathered from some issue comments and code frequency that Brad has taken a bit of a step back in favor of other responsibilities (congrats btw!). 
It'd be nice for the people using bcbio intensively to know what's on the roadmap and what the shifts in management are.
A small list of points needing development could also elicit some more response from the community.

Thanks!
Matthias

**Comment by roryk** [comment]
Hi Matthias,

Thanks! You rear our minds. On my list of things to do today is to make a stick TODO issue that has a list of things that we are planning on implementing on the short term, the long term and bugs that need to be fixed and what needs to be done for all of these, to make it easier for folks to know what is being worked on and what we could use help with if folks want to jump in and help out. Part of the reason for closing all the stale issues was to focus them on things that we are likely to implement, bugs and useful discussions. I'm also working on simplifying some of the code base and updating the documentation to make it easier for folks who want to contribute to get started.

We lost two folks-- Brad is still doing work on bcbio but he has another job now so he is ideally serving more of an advisory role. @lpantano switched over to work at MIT but is still maintaining the small RNA parts of bcbio. We've hired @naumenko-sa who has made a bunch of great contributions to help work on it to help fill the hole they left and @hackdna has been stepping in to help with development. We're hoping to get some of the frequent users like yourself to be regular contributors as well. I'm working on a small guide that walks through the steps of implementing support for a new tool that should help onboard folks wanting to contribute that don't know where to begin.

**Comment by matthdsm** [comment]
Hi Rory,

Thanks for the update! Looking forward to the TODO list and updated docs. I'm hoping to be able to contribute in the future, time permitting.

Cheers
M
