### ISSUE TITLE
Wrong FTP server link for VEP file CanFam3

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#2903]
Dear developers,

I was adding a few genomes of interest (including the dog genome, CanFam3) to our bcbio installation. However, the process failed when downloading VEP annotations. 

```
--2019-08-14 17:06:44--  http://ftp.ensembl.org/pub/release-97/variation/VEP/canis_familiaris_vep_97_CanFam3.1.tar.gz
Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.193.8
Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.193.8|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-14 17:06:44 ERROR 404: Not Found.

[...]
```

While bcbio is looking for `http://ftp.ensembl.org/pub/release-97/variation/VEP/canis_familiaris_vep_97_CanFam3.1.tar.gz`, the correct URL is `ftp://ftp.ensembl.org/pub/release-97/variation/vep/canis_familiaris_vep_97_CanFam3.1.tar.gz` (lower case `vep`). 

Could you please let me know if you can fix this issue?
Thanks a lot in advance,

Federico

**Comment by naumenko-sa** [comment]
Hi @FedericoComoglio!

Thanks for reporting the issue!
There was a fix recently for a similar issue: https://github.com/bcbio/bcbio-nextgen/issues/2883

Could you please try to upgrade the code to the development version of bcbio
`bcbio_nextgen.py upgrade -u development` 

And then install CanFam3 genome?

Sergey

**Comment by FedericoComoglio** [comment]
Thank you @naumenko-sa ! I upgraded as suggested, and will let you know should I experience any issue.

Federico

**Comment by roryk** [comment]
Thanks everyone, this definitely should fix it so closing.
