### ISSUE TITLE
Hanging?

### ISSUE THREAD

**Issue by rachel-oren** [bcbio/bcbio-nextgen#2906]
I am using bcbio for RNAseq analysis. I submitted a job to my local cluster on Friday to be completed over the weekend. I realized that something has caused it to be hung up. The bam files for each sample were created, but nothing was ever added to the "final" directory, so no count data has been output in any way. I was wondering if anyone knows why this would be, and alternatively, if there is a way to pick up the analysis from this point (ie. can I push it along from here, or should I kill the job and resubmit from the beginning)?

**Comment by roryk** [comment]
Hi Rachel,

There should be log files in your `work` directory that might give you hints about what happened. There is also a log file in `work/log/bcbio-nextgen-debug.log` that has debugging output, which should let you know what step it was on. bcbio can be safely restarted if something happened and it won't write out partial files or anything, so you can pick up where you left off.

**Comment by rachel-oren** [comment]
Hi Rory,

Thanks for getting back to me so quickly! 

These were the last few appendages to the debug file:
[2019-08-17T09:42Z] compute-a-17-134.o2.rc.hms.harvard.edu: [V] run time 03:34:60727700 (214.607 s)	MemUsage(size=7567,rss=1804.14,peak=12159.5)
[2019-08-17T09:42Z] compute-a-17-134.o2.rc.hms.harvard.edu: Index BAM file: PT12_Y_P2-sort.bam
[2019-08-17T09:42Z] compute-e-16-208.o2.rc.hms.harvard.edu: Resource requests: cufflinks, samtools; memory: 3.00, 3.00; cores: 16, 16
[2019-08-17T09:42Z] compute-e-16-208.o2.rc.hms.harvard.edu: Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job


o2 had an interruption over the weekend, which might explain why the job stopped, but I am wondering how I can restart from this point, as it did run for about 24 hours before it was interrupted. 

Thanks again!

**Comment by roryk** [comment]
Hi Rachel,

It looks like it did the alignments, but then paused before doing the quantification. That next step is trying to reserve for the next job, so probably what happened is that reservation timed out or was cancelled somehow, so O2 going down definitely would have caused that. If you just re-submit your bcbio job it will pick up where you left off-- steps that are done already will get passed by and it will only do the new steps.

**Comment by rachel-oren** [comment]
So, just to confirm, I should kill the job (its still going, but not doing anything) and then if I re-submit the job to o2, just as I did the first time around, it should continue where it left off and nothing will be duplicated/lost? 

The last bit of my submission looked like this: 
export PATH=/n/app/bcbio/tools/bin:$PATH
bcbio_nextgen.py ../config/alignment.yaml \
    -n 24 -t ipython -s slurm -q medium -r t=4-00:00 --timeout 2000

Does this all sound correct?

Thanks again!!

**Comment by roryk** [comment]
Hi Rachel,

That's right. I'd add a `--tag yourtag` to the call, which will make it easier to track the jobs on SLURM. You should see three jobs pop up. There is the one main bcbio job that is the result of you submitting that script. There will be a controller job that is the thing that bcbio uses to talk to the engines, that job should be submitted and enter the running state fairly quickly. Then it will wait for one or more of the engine jobs to start, which can take a long time if O2 is busy. Once one or more of those engine jobs is up, bcbio will start processing your sample and you'll see it picked up where it left off.

**Comment by rachel-oren** [comment]
Hey Rory, 

So I killed and re-submitted the job and it looks like things are running, but only one job has popped up. I have looked into the debug file again and it looks like its back to aligning; the last three entries here are:
[2019-08-19T19:49Z] compute-a-16-79.o2.rc.hms.harvard.edu: Aligning lane PT27_O_P1 with hisat2 aligner
[2019-08-19T19:49Z] compute-a-16-79.o2.rc.hms.harvard.edu: Aligning lane PT32_O_P1 with hisat2 aligner
[2019-08-19T19:49Z] compute-a-16-79.o2.rc.hms.harvard.edu: Aligning lane PT34_O_P1 with hisat2 aligner 

Does this make sense? Should I be worried that there is only one job popping up, or might this be an "O2 is busy" sort of issue do you think?

Thanks a ton again, I really appreciate it!

**Comment by roryk** [comment]
Hi Rachel,

That looks right. You gave bcbio 24 cores, and it is configured to try to use 16 cores per sample on O2, so it is just going to run one or two samples at once.

**Comment by roryk** [comment]
Closing as I think this should be all set, let us know if you are experiencing any issues. Thanks!
