### ISSUE TITLE
Ontarget_pct is very low

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2907]
Hi, I am running the variant pipeline on two targeted sequencing samples. I use `variant_regions ` parameter to specify the bed file of my target region. However, I found the mapping_pct is very high (~99%), but the Ontarget_pct is very low (16%). I know the sequenceing may be noisy and even off-target. I just want to know is there any other problem of the pipeline setting cause this problem? Thanks a lot.

> details:
>   - analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       coverage_interval: regional
>       variantcaller:
>         somatic: [freebayes]
>       variant_regions: /ngs/zhengu/3214551_Covered.bed
>       mark_duplicates: false
>       recalibrate: false
>       realign: false
>       effects: snpeff
>       remove_lcr: true
>       ensemble:
>         numpass: 2
>         use_filtered: false
>

**Comment by roryk** [comment]
Hi @hliu2016,

Could you attach your BED file? The coverage calculations aren't doing anything special other than taking the alignment file and running coverage in the regions of your BED file. I'm guessing that your BED file and what was actually targeted is not the same.

**Comment by hliu2016** [comment]
@roryk 
Thanks for your reply. The bed file is attahced. I am not very sure whether the Ontarget_pct is the percent of reads mapped to my target regions to the total reads.  The mutliQC report metrics of one sample is as below:

> %GC	50
> Average_insert_size	193.8
> Average_read_length	150.0
> Avg_coverage	1417
> Duplicates	0.0
> Duplicates_pct	0.0
> Mapped_paired_reads	17976004.0
> Mapped_reads	17993640.0
> Mapped_reads_pct	99.81298420167485
> Mapped_unique_reads	18013128
> Name	zhenyuejiao
> Offtarget_pct	60.993021312012
> Ontarget_padded_pct	38.99744675105845
> Ontarget_pct	39.006978687988
> Ontarget_unique_reads	7026377
> Quality_format	standard
> Sequence_length	30-150
> Sequences_flagged_as_poor_quality	0
> Total_reads	18027354.0
> Usable_pct	38.9761969504787
> sample	zhenyuejiao
> rRNA_rate	NA
> RiP_pct	0.000
> 

[3214551_Covered.zip](https://github.com/bcbio/bcbio-nextgen/files/3521246/3214551_Covered.zip)

**Comment by roryk** [comment]
Hi @hliu2016,

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#analysis-regions has some description of how coverage is figured out. When you just supply `variant_regions` the ontarget percentage is the percentage of total reads mapped to those regions, so it looks like most of the reads for this sample are appearing elsewhere.

**Comment by roryk** [comment]
Closing, as I think this is asked and answered. Hope that clarified things!
