### ISSUE TITLE
GATK3.8 wrongly calls GatherVcfs  and crashes a run 

### ISSUE THREAD

**Issue by erinijapranckeviciene** [bcbio/bcbio-nextgen#2914]

**Comment by erinijapranckeviciene** [comment]
Dear bcbio team, 
I don't know if such issue was noticed already and solution was proposed, but after a recent upgrade I am having problem which seems obvious, but difficult to track down: GATK3.8 calls GatherVcfs, which is a "job" for GATK4. So somewhere the "tools off: gatk4" is overlooked. I insert the tail of the crash message. Any help is appreciated.  If the config file is needed I will post it, tell me which. Many thanks in advance!
===
[2019-08-23T04:57Z] multiprocessing: process_alignment
[2019-08-23T04:57Z] Aligning lane NA12878-VR2-2_CHEO_sample with bwa aligner
[2019-08-23T04:57Z] Aligning lane NA12878-VR2-2_CHEO_sample with bwa aligner
[2019-08-23T04:57Z] Aligning lane NA12878-VR2-2_CHEO_sample with bwa aligner
[2019-08-23T04:57Z] Aligning lane NA12878-VR2-2_CHEO_sample with bwa aligner
[2019-08-23T05:31Z] Aligning lane NA12878-VR2-2_CHEO_sample with bwa aligner
[2019-08-23T05:42Z] multiprocessing: delayed_bam_merge
[2019-08-23T06:07Z] Timing: callable regions
[2019-08-23T06:07Z] multiprocessing: prep_samples
[2019-08-23T06:07Z] multiprocessing: postprocess_alignment
[2019-08-23T06:17Z] NA12878-VR2-2_CHEO_sample: Assigned coverage as 'regional' with 10.5% genome coverage and 0.0% offtarget coverage
[2019-08-23T06:26Z] Prepare BQSR tables with GATK: NA12878-VR2-2_CHEO_sample 
[2019-08-23T07:59Z] Applying BQSR recalibration with GATK: NA12878-VR2-2_CHEO_sample 
[2019-08-23T14:01Z] multiprocessing: combine_sample_regions
[2019-08-23T14:01Z] Identified 209 parallel analysis blocks
Block sizes:
  min: 16569
  5%: 4998040.4
  25%: 15509216.0
  median: 15509595.0
  75%: 15510206.0
  95%: 15901588.399999999
  99%: 19921974.75999999
  max: 43249566
Between block sizes:
  min: 251
  5%: 266.15
  25%: 328.0
  median: 401.0
  75%: 621.25
  95%: 1336.7999999999997
  99%: 6237.319999999924
  max: 33623

[2019-08-23T14:01Z] multiprocessing: calculate_sv_bins
[2019-08-23T14:01Z] multiprocessing: calculate_sv_coverage
[2019-08-23T14:01Z] multiprocessing: normalize_sv_coverage
[2019-08-23T14:01Z] Timing: hla typing
[2019-08-23T14:01Z] Timing: alignment post-processing
[2019-08-23T14:01Z] multiprocessing: piped_bamprep
[2019-08-23T14:27Z] Timing: variant calling
[2019-08-23T14:27Z] multiprocessing: variantcall_sample
[2019-08-23T15:18Z] multiprocessing: concat_variant_files
[2019-08-23T15:18Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; java -Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/projects/CCM_transfer/CHEO/NA12878-VR2-2/work/bcbiotx/tmprxnqy0xd -jar /projects/analysis/bcbio/toolplus/gatk/3.8-0-ge9d806836/GenomeAnalysisTK.jar GatherVcfs -I /projects/CCM_transfer/CHEO/NA12878-VR2-2/work/platypus/NA12878-VR2-2-files.list -O /projects/CCM_transfer/CHEO/NA12878-VR2-2/work/bcbiotx/tmp0f6njjtl/NA12878-VR2-2.vcf.gz
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.8-0-ge9d806836): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid argument value 'GatherVcfs' at position 0.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1.
[2019-08-23T15:18Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; java -Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/projects/CCM_transfer/CHEO/NA12878-VR2-2/work/bcbiotx/tmpkknjbnyu -jar /projects/analysis/bcbio/toolplus/gatk/3.8-0-ge9d806836/GenomeAnalysisTK.jar GatherVcfs -I /projects/CCM_transfer/CHEO/NA12878-VR2-2/work/samtools/NA12878-VR2-2-files.list -O /projects/CCM_transfer/CHEO/NA12878-VR2-2/work/bcbiotx/tmp0gsgk0pa/NA12878-VR2-2.vcf.gz
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.8-0-ge9d806836): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid argument value 'GatherVcfs' at position 0.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1.
[2019-08-23T15:18Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; java -Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/projects/CCM_transfer/CHEO/NA12878-VR2-2/work/bcbiotx/tmpvexlata2 -jar /projects/analysis/bcbio/toolplus/gatk/3.8-0-ge9d806836/GenomeAnalysisTK.jar GatherVcfs -I /projects/CCM_transfer/CHEO/NA12878-VR2-2/work/gatk-haplotype/NA12878-VR2-2-files.list -O /projects/CCM_transfer/CHEO/NA12878-VR2-2/work/bcbiotx/tmpqh0xsvhr/NA12878-VR2-2.vcf.gz
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.8-0-ge9d806836): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid argument value 'GatherVcfs' at position 0.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1.

**Comment by roryk** [comment]
Sorry for the problem and thank you for writing such a nice issue. I'm not sure what is going on here. Could you please post your sample-level YAML file so I can look at the options that are set?

**Comment by roryk** [comment]
I think this issue is related: https://github.com/bcbio/bcbio-nextgen/issues/2257

**Comment by erinijapranckeviciene** [comment]
Yes, it seems that these two issues are related. This is my sample-level YAML
details:
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
      use_filtered: false
    mark_duplicates: true
    realign: true
    recalibrate: true
    save_diskspace: true
    tools_off:
    - gatk4
    tools_on:
    - gemini
    - gemini_allvariants
    - coverage_perbase
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    - qualimap_full
    variantcaller:
    - gatk-haplotype
    - samtools
    - platypus
    - freebayes
    vcfanno:
    - /projects/config/cheop.conf
    - /projects/analysis/cre/cre.vcfanno.conf
  analysis: variant2
  description: NA12878-VR2-2_CHEO_sample
  files:
  - /projects/CCM_transfer/CHEO/NA12878-VR2-2/input/NA12878-2_S5_R1_001.fastq.gz
  - /projects/CCM_transfer/CHEO/NA12878-VR2-2/input/NA12878-2_S5_R2_001.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: NA12878-VR2-2
fc_name: NA12878-VR2-2
resources:
  default:
    cores: 16
    jvm_opts:
    - -Xms750m
    - -Xmx3000m
    memory: 2G
upload:
  dir: ../final

**Comment by roryk** [comment]
Thanks-- hm. If you do `bcbio_nextgen.py --version`, what does it say? It looks to me like we should be catching this error and handling it but it doesn't look like that happened.

**Comment by erinijapranckeviciene** [comment]
It says 1.1.5

After reading through the related issues now I will try upgrade -u development again, since I think I did it  already maybe a couple of weeks ago. Will let you know if it fixed.

**Comment by roryk** [comment]
Thank you very much Erinija for updating the issue, glad that fixed it! We've been doing a bunch of development and when that wraps up we'll push a new release soon so stable will get this fix.
