### ISSUE TITLE
Incomplete `programs.txt` for WGS runs

### ISSUE THREAD

**Issue by ohofmann** [bcbio/bcbio-nextgen#2916]
Wanted to formalize the discussion around this with an issue. With the last bcbio release I am seeing a few tools that are missing version information from `programs.txt` upon completion of the workflow:

```
chanjo,
featurecounts,
mutect,
novosort,
rna-star,
variant-effect-predictor,
```

I don't think we're actively using any of these but maybe worth flagging.

**Comment by roryk** [comment]
Thanks, I think what is happening here is we are looking stuff up in a manifest if it exists, but not falling back and trying other methods if those programs don't exist in the manifest, so they are showing up blank unless we installed them via bioconda.

**Comment by roryk** [comment]
Will see if I can supplement the manifest with them next.

**Comment by ohofmann** [comment]
Thanks for looking into this!

**Comment by FedericoComoglio** [comment]
I think the version of `multiqc` is also missing from the list.

**Comment by roryk** [comment]
Thanks all, I fixed this and some other problems with that module. Let me know if you notice other things that should be in there and are not and I'll add them.
