### ISSUE TITLE
Evaluate updating to GATK 4.1.3.0

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2921]
"Evaluate", because it's not the first time there are regressions, but the new version comes with important fixes in Mutect2, so it might be worthwhile to update.

**Comment by lbeltrame** [comment]
Indeed we have it already. I'm not sure to keep this open, since it's already there.

**Comment by gabeng** [comment]
Hi Luca,

I was actually pretty happy that you opened this thread. We could compare notes, if you like. I am putting some numbers together right now.
We started with some germline comparisons of WES data, but we are most interested in the potential Mutect2 improvements.

**Comment by gabeng** [comment]
We are using a number of different dilutions of NA12878 in NA24385 (40%, 20%, 10%, 5%). The analysis is "tumor only" which is the clinical use case. We are most concerned about FDR.
In total, there are a little more than 1000 SNVs and 150 Indels in the target regions.

As with 4.1.2.0, the results are somewhat mixed and not really an improvement. As far as I can see the differences are caused by changes in the filtering in mutect2. They do not seem to be related to allele frequency. From my point of view I cannot really argue in favor of an update. What is your take?

# Mutect2 4.1.0.0

![grafik](https://user-images.githubusercontent.com/1035021/64004826-5440ed80-cb0f-11e9-8e3c-a61304ac6367.png)

# Mutect2 4.1.3.0
![grafik](https://user-images.githubusercontent.com/1035021/64005136-0a0c3c00-cb10-11e9-8a76-cfc610fae97d.png)

**Comment by ohofmann** [comment]
From our side we'd mostly be worried about missing true positives, so that FNR jump is not what I'd want to see...

**Comment by roryk** [comment]
Hi Ben and Oliver,

You all are the experts here-- so I defer to whatever you all think is the way to go. Hopefully some other folks will get in on the discussion. That is a nice test idea Ben. I am curious if there is something common about the false negatives/positives in general and the new false negatives with 4.1.3.0. Maybe we can address this by fiddling with some of Mutect's filtering parameters. Ben, if you could pass along the calls and some markup of which ones are false positives/negatives from each of the runs we could see if setting some flags might help out.

**Comment by lbeltrame** [comment]
Mutect2 now has dropped most filtering options in favor of a single parameter that can be tweaked for accuracy or sensitivity, IIRC. @gabeng Just to make sure I understand your graphs correctly, are they paired or tumor-only analyses?

**Comment by gabeng** [comment]
It is tumor only. I will try to differentiate between low-AF and germline variants. It may look better in a tumor-normal setting, when it is not critical that true germline variants are removed by aggressive filtering.

**Comment by lbeltrame** [comment]
Did you try filtering with already-known GNOMAD sites as mentioned in #2873 (not yet in bcbio, but up for discussion)? It should have at least some impact as far as I can see (known sites are not even taken into account). 
Although I'm not sure if it would improve the FNR.

**Comment by gabeng** [comment]
No, I have not yet tried filtering against gnomAD. I was afraid of creating yet another copy of that data set. 
In general, I would like to put filtering against populations or other data pools (e. g. PoN) at the very end of a pipeline, or even leave it optional. Those reference populations change over time and make re-analysis under identical conditions challenging. It also may not really reflect the performance of a variant caller.

**Comment by lbeltrame** [comment]
At least for my own data sets I had to put in place very aggressive filtering and a PoN because at least the Mutect2 defaults tend to (IMO) over-call variants in tumor only mode.

**Comment by roryk** [comment]
Thanks everyone for the discussion, sorry to be slow about getting around to this stuff. Luca could you share what you did?

**Comment by roryk** [comment]
Running https://github.com/bcbio/bcbio_validations/tree/master/somatic_trim, I see an increase in false negatives for indels over previous validations for mutect2 in tumor-normal mode, so the opposite problem with tumor-only:

![grading-summary-gm1](https://user-images.githubusercontent.com/414586/64632901-073f0000-d3c8-11e9-950c-e77e4448bddc.png)

Looking at tumor-only now.
