### ISSUE TITLE
bcbio-variation-recall ensemble crash

### ISSUE THREAD

**Issue by erinijapranckeviciene** [bcbio/bcbio-nextgen#2924]
Dear bcbio team, 

I came across a crash in bcbio-variation-recall ensemble, that I can't resolve. Unfortunately I can't share vcf files that are causing it. A tail  of the message below. I attach the log files and project yaml . 

[1489.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/3560432/1489.yaml.txt)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/3560433/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/3560434/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/3560435/bcbio-nextgen-debug.log)

Maybe you still be able to help even without vcfs. Thank you. 

```
[2019-08-29T18:51Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/opt/analysis/bcbio/anaconda/bin:"$PATH" &&  /opt/analysis/bcbio/anaconda/bin/bcbio-variation-recall ensemble --cores=16 --numpass 2 --names gatk-haplotype,samtools,platypus,freebayes --nofiltered /projects/bcbioresults/C4R_data/1489/work/bcbiotx/tmpv3qhrskz/1489-ensemble.vcf.gz /opt/analysis/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa /projects/bcbioresults/C4R_data/1489/work/ensemble/1489/gatk-haplotype/1489-gatk-haplotype-noeff-nomultiallelic.vcf.gz /projects/bcbioresults/C4R_data/1489/work/ensemble/1489/samtools/1489-samtools-noeff-nomultiallelic.vcf.gz /projects/bcbioresults/C4R_data/1489/work/ensemble/1489/platypus/1489-platypus-noeff-nomultiallelic.vcf.gz /projects/bcbioresults/C4R_data/1489/work/ensemble/1489/freebayes/1489-freebayes-noeff-nomultiallelic.vcf.gz
                   bcbio.variation.recall.main.main                          
                                                ...                          
                  bcbio.variation.recall.main/-main            main.clj:   30
                  bcbio.variation.recall.main/-main            main.clj:   33
               bcbio.variation.recall.main/-main/fn            main.clj:   34
                                 clojure.core/apply            core.clj:  665
                                                ...                          
           bcbio.variation.ensemble.intersect/-main       intersect.clj:  116
           bcbio.variation.ensemble.intersect/-main       intersect.clj:  140
   bcbio.variation.ensemble.intersect/ensemble-vcfs       intersect.clj:   86
bcbio.variation.ensemble.intersect/ensemble-vcfs/fn       intersect.clj:   88
                                                ...                          
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj:  165
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj:  189
                                  clojure.core/next            core.clj:   64
                                                ...                          
                                clojure.core/map/fn            core.clj: 2746
                                   clojure.core/seq            core.clj:  137
                                                ...                          
                                clojure.core/map/fn            core.clj: 2755
                               clojure.core/comp/fn            core.clj: 2569
   bcbio.variation.ensemble.intersect/get-rep-vc/fn       intersect.clj:   58
java.lang.Exception: Problem retrieving reference variant for {:chr "chr1", :start 912124, :refa "cg", :alta ["c"], :end 912126, :vc-indices (1 3)}: []
' returned non-zero exit status 1.
```

**Comment by naumenko-sa** [comment]
Hi Erinija!

From the error message it seems that bcbio-variation-recall cannot retrieve the very first variant from the vcf fle (chr1:912124).

No sure, why, I may suppose a chromosome naming issue.
Could you please try using the same config but with grhc37 reference as you usually do? 

You are using align: bwa, bcbio automatically will extract reads from the input bam and realign to grch37
(in fact in your project it is realigning to hg19 - see the log).

Sergey

**Comment by erinijapranckeviciene** [comment]
Thank you Sergey! I use hg19 since the bam is from alignment to hg19.  I started the same with GRCh37 build.

**Comment by chapmanb** [comment]
Thanks much for this report and working on debugging this. My guess here is that something complicated is happening at the problematic location it's erroring out at: chr1:912124. From the ref and alt it's looking for: `:refa "cg", :alta ["c"]` there are two possible issues:

- Different upper/lower case for alleles in the input VCFs.
- Different representations at the position (some deletions, some substitutions).

Without being able to see the VCFs, I'm guessing it is the case issue since we're not explicitly uppercasing or lowercasing variants. If you look at the VCFs at this position with bcftools view, does this explain the issue?

Thanks again for helping debug.

**Comment by erinijapranckeviciene** [comment]
Thank you for the comment. The coordinates are not right, the variant is at chr1:912125 called by freebayes (upper case ref/alt ) and samtools (lower case ref/alt) . 

Too complicated for me to go see the ensemble code. Stripped chr1 input to ensemble from four callers temporary here: 
[chr1.zip](https://github.com/bcbio/bcbio-nextgen/files/3561209/chr1.zip)

**Comment by chapmanb** [comment]
Thanks much for confirming it was a case issue and for the example files. There is now a fixed version of bcbio-variation-recall (0.2.5) that should fix this issue. You can upgrade your tools (`bcbio_nextgen.py upgrade --tools`) or just this dependency (`bcbio_conda install -c bioconda -c conda-forge bcbio-variation-recall`) to get the latest. If you then re-run in place it should hopefully handle this cleanly. Thanks again for the help debugging and hope this gets your analysis finished.

**Comment by erinijapranckeviciene** [comment]
Hello and thank you for update. I have upgraded --tools . The analysis stops at another place `Problem retrieving reference variant for {:chr "chrM", :start 72, :refa "G", :alta ("A"), :end 73, :vc-indices (0 1 3)}: []
`
Below are log files from this fail and previously shared chr1.zip has chrM variants too. Interestingly, I followed Sergey's suggestion to use GRCh37 instead of hg19 and - on **GRCh37** the analysis completed OK with the previous `bcbio-variation-recall` version. I start thinking  that these issues might be specific to **hg19**.  Once again , many thanks for your help! I am not in any rush , because I have results on GRCh37, but it would be nice to fix the hg19 too, because my alignment in on hg19. 

[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/3570020/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/3570021/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/3570022/bcbio-nextgen-debug.log)

**Comment by chapmanb** [comment]
Erinija;
Sorry about the continued problems. There was a bug in the fix that caused the additional issues and we've resolved both the case issue and the new problem in v0.2.6 of bcbio-variation-recall, which you should get with any updates. Hopefully it'll work cleanly for all genome versions going forward. Please let us know if you hit any other problems and thanks again.

**Comment by erinijapranckeviciene** [comment]
Thank you for your message and correction. I will rerun and will let you
know.
