### ISSUE TITLE
bcbio upgrade can't find conda package

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#2927]
Hi there,

I was trying to update our bcbio installation like this

`bcbio_nextgen.py upgrade -u stable --tools --data --cores 14`

However, I don't get far as it crashes with the following error:

> Traceback (most recent call last):
>   File "/bcbio_ii2/local/share/bcbio/anaconda/bin/conda", line 7, in <module>
>     from conda.cli import main
> ModuleNotFoundError: No module named 'conda'
> Upgrading bcbio
> Traceback (most recent call last):
>   File "/bcbio_ii2/local/bin/bcbio_nextgen.py", line 221, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 69, in upgrade_bcbio
>     _update_conda_packages()
>   File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 277, in _update_conda_packages
>     channels = _get_conda_channels(conda_bin)
>   File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 262, in _get_conda_channels
>     config = yaml.safe_load(subprocess.check_output([conda_bin, "config", "--show"]))
>   File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/bcbio_ii2/local/share/bcbio/anaconda/bin/conda', 'config', '--show']' returned non-zero exit status 1.

I understand, that the installer can't find conda anymore?

Thank you,

Lukas

**Comment by roryk** [comment]
Hi Lukas,

Sorry about this-- conda did a bunch of switching some of how the underneath stuff is built, and it seems like upgrading from a version older than that to the newer versions is broken. We've been recommending for folks running into these problems to wipe the old install and install a new one.

Brad's suggestion here is the workaround:

https://github.com/bcbio/bcbio-nextgen/issues/2889#issuecomment-515842898

**Comment by leiendeckerlu** [comment]
Hey Rory,

thanks for the quick follow up!

I decided to go for a fresh installation of bcbio but now run into another issue.

That's the command:

`python bcbio_nextgen_install.py /bcbio_ii2_v2/ --tooldir=/bcbio_ii2_v2/tooldir --genomes GRCh37 --aligners bwa --aligners bowtie2`

and I get the following error message:

# Installing into conda environment dv: deepvariant
Traceback (most recent call last):
  File "/bcbio_ii2_v2/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/bcbio_ii2_v2/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 90, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/bcbio_ii2_v2/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 495, in upgrade_thirdparty_tools
    cbl_conda.install_in(_get_conda_bin(), args.tooldir, package_yaml)
  File "/bcbio_ii2_v2/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 89, in install_in
    "{py_version} {pkgs_str}".format(**locals()), shell=True)
  File "/bcbio_ii2_v2/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    ...               "ls -l non_existent_file ; exit 0"],
subprocess.CalledProcessError: Command 'export BOTO_CONFIG=/ignoreglobal && /bcbio_ii2_v2/anaconda/bin/conda install -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'' returned non-zero exit status 1.
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/software/171020/software/python/3.6.4-foss-2017a/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bcbio_ii2_v2/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/bcbio_ii2_v2/tooldir', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1.

Can you give any advice on that?

Thank you,
Lukas

**Comment by leiendeckerlu** [comment]
addendum: Further up in the log I found the following entry:

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(696): An error occurred while installing package 'bioconda::deepvariant-0.8.0-py27h7333d49_0'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package bioconda::deepvariant-0.8.0-py27h7333d49_0
location of failed script: /groups/obenauf/bcbio_ii2_v2/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Your credentials are invalid. Please run
$ gcloud auth login

return code: 1

()
```

What is it about with those gcloud credentials?

**Comment by roryk** [comment]
Thanks, I don't know why deepvariant fails like this sometimes. If you continue with `bcbio_nextgen.py upgrade -u development --tools` does it finish the installation properly?

**Comment by leiendeckerlu** [comment]
No, unfortunately it gives the same error when trying 

`bcbio_nextgen.py upgrade -u development --tools --tooldir=/bcbio_ii2_v2/tooldir`

Any other suggestion?

**Comment by roryk** [comment]
Thanks, sorry I can't reproduce this. Do you have some gcloud settings maybe that are interfering? What happens if you run the suggested `gloud auth login` command?

**Comment by chapmanb** [comment]
To follow up on Rory's suggestion, there can be external environmental things with gcloud that interfere with this. Even though the DeepVariant data is freely available, the command line tools react badly if you're in a misconfigured environment. This is typically user specific with whomever is running the command. We haven't seen this one before, so any help you can provide to debug might help us automatically work around or at least offer useful suggestions.

**Comment by leiendeckerlu** [comment]
Thanks for the suggestions!

I double-checked my environment, which is pretty vanilla, but there are no gcloud options set and I also can't find any traces of gcloud parameters that are set by others on our HPC that could influence the installation.

When I execute the `gcloud auth login` command alone (while having loaded the bcbio environment) I get 

> -bash: gcloud: command not found

That is the current, specific error output that I get, no matter whether I try a fresh install or trying to fix a broken one with the upgrade command:

> Downloading and Extracting Packages
> google-cloud-sdk-261 | 36.8 MB   | ########## | 100%
> Preparing transaction: ...working... done
> Verifying transaction: ...working... done
> Executing transaction: ...working... done
> ERROR conda.core.link:_execute(696): An error occurred while installing package 'bioconda::deepvariant-0.8.0-py27h7333d49_0'.
> Rolling back transaction: ...working... done
> 
> LinkError: post-link script failed for package bioconda::deepvariant-0.8.0-py27h7333d49_0
> location of failed script: /groups/obenauf/bcbio_ii2_v3/anaconda/envs/dv/bin/.deepvariant-post-link.sh
> ==> script messages <==
> <None>
> ==> script output <==
> stdout:
> stderr: Your credentials are invalid. Please run
> $ gcloud auth login
> 
> return code: 1
> 
> ()

Anything else I can provide you with that might be helpful? I really value your efforts helping me getting this sorted out!

**Comment by roryk** [comment]
Thanks-- I'm not understanding why this is happening. Do you have stuff in:  `~/.gsutil` that could be interfering?

If you run:
`/bcbio_ii2_v3/anaconda/envs/dv/bin/gcloud auth login`

does that give you a more informative error?

**Comment by leiendeckerlu** [comment]
`/bcbio_ii2_v3/anaconda/envs/dv/bin/gcloud auth login`

> -bash: /bcbio_ii2_v3/anaconda/envs/dv/bin/gcloud: No such file or directory

also just manually checked, there is no gcloud binary present in the /bin/ folder.


I had files in `~/.gsutil` but deleted the whole folder now - still give the same error...

**Comment by roryk** [comment]
Thanks-- I think that might be the problem. Does `bcbio_conda install -c bioconda google-cloud-sdk -n dv` complete install `gsutil` and `gcloud` into that directory? It looks like the google-cloud-sdk package is missing.

**Comment by roryk** [comment]
Heya, did this ever get resolved or did you end up giving up?

**Comment by leiendeckerlu** [comment]
Hey, 

sorry for not reporting back so far. I'm currently working together with our HPC support on trying to get that fixed. Will update here as soon as we managed.

Thanks,
Lukas

**Comment by roryk** [comment]
Thanks Lukas!

**Comment by leiendeckerlu** [comment]
Hey,

so our HPC support was now able to install it successfully but on different infrastructure. 

So the end of the story is, that I can't provide details why it did not work for me in the first place and what exactly caused the gcloud download error - but I'm all set now.

Thanks a lot for helping me troubleshoot.

Lukas

**Comment by roryk** [comment]
Hi Lukas,

Thanks so much for following up-- I'm glad it ended up working!
