### ISSUE TITLE
Genome directory contains bgzipped FASTA files but the uncompressed ones are referenced in loc files

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2930]
Very long title: I recently started doing some alignments for hg38 and I found that `hg38.fa` was missing from the directory in the genome. In its place there was a bgzipped file. The problem is that the `loc` files in the configuration still reference the non compressed `hg38.fa` and this breaks, among other things, alignment. 

Uncompressing it only solved the solution temporarily, as it was recompressed and deleted on the next bcbio update.

Besides I'm not sure if all the tools bcbio uses support bgzipped FASTA files.

**Comment by roryk** [comment]
Hi Luca,

Sorry-- this was a bug I introduced when adding support for hg38 with STAR. I fixed it but if you updated in the interim you'd have had this problem. Thanks!
