### ISSUE TITLE
Lossy CRAM archive option not working?

### ISSUE THREAD

**Issue by sam-ber** [bcbio/bcbio-nextgen#2936]
I tried to use the archive option as specified in the [documentation](https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#post-processing). 
In our case the option `[cram-lossless]` seems to work as intended, but `[cram]` unfortunately throws an error [0], a `CRAM` file is generated nonetheless. 
I suspect the quality score binning by [bamUtil](https://github.com/statgen/bamUtil) is causing the problem, because the actual compression to cram (using only samtools, without the binning) after the try/except in cram.py seem to work. 

Have other users already encountered the same problem? I have seen the comment 
https://github.com/bcbio/bcbio-nextgen/issues/2734#issuecomment-520844794, stating the `archive` option works, but not specifying which.

Are there any plans to use another tool for quality score binning instead of bamUtil as hinted in the interesting discussion https://github.com/bcbio/bcbio-nextgen/issues/2531#issuecomment-427403883? 

samtool itself currently supports only [lossy read names](https://www.htslib.org/doc/samtools.html) and in the above-mentioned discussion [crumble ](https://github.com/jkbonfield/crumble) was mentioned.

Any feedback is very welcome

[0] Error message using archive option [cram] from `bcbio-nextgen.log` :

> [2019-08-14T10:19Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/share/bcbio-nextgen/anaconda/bin/bam squeeze --in /bioinf-data/bcbio/work/align/NA12878/NA12878-sort.bam --out -.ubam --keepDups --binQualS=2,10,20,25,30,35,70 --binMid | /usr/local/share/bcbio-nextgen/anaconda/bin/samtools view -T /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -@ 16 -C -x BD -x BI -o /bioinf-data/bcbio/work/bcbiotx/tmp5FA5Np/NA12878-sort.cram
Number of records read = 93864852
Number of records written = 93864852
[E::bgzf_read] Read block operation failed with error 2 after 176 of 280 bytes
[main_samview] truncated file.
' returned non-zero exit status 1

**Comment by roryk** [comment]
Thanks, this should be working fine-- I'm guessing that the command failed due to something unrelated. If you rerun your run, does it fail here again? You could also try running ` /usr/local/share/bcbio-nextgen/anaconda/bin/bam squeeze --in /bioinf-data/bcbio/work/align/NA12878/NA12878-sort.bam --out -.ubam --keepDups --binQualS=2,10,20,25,30,35,70 --binMid | /usr/local/share/bcbio-nextgen/anaconda/bin/samtools view -T /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -@ 16 -C -x BD -x BI -o out-file.cram` outside of bcbio and seeing if it fails.

**Comment by chapmanb** [comment]
The `cram` lossy compression is unfortunately still in the same state as the previous discussion we didn't come up with a good approach to tackle it based on the existing tools. Explicit software quality binning has also become a bit less useful the newer machines output binned values.

Practically, what you're seeing is that `bam squeeze` can be pretty unreliable and we just fall back to standard CRAM when it dies:

https://github.com/bcbio/bcbio-nextgen/blob/05f088353d2b3498f6f77006f0fcafead784dcb7/bcbio/bam/cram.py#L40

Lossless CRAM provides pretty good compression relative to BAM so we haven't yet got into exploring new tools to work around this. Sorry about that, and hope that the lossless CRAM will work okay for your case.

**Comment by roryk** [comment]
Thanks Brad and @sam-ber. I added a blurb about this to the documentation to direct folks to mainly use ``cram-lossless``.

**Comment by sam-ber** [comment]
Thank you Brad, for your explanation. 
I agree, quality score binning is less useful when newer machines output already binned values and as you pointed out, the compression rate of lossless CRAM vs BAM is already pretty impressive. 
Furthermore, losing information through binning does not feel good to me (which is why I wanted to see the difference between lossy and lossless CRAM in crunchy numbers).

Thanks Rory for updating the documentation!

For posterity: Rerunning the whole analysis using bcbio and repeating only the specific command both lead to the identical error message. 
It looks like `bam squeeze` does not produce a valid uBam file.

**Comment by roryk** [comment]
Thanks for following up @sam-ber, that is helpful information!
