### ISSUE TITLE
Is there any fusion caller from DNA sequencing data?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2939]
Hi, I found that these fusion_caller parameter can be used to detect gene fusion using a few caller. However, I think these caller are all based on RNA-seq data. Is there any fusion caller from DNA sequencing data?

**Comment by roryk** [comment]
Hi @hliu2016,

Sorry, I missed this question. Structural variant callers should be able to call fusions, but they won't be marked as fusions, they'll be marked as various structural variant types.
