### ISSUE TITLE
Unable to find Atropos

### ISSUE THREAD

**Issue by keenhl** [bcbio/bcbio-nextgen#2942]
I have did a new install of bcbio with datatarget snrnaseq, and did a tools update bcbio_nextgen.py upgrade --tools

However, I get the following error.  I can find atropos in the tools/bin directory. 

bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'atropos' {} 'atropos'

Any thoughts about why bcbio is not finding Atropos?

Thanks.

**Comment by roryk** [comment]
Thanks, closing this as this should solve the problem!
