### ISSUE TITLE
toolz module not found after bcbio update

### ISSUE THREAD

**Issue by mbootwalla** [bcbio/bcbio-nextgen#2943]
Hello bcbio team,

I updated bcbio using the command `./bcbio_nextgen.py upgrade -u development` and when I tried to run a pipeline that previously worked I get an error that says `ModuleNotFoundError: No module named 'toolz'`. 

I tried re-running the update but I keep getting this same error and can't run anything. Kindly let me know what I can do to fix this.

Thanks,

Moiz

**Comment by roryk** [comment]
Sorry about that, if you haven't updated in a while, conda went through a ton of changes which unfortunately breaks our upgrading and can get the repo in a bad state. We've been recommending folks reinstall-- you can reinstall without removing the genome data, and just reinstall the code and the tools.

```
https://github.com/bcbio/bcbio-nextgen/issues/2889#issuecomment-515842898
```

**Comment by roryk** [comment]
Thanks, the workaround to fix a broken repo should work. Sorry for the problems, we are hoping that the upgrading will have settled down now and things should work more smoothly going forward.

**Comment by mbootwalla** [comment]
Thanks for following up @roryk. I haven't had a chance to test the early workaround that you suggested. Currently doing a fresh install of bcbio and will test that. Will report back if I run into any issues.

**Comment by roryk** [comment]
Thanks! Hopefully it will be all set now, sorry for the problems.
