### ISSUE TITLE
Could not process input file from sample configuration

### ISSUE THREAD

**Issue by keenhl** [bcbio/bcbio-nextgen#2946]
Good morning all, 

I recently did a new install of the srnaseq pipeline and am getting the following error.

Here is the error message

ValueError: Could not process input file from sample configuration. 
/Shared/Bioinformatics/data/test_bcbio/work/seqcluster/prepare/seqs.fastq
Is the path to the file correct or is empty?
If it is a fastq file (not pre-aligned BAM or CRAM), is an aligner specified in the input configuration?

The file seqs.fastq does exist, but is empty.

Here is the entire configuration file.

details:
- algorithm:
    adapters:
    - GCACCCGAGAATTCCA
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirdeep2
    species: hsa
  analysis: smallRNA-seq
  description: 10_18-063_100_20190114000_S10_L003
  files:
  - /Shared/Bioinformatics/data/keenhl/gonsalves_small/fastq/10_18-063_100_20190114000_S10_L003_R2_001.fastq.gz
  genome_build: hg38
fc_name: test_bcbio
upload:
  dir: ../final

Any thoughts?  Thank you.

**Comment by roryk** [comment]
I think your run is messed up in other ways-- it looks like you only have one of two reads here (you can see its R2 but where is it's paired file R1?) `/Shared/Bioinformatics/data/keenhl/gonsalves_small/fastq/10_18-063_100_20190114000_S10_L003_R2_001.fastq.gz`

I'm guessing something is up with your inputs.

**Comment by keenhl** [comment]
Thanks.  You're right.  What I had done was take a configuration file that had previously worked and edited it to process 1 sample as a test of the new installation.  If I use the entire configuration file, it is working, at least at to this point.

**Comment by roryk** [comment]
Great! Thanks for following up.
