### ISSUE TITLE
bcbio in not exiting the main job 

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2950]
Dear Bcbio team,

I submitted around 150 RNASeq samples using LSF as scheduler and for few samples bcbio didn't even started control & engine jobs. When I kill the main job & resubmit again, it is running fine. But when we submit in large scale it will become difficult to every time check jobs which were not started and resubmit again. Could you please help me to resolve this issue?

In addition,bcbio is not shutting down even though results were moved to final directory for some jobs.  Stiil job is in RUN state from last week. I checked with IBM LSF support team, I provided them last three lines from bcbio main log & LSF jobid.

Here is the response

2019-09-11 10:08:28.239 [IPClusterStop] Using existing profile dir: 'test/scratch/log/ipython'
2019-09-11 10:08:28.500 [IPClusterStop] Stopping cluster [pid=31836] with [signal=<Signals.SIGINT: 2>]
[2019-09-11T07:08Z] nsnode29: Timing: finished

###########
I have checked the output of the three PIDs, and all of their CMD are bcbio programs. That means in the operation system the user's bcbio program is not finished yet. That's why LSF also thinks the program is not complete. So, LSF has done its job perfectly on this issue.
As for why the program does not quit, we need to find the reason from the program itself.

Like the CMD of PID = 31836:

$HOME/BCBIO / v1 .1 .5 / anaconda / bin / python - E - c
import resource;
cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC);
target_proc = min(max_proc, 10240) if max_proc > 0
else 10240;
resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc));
cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE);
target_hdls = min(max_hdls, 10240) if max_hdls > 0
else 10240;
resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls));
from ipyparallel.apps.ipclusterapp
import launch_new_instance;
launch_new_instance() start--daemonize = True--IPClusterEngines.early_shutdown = 240--delay = 10--log - to - file--debug--n = 1--BcbioLSFEngineSetLauncher.cores = 8--BcbioLSFEngineSetLauncher.resources = 'P=bcbio-0700479021_S61_L006'--BcbioLSFEngineSetLauncher.mem = '32.1'--BcbioLSFEngineSetLauncher.tag = '0700479021_S61_L006'--IPClusterStart.engine_launcher_class = cluster_helper.cluster.BcbioLSFEngineSetLauncher--LSFLauncher.queue = 'normal'--cluster - id = 3 b515802 - 130 f - 45 db - 96e4 - 26 c7ddadb3cf--BcbioLSFControllerLauncher.mem = ''--BcbioLSFEngineSetLauncher.tag = '0700479021_S61_L006'--BcbioLSFControllerLauncher.tag = '0700479021_S61_L006'--BcbioLSFControllerLauncher.cores = 1--BcbioLSFControllerLauncher.resources = 'P=bcbio-0700479021_S61_L006'--IPClusterStart.controller_launcher_class = cluster_helper.cluster.BcbioLSFControllerLauncher--profile - dir = test / scratch / log / ipython
#####################

Could you please help me to resolve this issues?

Thanks In Advance
Fazulur Rehaman

**Comment by roryk** [comment]
Hi Fazulur,

Bcbio won’t make an engine and controller job for each sample— it will make
one controller job and a set of engines but not one for each sample.

Bcbio not always killing all of the resources is a known problem on some
systems and schedulers, we haven’t been able to figure out why this happens
sometimes.

**Comment by roryk** [comment]
Thanks, this should be answered. Sorry to not have a great solution for killing orphan bcbio jobs; they will eventually die, but it will take a while.
