### ISSUE TITLE
running bcbio-next gen single cell to start in the middle

### ISSUE THREAD

**Issue by dam39** [bcbio/bcbio-nextgen#2952]
I tried running the single cell seq pipeline in bcbio-nextgen, and it worked pretty well for two days. It got to the point of generating bam and bam.bai files  for the different libraries but as it generated the dupes-mat.full and mat.full files, the operation timed out and was killed and so the pipeline never worked till the end. I have a lot of the intermediate files, so I don't want to start from the top. Is there anyway to figure out what the exact commands executed by the pipeline are? I can't seem to figure that out. All I know are the commands that ran as they are in the log files, but how to proceed from there? Maybe a log file of a single cell job that ran to completion would help.
Thanks a lot!

**Comment by roryk** [comment]
Hi @dam39,

Thanks for the question! You can just restart bcbio and it will pick up where it left off. Each step in bcbio is transactional, meaning it will only write files once a step is completed, so there are never partially-created files even if it dies in the middle of processing. It will also check if steps are already completed and skip them. So you can just restart and you should be all set and it will pick up at the last completed step.

**Comment by dam39** [comment]
Excellent! Thanks!
