### ISSUE TITLE
question about the ensemble variant calling

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2953]
Hi, I have run three variant caller, including mutect2, vardict, freebayes, to call variants on tumor-only samples. the numpass parameter is set 2, i.e. when two callers support one mutant then output it. However, I found that some SNVs, such as rs113488022 and COSM14049, are all called out by mutect2 and vardict, but not by freebayes. The ensembl vcf file does not include these mutants. Why these mutants supported by two caller are not included in the final callset?

> details:
>   - analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       trim_reads: atropos
>       adapters: [truseq2, polya, illumina]
>       variantcaller: [vardict, mutect2, freebayes]
>       variant_regions: /ngs/zhengu/3214551_Covered.bed
>       mark_duplicates: false
>       recalibrate: false
>       realign: false
>       effects: snpeff
>       remove_lcr: true
>       min_allele_fraction: 1
>       ensemble:
>         numpass: 2
>         use_filtered: false

**Comment by roryk** [comment]
Hi @hliu2016,

It is hard to say without seeing the variant, if you could post the variants from the individual callers we could figure it out. Are you sure the variant is set to PASS for all of the callers?

**Comment by hliu2016** [comment]
@roryk 
We are right! These variants called by mutect2 is set to `clustered_events` of the FILTER column, while vardict set these variants to PASS. I guess this is the cause leading to missing of these variant in the ensemble vcf file. I wonder if the clustered_events means PASS or not?

**Comment by roryk** [comment]
Hi @hliu2016,

The FILTER column in VCF is the reason why it was filtered if it is not set to PASS see the [VCF spec, section 1.4.1](https://samtools.github.io/hts-specs/VCFv4.2.pdf) for more information. So that is definitely why this variant isn't making it through the ensemble calling.

**Comment by roryk** [comment]
I think this is answered, thanks!
