### ISSUE TITLE
Is there any parameter of mutect2 to get clustered_events variants passed

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2957]
Hi, I am using mutect2 to call somatic variant for tumor-only samples. I found that quite a few real variants are filtered out by `clustered_events `  and thus the callset misses these varaiants. I wonder if there is any parameter of mutect2 can be passed from bcbio to adjust the filter to get these variants call out. Thanks a lot.

**Comment by chapmanb** [comment]
Sorry about the issues with filtered variants that you've confirmed to be real. Practically this is a good question for the GATK and MuTect2 team, as they might have better insight into why the filter gets applied and how you can adjust it to account for your case. It's hard to offer general advice, but if you could put together a small reproducible example where this happens the MuTect2 team might be able to offer tuning advice for `FilterMutectCalls`. Hopefully that'll give you both an idea of tuning and also why your calls trigger these filters. Hope this helps.

**Comment by gabeng** [comment]
Hi Brad,

would it be possible to pass on command line parameters to `FilterMutectCalls` from bcbio like `--max-events-in-region`? I am not sure if there will ever be a "one-size fits all" solution for all kinds of somatic variant calling.

**Comment by hliu2016** [comment]
@chapmanb 
I have noticed that there are discussions about the `clustered_events ` filter of mutect2 tends to filter real vaiants. The parameter `--max-events-in-region` could relax the FilterMutectCalls to pass more varaints. If there is some method to pass this parameter from bcbio to  FilterMutectCalls  would be great!

**Comment by chapmanb** [comment]
Thanks for investigating useful parameters and for the helpful suggestion. In the latest development you can use the resources section (https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources) of the configuration to add in custom options like this:
```
resources:
    mutect2_filter:
      options: ["--max-events-in-region", "4"]
```
Hope that helps resolve the filtered variants you're seeing. Thanks again for all the feedback and discussion.

**Comment by gabeng** [comment]
Perfect, thanks so much Brad!
