### ISSUE TITLE
AssertionError: Require normal BAM for Sentieon TNhaplotyper

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2958]
Hi, I am trying using Sentieon  TNhaplotyper to call somatic variant for tumor-only samples. But the pipeline complains this error:

> AssertionError: Require normal BAM for Sentieon TNhaplotyper

My yaml file is as below:

> details:
>   - analysis: variant2
>     genome_build: hg38
>     algorithm:
>       aligner: bwa
>       trim_reads: atropos
>       adapters: [truseq2, polya, illumina]
>       variantcaller: [vardict, mutect2, varscan, freebayes, mutect]
>       svcaller: [lumpy, manta, cnvkit, delly]
>       variant_regions: /ngs/zhengu/3214551_Covered.bed
>       mark_duplicates: false
>       recalibrate: false
>       realign: false
>       effects: snpeff
>       remove_lcr: true
>       min_allele_fraction: 1
>       ensemble:
>         numpass: 3
>         use_filtered: false

**Comment by roryk** [comment]
Sorry about that— we don’t support the tumor only mode for TNhaplotyper;
for it to work you’d need to supply a panel of normals.

**Comment by hliu2016** [comment]
@roryk 
Thanks for your reply. It is said that Sentieon TNhaplotyper uses the same probability model of gatk but run very faster than gatk. So, I should use TNhaplotyper rather than mutect2 in calling somatic variants?

**Comment by roryk** [comment]
Hi @hliu2016,

We haven't looked at the TNhaplotyper in a while and don't have a good idea of how well it is doing,  I would just use mutect2.
