### ISSUE TITLE
mark duplicates using bamsormadup corrupt

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2959]
I am using cancer variant calling pipeline on hg38 assembly. When I do not set the mark_duplicate parameter the pipeline run smoothy, but If I set it to true then corrupt due to the following error: 

> /bio/bcbio/galaxy/../anaconda/bin/bamsormadup inputformat=sam threads=12 tmpfile=/ngs/zhengu/project2/work/bcbiotx/tmptkFN4S/zhangyajuan-sort-sorttmp-markdup SO=coordinate indexfilename=/ngs/zhengu/project2/work/bcbiotx/tmptkFN4S/zhangyajuan-sort.bam.bai > /ngs/zhengu/project2/work/bcbiotx/tmptkFN4S/zhangyajuan-sort.bam
> ' returned non-zero exit status 139
>

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. Unfortunately this is not enough information to remotely debug the issue with your file. This line tells us bamsormadup fails but the traceback earlier on should have additional information about the cause of the failure that would be helpful. It would also be useful to know your configuration and input, as `mark_duplicates: true` is the default for variant calling pipelines. Is it possible you're hitting some data specific error causing the failure here? Hope this helps for debugging.

**Comment by hliu2016** [comment]
@chapmanb 
This error looks very strange. Maybe it just occurred occasionaly. When I run the pipeline again, it went through this error. FYI, I have uploaded the whole log information.

[log.txt](https://github.com/bcbio/bcbio-nextgen/files/3669330/log.txt)

**Comment by chapmanb** [comment]
Thanks for following up with the full error message. It looks like bamsormadup is segfaulting here without a clear reason why. If it's intermittent there is likely something system specific on the machine you're running on. Hopefully it'll be more stable going forward, and thanks again for following up.
