### ISSUE TITLE
ChIP-Seq macs2 bedgraph need to be sorted

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#2963]
Hi,
 this is a suggestion.
Among the output files of macs2 there are two bedGraph files usually named as follows: _SAMPLENAME_treat_pileup.bdg.gz_ and _SAMPLENAME_control_lambda.bdg.gz_ 
They seem not be sorted, however some downstream analysis, such as converting to bigwig, require that. 
Could be possible to sort them, for example with bedSort, before saving in the final folder?

Many thanks,
Laura

**Comment by roryk** [comment]
Hi Laura,

Thanks for the suggestion. We are currently working on improving the ChIP-seq pipeline, so this is good timing. I will make sure those files are sorted.

**Comment by LMannarino** [comment]
Hi Rory,
 that sounds good!

Many thanks,
Laura

**Comment by roryk** [comment]
Thanks! We can leave it open until I get around to doing it. It is a good reminder. Also, it would be helpful to get feedback regarding how the ChIP-seq pipeline is doing. We have a bunch of improvements to make and outside feedback helps us triangulate on the best solutions.

**Comment by LMannarino** [comment]
Oh, I'm sorry! 
Yeah, sure. I'm going to use the ChIp-Seq pipeline again soon. I'll give my feedbacks and contribution where I can.

Thanks again

**Comment by roryk** [comment]
No worries. Thanks!

**Comment by roryk** [comment]
Hi Laura,

Sorry for taking so long getting to this. I added a sort before compressing those files, so this should be all set.
