### ISSUE TITLE
starting alignment

### ISSUE THREAD

**Issue by rachel-oren** [bcbio/bcbio-nextgen#2964]
Good afternoon,
I am trying to run a pipeline to analyze fastq files. This is only the second time I have used this pipeline. I submitted the batch to the cluster I am working with, but it seems like it might be stuck,  but I am not sure. 
In /alignment/work/log if i tail bcbio-nextgen-debug.log, this is the last update: Configuring 24 jobs to run, using 1 cores each with 3.00g of memory reserved for each job

It has been on this for the past 3 hours, which seemed off to me. If someone could let me know if this is normal, and it is just taking this long to configure, or if this does indeed seem wrong, I would greatly appreciate it. 

Thanks!
Rachel

**Comment by roryk** [comment]
Hi Rachel,

If your cluster is very busy, it can take a long time for the jobs to start, unfortunately. If you look at your jobs on your scheduler, I think that you'll see the engine job is pending.

**Comment by naumenko-sa** [comment]
Hi @rachel-oren !

Are you running 
a **multicore** (one node,  `bcbio_nextgen.py ../config/bcbio.yaml -n`) 
or **multinode** (ipython, `bcbio_nextgen.py bcbio_sample.yaml -t ipython -n 12 -s lsf -q queue`) job?

If the latter, you might want to try a multicore option first.

Sergey

**Comment by rachel-oren** [comment]
Hi Sergey,

I am running on a multicore node. It actually just started to run a few moments ago.. I guess I was just a bit overly eager – my apologies, but thank you for the responses.

Best,
Rachel

**Comment by roryk** [comment]
No worries! Glad your job is going.
