### ISSUE TITLE
Missing CADD annotations

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#2965]
Hi everyone,

I'm experiencing an issue that at first sight seemed very similar to [#1624](https://github.com/bcbio/bcbio-nextgen/issues/1624). CADD annotations are not downloaded when upgrading bcbio with

```
bcbio_nextgen.py upgrade -u skip --genomes hg38 --data --datatarget cadd
```

Our `gemini` installation is complete and in fact a call to

```
bcbio_nextgen.py upgrade -u skip --genomes hg38 --data --datatarget cadd --datatarget gemini
```

does not download any new data (`bcbio-nextgen data upgrade complete.`). 

Could you please look into this?
Thanks!

Federico

**Comment by chapmanb** [comment]
Federico;
Thanks for the report and apologies about the confusion. The latest versions of GEMINI that are genome independent (not tied to hg19/GRCh37) do not have this kind of support for CADD, so the functionality had been disconnected in bcbio. I've removed the remaining references from the documentation to avoiding confusion. Hopefully one of the other metrics from GEMINI are a useful proxy, or applying CADD annotations post-bcbio works for your needs. Sorry to not have this available in bcbio.

**Comment by FedericoComoglio** [comment]
Thank you for the clarification, Brad.
