### ISSUE TITLE
reference not found, exiting 

### ISSUE THREAD

**Issue by rachel-oren** [bcbio/bcbio-nextgen#2967]
Hello again,

My pipeline has stopped running, the last entry in debug.log was AssertionError: /n/scratch2/ro76_RNAseq/reference/Homo_sapiens.GRCh38.cdna.all.fa.gz was not found, exiting.

However, Homo_sapiens.GRCh38.cdna.all.fa.gz is located in my reference directory which is structured as suggested. I am wondering if I should just remove the references, redo the wgets and try to restart? Or is there something else that could be the problem?

I have included a screen shot as well in case that is useful.

<img width="1012" alt="Screen Shot 2019-10-03 at 7 41 43 AM" src="https://user-images.githubusercontent.com/54285903/66124330-16256680-e5b2-11e9-9b9d-3d94d3d560bd.png">

Thanks again!!

**Comment by rachel-oren** [comment]
Good afternoon,

Sorry to reach out again, I was wondering if anyone had seen this before/ might know what could have gone wrong/ ways to trouble shoot. Alternatively, I could redo the wget as stated and try again, but I am curious in the event that this occurs again. 

Thank you!

**Comment by roryk** [comment]
Hi Rachel,

Your run is pointing to the file: `/n/scratch2/ro76_RNAseq/reference/Homo_sapiens.GRCh38.cdna.all.fa.gz` which does not exist. Did you mean `/n/scratch2/ro76_plate2/reference/Homo_sapiens.GRCh38.cdna.all.fa.gz`.

**Comment by rachel-oren** [comment]
You are 100% correct, so sorry for bothering you with this… simply forgot to change one filepath in my yaml file, and just couldn’t see the difference.

To confirm, because bcbio logs its actions, when I resubmit the job, it should be able to pick up where it left off, correct?

Thank you again!!

**Comment by rachel-oren** [comment]
Hi Rory,

I edited the .yaml file that still had an old file path in it and began running the pipeline again. However, it unfortunately just exited with the same error. I am not sure what else could be directing it to the old file path.. any ideas? Do you think something might be corrupted now and I should delete what it has done and re submit the job fresh?

Thank you,
Rachel

**Comment by roryk** [comment]
Hi Rachel,

Which YAML file did you edit? The one you need to edit is the one in the config directory, and it will need to get edited for every entry.

**Comment by roryk** [comment]
I checked and I think this is all set, it looked like maybe the right YAML file didn't get edited but it is okay now.

**Comment by rachel-oren** [comment]
Hi Rory,


Apologies for not responding! I had edited the correct yaml but did not run : bcbio_nextgen.py -w template O2.yaml alignment.csv merged again so the information hadn’t been updated in config… but it should be fine now on that end. It has been configuring a job for about 6 hours now, but I think that is due to traffic in 02.

Best,
Rachel

**Comment by roryk** [comment]
No worries! Glad it seems to be working now.

**Comment by rachel-oren** [comment]
Hi Rory,


Sorry to be a pain.. I am not sure what the problem is with this go around, but the pipeline has still not started up again. The last log was at 7:44 this morning: [2019-10-04T07:44Z] compute-e-16-199.o2.rc.hms.harvard.edu: Configuring 1 jobs to run, using 16 cores each with 64.1g of memory reserved for each job

And it has not logged anything since. Additionally, I have checked if there were any pending jobs, in the event that this log was stating that bcbio was queueing a new job, but that is not the case. Any ideas on what might be preventing any progress?

Thanks again,
Rachel
