### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by HyunjunNam** [bcbio/bcbio-nextgen#2968]
I had error message during first time installation of bcbio on to my MacBook.

------------
```
# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

**PackagesNotFoundError: The following packages are not available from current channels:**

  - bcbio-nextgen==1.1.5

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
------------

**Comment by roryk** [comment]
Sorry @HyunjunNam,

bcbio doesn't work on OSX, not all of the tools will be able to be installed. You can run things if you need to run it on a Mac by making a virtual machine and doing that instead.

**Comment by HyunjunNam** [comment]
I see. bcbio doesn't work on OSX anymore...

The description of running bcbio by virtual machine is here?
https://github.com/bcbio/bcbio-nextgen-vm

And is there any things to know before running it on virtual machine?

Best,
Hyunjun

**Comment by roryk** [comment]
bcbio-vm is for running it on Amazon. If you need to run it locally, you'd want to do something like make a virtual machine with Vagrant and install it into there. It will be a gigantic pain to get it working though. bcbio is mostly designed to be run on compute clusters, or a local UNIX machine. You can run it on AWS/Google cloud/etc as well, but it will require some setup on your part.
