### ISSUE TITLE
Installation problems with system-wide conda 

### ISSUE THREAD

**Issue by karl616** [bcbio/bcbio-nextgen#2969]
I'm trying to install bcbio-nextgen to a local folder. I have tried this:

```
python bcbio_nextgen_install.py $PWD/bcbio --cores 1 --tooldir $PWD/tools --datatarget rnaseq --genomes hg38 --aligners star --isolate --distribution centos
```

after installing the python3 environment I get the following error:

```
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate python3
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Traceback (most recent call last):
  File "/path/bcbio-test-space/local_installation/bcbio/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/path/bcbio-test-space/local_installation/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 90, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/path/bcbio-test-space/local_installation/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 495, in upgrade_thirdparty_tools
    cbl_conda.install_in(_get_conda_bin(), args.tooldir, package_yaml)
  File "/path/bcbio-test-space/local_installation/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 48, in install_in
    conda_envs = _create_environments(conda_bin, packages)
  File "/path/bcbio-test-space/local_installation/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 236, in _create_environments
    out[addenv] = [x for x in conda_envs if x.endswith("/%s" % addenv)][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/path/bcbio-test-space/local_installation/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--cores', '1', '--tooldir', '/path/bcbio-test-space/local_installation/tools', '--datatarget', 'rnaseq', '--genomes', 'hg38', '--aligners', 'star', '--isolate', '--distribution', 'centos', '--data']' returned non-zero exit status 1
```

I think the problem is that I have central installation of conda that I normally use. I don't have write permissions to the installation folder and no space in the home folder why I have specified a separate `envs_dirs`. I suspect that this take precedence and disrupts the bcbio installation.

My line of reasoning is based on activating the bcbio conda instance:

```
source bcbio/anaconda/bin/activate
conda info --all --json
...
"envs_dirs": [
    "/path2/conda/envs",
    "/path/bcbio-test-space/local_installation/bcbio/anaconda/envs",
    "/home/user/.conda/envs"
  ],
...
```

All new environments will be installed to `/path2/conda/envs`, but bcbio only accepts that they reside within the installation folder. I think this comes down how cloudbiolinux works and I have raised an issue there as well:

https://github.com/chapmanb/cloudbiolinux/issues/324

**Comment by roryk** [comment]
Thanks-- is there a way you can clean your PATH out so you don't have the conda you normally use activated before installing?

**Comment by karl616** [comment]
Running it without the "normal" conda active AND commenting out the envs_dirs section from the .condarc file seems to be working. At least it passes the previous breaking point.

I'm not sure that I can get it to work if I would install the package from bioconda though
(`conda install bcbio-nextgen`)

**Comment by roryk** [comment]
Thank you-- we don't support just installing the package from conda as it just installs the code. The  automated installer handles installing of everything else, so that's the way to go to install bcbio.

**Comment by roryk** [comment]
Glad this is working, closing since this seems all set.

**Comment by karl616** [comment]
I don't agree. Finding a workaround is not the same thing as solving the
problem.

**Comment by roryk** [comment]
Hi Karl,

Sorry but it is very hard to solve every problem for every computing environment on every dataset for every type of analysis folks have since we are doing this for free, all of the tools are constantly changing and there are only a few of us doing it. You will find a lot of workarounds in the issues and in the code base, unfortunately!

**Comment by karl616** [comment]
I didn't need help to find a workaround. I tried to point out a design-flaw in how you handle conda and conda environments, but I will think twice before doing so in the future.

**Comment by roryk** [comment]
Hi Karl,

Sorry about that-- we do appreciate people posting issues and solutions, so please do keep posting if you run into issues. It's helpful to have the workaround in the issue in case other folks run into it. This type of problem is similar to folks having other versions of python libraries in their PATH, it is hard to fix for every environment, so we unfortunately have to suggest workarounds like this. If it is something that turns into a common problem we'll see if we can fix it though. Thanks again!

**Comment by keenhl** [comment]
Karl,

Successfully finding a workaround is solving the immediate problem.  Sometimes that's the best that can be done.   Just be glad that your installation is working.
