### ISSUE TITLE
New Bcbio release

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2973]
It's been 6 months since the latest release, v1.1.5, and several bug fixes have been made since then. Is there a plan for a new release in the near future and will there be a new Docker image release on quay.io as well?

**Comment by roryk** [comment]
Hi @amizeranschi,

Yes to both, we'll be pushing a new release soon.

**Comment by amizeranschi** [comment]
That's great news, thanks.

**Comment by roryk** [comment]
Thank you, I just cut a new release.

**Comment by amizeranschi** [comment]
Awesome, thanks for mentioning it!
