### ISSUE TITLE
RFC: looking for callable regions with IndexTools

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2987]
Hi all,

DNAnexus released a small tool called [indexTools](https://github.com/dnanexus/IndexTools).
Maybe this might be a valuable addition to the pipeline for the finding of callable regions in stead of the current approach?

Any ideas / comments are welcome.

Cheers
M

**Comment by lbeltrame** [comment]
To kick off some discussion: what are the current disadvantages of mosdepth (which is, IIRC, what is being used at this point) compared to IndexTools?

**Comment by matthdsm** [comment]
I'm not really sure here, but as far as I know mosdepth is used to calculate the callable regions by parsing the bam files, whereas indextools uses the bam index, which should be quite a bit faster.

This seems especially beneficial, since mosdepth is run twice during the pipeline (once for callable regions and once during coverage calculations/QC. (please correct me if I'm wrong)

Cheers
M

PS: on an unrelated note, a schematic overview of the workflow should be a huge plus for the docs. Shouldn't it be possible to auto generate a chart based on CWL? Using the scheme we could probably pinpoint steps that could use an update more easily, or enable us to find unneeded overhead.

**Comment by roryk** [comment]
Hi Matt,

I think mosdepth is pretty fast already and we use it in a bunch of different ways, so we're probably not going to implement support for indexTools-- I think we probably won't gain too much and there are other parts that we could speed up.

Having diagrams of the workflows would be awesome for the documentation, we just haven't gotten around to doing it. There is a diagram from the CWL for variant calling: https://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html#current-status but you can see it's pretty high level so it's not super useful for figuring out bottlenecks and what not.

**Comment by matthdsm** [comment]
Hi Rory, 

No problem! Just bouncing around some ideas.
Cheers
M
