### ISSUE TITLE
fastqc is out of RAM

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2989]
Hi!

In some rare cases 250m RAM is not enough for fastqc:

```
[2019-10-22T18:21Z] Started analysis of sort-downsample.bam
[2019-10-22T18:21Z] Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
[2019-10-22T18:21Z] 	at java.lang.String.toCharArray(String.java:2899)
[2019-10-22T18:21Z] 	at uk.ac.babraham.FastQC.Modules.PerSequenceGCContent.truncateSequence(PerSequenceGCContent.java:222)
[2019-10-22T18:21Z] 	at uk.ac.babraham.FastQC.Modules.PerSequenceGCContent.processSequence(PerSequenceGCContent.java:174)
[2019-10-22T18:21Z] 	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
[2019-10-22T18:21Z] 	at java.lang.Thread.run(Thread.java:748)
[2019-10-22T18:21Z] Uncaught exception occurred
```
Running fastqc from the command line with `-t 2` allocates 500M and works:
https://github.com/s-andrews/FastQC/issues/24

It looks like we don't have an options to control fastqc threads or memory from bcbio.yaml.
https://github.com/bcbio/bcbio-nextgen/blob/987656bec976fbcd7fc7c2b1cd469959a7dbc894/bcbio/qc/fastqc.py#L47

And we need it.

SN

**Comment by roryk** [comment]
Thanks, what was the FastQC command line that failed? I think we can add an explicit `-Xmx500m` to the FastQC call to give it more memory.

**Comment by naumenko-sa** [comment]
The VM got killed already. It was a regular fastqc command.

I think fastqc is a perl script that does not allow to set up java memory. Instead it is doing hardcoded mem=threads*250M

https://github.com/s-andrews/FastQC/blob/master/fastqc#L166

So, I will just use 2 threads as suggested in here https://github.com/s-andrews/FastQC/issues/24

**Comment by roryk** [comment]
Ah, interesting!

**Comment by naumenko-sa** [comment]
In the default bcbio installation in **bcbio/galaxy/bcbio_system.yaml** we have

```
resources:
  default:
    cores: 16
```
so fastqc is being called as `fastqc -t 16 ... `  and we never face the fastqc memory issue.

However, in some installations people do **bcbio/galaxy/bcbio_system.yaml**:
```
resources:
  default:
    cores: 1
```
So default is 1, and fastqc call is `fastqc -t 1 ...` - memory issue.

Reminding myself how cores work for a multicore job project.
There are:
- bcbio_nextgen.py -n NUMCORES (default = 1, typically 20-40)
- bcbio/galaxy/bcbio_system.yaml: resources/default/cores (default=16)
- project/config/bcbio.yaml: resources/default/cores

Probably, the easiest way to tackle this situation is to avoid setting `cores: 1`  in a system-wide config, min `cores: 2`.

SN

**Comment by chapmanb** [comment]
Sergey;
Great catch on the underlying issue. I pushed a small fix that floors the number of threads used at 2 to avoid hitting the low memory issues even if folks set `cores: 1`, so that it'll work in these cases as well. Hope this avoids the problems going forward.

**Comment by naumenko-sa** [comment]
Thanks, @chapmanb !
