### ISSUE TITLE
bcbio split chrom whole regions to several parts at joint calling, how it do split?

### ISSUE THREAD

**Issue by NElight** [bcbio/bcbio-nextgen#2995]

**Comment by roryk** [comment]
Hi @NElight,

Brad is a genius and had the idea to split regions into sub-regions by coverage. So bcbio calculates coverage over all of the chromosomes, finds regions that are bracketed by gaps, and then splits that region out by itself to do the calling.

**Comment by amizeranschi** [comment]
Is there any published paper describing this stuff, which could be cited?

**Comment by roryk** [comment]
Heya, unfortunately no-- we've kind of punted on publishing a paper since by the time it went through the whole review process, the paper would end up being out of date. We could/should give the bcbio repo itself a DOI that can be cited, through something like zenodo.
