### ISSUE TITLE
Clarification needed: which annotation is used etc

### ISSUE THREAD

**Issue by bug1303** [bcbio/bcbio-nextgen#2999]
I installed bcbio with  `--datatarget rnaseq --genomes mm10` several months ago, and I have some doubts about the transcriptome data that is used in there.

I found in `bcbiodata/genomes/Mmusculus/mm10/versions.csv`: 
```
transcripts,2018-10-10_92
rmsk,20180319
```

So from that I would assume that it is Ensembl version 92 (although oct2018 is actually v94).

And in `bcbiodata/genomes/Mmusculus/mm10/rnaseq/version.txt`:
```
Created from: /n/data1/cores/bcbio/rory_kirchner/genome_setups/mm10-build94/rnaseq/mm38.gtf
```

It seems that `bcbiodata/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.gtf` is used by both featureCounts and salmon in the rnaseq pipeline.

I tried to compare `ref-transcripts.gtf` with the version from `ftp://ftp.ensembl.org/pub/release-94/gtf/mus_musculus/Mus_musculus.GRCm38.94.gtf.gz`, and they are largely identical, apart from using different chromosome names (ensembl vs ucsc style naming), ensembl having 65 entries of feature "Selenocysteine" that are missing from the bcbio data, and some rearrangements in the attributes (last column). So, for all practical purposes it should be ensembl v94 (and possibly also note _94 in versions.csv instead of _92 or what is that refer to?), but I'm still wondering how the file had been derived. 

And similarly for other data used by the pipeline, is there a good overview somewhere of which sources were used?

**Comment by naumenko-sa** [comment]
Hi @bug1303 ! 

Thanks for starting this discussion!

Bcbio installs data using https://github.com/chapmanb/cloudbiolinux

In particular, mm10 installation recipe is 
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/mm10/transcripts.yaml

I think 92 is just a typo, in fact, it has been prepared using release 94, as stated in the comment.

Now ensembl 98 annotation is available, and we could easily upgrade the recipe,
however, more opinions are needed, whether the switch would be worth it.

I'd think that aligning Ensembl releases for variant annotation (we have just switched to v98) and for annotation of transcripts in RNA-seq would be logical. 

Sergey

**Comment by mjsteinbaugh** [comment]
+1 that we should make this clearer in the `versions.csv` file, and there are some genome build scripts currently only on O2, I think: `/n/data1/cores/bcbio/rory_kirchner/genome_setups`. We should add these into the CloudBioLinux repo.

**Comment by roryk** [comment]
Hi everyone,

I added a `--buildversion` option to the `bcbio_setup_genome.py` script, which will save an arbitrary string to the `version.txt` file in the `rnaseq` directory. For future updates, we'll include that in the transcriptome bundle and it will have the format `source_version`, so like `Ensembl_94`, `FlyBase_45` etc.

We probably won't add more genomes to the cloudbiolinux repo, unless there are organisms that end up being pretty popular to use and come with their own extra resources. It is easier to just have folks install whatever genomes they want.
