### ISSUE TITLE
gatk resource bundle ftp server is capped at 25 users and breaks installations

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3001]
Hello!

Quite an old issue resurfaced.

Users reported an installation issue:
```
Running GGD recipe: hg38 1000g_snps 20160105
--2019-11-01 06:18:47--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/hg38//1000G_phase1.snps.high_confidence.hg38.vcf.gz
           => 'variation/1000G_phase1.snps.high_confidence.vcf.gz'
Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.80.251
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ...
Login incorrect.
Traceback (most recent call last):
<...>
subprocess.CalledProcessError: Command '['/path/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/pathe/tools', '--genomes', 'GRCh37', '--genomes', 'hg38', '--aligners', 'bwa', '--data']' returned non-zero exit status 1.
```

The recipe is trying to download a file from GATK resource bundle
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/1000g_snps.yaml

The cause of the issue is that the ftp server has a limit of maximum 25 users:

```
ftp ftp.broadinstitute.org
Connected to ftp.broadinstitute.org.
220 ProFTPD 1.3.4a Server (Broad Institute of MIT and Harvard) [69.173.80.251]
Name (ftp.broadinstitute.org:ubuntu): gsapubftp-anonymous
331 Anonymous login ok, send your complete email address as your password
Password:
530 Sorry, max 25 users -- try again later
Login failed.
421 Service not available, remote server has closed connection
```

There was a massive outcry on gatk forum:
https://gatkforums.broadinstitute.org/gatk/discussion/1215/how-can-i-access-the-gsa-public-ftp-server

So for a bcbio user it looks like a random installation failure. 

Broad has moved their bundle to google cloud
https://console.cloud.google.com/storage/browser/gatk-legacy-bundles/b37?pli=1

Should we try to change the recipe to work with the google cloud instead of the broad ftp server?

Sergey

**Comment by chapmanb** [comment]
Sergey;
The Broad FTP limits are a continuous difficulty and it would be great to move away from them. The gcloud hosting is an option but I don't know of a way to directly download with wget or curl. Typically these require using gsutil. We install this with bcbio but it is tricky to isolate and can often not work due to system specific issues (existing gsutil configurations, boto configurations). The deepvariant install uses it to get the models and it's been a source of many issues on it's own.

It's definitely worth exploring, only wanted to let you know the issues I've bumped against so you can avoid them. Thanks much.

**Comment by roryk** [comment]
Thanks, I think the way we have it right now is workable for the time being. It does run into problems, but as Brad said, gsutil with deepvariant also runs into all kinds of problems. It's good that we have the option to switch, but I think the way things are right now, it is likely to cause more problems than it helps. Closing for now but we can revisit if the Broad servers are hopelessly overwhelmed.
