### ISSUE TITLE
 Addition of mm10 genome into a production 1.1.6a system

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#3006]
Brad, et. al.  Curious as to the most risk conscious way of adding an mm10 genome into an existing bcbio environment running 1.1.6a in production?

Any thoughts / help greatly appreciated here!

Many thanks!
R/
Mike

**Comment by naumenko-sa** [comment]
Hi Mike!

I think 

`bcbio_nextgen.py upgrade -u skip --genomes mm10 --aligners bwa --cores 20 ` will do the job.
It would not update bcbio code or tools, it will just run cloudbiolinux recipes for mm10:

https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes/mm10

Sergey

**Comment by roryk** [comment]
Thanks Sergey!
