### ISSUE TITLE
small RNAseq best-practice

### ISSUE THREAD

**Issue by areddy965** [bcbio/bcbio-nextgen#3007]
Hi @lpantano, our group is exploring a new small RNAseq kit (exoRNeasy) with NEB library prep run on a Novaseq; @roryk suggested you'd be able to advise on how to set up the adapters for running this with bcbio. And would you recommend following this config for the current best-practice with callers etc: https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/illumina-srnaseq.yaml? Thanks!

**Comment by lpantano** [comment]
Hi,

I think the adapters would be:AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC

And if you are interested on miRNA mainly I would leave it like this:
https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/illumina-srnaseq.yaml
changing
the line:

expression_caller: [mirdeep2]

If this is human then you can leave the sps param at it is, if not, you
should use whatever match miRBase. (I am assuming you will have the genome
reference and the rest installed already).

I hope this could help.

Cheers
