### ISSUE TITLE
Exome_AZ_V2 coordinate issue

### ISSUE THREAD

**Issue by LeoWelter** [bcbio/bcbio-nextgen#3008]
I ran into an issue aligning a WES to GRCh37 with Exome-AZ_V2.bed that comes with the installation.
Any suggestions? Is Exome-AZ_V2.bed compatible with GRCh37 ?

ValueError: Found BED coordinate off the end of the chromosome:
MT      0       16571   MT-ATP6
/tools/bcbio/1.1.8/genomes/Hsapiens/GRCh37/coverage/capture_regions/Exome-AZ_V2.bed
Is the input BED from the right genome build?

**Comment by gabeng** [comment]
This sure looks like it wasn't made for rCRS that is shipped with GRCh37. Not sure where the BED file comes from, never used it. 
Are you just running tests? Then I recommend to use an Exome BED file from a commercial manufacturer or create a BED from UCSC Tables Browser, e. g. from CCDS.

**Comment by LeoWelter** [comment]
Thanks,

In the end I used the bed file provide by the kit manufacturer

https://www.twistbioscience.com/sites/default/files/resources/2018-09/Twist_Exome_Target_hg19.bed

I translated the IDs using the mappings from

https://github.com/dpryan79/ChromosomeMappings


Op vr 8 nov. 2019 om 09:16 schreef Ben Liesfeld <notifications@github.com>

**Comment by naumenko-sa** [comment]
Hi @LeoWelter !
Thanks for reporting the issue!
@gabeng  thanks for helping to resolve!

You are right, 
/bcbio/genomes/Hsapiens/GRCh37/coverage/capture_regions/Exome-AZ_V2.bed 
has a record
MT	0	16571	MT-ATP6

which is not compatible with grch37, where MT contig is shorter
@SQ	SN:MT	LN:16569	UR:file:/data/biodata/genomes/Hsapiens/GRCh37/seq/GRCh37.fa	M5:c68f52674c9fb33aef52dcf399755519

I think, Exome-AZ_V2.bed  originates from here
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/capture_regions.yaml
https://github.com/AstraZeneca-NGS/reference_data/blob/de1ccc7f64a27fdeb604fcdba204eba5436d0d58/README.md

For testing you may use any other BED file provided along with the installation:
Exome-Agilent_V5_Clinical.bed
Exome-Agilent_V6.bed
Exome-IDT_V1.bed
Exome-MedExome.bed
Exome-NGv3.bed

They don't have mtDNA genes. 

If you need to test mtDNA genes, you may use coordinates from hg38 genome:
```
cat /bcbio/genomes/Hsapiens/hg38/coverage/capture_regions/Exome-AZ_V2.bed
chrM	0	149	.
chrM	150	194	.
chrM	195	262	.
chrM	263	309	.
chrM	310	3106	MT-RNR2
chrM	3107	11718	MT-CO1
chrM	11722	15300	MT-ND5
chrM	15301	15325	MT-CYB
chrM	15326	16171	MT-CYB
chrM	16172	16182	.
chrM	16183	16222	.
chrM	16223	16569	.
```

https://github.com/AstraZeneca-NGS/reference_data/blob/master/hg38/bed/Exome-AZ_V2.bed

So, Exome-AZ_V2.bed is incorrect for mtDNA in grch37 and correct for hg38. 
As this repo https://github.com/AstraZeneca-NGS/reference_data looks abandoned,
it might be better for the file from bcbio installation.

Sergey
