### ISSUE TITLE
tophat2 issue, picard related?

### ISSUE THREAD

**Issue by LeoWelter** [bcbio/bcbio-nextgen#3009]
I'm trying to run the tophat2 aligner with two rna-seq samples in order to compare them to a previous result, but I run into an error. Any ideas how to solve this?

installed bcbio version : 1.1.8:

ReorderSam -INPUT /tools/projects/ribek/RNA-tophat/work/align/RNA-FFPE-BS/RNA-FFPE-BS_tophat/merged-fixrgs.bam -OUTPUT /tools/projects/ribek/RNA-tophat/work/bcbiotx/tmpfbh5_g2z/merged-fixrgs.picard.bam -REFERENCE /tools/bcbio/1.1.8/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -ALLOW_INCOMPLETE_DICT_CONCORDANCE true -TMP_DIR /tools/projects/ribek/RNA-tophat/work/bcbiotx/tmptxe0833h -VALIDATION_STRINGENCY SILENT
**********
ERROR: Unrecognized option: REFERENCE

[picard_error.txt](https://github.com/bcbio/bcbio-nextgen/files/3831162/picard_error.txt)

**Comment by naumenko-sa** [comment]
Hi @LeoWelter !

I hope this issue had been fixed recently here
https://github.com/bcbio/bcbio-nextgen/commit/f33f1c8e2d1ee9f3e6e9be175b5f6cbc552419fa
Could you please `bcbio_nextgen.py upgrade -u development` and try again?

Sergey

**Comment by roryk** [comment]
Sergey's suggestion should fix the issue, so closing this.
