### ISSUE TITLE
Option to add `-I -I` flag in Arriba

### ISSUE THREAD

**Issue by areddy965** [bcbio/bcbio-nextgen#3018]
It would be great to have the option of running Arriba with the `-I -I` flag so that the calls have a "read_identifiers" column with the supporting read ids; it'll help with checking for alignment artifacts and to automate reconstructing the transcripts

**Comment by roryk** [comment]
Hi Avinash,

Thanks-- how do you do the transcript reconstruction after this step? Maybe we can automate that too?
