### ISSUE TITLE
Ensemble with no annotation

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3026]
Hi! How can I achieve a vcf without any annotations in enseble mode?
I define effects to false, but I also want a clean vcf.

**Comment by roryk** [comment]
Hi @kokyriakidis,

We don't support this currently. What is your use case for wanting this?

**Comment by naumenko-sa** [comment]
You could try remove annotations with `vt` or `bcftools`
https://github.com/naumenko-sa/cre/blob/master/cre.annotation.strip.sh
SN

**Comment by roryk** [comment]
Thanks Sergey!
