### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment

### ISSUE THREAD

**Issue by mrityunjayravi** [bcbio/bcbio-nextgen#3027]
Hi,
I am getting below error while install dlib

(base) PS C:\Users\mrravi> conda install -c menpo dlib
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining pyparsing:   4%|██▎                                                           | 2/53 [00:00<00:00, 63.92it/s]|failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - dlib -> python[version='2.7.*|3.5.*']
  - dlib -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Package setuptools conflicts for:
dlib -> python=2.7 -> pip -> setuptools
python=3.6 -> pip -> setuptools
Package wheel conflicts for:
dlib -> python=2.7 -> pip -> wheel
python=3.6 -> pip -> wheel
Package pip conflicts for:
dlib -> python=2.7 -> pip
python=3.6 -> pip
Package certifi conflicts for:
dlib -> python=2.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
python=3.6 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
Package wincertstore conflicts for:
python=3.6 -> pip -> setuptools -> wincertstore[version='>=0.2']
dlib -> python=2.7 -> pip -> setuptools -> wincertstore[version='>=0.2']
Package ca-certificates conflicts for:
python=3.6 -> pip -> requests -> urllib3[version='>=1.21.1,<1.24'] -> cryptography[version='>=1.3.4'] -> openssl=1.0 -> ca-certificates
dlib -> python=2.7 -> ca-certificates
Package msgpack-python conflicts for:
python=3.6 -> pip -> cachecontrol -> msgpack-python
dlib -> python=2.7 -> pip -> cachecontrol -> msgpack-python

**Comment by mjsteinbaugh** [comment]
@mrityunjayravi This seems to be a conda issue unrelated to bcbio-nextgen. If you're updating the internal conda environment inside bcbio, I'd strongly recommend against that.

**Comment by roryk** [comment]
Hi @mrityunjayravi,

+1 to what Mike said. Looking at https://github.com/menpo/conda-dlib, I think that repository has been abandoned. https://stackoverflow.com/a/53276910 describes how to install dlib with pip, I'd just do that.

**Comment by phigrlzt** [comment]
I have the same error when trying `conda install -c openastronomy sep`. Did you find a solution to this problem in your case? or Can you suggest to me what can I do?
Any idea to fix this would be very useful.
