### ISSUE TITLE
sambamba fails after the latest update

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3032]
Hello!

One of O2 bcbio users reported an issue:

```
which sambamba
/n/app/bcbio/tools/bin/sambamba
bash-4.2$ sambamba
sambamba: error while loading shared libraries: libphobos2-ldc-shared.so.83: cannot open shared object file: No such file or directory
```

It happened after the last `bcbio_nextgen.py upgrade -u skip --tools` update 2019-11-28.

I think this is because of:
https://github.com/bioconda/bioconda-recipes/issues/11422
https://github.com/bioconda/bioconda-recipes/commit/c8a2fc738b3989c68575436c8a03b200448c5040#diff-1f1f09bef5e9e5f78b1eb054591e0dda

Sambamba now is compatible with the updated `ldc` and they unpinned ldc version in the sambamba recipe.

But we still have ldc 1.10 in bcbio:
```
bcbio_conda list | grep ldc
ldc                       1.10.0               hb2c9046_0    conda-forge
```

ldc is D programming language environment

When I tried to update it with 
```
bcbio_conda update ldc
```

It proposed to update too many packages in the system, so I cancelled it.

Any ideas how to fix that? 

SN

**Comment by naumenko-sa** [comment]
Updating ldc with helped
```
bcbio_conda install --force-reinstall -c conda-forge ldc
```
So everything should work for new installations, but when upgrading, we don't specify ldc,
and bioconda recipe does not specify ldc version >1.10, so ldc is not updated by default,
and then ldc1.10 + new sambamba fail.

**Comment by roryk** [comment]
Thanks, if you pin ldc to being >= whatever the version that got installed in the `cloudbiolinux/contrib/ngs-pipeline-minimal/conda` file, whatever that is, it will force bcbio to update `ldc` so this will fix it for folks.

**Comment by roryk** [comment]
Can confirm it fixes it if you are doing an upgrade, so this should be all set now. Thanks Sergey!
