### ISSUE TITLE
validation 2020

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3038]
Hello!

Starting this thread to update variant calling validation in bcbio.

Users reported some validation results, 
based on NA12878 and another 6 NA12XXXXX samples, 
showing that gatk4.1 + bcbio filters result in somewhat lower 
indel calling precision: 90% vs 95% compared to another GATK workflows.

SErgey

**Comment by roryk** [comment]
Great-- do we have links to the results? It would be good to see where we might be missing stuff.

**Comment by naumenko-sa** [comment]
closing for now, goes to circle 3
