### ISSUE TITLE
v1.1.9 install is hanging at conda environment solve

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3040]
I'm seeing the bcbio-nextgen 1.1.9 installer get stuck trying to figure out the conda environment recipe, when these flags are used:

```
    --upgrade="stable"
    --datatarget="rnaseq"
    --datatarget="variation"
    --nodata
    --isolate 
```

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...
```

I'll re-run this with just the `rnaseq` datatarget and report back.

**Comment by roryk** [comment]
Thanks, this isn't really anything we can handle unfortunately. If you let it sit for a while it will figure it out, but it can take hours to eventually finish.

**Comment by mjsteinbaugh** [comment]
Yeah it's hanging with only `--datatarget="rnaseq"` too

**Comment by roryk** [comment]
Yeah, it's the tools that run into this problem, should be independent of the data.

**Comment by mjsteinbaugh** [comment]
[mamba](https://github.com/QuantStack/mamba) to the rescue?

**Comment by roryk** [comment]
Could be, there have been some other solutions proposed too. For now we're just waiting to see what shakes out as something that is faster and works stably.

**Comment by mjsteinbaugh** [comment]
Following up, I let the installer run overnight and the solver does eventually complete and run through. 👍

**Comment by erinijapranckeviciene** [comment]
Dear colleagues, 

I am installing v1.1.9 on a fresh Ubuntu 18 LTS system with a simple command 

`python3 bcbio_nextgen_install.py ~/bcbio/v1.1.9 --tooldir=~/bcbio/v1.1.9 --genomes GRCh37 --aligners bwa`

and am experiencing the  install hanging specifically  at this step:

`# Installing into conda environment python2: bismark=0.22.1, cpat, cutadapt=1.16, dkfz-bias-filter, gemini, gvcf-regions, hap.py, hisat2, htseq=0.9.1, lumpy-sv, macs2, manta, metasv, mirge, optitype, peddy, phylowgs, platypus-variant, sentieon, smcounter2, smoove, strelka, svtools, svtyper, theta2, tophat, vawk, vcf2db`
`Collecting package metadata (current_repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Collecting package metadata (repodata.json): done`
`Solving environment: \`

This step was taking more than 12 hours, so I cancelled. I have retried several times. Every time it is stuck at the same step. Is there an approximate estimate of how long it actually should take? I might be wrong, but It does not seem right for installer to be stuck for such a long time. 

Many thanks in advance!

**Comment by mjsteinbaugh** [comment]
@erinijapranckeviciene Try letting it run for a full day (~24 hours) and see if the solver completes. It took longer than 12 hours for me last time on an Azure VM.

**Comment by erinijapranckeviciene** [comment]
@mjsteinbaugh That is very helpful. Many thanks!

**Comment by mjsteinbaugh** [comment]
@erinijapranckeviciene If the install path is the same on a different machine, rsync will work. If the installation path is different, you may run into problems.

**Comment by roryk** [comment]
Thanks, sorry about that. There isn't anything we can do ATM to fix this, it is an issue with complex conda environments. They've been working on improving the solver, but we're mostly at their mercy for it completing.

**Comment by erinijapranckeviciene** [comment]
Yes indeed, it is fully understandable, NP.  Just an update - in my case the long time taking step completed in about 15 hours.
