### ISSUE TITLE
Scalpel won't report this indel 

### ISSUE THREAD

**Issue by josephpowi** [bcbio/bcbio-nextgen#3042]
I am a new Scalpel user. Would anyone help me to check why scalpel won't report the indel shown in the attached figure? 
<img width="1776" alt="Screen Shot 2019-12-13 at 9 24 58 AM" src="https://user-images.githubusercontent.com/32489359/70811152-a807d780-1d8a-11ea-9aa4-7c309b2ac891.png">

**Comment by roryk** [comment]
Heya-- are you using bcbio-nextgen or just scalpel on it's own? You might get better luck asking on the scalpel ticket page: https://sourceforge.net/projects/scalpel/ if you are using scalpel on it's own.

**Comment by josephpowi** [comment]
Thanks for your reply. I appreciate it.

**Comment by roryk** [comment]
Anytime!
