### ISSUE TITLE
UMI: correct_umis: [path/to/whitelist_umi.txt]

### ISSUE THREAD

**Issue by fengshuaisheng** [bcbio/bcbio-nextgen#3050]
hi : 
   I hava a question while using the the UMIs target,  correct_umis: [path/to/whitelist_umi.txt], The parameter can specify a file eg: whitelist_umi.txt, the description of the umi file is "File of UMI sequences, one per line." but I don't know how to definition of one UMI sequence,  also 
 in the fgbio "http://fulcrumgenomics.github.io/fgbio/tools/latest/CorrectUmis.html" can not find the detail of the parameter --umi-files;  eg:  the ahead of 12bp is UMI(random sequences) and 13-20bp is common seq (AATGTACAGTATTGCGTT) my fastq files of read1, and 21bp is  common seq in  fastq files of read2. So how can I editor my  "whitelist_umi.txt" or what is the rules when editor UMI sequence ??? 
thank you very much!!!

**Comment by chapmanb** [comment]
Thanks for the question. This file is useful when you have a defined set of UMIs in your pool and can help fix sequencing errors in this case by correcting UMIs to this defined set. It sounds from your description that this is not the case for your design and you have random UMIs. In this case, you don't need to include the parameter since it won't be useful. Hope this helps.

**Comment by naumenko-sa** [comment]
+1
whitelist_umi.txt usually comes with the library preparation kit. TwinStrand or IDT have their own pre-defined sets of UMIs. Also you may investigate your reads and compile a UMI frequency table - then you will see if there are some standard UMIs or they are just random.

**Comment by fengshuaisheng** [comment]
hi @naumenko-sa and chapmanb：
      Thank you for your replication, I have already checked my fastq files, the first 12bp are just random in reads2 and 12-23bp is not random as mentioned in my question, and the panel is designed by QIAGEN, So if I droped the parameter correct_umis would readly help to recognzie and mark the UMI for the QIAGEN design ?
look forward to your reply!

**Comment by roryk** [comment]
Yep, just leaving it out will work, but you'll need to do an additional preprocessing step to get your files in the right format. Do you have UMI as the first 12 bases for R1 and R2, or is it just one of the reads that has the UMI in it?

**Comment by fengshuaisheng** [comment]
Hi , @roryk, thank you for your reply, I have test the bcbio pip without the  parameter(correct_umis), but it seems can't work, So How can I prepare my fastq files in the right format or modificate the yaml file of bcbio ? 
The first 32 lines of  fastq file is unploaded, and the first 21bp in all sequences of fastq1 is  AATGTACAGTATTGCGTTTTG, the first 12bp is random sequence and 13-23bp is ATTGGAGTCCT in all sequences of fastq2.

**Comment by roryk** [comment]
Thanks-- could you link us the URL to the description of the kit and send us 1000 reads from the end of the first and second fastq files?

**Comment by fengshuaisheng** [comment]
Hi  @roryk:  the first 1000 reads of fastq file is already uploaded to the website as below, hope to help for the question， thank you very much!
https://minersutep-my.sharepoint.com/:u:/g/personal/jshi_utep_edu/EaVfmwblUJNLgDokdAAZALkBuCwzhFHgOveUY7ENPJuFlQ?e=8KUBf0

**Comment by naumenko-sa** [comment]
Thanks for sharing the data!
Now I understand the structure of the library better.

![read1](https://user-images.githubusercontent.com/13981803/72021053-1c735080-323b-11ea-997d-14122d07a551.png)
![read2](https://user-images.githubusercontent.com/13981803/72021054-1c735080-323b-11ea-818e-e60b81522bcf.png)

read1 = 21bp adapter + 100 bp read
read2 = 12 bp UMI + 8bp adapter + 101bp read

Currently, we support two types of UMIs in bcbio with a parsing script: 
https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/bcbio_fastq_umi_prep.py
- R1 (data), R2 (umi), R3 (data), parsing with
`bcbio_fastq_umi_prep.py single  <basename> R1.fq R3.fq R2.fq`
- R1 (data), first N bases are UMIs, R2(data), first M bases are UMIs, parsing with
`bcbio_fastq_umi_prep.py autopair -c 1 --tag1 N --tag2 M R1.fq.gz R2.fq.gz`

In both cases resulting files will be in with_umis folder and UMI's will be added to fastq read name lines.

In your case, you may try either option:
-option 1:
 copy 12 bp UMI from R2 into R3 and then parse:
` cat R2.fq | awk '{if(NR%2==0)print substr($0,1,12); else print $0}' > R3.fq;
When running bcbio, use `trim_ends: [21,0,20,0]` to trim the adapters.

- option2:
`bcbio_fastq_umi_prep.py autopair -c 1 --tag2 12 R1.fq.gz R2.fq.gz`
When running bcbio, use `trim_ends: [21,0,8,0]` to trim the adapters.

I found the adapters in:
https://www.nature.com/articles/s41598-019-41215-z
http://www.freepatentsonline.com/y2019/0241946.html
Is this the barcoding method you are using?

SN

**Comment by fengshuaisheng** [comment]
hi @naumenko-sa:
Very thanks for your reply, it' s make it very clear for my question and  I have test both the option 1 and option 2, both worked well for preparing and dealing the fastq files, also the umi sequence was added to the header of fastq files accroding to the script bcbio_fastq_umi_prep.py, but while running the bcbio, it can not working well at the step of  generate bam file, it seams that  bamsormadup can not process the sam file after bwa. But this could not happend which running the normal fastq file( without umi_type: fastq_name in the yaml file and without umi in fastq files), So I don't why this happened that in resulting bam files, hope to your reply.
thank again for your explanation in detail l!!

the yaml file of  bcbio is as flows:
details:
  - analysis: variant2
    genome_build: hg19
    algorithm:
      aligner: bwa
      trim_ends: [21,0,23,0]
      umi_type: fastq_name
      mark_duplicates: true
      variantcaller: vardict
      min_allele_fraction: 0.5
resources:
  fgbio:
    options: [--min-reads, 3]

and the tail of bcbio logs is as flow:
[2020-01-14T09:24Z] [V] blocks generated in time 24:44:94579500
[2020-01-14T09:24Z] [V] number of blocks to be merged is 9 using 910 blocks per input with block size 1048576
[2020-01-14T09:25Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /public/bcbio/galaxy/../anaconda/bin/bwa mem   -c 250 -M -t 16  -R '@RG\tID:new_test\tPL:illumina\tPU:new_test\tSM:new_test' -v 1 /public/bcbio/genomes/Hsapiens/hg19/bwa/hg19.fa /work/align_prep/new_test_R1.fastq.gz /work/align_prep/new_test_R2.fastq.gz  | /public/bcbio/galaxy/../anaconda/bin/bamsormadup tmpfile=/work/bcbiotx/tmp_qpxpk2i/new_test-sort-sorttmp-markdup inputformat=sam threads=16 outputformat=bam level=0 SO=coordinate | /public/bcbio/anaconda/bin/python /public/bcbio/galaxy/../anaconda/bin/umis bamtag - | samtools view -b > /work/bcbiotx/tmp_qpxpk2i/new_test-sort.bam
[V] blocks generated in time 24:44:94579500
[V] number of blocks to be merged is 9 using 910 blocks per input with block size 1048576
' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
Hi @fengshuaisheng!

Sorry for breaking the thread. Have you succeeded in running bcbio in your case?
If not, please share your full bcbio-nextgen-commands.log file and a small sample of input data, if possible.

Sergey

**Comment by naumenko-sa** [comment]
please feel free to reopen if you still see issues with UMIs.
