### ISSUE TITLE
Issues Running SV Caller Pipeline with Manta and Lumpy

### ISSUE THREAD

**Issue by mbootwalla** [bcbio/bcbio-nextgen#3053]
Hello Bcbio Team,

I am trying to run the SV Caller Pipeline using lumpy and manta SV callers and I keep getting the following error -

```
[smoove]:2020/01/04 16:30:00 error running command: set -eu; lumpy_filter -f /gpfs/fs1/data/bcbio_data_1.1.9/genomes/Hsapiens/hs37d5/seq/hs37d5.fa bcbio_sv_20200103/work/prealign/Sample2/Sample2-prealign.bam bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.split.bam.tmp.bam bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.disc.bam.tmp.bam 2 && mv bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.split.bam.tmp.bam bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.split.bam && mv bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.disc.bam.tmp.bam bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.disc.bam && cp bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.split.bam bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.split.bam.orig.bam && cp bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.disc.bam bcbio_sv_20200103/work/bcbiotx/tmp64w53h0r/Sample2.disc.bam.orig.bam -> exit status 127
[smoove] 2020/01/04 16:30:07 done calculating bam stats
panic: exit status 127
goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffddb115e5f, 0x3c, 0x7ffddb115e12, 0x45, 0x7ffddb115ea5, 0x5a, 0xc00016ef80, 0x2, 0x2, 0xc000174a00, ...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x57e
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
        /home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1ce
' returned non-zero exit status 2.
[1:apply]: CalledProcessError: Command '/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/bin/python3.6 /gpfs/fs1/data/bcbio_data/anaconda/share/manta-1.0.3-0/bin/configManta.py --bam=bcbio_sv_20200103/work/prealign/Sample1/Sample1-prealign.bam --bam=bcbio_sv_20200103/work/prealign/Sample2/Sample2-prealign.bam --referenceFasta=/gpfs/fs1/data/bcbio_data_1.1.9/genomes/Hsapiens/hs37d5/seq/hs37d5.fa --runDir=bcbio_sv_20200103/work/bcbiotx/tmplb0i0eex/manta
Traceback (most recent call last):
  File "/gpfs/fs1/data/bcbio_data/anaconda/share/manta-1.0.3-0/bin/configManta.py", line 34, in <module>
    from mantaOptions import MantaWorkflowOptionsBase
  File "/gpfs/fs1/data/bcbio_data/anaconda/share/manta-1.0.3-0/lib/python/mantaOptions.py", line 32, in <module>
    from configureOptions import ConfigureWorkflowOptions
  File "/gpfs/fs1/data/bcbio_data/anaconda/share/manta-1.0.3-0/lib/python/configureOptions.py", line 171
    except OptParseException, e :
                            ^
SyntaxError: invalid syntax
' returned non-zero exit status 1.

```

Additionally when I ran the pipeline previously I was getting an error saying that the smoove command could not be found. I manually linked the smoove binary installed under bcbio/anaconda/bin directory to a directory in my path across all the nodes on my server and after that this error went away. But now I see the error that the tool lumpy_filter cannot be found. 

I have run into such errors previously in regards with tools such as apropos and gsort. Normally bcbio always looks under the --tooldir that was specified during install for any tool it needs but recently I have been noticing that for some tools it looks for them directly in the user's path and if the tool can't be found in the path bcbio crashes. It would be great if this issue regarding the location of the tools can be fixed in the long term.

Any pointers towards fixing the above highlighted issue would be greatly appreciated? Kindly let me know if there is any further information I can provide to help debug this issue. I am using bcbio version 1.1.8.

Thanks,

Moiz

**Comment by naumenko-sa** [comment]
Hi Moiz!

Thanks for reporting the issue!

It looks your bcbio was not successfully installed. The tools like gsort, smoove are widely used in many projects and should be there by default, no need to link them manually.

I'd suggest you to update bcbio and tools to the latest development 1.2.0a and post the details here first. And we will try to see if your installation is ok.

Sergey

**Comment by roryk** [comment]
Hi @mbootwalla,

For a lot of the tools, we try to find the full path to them in the bcbio installation, but we have missed places, you can see for the `lumpy_filter` call we aren't using the full path. I'll fix that, but there are likely other ones. If you put the `tool-directory/bin` in your PATH it will find these files.

**Comment by roryk** [comment]
Should be all set now!

**Comment by mbootwalla** [comment]
Thank you @roryk and @naumenko-sa. I will try out the updated version of bcbio and report back if I run into any issues.
