### ISSUE TITLE
ctDNA

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3056]
Hi everyone!

Do you have any recommendations for circulating tumor dna analysis?

**Comment by roryk** [comment]
Hi Konstantinos,

Hope you had a great break. Usually when we've done this we had a small panel of genes we were looking at, so we just ran everything like it was amplicon sequencing. What kind of data do you have?

**Comment by kokyriakidis** [comment]
Hi rory!

I have blood samples sequenced at 35.000x in a panel of 523 genes using UMIs. Do you have any suggestion?

**Comment by roryk** [comment]
Yup! You'll want to figure out where the UMIs are so you can run the preparation script described here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#umis

The running the panel sequencing pipeline with `umis: fastq_name` will run bcbio in the UMI aware mode. If you don't have duplex UMI, calling down to extremely low allele frequencies can cause some false positive artifacts, just so you are aware.

**Comment by kokyriakidis** [comment]
Thanks! Do I have to set something else in the pipeline?

**Comment by roryk** [comment]
You'll want to use a somatic caller: https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#cancer-variant-calling

**Comment by kokyriakidis** [comment]
Any preferance? Mutect?

**Comment by MrsLaviniaG** [comment]
Hi Konstantinos,

There are some great publications covering ctDNA analysis. For example, https://www.biorxiv.org/content/10.1101/759399v1 is a recent example using Mutect2, and there are some comments on running Mutect2 with ctDNA samples here:
https://gatkforums.broadinstitute.org/gatk/discussion/23625/mutect2-filtering-mutation-calls-issue

Hope this helps.

**Comment by naumenko-sa** [comment]
Hi Konstantinos!

Here is a sister thread on using UMIs: https://github.com/bcbio/bcbio-nextgen/issues/3050
Re somatic callers, I think the best options for now in bcbio are mutect2 and vardict.

Sergey

**Comment by kokyriakidis** [comment]
Good to know! Thanks everyone for the info!

**Comment by roryk** [comment]
Thanks @MrsLaviniaG for the information, that is super helpful.

**Comment by lbeltrame** [comment]
The best results I had with my own testing and some UMIs were with MuTect2. Of course a lot depends on the variant fraction you're interested in and the type of tumor (some, like colon cancer, release a lot of ctDNA; some others, very little). 

Finding clonal variants is not a big deal in my experience, even if you have a certain degree of PCR artifacts. If you go for subclonal, you really need high depths and UMIs (and MuTect2), for what I've seen.

**Comment by naumenko-sa** [comment]
Thanks everyone!
