### ISSUE TITLE
Adding samples with different coverage profiles to the same batch for variant calling

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3057]
Is it possible to add samples with different coverage profiles (e.g. for WGS, for exome seq and for amplicon seq) to the same batch, in order to run joint variant calling? I'm interested in getting a unified VCF file at the end with calls from all the samples and I'd like to avoid running separate analyses for each type of samples (WGS, exome, amplicon etc.), if possible.

Would it work if I don't specify the `variant_regions` and if I set `coverage_interval: amplicon` and `mark_duplicates: false` for the whole analysis?

**Comment by matthdsm** [comment]
Hi,

If I were you, I'd set the variant_regions for all "samples" to the same bed file containing the ranges covered by your amplicon and the coverage interval to the one most suitable for each sample. The `coverage_interval` has some effects on mapping settings if memory serves, so I wouldn't mess with those.
That way, you'll only get the variants from your ROI, but the mapping will run with the optimal settings.

Cheers
M

**Comment by amizeranschi** [comment]
Hi @matthdsm 

Thanks a lot for the reply. I don't have a suitable `variant_regions` BED file for the amplicon sequencing samples (I was looking at second-hand data). And even if I had one, I was thinking about mapping reads to a non-standard genome (in yeast), so the BED file would have been useless anyway.

So, I was hoping to let bcbio_nextgen find the regions of coverage from the mapped reads (regardless of whether they're for NGS or amplicon sequencing or anything else in between). I think bcbio should also work when `variant_regions` isn't specifically set up, right? My biggest problem with this, so far, is that this runs into parallelization issues, as mentioned in https://github.com/bcbio/bcbio-nextgen/issues/2614 and https://github.com/bcbio/bcbio-nextgen/issues/2572.

And what about `mark_duplicates`? I know this should be turned off for amplicon sequencing. Will this be fine for NGS as well?

**Comment by matthdsm** [comment]
Hi, 

Sure it should work, but I don't thinks that's the optimal approach. Perhaps you can let bcbio infer the regions from your amplicon data, and then use that bed file as regions for the exome/WGS data? This might also fix your parallelizations issues.

as for marking duplicates, that's up to you. I'd leave it on for the NGS data, but thats just me. The duplicates don't get removed, they're just marked, so you don't lose any data I suppose.

M

**Comment by roryk** [comment]
Having the regions will be important, since if you don't have them, bcbio will call variants anywhere where there is any coverage at all, and those extra areas will tend to be laden with false positives, which will ruin the whole point of doing the comparison at all. I would just use whatever variant calls you have already and then compare them manually with the other variants you have called, rather than try to have them all run together with different technologies and strategies and try to make any sense out of it.

**Comment by amizeranschi** [comment]
@matthdsm That seems like a good idea, thanks. I'll try to get bcbio to inger the regions for the amplicon samples and get a variant_regions.bed file from those.

@roryk You're right, I was worried about the false positives for the targeted sequencing samples due to off-target reads, but wasn't sure how to deal with this. So far, I've only looked at WGS samples and called variants from these. I was considering to add amplicon and targeted sequencing samples and then to call variants from everything, using joint calling, so that I get a unified VCF file at the end, and then look for common variants across the samples. Based on my understanding so far, with joint calling, bcbio should just output `no-call` genotypes in the targeted sequencing samples, if there was no coverage at that site. 

I don't think I'll be able to come up with a BED file for the amplicon sequencing samples, especially since I'm looking into mapping reads to a non-standard genome. So, my only choice is to let bcbio infer the coverage regions, but this leads to parallelization issues (https://github.com/bcbio/bcbio-nextgen/issues/2614 and https://github.com/bcbio/bcbio-nextgen/issues/2572). Could you help with these?

**Comment by amizeranschi** [comment]
In what way does the `coverage_interval` setting affect the analysis? Specifically, for example, would it be a big deal if a WGS sample was marked as `regional`, as opposed to `genome`?

From the documentation (https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#coverage-information), it seems like VQSR would get turned off. However, I've already disabled it via `tools_off`, so this wouldn't make a difference. Also, I'm not running CNV or structural variant calling. 

Is there anything else I'd be missing on in this scenario?

**Comment by naumenko-sa** [comment]
Sorry, it is a very unusual setup when trying to call variants with WGS + WES + amplicons. It seems nobody ever tried to run WGS with `coverage_interval: regional`. I'd also suggest to call variants separately per technology and then work at the level of variants.

Please update if you elaborated anything interesting to share with other users.

**Comment by amizeranschi** [comment]
Yes, I'm planning to do just that: separate runs per technology and then check for any overlaps at the level of VCF files. 

As for `coverage_interval: regional`, I imagined this should be used for stuff like exome sequencing. If not, then what coverage setting should be used for such scenarios?

**Comment by roryk** [comment]
Hi @amizeranschi,

`coverage_interval` gets computed automatically by bcbio, so you don't need to set it. https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#coverage-information has a good description of when you'd want to set it. Hope that helps! Thanks for the discussion.
