### ISSUE TITLE
Bcbio docker images on quay.io

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3060]
Is it still planned to release updated docker images (`bcbio-vc` and `bcbio-rnaseq`) on quay.io? The latest available images are for version 1.1.7 and were updated on the 11th of October 2019 (bcbio versions 1.1.8 and 1.1.9 are missing): https://quay.io/repository/bcbio/bcbio-vc?tab=tags.

**Comment by amizeranschi** [comment]
Another release came out in the mean time. https://github.com/bcbio/bcbio-nextgen/commit/9289bdf1a48adab55b8ce51058d4bdc7f5d81f97

Is it safe to assume that bcbio Docker images are a thing of the past?

**Comment by roryk** [comment]
No, we definitely still want to do them. The conda solving times is breaking the builds is the problem.

**Comment by matthdsm** [comment]
Hi @roryk,

Do you think changing `conda` for `mamba` might be a solution?
Or perhaps just skip the solving altogether and feed conda the urls to the required packages ( + requirements)? It should be relatively easy to do a 'local' install with the dependency resolvement, from which we'd be able to pull a comprehensive list of required packages. This would also help with pinning the software to exact versions.

For local install we could keep what we have, but for the docker builds we could work with the generated pkg list.

Cheers
M

**Comment by roryk** [comment]
I tried switching the few conda calls here to mamba but it didn't help any, let me mess around a little bit more and see if I can come up with a way to get this going faster. Your idea is a good one.

**Comment by roryk** [comment]
Hi @amizeranschi,

I've managed to fix the docker image building, so we should be all good for new releases going forward. Thanks!

**Comment by amizeranschi** [comment]
Hi @roryk 

Great job and thanks a lot for looking into it!
