### ISSUE TITLE
CNVkit fails in bcbio

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3061]
Preeti reports a bug, she will give some more detail:

```
subprocess.CalledProcessError: Command 'set -o pipefail; export TMPDIR=/n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/bcbio_test/bcbio_WGS/work/bcbiotx/tmpme08admw && /n/app/bcbio/dev/anaconda/bin/cnvkit.py scatter -s /n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/bcbio_test/bcbio_WGS/work/structural/NF2_CAS9_iPSC_cellline/cnvkit/NF2_CAS9_iPSC_cellline-chromfilter.cns -o /n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/bcbio_test/bcbio_WGS/work/bcbiotx/tmpme08admw/NF2_CAS9_iPSC_cellline-normalized-scatter_global.pdf /n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/bcbio_test/bcbio_WGS/work/structural/NF2_CAS9_iPSC_cellline/cnvkit/NF2_CAS9_iPSC_cellline-normalized-chromfilter.cnr

QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/172693', please create it with 0700 permissions.

qt.qpa.screen: QXcbConnection: Could not connect to display localhost:20.0

Could not connect to any X display.

' returned non-zero exit status 1.
```

**Comment by preetida** [comment]
CNV kit issue. No CNV calls generated. 
subprocess.CalledProcessError: Command 'set -o pipefail; export TMPDIR=/n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/data/bcbio_WGS/work/bcbiotx/tmpyaagnmq6 && /n/app/bcbio/dev/anaconda/bin/cnvkit.py scatter -s /n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/data/bcbio_WGS/work/structural/NF2_CAS9_iPSC_cellline/cnvkit/NF2_CAS9_iPSC_cellline-chromfilter.cns -o /n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/data/bcbio_WGS/work/bcbiotx/tmpyaagnmq6/NF2_CAS9_iPSC_cellline-normalized-scatter_global.pdf /n/data1/cores/bcbio/PIs/konstantina_stankovic/wgs_of_CRISPR_line_hbc03742/data/bcbio_WGS/work/structural/NF2_CAS9_iPSC_cellline/cnvkit/NF2_CAS9_iPSC_cellline-normalized-chromfilter.cnr
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/172693', please create it with 0700 permissions.
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:20.0
Could not connect to any X display.
' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
Investigating another CNVkit issue (T/N WES use case), I found that new cnvkit 0.9.7beta is more stable, and it solved the issue I had (I just installed cnvkit 0.9.7 beta from source into bcbio conda envronment).

Hopefully, it will appear in conda soon (currently we are on 0.9.6).
https://github.com/etal/cnvkit/issues/509

**Comment by naumenko-sa** [comment]
bioconda does not acknowledge beta versions, so to fix your bcbio installation with the latest cnvkit, you may try:

```
git clone https://github.com/etal/cnvkit
which pip
pip install -e .
which cnvkit.py
cnvkit.py version
```

**Comment by preetida** [comment]
i ran cnvkit with bcbio {perhaps with updated bcbio instatllation}, and it worked for me with no issue.

**Comment by roryk** [comment]
Awesome, thanks for following up Preeti!

**Comment by hackdna** [comment]
Would Conda be able to upgrade a package installed from GitHub with pip when the new version becomes available in a Conda channel in the future?
