### ISSUE TITLE
unusable conda in latest bcbio on CentOS 7.6 time to solve 12+ hours not yet at 10%

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#3062]
Currently using CentOS 7.6 
Kernel:3.10.0-862.3.2.el7.x86_64

[root@ip-10-200-0-156 bin]# ./conda --version
conda 4.8.0

bcbio command issued was:
python bcbio_nextgen_install.py /mnt/fsx/usr/local/share/bcbio --tooldir=/mnt/fsx/usr/local --genomes hg38 --genomes mm10 --aligners star --aligners star --cores 32

Conda currently running for 12 hours and 9% through "solving" . Environment relatively clean except for Slurm install and Lustre FSx drivers for AWS.  Curious if this is a well known issue.

Conda channel priority set to strict:
[root@ip-10-200-0-156 bin]# ./conda config --get channel_priority
--set channel_priority strict
[root@ip-10-200-0-156 bin]# 

Read somewhere that new conda is multithreaded but am just seeing one cpu woefully slammed in top (below).  If this is known issue and if there are workaround please let me know.  This has been a minor issue in the past but is effectively unusable now.

 92114 root      20   0 2538740   1.8g   2416 R 100.0  3.1 947:42.95 conda    

<img width="1584" alt="Screen Shot 2020-01-18 at 2 54 01 PM" src="https://user-images.githubusercontent.com/47373948/72671706-10d61580-3a03-11ea-822c-dc04a7255550.png">

**Comment by naumenko-sa** [comment]
It is the same issue: https://github.com/bcbio/bcbio-nextgen/issues/3054
We have recently activated mamba solver back https://github.com/chapmanb/cloudbiolinux/pull/331, this gave us -10h, last measurement I did was 14h (without genomes and indices). Hopefully, another -10h will be achieved soon by using mamba in the installation of environments.
SN

**Comment by chapmanb** [comment]
Sergey -- the latest cloudbiolinux now includes mamba used in environments as well with the hope of gaining additional efficiency. I hope this will help with install and resolve speeds, and please let me know if anything doesn't work as expected. I've done some basic testing but could definitely use more eyes on it. Thanks so much for benchmarking this and the patience with install speeds.

**Comment by lento2002** [comment]
ok thanks; do you recommend "strict" or "flexible" setting.  Re-ran and I'm looking at it starting at me for about 8 hours in 'Solving Environment -"  With strict I'd get the above bars showing about 10 days of work to do re: solving.

**Comment by chapmanb** [comment]
If you've got the latest cloudbiolinux with your re-run, it should do most of the install work with mamba so the conda solves should hopefully be fast. Do you see mamba being used? It's possible you have an older cached cloudbiolinux from your previous run and might need to do `rm -rf tmpbcbio-install` to get the latest. I haven't done much playing around with strict/flexible so not sure about that and have used the default for all of the tests. Hope getting mamba working solves the issue for you.

**Comment by lento2002** [comment]
seemingly in a loop now see screenshot.  Is this normal?  I diverged from installing it on Lustre FSx to just local and am getting completely different output now.  At this point though it keeps showing me mamba, then says all packages installed, then solving environment.  Keeps doing this over and over again though without going to a next step.  Expected behavior?
<img width="1553" alt="Screen Shot 2020-01-20 at 2 43 40 PM" src="https://user-images.githubusercontent.com/47373948/72762164-69d4b380-3b93-11ea-94d1-0fdc0ccdb504.png">

**Comment by lento2002** [comment]
yeah just checked now and it's still looping.  it seemingly is using the new cloudbiolinux.  The mtimes of the files are all 19JAN in the tmpbcbio-install dir

**Comment by chapmanb** [comment]
Thanks for testing this and apologies for the continued issues. Apologies when refactoring this I messed up the level for running this and it was getting called once for each package, which is what is causing the looping you're seeing. The very latest cloudbiolinux fixes this, so if you `rm -rf tmpbcbio-install` one more time and then re-run to get the latest, it should avoid this and hopefully work quicker for you now. Thank you again for all the patience trying this out.

**Comment by lento2002** [comment]
Brad, not a problem will give this a shot now; just wiped all the state and re-trying.  Many thanks! R/Mike

**Comment by lento2002** [comment]
That fixed it; it's crunching on hg38 now; many thanks!

**Comment by naumenko-sa** [comment]
Many thanks @chapmanb ! 
The test install on AWS was under 20 min with:
`python3 bcbio_nextgen_install.py $1 --tooldir $2 --isolate --nodata`

SN
