### ISSUE TITLE
Enabling consistent round-trips in bcbio: FASTQ-BAM-FASTQ-BAM...

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3067]
Hi,

this question is not related to UMI like my earlier post #2919. 
I noticed that when using the output files of bcbio (BAM files) as input files to repeat an identical analysis, one will end up with a different variant calling result. The reason for this seems to be a different alignment of the reads (not the variant calling). 

|Iteration|FASTQ|BAM|
|---|---|---|
|1|Sort-order-1 (original)|Alignment-1|
|2|Sort-order-2 derived from Alignment-1|Alignment-2 (slightly different from Alignment 1)|
|3|Sort-order-3|Alignment-3|
(and so on)

`biobambam bamtofastq` seems to output the reads in the order they are encountered in the bam file. The differences between iterations may be small, but it is noise that makes optimization of settings more difficult. The impact may be significant when looking at a smaller number of variants in low-AF scenarios like liquid biopsy.

An obvious solution would be to name-sort the fastq files before processing. This would be a useful option for validation runs. What is your opinion? Any thoughts about the impact of read order on validation results?

**Comment by roryk** [comment]
Hi Ben!

Thanks, that is a good point. We're reluctant to add any kind of functionality to name-sort the FASTQ files up front since that adds an expensive pre-processing step that is going to be unnecessary for most of the runs. Is this something you all could handle up front yourselves by name-sorting the BAM file prior to starting a new run?

**Comment by gabeng** [comment]
Hi Rory,

you are right, you would not want the sorting to be performed with every sample. An option to activate sorting in bcbio would be most helpful, though. It would enable users to use bam/cram files as archive and still accurately reproduce validation results.

Regards,
Ben
