### ISSUE TITLE
Expected format of UMIs in fastq read names

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#3071]
Dear developers,

I am working with Illumina sequencing data from TruSight Oncology 500 panel (TSO500). My understanding is that the UMI kit used here makes use of two UMI sequences, one for each adapter. The output of `bcl2fastq` generates read names with the following structure:

```
@A00574:89:HCLMTDRXX:1:2101:1425:1016:CGAACGT+GTACACG 2:N:0:CTGAAGCT+GGCTCTGA
GTGATATAATTTATTTTCTTAAAATAGCCATGCTGGCTGGAGCCACAGCAGTTTACTCCCAGTTCATTACTCAGCTAACAGACGAAAACCAGT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

where I assume **CGAACGT+GTACACG** correspond to the two short UMI sequences. However, when running `bcbio` (variant calling) with `umi_type: fastq_name` I get:

```
ERROR:umis.umis:No annotation present on this file, aborting.
```

Could you please let me know how exactly should the UMI string be formatted? Am I right in assuming that I would need to concatenate the two sequences and add a `UMI_` prefix to it, e.g. **UMI_CGAACGTGTACACG**?

Thanks a lot in advance!
Federico

**Comment by roryk** [comment]
Hi Federico,

Yup, that is the format that is needed, if you make your reads look like this:

```
@A00574:89:HCLMTDRXX:1:2101:1425:1016:UMI_CGAACGTGTACACG 2:N:0:CTGAAGCT+GGCTCTGA
GTGATATAATTTATTTTCTTAAAATAGCCATGCTGGCTGGAGCCACAGCAGTTTACTCCCAGTTCATTACTCAGCTAACAGACGAAAACCAGT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

you should be all set.

**Comment by FedericoComoglio** [comment]
Thanks a lot! I now re-formatted read names and testing the pipeline with this new input.

**Comment by ohofmann** [comment]
@FedericoComoglio Let us know how this turns out - as you know we're working with TSO500 on Dragen in parallel; would be good to have bcbio support for comparison.
