### ISSUE TITLE
removing reference from bcbio installation

### ISSUE THREAD

**Issue by LeoWelter** [bcbio/bcbio-nextgen#3072]
I added GRCh37 to my bcbio installation for an ad-hoc project, but I'm switching to non-human species for new projects. How do I remove the genome properly from my bcbio installation. Deleting the genome directory leads to the following error when installing another genome:

ValueError: 
Problems with input reference file None
Did not find fasta reference file for genome GRCh37.
Check tool-data/*.loc files to ensure paths to reference data are correct.

Should I delete the GRCh37 lines from the .loc files manually? Anything else that should be taken care of?

**Comment by roryk** [comment]
Hi Leo,

That's right, nuking those lines from the .loc files should do it I think, let me know if that does the trick and I'll add it to the documentation.

**Comment by LeoWelter** [comment]
works indeed as expected. Thanks, saved a lot of diskspace.

**Comment by roryk** [comment]
Thank you for following up Leo, I'll add it to the docs!
