### ISSUE TITLE
SICER2 support

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3073]
Can we add SICER2 support for ChIP-seq peak calling?

I'm working on a bioconda recipe here:
https://github.com/bioconda/bioconda-recipes/pull/20017

Here are some URLs with more details:
- https://github.com/zanglab/SICER2
- https://pypi.org/project/SICER2/

**Comment by roryk** [comment]
Heya, ENCODE uses MACS2 (https://github.com/ENCODE-DCC/chip-seq-pipeline2)-- is there a reason for wanting SICER2 over it?

**Comment by mjsteinbaugh** [comment]
We're using MACS2 primarily for peak calling but some vendors (e.g. ActiveMotif) are using SICER internally in their pipelines. I thought it might be a good idea to build in support, since it seems to be a popular alternative to MACS2.

**Comment by roryk** [comment]
Gotcha, we're probably not going to do it unless its demonstrably better than MACS2 as it will add a bunch of support overhead.

**Comment by mjsteinbaugh** [comment]
No worries thanks Rory. We may just pipeline it out in Nextflow.

**Comment by roryk** [comment]
Thanks! It would be awesome to know if it performs better-- if you end up using it and it beats MACS2, let us know. Closing for now.

**Comment by roryk** [comment]
Are you using bowtie2 or bwa for your alignments?

**Comment by mjsteinbaugh** [comment]
bowtie2
