### ISSUE TITLE
variant caller xAtlas

### ISSUE THREAD

**Issue by LeoWelter** [bcbio/bcbio-nextgen#3076]
does anyone have experience with using gVCFs from xAtlas as input for joint-genotyping?
see https://github.com/jfarek/xatlas
https://www.biorxiv.org/content/10.1101/295071v1
if not I would like to try implementing it along the other available options.

**Comment by roryk** [comment]
Hi Leo,

It looks like that repository is abandoned-- no commits for over a year and a half and not a lot of action before that. Is there a reason why you want to use it over options that are already available?

**Comment by vdejager** [comment]
Thanks Rory, I have a lot of files made by a predecessor and not always access to the raw data. We might still have DNA though. He claims it was/is much faster and accoording to some tests he did it was performing equally to GATK. 
I would need to match new data with what we already have for what its worth.

But indeed....my preference would go to GATK for this project

**Comment by LeoWelter** [comment]
Thanks Rory, I have a lot of files made by a predecessor and not always access to the raw data. We might still have DNA though. He claims it was/is much faster and accoording to some tests he did it was performing equally to GATK
I would need to match new data with what we already have for what its worth.

But indeed...my preference would go to GATK for this project
