### ISSUE TITLE
No trimming in Variant2Pipeline?

### ISSUE THREAD

**Issue by mariogiov** [bcbio/bcbio-nextgen#308]
I may be missing something here but is the trimming step intentionally left out of the Variant2Pipeline? It is present [in the RNASeq pipeline](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/main.py#L378) but I don't see it being called in variant2. If this is the case, what's the thinking behind skipping this step? I read that the newer GATK pipelines don't require quality trimming but adapter trimming still seems relevant, unless I misunderstand.

**Comment by audyavar** [comment]
I am having issues with adapter contamination in tumor samples from my exomeSeq data. But I don't see an option to trim adapters in exomeSeq config files. When I add the following lines to the config file, it gives the error "yaml.scanner.ScannerError: mapping values are not allowed here
  in "/arcusdata/au/pact131_exomeseq/config/exomeseq_config.yaml"
1 trim_reads: atropos
2      adapters: [nextera2]

But I do have adapter content in more than 10% of my sequences. Is this not a high enough number where adapter trimming will be needed?
![fastqc_adapter_content_plot](https://user-images.githubusercontent.com/2364625/53278660-64d75d80-36bf-11e9-9650-1f229f805acb.png)

**Comment by lpantano** [comment]
Hi,

Can you try using tream_reads: true and in adapters put the exactly sequence?

I think that should trigger the trimming.

Let me know what happens.

**Comment by audyavar** [comment]
Yes this worked perfectly. Thanks!!

Sincerely,

Akshata
