### ISSUE TITLE
Adding tool specific setting in yaml file

### ISSUE THREAD

**Issue by alhafidzhamdan** [bcbio/bcbio-nextgen#3099]
Dear Bcbio team,

I want to add this flag (--f1r2-tar-gz) to the caller mutect2 in my variant.yaml file.
Here's how i've done it. 

details:
- algorithm:
    aligner: false
    mark_duplicates: false
    remove_lcr: true
    mixup_check: qsignature
    variantcaller: 
      somatic: [vardict, strelka2, mutect2]
      germline: [gatk-haplotype]
    min_allele_fraction: 5
    indelcaller: false
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
      use_filtered: false
    tools_off: [gemini]
    tools_on: [gatk4]
  analysis: variant2
  genome_build: hg38
  resources:
    mutect2:
      options: ["--f1r2-tar-gz", "f1r2.tar.gz"]

However, my vcf output file doesn't seem to have used the flag at all. 
Have I done the right thing?

**Comment by alhafidzhamdan** [comment]
Essentially i want to use the new tool by GATK4.1.4.1 here https://gatk.broadinstitute.org/hc/en-us/articles/360035531132

**Comment by naumenko-sa** [comment]
Hi @alhafidzhamdan!

Yes, that looks right. The only thing I don't see indentation in your yaml, resources should be top level:
https://github.com/bcbio/bcbio-nextgen/blob/master/config/examples/mitochondrial_variants_amplicons.yaml

Mutect2 module should pull the resources from the yaml
https://github.com/bcbio/bcbio-nextgen/blob/a3473775db06540c10b5f20ddc2043b8cc99d1f8/bcbio/variation/mutect2.py#L106
could you please add bcbio-nextgen-commands.log to confirm, that the mutect call was correct?

Sergey

**Comment by alhafidzhamdan** [comment]
Thank you. Yes the indentations are correct- just didn't paste it correctly on here. Here's an example log.

> unset JAVA_HOME && export PATH=/gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/bcbiotx/tmpz36aajty' Mutect2 --annotation ClippingRankSumTest --annotation DepthPerSampleHC --reference /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage --read-validation-stringency LENIENT -I /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/prealign/DO10900T/DO10900T-prealign.bam --tumor-sample DO10900T -I /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/prealign/DO10900N/DO10900N-prealign.bam --normal-sample DO10900N -L /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/mutect2/chrUn_KI270334v1/DO10900-chrUn_KI270334v1_0_285-regions-nolcr.bed --interval-set-rule INTERSECTION -O /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/mutect2/chrUn_KI270334v1/DO10900-chrUn_KI270334v1_0_285-raw.vcf.gz && sed -i 's/callable\t0.0/callable\t10.0/' /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/mutect2/chrUn_KI270334v1/DO10900-chrUn_KI270334v1_0_285-raw.vcf.gz.stats && unset JAVA_HOME && export PATH=/gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/bcbiotx/tmpz36aajty' FilterMutectCalls --reference /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/genomes/Hsapiens/hg38/seq/hg38.fa --variant /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/mutect2/chrUn_KI270334v1/DO10900-chrUn_KI270334v1_0_285-raw.vcf.gz --output /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO10900/bcbiotx/tmpz36aajty/DO10900-chrUn_KI270334v1_0_285-raw-filt.vcf.gz

It doesn't seem to include the flag --f1r2-tar-gz. 
And the output vcf is the no difference than the original vcf.
Do you think it's because i included "f1r2.tar.gz" as a stdout filename, within the yaml file?

**Comment by alhafidzhamdan** [comment]
Also i note in this version of mutect.py, there is no flag --f1r2-tar-gz. 

Whereas in the master version - https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/mutect2.py
there is.
I wonder it doesn't work because of this?
Essentially mutect2 got updated with the flags --f1r2-tar-gz and LearnReadOrientationModel a month back.

**Comment by alhafidzhamdan** [comment]
@naumenko-sa any thoughts?

**Comment by naumenko-sa** [comment]
Hi @alhafidzhamdan !

1. Please update to the latest development to have the same mutect2.py as in the master:
```bcbio_nextgen.py upgrade -u development```

2. Try to add `mutect2_readmodel` switch to your bcbio.yaml:
```
tools_on:
- gatk4
- mutect2_readmodel
```

I think this switch turns on the parameter:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/mutect2.py#L110
and you don't need to specify resources, as it is doing it automatically.

Please let us know, how it works. It is a new feature and needs more feedback.

Sergey

**Comment by lbeltrame** [comment]
I didn't have many files to test the MuTect 2 read model with: in fact some files made it break, so that is one of the reasons it's behind a `tools_on` flag.

**Comment by naumenko-sa** [comment]
thanks @lbeltrame 
@alhafidzhamdan  please reopen if you have any updates on that
