### ISSUE TITLE
Convert documentation to Markdown

### ISSUE THREAD

**Issue by hackdna** [bcbio/bcbio-nextgen#3100]
Currently (v1.2.0) most of the project documentation is written using reStructuredText:
* https://github.com/bcbio/bcbio-nextgen/tree/v1.2.0/docs (published on [Read theDocs](https://bcbio-nextgen.readthedocs.io/en/latest/))
* https://github.com/bcbio/bcbio-nextgen/blob/v1.2.0/README.rst (published on [PyPI](https://pypi.org/project/bcbio-nextgen/))
* Documentation already written in Markdown: 
  * https://github.com/bcbio/bcbio-nextgen/blob/v1.2.0/CODE_OF_CONDUCT.md
  * https://github.com/bcbio/bcbio-nextgen/blob/v1.2.0/HISTORY.md

Motivation:
* Markdown has a simpler syntax and is easier to edit than reStructuredText
* Markdown is supported by [Read the Docs](https://blog.readthedocs.com/adding-markdown-support/) (CommonMark) and [PyPI](https://packaging.python.org/guides/making-a-pypi-friendly-readme/) (GitHub Flavored Markdown by default, or CommonMark)

Challenges:
* There are many different flavors of Markdown but there is [CommonMark Spec](https://spec.commonmark.org/)
* `toctree` directive and `:ref:` markup are not supported but it looks like there are workarounds available: https://recommonmark.readthedocs.io/en/latest/auto_structify.html

Reference:
* https://commonmark.org/
* https://blog.readthedocs.com/adding-markdown-support/
* https://packaging.python.org/guides/making-a-pypi-friendly-readme/
* https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx
* https://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst
* https://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/
* https://www.zverovich.net/2016/06/16/rst-vs-markdown.html

**Comment by naumenko-sa** [comment]
Great, if there are no objections, @hackdna please convert to Markdown!

I'd also propose later to reorganize docs in the 'user story' format, i.e. a page about germline variant calling:
- quick start
- all parameters described
- latest validation
- output
- steps in detail
- links to the key past discussions on github
- performance and resource estimates 

currently we have the following user stories:
- installation and update story
- small variants germline 
- SV/CNV for WGS
- somatic variant calling
- methylation
- smallRNA
- bulk RNA-seq
- scRNAseq
- chip-seq/ataq seq
- developer story

Each story is rather split between different pages now.

SN

**Comment by roryk** [comment]
Thank you so much everyone, I love this.

**Comment by hackdna** [comment]
Great, thanks. I agree that the docs could be organized better but I will focus on the conversion first to keep the scope of the changes constrained. I will open a separate issue for the re-org.
Btw, is `TODO.md` still needed? It has not been touched in over four years: https://github.com/bcbio/bcbio-nextgen/blob/master/TODO.md

**Comment by roryk** [comment]
TODO is definitely not needed, feel free to nuke. Thank you!
