### ISSUE TITLE
heads up: update to R3.6.0

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3109]
Hello everyone!

We need to update R to 3.6.0 as some tools, in particular [PureCN](http://bioconductor.org/packages/release/bioc/html/PureCN.html) require it.

I'm turning it on here:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml

Please let us know if you see any terrible installation or R package issues.

Sergey

**Comment by naumenko-sa** [comment]
R 3.5.1 > 3.6.0 causes massive issues, so I reverted it for now.
Will continue testing.

**Comment by hackdna** [comment]
Btw, is there a way to make changes to tools in `packages-conda.yaml` locally without having to update that file in the cloudbiolinux repo?

**Comment by roryk** [comment]
Yes-- when bcbio is doing an update, it grabs cloudbiolinux. If you do:

```
   mkdir tmpbcbio-install
   ln -s `pwd`/cloudbiolinux tmpbcbio-install/cloudbiolinux
```

it will skip that step and the link instead, so you can make the change locally and test it out before pushing it.

**Comment by roryk** [comment]
One thing we could do to get PureCN working is to install it into it's own environment, so we can skip having to deal with the R 3.6 issues in general for dealing with that specific issue while we get ready for R 3.6.

**Comment by lbeltrame** [comment]
It would be a good idea. Currently I offload everything PureCN related to outside bcbio, but this would greatly simplify things.

**Comment by naumenko-sa** [comment]
I have pushed R3.6 and pureCN environemnt to cloudbiolinux. @roryk is currently fixing bcbio side of it, to make the right call of pureCN.

**Comment by naumenko-sa** [comment]
Updated by Rory:
https://github.com/bcbio/bcbio-nextgen/blame/e2ca576cf3ae03cc85eb775c41b4c55305f30b47/bcbio/structural/purecn.py#L101

Please reopen if you see any issues.
