### ISSUE TITLE
Mosiac chromosomal alterations

### ISSUE THREAD

**Issue by roryk** [bcbio/bcbio-nextgen#3113]
Hi everyone,

Does anybody have any experience calling mosiac chromosomal alterations? We've had some folks asking about it but I have no idea where to begin in terms of validating what actually works well. I've been pointed at https://github.com/freeseek/mocha for a good resource. Do any of you have any actual experience with calling these?

**Comment by naumenko-sa** [comment]
Hi!

I have not done it myself, but I'd also suggest to look at how DDD folks did it:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5630034/
https://github.com/asifrim/mrmosaic

S

**Comment by kokyriakidis** [comment]
Hi! 

This new paper may be interesting!
https://www.nature.com/articles/s41598-020-59963-8

**Comment by kokyriakidis** [comment]
Rory you can also look at this tool:
https://github.com/parklab/MosaicForecast
