### ISSUE TITLE
Bismark installation issue?

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3117]
Hello everyone!

I'm updating bcbio with
```
bcbio_nextgen.py upgrade -u skip --data --genomes BDGP6 --datatarget smallrna
```

And it seems that bismark does not skip reference installation (it has been installed already):
```
Writing bisulfite genomes out into a single MFA (multi FastA) file

Bisulfite Genome Indexer version v0.22.1 (last modified: 14 April 2019)

A directory called /n/shared_db/bcbio/biodata/genomes/Dmelanogaster/BDGP6/bismark/Bisulfite_Genome/ already exists. Already existing converted sequences and/or already existing Bowtie 2 or HISAT2) indices will be overwritten!
```

It works fine for human genome, something is wrong with non-human? 

Sergey

**Comment by roryk** [comment]
Thanks, I can take a look-- it shouldn't be genome dependent at all. Are we sure the bismark genome was complete? It is possible files were missing and that is why it was not skipped. If you rerun now, does it skip it properly?

**Comment by naumenko-sa** [comment]
I re-ran several times, it reinstalls every time:
(o2): /n/shared_db/bcbio/biodata/genomes/Dmelanogaster/BDGP6/bismark

**Comment by roryk** [comment]
Thanks! I must have messed up the memoization check, I'll fix it.

**Comment by roryk** [comment]
Thanks! I added in the step to check if the index is already made.

**Comment by naumenko-sa** [comment]
Thanks, it works!
