### ISSUE TITLE
RFC: allele fraction thresholds for paired analyses

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#314]
MuTect and VarScan has a threshold setting (`--tumor_f_pretest`) to select sites with at least a certain fraction of non-REF alleles. Something similar is in VarScan (minimum frequency to call an allele as heterozygote). MuTect has no preset, VarScan has 0.1 by default.

I'm wondering if (hence the RFC) this could be handled in the algorithm parameters, or at least harmonized between the two callers. Selecting a proper "frequency" (quotes, because you can't really call it frequency when you have just a sample pair) is important for validation.

Opinions? Pro, contra?

**Comment by audyavar** [comment]
Is varscan2 part of BCBIO1.1.6? I don't see it in the configuration options documentation on bcbio readthedocs yet.

**Comment by chapmanb** [comment]
It is, if you add `varscan` to your `variantcaller` specification it will use that. We emphasize using other somatic callers (VarDict, MuTect2, strelka2, octopus) which are actively developed and we feel do a better job, but it's still available to use. Hope this helps.

**Comment by audyavar** [comment]
Thanks Brad. I typically use a combination of 3 callers - one of which is varscan. When bcbio runs, its says Varscan and not varscan 2, so was wondering which version it was.

Best

Akshata

________________________________

**Comment by chapmanb** [comment]
Akshata;
That's right on, the original varscan isn't really used so we didn't need naming to differentiate them. If you want to check the version of any tool installed with bcbio you can use the `conda list` functionality:
```
$ bcbio_conda list | grep varscan
varscan                   2.4.3                         2    bioconda
```

**Comment by roryk** [comment]
Looks like this is some old discussion that got bumped with a question about varscan, which got answered. Closing this, thanks everyone!
