### ISSUE TITLE
fresh install of bcbio 1.2.0 fails running hlacaller: optitype due to configparser in python2

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3145]
Hello everyone!

In a fresh 1.2.0 bcbio installation variant calling with `hlacaller: optitype` fails at

https://github.com/FRED-2/OptiType/blob/master/OptiTypePipeline.py#L231

A fresh one has python 2.7.17 in python2 environment and a backported module configparser:
```
>>> import os
>>> import configparser
>>> config = configparser.SafeConfigParser(os.environ)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1264, in __init__
    super(SafeConfigParser, self).__init__(*args, **kwargs)
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 637, in __init__
    self._read_defaults(defaults)
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1255, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 750, in read_dict
    raise DuplicateOptionError(section, key, source)
backports.configparser.DuplicateOptionError: While reading from u'<dict>': option u'http_proxy' in section u'DEFAULT' already exists
```

A less fresh one with python 2.7.15 does not have it and works fine:
```
>>> import os
>>> import configparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named configparser
>>> import ConfigParser as configparser
>>> config = configparser.SafeConfigParser(os.environ)
```

Andras @andras86, would it be possible to fix this on the Optitype side?

Raised an issue in https://github.com/FRED-2/OptiType/issues/101

@hackdna, could you please review the issue? If it is not get fixed fast in OptiType, we need to fix it fast ourselves: HLA typing is one of the major use cases and this issue is blocking people from updating to bcbio 1.2.0+.

The right thing to do is, probably, to finish the python3 transition for OptiType and update the bioconda recipe:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/optitype/meta.yaml

Sergey

**Comment by hackdna** [comment]
Happy to have a look but need to know how to reproduce this first.

**Comment by naumenko-sa** [comment]
Fixed and merged in the optitype repo.
We still need a new release of optitype and to update the conda package to apply the fix widely.
I contacted Andras.

**Comment by roryk** [comment]
Looks like they need some help fixing their travis builds too, some missing dependencies: https://travis-ci.org/github/FRED-2/OptiType/jobs/670475453

**Comment by naumenko-sa** [comment]
update: switching optitype to python3 in bioconda:
https://github.com/bioconda/bioconda-recipes/pull/21347

**Comment by naumenko-sa** [comment]
merged in biocona, updated in cloudbiolinux:
https://github.com/chapmanb/cloudbiolinux/commit/a507600f8bbd49f629d49aba4b838081ccd12e3d
closing
