### ISSUE TITLE
fabric not found

### ISSUE THREAD

**Issue by saxejeffreyd** [bcbio/bcbio-nextgen#315]
I'm attempting to do a new install on the AZ system in China.  It went pretty far, but then died looking for fabric.

[root@cniclmgt003 0.7.6]# ./bcbio-nextgen/anaconda/pkgs/python-2.7.6-0/bin/python bcbio_nextgen_install.py /gpfs01/apps/az/bcbio-nextgen/stable/0.7.6/bcbio-nextgen --tooldir=/gpfs01/apps/az/bcbio-nextgen/stable/0.7.6/tooldir
Checking required dependencies
git version 1.7.1
Installing isolated base python installation
Installing bcbio-nextgen
# All requested packages already installed.
# packages in environment at /gpfs01/apps/az/bcbio-nextgen/stable/0.7.6/bcbio-nextgen/anaconda:
# 

numpy                     1.8.0                    py27_0  
# All requested packages already installed.
# packages in environment at /gpfs01/apps/az/bcbio-nextgen/stable/0.7.6/bcbio-nextgen/anaconda:
# 

biopython                 1.63                 np18py27_0  
boto                      2.25.0                   py27_0  
cython                    0.20.1                   py27_0  
ipython                   1.1.0                    py27_0  
lxml                      3.3.1                    py27_0  
matplotlib                1.3.1                np18py27_0  
nose                      1.3.0                    py27_0  
numpy                     1.8.0                    py27_0  
pandas                    0.13.1               np18py27_0  
patsy                     0.2.1                np18py27_0  
pip                       1.5.2                    py27_0  
pycrypto                  2.6.1                    py27_0  
pysam                     0.6                      py27_0  
pyyaml                    3.10                     py27_0  
pyzmq                     14.0.1                   py27_0  
requests                  2.2.1                    py27_0  
scipy                     0.13.3               np18py27_0  
statsmodels               0.5.0                np18py27_0  
tornado                   3.2.0                    py27_0  
Downloading/unpacking fabric
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement fabric
Cleaning up...
No distributions at all found for fabric
Storing debug log for failure in /root/.pip/pip.log
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 228, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 35, in main
    bcbio = bootstrap_bcbionextgen(anaconda, args, remotes)
  File "bcbio_nextgen_install.py", line 66, in bootstrap_bcbionextgen
    subprocess.check_call([anaconda["pip"], "install", "fabric"])
  File "/gpfs01/apps/az/bcbio-nextgen/stable/0.7.6/bcbio-nextgen/anaconda/pkgs/python-2.7.6-0/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/gpfs01/apps/az/bcbio-nextgen/stable/0.7.6/bcbio-nextgen/anaconda/bin/pip', 'install', 'fabric']' returned non-zero exit status 1
[root@cniclmgt003 0.7.6]#

**Comment by ggrimes** [comment]
I am having a similar issue installing bcbio-nextgen when it tries to install fabric.

python bcbio_nextgen_install.py  /export/users/bcbio/bcbio_nextgen --tooldir=/export/users/bcbio/bcbio-nextgen --isolate  --genomes GRCh37 --aligners bwa --aligners bowtie2
Checking required dependencies
git version 1.5.5.6
Installing isolated base python installation
Installing bcbio-nextgen
Fetching package metadata: ....
Solving package specifications: .
 All requested packages already installed.
 packages in environment at /export/users/bcbio/bcbio_nextgen/anaconda:

numpy                     1.9.1                    py27_0
Fetching package metadata: ......
Solving package specifications: .
 All requested packages already installed.
 packages in environment at /export/users/bcbio/bcbio_nextgen/anaconda:

biopython                 1.65                 np19py27_0
boto                      2.36.0                   py27_0
cnvkit                    0.3.2                np19py27_1
cpat                      1.2.2                    py27_0
cython                    0.22                     py27_0
ipython                   2.4.1                    py27_0
lxml                      3.4.2                    py27_0
matplotlib                1.4.2                np19py27_0
msgpack-python            0.4.1                    py27_0
nose                      1.3.4                    py27_0
numpy                     1.9.1                    py27_0
pandas                    0.15.2               np19py27_0
patsy                     0.3.0                np19py27_0
pip                       6.0.8                    py27_0
pycrypto                  2.6.1                    py27_0
pysam                     0.8.1                    py27_1
pyvcf                     0.6.7                    py27_0
pyyaml                    3.11                     py27_0
pyzmq                     14.5.0                   py27_0
reportlab                 3.1.44                   py27_0
requests                  2.5.1                    py27_0
scikit-learn              0.15.2               np19py27_0
scipy                     0.15.1               np19py27_0
seaborn                   0.5.1                np19py27_0
setuptools                12.1                     py27_0
sqlalchemy                0.9.8                    py27_0
statsmodels               0.6.1                np19py27_0
toolz                     0.7.1                    py27_0
tornado                   4.1                      py27_0
Collecting fabric
  Could not find any downloads that satisfy the requirement fabric
  No distributions at all found for fabric
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    bcbio = bootstrap_bcbionextgen(anaconda, args, remotes)
  File "bcbio_nextgen_install.py", line 68, in bootstrap_bcbionextgen
    subprocess.check_call([anaconda["pip"], "install", "fabric"])
  File "/opt/gridware/apps/gcc/python/2.7.6/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/export/users/bcbio/bcbio_nextgen/anaconda/bin/pip', 'install', 'fabric']' returned non-zero exit status 1
