### ISSUE TITLE
UMI and structural variant calling

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3153]
I was contemplating to evaluate different SV callers on UMI data. It appears, however, that the fgbio workflow removes all non-perfect reads from the consensus bam file. 
I was therefore wondering if the result of read collapsing by UMI is suitable for SV calling at all. One would probably rather use a BAM file including unmapped, low quality reads as input for SV callers, right? 
What is the reasoning why bcbio uses the cleaned collapsed-reads bam file for SV variant calling?

**Comment by naumenko-sa** [comment]
Hi Ben @gabeng!

Thanks, any SV validation would be very useful!

SV callers are of two sorts: split-reads algorithms (all used in bcbio excep cnvkit) and read depth.
Also we add duphold coverage information to split-read produced SVs.

UMI read processing is explained here: 
https://bcbio-nextgen.readthedocs.io/en/latest/contents/internals.html#somatic-tumor-only-variant-calling-pipeline-with-umis-step-by-step

It is mostly tuned for low frequency somatic variant calling. But I think it makes sense for split-read SV calling methods as well.

To call without UMI you may try to omit `umi_type: fastq_name` option, and the run would be processed without UMI collapsing. Please share validation results if you can.

Previous SV validations (no UMI) https://github.com/bcbio/bcbio-nextgen/issues/2313

Sergey

**Comment by gabeng** [comment]
Hi Sergey,
you put the finger in the wound: I am lacking useful validation data. The target in these applications is so tiny that it is basically impossible to find a suitable reference sample.
I appreciate your documentation. It is super helpful. The `fgbio` documentation says that reads are [filtered pretty aggressively in the process](http://fulcrumgenomics.github.io/fgbio/tools/latest/GroupReadsByUmi.html). 

If I come across a true variant I will try to evaluate if the UMI process improves detection and post it here. Thanks for your input.
