### ISSUE TITLE
Avoid editing the source code to keep the work directory between test runs

### ISSUE THREAD

**Issue by hackdna** [bcbio/bcbio-nextgen#3155]
The current behavior (v1.2.1) is to delete the work directory before a test run. While it is useful to keep the work directory in some circumstances it should not be necessary to edit the source code to accomplish that (https://github.com/bcbio/bcbio-nextgen/commit/936ed35121d83f47b868b673a14f6775ed0b076b).

Note: it appears that the work directory is deleted after each successful test run but not after a failed run.

**Comment by roryk** [comment]
Thanks! I agree this sucks to do this and fixing it would be good.
