### ISSUE TITLE
Error in "Getting Started" instructions

### ISSUE THREAD

**Issue by tony-travis** [bcbio/bcbio-nextgen#3162]
Hi, Documenters.

There is an error in:

[Getting Started](https://bcbio-nextgen.readthedocs.io/en/latest/contents/intro.html#getting-started)
```
python bcbio_nextgen_install.py [bcbio_installation_path] --tooldir [tools_installation_path] --nodata
Missing '=' -------------------------------------------------------^
```
Omitting the '=' created a null "[tools_installation_path]" that caused errors installing/upgrading tools.

I also suggest making the "[tools_installation_path]" default to './bin' in the "[bcbio_installation_path]"  if a separate "--tooldir=" is not specified - e.g. for the command:
```
python bcbio_nextgen_install.py /usr/local/bcbio --tooldir=/usr/local/bcbio/bin --nodata
```
Use a default "[tools_installation_path]" of "/usr/local/bcbio/bin" instead "--tooldir=":
```
python bcbio_nextgen_install.py /usr/local/bcbio --nodata
```
Bye, Tony.

**Comment by naumenko-sa** [comment]
Thanks, @tony-travis!
I have fixed GettingStarted.

Agree, it would be nice to set the default tooldir to `[bcbio_installation_path]/tools`.
If you or somebody wanted to implement that, test, and make a PR, that would be much appreciated!

It is a great case for the first code contribution!

S.
