### ISSUE TITLE
Locking down tool versions  or manually setting tool versions

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3164]
Hi,

Is it possible to specify or lock the versions of software packages and external tools installed using bcbio? I could not find any specific reference or way to do this but if there is a particular script I can edit or a way to provide these versions at installation that would be very helpful.

As always thanks for all the work to maintain such a helpful tool!

Thanks!
Warren

**Comment by naumenko-sa** [comment]
Hi Warren @waemm!

You may find program versions in `bcbio_project/final/project/programs.txt` of any bcbio run.
Example:
```
bamtofastq,2.0.87
bamtools,2.4.0
bcbio-nextgen,1.2.1-e7a95d4
bcbio-variation,0.2.6
bcftools,1.9
bedtools,2.27.1
biobambam,2.0.87
bioconductor-bubbletree,2.6.0
bowtie2,2.3.5.1
break-point-inspector,1.5
```

conda packages with some version restrictions are listed here:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml

If you want a freeze, you may install, and then avoid updating tools. That is the only way to lock down the versions.

SN

**Comment by waemm** [comment]
Thanks @naumenko-sa, the link was very helpful!

So if I were to fork the repo and apply my own version restrictions to the packages-conda.yaml  I could effectively lock the versions of all the tools ? I realise after installing bcbio this soft locks the packages but unfortunately I'd need the option to install an identical copy of bcbio on different clusters or reinstall if the current cluster drives fail.

**Comment by naumenko-sa** [comment]
Unfortunately, there is no way to freeze versions in a hard way. It is an old debate. We rely on many bioconda packages and other tools which constantly got updated and fixed. There are complex interdependencies between the packages, so you can't just specify the exact versions in the yaml. Conda reads the specification and solves the dependency tree during the installation. If you want strict versioning in production, you may have separate folders with bcbio and tools for every freeze you use and reuse data folder between them. Or clone and run VMs.

**Comment by gabeng** [comment]
I am not sure if using docker is an option on your cluster(s). In my view this is the only practical way to create a reproducible bcbio environment of a specific version. There is a useful history of older docker images available:
https://quay.io/repository/bcbio/bcbio-vc?tab=tags
It may make sense to archive data installations as well.

**Comment by waemm** [comment]
Thanks both for your replies, very helpful indeed! @gabeng thanks for the link, I do think docker seems to be the way forward. I am planning on running this on AWS infrastructure,  I know the native support via cromwell is not working yet so I assume I'll have to have a submission system in place such as SGE/PBS. If you have any better suggestions please let me know!

**Comment by gabeng** [comment]
I have no experience with cromwell. In my simple use cases a single instance and the built-in multi-threading in bcbio were sufficient. AWS Batch may be worth looking into if lock-in is not an issue for you.
