### ISSUE TITLE
Switch to Salmon selective alignment method

### ISSUE THREAD

**Issue by roryk** [bcbio/bcbio-nextgen#3166]
https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/

We already do the genome quantification since we align to STAR for quality control, so I'm not sure that this buys us anything for non hg38 genomes. For hg38 though it would be helpful, right now we are just supplying the decoys and the transcriptome.

We need to do these things:

1. Figure out if we need to do something special with the ALTs or not. I'm guessing no, but we should ask.
2. Can we do the new index creation on the fly, or does it take forever? If it takes forever, then we'll have to prep these indices as part of the genome creation step. This means we won't be able to do this method for user-supplied transcriptomes.
3. Is this better? On a simulated dataset it shouldn't be, but on a real dataset it should be. Checking this against a known set or at least one simulated to have more of the noise of a real dataset would be good.

**Comment by kokyriakidis** [comment]
Hi @roryk,

What's the current best practices for Bulk RNASeq?

Should I use hg38 with STAR and Salmon providing the quantify_genome_alignments option? Or should I use hg19 with STAR, Salmon and quantify_genome_alignments for better results? Or not use  quantify_genome_alignments at all?

**Comment by roryk** [comment]
Hi @kokyriakidis,

hg38 + STAR + the quantify_genome_alignments option is current best practice, but I don't have a comprehensive report up looking at the differences. Some folks at AstraZeneca looked at both and showed the quantify_genome_alignments did a better job on their patient data but YMMV though.
