### ISSUE TITLE
Install failed on hg38

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3169]
I've not been able to install bcbio with genome hg38, as it kept failing on while attempting to install dbsnp. Kindly refer to the attached file.
[bcbio.install.failed.txt](https://github.com/bcbio/bcbio-nextgen/files/4440514/bcbio.install.failed.txt)

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !

Probably, it was a github glitch recently?
The file is here:
https://gist.githubusercontent.com/matthdsm/f833aedd2d67e28013ff1d171c70f4ee/raw/442a45ed3ddc6e85c66c5e58e0fa78e16a0821c8/refseq2ucsc.tsv

I've updated dbsnp recently in hg38 installation.

Could you please try again?

Sergey

**Comment by naumenko-sa** [comment]
Feel free to re-open if the issue still persists.
