### ISSUE TITLE
realignment to new reference from cram?

### ISSUE THREAD

**Issue by LeoWelter** [bcbio/bcbio-nextgen#3183]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.2
 - OS name and version: CentOS or Ubuntu

Is it possible to start from a set of CRAM files aligned against GRCh37 and build a new dataset against GRCh38 directly or should I first manually reconstruct the fastq's?

I'm trying to merge older data with newly generated samples and would like to have a uniform sample treatment in the final results.

**Comment by roryk** [comment]
Hi Leo,

Hope you are keeping safe! You should manually reconstruct the FASTQ files, since bcbio won't be aware of where the original CRAM files came from.

**Comment by LeoWelter** [comment]
thanks,
I also hope everyone in the community keeps safe.
Guess I need to ask for more diskspace then....(no issue btw)

**Comment by roryk** [comment]
Thanks for following up Leo!
