### ISSUE TITLE
GRCz11 STAR indexing issue

### ISSUE THREAD

**Issue by vdejager** [bcbio/bcbio-nextgen#3195]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.3
 - OS name and version: redhat

**To Reproduce**
python bcbio_nextgen_install.py ${BASE}/${VERSION}/bcbio \
--tooldir=${BASE}/${VERSION}/tools \
      --genomes GRCz11 \
      --aligners star \
      --cores 16 \
      --datatarget rnaseq

indexing the zebrafish genome for STAR was stopped after exceeding the max job time (99h) on a 24 core 64 GB Haswell node. 

seems to be related to https://github.com/alexdobin/STAR/issues/650
GRCz10 went through fine

did anyone else encounter issues with zebrafish and STAR?

**Comment by naumenko-sa** [comment]
Hi @vdejager !

We do have  Zv11 genome  + STAR reference in our local installation.
I think it was installed as a custom genome:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#adding-custom-genomes
using the primary assembly.

If you could help updating GRCz11 recipe for everyone, that would be a fantastic contribution!
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCz11/seq.yaml

How to test a recipe:
https://github.com/chapmanb/cloudbiolinux/blob/master/doc/hacking.md#testing-a-ggd-recipe

Sergey

**Comment by vdejager** [comment]
Hi Sergey,

I managed to install GRCz11 with a stripped version of the genome. 
However, when I run an RNA-seq batch (on both the stable or development branch) I'm encountering an issue with STAR. The setting --sjdbGTFfile is set to None, which crashes STAR.
If I run the command with the GFT file in the  genome's rnaseq directory ( ref-transcripts.gtf) STAR works.
Is there a setting in the YAML config to specify the GTF file to use for STAR?

Vic
----------------
 /home/victor/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /home/victor/bcbio/genomes/Drerio_Zebrafish/GRCz11/star/ --readFilesIn <(gunzip -c /home/victor/projects/SRP113243/SRP113243/work/fastq/SRR5853083.fastq.gz) --runThreadN 7 --outFileNamePrefix /home/victor/projects/SRP113243/SRP113243/work/align/ --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outSAMattributes NH HI NM MD AS  --sjdbGTFfile **None**  --sjdbOverhang 100  --outSAMattrRGline ID:adult5 PL:illumina PU:adult5 SM:adult5  --outSAMstrandField intronMotif  --quantMode TranscriptomeSAM
May 06 19:42:45 ..... started STAR run
May 06 19:42:45 ..... loading genome
May 06 19:43:05 ..... processing annotations GTF

FATAL error, could not open file pGe.sjdbGTFfile=None

**Comment by naumenko-sa** [comment]
HI @vdejager !

Yes, we had this issue before.
You may try: `transcriptome_gtf` option:
https://github.com/bcbio/bcbio-nextgen/blob/a3473775db06540c10b5f20ddc2043b8cc99d1f8/config/templates/illumina-rnaseq.yaml#L24

Let us know if that works for Zebrafish!

SN

**Comment by naumenko-sa** [comment]
Feel free to re-open if that is not working!
