### ISSUE TITLE
two sample indices but only one sample output

### ISSUE THREAD

**Issue by sunliang3361** [bcbio/bcbio-nextgen#3204]
**Version info**
 - bcbio version (bcbio_nextgen.py --version):latest
 - OS name and version: o2

**To Reproduce**
 - Exact bcbio command you have used
 - Your sample configuration file

**Observed behavior**
Error message or bcbio output.

**Expected behavior**
I have two sample indices for my indrops sequences, after running bcbio pipeline, I only got one output for one sample. Do you know what my problem is . I have attached all log files

[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4553854/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/4553855/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4553856/bcbio-nextgen.log)

barcode_sample.csv is below:
AGAGGATA,S02
ATAGAGAG,S01
yaml file:
details:
- algorithm:
    cellular_barcode_correction: 1
    minimum_barcode_depth: 1000
    sample_barcodes: /n/scratch2/ls360/sc_zebra/config/sample_barcodes.csv
    transcriptome_fasta: /n/shared_db/bcbio/biodata/genomes/Drerio/Zv10/rnaseq-2018-03-02/ref-transcripts.fa
    transcriptome_gtf: /n/shared_db/bcbio/biodata/genomes/Drerio/Zv10/rnaseq-2018-03-02/ref-transcripts.gtf
    umi_type: harvard-indrop-v3
  analysis: scRNA-seq
  description: Burns
  files:
  - /n/scratch2/ls360/sc_zebra/input/Burns_1.fq.gz
  - /n/scratch2/ls360/sc_zebra/input/Burns_2.fq.gz
  - /n/scratch2/ls360/sc_zebra/input/Burns_3.fq.gz
  - /n/scratch2/ls360/sc_zebra/input/Burns_4.fq.gz
  genome_build: Zv10

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**

**Comment by roryk** [comment]
Sorry about that, I think our documentation might be a little off. Do you end up with this problem if you take the `barcode_sample.csv` file and just make it one line per barcode?

```
AGAGGATA
ATAGAGAG
```

**Comment by sunliang3361** [comment]
Thank you for your reply. I just tried and only got the last sample (ATAGGAG) result also.

**Comment by roryk** [comment]
Thanks, ok I can reproduce the problem-- I'm pretty sure it is an issue with `umis`, I'll fix it today.

**Comment by roryk** [comment]
Was the barcodes.csv file created on Windows? I figured out the problem. The barcodes.csv file has a byte order heading up front:

```
file barcodes.csv
barcodes.csv: UTF-8 Unicode (with BOM) text
```

which causes the barcodes to get parsed incorrectly:

```
ipdb> [x.strip() for x in barcodes]
['\ufeffAGAGGATA', 'ATAGAGAG']
```

if I make the same file on UNIX, I don't see this problem. You can fix the barcode your file by doing:

```bash
dos2unix /n/scratch2/ls360/sc_zebra/config/sample_barcodes.csv
```

and you should be all set. I'll catch this and fix this in the umis repository, but that should get you going. Thanks!

**Comment by sunliang3361** [comment]
Thank you so much! I am going to re-run it based on your suggestion and will update to you the result. Can I ask one question? Does BCBIO provide the total number of cells for each sample, information such as how many reads trimmed and mapped from the output folder? It seems I cannot find this type of information.

**Comment by roryk** [comment]
Hi Liang,

It doesn't, if we need to know that stuff we usually just do it by using the alignment files and what ended up in the `work/umis` directory. It would be good to calculate those things and make a MultiQC report with them in it though, we just have not gotten around to doing it.

**Comment by sunliang3361** [comment]
Got it. Thank you Rory. Does bcbio provide gene symbol for all genes ID in features.tsv.gz file (or mtx.rowname file)? It seems that I only have Ensembl gene ID but no symbol (10x has gene symbols) in this output file.  If there is no mitochondria gene symbol there, it seems percent.mt of volinplot in Seurat is alway 0. Just wondering if this is normal for bcbio pipeline? Thank you so much.

**Comment by roryk** [comment]
Hi Liang,

It's normal-- there isn't really a 1-1 mapping between symbols and gene IDs so we keep everything at the level of the ID and let the user decide how they want to annotate the IDs later on.

**Comment by sunliang3361** [comment]
Hi Rory,
I confirm that your solution worked for me. Thank you Rory.

**Comment by roryk** [comment]
Thanks for following up!
