### ISSUE TITLE
parsedAlternates: alignment does not start with match over padded sequence

### ISSUE THREAD

**Issue by chatchawit** [bcbio/bcbio-nextgen#3206]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.3
 - OS name and version: 18.04.4 LTS (Bionic Beaver)

YAML file

details:
  - files: [/nas1/peat/input/SRR5858156.1_1.fq, /nas1/peat/input/SRR5858156.1_2.fq]
    description: Glaucoma
    metadata:
       batch: Batch1
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      ensemble:
        numpass: 3
      variant_regions: /nas1/peat/input/lib/hg38/nextera_rapid_capture_expanded_exome_unique_intervals.bed
upload:
  dir: /nas1/peat/final
resources:
  tmp:
    dir: /home/bcbio/peat/tmp
  default:
    cores: 4
    memory: 4G
    jvm_opts: ["-Xms750m", "-Xmx4000m"]
  machine:
    cores: 16
    memory: 64

Error Message

subprocess.CalledProcessError: Command 'set -o pipefail; gunzip -c /home/bcbio/peat/work/gatk-haplotype/Glaucoma.vcf.gz | bcftools view -f 'PASS,.' --min-ac 1:nref  | vcfallelicprimitives -t DECOMPOSED --keep-geno | sed 's/ID=AD,Number=./ID=AD,Number=R/' | vt decompose -s -  | vt normalize -n -r /home/bcbio/install/stable/genomes/Hsapiens/hg38/seq/hg38.fa -  | awk '{ gsub("./-65", "./."); print $0 }' | sed -e 's/Number=A/Number=1/g' | bgzip -c > /home/bcbio/peat/tmp/tmpbtjsuwij/Glaucoma-noeff-decompose.vcf.gz

parsedAlternates: alignment does not start with match over padded sequence
15M4I9M1S
ZZZZZZZZZZQCCCZZZZZZZZZZ
ZZZZZZZZZZQNON_REF>ZZZZZZZZZZ

I found that "vcfallelicprimitives" causes the error.

**Comment by naumenko-sa** [comment]
No sure, if that immediately helps, but you are using jointcaller + ensemble.
Jointcaller is for population calling, ensemble is for combining calls from multiple callers (gatk, vardict).
jointcaller + ensemble should not be used together.

```
variantcaller: gatk-haplotype
jointcaller: gatk-haplotype-joint
ensemble:
    numpass: 3
```
SN

**Comment by naumenko-sa** [comment]
closing for now. Feel free to re-open if you still see the issue here.
