### ISSUE TITLE
[missing file]HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by tykim0109** [bcbio/bcbio-nextgen#3213]
**Version info**
 - bcbio version (bcbio_nextgen.py --version):1.2.3
 - OS name and version:Ubuntu 18.04

**To Reproduce**
 - Exact bcbio command you have used: python bcbio_nextgen_install.py -u development /apps1/local/share/bcbio --tooldir=/apps1/local --genomes hg19 --aligners bwa --aligners bowtie2

**Observed behavior**
Error message or bcbio output.
' ' '

> Running GGD recipe: hg19 genesplicer 2004.04.03
> --2020-05-08 16:27:45--  http://www.cs.jhu.edu/~genomics/GeneSplicer/GeneSplicer.tar.gz
> Resolving www.cs.jhu.edu (www.cs.jhu.edu)... 128.220.13.76
> Connecting to www.cs.jhu.edu (www.cs.jhu.edu)|128.220.13.76|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-05-08 16:27:45 ERROR 404: Not Found.

' ' '

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**

Hello,

I was installing bcbio, but ran into an issue due to a missing web link: http://www.cs.jhu.edu/~genomics/GeneSplicer/GeneSplicer.tar.gz

And fortunately, I found an alternative link to replace the original link:
ftp://ftp.ccb.jhu.edu/pub/software/genesplicer/GeneSplicer.tar.gz

I am not sure if this is a temporary issue, but I would appreciate if you let me know how to fix this.

Thank you.

**Comment by naumenko-sa** [comment]
Thanks for reporting @tykim0109!

It seems they removed the file from the server.
I've fixed the cloudbiolinux script with ftp link you provided.

https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/genesplicer.yaml.
Please re-open if you still have issues with this recipe.

Sergey
