### ISSUE TITLE
problems with loading datatargets

### ISSUE THREAD

**Issue by JenkoB** [bcbio/bcbio-nextgen#3229]
Hello, 

I have difficulties to dowloand databases for variant annotation:

**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.3.
 - OS name and version: Ubuntu 18.04.4 LTS

**To Reproduce**
python bcbio_nextgen_install.py upgrade --datatarget gemini --datatarget gnomad --datatarget vep --datatarget dbnsfp --datatarget battenberg --datatarget kraken --datatarget ericscript --genomes GRCh37

Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2020-05-21 10:24:43--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.240.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.240.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

requirements-conda.txt                  100%[===============================================================================>]      20  --.-KB/s    in 0s      

2020-05-21 10:24:43 (1,44 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Installing data and third party dependencies
Upgrading bcbio
Upgrading bcbio-nextgen data files
--2020-05-21 10:25:09--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2020-05-21 10:25:09--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 140.82.112.9
Connecting to codeload.github.com (codeload.github.com)|140.82.112.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 2,18M
  3072K ........ ........ ........ .......                    3,09M=2,0s

2020-05-21 10:25:12 (2,46 MB/s) - written to stdout [5189907]

Traceback (most recent call last):
  File "/home/kisld/BCBIO/upgrade/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/kisld/BCBIO/upgrade/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/kisld/BCBIO/upgrade/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 377, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/kisld/BCBIO/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 349, in install_data_local
    os.environ["PATH"] = "%s/bin:%s" % (os.path.join(system_installdir), os.environ["PATH"])
  File "/home/kisld/BCBIO/upgrade/anaconda/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/kisld/BCBIO/upgrade/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--datatarget', 'gemini', '--datatarget', 'gnomad', '--datatarget', 'vep', '--datatarget', 'dbnsfp', '--datatarget', 'battenberg', '--datatarget', 'kraken', '--datatarget', 'ericscript', '--genomes', 'GRCh37', '--data']' returned non-zero exit status 1

Out of the Error I can not figure out, what to do to downlad databases. Thank you for help.

Reards Barbara

**Comment by naumenko-sa** [comment]
Hi Barbara @JenkoB !

Once you have installed bcbio-nextgen package, i.e. with 
`python bcbio_nextgen_install.py ... --nodata`, you have the main script
`which bcbio_nextgen.py`.

You can use it to install data. This way you make sure you are using the right python.
`bcbio_nextgen.py  upgrade -u skip --data --datatarget gemini --genomes GRCh37`
(use one datatarget at time - some of them are quite long installs).

Sergey

**Comment by naumenko-sa** [comment]
I clarified the installation more in the docs:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html

**Comment by JenkoB** [comment]
Thanks!
