### ISSUE TITLE
Which genomes can be installed automatically?

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3231]
I was looking through the documentation for a list of currently supported genomes but couldn't find it. Then, searching on Google, I came across this: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/install.py#L40

Is this list up to date?

**Comment by naumenko-sa** [comment]
Yes, this list does not change much.

I've added more details about supported genomes to documentation:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html

We mostly focus on the existing genomes (99% of the analyses are on human, mouse, C.elegans, and Drosophila references). Users who need extra genomes usually install them as a custom genome.

SN

**Comment by amizeranschi** [comment]
Guess I'm in the 1%, then, working on cattle. Would be cool to get more people working on this species with bcbio. I saw that there's a docs page describing how to add new genomes for bcbio: https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html?highlight=adding%20genome#adding-new-organisms. Would it be worth adding an "official" Bos Taurus genome? I could give this a shot once I get a bit more experience with bcbio.

Meanwhile, I've set up a custom genome using `bcbio_setup_genome.py`. Would be nice if that script could also automate the set up of a VCF file with known variants for BQSR: https://github.com/bcbio/bcbio-nextgen/issues/3233.

One last thing, the list of genomes mentioned on that previous docs page: https://github.com/bcbio/bcbio-nextgen/blob/8c93fe2dc4d2966e106a4b3edf5aa23550703481/scripts/bcbio_nextgen_install.py#L236

is different from the list of genomes from my first post on this thread: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/install.py#L40. Some genomes like `rn6` and `WBcel235` are missing from the list from the docs. Is this outdated?

Thanks a lot for your help!

**Comment by hackdna** [comment]
Yes, we really need to simplify the installer to avoid duplication of functionality between `bcbio_nextgen_install.py` and `bcbio/install.py`

**Comment by amizeranschi** [comment]
I noticed now that the links in the docs refer to old commits of `bcbio_nextgen_install.py` and `bcbio/install.py`. 

I think the docs be updated to refer to https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/install.py#L40 and https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/bcbio_nextgen_install.py#L266.

**Comment by naumenko-sa** [comment]
Thanks, I have fixed the doc.
BTW, you can do the same if you see that something is obviously wrong in the docs - just edit on github, create a branch and submit a PR. We will just press merge or correct it.

Thanks for expanding bcbio use on cattle genomics! 

Unfortunately, we cannot place this use case in the list 
of current priorities higher than at the very bottom, which would mean 'never done'.
We have a big list to deliver this year in bcbio, it is mostly CNV/SV/RNA-seq variant calling, mobile element calling, etc on top, AWS and CWL need urgent attention.

So I'd suggest to continue calling variants on BosTau as a custom genome, accumulate experience, annotations (you can annotate with vcfanno using any vcf or bed).

Once you have enough material for a page on how to use bcbio in cattle genomics, we could create  such a page and link from
https://bcbio-nextgen.readthedocs.io/en/latest/contents/users.html

For now we could add a paragraph there if you like to describe your lab and research.

If you then bring every researcher in the cattle genomics field to the use of bcbio, i.e. people will need to re-use your your bcbio developments in BosTau, we could return to reviewing the use case and priorities, and discuss how to merge it safely.

Maybe not everyone will agree, but even putting aside our limited bandwidth, I'm not convinced in the use of BQSR (base quality score recalibration) and VQSR (variant quality score recalibration), at least when we are calling individual samples or small groups of samples. These days sequence quality is close to perfect, variant callers improved a lot, and we saw that hard filters give very good validation results compared to VQSR which is more computationally intense. 

If you sequence more and more individuals and want to aggregate calls, you may team up with @WimSpee who also has a unique use case with a custom genome, and outlined a whole detailed procedure on how to improve bcbio there: https://github.com/bcbio/bcbio-nextgen/issues/3036.
Maybe you can help to make it happen and it would be also useful in your case?

Closing for now, but feel free to submit a paragraph for users.html (or just PR it).

S.

**Comment by amizeranschi** [comment]
It's too early for me to submit PRs, but I will do so once I learn a bit more about all of this. 

The reason I was looking into BQSR is because it's a requirement of the 1000 Bull Genomes and they rely on a custom genome and VCF file with known variants: http://www.1000bullgenomes.com/. It's something we're looking into for the future, nothing crucial so far.

Thanks for all the info and good luck with the planned deliverables for this year!
