### ISSUE TITLE
Feature request: new option for bcbio_setup_genome.py to add a VCF file with known variants for BQSR

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3233]
It would help a lot to be able to add a VCF file with known variants for BQSR to a custom genome via the `bcbio_setup_genome.py` script and to have it automatically included into `bcbio_nextgen/genomes/${custom_genome}/seq/${custom_genome}.yaml`.

**Comment by naumenko-sa** [comment]
closing, see why here: https://github.com/bcbio/bcbio-nextgen/issues/3231
