### ISSUE TITLE
Speed up installation of third party tools

### ISSUE THREAD

**Issue by hackdna** [bcbio/bcbio-nextgen#3238]
Currently (v1.2.3), bcbio requires downloading and installing about [250 tools](https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml). This results in over 1,000 packages installed into the base Conda environment that consume about 12GB of storage (`PKGS_DIR`).

The default `conda` installer requires hours to install all these tools because the algorithm to resolve the dependencies has [superpolynomial performance](https://www.anaconda.com/blog/understanding-and-improving-condas-performance). This is not a new issue and several workarounds were implemented like using the experimental `mamba` installer and [separating some of the tools into their own environments](https://github.com/chapmanb/cloudbiolinux/blob/85077a102226bc8c89fa2cad62dae433c5252280/cloudbio/package/conda.py#L245).

These workarounds are only partially effective and are not sustainable in the long run (when more packages are added in the future) because they don't address the root cause - the excessive number of tools to install at once. While `mamba` is generally faster than `conda` it can still take a long time to run, it can randomly stop with errors, and it may not always install all the packages correctly, so [running `conda` is still required](https://github.com/chapmanb/cloudbiolinux/blob/85077a102226bc8c89fa2cad62dae433c5252280/cloudbio/package/conda.py#L40).

Slow and error-prone installation prevents running integration tests in Travis CI and provides a poor user experience. This also slows down development significantly.

Solutions (from [Conda performance best practices](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/conda-performance.html#improving-conda-performance)):
* specify exact versions of the tools required for installation (also helps with reproducibility)
* allow installing a small subset of tools that are required by each pipeline separately

Related issues:
* [can't upgrade to 1.1.3 due to conda being unable to solve environment #2676](https://github.com/bcbio/bcbio-nextgen/issues/2676)
* [UnsatisfiableError during bcbio install #2871](https://github.com/bcbio/bcbio-nextgen/issues/2871)
* [v1.1.9 install is hanging at conda environment solve #3040](https://github.com/bcbio/bcbio-nextgen/issues/3040)
* [clouldbiolinux debugging to reduce bcbio installation time #3054](https://github.com/bcbio/bcbio-nextgen/issues/3054)
* [unusable conda in latest bcbio on CentOS 7.6 time to solve 12+ hours not yet at 10% #3062](https://github.com/bcbio/bcbio-nextgen/issues/3062)
* [Lock conda environments #3174](https://github.com/bcbio/bcbio-nextgen/issues/3174)
* [Make installation and upgrading more robust #3191](https://github.com/bcbio/bcbio-nextgen/issues/3191)
* [Installation failed - mamba not found #3234](https://github.com/bcbio/bcbio-nextgen/issues/3234)
* [unable to do fresh install, conda problem #3240](https://github.com/bcbio/bcbio-nextgen/issues/3240)

**Comment by naumenko-sa** [comment]
Thanks for gathering all the info!
closing for now. 30 min installation is ok for most of the users. 
will re-open when our focus will be on it again
