### ISSUE TITLE
Run Mapping alone for RNASeq data using bcbio

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#3239]
Dear Bcbio team,

I found the below issue related to run only alignment which works with wgs variantcalling pipeline.
https://github.com/bcbio/bcbio-nextgen/issues/1030

But i didn't found the same for RNASeq data. Could you please let me know what changes to be done to yaml template in order to run only alignment & skip further steps like QC, generating counts using salmon & featureCounts etc for RNA_Seq data.

Thanks In Advance
Fazulur Rehaman

**Comment by roryk** [comment]
Hi Fazulur,

We don't currently have an option to just run the alignments, but we could add it. What's your use case so I can think about if there is a better way to go about it?

**Comment by Fazulur** [comment]
Hi @roryk,

Thanks for your quick response.

Sometimes, We will be receiving data for same sample in batches from different flowcells. We are merging fastq from same flowcell using bcbio prepare_samples.py program. 

We would like to do only alignment If we get new fastq files for same sampleid in next batch (instead of running enitrie bcbio RNA_Seq pipeline on new data), then merge previous bam with current bam file using samtools merge and submit the merged bam to bcbio RNA_Seq pipeline by modifying **aligner: false** in yaml config. 

Thanks In Advance
Fazulur Rehaman

**Comment by naumenko-sa** [comment]
Hi @Fazulur !

I have added your request to the bcbio priorities list.
Unfortunately, it seems it won't be addressed soon, sorry,
unless you want to contribute and test the solution yourself.

In the meanwhile, I'd warn you against creating hidden batch effects in your RNA-seq data.
See "Design aspects of RNA­seq" in https://peerj.com/preprints/27283/ and in the other sources.

Sergey

**Comment by Fazulur** [comment]
Hi @naumenko-sa,

Thanks a lot for update on my post and thanks for article on batch effects.

Thanks & Regards
Fazulur Rehaman
