### ISSUE TITLE
Paired variant calling final normal BAM files cropped

### ISSUE THREAD

**Issue by mjafin** [bcbio/bcbio-nextgen#324]
When running a single-normal, multiple-tumor analysis, the output BAM file is a fraction of the real BAM file size. The work/align/ folder contains the correct BAM file (at least in terms of expected file size) but the final/ folder contains a miniscule file. It would seem like variant calling is not affected by this, maybe only the final step of merging the final output BAM file..?

**Comment by aiminy** [comment]
where I can find refseq_exome_10bp_hg19_300_1kg_normal_panel.hg19.vcf file?
