### ISSUE TITLE
Effect on defining variant_regions

### ISSUE THREAD

**Issue by rkendar** [bcbio/bcbio-nextgen#3241]
Hi,

Currently, I am working on WGS data for T/N small and structural variant calling. And just wondering about the variant_regions parameter. If I specified the variant_regions, how it will affect the analysis?

- Will it affect the BAM (being filtered based on the bed)? 
- Will it affect all my variants called by somatic/germline callers and structural variants caller (only call variant in bed)?
- What other analysis will be affected?

Thank you.

**Comment by roryk** [comment]
Hi @rkendar,

You'd want to use `variant_regions` if you were doing exome sequencing-- the exome captures aren't perfect and have off-target region captured, and if you call variants there you will end up with a high amount of false positives. You can ignore it if you are doing WGS though. Thanks for the question!

**Comment by rkendar** [comment]
Hi @roryk ,

Thank you for your answer.

So basically if I specify the variant regions, all my results will be on WES (based on the BED file) even though I analyze the WGS data? If it is true, is there any shortcut to revert back to WGS, or I have to rerun the pipeline from the beginning without specifying the BED?

The thing is I have WGS data but I forget to remove the variant regions in my yaml. So seems like all my output is WES-like.

Thank you.

**Comment by roryk** [comment]
Hi @rkendar,

That stinks-- yeah, if you need the variants called everywhere you'll need to start from the beginning. You might be able to delete everything except the `align` directory, since I think the alignments should be independent, which might save you that step. But I'm not 100% sure if that would work or not so to be safe I'd just start over.

**Comment by rkendar** [comment]
Hi @roryk,

I see, got it! 
May I clarify, so the thing that you unsure is the alignment is independent (not affected by BED) or the pipeline will still work if I left only the align dir? Because if the alignment is independent, that actually helps a lot since it is the most time-consuming step.

**Comment by roryk** [comment]
Hi @rkendar,

The initial alignment is definitely independent, but there might be some files calculated from the alignments that are not that are stashed in those directories. I'm not 100% sure, so I don't want to lead you astray. You could nuke everything except the main alignment files in `align` if you wanted to be sure which would save you the initial costly WGS alignment.

**Comment by roryk** [comment]
Feel free to reopen if you run into problems. Thanks for the question!

**Comment by rkendar** [comment]
Hi @roryk,

Alright. Or since I already have the -ready.bam, maybe I just make another pipeline starting with BAM. From what I understand is I can skip the alignment process with `align: false` and call the variant directly. Am I correct?

Another thing is, just want to clarify. In the work/ bcbio generated `-sort.bam`, but in the final/ it has `-ready.bam`. However, I cannot find the command in bcbio-nextgen-commands.log how bcbio generated `-ready.bam` from `-sort.bam`. Are they the same? I noticed the size is smaller in -ready.bam.
