### ISSUE TITLE
a list of technical debt issues

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3243]
The issues below don't break production, however, it is good to have them solved at some point. 
Contributions welcome - pick an issue, ask to re-open the issue if you are working on it.
Some of them are good for the first contribution to bcbio.

CnvKit - 0.9.7b issues #3201 - waiting for new cnvkit release or using gatkcnv by deafult
Error in "Getting Started" instructions #3162
Remove Sailfish support #3157
Speed up installation of third party tools #3238 
related to 
Make installation and upgrading more robust #3191 
TypeError in test_atacseq #3225
FileNotFoundError in test_chipseq #3224
Allow custom genome installation with --no-data #3226 
ValueError in test_variantcall_2 #3218 
Value error in test_detect_fusions_with_ericscipt_with_disambiguate #3220
ValueError in test_detect_fusions_with_ericscipt_without_disambiguate #3219
ValueError in test_variantcall_1 #3217 
ValueError in test_fusion #3216 
Error running bcbio_nextgen.py version sub-command #3209
Upgrade to Ubuntu 20.04 LTS #3192
Move Docker tests out of the bcbio-nextgen repo #3176
Lock conda environments #3174
Avoid editing the source code to keep the work directory between test runs #3155
Remove legacy AWS setup documentation and code #3134

**Comment by hackdna** [comment]
GitHub issues are really not designed for project management. Can we create a technical debt project instead?

**Comment by naumenko-sa** [comment]
moved to bcbio priorities #3242
