### ISSUE TITLE
No result for hlacaller: optitype

### ISSUE THREAD

**Issue by rkendar** [bcbio/bcbio-nextgen#3252]
**Version info**
 - bcbio version : 1.1.5

Hi Bcbio Team,

Currently, I am running HLA typing using OptiType. I use BAM as input `aligner: false`, since I don't want to redo the mapping step to fasten the process. And I have specified `hlacaller: [optitype]` in my .yaml.

However, why it doesn't give me the output `-hla-optitype.csv` in my final/ or work/ ?
I did see the message about HLA typing in debug.log as below:
```
[2020-05-30T14:04Z] Timing: hla typing
[2020-05-30T14:04Z] multiprocessing: call_hla
```
But I cannot find ant optitype command in command.log. Do you know what happens? Is it because I start the input using BAM instead of FASTQ?
I have attached my .yaml. template.
[yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/4709436/yaml.txt)

Thank you!

**Comment by chapmanb** [comment]
Thanks for the question on HLA calling. You're exactly right that HLA calling is not available if you're not doing alignment as part of the run. When aligning, there is a bwa post-processing script that extracts HLA reads and then uses those as inputs for the calling process. You can start with bam files as inputs but will have to turn alignment on. Hope this helps.

**Comment by rkendar** [comment]
Hi @chapmanb ,

Thank you for your answer. I understand now.
But, if I'm turning on the aligner `aligner:  bwa`, will it raise any issue for other processes (like raise error since the input is BAM)? Because as you can see I have variantcaller and svcaller as well in my yaml file.

Thank you!

**Comment by roryk** [comment]
Hi @rkendar,

You can use a BAM file as input to bcbio and it will do the right thing for tools that need to start from FASTQ files so you should be all set.
