### ISSUE TITLE
Somatic variant analysis questions

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3254]
Hi guys,

Thanks for reworking the somatic variants documentation and user stories, it has been very helpful! I just wanted to ask about the panel of normals for mutect2 (It would be great if you can include a section for this in user stories as well), as I understand it this can be included in the analysis using the following in your YAML:

 background: 
   variant: pon.vcf

Is there functionality to create Mutect2 PON background files (using GenomicsDBImport etc.) in the bcbio framework ? It would be great to create all PON for CNV and variant calling simultaneously if that is possible. 

Also, I wanted to ask about the ensemble variant calling algorithm. You explain a more complicated use case where you specify the type of algorithm, then various parameters. Is this explained in depth somewhere? Does using this necessarily improve results or has this largely been replaced by the numpass arguement? 

Thanks again for your work!
Warren

**Comment by lbeltrame** [comment]
As far as I know, you need to create the MuTect PoN outside bcbio.

**Comment by naumenko-sa** [comment]
Hi Warren  @waemm!

1. I don't see a PON support in mutect2 module as input
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/mutect2.py
and we don't have PON creation support for small variants.

I agree, that we need to support it along the lines of 
https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2

2. Regarding ensemble calling. Yes, there were grounds to switch from sophisticated voting to just a `numpass` parameter. Unfortunately, I can't recall the details. I think, first of all, you can't compare quality values from the different callers, for example GATK uses by default much higher values than samtools.
You may try to dig  out more details here
https://github.com/bcbio/bcbio-nextgen/search?q=ensemble&unscoped_q=ensemble&type=Issues

Sergey

**Comment by waemm** [comment]
@naumenko-sa  @lbeltrame Hi Guys, thanks for your replies.  Is it possible that the background tag somehow overwrites the paired.normal parameter? I saw a previous comment from Brad mentioning that you could add the panel of normals like this https://github.com/bcbio/bcbio-nextgen/issues/2976

If using the numpass feature produced overall better results then that is good to know, however if there is someone I could discuss this with further to see if improvements could be made to the SVM then that would be great.

**Comment by lbeltrame** [comment]
I don't think `background`overwrites the pairing, or last time I tried it, it did not.  As for `numpass` I use it in a different way, to generate a union of all variant callers' calls, as opposed to an intersection. The other approaches are not that used, and as far as I can see, they're far more complicated.  I don't know much about the SVM code myself.

**Comment by waemm** [comment]
Thanks @lbeltrame , was this functionality removed? From the ticket I linked previously (#2976) Brad states that this is possible. Alternatively can I add this as an arguement to 
`resource: mutect2:` ?

**Comment by lbeltrame** [comment]
I did something like that a couple of days ago, and I believe it is still working, but I did not have any paired sample in the configuration file.

**Comment by naumenko-sa** [comment]
Thanks @lbeltrame  for correcting me! PON is an important use case!

@waemm it indeed works, I have tested with a T/N  pair and documented here:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/somatic_variants.html#parameters

Regarding ensemble calling, Brad developed https://github.com/bcbio/bcbio.variation.recall in `clojure` You are more than welcome to contribute. 

However, it has been discussed several times during the last years, and I think the consensus is close to what @lbeltrame  is doing - to pick up variants from many callers (union), and then use sophisticated filtration strategies downstream, tailored to the particular research/diagnostic needs, for example:
https://github.com/umccr/umccrise or https://www.solvebio.com/.

**Comment by lbeltrame** [comment]
Thanks for the pointer to umccrise: I've filed an issue with regards to their licensing (unspecified), but it might be worth looking at for downstream workflows. 

I don't use any "sophisticated" strategies at this point (save some pretty aggressive filtering) but I agree it is the way to go (in particular querying and using known databases).

**Comment by waemm** [comment]
Thanks both for your answers, @naumenko-sa I assume PON works with tumor-only as well? Thanks for clearing this up!

**Comment by lbeltrame** [comment]
It does. Be prepared to do some hard filtering post-run because you'll need to remove quite a bit of noise. Use the EPR field put in by bcbio for tumor-only analyses as a good way to slash some "called somatic but likely germline" variants that were called.

**Comment by waemm** [comment]
Thanks @lbeltrame, I have not used EPR for filtering yet, do you filter for "pass" ?  I have seen some benefit to harding filter for depth but I generally use PureCN to help with filtering. I was hoping with a PON in mutect and using ensemble calling I'd be able to filter quite a bit more effectively. If you have any further suggestions please let me know.

**Comment by lbeltrame** [comment]
I filter for "pass" and "pass;clinvar", because presence in ClinVar might mean something useful (I do some extra filtering down the road anyway).
