### ISSUE TITLE
-sort.bam and -ready.bam, are they the same?

### ISSUE THREAD

**Issue by rkendar** [bcbio/bcbio-nextgen#3259]
Hi Bcbio Team,

I would like to clarify about the output BAM. In the work/ bcbio generated `-sort.bam`, but in the final/ it has `-ready.bam`. However, I cannot find the command in `bcbio-nextgen-commands.log` how bcbio generated `-ready.bam` from `-sort.bam`. Are they the same? I noticed the size is smaller in `-ready.bam`.

Thank you!

**Comment by roryk** [comment]
Hi @rkendar,

It depends on the pipeline and what options you have set but generally the `-sort.bam` is an intermediate file that has some further processing done to it for most pipelines to get to the `-ready.bam` file, so they should usually be different.

**Comment by hackdna** [comment]
Would it makes sense to give these files more descriptive names and/or add this explanation to the docs?

**Comment by roryk** [comment]
Heya, I don't think so-- the work directory is design to house intermediate files so mapping out what they are isn't too useful. Just working from the -ready file is the intended workflow post run.

**Comment by skanwal** [comment]
Hi @roryk for clarification - are "all" the commands used for "further processing" of intermediate files recorded in the `bcbio-nextgen-commands.log` file?

**Comment by roryk** [comment]
They should be, but it is possible we are missing one in one of the pipelines. If you spot any missing, let us know and we can wrap it in the function that writes it out to the log.

**Comment by rkendar** [comment]
Hi @roryk ,

Thank you for your answer. 

I see. The reason I ask this is currently my variant calling has some issue (running on AWS), then I want to rescue the BAM to analyze it locally. Since the pipeline hasn't finished yet (because of that issue), so I don't have `final/` folder. Do you know where is the `-ready.bam` in `work/` folder? In `work/align/` I just can find the `-sort.bam`.

I have looked into the 3 logs file bcbio generated, but I can't find how is `-ready.bam` is generated from `-sort.bam` in `bcbio-nextgen-commands.log`. I can find `-ready.bam` in other 2 logs, but it just stated the path of the file in `final/` folder.

**Comment by roryk** [comment]
Hi @rkendar,

Ah, gotcha. The `-ready` BAM is just a renamed version of the BAM file that is being used and it isn't logged anywhere what the original name was. It would be good for us to add that to the log.  if you look at what is being used for variant calling, then that's the BAM file that will end up as the -ready BAM file, so you can grab that one and you should be all set.

**Comment by rkendar** [comment]
Hi @roryk ,

Yes, you're right! It used the `-sort.bam` from `work/align/`, so it should be the same with `-ready.bam`. But last time check they have slightly different sizes (`-ready.bam` is smaller), that's why I got confused and assume they're not the same. I will double-check it and get back to you.

And yes, adding the step how is `-ready.bam` generated (even only rename) in command.log will be great to avoid confusion, just in case. Thank you so much!

**Comment by roryk** [comment]
Thanks-- they should be the same size, it is just copying the file over, so it would be good to check if anything else has been done to the file. What pipeline are you running?

**Comment by rkendar** [comment]
Hi @roryk ,

Sorry for the late update. And yes after I compare about 20 BAMs, the `-ready.bam` and -`sort.bam` have the same size! So sorry for the wrong information previously. Thank you for your explanation :)

Now we're running paired T/N pipeline using mutect2 and strelka2 as variant_caller and cnvkit as sv_caller. But seems like sterlka2 have a problem when running in AWS, not sure what happened could be environment issue because it works well when we run locally, thus we just download the BAM to local and run locally.

**Comment by roryk** [comment]
Thanks for following up! Glad that helped-- we can help figure out the strekla2 problem if you can post what you are seeing in a new issue, another user was also having some troubles with strekla2 as well.

**Comment by naumenko-sa** [comment]
Hi! 

There was a python2/strelka2 issue:
https://github.com/bcbio/bcbio-nextgen/issues/3019

It is not a clean solution, but in some cases, it was solved by installing system-wide python2.

Sergey
