### ISSUE TITLE
java.lang.NullPointerException in GenotypeGVCFs

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3263]
Hi, 

I'm running into a java.lang.NullPointerException for some bcbio runs during the GenotypeGVCFs phase.

This is a known issue with GATK versions >= 4.1.5.0, as outlined here: https://gatk.broadinstitute.org/hc/en-us/community/posts/360060283092-GenotypeGVCFs-java-lang-NullPointerException and here: https://github.com/broadinstitute/gatk/issues/6548.

According to the first link above, a solution is to run GenotypeGVCFs with the setting `--genomicsdb-use-vcf-codec`: https://gatk.broadinstitute.org/hc/en-us/articles/360040509751-GenotypeGVCFs#--genomicsdb-use-vcf-codec

Is there any way of passing this setting to GenotypeGVCFs from within Bcbio?

**Comment by roryk** [comment]
Thanks so much for figuring out the source of the problem and how to work around it-- you can pass it via the `options` config for `gatk` in your YAML file. I also just pushed a fix so we always run with it enabled while they fix the bug.

**Comment by amizeranschi** [comment]
Alright, thanks a lot for looking into this.

I didn't realize that one could pass tool-specific settings via the `gatk` options, as well. Thanks for pointing that out.

**Comment by roryk** [comment]
No worries, not all of the tools support it, so it is hit or miss if it works or not. Thanks a lot for figuring out what was happening, hopefully the GATK team will fix it soon.

**Comment by amizeranschi** [comment]
@roryk 

Check this out for an update on this issue: https://github.com/broadinstitute/gatk/pull/6675.

Starting from [release 4.1.8.0](https://github.com/broadinstitute/gatk/releases/tag/4.1.8.0) (which came out 2 days ago and is already in bioconda), the VCF codec was made the default and the argument `--genomicsdb-use-vcf-codec` has been replaced by `--genomicsdb-use-bcf-codec`.
