### ISSUE TITLE
remove_lcr: what does this setting do?

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3267]
Hi,

I've just come across a setting that I wasn't familiar with: `remove_lcr`.

It appears here in the documentation: https://bcbio-nextgen.readthedocs.io/en/latest/contents/somatic_variants.html?highlight=remove_lcr#review-parameters-in-the-yaml-file

and nowhere else, as far as I can see.

Sounds like it has something to do with removing low complexity (repetitive) regions from the variant calling analysis. But how exactly does it work? Where are the low complexity regions defined/described?

Is this setting only usable for somatic variant calling? Or for germline variant calling as well?

**Comment by naumenko-sa** [comment]
Hi @amizeranschi !

Yes, it removes low complexity regions from variant calling, both germline and somatic.

The following code: https://github.com/bcbio/bcbio-nextgen/blob/fe239ee2a09adae18bdddc1af615bf02e3df22c4/bcbio/pipeline/shared.py#L143
is looking for a resource in genome resources, for example
`genomes/Hsapiens/hg38/seq/hg38-resources.yaml` : 
```
  lcr: ../coverage/problem_regions/repeats/LCR.bed.gz
```
i.e. the bed file is in 
`genomes/Hsapiens/hg38/coverage/problem_regions/repeats/LCR.bed.gz`

The file is installed by https://github.com/chapmanb/cloudbiolinux/blob/b913e075deb6678eaf27a086d3fcdb58450e1024/ggd-recipes/hg38/coverage.yaml
from here: https://github.com/lh3/varcmp

There is an article explaining the motivation:
https://www.ncbi.nlm.nih.gov/pubmed/24974202

S.

**Comment by amizeranschi** [comment]
Hi @naumenko-sa,

Thanks a lot for the information and the citation, this is really helpful!

**Comment by hackdna** [comment]
Should this be added to the docs?

**Comment by amizeranschi** [comment]
@hackdna IMO this could be helpful.

**Comment by amizeranschi** [comment]
@naumenko-sa 

Do you know of any other potential sources for LCR BED files, for non-human organisms?

I'm interested in bovine and I noticed that UCSC has some datasets for tandem repeats, microsatellites and tandem repeats. Would it make sense to convert these to BED and concatenate them? 

http://hgdownload.soe.ucsc.edu/goldenPath/bosTau6/database/microsat.txt.gz
http://hgdownload.soe.ucsc.edu/goldenPath/bosTau6/database/nestedRepeats.txt.gz
http://hgdownload.soe.ucsc.edu/goldenPath/bosTau6/database/simpleRepeat.txt.gz

**Comment by naumenko-sa** [comment]
We documented remove_lcr: https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#coverage-information
Thanks for facilitating this improvement!

The original Li2014 publication used [mdust](http://nebc.nox.ac.uk/bioinformatics/docs/mdust.html) to generate 2% LCR regions.
I think mdust is agnostic regarding the reference (you may run it on bosTau), but I can't open the page anymore.

I don't have an idea of how to tackle LCRs in bosTau. If you don't have a validation dataset like NA12878 for _H.sapiens_, you can't perform validations similar to Li2014. I'd rather take the annotation approach - to annotate variants with repetitive regions instead of not calling them at all. Then you can filter variants downstream.

**Comment by amizeranschi** [comment]
Alright, thanks for following up on this. Can you recommend any tool or approach for annotating variants with repetitive regions read from a BED file?

**Comment by lbeltrame** [comment]
FTR, `remove_lcr` is an alias of a specific option of `exclude_regions`.

**Comment by naumenko-sa** [comment]
@amizeranschi 
https://github.com/brentp/vcfanno
https://bcbio-nextgen.readthedocs.io/en/latest/contents/germline_variants.html?highlight=vcfanno#variant-annotation

**Comment by amizeranschi** [comment]
@naumenko-sa thanks a lot for mentioning it. 

I guess the easiest thing to do is to set up a BED file with LCRs and subtract this from `variant_regions.bed`. It would be helpful if `bcbio_setup_genome.py` could automatically set up the BED file within the genome resources (and same for a VCF file with known variants for BQSR). I've opened up a separate feature request for this.
