### ISSUE TITLE
How to find bcbio conda shared library information

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3272]
Hi guys,

Apologies for the multiple posts! I am trying to find a way to "lock" bcbio without installing it each time due to subtle changes in package versions. Currently I am crudely copying all the bcbio directories to a new node (identical to the one where I originally installed bcbio). I am getting errors for software that requires shared/dynamic libraries. I noticed there are no environments active for conda either. Clearly I must be missing a file somewhere which contains a manifest of all shared libraries so conda knows where to look, not sure if you're aware of where this information would be?

Thanks!

**Comment by naumenko-sa** [comment]
Hi @waemm !

Not sure, if it is particularly helpful:
-  PATHs, where linux is looking for shared libraries (*.so), are configured in /etc/ls.so.conf.d/
-  conda configs are in `~/.condarc`, `~/.conda/environments.txt`
-  environments are not getting activated, bcbio just uses the proper path for python2, r36 environments: 
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/utils.py#L703

S.

**Comment by waemm** [comment]
@naumenko-sa Thanks for your reply! I have taken a few days to investigate, I am still not sure why the library links don't work but I am now trying to use conda-pack to move the environment, the only issue is the cnvkit package which is not installed directly through conda. I will let you know how I progress with this. Thanks again!
