### ISSUE TITLE
RSEM not being executed

### ISSUE THREAD

**Issue by adammaikai** [bcbio/bcbio-nextgen#3276]
**Version info**
1.2.3
Ubuntu 16.04.6

**To Reproduce**
details:
- algorithm:
    aligner: star
    expression_caller: [rsem]
  analysis: RNA-seq
  description: H3-1
  files:
  - /scratch/rnaseq/H3-1_R1_001.fastq.gz
  - /scratch/rnaseq/H3-1_R2_001.fastq.gz
  genome_build: hg38
fc_name: metadata
upload:
  dir: ../final

**Observed behavior**
rsem is skipped and does not run. I still get quants from htseq-count, however. I was able to install rsem in my bcbio tools folder but actually do not see documentation anywhere about how to execute it so I am wondering if it is even possible. I executed again with expression_caller: [rsem, kallisto] and get kallisto results as well.

[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4828133/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/4828134/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4828135/bcbio-nextgen.log)

**Comment by naumenko-sa** [comment]
Hi @adammaikai !

I think there were some efforts to support rsem in bcbio 5-6 years ago:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/rnaseq/rsem.py

But as you mentioned it is not even getting installed: 
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml

I think it was abandoned in favor of salmon/kallisto, see this comparison, for example:
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1526-y

SN

**Comment by adammaikai** [comment]
Thanks so much for your quick response. If at all possible I would like to submit a feature request for RSEM support. We are interested for the purpose of reproducing work from other projects.

**Comment by naumenko-sa** [comment]
Unfortunately, RSEM goes not very high on the priorities list. 
Would you consider contributing code to the enhanced support of RSEM in bcbio?
We welcome PRs.

S.

**Comment by naumenko-sa** [comment]
Please feel free to re-open if somebody wants and has time to implement rsem support.
