### ISSUE TITLE
Tests fail with current bcbio-rnaseq docker image

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3280]
**Version info**
 - bcbio version: quay.io/bcbio/bcbio-rnaseq:1.2.3-2d6a5bb

**To Reproduce**
```
git clone https://github.com/bcbio/bcbio-nextgen.git
./run-tests.sh rnaseq
```

**Observed behavior**
```
================================================== short test summary info ==================================================
FAILED integration/test_automated_analysis.py::test_2_stranded - subprocess.CalledProcessError: Command '['bcbio_nextgen.p...
FAILED integration/test_automated_analysis.py::test_2_star - subprocess.CalledProcessError: Command '['bcbio_nextgen.py', ...
FAILED integration/test_automated_analysis.py::test_2_fastrnaseq - subprocess.CalledProcessError: Command '['bcbio_nextgen...
FAILED integration/test_automated_analysis.py::test_2_scrnaseq - subprocess.CalledProcessError: Command '['bcbio_nextgen.p...
FAILED integration/test_automated_analysis.py::test_2_hisat2 - subprocess.CalledProcessError: Command '['bcbio_nextgen.py'...
FAILED integration/test_automated_analysis.py::test_explant - subprocess.CalledProcessError: Command '['bcbio_nextgen.py',...
================================== 6 failed, 1 skipped, 76 deselected, 1 warning in 56.7
```

**Expected behavior**
Tests passing.

I tried to find any `bcbio-rnaseq` docker image where tests pass, but was not successful so far. Are these tests supposed to work on the docker images?
No better luck with `bcbio-vc` docker images either. Tests fail. 
What is the recommended way to check that a specific setup is working?
In my particular instance I am trying to run an RNA-seq analysis which fails. I was looking for a way to pinpoint the issue.

**Comment by hackdna** [comment]
The same tests are also failing when not using containers due to `AttributeError: 'FastqPhredIterator' object has no attribute 'close'` (see #3277 for more details).

**Comment by hackdna** [comment]
The only tests that can actually work using containers are labeled `docker` and they require a [bcbio-nextgen-vm installation](https://github.com/bcbio/bcbio-nextgen-vm#installation). Tests labeled `rnaseq` require a [tools-only bcbio installation](https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#install-bcbio-package-and-tools) to run.

The way to check if a specific setup is working is to run:
* `bcbio_nextgen.py --version` (the most basic test)
* `cd tests; ./run_tests.sh` (unit tests and some integration tests that can be run relatively quickly)

I hope this helps. If you need assistance with a specific RNA-seq analysis issue please open a separate bug report.

**Comment by gabeng** [comment]
Thanks for the explanation. Will be following up with this in separate tickets.
