### ISSUE TITLE
Star cannot open genome file genomeParameters.txt

### ISSUE THREAD

**Issue by drlaurenwasson** [bcbio/bcbio-nextgen#3281]
Hello,

I am trying to use bcbio-nextgen to align to mm10 using STAR and I get this error:

 Aligning lane C57_adult_heart with star aligner
[2020-06-27T11:50Z] Running 1st pass of STAR aligner on /proj/conlonlb/users/wasson/C57-female-1-resub-2_001_R1.fastq.gz and /proj/conlonlb/bcbio/genomes/Mmusculus/mm10/star/
[2020-06-27T11:50Z] EXITING because of FATAL ERROR: could not open genome file /proj/conlonlb/bcbio/genomes/Mmusculus/mm10/star//genomeParameters.txt
[2020-06-27T11:50Z] SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
[2020-06-27T11:50Z] Jun 27 07:50:20 ...... FATAL ERROR, exiting

when I head over to /proj/conlonlb/bcbio/genomes/Mmusculus/mm10/star I have the following files in there:

- chrLength.txt
- chrNameLength.txt
- chrName.txt
- chrStart.txt
- Log.out
- _STARtmp

Therefore I concluded that something must have happened in the upgrade to STAR. 
So I tried to upgrade
bcbio_nextgen.py upgrade -u skip --genomes mm10 --aligners star

and it tells me it's complete
outfile:
Upgrading bcbio-nextgen data files
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'mm10', 'name': 'Mouse (mm10)', 'indexes': ['seq', 'twobit'], 'annotations': ['problem_regions', 'dbsnp', 'vcfanno', 'transcripts', 'rmsk', 'mirbase']}], 'genome_indexes': ['star', 'rtg', 'bwa', 'hisat2'], 'install_liftover': False, 'install_uniref': False}'): Mouse (mm10)
Preparing STAR index from /proj/conlonlb/bcbio/genomes/Mmusculus/mm10/seq/mm10.fa.
bcbio-nextgen data upgrade complete.

How do I get this file?
Thanks
Lauren

**Comment by roryk** [comment]
I think when you installed the STAR genome for mm10, the first time it failed, the STAR directory looks incomplete. If you remove `/proj/conlonlb/bcbio/genomes/Mmusculus/mm10/star` and redo `bcbio_nextgen.py upgrade -u skip --genomes mm10 --aligners star` it will regenerate it. You'll need 40G or so for the job for it to not fail though.

**Comment by drlaurenwasson** [comment]
Thank you Rory. Removing the directory and starting over worked like a charm.
