### ISSUE TITLE
changing GATK path 

### ISSUE THREAD

**Issue by ashwathkumar-arcus** [bcbio/bcbio-nextgen#3283]
Hi, 

I wanted to ask if it is possible to tell bcbio to use a different gatk that the default one installed with it. I would like to temporarily use a different GATK4 version. I have tried using the following lines in my input YAML file
resources:
  gatk: 
      cmd: NEW PATH

but this doesnt seem to change the way bcbio runs Mutect2. Any help is appreciated. 

Thanks !

Edit: I would like to add that I do not want to update bcbio itself with the new path but rather use the NEW PATH for just one of the runs.

**Comment by naumenko-sa** [comment]
Hi!

Unforturtunately you cannot change GATK version in the resources.
Gatk4 is a conda package:

```
conda list | grep gatk
gatk4                     4.1.7.0                  py38_0    bioconda
```

I think the way to solve this is to downgrade gatk4, do your run, and upgrade it back when you are done, it is easy:

```bash
conda install -c conda-forge -c bioconda gatk4=4.1.6.0
```

Sergey

**Comment by ashwathkumar-arcus** [comment]
@naumenko-sa thank you for the suggestion.
