### ISSUE TITLE
RFE: genotype germline sites with Mutect2 to be used with PureCN

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3288]
The current solution for PureCN uses VarDict, which does mark sites as somatic or likely germline, followed by a series of filtering (which, honestly, I did not understand completely) to produce a file which can be digested by PureCN.

We can allow MuTect 2 to genotype germline sites: this normally means just an increase in runtime with little benefit, but doing for specific cases might be useful. In particular, PureCN could then be used with MuTect2, which would allow to leverage PureCN's native handling of MuTect2 VCFs.

Not sure if it's worth it or not, but I'm throwing ideas into the mix.

**Comment by naumenko-sa** [comment]
This is done as of bcbio 1.2.7:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/mutect2.py#L99
