### ISSUE TITLE
Installing custom genome failure with gff3

### ISSUE THREAD

**Issue by drlaurenwasson** [bcbio/bcbio-nextgen#3289]
Hello,
I am trying to build a custom genome for XenTro10 and I believe I get pretty far in the process, it ran for a few hours and then failed. I see where it failed (I bolded it) but I have no idea what that means and how to fix it. (I am using the newest version of bcbio)

I found my fasta file and gttf3 files using Xenbase (http://ftp.xenbase.org/pub/Genomics/JGI/Xentr10.0/)

Here is my run script
#!/bin/bash
#SBATCH -p general
#SBATCH --job-name=xtrop10_build
#SBATCH -c 10
#SBATCH -t 24:00:00
#SBATCH --mem=100G
#SBATCH -e xtrop10_build.err

export PATH=/proj/conlonlb/bcbio/anaconda/bin:/proj/conlonlb/bcbio/tools/bin:$PATH

bcbio_setup_genome.py \
-f /proj/conlonlb/XENTR_10.0_genome.fasta.gz \
-g /proj/conlonlb/XENTR_10.0_GCF.gff3 \
-i bwa star seq \
-n XenTro -b XenBase10_0 --buildversion XenBase10

Here is my .err file
--2020-07-01 11:21:56--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2020-07-01 11:21:56--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 140.82.112.10
Connecting to codeload.github.com (codeload.github.com)|140.82.112.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 3.14M
  3072K ........ ........ ........ .......                    2.24M=1.8s

2020-07-01 11:21:58 (2.71 MB/s) - written to stdout [5189916]

[bwa_index] Pack FASTA... 9.70 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=2902567198, availableWord=216235256
[BWTIncConstructFromPacked] 10 iterations done. 99999998 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 199999998 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 299999998 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 399999998 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 499999998 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 599999998 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 699999998 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 799999998 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 899999998 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 999999998 characters processed.
[BWTIncConstructFromPacked] 110 iterations done. 1099999998 characters processed.
[BWTIncConstructFromPacked] 120 iterations done. 1199999998 characters processed.
[BWTIncConstructFromPacked] 130 iterations done. 1299999998 characters processed.
[BWTIncConstructFromPacked] 140 iterations done. 1399999998 characters processed.
[BWTIncConstructFromPacked] 150 iterations done. 1499999998 characters processed.
[BWTIncConstructFromPacked] 160 iterations done. 1599999998 characters processed.
[BWTIncConstructFromPacked] 170 iterations done. 1699999998 characters processed.
[BWTIncConstructFromPacked] 180 iterations done. 1799999998 characters processed.
[BWTIncConstructFromPacked] 190 iterations done. 1899999998 characters processed.
[BWTIncConstructFromPacked] 200 iterations done. 1999999998 characters processed.
[BWTIncConstructFromPacked] 210 iterations done. 2099999998 characters processed.
[BWTIncConstructFromPacked] 220 iterations done. 2199999998 characters processed.
[BWTIncConstructFromPacked] 230 iterations done. 2296888974 characters processed.
[BWTIncConstructFromPacked] 240 iterations done. 2383356302 characters processed.
[BWTIncConstructFromPacked] 250 iterations done. 2460204670 characters processed.
[BWTIncConstructFromPacked] 270 iterations done. 2589204030 characters processed.
[BWTIncConstructFromPacked] 280 iterations done. 2643150622 characters processed.
[BWTIncConstructFromPacked] 290 iterations done. 2691094462 characters processed.
[BWTIncConstructFromPacked] 300 iterations done. 2733703054 characters processed.
[BWTIncConstructFromPacked] 310 iterations done. 2771569662 characters processed.
[BWTIncConstructFromPacked] 320 iterations done. 2805221582 characters processed.
[BWTIncConstructFromPacked] 330 iterations done. 2835127438 characters processed.
[BWTIncConstructFromPacked] 340 iterations done. 2861703838 characters processed.
[BWTIncConstructFromPacked] 350 iterations done. 2885320958 characters processed.
[bwt_gen] Finished constructing BWT in 359 iterations.
[bwa_index] 985.42 seconds elapse.
[bwa_index] Update BWT... 8.26 sec
[bwa_index] Pack forward-only FASTA... 5.92 sec
[bwa_index] Construct SA from BWT and Occ... 422.89 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index -a bwtsw XenBase10_0.fa
[main] Real time: 1441.218 sec; CPU: 1432.215 sec
INFO    2020-07-01 12:45:30     CreateSequenceDictionary

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CreateSequenceDictionary -REFERENCE /proj/conlonlb/bcbio/genomes/XenTro/XenBase10_0/seq/XenBase10_0.fa -OUTPUT /proj/conlonlb/bcbio/genomes/XenTro/XenBase10_0/seq/XenBase10_0.dict
**********

12:45:32.050 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/proj/conlonlb/bcbio/anaconda/share/picard-2.23.0-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jul 01 12:45:32 EDT 2020] CreateSequenceDictionary OUTPUT=/proj/conlonlb/bcbio/genomes/XenTro/XenBase10_0/seq/XenBase10_0.dict REFERENCE=/proj/conlonlb/bcbio/genomes/XenTro/XenBase10_0/seq/XenBase10_0.fa    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jul 01 12:45:32 EDT 2020] Executing as lwasson@c0310.ll.unc.edu on Linux 3.10.0-1062.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_192-b01; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.0
[Wed Jul 01 12:45:38 EDT 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.11 minutes.
Runtime.totalMemory()=1592262656
Building a SMALL index
Traceback (most recent call last):
  File "/proj/conlonlb/cloudbiolinux/utils/prepare_tx_gff.py", line 846, in <module>
    main(args.org_build, args.gtf, args.fasta, genome_dir, args.cores, args)
  File "/proj/conlonlb/cloudbiolinux/utils/prepare_tx_gff.py", line 296, in main
    gtf_file = clean_gtf(gtf_file, genome_fasta)
  File "/proj/conlonlb/cloudbiolinux/utils/prepare_tx_gff.py", line 362, in clean_gtf
    if line.split()[0].strip() not in fa_names:
**IndexError: list index out of range**
Traceback (most recent call last):
  File "/proj/conlonlb/bcbio/anaconda/bin/bcbio_setup_genome.py", line 313, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/proj/conlonlb/bcbio/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/proj/conlonlb/bcbio/anaconda/bin/python3.6 /proj/conlonlb/cloudbiolinux/utils/prepare_tx_gff.py --buildversion XenBase10 --cores 1 --genome-dir /proj/conlonlb/bcbio/genomes --gtf /proj/conlonlb/bcbio/genomes/XenTro/XenBase10_0/rnaseq/ref-transcripts.gtf XenTro XenBase10_0' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
Hello @drlaurenwasson!

Thanks for the detailed report.
I think it is because the input annotation is `gff3` rather than `gtf`.

For gff3 there is a flag in `bcbio_setup_genome.py`:
```
bcbio_setup_genome.py \
-c 15 \
-f XENTR_10.0_genome.fasta.gz \
--gff3 \
-g XENTR_10.0_GCF.gff3 \
-i bwa star seq \
-n XenTro -b XenBase10_0 --buildversion XenBase10
```

Unfortunately, this fails with a bug. 
I managed to convert with `gffread XENTR_10.0_GCF.gff3 -T -o XENTR_10.0_GCF.gtf` (gffread is installed with bcbio).

Could you try this conversion and then:
```
bcbio_setup_genome.py \
-c 15 \
-f XENTR_10.0_genome.fasta.gz \
-g XENTR_10.0_GCF.gtf \
-i bwa star seq \
-n XenTro -b XenBase10_0 --buildversion XenBase10
```

Sergey

**Comment by drlaurenwasson** [comment]
Hi Sergey,
This installation also finished successfully for me! Thank you so much
