### ISSUE TITLE
Upload results to FTP

### ISSUE THREAD

**Issue by fgvieira** [bcbio/bcbio-nextgen#3296]
Dear all,

according to `bcbio` documentation, it is possible to upload the final results to a local directory, Dropbox, Galaxy, Amazon S3 or iRODS. Is it possible to upload to an FTP server?

thanks,

**Comment by hackdna** [comment]
Unfortunately, there is no support for FTP uploads.

**Comment by fgvieira** [comment]
Well, then I'll just leave it here as a suggestion.. :)

**Comment by hackdna** [comment]
Could you describe your use case?

**Comment by amizeranschi** [comment]
@hackdna I think @fgvieira's use case is something like "it would be nice if bcbio's final results could be uploaded to a FTP server". 

Apologies, I couldn't help myself. :)

**Comment by hackdna** [comment]
I guess I could have been more specific :) I am curious as to why FTP is necessary given how old and insecure this protocol is, and if there may be an alternative solution.

**Comment by fgvieira** [comment]
I was just thinking in a case where you'd run the pipeline in an HPC and automatically upload the results to a local machine for downstream analyses. As I see it, currently available platforms have some limitations:
- Dropbox: not suitable for large datasets (most people have small accounts and, in case of downstream analyses, it needs a later download to local computer/HPC)
- Galaxy: only makes sense if you are planning to use Galaxy
- Amazon S3 and iRODS: very specific platforms that most people do not have

I think that it would be nice to support a more simple, general, and widespread platform, may it be FTP, rsync, Samba, etc...
That said, I do not have a strong opinion about it being FTP, as long as it is easier to use and widely available.

**Comment by roryk** [comment]
Heya @fgvieira,

Thanks! This would be nice to have, but is probably something we won't implement-- it seems like a pretty niche use case and it can get handled by a simple script on the remote machine that tars up the final directory and passes it on. I think this would be more trouble than its worth to implement and maintain at the moment, but if there is more clamor for this feature it can get added to the list. Thank you!
