### ISSUE TITLE
Feature request: enable bcbio_setup_genome.py to add a BED file with known LCRs and a VCF file with known variants for BQSR

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3299]
As the title mentions, it would help if `bcbio_setup_genome.py` could be expanded to automatically set up two things:

- a BED file with LCR regions (see: https://github.com/bcbio/bcbio-nextgen/issues/3267#issuecomment-645718600)
- a VCF file with known variants, for GATK's BQSR function -- although some people say BQSR might not add much benefit, it is still recommended by GATK's best practices workflows and some projects require it for data submission, for example: http://www.1000bullgenomes.com/.

**Comment by roryk** [comment]
Thanks, GATK is dropping BQSR from its best practices soon, so this won't be necessary. Sorry for missing this request and not responding in a timely fashion.
