### ISSUE TITLE
Use of samtools sort after alignment (somatic variant pipeline) followed by bamcat with second sorting step

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3305]
Hi Guys,

I was looking at the somatic variant pipeline commands, it looks like for each FASTQ chunk, you align using bwa then sort each chunk with samtools. Then after alignment is done you bamcat all the pieces and use bamsormadup. Am I missing something here or is the first sort unnecessary? Just curious as I'm not sure if there is a specific reason for this?

**Comment by roryk** [comment]
Thanks for the thought-- we have a generic aligner function that sorts at the end that isn't aware if something is a chunk in a larger alignment or the whole alignment, so it always sorts the output. It's definitely not the fastest thing we could be doing in all cases.
