### ISSUE TITLE
ChipSeq analysis 

### ISSUE THREAD

**Issue by MurliNair** [bcbio/bcbio-nextgen#3309]
Hi,
I am trying to use bcbio to analyze chipSeq data.  I am following the example given here 
https://bcbio-nextgen.readthedocs.io/en/latest/contents/atac.html

I tried using the following template 
---
details:
- analysis: chip-seq
  genome_build: hg38
  algorithm:
    aligner: bwa
    peakcaller: [macs2]
    chip_method: atac
    keep_duplicates: False
    keep_multimapped: False
upload:
  dir: ../final
==========================
I am getting the following errors
ValueError: Unexpected configuration keyword in 'algorithm' section: ['keep_multimapped', 'keep_duplicates']

Is there a specific argument for chip_method that I need to assign if it is chipseq data and not atac seq data? 

Thanks ../Murli

**Comment by naumenko-sa** [comment]
HI @MurliNair !

Please try this example:
https://github.com/bcbio/bcbio-nextgen/issues/2626

(chip_method: chip + phenotype: input/chip).

Sergey

**Comment by MurliNair** [comment]
Thanks for you help. I shall study it.

**Comment by naumenko-sa** [comment]
feel free to re-open if you see further issues. 
S
