### ISSUE TITLE
Issue with alignment for UMI-tagged DNA-seq

### ISSUE THREAD

**Issue by IvantheDugtrio** [bcbio/bcbio-nextgen#3315]
**Version info**
- bcbio-nextgen 1.2.3:
- CentOS 8

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen ../config/QIAseq-071020B.yaml
```
Your sample configuration file:
[QIAseq-071020B.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/4969880/QIAseq-071020B.yaml.txt)

**Observed behavior**
Error message or bcbio output:
```
Traceback (most recent call last):
  File "/staging/gtcmolecular/local/share/bcbio/galaxy/../anaconda/bin/umis", line 11, in <module>
    load_entry_point('umis==1.0.6', 'console_scripts', 'umis')()
  File "/staging/gtcmolecular/local/share/bcbio/anaconda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/staging/gtcmolecular/local/share/bcbio/anaconda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/staging/gtcmolecular/local/share/bcbio/anaconda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/staging/gtcmolecular/local/share/bcbio/anaconda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/staging/gtcmolecular/local/share/bcbio/anaconda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/staging/gtcmolecular/local/share/bcbio/anaconda/lib/python3.6/site-packages/umis/umis.py", line 1244, in bamtag
    aln.tags += [('RX', match.group('MB'))]
AttributeError: 'NoneType' object has no attribute 'group'
' returned non-zero exit status 1.
```

**Expected behavior**
This is my first time running this set of FASTQ files, so I am not sure if there are formatting issues, however I have eliminated FASTQs with fewer than 1000 reads. 

**Log files**
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4969872/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/4969873/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4969874/bcbio-nextgen.log)

**Additional context**
The UMI tags were manually prepared as I used bcl2fastq's UMI trim functionality, followed by a sed expression to add "UMI_" to the beginning of every UMI sequence. Below is example of one of the headers from one of my samples. For reference, these are QIAseq libraries with one random 12-mer at the start of read 2 as the UMI. 
```
@NB551615:187:HWHW5BGXF:1:12205:19216:2634:UMI_GTTGGATCAAGC 1:N:0:CTCTCTAT+ATTAGACG
```
I hope that eventually I won't need to add "UMI_" to use bcbio's UMI functions. It is rather time consuming and breaks compatibility with Illumina's UMI tools.

**Comment by naumenko-sa** [comment]
Hi @IvantheDugtrio !

UMIs are useful to pick up low-frequency variants. We use umis and fgbio to process them:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/internals.html?highlight=fgbio#somatic-tumor-only-variant-calling-pipeline-with-umis-step-by-step

Could you please share a 10k subset of your fastq files?

Sergey

**Comment by IvantheDugtrio** [comment]
Hi @naumenko-sa ,

In another thread, I discovered that the FASTQs that I was processing had inconsistent UMI sequences, where some of the UMI sequences were missing the "UMI_" tag, due to wildcard bases present. Fixing this appears to have resolved my problem.

Thanks,
Ivan
