### ISSUE TITLE
bcbio v1.2.3 installation missing mos depth

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3317]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): RHEL 2.6.32-279.el6.x86_64

**To Reproduce**
Exact bcbio command you have used: Same installation commands as provided in https://bcbio-nextgen.readthedocs.io/en/latest/contents/intro.html
```
wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py [bcbio_installation_path] --tooldir=[tools_installation_path] --nodata

```
Your sample configuration file:
```
N/A (Installation issue)
```

**Observed behavior**
Error message or bcbio output:
```
The installation completed with no errors, but when running bcbio, it complained that mosdepth is not found. I manually checked <bcbio path>/anaconda/bin/ and confirmed that it is not there. 

My workaround was to take a previously installed mosdepth and copied it into the bin directory.
```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**

**Comment by naumenko-sa** [comment]
Hello @gis-nlsim !

Thanks for reporting!

mosdepth is in `tools/bin`, i.e. `/n/app/bcbio/tools/bin/mosdepth` on my system.
Please make sure that `tools/bin` is also included in the PATH

https://bcbio-nextgen.readthedocs.io/en/latest/contents/intro.html#run-the-analysis-distributed-on-8-local-cores-with

Sergey

**Comment by roryk** [comment]
Thanks, we had to move `mosdepth` to it's own environment because it depends on `htslib1.10` but most of bioconda does not, which is why this vanished from the base path. Sergey's fix is the way to resolve it.
