### ISSUE TITLE
New tools for CNV calling and low-frequency somatic calling

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#3322]
I’m Pär Larsson from Umeå, Sweden. We’re currently using bcbio-nextgen in some of our clinical workflows and are very happy with it, but would like to expand its capabilities by adding a couple of extra tools. Those we’re thinking of are CNVpytor (~CNVnator), ExpansionHunter and possibly a low-frequency somatic caller such as LoFreq.

Would these tools also be of interest for you to integrate also in upcoming bcbio-nextgen releases?  

I’m now trying to understand the bcbio codebase but unfortunately Everything is not completely obvious to me. I hope I can return with stupid questions.

**Comment by roryk** [comment]
Hi Pär,

Yes, we love to work with folks to improve the capabilities of bcbio. Usually what we will do is run tools outside of bcbio on validation data to prove to ourselves that the tools actually run and give solid results. https://github.com/bcbio/bcbio_validations/tree/master/huref_sv has a description of our current validation.

@naumenko-sa has done a bunch of work looking at CNVs, and also suggested CNVnator, but I'm not sure if he has changes hid mind or not: https://github.com/bcbio/bcbio-nextgen/issues/2313

**Comment by parlar** [comment]
Super! A colleague (Daniel Nilsson, Scilifelab/Clinical Genetics at Karolinska) has evaluated them quite extensively but we can run a comparison.

**Comment by pfpjs** [comment]
ExpansionHunter would be great!

**Comment by naumenko-sa** [comment]
Hi Pär @parlar  !

Right now I'm pushing pureCN/gatkCNV use case to make T-only CNV detection possible in bcbio.

You are very welcome to contribute to improving CNV calling in bcbio! Could you publish validations of CNVPytor?
Is it for tumor/normal, tumor-only case? Exomes or panels? How does the workflow compare with cnvkit, purecn, gatkcnv?

Many users need repeat expansion detection - please contribute to the validation and implementation! 
I think for this user story the other tools to compare are Lobstr and STRetch.
- https://github.com/Illumina/ExpansionHunter
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3371701/
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6102892/

Sergey

**Comment by roryk** [comment]
Hi Pär!

Happy to help with the implementation and some tips on where to start for adding things to bcbio. The code base is complicated since its both a transactional, memoized workflow engine and the actual run-things-code but to add a new tool you only need to touch a small piece of the codebase. If you fork bcbio and open up a p/r with whatever work you are doing we can comment and help out. Happy to do a video call as well.

It is helpful to run a tool first via the shell, and collect the command lines that you need to run it. That will give you an idea of what you need to find to run it, if you do that we can show you how to look up all of the things you need to run it. If you do lofreq, you could open up the p/r with just a python function that runs it and we can show you how to use the bcbio idioms to hook it into the workflow engine. Thanks so much for helping out, we're happy to give you whatever support you need.

**Comment by parlar** [comment]
Thanks! I'll start by doing a fork.

**Comment by parlar** [comment]
I'm working on this albeit with a lot of interruptions. 

A quick question: Unfortunately, lofreq does not produce valid vcfs. Chromosomes/cotigs are missing in the header. This can be fixed easily using ```gatk UpdateVCFSequenceDictionary```. However, it appears that this command cannot be piped, meaning that I will need to save an intermediary vcf file. 

Are you aware of anyway of fixing the vcfs without resorting to UpdateVCFSequenceDictionary, perhaps using some function in bcbio or other tool? Otherwise, can you point to a good example of how use temp files in bcbio?  

Have a nice weekend!

**Comment by roryk** [comment]
Hi Pär,

Yup, just using `NamedTemporaryFile` from the `tempfile` library will work, here is an example used in the ChIP-seq pipeline: 

https://github.com/bcbio/bcbio-nextgen/blob/b0b262fca7c17bd3f2e34f89e035cccfea12debb/bcbio/chipseq/peaks.py#L186-L189

I don't know of another way of fixing the VCFs, what you're doing sounds like the way I would do it!

**Comment by roryk** [comment]
The `lofreq` folks are pretty active on their github, it also might be worth following up with them, maybe it is something they could add or fix on their end at some point so we don't have to resort to fixing it up ourselves.

**Comment by naumenko-sa** [comment]
closing for now. please re-open if somebody starts working on lofreq or repeat expansions.

Please note that PureCN support is implemented: https://bcbio-nextgen.readthedocs.io/en/latest/contents/purecn.html
