### ISSUE TITLE
SV calling error

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#3325]
Hi,

I've been hitting errors in germline SV calling runs with lumpy and manta. I've run three separate jobs:
- Job 1 started from BAMs produced by a previous small variant run, and finished without any issues.
- Job 2 also started from BAMs produced by a previous small variant run and has crashed repeatedly.
- Job 3 started from FASTQs and crashed with what appears to be the same error as job 2.

Attached logs are from job 3 (bcbio-nextgen-debug.log is 82MB, so not attached). 

As far as I can tell from the log, the following line looks to be the root cause of the crash:
`[2020-08-12T01:25:59.710464Z] [rn249.localdomain] [113774_1] [WorkflowRunner] [ERROR] [2020-08-12T01:25:53.051360Z] [rn249.localdomain] [113774_1] [generateCandidateSV_0000] FATAL_ERROR: Failed to open SAM/BAM/CRAM file for reading: '/scratch/bennetm/bcbio-cataract-sv/cataract-sv-all/work/align/CSA168_01/CSA168_01-sort.bam'`

I've checked the file, and it's there and appears to be a perfectly cromulent BAM file (at least `samtools view` reads it without error).

Please let me know if there are any other files that would be of use in tracking down the cause of this.

Regards,
Bennet

[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5072338/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/5072339/bcbio-nextgen-commands.log)

**Comment by naumenko-sa** [comment]
Hi Bennet @DrMcStrange !

I've found a similar issue in the manta github: https://github.com/Illumina/manta/issues/220.
My suggestion would be to run fewer samples in bcbio run - anyway, there is no batch SV calling.

Sergey

**Comment by DrMcStrange** [comment]
Thanks Sergey, that would explain why job 1 ran successfully! I'll try breaking them up into smaller jobs.

**Comment by amizeranschi** [comment]
Hi @naumenko-sa 

> anyway, there is no batch SV calling.

See my older related issue here: https://github.com/bcbio/bcbio-nextgen/issues/3268

**Comment by DrMcStrange** [comment]
Just to confirm, splitting my run into batches of 10 or fewer samples worked.
