### ISSUE TITLE
unable to inject bcbio code 

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#3330]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): CentOS Linux release 7.8.2003 (Core)

**To Reproduce**
Exact bcbio command you have used:

I have a freshly cloned bcbio code folder from github and made a new bcbio installation using 

```python bcbio_nextgen_install.py ${HOME}/local/share/bcbio --tooldir=${HOME}/local --nodata```

Its not isolated but there are no conflicting bcbio installations for the user.

After injecting code from the code folder (with no changes made) into the bcbio installation, the installation does not work any longer.   

I have first removed the bcbio site-packages as follows (as per the documentation): 
```rm -rf /path/to/anaconda/lib/python3.6/site-packages/bcbio*```

and then run the installation script using bcbio_python as follows:
```bcbio_python setup.py install```

**Observed behavior**
Error message or bcbio output:

The bcbio code gets injected into the correct bcbio installation, but when I try using it,
I get this error message:

```
[bcbio-dev@vs478 work]$ bcbio_nextgen.py -t local -n 20 ../config/calling.yaml
Traceback (most recent call last):
  File "/home/bcbio-dev/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.2.3', 'bcbio_nextgen.py')
  File "/home/bcbio-dev/local/share/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bcbio-dev/local/share/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/bcbio_nextgen.py' not found in metadata at '/home/bcbio-dev/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.2.3-py3.8.egg-info'
```

**Expected behavior**

Functional bcbio pipeline.

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

No log files produced, it exits immediately. 

**Additional context**

**Comment by roryk** [comment]
Hi Pär,

Sorry about that, you'll need to nuke `bcbio*` in the `site-packages` directory in your install, I think it should be here: `/home/bcbio-dev/local/share/bcbio/anaconda/lib/python3.6/site-packages/`. This is some issue with python eggs not getting removed correctly, if you nuke that and then run `bcbio_python setup.py install` it should let you install your patched version.

**Comment by parlar** [comment]
You're absolutely right! I thought i nuked ```bcbio*``` but I actually didn't. I used a script for the nuke and install commands but later changed location of the bcbio installation so the nuke command pointed to an incorrect path. 

Sorry about bothering you with this.

**Comment by roryk** [comment]
Hi Pär,

No worries! It bites me every time I do it too, sorry that we haven't figured out how to make it not happen.
