### ISSUE TITLE
mtDNA 

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#3331]
Hi,

We have some mtDNA spiked into our exome samples. I have appended the IDT bed file with the mtDNA probes. Now that I am running bcbio its failing with the following error

A USER ERROR has occurred (version 2015.1.1-3.4.46-0-ga8e1d99):
##### ERROR MESSAGE: File associated with name /mnt/speed/qc/sequencing/mtDNA_Validation/GML3914_FD071620_Fam1063_bcbio/bedprep/xgen_exome_mtDNA_research-panel-targets_6bpexpanded.bed is malformed: Problem reading the interval file caused by Badly formed genome loc: Contig M given as location, but this contig isn't present in the Fasta sequence dictionary

do the GRCh37 fa fle that we download during installation does not come with chr M? If so can i get it from ucsc genome browser and rebuild the bwa index for this?

**Comment by roryk** [comment]
Hi @DiyaVaka,

The chromosome is called MT in the GRCh37 file, so if you swap it to that it should work.
