### ISSUE TITLE
viability of migrating existing bcbio on Lustre to local FS for cloud processing

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#3336]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
1.1.6a
- OS name and version (`lsb_release -ds`):
CentOS Linux release 7.6.1810 (Core)

**Additional context**
Want to migrate to version: 1.1.9a

Currently using a Lustre file system with libraries in the global namespace and SLURM headnode.

Two approaches come to mind
1. fresh new re-install on existing Lustre namespace
2. approach where cloud workers effectively run bcbio local (new local install on new global AMI) with outputs to Lustre namespace.  Each EC2 worker would only run one job at a time in this model.  In this model all calls for processing use the same AMI.  Strictly one bcbio job per instance in this model as well.

#1 is straightforward
#2 may have a very large amount of dependencies post-install in terms of hardcoded links, symlinks etc.

Wanted to get the community opinion prior to embarking on a path.  Greatly appreciate all help and suggestions anyone may be able to provide.  Thanks!  R/Mike

**Comment by naumenko-sa** [comment]
Hi Mike!

Why don't you upgrade to the latest bcbio (1.2.3)?

I think this discussion could be useful for people who are doing production bcbio deployment. 
Could you please outline your setup a bit more?

On one hand, you mentioned SLURM, head node, and Lustre, which are attributes of a hardware HPC, 
on the other hand - you are talking about AMIs, i.e. cloud instances. Have you configured your cluster in the cloud?

I know that a more or less standard approach in a cloud is when people create an AMI instance with bcbio installed (bcbio package + tools, i.e. --nodata), and then they launch their analyses by cloning that instance and mounting a folder with bcbio data. That folder even could be re-used between bcbio upgrades (you create another template instance with --nodata).

Sergey

**Comment by naumenko-sa** [comment]
Closing for now. Feel free to re-open if there are installation issues.
