### ISSUE TITLE
how to turn off the contamination check using gdc-viral?

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#3340]
We have the implementation for the contamination check outside of bcbio and thus don't need this step within bcbio.  Could you kindly let me know how to turn off this option in the yaml file?

Thanks,
Segun

**Comment by roryk** [comment]
Hi Segun,

There wasn't a way to do this, I just added it for you all. If you add `tools_off: [viral]` to your configuration it should skip the viral check.

**Comment by dauss75** [comment]
Thank you Rory. To make that work, I guess you updated some lines in the bcbio wrapper. Could you let me know which scripts has to be updated? I want to avoid the bcbio update only for this.

**Comment by dauss75** [comment]
oh.. never mind. found it. thank you a ton!

**Comment by roryk** [comment]
Awesome, thanks for the suggestion!
