### ISSUE TITLE
Using Hg38 with Gemini in Bcbio

### ISSUE THREAD

**Issue by VictoriaPatten** [bcbio/bcbio-nextgen#3342]
In the config files for bcbio I specified `tools_on: gemini` and also `vcfanno: [gemini, somatic]` 
However, when reading the Gemini documentation now, the documentation says "_GEMINI solely supports human genetic variation mapped to build 37 (aka hg19) of the human genome_"
How can the pipeline run successfully without reporting an error about the use of GEMINI and Hg38?
Any advice on what to do or how to get around this as I now need to do downstream analysis of the results?

**Comment by roryk** [comment]
Hi Victoria,

Good question. Did the run not produce the database? We use `vcf2db.py` to load the GEMINI database, which is compatible with arbitrary genomes. The idea is you annotate the variants with `vcfanno` and then load them with `vcf2db.py` and then you can do normal GEMINI queries on them.

**Comment by VictoriaPatten** [comment]
@roryk Thanks for clarifying that... I am **_very_** new to bioinformatics and am using bcbio and GEMINI for the first time. I will have a look at the output files again and get back to you if I have more questions/trouble. 
Thanks so much. 
Kind regards, 
Victoria

**Comment by roryk** [comment]
Hi Victoria,

Great! Helping new folks get moving with best practice pipelines is one of our major goals, so welcome aboard!
