### ISSUE TITLE
No bcbioRNASeq directory in the output

### ISSUE THREAD

**Issue by xgong-tb** [bcbio/bcbio-nextgen#3343]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): Ubuntu 18.04.5 LTS

**To Reproduce**
Exact bcbio command you have used: 
bcbio_nextgen.py ../config/seqc.yaml -n 20
```

```
Your sample configuration file:
details:
- algorithm:
    aligner: star
    quality_format: Standard
    strandedness: unstranded
  analysis: RNA-seq
  description: normal_1
  files:
  - /media/ssd/RNA-Seq-ALZS-MandaRat30/MandaRat30Fastq/test_bcbio/input/SH6301_SA69601_S1_merge_R1_001.fastq.gz
  - /media/ssd/RNA-Seq-ALZS-MandaRat30/MandaRat30Fastq/test_bcbio/input/SH6301_SA69601_S1_merge_R2_001.fastq.gz
  genome_build: rn6
  metadata:
    panel: normal
fc_name: seqc
upload:
  dir: ../final
```

```

**Observed behavior**
Error message or bcbio output: no error 
```

```

**Expected behavior**
I should see three folders in the output: Project directory, Sample directories and bcbioRNASeq directory. But I only see the first two folders and did not see the bcbioRNASeq folder.

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[log.zip](https://github.com/bcbio/bcbio-nextgen/files/5221496/log.zip)

**Additional context**
I did not see the bcbioRNASeq folder.

**Comment by roryk** [comment]
Hello! You need to turn `bcbioRNASeq` on, see https://bcbio-nextgen.readthedocs.io/en/latest/contents/bulk_rnaseq.html#parameters to see how to do it. 

It looks like your run is just a single sample though and `bcbioRNASeq` will turn itself off if there are < 3 samples since you can't do any meaningful statistics on it.

Hope that helps!
