### ISSUE TITLE
How can I change the reference for gene quantification?

### ISSUE THREAD

**Issue by xgong-tb** [bcbio/bcbio-nextgen#3354]
Dear There,

I would like to use the bulk RNA-Seq pipeline to do data analysis. I did some test and figured that the default is Ensembl reference for gene quantification. Is there anyway I can change it to RefSeq reference? Thanks!

Xue

**Comment by roryk** [comment]
Hi @xgong-tb,

Sorry for taking so long to get back to you. You can provide a GTF file from RefSeq if you like via the `transcriptome_gtf` option, and bcbio will use that to do the quantification. You have to be careful though to make sure the chromosome names match up and the GTF is well formed. If you can point me to the GTF you want to use, I can tell you if it will be compatible or not. Sorry again for the delay.
