### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by drlaurenwasson** [bcbio/bcbio-nextgen#3362]
Hello,
I am trying to run bcbio for the first time in a while for some bulk-RNA-seq data on the O2 Harvard Computing cluster and it fails pretty much immediately, even before alignment. Therefore there must be some trouble with my setup.

Here is my batch script to run it:
#SBATCH -p short
#SBATCH --job-name=bcbionextgen
#SBATCH -c 1
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=10G
#SBATCH -e bcbionextgen.err

bcbio_nextgen.py ../config/submission_hg38.yaml -n 64 -t ipython -s slurm -q short '-rW=100:00' --retries 3 --timeout 5000

I made sure that the yaml file exists in the proper place and it looks like this

details:
- algorithm:
    aligner: star
    quality_format: standard
    trim_reads: false
  analysis: RNA-seq
  description: PGP1_D30_1_AS
  files:
  - <the correct fastq files are here_R1>
- <the correct fastq files are here_R2>
  genome_build: hg38
  metadata:
    cellline: PGP1
    gene: wt
    person: AS

The error log states this:
Traceback (most recent call last):
  File "/n/app/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/n/app/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    pipelines, config = _pair_samples_with_pipelines(run_info_yaml, config)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 485, in _pair_samples_with_pipelines
    samples = config_utils.load_config(run_info_yaml)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 138, in load_config
    config = _expand_paths(config)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 150, in _expand_paths
    for field, setting in config.items():
AttributeError: 'str' object has no attribute 'items'

**Comment by roryk** [comment]
Hi Lauren,

Hope you are well, sorry for the problem-- is the files attribute missing from your YAML file?  If you can paste the directory you are working in we can take a look at it for you.

**Comment by drlaurenwasson** [comment]
Hi Rory,
Thanks for your response. My current directory is /n/groups/seidman/lauren/RNAseq/2019_02_04

I need to rerun an old pipeline that was run in hg19 to hg38. The fastq files are in the directory above, and the yaml file can be found here:

/n/groups/seidman/lauren/RNAseq/2019_02_04/submission_hg38/config

Thanks for your help
Lauren

On Oct 28, 2020, at 10:51 AM, Rory Kirchner <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Lauren,

Hope you are well, sorry for the problem-- is the files attribute missing from your YAML file? If you can paste the directory you are working in we can take a look at it for you.

**Comment by roryk** [comment]
Thanks, I don't have permissions to look in that directory. Could you upload the YAML file here so I can take a look?

**Comment by drlaurenwasson** [comment]
I believe I changed the settings but I’ve also attached it here
Lauren

On Oct 28, 2020, at 10:59 AM, Rory Kirchner <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks, I don't have permissions to look in that directory. Could you upload the YAML file here so I can take a look?

**Comment by roryk** [comment]
Hi Lauren,

Thanks! Hm, are you sure you are pointing to the right file in your submission script?

`/n/app/bcbio/tools/bin/bcbio_nextgen.py /n/groups/seidman/lauren/RNAseq/2019_02_04/submission_hg38/config/submission_hg38.yaml -n 1` seems to start up fine.

**Comment by roryk** [comment]
Closing for now, please re-open if you are still having troubles. Thank you!
