### ISSUE TITLE
Bulk RNA-seq config template fails to see paired-end reads in input data

### ISSUE THREAD

**Issue by Simontwice** [bcbio/bcbio-nextgen#3375]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.4

- OS name and version (`lsb_release -ds`):Ubuntu 20.04.1 LTS

**To Reproduce**
Exact bcbio command you have used:
```
~/bcbio/project2$ /home/hulk/bcbio/anaconda/bin/bcbio_nextgen.py -w template rnaseq-seqc.yaml input/seqc.csv input
```

**Observed behavior**
Error message or bcbio output:

hulk@Szymon:~/bcbio/project2$ /home/hulk/bcbio/anaconda/bin/bcbio_nextgen.py -w template rnaseq-seqc.yaml input/seqc.csv input

WARNING: sample not found SRR11934385_2.fastq.gz
WARNING: sample not found SRR11934386_2.fastq.gz
WARNING: sample not found SRR11934387_2.fastq.gz
WARNING: sample not found SRR11934388_2.fastq.gz
WARNING: sample not found SRR11934389_2.fastq.gz
WARNING: sample not found SRR11934390_2.fastq.gz

Configuration file created at: /home/hulk/bcbio/project2/seqc/config/seqc.yaml
Edit to finalize and run with:
  cd /home/hulk/bcbio/project2/seqc/work
  bcbio_nextgen.py ../config/seqc.yaml
hulk@Szymon:~/bcbio/project2$ 
hulk@Szymon:~/bcbio/project2$ find . -name SRR11934385_2.fastq.gz
./input/SRR11934385_2.fastq.gz

**Expected behavior**
I excpected that the template would see the _2 parts of the reads - that did not happen.

**Additional context**
The bulk RNA-seq config template refuses to find second parts of the paired-end reads. Mind that my input contains 12 fastq.gz files (only 6 listed above), and the other 6 are the corresponding files ending with _1 instead of _2. 
When i take one pair and swap their suffixes so that the _2 becomes _1 and vice versa, the former _1 file becomes an invisible _2, and a former _2 becomes a visible _1 - thus the contents do not matter, only the suffix. I've included above a clear check that the first of the missing files is in fact in place.
What possibly might matter is the fact that I've already run the pipeline on these files, only I've mislabeled them (I mean the labels contained in input/seqc.csv) and the pipeline output is worthless. When I found that out I tried to run the same thing with fixed labels, only to get this absolutely bizzare problem. I've already tried redownloading the 12 input files and reinstalling bcbio, to no effect.

**Comment by roryk** [comment]
Hi @Simontwice,

Sorry about that-- this is happening because the code to do the matching up the files is getting confused. If you add R before the _1 and _2 it should be able to find it correctly, so _R1 and _R2. bcbio has to guess at which part of the file is the read identifier and sometimes gets it wrong, the R1 and R2 will make it so it definitely uses that part.

**Comment by Simontwice** [comment]
After reinstalling the OS, bcbio and redownloading data, the problem prevails in indentical state. Using _R1/_R2 does _not_ resolve the issue. I am at loss for ideas what might be the cause. Terminal response after changing suffixes to _R1/_R2:

/home/hulk/bcbio/anaconda/bin/bcbio_nextgen.py -w template rnaseq-seqc.yaml input/seqc.csv input
WARNING: sample not found SRR11934385_R2.fastq.gz
WARNING: sample not found SRR11934386_R2.fastq.gz
WARNING: sample not found SRR11934387_R2.fastq.gz
WARNING: sample not found SRR11934388_R2.fastq.gz
WARNING: sample not found SRR11934389_R2.fastq.gz
WARNING: sample not found SRR11934390_R2.fastq.gz

Configuration file created at: /home/hulk/bcbio/myproject/seqc/config/seqc.yaml
Edit to finalize and run with:
  cd /home/hulk/bcbio/myproject/seqc/work
  bcbio_nextgen.py ../config/seqc.yaml

**Comment by Simontwice** [comment]
Additionally, if I delete one _R1 name from the sample info file seqc.csv, the config template warns us that there are files within the specified directory that are not described in the seqc.csv:

WARNING: Added minimal sample information: metadata not found for SRR11934390, ['SRR11934390_R1.fastq.gz', 'SRR11934390_R2.fastq.gz']
WARNING: sample not found SRR11934385_R2.fastq.gz
WARNING: sample not found SRR11934386_R2.fastq.gz
WARNING: sample not found SRR11934387_R2.fastq.gz
WARNING: sample not found SRR11934388_R2.fastq.gz
WARNING: sample not found SRR11934389_R2.fastq.gz
WARNING: sample not found SRR11934390_R2.fastq.gz

Notice in the first warning above that _R1 and _R2 are both classified as part of SRR11934390, and the script does see _R2 in the first warning, then goes on to state in the last warning that the same sample was not found.
Deletion of any _R2 file, on the other hand, only results in one less warning about samples not being found:

WARNING: sample not found SRR11934385_R2.fastq.gz
WARNING: sample not found SRR11934386_R2.fastq.gz
WARNING: sample not found SRR11934387_R2.fastq.gz
WARNING: sample not found SRR11934388_R2.fastq.gz
WARNING: sample not found SRR11934389_R2.fastq.gz

I would appreciate any insight on possible fixes.

**Comment by Simontwice** [comment]
One last important thing is that when I run the main analysis the same thing happens - so writing the config files by hand does not resolve the issue.

**Comment by roryk** [comment]
Thanks, sorry for the slow response. Could you post your `seqc.csv` and `seqc.yaml` files so I can take a look at them?

**Comment by jrozycka** [comment]
I'm having exactly the same issue. Switching 1s and 2s in labels produces exactly the same effect, and changing the _1 and _2 to _R1 and _R2 does not help. I'm following the bulk RNA-seq user story and the template creation and workflow worked once, but when I tried to repeat it with slightly different parameters it suddenly stopped seeing the _2 files, even though they are all still in the same input folder.

My seqc.csv file:
samplename,description
ERR2179089_1.fastq.gz,sample62
ERR2179089_2.fastq.gz,sample62
ERR2179090_1.fastq.gz,sample106
ERR2179090_2.fastq.gz,sample106

seqc.yaml I kept unchanged from the tutorial:
# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: hg38
    algorithm:
      quality_format: Standard
      aligner: star
      strandedness: unstranded
upload:
  dir: ../final

I'm running 
bcbio_nextgen.py -w template rnaseq-seqc.yaml input/seqc.csv input
and the message I'm getting is:
WARNING: sample not found ERR2179089_2.fastq.gz
WARNING: sample not found ERR2179090_2.fastq.gz

Configuration file created at: /encrypted_1/julia/projects/bcbio_test/seqc/config/seqc.yaml
Edit to finalize and run with:
  cd /encrypted_1/julia/projects/bcbio_test/seqc/work
  bcbio_nextgen.py ../config/seqc.yaml

Any ideas what I might be doing incorrectly? Thanks.

**Comment by roryk** [comment]
Thanks, yes-- the CSV file just needs to be pointed to the one file:

```csv
samplename,description
ERR2179089_1.fastq.gz,sample62
ERR2179089_2.fastq.gz,sample62
ERR2179090_1.fastq.gz,sample106
ERR2179090_2.fastq.gz,sample106
```

should be:

```csv
samplename,description
ERR2179089_1.fastq.gz,sample62
ERR2179090_1.fastq.gz,sample106
```

bcbio will automatically figure out the _1 and _2 should be together for each of those. The 

```
WARNING: sample not found ERR2179089_2.fastq.gz
WARNING: sample not found ERR2179090_2.fastq.gz
```

message is because `ERR2179089_2.fastq.gz` has been assigned as the pair to `ERR2179089_1.fastq.gz` so it doesn't exist anymore. If you look in `config/seqc.yaml` you should see two samples, sample62 and sample106, both with the _1 and _2 assigned to it.

**Comment by naumenko-sa** [comment]
And the command to generate the config:
```bcbio_nextgen.py -w template rnaseq-seqc.yaml seqc.csv seqc/input/*.gz```

Let us know if that helped! Feel free to re-open if not!
