### ISSUE TITLE
New Feature: create a tools_on: vardict_sv option

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3384]
Hello everyone!

By default, we are running vardict with --nosv. We need a yaml option to switch sv detecting in vardict **on**.
It should not be the default behavior, because the output could be problematic for some downstream analysis tools
(duplicated SV calls in the file?).

Switching SV detection ON adds 10-15% to vardict running time. Vardict itself is ~10% of a bcbio run, so it is not a big increase.

SN

**Comment by lbeltrame** [comment]
+1 to the idea. Is there any paper (or preprint) which discussed VarDict's SV calling?

**Comment by roryk** [comment]
Hi Luca, yup https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4914105/ talks about it some. We haven't done any independent validation though, yet.

**Comment by naumenko-sa** [comment]
That request did not prove itself to be useful: it disturbs the default behaviour of vardict and does not add useful output.
