### ISSUE TITLE
How to change IPython parent directory?

### ISSUE THREAD

**Issue by pengxiao78** [bcbio/bcbio-nextgen#3386]
Hi,

I found the following error when used IPython parallel because my home directory does not have enough space. Is there any way to change the IPython parent directory?
/.../bcbio/anaconda/lib/python3.6/site-packages/IPython/paths.py:67: UserWarning: IPython parent '/home/peng' is not a writable location, using a temp directory.
" using a temp directory.".format(parent))

Thanks!

**Comment by roryk** [comment]
Hi @pengxiao78,

Sorry-- we don't have a way to do that-- the IPython directory should be really really small though, is it taking up a lot of space in your home directory?

**Comment by pengxiao78** [comment]
Hi @roryk 
I checked my home directory. I have enough space and authority to write. Could you let me know why this error appeared?
Thanks!

**Comment by roryk** [comment]
Hi @pengxiao78,

Sorry for being slow about getting back to you, I was on break. Are you actually seeing an error or is it just the warning?

**Comment by pengxiao78** [comment]
Hi @roryk,
It's an actual error that resulted failure in installation. Sorry, I did not reply to you question since I was successfully installed bcbio in another server. However, if you still can help me with this one, I really appreciate it in case that I have many samples to run. Thank you!

**Comment by naumenko-sa** [comment]
Two thoughts:
- is /home/peng your actual home directory? what is your `echo $HOME`?
- where are you installing bcbio? usually, home directories on HPC have a low quota and bcbio installation happens in `/where/big/volume/mounted`.
