### ISSUE TITLE
Deactivate dbSNP annotation

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3388]
I appreciate the many configuration options in bcbio a lot. Currently, I am trying to minimize footprint and runtime of the small-variants analysis in bcbio for testing purposes. 
Is it possible to deactivate the dbSNP annotation with vcfanno? The dbSNP vcf file is >10G and annotation takes its time.

--
Ben

**Comment by roryk** [comment]
Hi Ben,

I'm really sorry for being slow about getting back to you.  Do you want to stop vcfanno entirely or just dbSNP?
For just dbSNP, not specifically in the YAML file, but if you comment it out from the `gemini.conf` file in `genomebuild/config/vcfanno/gemini.conf` it will stop loading it. 

Rory

**Comment by gabeng** [comment]
Hi Rory,
it is just about dbSNP. Thanks for the hint to `gemini.conf`, I will try that. It should solve my problem.

--
Ben
