### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment:

### ISSUE THREAD

**Issue by mahimakaushik-oss** [bcbio/bcbio-nextgen#3393]
Hello,
I am trying to install mysql connector in anaconda  but its showing this error. 
can anyone help me to find solution for this error---->
conda install -c anaconda mysql-connector-python
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - mysql-connector-python -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by roryk** [comment]
Hi Mashima,

Hope you are well-- this is a repository for the bioinformatics tool bcbio-nextgen, we just show up first on Google with a lot of conda issues. You might get better answers on the anaconda channel.

That being said, it looks like mysql-connector-python doesn't support python 3.8 yet, so you will have to install it into its own environment that has python 3.7, like this:

```bash
conda create -n py37 python=3.7 mysql-connector-python
```

and you can switch to that environment to use it with:
```bash
conda activate py37
```

Hope that helps!
