### ISSUE TITLE
Installation and upgrade use both mamba and conda

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3395]
This is more of an issue in cloudbiolinux (which I will report) but since it affects bcbio, I'll report it also here.

`conda` can be very slow, taking days, to resolve environments with very old installs of bcbio (this one has been constantly upgraded for a few years), while mamba doesn't.

However, cloudbiolinux does two passes, one with mamba and one with conda, causing upgrades to take days unless the conda part is patched out. Conda should be used only as a fallback if mamba fails, instead.

I'll report a separate issue in cloudbiolinux.

**Comment by roryk** [comment]
Thank you for finding this! I was wondering why it looked like the solvers were running twice, and this explains it. Thank you thank you thank you thank you thank you.
