### ISSUE TITLE
Post-alignment processing: make CollectSequencingArtifacts optional

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3402]
I appreciate that new features are continuously added to bcbio. You are also providing flexibility to activate or deactivate specific features that are compute-intensive. Would you consider making CollectSequencingArtifacts an optional step?

--
Ben

**Comment by roryk** [comment]
Thanks! Good suggestion. I added this as an option but messed up tagging the commit, to shut it off just do `tools_off: [collectsequencingartifacts]`.

**Comment by gabeng** [comment]
Perfect, thank you!
