### ISSUE TITLE
CNVkit output cnr don't have chromosome X

### ISSUE THREAD

**Issue by jeongmeani** [bcbio/bcbio-nextgen#3404]
HI, 

i'm using cnvkit and it has some problem.

there are some data of WES, and i ran cnvkit with this.
then i got output of cnvkit but some of this don't have chromosome X and scatter plot of normal sample is not clean(high variance of log2 value).

what is the problem? 
could you recommend any solution?

Best Regards

Jeongmin

**Comment by naumenko-sa** [comment]
Hi @jeongmeani!

Thanks for reporting! 

Unfortunately, we don't have the bandwidth to validate CNVkit, as we are focusing currently on
PureCN for CNV calling: https://bcbio-nextgen.readthedocs.io/en/latest/contents/purecn.html

If you found that CNVkit is not running correctly in bcbio in your case, investigated why, 
created a reproducible example, and proposed a solution (PR), we would gladly review and accept it!

Sergey

**Comment by naumenko-sa** [comment]
closing for now, please re-open if you could provide some additional input.
