### ISSUE TITLE
Fresh installation - scramble issue

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3408]
Hello!

I'm doing a fresh installation:

```
Checking for problematic or migrated packages in default environment
Installing initial set of packages for default environment with mamba

Encountered problems while solving.
Problem: package scramble-1.0.1-h516909a_0 requires htslib >=1.11,<1.12.0a0, but none of the providers can be installed
```

It continues to solve, but, I think, without scramble.

SN

**Comment by roryk** [comment]
Gotcha-- this worked for me on an upgrade, but I guess not a fresh install. I'm testing sticking scramble into a htslib1.11 environment; eventually we can drop those and the htslib1.10 environments but we need to wait for bioconda to rebuild everything with those versions.

**Comment by roryk** [comment]
Ok, should be fixed now!

**Comment by naumenko-sa** [comment]
Thanks, it worked!
