### ISSUE TITLE
Gemini annotation by bcbio missing some boolean columns

### ISSUE THREAD

**Issue by audyavar** [bcbio/bcbio-nextgen#3418]
Hi Brad - 

I am trying to run bcbio on tumor-only sample. It ran successfully and provided gemini annotated files for freebayes, vardict and varscan. However, the vcf files in the individual folders say "filtered-annotated-gemini-priority.vcf.gz', I dont see the vcf files filtered for variants that are present in gnomAD, ExAC etc. In addition, the boolean columns that typically exist in gemini annotated files such as "in_dbsnp", "in_exac" etc are missing from the vcf files. Also is there a way to filter the vcfs post-gemini using these columns using bcftools or other tools? Kindly advise. TIA

**Comment by roryk** [comment]
Hi @audyavar!

We have swapped over from using GEMINI to load the database to using `vcf2db.py` because it is faster and much more flexible, so some of the columns are named differently. If you do `gemini db_info your-gemini.db` you should be able to see all of the columns and there may be one you can filter on if you are using GEMINI.

Alternatively you can filter the VCF files yourself, `bcftools query` has a filtering language you can use to filter out VCF files. We don't do much filtering of the VCF files, instead we annotate them with the exac/gnomad/etc information so that users can decide what they want to look at.

Hope that helps get you going!

**Comment by roryk** [comment]
@audyavar,

https://github.com/brentp/slivar also looks quite nice for doing filtering on VCF files without bothering to create the database, that might be a useful.

**Comment by naumenko-sa** [comment]
Hello!

Thanks for the discussion!

Typical variant analysis has 3 stages:
- variant calling;
- variant annotation;
- variant prioritization.

Bcbio focuses on 1) and 2) but not on 3).

Once variants are annotated you may query them (using gemini.db, vcf file, excel, big data warehouse system like https://www.solvebio.com/ - depending on the scale of your project).

Variant prioritization methods are numerous and specific to the project:
- gene panels;
- population frequency;
- COSMIC and other DB status;
- variant impact;
- variant effect predictions;
- VAF;
- segregation in a pedigree;
- informed by analyses of other data types (RNA-seq);
- overlap with an internal database;
- MUTECT2 or other caller filter status.

SN

**Comment by ohofmann** [comment]
For tumor only data you might also want to feed them through something like [PCGR](https://github.com/sigven/pcgr) which handles 1000G/Exac/GnomAD filtering. In addition to the HTML reports you also get annotated VCFs which you can feed into other downstream processes.

**Comment by audyavar** [comment]
Thanks so much everyone. Will give these suggestions a try.

We have done some benchmarking between tumor + matched normal (TN) versus tumor only (TO) variant calls from 150bp paired end exome sequencing. The recall is high (80-95%) because of the high number of calls in TO mode. However the precision is poor 0.005-0.01 (computed with som.py). We have tried restricting variants to just clinically actionable ones according to ACMG and PCGR, and also high AF/DP etc but that hasn't helped a whole lot. What has your experience been? Any specific variant callers that you recommend for TO variant calling? Is there any merit in using mutect2 with panel of normals to decrease false positives? Any suggestions here would be greatly useful.

Sincerely,


Akshata

________________________________

**Comment by ohofmann** [comment]
You mean precision when counting all germline variants that are called as somatic? There's not much you can do in tumor-only calling other than filtering against an appropriate reference set (ideally same ancestry as your patient(s)) and maybe filtering against your own panel of normals. After that you can just whittle things down a bit with GnomAD. https://bcbio.wordpress.com/2015/03/05/cancerval/ is almost six years old but things haven't changed much, tbh.

**Comment by roryk** [comment]
Thanks for the discussion everyone-- wow PCGR looks great.
