### ISSUE TITLE
Scalpel Fails on Single Sample

### ISSUE THREAD

**Issue by eeleclair** [bcbio/bcbio-nextgen#3420]
I know there is a Scalpel page on Sourceforge but no users seem to post there.  Can any community members assist? 
********
I installed Scalpel as indicated in[ this paper](https://www.biorxiv.org/content/10.1101/028050v1.full.pdf) and finally got it to run, but it fails within seconds and not sure why.  New to Linux so can you me if the problem is my   input and/or the installation?  I've spent 3 weeks on this.  :-(   Or is there another way to run the same analysis?  I need to find indels (not SNPs) on chromosome 15, thanks. :-)

$ perl /mnt/d/scalpel-0.5.4/scalpel-discovery --single --bam /mnt/d/scalpel-0.5.4/MC-files/MC-fish.marked_duplicates.bam --bed 15:1-48040578 --ref /mnt/d/scalpel-0.5.4/MC-files/danRer11.fa --window 600 --numprocs 4

Program: scalpel-discovery (micro-assembly variant detection)
Version: 0.5.4 (beta), January 11 2018
Contact: Giuseppe Narzisi <gnarzisi@nygenome.org>

***START ANALYSIS***
-- Print parameters to /mnt/d/scalpel-0.5.4/outdir/parameters.txt
Loading targets region: 15:1-48040578
Loading genome from FASTA file...1923 sequences.
Assembly Exons
start assembly of 480402 regions.
stepSize: 120101
Undefined sequence (15)
Command failure: FindVariants (/mnt/d/scalpel-0.5.4/FindVariants.pl --bam /mnt/d/scalpel-0.5.4/MC-files/MC-fish.marked_duplicates.bam --bed 15:1-48040578 --ref /mnt/d/scalpel-0.5.4/MC-files/danRer11.fa --kmer 25 --covthr 5 --lowcov 2 --mincov 5 --covratio 0.01 --outratio 0.05 --radius 100 --window 600 --maxregcov 10000 --step 100 --mapscore 1 --mismatches 3 --pathlimit 1000000 --dir /mnt/d/scalpel-0.5.4/outdir --numprocs 4 --format vcf --seed 0 --coords null)...
child exited with value 25
Discovery: elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 16 second(s)

**Comment by roryk** [comment]
Hi @eeleclair,

It looks like this is the source of your problem: `Undefined sequence (15)`

I think `--bed 15:1-48040578` is the problem. I'm guessing that your BAM file has a different chromosome naming than 15, maybe it has names like `chr15`?

Hope that helps!

**Comment by eeleclair** [comment]
That helped a lot, it seems to have started to run.  But is it normal to take >24 hours to analyze one chromosome?  The CPU is still busy but I don't see any output files after an entire day.

**Comment by roryk** [comment]
Hi @eeleclair,

scalpel is very slow on whole genomes, so if you are running on whole genomes then it will take a long time. We recommend using a different caller on whole genomes; depending on the size of indels you want to call, different callers do a better job. Manta would be a good choice though.

**Comment by eeleclair** [comment]
Hello again, thanks so much for your feedback.  But I'm only running on one
chromosome... shouldn't that get it done in 1/20th the time?  Just looking
for an overall estimate as I've never run this type of analysis before.

**Comment by roryk** [comment]
Hi @eeleclair,

In the scalpel paper, it takes 5 hours to run a reasonable depth whole exome with scalpel with 10 cores and 64 GB of RAM, and that's 2% of the genome so you'd expect a single chromosome to take around double that with 10 cores. There may be algorithm issues that make it even slower on whole genomes as well. The takeaway is scalpel is really slow on whole genomes so we don't recommend using it for them.

**Comment by roryk** [comment]
Oh I'm just noticing this is Zebrafish, I'm not sure how scalpel will run on Zebrafish WGS, we haven't actually done that. Are you specifically looking for indels? If you are just looking for SNPs and short indels I would just run GATK HaplotypeCaller on it, that is our standard method for calling on model organisms.
