### ISSUE TITLE
Versioning issue of vardict bioconda package

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3421]
**Version info**
- bcbio version: 1.2.5

**Description**
The mixed versioning of the vardict bioconda package may create issues when defining dependencies, e. g. 
https://github.com/bcbio/bcbio-nextgen/blob/3f8a6e6342e1ba5c4dcfdda2c0ff70731ab8655f/bcbio/variation/vardict.py#L54

The current version of the bioconda vardict package is `1.8.2` which is sorted numerically before `2018`. Not sure if this is ever relevant here, but the vardict restriction will probably never be true in current bcbio installs.
See also https://github.com/chapmanb/cloudbiolinux/commit/c0a983fd1340eecff0d8b8e419ea2ce21d93feae and https://github.com/bioconda/bioconda-recipes/issues/26140.

**Comment by roryk** [comment]
Thank you for catching this. We want SV calling to be turned off all of the time ATM (though we are testing VarDict's SV calling) so I just turned it off if we are using the vardict command-line at all. I'm wondering if we even need to support the non vardict-java version of vardict anymore, will talk to the VarDict folks about it.
