### ISSUE TITLE
Can someone confirm that the tximport-counts.csv column label headings (salmon, salmon.1, salmon.2) are in the order of the metadata.csv?

### ISSUE THREAD

**Issue by froggiie** [bcbio/bcbio-nextgen#3422]
I have run some samples through the RNAseq pipeline using bcbio 1.2.0 that includes alignment by STAR and also expression calling by salmon.

The final result folder gives me an annotated_combined.counts.csv file which I believe is a Featurecounts calling from the STAR-aligned BAM files. This CSV file contains the correct column headings per sample in the order of  the original metadata.csv file I created (e.g. "individual 1, individual 2, individual 3...")

For my downstream RNAseq analysis I would like to use the counts generated by Salmon. I can find the gene-collapsed counts in tximport-counts.csv file. However, the column headings are generic (i.e. "salmon, salmon.1, salmon.2"). Can I safely assume that these headings follow the order of the metadata.csv file I created, and indeed the featurecounts file?

Many thanks in advance.

Kind regards,
Richard

**Comment by roryk** [comment]
Hi Richard,

Hope you are well-- bcbio 1.2 is super old. If it is possible I would update bcbio to a new version and rerun. Since the version of bcbio is old, I'd just load the files from Salmon with tximport, instructions on how to do that are here: https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html#salmon

**Comment by froggiie** [comment]
Hi roryk,

Thanks for the reply. If it's possible to not re-run the samples again that would be ideal - unless there are any major RNAseq problems that were addressed in the later versions. 

The reason for this is it's a relatively large ~80 sample cohort that would need re-running. I will take a look at the code for tximport to see if I can either generate the matrix for all samples. Perhaps I can confirm for one or two samples. Thank you again for your suggestion.

**Comment by roryk** [comment]
Hi Richard,

Not much should have changed if you are using the Salmon quantifications, there have been some minor improvements but in general you should be fine going ahead with those. The tximport way is definitely the way to go, that is all that bcbio is doing on the Salmon files. We use the `lengthScaledTPM` option, which is a little confusing but the best explanation I found was on biostars: https://support.bioconductor.org/p/84883/   the idea of it is that you remove length-expression bias between libraries, but then put back in the average length-expression bias of all the samples back in so the data looks like normal RNA-seq count data again but without the sample-bias present.

Hope that helps get you going!
