### ISSUE TITLE
subprocess.CalledProcessError during Somatic (cancer) variant calling

### ISSUE THREAD

**Issue by Hmllycat** [bcbio/bcbio-nextgen#3424]
Traceback (most recent call last):
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/ibex/scratch/projects/c2014/bcbio2/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/encrypted/e3008/Yang/work16/bcbiotx/tmp1la74ajx' Mutect2 --annotation ClippingRankSumTest --annotation DepthPerSampleHC --reference /ibex/scratch/projects/c2014/bcbio2/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage --read-validation-stringency LENIENT -I /encrypted/e3008/Yang/work16/align/hepa-tumor01/hepa-tumor01-sort.bam --tumor-sample hepa-tumor01 -I /encrypted/e3008/Yang/work16/align/hepa-normal01/hepa-normal01-sort.bam --normal-sample hepa-normal01 -L /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-regions-nolcr.bed --interval-set-rule INTERSECTION -O /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz && sed -i 's/callable\t0.0/callable\t10.0/' /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz.stats && unset JAVA_HOME && export PATH=/ibex/scratch/projects/c2014/bcbio2/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/encrypted/e3008/Yang/work16/bcbiotx/tmp1la74ajx' FilterMutectCalls --reference /ibex/scratch/projects/c2014/bcbio2/genomes/Hsapiens/hg38/seq/hg38.fa --variant /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz --output /encrypted/e3008/Yang/work16/bcbiotx/tmp1la74ajx/syn3-chr8_16183871_32817073-raw-filt.vcf.gz
INFO: Failed to detect whether we are running on Google Compute Engine.

**Comment by Hmllycat** [comment]
I added details here, and if anyone wanna have a look on the whole log file, here is the link, 
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5874862/bcbio-nextgen.log)


"""
01:10:10.275 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.35258290800000003
01:10:10.275 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 65.65309177600001
01:10:10.275 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 107.90 sec
01:10:10.275 INFO  Mutect2 - Shutting down engine
[January 25, 2021 1:10:10 AM AST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 8.53 minutes.
Runtime.totalMemory()=691404800
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1927)
	at org.broadinstitute.hellbender.tools.walkers.annotator.TandemRepeat.getNumTandemRepeatUnits(TandemRepeat.java:54)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyRegionTrimmer.trim(AssemblyRegionTrimmer.java:175)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:229)
	at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:299)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
Using GATK jar /ibex/scratch/projects/c2014/bcbio2/anaconda/share/gatk4-4.1.7.0-0/gatk-package-4.1.7.0-local.jar defined in environment variable GATK_LOCAL_JAR
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/encrypted/e3008/Yang/work16/bcbiotx/tmp1la74ajx -jar /ibex/scratch/projects/c2014/bcbio2/anaconda/share/gatk4-4.1.7.0-0/gatk-package-4.1.7.0-local.jar Mutect2 --annotation ClippingRankSumTest --annotation DepthPerSampleHC --reference /ibex/scratch/projects/c2014/bcbio2/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage --read-validation-stringency LENIENT -I /encrypted/e3008/Yang/work16/align/hepa-tumor01/hepa-tumor01-sort.bam --tumor-sample hepa-tumor01 -I /encrypted/e3008/Yang/work16/align/hepa-normal01/hepa-normal01-sort.bam --normal-sample hepa-normal01 -L /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-regions-nolcr.bed --interval-set-rule INTERSECTION -O /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz
' returned non-zero exit status 3.
[2021-01-24T22:10Z] cn513-03-l: Unexpected error
Traceback (most recent call last):
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 439, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 377, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/variation/mutect2.py", line 160, in mutect2_caller
    do.run(cmd.format(**locals()), "MuTect2")
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/ibex/scratch/projects/c2014/bcbio2/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/encrypted/e3008/Yang/work16/bcbiotx/tmp1la74ajx' Mutect2 --annotation ClippingRankSumTest --annotation DepthPerSampleHC --reference /ibex/scratch/projects/c2014/bcbio2/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage --read-validation-stringency LENIENT -I /encrypted/e3008/Yang/work16/align/hepa-tumor01/hepa-tumor01-sort.bam --tumor-sample hepa-tumor01 -I /encrypted/e3008/Yang/work16/align/hepa-normal01/hepa-normal01-sort.bam --normal-sample hepa-normal01 -L /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-regions-nolcr.bed --interval-set-rule INTERSECTION -O /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz && sed -i 's/callable\t0.0/callable\t10.0/' /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz.stats && unset JAVA_HOME && export PATH=/ibex/scratch/projects/c2014/bcbio2/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/encrypted/e3008/Yang/work16/bcbiotx/tmp1la74ajx' FilterMutectCalls --reference /ibex/scratch/projects/c2014/bcbio2/genomes/Hsapiens/hg38/seq/hg38.fa --variant /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz --output /encrypted/e3008/Yang/work16/bcbiotx/tmp1la74ajx/syn3-chr8_16183871_32817073-raw-filt.vcf.gz
INFO: Failed to detect whether we are running on Google Compute Engine.
01:01:46.511 INFO  Mutect2 - ------------------------------------------------------------
01:01:46.512 INFO  Mutect2 - The Genome Analysis Toolkit (GATK) v4.1.7.0
"""

**Comment by naumenko-sa** [comment]
Hi @Hmllycat !

I looks like mutect2 call failed at 
`01:10:01.261 INFO  ProgressMeter -        chr8:29752949              8.0                 58790           7363.0`

when processing this chunk of T/N bam files:
```
-I /encrypted/e3008/Yang/work16/align/hepa-tumor01/hepa-tumor01-sort.bam \
--tumor-sample hepa-tumor01 \
-I /encrypted/e3008/Yang/work16/align/hepa-normal01/hepa-normal01-sort.bam --normal-sample hepa-normal01 -L /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-regions-nolcr.bed --interval-set-rule INTERSECTION -O /encrypted/e3008/Yang/work16/mutect2/chr8/syn3-chr8_16183871_32817073-raw.vcf.gz
```
You may try to investigate coverage at the locus - maybe you have a peak there?
Also you may try to give more RAM to gatk and also try to process this locus out of bcbio just running mutect on the command line adding memory: https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources

SN

**Comment by Hmllycat** [comment]
@naumenko-sa 

I tried to increase the memory from 48G to 100G and is waiting for the result. I will get back to you if the job stops running.

**Comment by naumenko-sa** [comment]
Note that the max GATK RAM (per core) is increased in the yaml config.
If you gave more RAM to the main launch script, and have not changed anything here, 
that would not make a difference.

```
resources:
  gatk:
    jvm_opts: ["-Xms2g", "-Xmx4g"]
```

**Comment by Hmllycat** [comment]
@naumenko-sa , thank you for your suggestion. However, it fails again. Attached is the log file. I think the error is the similar.

[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5909215/bcbio-nextgen.log)

**Comment by naumenko-sa** [comment]
@Hmllycat,

Could you try to investigate the locus?
- run the mutect command outside of bcbio for the locus to see if it works;
- investigate coverage in the locus (IGV, or bedtools)

**Comment by Hmllycat** [comment]
@naumenko-sa 

Thank you for your helpful advice, I find that it has something to do with the gatk version. After I tried the latest version of gatk, it works!

**Comment by roryk** [comment]
Thank you!
