### ISSUE TITLE
subprocess.CalledProcessError when call copy number variants.

### ISSUE THREAD

**Issue by Hmllycat** [bcbio/bcbio-nextgen#3425]
Traceback (most recent call last):
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/ibex/scratch/projects/c2014/bcbio2/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; bamcat level=0 tmpfile=/encrypted/e3007/Yang/pon/work/bcbiotx/tmpjsv__dfl/bcbiotx/tmpil0cv6jd/LS1P0010-V01-sort.bam-bammerge `cat /encrypted/e3007/Yang/pon/work/bcbiotx/tmpjsv__dfl/bcbiotx/tmpil0cv6jd/LS1P0010-V01-sort.list` | bamsormadup threads=16 tmpfile=/encrypted/e3007/Yang/pon/work/bcbiotx/tmpjsv__dfl/bcbiotx/tmpil0cv6jd/LS1P0010-V01-sort.bam-bamsormaduptmp indexfilename=/encrypted/e3007/Yang/pon/work/bcbiotx/tmpjsv__dfl/bcbiotx/tmpil0cv6jd/LS1P0010-V01-sort.bam.bai > /encrypted/e3007/Yang/pon/work/bcbiotx/tmpjsv__dfl/bcbiotx/tmpil0cv6jd/LS1P0010-V01-sort.bam

**Comment by roryk** [comment]
Hi @Hmllycat,

It's tough to debug this without seeing the whole error-- this is just telling us the command failed, but not why. Could you post more of the log, or the entire log, so that we can take a look? I'm guessing the same issue is causing both problems you posted.

**Comment by naumenko-sa** [comment]
Can you also share you pon.yaml?
See also some memory tweaks in: #3230 for production-size pureCN runs.

**Comment by Hmllycat** [comment]
@naumenko-sa, thanks for your reply, here is my pon.yaml file:

"""
details:
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0001-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5896_LS1P0001-V01-BFC1_i701-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5896_LS1P0001-V01-BFC1_i701-i501_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0001-V01-tumor
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5897_LS1P0001-V01-LIV1_i702-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5897_LS1P0001-V01-LIV1_i702-i501_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: tumor
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0002-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5898_LS1P0002-V01-BFC1_i703-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5898_LS1P0002-V01-BFC1_i703-i501_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5899_LS1P0002-V01-LIV1_i704-i501
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5899_LS1P0002-V01-LIV1_i704-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5899_LS1P0002-V01-LIV1_i704-i501_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0002-V02
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5900_LS1P0002-V02-BFC1_i705-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5900_LS1P0002-V02-BFC1_i705-i501_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5901_LS1P0002-V02-LIV1_i706-i501
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5901_LS1P0002-V02-LIV1_i706-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5901_LS1P0002-V02-LIV1_i706-i501_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0006-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5902_LS1P0006-V01-BFC1_i707-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5902_LS1P0006-V01-BFC1_i707-i501_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5903_LS1P0006-V01-LIV1_i708-i501
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5903_LS1P0006-V01-LIV1_i708-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5903_LS1P0006-V01-LIV1_i708-i501_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0008-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5906_LS1P0008-V01-BFC1_i7011-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5906_LS1P0008-V01-BFC1_i7011-i501_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5907_LS1P0008-V01-LIV1_i7012-i501
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5907_LS1P0008-V01-LIV1_i7012-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5907_LS1P0008-V01-LIV1_i7012-i501_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0010-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5908_LS1P0010-V01-BFC1_i701-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5908_LS1P0010-V01-BFC1_i701-i502_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5909_LS1P0010-V01-LIV1_i702-i502
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5909_LS1P0010-V01-LIV1_i702-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5909_LS1P0010-V01-LIV1_i702-i502_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0013-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5910_LS1P0013-V01-BFC1_i703-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5910_LS1P0013-V01-BFC1_i703-i502_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5911_LS1P0013-V01-LIV1_i704-i502
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5911_LS1P0013-V01-LIV1_i704-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5911_LS1P0013-V01-LIV1_i704-i502_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0014-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5912_LS1P0014-V01-BFC1_i705-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5912_LS1P0014-V01-BFC1_i705-i502_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5913_LS1P0014-V01-LIV1_i706-i502
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5913_LS1P0014-V01-LIV1_i706-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5913_LS1P0014-V01-LIV1_i706-i502_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0015-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5914_LS1P0015-V01-BFC1_i707-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5914_LS1P0015-V01-BFC1_i707-i502_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5915_LS1P0015-V01-LIV1_i708-i502
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5915_LS1P0015-V01-LIV1_i708-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5915_LS1P0015-V01-LIV1_i708-i502_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0023-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5918_LS1P0023-V01-BFC1_i7011-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5918_LS1P0023-V01-BFC1_i7011-i502_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5919_LS1P0023-V01-LIV1_i7012-i502
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5919_LS1P0023-V01-LIV1_i7012-i502_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5919_LS1P0023-V01-LIV1_i7012-i502_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0023-V02
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5920_LS1P0023-V02-BFC1_i701-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5920_LS1P0023-V02-BFC1_i701-i503_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5921_LS1P0023-V02-LIV1_i702-i503
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5921_LS1P0023-V02-LIV1_i702-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5921_LS1P0023-V02-LIV1_i702-i503_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0024-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5922_LS1P0024-V01-BFC1_i703-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5922_LS1P0024-V01-BFC1_i703-i503_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5923_LS1P0024-V01-LIV1_i704-i503
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5923_LS1P0024-V01-LIV1_i704-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5923_LS1P0024-V01-LIV1_i704-i503_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0025-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5924_LS1P0025-V01-BFC1_i705-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5924_LS1P0025-V01-BFC1_i705-i503_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5925_LS1P0025-V01-LIV1_i706-i503
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5925_LS1P0025-V01-LIV1_i706-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5925_LS1P0025-V01-LIV1_i706-i503_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0026-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5926_LS1P0026-V01-BFC1_i707-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5926_LS1P0026-V01-BFC1_i707-i503_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5927_LS1P0026-V01-LIV1_i708-i503
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5927_LS1P0026-V01-LIV1_i708-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5927_LS1P0026-V01-LIV1_i708-i503_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0033-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5928_LS1P0033-V01-BFC1_i709-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5928_LS1P0033-V01-BFC1_i709-i503_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5929_LS1P0033-V01-LIV1_i7010-i503
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5929_LS1P0033-V01-LIV1_i7010-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5929_LS1P0033-V01-LIV1_i7010-i503_R2.fastq.gz
  genome_build: hg38
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0034-V01
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5930_LS1P0034-V01-BFC1_i7011-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5930_LS1P0034-V01-BFC1_i7011-i503_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: pon_build
    svclass: control
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5931_LS1P0034-V01-LIV1_i7012-i503
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5931_LS1P0034-V01-LIV1_i7012-i503_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5931_LS1P0034-V01-LIV1_i7012-i503_R2.fastq.gz
  genome_build: hg38
fc_name: pon
upload:
  dir: ../final
"""

**Comment by naumenko-sa** [comment]
Could you please attach it as a file? It is hard to tell whether we see a GitHub formatting error or config error.
There are samples with and without `metadata`, also it would help if you described how have you created that config.

**Comment by Hmllycat** [comment]
@naumenko-sa, here is my yaml file, thank you.

[pon.zip](https://github.com/bcbio/bcbio-nextgen/files/5909207/pon.zip)

**Comment by naumenko-sa** [comment]
Some samples are with
```yaml
metadata:
  batch: pon_build
  svclass: control
```
or 
```yaml
metadata:
   batch: pon_build
   svclass: tumor
```
and some are without metadata, for example:
```yaml
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: M-19-5899_LS1P0002-V01-LIV1_i704-i501
  files:
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5899_LS1P0002-V01-LIV1_i704-i501_R1.fastq.gz
  - /encrypted/genomics/YangLiu/hepatocellular/merged/M-19-5899_LS1P0002-V01-LIV1_i704-i501_R2.fastq.gz
  genome_build: hg38
# here new sample starts
- algorithm:
    aligner: bwa
    svcaller: gatk-cnv
  analysis: variant2
  description: LS1P0002-V02
```

Could you make sure that all the samples have their metadata defined, or remove the samples without metadata, and re-run then?

**Comment by Hmllycat** [comment]
@naumenko-sa , thank you, I checked the data and noticed that there are actually some files without meta information, after I removed those files, it works!
