### ISSUE TITLE
Bcbio system and unit tests

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3427]
Hi guys,

I just wanted to know if there are any unit tests currently in bcbio - specifically for the cancer variant calling/cnv workflows  (outdated or otherwise), in the "tests" directory in this repo I don't see many unit tests but not sure if these are hosted here? 

I know there are some system based tests to check various workflows, where are these tests currently kept? I can see the conftest.py and sh scripts but I can't find the test classes

sorry, one last question - I was looking at the install script "bcbio_nextgen_install.py", can't find where the packages and their verions packages are specified.

Any help would be greatly appreciated!

Thanks!
Warren

**Comment by naumenko-sa** [comment]
Hi Warren @waemm!

There are tests!

https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html#testing
https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html#new-release-checklist

The simplest test is 
```
clone bcbio code
cd tests
./run_tests cancermulti
```

Sergey

**Comment by roryk** [comment]
Hi Warren,

Thanks for the questions! To answer your second question, the versions specified can be found here: https://github.com/chapmanb/cloudbiolinux/tree/master/contrib/flavor/ngs_pipeline_minimal

Sorry that it is so confusing, we used to have to handle all of the building and installing the packages ourselves, so it was farmed out to cloudbiolinux and we've just kept it that way over the years.

**Comment by waemm** [comment]
Thank you @roryk  and @naumenko-sa, you guys have done a fantastic job maintaining this tool, it is very much aprpeciated!
