### ISSUE TITLE
Installation on WSL fails

### ISSUE THREAD

**Issue by pastaxingxin** [bcbio/bcbio-nextgen#3430]
I ran this command line:
python bcbio_nextgen_install.py /mnt/e/bcbio/share/bcbio --tooldir=/mnt/e/bcbio --genomes hg38 --aligners bwa --aligners bowtie2
However, I got some errors during the installation, so I failed to install it.
There are parts of errors messages:
"
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 882, in exception_converter
        raise e
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 720, in do_call
        exit_code = create(args, parser)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 624, in create
        return install(args, parser, "create")
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 595, in install
        handle_txn(conda_transaction, prefix, args, newenv)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 148, in handle_txn
        unlink_link_transaction.execute()
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 231, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 591, in _verify
        itervalues(prefix_action_groups)):
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 411, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/e/bcbio/share/bcbio/anaconda/pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/NCR260VT300WPP'

`$ /mnt/e/bcbio/share/bcbio/anaconda/bin/mamba create -q --no-default-packages -y --name python3 python=3 nomkl`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/xingxinpan/anaconda3/bin/conda
         CONDA_PYTHON_EXE=/home/xingxinpan/anaconda3/bin/python
               CONDA_ROOT=/mnt/e/bcbio/share/bcbio/anaconda
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                     PATH=/mnt/e/bcbio/share/bcbio/anaconda/bin:/home/xingxinpan/meme/bin:/home/
                          xingxinpan/meme/libexec/meme-5.1.1:/home/xingxinpan/bin:/home/xingxinp
                          an/.local/bin:/home/xingxinpan/anaconda3/condabin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/
                          mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_
                          2004.2020.812.0_x64__79rhkp1fndgsc:/mnt/c/Program
                          Files/Git/usr/local/bin:/mnt/c/Program
                          Files/Java/jdk-11.0.2/bin:/mnt/c/Program Files/Git/bin:/mnt/c/Program
                          Files (x86)/Graphviz2.38/bin:/mnt/c/Program Files/NVIDIA GPU Computing
                          Toolkit/CUDA/v10.1/bin:/mnt/c/Program Files/NVIDIA GPU Computing Toolk
                          it/CUDA/v10.1/libnvvp:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Wi
                          ndows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mn
                          t/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA
                          Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/IDM Computer
                          Solutions/UltraCompare:/mnt/c/Program Files/IDM Computer
                          Solutions/UltraFinder:/mnt/c/Program Files/IDM Computer
                          Solutions/UltraEdit:/mnt/d/Program Files/MATLAB/MATLAB Production
                          Server/R2015a/runtime/win64:/mnt/d/Program Files/MATLAB/MATLAB
                          Production Server/R2015a/bin:/mnt/d/Program Files/MATLAB/MATLAB
                          Production Server/R2015a/polyspace/bin:/mnt/c/Program Files/NVIDIA
                          Corporation/Nsight Compute 2019.4.0:/mnt/c/Program Files/Java/jdk-14.0
                          .1/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/
                          Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/Sys
                          tem32/OpenSSH:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Docker
                          /Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mn
                          t/c/Users/pasta/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/pasta
                          /AppData/Local/Programs/Microsoft VS
                          Code/bin:/mnt/c/Users/pasta/PyCharm 2019.3.2/bin:/mnt/c/Program Files/
                          Bandizip:/snap/bin:/mnt/e/bioinformatics/homer/bin:/mnt/e/bioinformati
                          cs/htslib-1.9:/mnt/e/bioinformatics/samtools-1.9:/mnt/e/bioinformatics
                          /bcftools-1.9:/mnt/e/bioinformatics/bam-readcount/bin:/mnt/e/bioinform
                          atics/hisat2-2.1.0:/mnt/e/bioinformatics/stringtie-1.3.4d.Linux_x86_64
                          :/mnt/e/bioinformatics/stringtie-1.3.4d.Linux_x86_64/gffcompare-0.10.6
                          .Linux_x86_64:/mnt/e/bioinformatics/stringtie-1.3.4d.Linux_x86_64/gffc
                          ompare-0.10.6.Linux_x86_64/htseq-release_0.11.0/scripts:/mnt/e/bioinfo
                          rmatics/tophat-2.1.1.Linux_x86_64:/mnt/e/bioinformatics/kallisto_linux
                          -v0.44.0:/mnt/e/bioinformatics/FastQC:/mnt/e/bioinformatics/flexbar-3.
                          4.0-linux:/mnt/e/bioinformatics/regtools/build:/mnt/e/bioinformatics/g
                          atk-4.1.7.0:/mnt/e/bioinformatics/bin:/mnt/e/bioinformatics/snpEff:/mn
                          t/e/bioinformatics/sratoolkit.2.9.6-1-ubuntu64/bin:/mnt/e/bioinformati
                          cs/ucsc:/mnt/e/bioinformatics/bedtools2/bin:/mnt/d/Documents/chipseq-
                          project/data/peakcalls/common/buchong/buchong2/33/44/stereogene-
                          master/src:/mnt/e/bioinformatics/geneSCF-master-
                          source-v1.1-p2:/mnt/g/NRSA-v2/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/xingxinpan/.condarc
 populated config files : /mnt/e/bcbio/share/bcbio/anaconda/.condarc
                          /home/xingxinpan/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/e/bcbio/share/bcbio/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/e/bcbio/share/bcbio/anaconda/pkgs
                          /home/xingxinpan/.conda/pkgs
       envs directories : /mnt/e/bcbio/share/bcbio/anaconda/envs
                          /home/xingxinpan/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.7.6 Linux/4.19.104-microsoft-standard ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Traceback (most recent call last):
  File "/mnt/e/bcbio/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 91, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 509, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/mnt/e/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 92, in install_in
    conda_envs = _create_environments(conda_bin, packages)
  File "/mnt/e/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 273, in _create_environments
    .format(**locals()), shell=True)
  File "/mnt/e/bcbio/share/bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/mnt/e/bcbio/share/bcbio/anaconda/bin/mamba create -q --no-default-packages -y --name python3 python=3 nomkl' returned non-zero exit status 1.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 290, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 51, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/e/bcbio/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/mnt/e/bcbio', '--genomes', 'hg38', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
"
Could anyone give me solutions to this?
Thank you in advance.

**Comment by pastaxingxin** [comment]
I ran this command in WSL.

**Comment by naumenko-sa** [comment]
Hi @pastaxingxin!

We have not run bcbio on WSL (Windows Subsystem for Linux).
We had similar symbolic links issues - check out https://github.com/bcbio/bcbio-nextgen/search?q=symbolic+links&type=issues
They are usually system-specific, not related to bcbio or conda.

Sorry, cannot be of much help here. Let us know how it runs on WSL if you overcome this issue!

Sergey
