### ISSUE TITLE
hello,RNA-seq single end input data WARNING

### ISSUE THREAD

**Issue by gongmeiyuan** [bcbio/bcbio-nextgen#3435]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
- OS name and version (`lsb_release -ds`):

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py -w template rnaseq-seqc.yaml seqc.csv seqc/input/*.gz
```
Your sample configuration file:
```
APR-246-1_R1_001.fastq.gz
APR-246-2_R1_001.fastq.gz
APR-246-3_R1_001.fastq.gz
MK-2206-1_R1_001.fastq.gz
MK-2206-2_R1_001.fastq.gz
MK-2206-3_R1_001.fastq.gz
MKT-077-1_R1_001.fastq.gz
MKT-077-2_R1_001.fastq.gz
MKT-077-3_R1_001.fastq.gz
NULL-1_R1_001.fastq.gz
NULL-2_R1_001.fastq.gz
NULL-3_R1_001.fastq.gz
Ori-1_R1_001.fastq.gz
Ori-2_R1_001.fastq.gz
Ori-3_R1_001.fastq.gz
```

**Observed behavior**
Error message or bcbio output:
```
WARNING: Added minimal sample information: metadata not found for 1, ['1.txt']
WARNING: Added minimal sample information: metadata not found for APR-246, ['APR-246-1_R1_001.fastq.gz', 'APR-246-2_R1_001.fastq.gz', 'APR-246-3_R1_001.fastq.gz']
WARNING: Added minimal sample information: metadata not found for MK-2206, ['MK-2206-1_R1_001.fastq.gz', 'MK-2206-2_R1_001.fastq.gz', 'MK-2206-3_R1_001.fastq.gz']
WARNING: Added minimal sample information: metadata not found for MKT-077, ['MKT-077-1_R1_001.fastq.gz', 'MKT-077-2_R1_001.fastq.gz', 'MKT-077-3_R1_001.fastq.gz']
WARNING: Added minimal sample information: metadata not found for NULL, ['NULL-1_R1_001.fastq.gz', 'NULL-2_R1_001.fastq.gz', 'NULL-3_R1_001.fastq.gz']
WARNING: Added minimal sample information: metadata not found for Ori, ['Ori-1_R1_001.fastq.gz', 'Ori-2_R1_001.fastq.gz', 'Ori-3_R1_001.fastq.gz']
WARNING: sample not found NULL-2
WARNING: sample not found NULL-3
WARNING: sample not found Ori-2
WARNING: sample not found Ori-3
WARNING: sample not found APR-246-2
WARNING: sample not found APR-246-3
WARNING: sample not found MK-2206-2
WARNING: sample not found MK-2206-3
WARNING: sample not found MKT-077-2
WARNING: sample not found MKT-077-3
```

**Expected behavior**
seqc.csv  was used is 

samplename,description,category
NULL-1,control_rep1,Control
NULL-2,control_rep2,Control
NULL-3,control_rep3,Control
Ori-1,Ori-treat_rep1,Treat
Ori-2,Ori-treat_rep2,Treat
Ori-3,Ori-treat_rep3,Treat
APR-246-1,APR-treat_rep1,Treat
APR-246-2,APR-treat_rep2,Treat
APR-246-3,APR-treat_rep3,Treat
MK-2206-1,MK-treat_rep1,Treat
MK-2206-2,MK-treat_rep2,Treat
MK-2206-3,MK-treat_rep3,Treat
MKT-077-1,MKT-treat_rep1,Treat
MKT-077-2,MKT-treat_rep2,Treat
MKT-077-3,MKT-treat_rep3,Treat

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
I'm a new user of linux & bcbio-nextgen ，I am very sorry if I have caused you trouble.

**Comment by roryk** [comment]
Hi @gongmeiyuan,

So sorry for the delay in responding. The sample configuration file needs to have the FASTQ name for R1 for each sample. Could you change the first column under "description" to that and retry?

**Comment by gongmeiyuan** [comment]
I am very happy to receive your letter and I am sorry to trouble you. My English is not good, please forgive me if I offend you accidentally


I will try it again ,thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bcbio/bcbio-nextgen"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月17日(星期三) 凌晨3:32
收件人:&nbsp;"bcbio/bcbio-nextgen"<bcbio-nextgen@noreply.github.com&gt;;
抄送:&nbsp;"995834426"<995834426@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bcbio/bcbio-nextgen] hello,RNA-seq single end input data WARNING (#3435)





 
Hi @gongmeiyuan,
 
So sorry for the delay in responding. The sample configuration file needs to have the FASTQ name for R1 for each sample. Could you change the first column under "description" to that and retry?

**Comment by roryk** [comment]
No worries @gongmeiyuan, your English is great. It is certainly a lot better than my Chinese!
