### ISSUE TITLE
vcf2db.py  fails after bcbio_nextgen.py upgrade -u development 

### ISSUE THREAD

**Issue by erinijapranckeviciene** [bcbio/bcbio-nextgen#3436]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
- 1.2.6
- OS name and version (`lsb_release -ds`):
Ubuntu 20.04.1 LTS

**To Reproduce**
Exact bcbio command you have used:
```
vcf2db.py -h
```
Your sample configuration file:
```
No sample configuration,  I checked to invoke a standalone program. For example vcfanno prints help.  
```

**Observed behavior**
Error message or bcbio output:
```
zmgkserv@zmgkserv-MS-7C59:~$ vcf2db.py -h
Traceback (most recent call last):
  File "/opt/bcbio/tools/bin/vcf2db.py", line 30, in <module>
    import cyvcf2
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "cyvcf2/cyvcf2.pyx", line 19, in init cyvcf2.cyvcf2
  File "__init__.pxd", line 1038, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

```

**Expected behavior**
help printed

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
NA

**Additional context**
I wished to create a gemini database from a standalone multisample vcf file. 

Thank you very much in advance for your time and looking into this!

**Comment by erinijapranckeviciene** [comment]
Hi,  just leaving a note for someone who might encounter the same issue. 
I solved it with upgrading numpy in the bcbio python2 environment. 

`conda activate python2`
`pip install numpy --upgrade`

Maybe this is not a right way to upgrade within bcbio and I will encounter other issues, but for now vcf2db.py it is working for me.

**Comment by roryk** [comment]
Hi Erin!

Sorry for missing this-- thank you so much for posting the solution. I'm not sure why numpy is getting downgraded in that environment, but your solution seems pretty reasonable to me. Let me know if you encounter problems and we can come up with a better solution.

**Comment by erinijapranckeviciene** [comment]
👍
