### ISSUE TITLE
Does bcbio resume a pipeline run from crash site?

### ISSUE THREAD

**Issue by DolapoA** [bcbio/bcbio-nextgen#3437]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): "CentOS Linux release 7.6.1810 (Core) "

**Question:**
I was running the tumour-normal pipeline for variant calling which crashed, I have resolved the issue, which was a missing file.
If I shoot off the pipeline command again, I'm worried it will overwrite what it's done so far by starting again.
Do I have to manually make a new config and start from the variant calling stage and on the sample that it crashed on?

**Comment by roryk** [comment]
Hi @DolapoA,

Nope, you should be all set just fixing the issue and re-kicking it off, assuming other samples don't depend on the file or previous steps for the sample with the missing file didn't depend on the file. Hope that helps get you moving, if you can be more specific about what was the file that was missing we can answer the question better.

**Comment by DolapoA** [comment]
I was running a tumour-normal process. It was a sample that was missing a tumour counterpart and I think it crashed on mutect2.

**Comment by roryk** [comment]
Thanks! Definitely should be all set to just rerun then.
