### ISSUE TITLE
Install: installer tries to download non-existing files from the 1000 genomes HTTP

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3443]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Debian GNU/Linux 10 (buster)

**To Reproduce**
Exact bcbio command you have used:
```
python3 bcbio_nextgen_install.py --tooldir /home/share/bcbio-tools /home/share/bcbio/ -u dev
elopment --isolate --genomes hg38 --aligners bowtie --aligners bwa --datatarget variation --datatarget vep
```

**Observed behavior**
Error message or bcbio output [Italian, but the meaning is clear:
```
Running GGD recipe: hg38 seq 1000g-20150219_1
--2021-03-04 15:42:41--  http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GR
Ch38_full_analysis_set_plus_decoy_hla.fa.fai
Risoluzione di ftp.1000genomes.ebi.ac.uk (ftp.1000genomes.ebi.ac.uk)... 193.62.193.140
Connessione a ftp.1000genomes.ebi.ac.uk (ftp.1000genomes.ebi.ac.uk)|193.62.193.140|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 404 Not Found
2021-03-04 15:42:41 ERRORE 404: Not Found.
```

It looks like the 1000 Genomes FTP had some changes: these files are available via FTP, but not via HTTP.

**Comment by naumenko-sa** [comment]
Hi @lbeltrame !

Thanks for catching this!
Could you please try again? (I've fixed HTTP>ftp)  in
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/seq.yaml

Sergey

**Comment by lbeltrame** [comment]
Looks like it's working, thanks.
