### ISSUE TITLE
MACS error in ATAC-Seq pipeline

### ISSUE THREAD

**Issue by sbdaxia** [bcbio/bcbio-nextgen#3447]
Hi!

Thank you so much for developing this amazing compilation of pipelines!

I recently started trying out the ATAC-Seq pipeline for data processing. However, I am running into an error that seems to be due to the pipeline itself.

I am using the example dataset ENCSR312LQX and ENCSR310MLB from the ENCODE project that were used in the bcbio documentation and followed the exact instruction.

However, I am running into the following error message. 

```
[2021-03-15T13:08Z] macs2 for hindbrain_rep2-NF
[2021-03-15T13:08Z] Traceback (most recent call last):
[2021-03-15T13:08Z]   File "/n/app/bcbio/dev/anaconda/bin/macs2", line 23, in <module>
[2021-03-15T13:08Z]     from MACS2.Constants import *
[2021-03-15T13:08Z] ModuleNotFoundError: No module named 'MACS2.Constants’
```
 
The alignment and post-alignment processing seemed to work well but MACS2 was not able to run. 

It seems like some other users of MAC2 have also run into the same issue:
[ImportError: No module named MACS2.Constants](https://github.com/macs3-project/MACS/issues/132)

Do you have any recommendation regarding how to resolve this issue in bcbio?

Thank you so much!

Best,
Bing

**Comment by naumenko-sa** [comment]
Hi Bing @sbdaxia !

Thanks for reporting and sorry about the issue!

This line of code:
```python
from MACS2.Constants import *
```
is not from bcbio but from macs2 script:
/n/app/bcbio/dev/anaconda/bin/macs2

I was able to successfully run the last commands from your projects on O2 with 50G RAM session.

```bash
/n/app/bcbio/dev/anaconda/bin/macs2 \
callpeak \
-t /path/to/atac-example/hindbrain_forebrain/work/align/forebrain_rep1/forebrain_rep1-sort-shifted_chrom-noMito.unique-noduplicates-NF.bam \
--nomodel  \
-f BAMPE \
-g 2730871774 \
-n forebrain_rep1-NF \
--bdg  \
--nolambda \
--keep-dup all 
```
and

```bash
/n/app/bcbio/dev/anaconda/bin/macs2 \
callpeak \
-t /path/to/atac-example/hindbrain_forebrain/work/align/forebrain_rep2/forebrain_rep2-sort-shifted_chrom-noMito.unique-noduplicates-NF.bam \
--nomodel  -f BAMPE -g 2730871774 -n forebrain_rep2-NF --bdg  --nolambda --keep-dup all
```

So, macs2 is working in bcbio O2 installation.

Could you please check that the bcbio MACS2 is the only MACS2 in your PATH?
```
$ which macs2
/n/app/bcbio/dev/anaconda/bin/macs2
echo $PATH
/n/app/bcbio/dev/anaconda/bin:/n/app/bcbio/tools/bin:
```

If that is the case, and you still getting the error, could you try to give bcbio and macs2 more RAM? 
You were running with 16 cores/ 80G RAM / 5G/core, can you try 8Cores/80G RAM/ 10G/core?

Sergey

**Comment by sbdaxia** [comment]
Thank you Sergey @naumenko-sa!

Joon from the HSPH core told me to add the following to my `.bashrc`file
```
unset PYTHONHOME
unset PYTHONPATH
```

and the following to my `.bash_profile` file:
```
# bcbio
export PATH=/n/app/bcbio/tools/bin:$PATH:$HOME
```

As of now, here are the results when I follow your instruction on O2 after loading `bcbio/latest` module:
```
$ which -a macs2
/n/app/bcbio/tools/bin/macs2
/n/app/bcbio/dev/anaconda/bin/macs2
/n/app/bcbio/tools/bin/macs2

$ echo $PATH
/n/app/bcbio/tools/bin:/n/app/bcbio/dev/anaconda/bin:/n/cluster/bin:/opt/singularity/bin:/n/app/bcbio/tools/bin:/n/cluster/bin:/opt/singularity/bin:/usr/local/rvm/gems/ruby-2.4.9/bin:/usr/local/rvm/gems/ruby-2.4.9@global/bin:/usr/local/rvm/rubies/ruby-2.4.9/bin:/n/cluster/bin:/opt/singularity/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/sbin:/home/bs218:/opt/ibutils/bin:/opt/dell/srvadmin/bin
```

Are these something of concern?

Thank you!

Best,
Bing

**Comment by sbdaxia** [comment]
@naumenko-sa 

Also for your reference, here is the full content of my `.bashrc`
```
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# Defines a new command, soar, for requesting an interactive compute shell
alias 'soar=srun -p interactive -t 0-12:00 -n 2 --mem=16G --pty /bin/bash'

# unsnet Python path for ATAC-Seq pipeline to use bcbio Python
unset PYTHONHOME
unset PYTHONPATH
```

And the full content of my `.bash_profile`
```
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

# PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

# bcbio
export PATH=/n/app/bcbio/tools/bin:$PATH:$HOME
```

Thank you!

**Comment by naumenko-sa** [comment]
The PATH is fine, please try the memory trick!
Sergey

**Comment by sbdaxia** [comment]
Ok perfect! I will starting running a job with the memory you recommended and will keep you posted!

Bing

**Comment by naumenko-sa** [comment]
It looks like it was because
/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/MACS2
dir had o = r-- permission, not o=r-x

thanks @yoonsquared for the idea!

**Comment by sbdaxia** [comment]
@naumenko-sa thank you so much! Now I can actually call `macs2 -h` and have it working!

Thanks for your advice on resolving this issue!

**Comment by sijiali-0107** [comment]
> @naumenko-sa thank you so much! Now I can actually call `macs2 -h` and have it working!
> 
> Thanks for your advice on resolving this issue!

Hi Bing.
Unfortunately I'm experiencing the same problem. Do you have any recommendation regarding how to resolve it ?

Thank you so much!

Best,
Sijia

**Comment by sijiali-0107** [comment]
> The solution I had was specific the HMS O2 cluster. Is this the cluster you are running you job on? If so, you can follow this comment in the thread:
> 
> [#3447 (comment)](https://github.com/bcbio/bcbio-nextgen/issues/3447#issuecomment-799908586)

/
/
/
