### ISSUE TITLE
Valid sample name improvement for RNA-seq

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3449]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Ubuntu 20.04.2 LTS

Minor issue, the sample name sanitizer should be improved to also handle dashes, which are considered illegal characters in R. I noticed this message pop up in a bcbio run:

```
10000-001 is not a valid R name, converting to X10000-001.
```

Technically, "X10000-001" is also not a valid name in R because of the hyphen. By default, the `make.names()` function in R convert hyphens to periods, but the current recommended best practice is to sanitize to underscores.

It may be a good idea to tweak this in the pipeline, so the sample name gets converted from "10000-001" to "X10000_001", to avoid any downstream issues in R.

Best,
Mike

**Comment by naumenko-sa** [comment]
Hi Mike!

Nice to hear from you - thanks for the suggestion!

We sanitize sample names for several types of projects (not for variant calling) here:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/pipeline/run_info.py#L956

It is an easy fix, but I doubt that many users would be happy with us automatically changing their sample names,
which are cross-referenced in sample tracking systems, work tracking systems, data analysis systems, etc. 

100 > X100 is a necessary evil for bulk RNA-seq (and we are not changing the name, we are just using an X prefix), 
but sample-01_ 20-01-01 => sample_01_20_01_01 could be too much of a change to bear. 
Imagine also users who re-process their samples.

I'd suggest fixing this downstream in R unless there is a massive outcry to fix sample names at the level of bcbio.

Sergey

**Comment by mjsteinbaugh** [comment]
Hi @naumenko-sa , I agree that we should attempt to avoid renaming sample names, and allow for (in my opinion, bad practice) edge cases such as "sample-01_ 20-01-01" in the bcbio output. Almost every FASTQ sample I get back from a sequencing vendor is formated along the lines of "10000_001_R1_001.fastq.gz", so I deal with this issue frequently.

Originally we added the "X" prefix to bulk RNA-seq sample names to avoid some downstream issues specifically in R, since samples starting with a number aren't syntactically valid. See the `make.names()` documentation for details on this. So in the event of a sample such as "10001" getting converted to "X10001", this works without issue in R. But sample names containing a hyphen (e.g. "sample-01_ 20-01-01") are *also* considered invalid in R, and can also produce some unexpected results in packages that rely on dependencies that change column and/or row names, including the tidyverse and potentially data.table as well.

So I'm wondering if maybe we should just revert the "X" prefix addition step in the main bcbio processing pipeline, but then enforce syntactically valid R naming conventions *specifically* in the internal R scripts, such as [`bcbio2se.R`](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/scripts/R/bcbio2se.R). What to consider as best practice here is tricky, as many users still load into R directly from the flat file matrices, and therefore these kind of naming issues will persistent in their downstream workflows without additional sanitization steps.

We take a similar approach in bcbioRNASeq and bcbioSingleCell using our [`makeNames()`](https://r.acidgenomics.com/packages/syntactic/reference/makeNames.html) function variant, which essentially calls the base `make.names()` function but returns with underscores instead of periods, which users generally prefer. Refer also to our [YAML parser code](https://github.com/hbc/bcbioBase/blob/master/R/internal-yaml.R#L144) defined in bcbioBase, that helps handle sample name processing inside the bcbio R packages.

I guess my point is that currently adding the "X" prefix sends a bit of a mixed message if we're still allowing hyphens in the sample names, and maybe we should just take this out to begin with?

Mike

**Comment by mjsteinbaugh** [comment]
This isn't a high priority, so safe to close
