### ISSUE TITLE
FilterMutectCalls: retaining the .filtering_stats.tsv file

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3455]
Hi Guys,

The newer versions of the FilterMutectCalls functions should produce a .filtering_stats.tsv file that contains further information on the filtering thresholds and scores for each variant, I can't seem to find this in the work directory. I assume this is not being retained by default?  I was wondering if there is a simple way to get the pipeline to retain this file ? I am happy to edit the code myself any tips would be much appreciated!

Thanks!

**Comment by naumenko-sa** [comment]
Hi Warren @waemm !

Great suggestion!
I don't see this file in the work/mutect2 for a T/N project.

I think the steps could be:
- make sure that the flag is on and the stats file is written: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/mutect2.py#L233 https://gatk.broadinstitute.org/hc/en-us/articles/360036856831-FilterMutectCalls#--filtering-stats
- mutect2 calls are parallelized, i.e. there are many vcf files, and there will be many filtering_stats files, we need to make sure the stats get merged in the end;
- uploader module is here: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/upload/__init__.py#L777

Sergey

**Comment by waemm** [comment]
Thank you Sergey, very helpful advice! I managed to get what i was looking for through some manual analyses but this will no doubt be helpful in future!
