### ISSUE TITLE
"Getting Started" page has an example of a yaml script that isn't parsable

### ISSUE THREAD

**Issue by david-a-siegel** [bcbio/bcbio-nextgen#3481]
I don't really know what I'm doing but I couldn't get things to run so I used this tool to check the yaml script: http://yaml-online-parser.appspot.com/

It looks like there are a couple of bugs in the getting started documentation:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/intro.html

Under "#4", the example YAML script has a couple of errors.  The first is that there should either be no dash in front of "files:", or there should be no space after the dash.  The second is that "genome_build" shouldn't be indented and the indentation is messed up lower down.

Cheers

**Comment by naumenko-sa** [comment]
thanks for catching this! It was a wrong indentation issue. I've fixed it.
