### ISSUE TITLE
RFE: Remove MuTect 2 requirement for a panel or a matched normal

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3488]
MuTect 2 *can* run in tumor-only mode: although it generates a lot of uninteresting calls, if you're focused on a handful of targets you can get away with it if you use some annotation-based filtering.

Right now you can't unless you comment out the code that raises a `ValueError` inside bcbio.

**Comment by naumenko-sa** [comment]
Hi @lbeltrame !

We are usually running it this way:
https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/somatic_tumor_only.yaml

SN
