### ISSUE TITLE
VM install (MacOS) Install bcbio-nextgen Syntax Error

### ISSUE THREAD

**Issue by johndhstead** [bcbio/bcbio-nextgen#3493]
Hello

I've been following installation instructions at
https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html
to create a virtual machine on MacOS. Execution of the following line...

python /vagrant/scripts/bcbio_nextgen_install.py ~/local/share/bcbio --tooldir=~/local --nodata

...generated the following error:

File "/vagrant/scripts/bcbio_nextgen_install.py", line 45
    print(f"Installing {conda_bin}")
                                  ^
SyntaxError: invalid syntax

Thanks to a much more experienced colleague, I was able to fix this by changing the script to python3 /vagrant......
(The default setting in the VM was for python 2)

Thanks!

**Comment by naumenko-sa** [comment]
Hi @johndhstead !
We have switched to python3  in the installer script.
Sergey

**Comment by johndhstead** [comment]
thanks!
