### ISSUE TITLE
unable to run bcbio-nextgen after installing on HPC using singularity container

### ISSUE THREAD

**Issue by iichelhadi** [bcbio/bcbio-nextgen#3498]
I get the following error when I try to run the pipeline:
has anyone encountered this issue before?
![bcbio-nextgen_error](https://user-images.githubusercontent.com/59079565/120962202-d99c0c00-c791-11eb-8660-e939f33cf503.png)

**Comment by naumenko-sa** [comment]
containers are not supported at the moment!

**Comment by amizeranschi** [comment]
Any plans to bring back support for containers? It could help a lot with reproducing older studies, given how it's not normally possible to install older versions of Bcbio and its dependencies.

**Comment by naumenko-sa** [comment]
Yes, containers is the obvious next big target after cleaning up conda envs and snpeff upgrade.
