### ISSUE TITLE
Update to the latest version of PureCN

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3500]
As far as I can see, bcbio uses 1.20.0, while 1.22.1 is out and on conda, and that fixes a few edge cases when handling intervals.

(ref: https://github.com/lima1/PureCN/commit/b740780ab9a84433a148f4def3571dcdf6b5e638)

**Comment by naumenko-sa** [comment]
Hi @lbeltrame !
Thanks for the heads up!

We are not pinning purecn in bcbio: 
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L268

A fresh 1.2.9a installation has received bioconductor-purecn 1.22.1 automatically.

I've updated the older installation with:
conda update -n r36 -c conda-forge -c bioconda bioconductor-purecn

SN

**Comment by naumenko-sa** [comment]
bcbio 1.2.9 receives purecn 2.0.1
