### ISSUE TITLE
Adding a new aligner

### ISSUE THREAD

**Issue by KBT59** [bcbio/bcbio-nextgen#3502]
I'd like to add a new aligner as an option in bcbio.  I have seen the various <aligner>.py scripts in ngsalign, I can easily make such a file, but where else must I make changes to make the aligner fully usable within bcbio?

**Comment by naumenko-sa** [comment]
Hi @KBT59 !

What kind of aligner are you going to add?

It depends on the pipeline, see for example:
https://github.com/bcbio/bcbio-nextgen/search?q=STAR
https://github.com/bcbio/bcbio-nextgen/search?q=bismark
https://github.com/bcbio/bcbio-nextgen/search?q=bwa

Also don't forget about installation and indices:
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/bwa.yaml

SN

**Comment by naumenko-sa** [comment]
closing. please feel free to re-open if you are working on that!
