### ISSUE TITLE
What exactly is "use_filtered" doing?

### ISSUE THREAD

**Issue by DolapoA** [bcbio/bcbio-nextgen#3503]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): "CentOS Linux release 7.6.1810 (Core) "

**Question:**
I just wanted to know what exactly the `use_filtered` is doing, is it allowing only PASS variants which have been filtered as pass within each variant caller?

**Comment by naumenko-sa** [comment]
Hi @DolapoA !

https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/ensemble.py#L78
By default, ensemble variant calling approach uses only PASS variants. 
With `use_filtered: true` you could use non-PASS variants as well.  

SN
