### ISSUE TITLE
Octopus does not update in base env

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3505]
Hi everyone!

Bcbio cannot install the latest version of Octopus (0.7.4) in base env. Remains with a really old version (0.6.3.b). 

When I try to install it in another env (eg. python3 bcbio env) I can see that conda correctly find the new version and can install this version in python3 env.

It would be awesome if I could also specify options like:

Error models
```
https://luntergroup.github.io/octopus/docs/guides/errorModels/
```
and 

Pretrained random forest models
```
https://luntergroup.github.io/octopus/docs/guides/filtering/forest
```

**Comment by mjsduncan** [comment]
i tried adding the latest version of octopus with --toolplus but couldn't get that to work and then tried linking the 0.7.4 binary in place of 0.6.3b but the --legacy flag is not recognized by 0.7.4 and halts the pipeline.

i'm too much of a python newbie to take the time to update the bcbio octopus installation & run recipes myself, but the octopus 0.7.4 install script can automatically download the the random forest models so adding them into the recipe should be straightforward.

i'm now in the middle of variant calling 25 germline exomes using an ensemble of octopus 0.6.3b, freebayes, and gatk-haplotype and am happy to share aggregate results and re-call with the 0.7.4 version of octopus to help tune the default settings if it will help with the updating process...

**Comment by naumenko-sa** [comment]
Octopus is updated in the latest dev:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L296
please check out

**Comment by naumenko-sa** [comment]
End of year cleaning - octopus is updated in bcbio 1.2.9. feel free to re-open if you see any issues.
