### ISSUE TITLE
RNA-seq: using current version of DEXSeq

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3509]
If I understand previous posts correctly, R is pinned to v3.5.1 in the default conda environment.
The r36 conda environment seems to be meant for tools that require a newer version of R. 

I tried installing `bioconductor-dexseq=1.38` into r36. However, DEXSeq cannot be found when installed in this environment. 
DEXSeq versions compatible with R 3.5.1 are not compatible with python3. 
```
multiprocessing: run_dexseq
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
DEXseq is not installed, skipping exon-level counting.
```

If I remove the r=3.5.1 requirement from the default environment, I can install `bioconductor-dexseq=1.38` and the analysis is completed, but `provenance.py` exits with error.

Any tips how I could use the current version of DEXSeq (1.38)?.
Thx
Ben

**Comment by naumenko-sa** [comment]
Thanks @gabeng !

I am working on the update. 
The solution is to update DEXSeq in r36 enviroment and then use it from there, not from the default:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/rnaseq/dexseq.py#L75

similarly how we are doing it for purecn.

SN

**Comment by gabeng** [comment]
Hi Sergey,

Would be great if you could make it work from the r36 environment.
TIA!
--
Ben

**Comment by naumenko-sa** [comment]
By the way, how did you manage to install bioconductor-dexseq=1.38?

In my bcbio instance:
```
# solves forever
conda install bioconductor-dexseq=1.38 -n r36 -c bioconda
# proposes to alter a lot of packages
mamba install bioconductor-dexseq=1.38 -n r36 -c bioconda
# installs 1.36
conda install bioconductor-dexseq -n r36 -c conda-forge -c bioconda
```

**Comment by gabeng** [comment]
I am using a `tools.yaml` tailored to my bulk rna-seq application, similar to this one:
https://github.com/bcbio/bcbio_docker/blob/19369dde53fe40e624b1086d19570b3024929567/packages/bcbio-rnaseq.yaml

```
bio_nextgen:
- atropos
- arriba;env=r36
- bcftools
- biobambam=2.0.87
- bioconductor-dexseq>=1.38;env=r36
- bioconductor-tximport;env=r36
- express
- fastqc>=0.11.8=1
- gffread
- goleft
- grabix
- hts-nim-tools
- htseq
- kallisto>=0.43.1
- mosdepth;env=htslib1.10
- multiqc
- multiqc-bcbio
- parallel
- picard
- pizzly
- pythonpy
- qualimap
- qsignature=0.1pre=4
- r-base
- r-wasabi
- r=3.5.1
- r-janitor;env=r36
- r-tidyverse;env=r36
- salmon
- sambamba
- samtools
- seqtk
- star
- stringtie
- subread
- xorg-libxt
channels:
- conda-forge
- bioconda
minimal:
- awscli
- bzip2
- ncurses
- nomkl
- readline
- ucsc-fatotwobit
```

**Comment by naumenko-sa** [comment]
The fresh installation gave me
`bioconductor-dexseq       1.38.0`

Please give it a try - I've submitted a fix.
Also, you'd need htseq in r36
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L86

**Comment by gabeng** [comment]
I can confirm it works. Thank you!
I noted that the rnaseq tools like `express`, `kallisto`, `stringtie`, `dexseq `etc. are not listed in the `programs.txt`. Not sure if the output in `programs.txt` is still maintained.

**Comment by naumenko-sa** [comment]
that is an easy fix @gabeng  - please check it out in the latest dev
