### ISSUE TITLE
Dup % column in MultiQC is reporting the wrong percentage of duplicated reads

### ISSUE THREAD

**Issue by sib-bcf** [bcbio/bcbio-nextgen#3522]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8  
- OS name and version (`lsb_release -ds`):

**To Reproduce**
The Dup % column in MultiQC reports the percentage of non-duplicated reads, instead of the duplicated ones
The bug is related to these issues:
https://github.com/bcbio/bcbio-nextgen/issues/3406
https://github.com/bcbio/bcbio-nextgen/issues/3029

The bug is in
https://github.com/bcbio/bcbio-nextgen/blob/69bc24d703d3a0166caabf833ddd9e514ff1d445/bcbio/qc/qualimap.py#L227

dup_count is counting the reads without the Duplicated SAM flag, instead of the Duplicated ones

dup_count = readstats.number_of_mapped_reads(data, dup_align_bam, keep_dups=False)
tot_count = readstats.number_of_mapped_reads(data, dup_align_bam, keep_dups=True)

Therefore
https://github.com/bcbio/bcbio-nextgen/blob/69bc24d703d3a0166caabf833ddd9e514ff1d445/bcbio/qc/qualimap.py#L238
should be
rate = 1 - dupes / total

**Comment by naumenko-sa** [comment]
Thanks for digging this out @sib-bcf ! Please give it a try!
