### ISSUE TITLE
Question - RNASeq tumour-normal data and variant calling

### ISSUE THREAD

**Issue by VictoriaPatten** [bcbio/bcbio-nextgen#3523]
Hi there, is there a specific pipeline for matched tumour-normal RNA-Seq data or should one follow the yaml file set up for the 'Somatic (cancer) variants' as per the documentation pages? I couldn't  seem to find a specific set-up under 'bulk-RNA-seq'.

Also, which tool would be best to use for variant calling? I read that vardict results might be uncertain and mutect2 not supported?

Thanks in advance.

**Comment by naumenko-sa** [comment]
Hi @VictoriaPatten!

Unfortunately, we don't have T/N calling for RNA-seq. Even N calling is tricky in RNA-seq (precision could be quite low especially for indels, gatk3.x is recommended over gatk4). You may try to call T and N separately with gatk or vardict and then subtract the variants as the first approximation. 

Sergey

**Comment by VictoriaPatten** [comment]
@naumenko-sa Thank you for the info and advice. Much appreciated.
