### ISSUE TITLE
SHA issue when installing bcbio

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3529]
** Problem Description **
Seek your assistance in this issue that I'm encountering while attempting to install bcbio. My installation command is:

python3 /XXX/install/bcbio_nextgen_install.py /XXX/apps/bcbio128/ --tooldir=/XXX/apps/bcbio128 --nodata

I have attempted around 5 times without success.
[bcbio.install.err.txt](https://github.com/bcbio/bcbio-nextgen/files/7176000/bcbio.install.err.txt)
[bcbio.install.err.log](https://github.com/bcbio/bcbio-nextgen/files/7176008/bcbio.install.err.log)

**Observed behavior**
Error message or bcbio output:
```
--2021-09-16 09:55:04--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2021-09-16 09:55:04--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 54.251.140.56
Connecting to codeload.github.com (codeload.github.com)|54.251.140.56|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 1.93M
  3072K ........ ........ ........ .......                    12.3M=1.7s

2021-09-16 09:55:07 (2.89 MB/s) - written to stdout [5191933]

ERROR   File not valid: SHA256 sum doesn't match expectation "/scratch/users/astar/gis/simngl/apps/bcbio128/anaconda/pkgs/star-2.6.1d-h9ee0642_1.tar.bz2"
        Expected: 140624a4f214b327d3c3b4216bc467fbdcd610448e832c42863231a33b25e619
        Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        
ERROR   File not valid: SHA256 sum doesn't match expectation "/scratch/users/astar/gis/simngl/apps/bcbio128/anaconda/pkgs/oncofuse-1.1.1-0.tar.bz2"
        Expected: 9400edf8faf4d2ac5e35d6f5e4ffcda9b905b4fa1111072035b228769dc4fcd9
        Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        
ERROR   File not valid: SHA256 sum doesn't match expectation "/scratch/users/astar/gis/simngl/apps/bcbio128/anaconda/pkgs/fgbio-1.3.0-hdfd78af_2.tar.bz2"
        Expected: 68aa1094e4bce8756a27bdfe43cbc1afd525a74ec03d58683ceb70954c2ecc33
        Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        
```

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !

Thanks for reporting and sorry about the issues! 
It must be especially upsetting not being able to install STAR at A-STAR!

I just have installed it with no issues. I think in your case the old package cache interferes with the new installation.
For example, if you get the STAR package from conda at 
https://anaconda.org/bioconda/star/2.6.1d/download/linux-64/star-2.6.1d-h9ee0642_1.tar.bz2
its sha256 is 140624a4f214b327d3c3b4216bc467fbdcd610448e832c42863231a33b25e619
which is what conda expects in your case. But somehow it finds a package (in the old cache) with sha256 of
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.

I'd try to remove any links to another conda installation:
- rename ~/.condarc  to ~/.condarc.save
- rename ~/.conda/environments.txt to ~/.conda/environments.txt.save
- make sure you unset the conda enviroment variables: CONDA_EXE, CONDA_PREFIX, $CONDA_PYTHON_EXE
- export PYTHONPATH=
- make sure PATH don't have references to the old conda
- export PYTHONNOUSERSITE=True - avoids adding ~/.local to PYTHONPATH

Another idea is to clean conda caches:
https://docs.conda.io/projects/conda/en/latest/commands/clean.html

SN

**Comment by gis-nlsim** [comment]
Thank you for your reply. I'm still facing the same problem even after unsetting the environmental variables (please see attached error.txt file)

This is actually a completely new server, and I have just gotten my account and there is no condo installed at all. I was actually hoping to use the condo installed by bcbio to be my condo setup for subsequent installations. 

I'm wondering if this might be caused by downloading issues due to the network? If so, is there anyway I can download in another server, transfer to the one I'm setting up, and kick off the installation from the point AFTER the download? Thanks in advance.



> Hi @gis-nlsim 
[error.txt](https://github.com/bcbio/bcbio-nextgen/files/7188980/error.txt)
!
> 
> Thanks for reporting and sorry about the issues!
> It must be especially upsetting not being able to install STAR at A-STAR!
> 
> I just have installed it with no issues. I think in your case the old package cache interferes with the new installation.
> For example, if you get the STAR package from conda at
> https://anaconda.org/bioconda/star/2.6.1d/download/linux-64/star-2.6.1d-h9ee0642_1.tar.bz2
> its sha256 is 140624a4f214b327d3c3b4216bc467fbdcd610448e832c42863231a33b25e619
> which is what conda expects in your case. But somehow it finds a package (in the old cache) with sha256 of
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
> 
> I'd try to remove any links to another conda installation:
> 
> * rename ~/.condarc  to ~/.condarc.save
> * rename ~/.conda/environments.txt to ~/.conda/environments.txt.save
> * make sure you unset the conda enviroment variables: CONDA_EXE, CONDA_PREFIX, $CONDA_PYTHON_EXE
> * export PYTHONPATH=
> * make sure PATH don't have references to the old conda
> * export PYTHONNOUSERSITE=True - avoids adding ~/.local to PYTHONPATH
> 
> Another idea is to clean conda caches:
> https://docs.conda.io/projects/conda/en/latest/commands/clean.html
> 
> SN

**Comment by naumenko-sa** [comment]
maybe it is a proxy server cache issue, i.e. there is an older version of the file in the cache, and its getting fetched instead of the direct download? try switch off proxy / talk to network admins?

Unfortunately, installing on the other server and copying is not a good idea - there are some soft and hard-links created in the packages during the installation. These might get broken.

What is transferable is the VM. For example, people do AWS AMI instances with bcbio installations and clone them.
