### ISSUE TITLE
For UMI pipeline use 'UmiAwareMarkDuplicatesWithMateCigar' instead of bamsormadup

### ISSUE THREAD

**Issue by Admera2020** [bcbio/bcbio-nextgen#3532]
Hello Team, 

Thank you for the great pipelines and the comprehensive documentation.  I am interested in running a UMI pipeline for ctDNA. While reviewing the documentation ( As well within command logs ), I found out that duplicate reads are marked using "bamsormadup". Is the tool detects duplicate in UMI aware fashion ( I don't find particular information on GitHub page)? Alternatively,  would it be possible at all to switch the duplicate marking using UmiAwareMarkDuplicatesWithMateCigar from GATK/Picard? 

Thanks in advance,
Nihir

**Comment by naumenko-sa** [comment]
Hi Nihir!

We do use UMIs, single and Duplex (see https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/somatic-duplex-umi.yaml) for somatic variant detection.

The overall scheme is:
- raw reads are aligned;
- umi families are identified (fgbio);
- umi families are collapsed (fgbio);
- collapsed reads are aligned (from here the pipeline proceeds pretty much as non-umi data, including duplicate marking).

Could you please elaborate what would be UmiAwareMarkDuplicatesWithMateCigar in this scheme?

Sergey

**Comment by Admera2020** [comment]
Hello Sergey,

Thanks for your response, 
The "UmiAwareMarkDuplicatesWithMateCigar " tries to leverage UMI information along with Start and end position while detecting duplicates. So at first glance, it looked promising but I do see your point that once the consensus is created from UMI families via GroupReadsByUmi the marked duplicate can be the same as any non-umi data. 

Best, 
Nihir
