### ISSUE TITLE
Incorrect Ensembl release version for hg38

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3536]
The "92" Ensembl release number of hg38 (see cloudbiolinux `transcripts.yaml` file) is currently incorrect. It was built against Ensembl 94, which is noted in the YAML comments. I just double checked the reference against Ensembl 94 annotations and they match up correctly but not against 92.

Relevant file:
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/transcripts.yaml

See related cloudbiolinux issue:
https://github.com/chapmanb/cloudbiolinux/issues/385

**Comment by naumenko-sa** [comment]
Hi @mjsteinbaugh !
Thanks for catching this! It says in the header that it was built from v94. 
92 I think was a typo in the filename that spread out.
If I change _92 to _94 in the yaml now, that will trigger the reinstall for many people, 
and the reinstall will be with the same annotation.
Anyway, we are going to replace it with a newer one, so hopefully 92 will be gone soon.
SN
