### ISSUE TITLE
bcbio jobs killed but main job remains

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3537]
Greetings,

I am encountering issues similar to that raised in issue 741, but it doesn't seem to be due to memory issues
https://github.com/bcbio/bcbio-nextgen/issues/741

The job scheduler is SLURM
Each sbatch seem to spawn off 2 more jobs with names that start with "bcbio"
I requested for 2 nodes, each with 16GB memory for each sbatch
After a while, the 2 bcbio jobs disappeared, leaving the main job running.

The bcbio-ipcontroller and bcbio-ipengine are attached.
ipcontroller seems to indicate that the job was cancelled about 15 minutes after the scheduler was started.
ipengine seem to indicate that the jobs were killed while running GenerateSVCandidates.

[bcbio-ipcontroller.err.8_4294967294.log](https://github.com/bcbio/bcbio-nextgen/files/7282448/bcbio-ipcontroller.err.8_4294967294.log)

My sbatch script is as follows:
#!/bin/bash
#SBATCH -J A646-T-S61-09102017-E
#SBATCH -p compute
#SBATCH -n 2
#SBATCH -N 2
#SBATCH -t 7-00:00:00 # running time of 7 days
#SBATCH --mem 15500 # memory request of a little less than 16GB
#SBATCH -o /shared/lung-qseq/runs/ITH-Exome/GIS-qSEQ-ITH-Exome-A646-T-S61-09102017-E/bcbio_work/z-GIS-qSEQ-ITH-Exome-A646-T-S61-09102017-E.o
#SBATCH -e /shared/lung-qseq/runs/ITH-Exome/GIS-qSEQ-ITH-Exome-A646-T-S61-09102017-E/bcbio_work/z-GIS-qSEQ-ITH-Exome-A646-T-S61-09102017-E.e

cd /shared/lung-qseq/runs/ITH-Exome/GIS-qSEQ-ITH-Exome-A646-T-S61-09102017-E/bcbio_work

/shared/apps/bcbio/anaconda/bin/bcbio_nextgen.py ../config.yaml  -t ipython -s slurm -q compute -n 2 --timeout 60
[bcbio-ipengine.err.9_1.log](https://github.com/bcbio/bcbio-nextgen/files/7282446/bcbio-ipengine.err.9_1.log)

I have encountered bcbio jobs disappearing at different stages of the process while running on SLURM. Sometimes they were killed while running alignment, sometimes they were killed after running alignment.

To date, I have not been able to successfully complete a single bcbio run for DNASeq, although I was able to complete HLA optityping and RNASeq processes. 

My apologies but I am not familiar with HPC and job scheduler. Seek your assistance and advice in this matter please. Thank you.

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !

It might be also related to #3537.

A complex bcbio run with ipython is for large batches mainly (when you run >10 RNA-seq, >10WES samples). Otherwise, for a single sample or a couple of samples, it might be a good idea to run simply in one-node (multicore) mode:

```bash
bcbio_nextgen.py ../config.yaml -n 2
```

In that case you may control memory/CPU usage in a simpler way.
-n 2 specifies using 2 cores on the machine. Total memory `#SBATCH --mem 15500`

The resource usage by particular processes is regulated by `bcbio/galaxy/system/yaml`, for example
```
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 4G
    cores: 16
    jvm_opts: ["-Xms750m", "-Xmx3500m"]
  # Can also set program specific options
  # gatk:
  #   jvm_opts: ["-Xms500m", "-Xmx3500m"]
```

So, first, you may want to make sure your project is running end2end in one sample configuration, and only after a success to scale up with ipython.

In the ipython mode, there is 3 kinds of jobs:
- the main job, which you start, does not need much resources (1cpu, 10G)
- the controller job (you may bump memory with -r conmem=20 ) /20G for a controller job
- the engine jobs (total cpu is controlled by -n and their size and amount by -n value / by specifications in `bcbio/galaxy/system/yaml` - you requested 400 cores, samtools uses 4 cores, you get ~100 samtools workers (roughly, it is more complex in practice - see the code); also note walltime for engine jobs controlled by -q (parition) and -r.

In your example above you have not specified a walltime for them, so the engines just could have been killed by the scheduler after the default walltime passed.

See more info at:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#ipython-parallel

Sn

**Comment by gis-nlsim** [comment]
Thanks Dr. Naumenko for the explanation.

Background
I’m quite unfamiliar with HPC systems, but I do have to run large batches of RNA and WES/WGS samples.
Our previous system uses PBS (qsub), but now I have to set up a bcbio pipeline on AWS with SLURM job scheduler.


Seek your advice for the following please.

Given that I have a cluster with compute nodes of 16GB memory, and 4 vCPUs (AWS M5A.2XLARGE)
Would this be the correct settings:

For DNASeq:
#SBATCH -J job-name
#SBATCH -p compute
#SBATCH -n 1 # 1 task
#SBATCH -N 1 # 1 node
#SBATCH -t 7-00:00:00 # running time of 7 days
#SBATCH --mem 15600 # memory request of a little less than 16GB
#SBATCH -o <logfile>
#SBATCH -e <logfile>

cd <path> to <bcbio_workdir>
/shared/apps/bcbio/anaconda/bin/bcbio_nextgen.py ../config.yaml  -t ipython -s slurm -q compute -n 16 --timeout 60 -r "timelimit=7-00:00:00"


And for RNASeq (to use a total memory of 64GB):
#SBATCH -J job-name
#SBATCH -p compute
#SBATCH -n 4 # 4 task
#SBATCH -N 4 # 4 node
#SBATCH -t 7-00:00:00 # running time of 7 days
#SBATCH --mem 15600 # memory request of a little less than 16GB
#SBATCH -o <logfile>
#SBATCH -e <logfile>

cd <path> to <bcbio_workdir>
/shared/apps/bcbio/anaconda/bin/bcbio_nextgen.py ../config.yaml  -t ipython -s slurm -q compute -n 16 --timeout 60 -r "timelimit=7-00:00:00"

My apologies; I realize it’s not specifically bcbio related, but I’ve been struggling with this for a long time. Would appreciate any advice on this. Thank you.

Regards,
N L Sim











Sim Ngak Leng
Senior Bioinformatics Specialist
Computational & Systems Biology 3

Genome Institute of Singapore
Agency for Science, Technology and Research
60 Biopolis Street, Genome, #03-01, Singapore 138672
D +65 6808 8013  T +65 6808 8000  E ***@***.******@***.***>  W www.a-star.edu.sg/gis<http://www.a-star.edu.sg/gis>
[a-star-logo]

**Comment by gis-nlsim** [comment]
My apologies, please ignore my previous email. I managed to get the jobs started, and have closed this issue on github. Thank you for all your help.

Regards,
N L Sim

From: SIM Ngak Leng ***@***.***>
Date: Friday, 8 October 2021 at 10:54
To: bcbio/bcbio-nextgen ***@***.***>, bcbio/bcbio-nextgen ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [bcbio/bcbio-nextgen] bcbio jobs killed but main job remains (#3537)

Thanks Dr. Naumenko for the explanation.

Background
I’m quite unfamiliar with HPC systems, but I do have to run large batches of RNA and WES/WGS samples.
Our previous system uses PBS (qsub), but now I have to set up a bcbio pipeline on AWS with SLURM job scheduler.


Seek your advice for the following please.

Given that I have a cluster with compute nodes of 16GB memory, and 4 vCPUs (AWS M5A.2XLARGE)
Would this be the correct settings:

For DNASeq:
#SBATCH -J job-name
#SBATCH -p compute
#SBATCH -n 1 # 1 task
#SBATCH -N 1 # 1 node
#SBATCH -t 7-00:00:00 # running time of 7 days
#SBATCH --mem 15600 # memory request of a little less than 16GB
#SBATCH -o <logfile>
#SBATCH -e <logfile>

cd <path> to <bcbio_workdir>
/shared/apps/bcbio/anaconda/bin/bcbio_nextgen.py ../config.yaml  -t ipython -s slurm -q compute -n 16 --timeout 60 -r "timelimit=7-00:00:00"


And for RNASeq (to use a total memory of 64GB):
#SBATCH -J job-name
#SBATCH -p compute
#SBATCH -n 4 # 4 task
#SBATCH -N 4 # 4 node
#SBATCH -t 7-00:00:00 # running time of 7 days
#SBATCH --mem 15600 # memory request of a little less than 16GB
#SBATCH -o <logfile>
#SBATCH -e <logfile>

cd <path> to <bcbio_workdir>
/shared/apps/bcbio/anaconda/bin/bcbio_nextgen.py ../config.yaml  -t ipython -s slurm -q compute -n 16 --timeout 60 -r "timelimit=7-00:00:00"

My apologies; I realize it’s not specifically bcbio related, but I’ve been struggling with this for a long time. Would appreciate any advice on this. Thank you.

Regards,
N L Sim











Sim Ngak Leng
Senior Bioinformatics Specialist
Computational & Systems Biology 3

Genome Institute of Singapore
Agency for Science, Technology and Research
60 Biopolis Street, Genome, #03-01, Singapore 138672
D +65 6808 8013  T +65 6808 8000  E ***@***.******@***.***>  W www.a-star.edu.sg/gis<http://www.a-star.edu.sg/gis>
[a-star-logo]
