### ISSUE TITLE
Building a PoN with PureCN hard-requires GATK 3

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3541]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8
- OS name and version (`lsb_release -ds`): Debian 10

**To Reproduce**

The code explicitly *wants* GATK 3:

https://github.com/bcbio/bcbio-nextgen/blob/5cfc02b5974d19908702fa21e6d2f7a50455b44c/bcbio/variation/vcfutils.py#L336

However there is no check for it, and if the command isn't found, the error condition is not triggered and the pipeline errors because it can't find the assembled PoN file.

**Expected behavior**

GATK 3 should *not* be required.

**Comment by naumenko-sa** [comment]
Hi @lbeltrame !

We install gatk3 by default via conda: 
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L281
and it is present usually in `bcbio/tools/bin/gatk3`. It does not need to be manually downloaded and registered as before.
So we may safely assume gatk3 is onboard. We tried combining variants with gatk4 - it was more complicated at the time, so we chose gatk3.

Sergey
