### ISSUE TITLE
'ipyparallel.apps.launcher' has no attribute 'BatchClusterAppMixin'

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3549]
Hi,

I installed bcbio on an AWS with (SLURM job scheduler) on 28th October 2021. When I tried to submit the job, I encountered this error. Not sure if this is an AWS issue, or is it from bcbio, because the error appears to be from a python file in the bcbio installation. Seek your help in this please. Thank you.

[2021-10-29T06:58Z] ip-10-255-0-189: System YAML configuration: /apps/bcbio128/galaxy/bcbio_system.yaml.
[2021-10-29T06:58Z] ip-10-255-0-189: Locale set to C.UTF-8.
[2021-10-29T06:58Z] ip-10-255-0-189: Resource requests: bwa, sambamba, samtools; memory: 4.00, 4.00, 4.00; cores: 16, 16, 16
[2021-10-29T06:58Z] ip-10-255-0-189: Configuring 4 jobs to run, using 2 cores each with 9.33359375g of memory reserved for each job
/apps/bcbio128/anaconda/lib/python3.7/site-packages/ipyparallel/apps/ipcontrollerapp.py:3: UserWarning: ipyparallel.apps.ipcontrollerapp is deprecated in ipyparallel 7. Use ipyparallel.controller
  warnings.warn(f"{__name__} is deprecated in ipyparallel 7. Use ipyparallel.controller")
Traceback (most recent call last):
  File "/apps/bcbio128/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/apps/bcbio128/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 58, in run_main
    fc_dir, run_info_yaml)
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 125, in variant2pipeline
    multiplier=alignprep.parallel_multiplier(samples)) as run_parallel:
  File "/apps/bcbio128/anaconda/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/distributed/prun.py", line 54, in start
    from bcbio.distributed import ipython
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/bcbio/distributed/ipython.py", line 31, in <module>
    from cluster_helper import cluster as ipython_cluster
  File "/apps/bcbio128/anaconda/lib/python3.7/site-packages/cluster_helper/cluster.py", line 443, in <module>
    class BcbioSLURMEngineSetLauncher(SLURMLauncher, launcher.BatchClusterAppMixin):
AttributeError: module 'ipyparallel.apps.launcher' has no attribute 'BatchClusterAppMixin'

**Comment by gis-nlsim** [comment]
I just tried on a new bcbio installation on a separate server (non-AWS), and I'm getting the same issue as well. Seek your assistance in this please. Thank you.

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !

Thanks for reporting and sorry about the issue! I am also facing it and fixing it right away.
It is because of the latest update in cloudbiolinux where I upgraded to python3.7 (https://github.com/chapmanb/cloudbiolinux/pull/387): , and python packages also got upgraded, which became incompatible with ipython-cluster-helper (https://github.com/roryk/ipython-cluster-helper).

For now, I've fixed it this way:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L164

and I also attempted to re-write ipython-cluster-helper to use ipyparallel 7x, but it is a bigger effort.

Please try updating `bcbio_nextgen.py upgrade -u development` and run ipython project again.

Sergey

**Comment by gis-nlsim** [comment]
Thank you Dr Naumenko, I’ll update and try again.


Regards,
Sim Ngak Leng
Senior Bioinformatics Specialist
Computational & Systems Biology 3

Genome Institute of Singapore
Agency for Science, Technology and Research
60 Biopolis Street, Genome, #03-01, Singapore 138672
D +65 6808 8013  T +65 6808 8000  E ***@***.******@***.***>  W www.a-star.edu.sg/gis<http://www.a-star.edu.sg/gis>
[a-star-logo]

**Comment by dauss75** [comment]
encountered the same problem and updating to dev. Hope the stable version includes the fix.

**Comment by dauss75** [comment]
Hi Sergey,
Do I update the ipyparallel version in manifest/python-packages.yaml and then update with `bcbio_nextgen.py upgrade -u development`?  I updated without changing any, but the error didn't get resolved.

Thanks, Segun

**Comment by naumenko-sa** [comment]
Hi @dauss75 !

Are you upgrading the old installation or working on a fresh one?

To get the latest bcbio you would need to re-install the conda envs and tools
- https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html#creating-a-separate-bcbio-installation
- link the genomes
- and upgrade to the latest code.

Sergey

**Comment by dauss75** [comment]
That was a fresh installation. OK.  I will give it another try. thanks

**Comment by naumenko-sa** [comment]
what is your output of:

```
mamba list ipython
mamba list traitlets
mamba list ipyparallel
```

**Comment by dauss75** [comment]
Thanks for the follow-up.

mamba list ipython
# Name                    Version                   Build  Channel
ipython                   7.16.1           py36he448a4c_2    conda-forge
ipython-cluster-helper    0.6.4              pyh864c0ab_1    bioconda
ipython_genutils          0.2.0                      py_1    conda-forge

mamba list traitlets
# Name                    Version                   Build  Channel
traitlets                 4.3.3              pyhd8ed1ab_2    conda-forge

mamba list ipyparallel
# Name                    Version                   Build  Channel
ipyparallel               7.1.0              pyhd8ed1ab_0    conda-forge

**Comment by naumenko-sa** [comment]
Could you please try
`mamba install ipython=7.29.0 ipython-cluster-helper=0.6.4=py_0 ipyparallel=6.3.0`
and re-run the ipython project?

Are you sure you are on python3.7? (your ipython version is py36)
what is your 
```
$ which python
$ python --version
```

**Comment by dauss75** [comment]
You are right. It's python3.6. Didn't pay attention if it's 3.7, but should I get 3.7 instead?

**Comment by naumenko-sa** [comment]
That means you are still using the old installation, not the fresh one. The fresh one installs python37
https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/bcbio_nextgen_install.py#L30

**Comment by dauss75** [comment]
Sorry. I must be confused.  There was no bcbio installed in the machine that I meant it's fresh one.  I will get this right and give another try. Thanks for the help!

**Comment by naumenko-sa** [comment]
Probably, you have used the old installer script?

Try
```
rm bcbio_nextgen_install.py
wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python3 bcbio_nextgen_install.py [bcbio_path] --tooldir=[tools_path]/tools --nodata --mamba
```

**Comment by dauss75** [comment]
thank you. working on it.  will keep you posted!

**Comment by dauss75** [comment]
it's working. thanks again for all your help!
