### ISSUE TITLE
Questions - Does bcbio convert bams to fastq then map?

### ISSUE THREAD

**Issue by VictoriaPatten** [bcbio/bcbio-nextgen#3558]
I have paired T/N cancer  .bam files that were mapped with GRCh37/hg19.
In the setup config file, if I specify **aligner: bwa** and **genome_build: hg38** ... When running the script will bcbio first convert the .bam files back to fastq files and then map with hg38?
TIA

**Comment by naumenko-sa** [comment]
Hi @VictoriaPatten !

Yes!

When `aligner` is set, bcbio is converting bam2fastq and trying to align. If `aligner: false` bcbio is trying to use the bam as is. Sometimes `bam_clean: picard` or  `bam_clean: fixrg` help to fix the bam. When running on the different reference realignment is necessary.

Sergey

**Comment by VictoriaPatten** [comment]
Hi @naumenko-sa
Thank you! This is very helpful.
