### ISSUE TITLE
Question: UMI handling in bcbio

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#3566]
Hi,

Bcbio can handle UMI's in the fastq header e.g.
```
@A00785:324:H5GN2DMXY:1:1101:11125:1063:TCGAGTGTG 2:N:0:ATGACGTC+CTTCCTTC
```
by using `umi: fastq_name`.

I'm trying to understand what happens exactly to get the UMI from the fastq header into the `RX`tag in the aligned bam. Could you please elaborate?

Thanks
Matthias

**Comment by naumenko-sa** [comment]
Hi @matthdsm !

Just for the reference, there is an open dataset with UMI's to synchronize the discussion:
https://github.com/bcbio/bcbio_validation_workflows/blob/master/somatic-lowfreq/prepare_inputs/smcounter2/prepare_data.sh

Usually, we work with fastqs having UMI or CELL in the header:

```
@M04362:253:000000000-BD2B6:1:1103:10823:2980:UMI_AGCGGGGTCGGT/1
GCCAAGAGTTACGGGATTATTGAAACCTCAGCCAAGACCAGACAGGTATGGTACAGCTTTCAGCATTTGTGCAAGAGTTTGCATCAGTTGATTAACTCTGGTAGAGATGTGATCCATATTCATATTCTTTGTTGTTATGCATTTTTTTCAT
+
BBBBBBFFFFFFGGGEEGGGGGHHHHHHHHHHHHHHHHHHHHGHHGBDGHHBGHHHHHHHHHFHHHHHHHGHGHFHHHGHHGHHHHHHHHGHHHHHHHHHHGFHHHGFHHHHFFHHFHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGHHH
@M04362:253:000000000-BD2B6:1:1109:26261:20513:UMI_TGTGCCCTGGGG/1
GCCAAGAGTTACGGGATTCCATTCATTGAAACCTCAGCCAAGACCAGACAGGTATGGTACAGCTTTCAGCATTTGTGCAAGAGTTTGCATCAGTTGATTAACTCTGGTAGAGATGTGATCCATATTCTTTGTTGTTATGCATTTTTTTCAT
+
>ABBAAFFFFFFGGGGCGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHGHHGHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHGHHGHHHHHHHHHHHHGHHGHHHHHHHHHHHGGHHH

```

Then the reads are aligned with bwa (UMI is in the read name), and UMIs are lifted to the bam tags with umis:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/internals.html#somatic-tumor-only-variant-calling-pipeline-with-umis-step-by-step
https://github.com/vals/umis/blob/master/umis/umis.py#L1222

Sergey

**Comment by matthdsm** [comment]
Hi Sergey,

Thanks for the thorough explanation!

Matthias
