### ISSUE TITLE
How install genome data to smb disk?

### ISSUE THREAD

**Issue by VikArz02** [bcbio/bcbio-nextgen#3596]
- bcbio version (`bcbio_nextgen.py --version`):
- 1.2.9
- OS name and version (`lsb_release -ds`):
- Ubuntu 20.04 

Hello!
I have smb disk /mnt/lapd and I want to install genome data to this disk. How can I specify the path?

I try this one:
`bcbio_nextgen.py upgrade -u skip --cores 20 --tooldir ~/Soft/bcbio/tools --tools --genomes hg38 --aligners hisat2 --datatarget variation`

but i have this message:
`tar: cloudbiolinux-master/ggd-recipes/BDGP6/gtf.yaml: Cannot utime: Operation not permitted` and etc

**Comment by naumenko-sa** [comment]
Hi @VikArz02 !

bcbio is simply trying to untar the file in the mounted partition.. Make sure you can do it from the command line, i.e. your mount options allow that.

Sorry - I have not configured samba in a while, I am not sure about the particular mount options.

Sergey

**Comment by VikArz02** [comment]
Thank you! So, I will talk with my colleagues about it.
