### ISSUE TITLE
RNASeq STAR index building taking a long time

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3597]
Hi,
I am installing bcbio v1.2.9 on a fresh cluster. The server I'm installing on is an AWS M5A.2xLarge with 32GB RAM and 8vCPUs.
When installing the genome, the STAR indexing appears to take a very long time; it's been indexing since 18th December 2021, and as of writing (23rd December 2021), it is still indexing. 

I am not running anything other than installing the genome.

May I know if this has anything to do with the new bcbio v1.2.9?

I have successfully installed bcbio with genome as recently as 1 month ago on a machine with the same specifications without any problems, but that was bcbio v1.2.8.

Attached is the LOG file for your reference.

Top shows STAR running with 100% CPU

top - 01:54:25 up 4 days, 20:42,  1 user,  load average: 1.00, 1.00, 1.00
Tasks: 241 total,   2 running, 173 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.6 us,  0.2 sy,  0.0 ni, 87.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32294864 total,   908992 free, 20943828 used, 10442044 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 10893884 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                  12242 ubuntu    20   0 19.026g 0.019t   2032 R 100.0 61.8   6928:18 STAR                                                                                                                                                                     17233 ubuntu    20   0   42384   4012   3232 R   6.7  0.0   0:00.01 top                                                                                                                                                                          1 root      20   0  225828   8404   5504 S   0.0  0.0   0:10.08 systemd                                                                                                                                                                      2 root      20   0       0      0      0 S   0.0  0.0   0:00.06 kthreadd                                                                                                                                                                     4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:0H                                                                                                                                                                 6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_wq                                                                                                                                                                 7 root      20   0       0      0      0 S   0.0  0.0   0:01.20 ksoftirqd/0                                                                                                                                                                  8 root      20   0       0      0      0 I   0.0  0.0   0:52.48 rcu_sched                                                                                                                                                                    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh                                                                                                                                                                      10 root      rt   0       0      0      0 S   0.0  0.0   0:00.07 migration/0                                                                                                                                                                 11 root      rt   0       0      0      0 S   0.0  0.0   0:00.79 watchdog/0                                                                                                                                                                  12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0                                                                                                                                                                     13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1                                                                                                                                                                   

[Log.out.log](https://github.com/bcbio/bcbio-nextgen/files/7766158/Log.out.log)

**Comment by naumenko-sa** [comment]
no, it should not take this long. I've installed hg38/STAR recently, it built in a couple of hours (50G RAM/1CPU). Have you tried to restart or to built an index from the command line?
