### ISSUE TITLE
samblaster exit with status 1

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3598]
Hi,

I installed bcbio v129 on an AWS cluster, and tested with a set of fastq files that were previously successfully processed in another HPC (with bcbio v107). For some reason, I encountered the following samblaster issue, and I'm wondering if this has anything to do with memory issues? Seeking your advice on this, thank you.

```
#----------------------------------------------
samblaster: unable to allocate hash table.
samblaster: Exiting early, the following stats are for processing preceeding the error
samblaster: Output     1564621 discordant read pairs to /dev/fd/62
samblaster: Output      174862 split reads to /dev/fd/63
samblaster:
samblaster: Pair Type        Type_ID_Count   %Type/All_IDs Dup_ID_Count  %Dups/Type_ID_Count  %Dups/All_Dups  %Dups/All_IDs
samblaster: ---------------------------------------------------------------------------------------------------------------
samblaster: Both Unmapped           16719         0.162              0           0.000             0.000          0.000
samblaster: Orphan/Singleton        25196         0.243            947           3.759             0.254          0.009
samblaster: Both Mapped          10306078        99.595         371940           3.609            99.746          3.594
samblaster: Total                10347993       100.000         372887           3.603           100.000          3.603
samblaster:
samblaster: Marked      372887 of   10347993 (3.603%) total read ids as duplicates using 177700k memory in 1M2S(62.407S) CPU seconds and 2H17M14S(8234S) wall time.
samblaster: Premature exit (return code 1).
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
[bam_sort_core] merging from 0 files and 2 in-memory blocks...
' returned non-zero exit status 1
```

My AWS cluster consists of R5A.xLARGE nodes (4 cpus, 32 GB per node)

I set bcbio_system.yaml to
  default:
    memory: 8G
    cores: 2

My sbatch command requests for 1 node (-N 1), 30GB per node (--mem), and for bcbio, I asked for -n 4, 

```bash
sbatch \
-J W-job  \
-p compute \
-N 1 \
-t 10-00:00:00 \
--mem=30G \
-o /shared/test/W-test/bcbio_work/test.o \
-e /shared/test/W-test/bcbio_work/test.e \
--wrap="bcbio_nextgen.py ../config.yaml -t ipython -s slurm -q compute -n 4 --timeout 6000"
```

From what I understand, -n 4 workers with maximum of 2 cores gives me 2 jobs each having 8GB, for a total of 16GB for the bcbio run?

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !
What is your yaml file?

`-n 4` means how much cores you request, not workers (engines). engines = 4 (from -n) / 2 (from bcbio_system.yaml)  = 2.
So your workers are 2 cores / 16G RAM.

With updated versions, tools might become more memory greedy. our default in the yaml is 16cores + 4G/Core, i.e. 16 cores + 64G RAM.

You might want to use all RAM available on 32G nodes
```bash
memory: 16G
cores: 2
```
or 
```
memory: 8G
cores: 4
```

**Comment by gis-nlsim** [comment]
Thank you, I'll increase the number of cores and try again.
