### ISSUE TITLE
Installation Error when updating

### ISSUE THREAD

**Issue by j5jun** [bcbio/bcbio-nextgen#3600]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): Version 1.2.9
- OS name and version (`lsb_release -ds`): macOS Monterey (Version 12.0.1)

**To Reproduce**
Exact bcbio command you have used:
```
python3 bcbio_nextgen_install.py /Users/alpha/bcbio --tooldir=/Users/alpha/bcbio/tools --nodata
```

Your yaml configuration file:
```
There is no file in the config directory of the installation directory (bcbio)
```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 304, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 55, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/alpha/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/Users/alpha/bcbio/tools']' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
Hi @j5jun !

You need a Linux Server/Cluster to install bcbio. Bcbio is useless on a laptop and not working on MacOS.

Sergey

**Comment by j5jun** [comment]
Thank you :)

**Comment by naumenko-sa** [comment]
Ha-ha, sorry for disappointing you. You can develop bcbio under macOS for sure - just clone the git repo.
For any real NGS data analysis you would need reference files, which currently for Hsapiens/hg38 are 81G (reference + bwa + rnaseq + STAR) . The NGS datasets (input data) depending on a projects are 10G - 1T. The intermediate work files in the pipeline are from 10th of GB to Terabytes. and the RAM/Cores requirement - it is good to have at least 20Cores/50G RAM. Sometimes it is hundreds of cores for real world analyses. It can't be done on a MacBook :)
