### ISSUE TITLE
Error in Install STAR index

### ISSUE THREAD

**Issue by TingtingSsl2** [bcbio/bcbio-nextgen#3606]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9a
- OS name and version (`lsb_release -ds`): HMS O2 server

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py upgrade -u skip --genomes hg38 --aligners star --cores 10
```

Your yaml configuration file:
```

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

PermissionError: [Errno 13] Permission denied: '/n/shared_db/bcbio/biodata/genomes/Hsapiens/hg38/txtmp'

**Comment by naumenko-sa** [comment]
Hi @TingtingSsl2 !

You can't install in this folder without having permissions. 
STAR index is already installed - you can just use it.

bcbio1.2.9:
. ./n/app/bcbio/1.2.9/.bcbio_profile

bcbio1.2.9a:
`ml bcbio/latest`

Sergey
