### ISSUE TITLE
Peddy fails with gvcf data

### ISSUE THREAD

**Issue by HudoGriz** [bcbio/bcbio-nextgen#3616]
Hi,

I encountered a similar issue to https://github.com/bcbio/bcbio-nextgen/issues/3506
`peddy` fails when running `tools_on: gvcf`. I repeated the run on the same data without `tools_on: gvcf` and with `jointcaller: gatk-haplotype-joint`, without specified bulk name (so that it only jointcalls on that sample). Both times `peddy` successfully finished.
My goal is to obtain `gvcf` data with a `peddy` analysis, to be latter used in custom downstream pipelines. 

Any ideas on solving the problem?
Thanks!

**Version info**
- bcbio version: 1.2.9
- OS name and version: Ubuntu 18.04.5 LTS

**To Reproduce**
Exact bcbio command I have used
```
bcbio_nextgen.py ../config/GVCF_analysis.yaml -n 20
```
My yaml configuration file:
```
details:
- algorithm:
    aligner: bwa
    archive: cram-lossless
    recalibrate: gatk
    variant_regions: /data/xgen-exome-research-panel-v2-targets-GRCh37-50-flanking.bed
    variantcaller:
    - gatk-haplotype
    tools_on:
    - gvcf

  analysis: variant2
  description: data-wgs
  files:
  - /data/wgs_fastq/data_R1.fastq.gz
  - /data/wgs_fastq/data_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: data_wgs
    phenotype: unknown
    sex: unknown

fc_name: GVCF_analysis
upload:
  dir: ../final_gvcf
```
bcbio-nextgen.log
```
[2022-02-09T14:40Z] multiprocessing: run_peddy
[2022-02-09T14:40Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/user/BCBIO/bcbio_dir/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/user/BCBIO/bcbio_dir/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export LC_ALL=C.UTF-8 && export LANG=C.UTF-8 &&  /home/user/BCBIO/bcbio_dir/anaconda/bin/peddy -p 10  --plot --prefix /data/GVCF_analysis/work/bcbiotx/tmpx4n_kp8v/data_wgs /data/GVCF_analysis/work/gatk-haplotype/data_wgs-effects-annotated-nomissingalt-filterSNP-filterINDEL.vcf.gz /data/GVCF_analysis/work/gatk-haplotype/data_wgs-effects-annotated-nomissingalt-filterSNP-filterINDEL.ped 2> /data/GVCF_analysis/work/bcbiotx/tmpx4n_kp8v/run-stderr.log
' returned non-zero exit status 1.
[2022-02-09T14:40Z] Skipping peddy because no variants overlap with checks: GVCF_analysis_wgs
```

**Comment by naumenko-sa** [comment]
Hi @HudoGriz !

Thanks for reporting and sorry about the issue!

It finished ok for me with gvcf on and peddy with bcbio 1.2.9, peddy 0.4.8.

Could you please make sure that you are running the 1.2.9 bcbio? Because in the trace there is python3.6. bcbio1.2.9 has python3.7...

Sergey

**Comment by HudoGriz** [comment]
Hi @naumenko-sa !
The fix works fine.

Much obliged,

Blaž
