### ISSUE TITLE
Symlinks for samtools are not created for a fresh installation

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3625]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9 (development)
- OS name and version (`lsb_release -ds`): Ubuntu 18.04.6 LTS

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen_install.py /usr/local/share/bcbio-nextgen --isolate --minimize-disk --nodata -u development --revision master
/usr/local/share/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py upgrade --isolate --tooldir=/usr/local --tools --toolconf packages-conda.yaml
```
`packages-conda.yaml` is the current file from `Cloudbiolinux`.

Installation completes without error. However, there are no symlinks in `/usr/local/bin` for tools included in `samtools` like `samtools` itself or `bgzip`. Symlinks for all other tools exist, as far as I can see. `/usr/local/share/bcbio-nextgen/anaconda/bin/samtools` exists.
Executing `bcbio_nextgen.py upgrade` again does not help.

Any hints what could be wrong?

**Comment by naumenko-sa** [comment]
Hi @gabeng !

Thanks for reporting!

I suspect you might have another samtools in the system. What is your:

```bash
which -a samtools
```

Also, why do you install it in two steps instead of
```bash
python3 bcbio_nextgen_install.py [bcbio_path] --tooldir=[bcbio_path]/tools --nodata --mamba
```

Sergey
