### ISSUE TITLE
bcftools symbol lookup error (after bcbio v1.2.9 installation)

### ISSUE THREAD

**Issue by prasundutta87** [bcbio/bcbio-nextgen#3632]
Hi,

I successfully installed bcbio-nextgen v1.2.9 yesterday. On checking samtools version, I got this error:

`samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

I updated samtools using ` mamba update samtools` and the error was gone and the software ran.

However, after the update, bcftools started getting this error:

`bcftools: symbol lookup error: /mnt/e1000/home/u027/u027/pdutta/bcbio-nextgen/bcbio_data/anaconda/bin/../lib/libgsl.so.25: undefined symbol: cblas_ctrmv`

Can somenoe help me with this issue? Updating bcftools using mamba didn't help as I got 'All requested packages already installed' message.

Regards,
Prasun

**Comment by prasundutta87** [comment]
Updating bcftools in specific environments solved this error. Manual updating/re-installation is required. Not sure, if this should be tested in the bcbio-nextgen installation itself somehow.

**Comment by amizeranschi** [comment]
For the record, I opened a very similar issue here: https://github.com/bcbio/bcbio-nextgen/issues/3557 some time ago, and ran into the same problem again just recently. 

Manually updating Samtools fixed things for me as well, but it would be nice to have a recent version of Samtools / Bcftools pinned by default in Conda, as part of the bcbio install.

**Comment by mjsteinbaugh** [comment]
Hi @prasundutta87 , thanks for posting regarding this issue. I can reproduce it on my machine, and am looking into a fix.

**Comment by jamesdalg** [comment]
Still an issue. If anyone knows how to go about fixing it, please feel free to post.

**Comment by mjsteinbaugh** [comment]
Argh OK I'll try to see if I can reproduce this -- thanks for the update @jamesdalg 

There's probably something going on with openssl1 vs. openssl3 flipping in the conda recipe

**Comment by mjsteinbaugh** [comment]
@jamesdalg I just reinstalled bcbio and am checking this out today

**Comment by caladov** [comment]
Hello! I'm still encountering the same issue with bcftools when installing it with conda. 
bcftools: symbol lookup error: /usr/lib/libgsl.so.25: undefined symbol: cblas_ctrmv

**Comment by mjsteinbaugh** [comment]
@caladov Unfortunately not sure this is going to get fixed, see [discontinuation notice](https://github.com/bcbio/bcbio-nextgen/issues/3749)

**Comment by caladov** [comment]
@mjsteinbaugh Thank you for the reply! I was able to go around the issue by downgrading bcftools to 1.10.2 and gsl to 2.5 in a separate environment. Also thank you for all the support in making this project available.
