### ISSUE TITLE
What is the option command of bowtie2 in the ATAC seq alignment?

### ISSUE THREAD

**Issue by panic0918** [bcbio/bcbio-nextgen#3634]
It's been a while since I posted a question.
Thank you for your kind response to my previous question.
Thanks to you, I was doing my research well.

I'm currently doing an atac seq analysis.
I did a great job with bcbio, but I had to align myself for detailed analysis

I created file **_DAY0_RX2KO_rep1_2000X_sorted.bam_** with the following code.
`bowtie2 -p 25 -t -x ./mm10 
-1 ../../atac-bcbio/fastq/DAY0_RX2KO_rep1_R1.fastq
-2 ../../atac-bcbio/fastq/DAY0_RX2KO_rep1_R2.fastq
-S DAY0_RX2KO_rep1_2000X.sam 
--very-sensitive-local -X 2000`
`samtools sort DAY0_RX2KO_rep1_2000X.sam -o DAY0_RX2KO_rep1_2000X_sorted.bam`

Subsequently, the result of dividing based on insert size is as follows.

![image](https://user-images.githubusercontent.com/95567530/159210463-a84164e3-575d-4652-9ead-b734203abb81.png)

As you can see, there was no value corresponding to Open Region (100>).

But When using bcbio output of Work/align/~/DAY0_RX2KO_rep1_sort.bam
When I used it, I found out that Open region has values as follows.

![image](https://user-images.githubusercontent.com/95567530/159210902-85ab5fb5-cd61-4e09-a3c6-daeee78043ed.png)

Could you please let me know the option command for bowtie2 when analyzing atac-seq in bcbio?

Please answer whenever you have time.
Thank you always. :)

**Comment by amizeranschi** [comment]
Hi!

You can see a list of all the commands that bcbio ran in the log file `bcbio-nextgen-commands.log`. You can find this in the main directory with results, usually called something like `.../final/2022-MM-DD_your_analysis`.

**Comment by panic0918** [comment]
thank you!!!!!! :)
