### ISSUE TITLE
404 Error during bcbio installation of human genome.

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3638]
I'm attempting to install the Human Genomes GRCh37 and hg38. There appears to be a few issues causing it the break; the latest one I received is a 404 not found reply when bcbio installer attempted to download  snpEff_v5_0_GRCh37.75.zip.

subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v5_0_GRCh37.75.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip']' returned non-zero exit stat\
us 8.

I tried running the wget command manually:

```bash
bash-4.4$ wget --no-check-certificate -c -O snpEff_v5_0_GRCh37.75.zip http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
--2022-03-26 19:21:28--  http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-26 19:21:29 ERROR 404: Not Found.
```

Seek your assistance in this matter urgently, as we need to have bcbio up and running on a new HPC cluster before the old cluster goes out of commission. Thank you.

The more detailed error is as follows

Saving to: ‘validation/giab-NA24695/truth_regions.bed’

validation/giab-NA24695/truth_regions.bed                  100%[========================================================================================================================================>]  24.88M  6.82MB/s    in 3.6s

2022-03-25 21:21:33 (6.82 MB/s) - ‘validation/giab-NA24695/truth_regions.bed’ saved [26092317/26092317]

Updating GRCh37 genome resources configuration
Updating hg38 genome resources configuration
Installing snpEff database GRCh37.75 in /scratch/users/astar/gis/simngl/apps/bcbio/genomes/Hsapiens/GRCh37/snpeff
--2022-03-25 21:21:36--  http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-25 21:21:40 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/scratch/users/astar/gis/simngl/apps/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/scratch/users/astar/gis/simngl/apps/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/scratch/users/astar/gis/simngl/apps/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    _upgrade_snpeff_data(galaxy_home, args, remotes)
  File "/scratch/users/astar/gis/simngl/apps/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 439, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "--no-check-certificate", "-c", "-O", dl_file, dl_url])
  File "/scratch/users/astar/gis/simngl/apps/bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v5_0_GRCh37.75.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip']' returned non-zero exit stat\
us 8.
bash-4.4$ wget --no-check-certificate -c -O snpEff_v5_0_GRCh37.75.zip http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
--2022-03-26 19:21:28--  http://downloads.sourceforge.net/project/snpeff/databases/v5_0/snpEff_v5_0_GRCh37.75.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-26 19:21:29 ERROR 404: Not Found.

**Comment by naumenko-sa** [comment]
HI @gis-nlsim !

Snpeff moved from sourceforge to Microsoft Azure.

You need to switch to bcbio1.2.9/snpeff5.0.

Sergey

**Comment by gis-nlsim** [comment]
Hi,

This is actually part of the bcbio installation process, the SNPEff download path appears to be hard-coded into some shell script that was downloaded during the installation? I’m not sure it can be fixed from my end.

Also, I was using the latest bcbio_nextgen_install.py downloaded just before running the installation, so it is the v1.2.9 version.

Sim Ngak Leng

**Comment by naumenko-sa** [comment]
Yes, it is in bcbio (note windows.net rather than sourceforge):
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/install.py#L38

Have you installed with `--nodata` first?

What is your `bcbio_nextgen.py --version`

**Comment by gis-nlsim** [comment]
I have installed with –nodata first, then I tried to install genomes and got this error.

The bcbio_nextgen.py is v1.2.9

Sim Ngak Leng
Senior Bioinformatics Specialist
Computational & Systems Biology 3

Genome Institute of Singapore
Agency for Science, Technology and Research
60 Biopolis Street, Genome, #03-01, Singapore 138672
D +65 6808 8013  T +65 6808 8000  E ***@***.******@***.***>  W www.a-star.edu.sg/gis<http://www.a-star.edu.sg/gis>
[a-star-logo]

**Comment by naumenko-sa** [comment]
#3639
