### ISSUE TITLE
Does bcbio allow min_allele_frequency < 1 ?

### ISSUE THREAD

**Issue by hanaecarrie** [bcbio/bcbio-nextgen#3643]
Dear authors,

Does bcbio allow somatic variant calling with min_allele_frequency below 1 (that is to say VAF threshold is set to 1% or 0.01)?
I tried with I tried 0.00000001 as I am interested in ultra low allele frequencies but it broke due to this parameter.
What is the range of acceptable min_allele_frequency values?

OS version: CentOS 6.5
bcbio version: 1.0.9a0
somatic callers used: ['freebayes', 'mutect2', 'strelka2', 'vardict', 'varscan']

Many thanks in advance for your help,
Kind regards,
Hanaé

**Comment by naumenko-sa** [comment]
Hi @hanaecarrie 

1) I'd suggest to to upgrade from 1.0.9a to 1.2.9
2) Detecting low VAF variants requires high coverage, for example we tried duplex UMI:
https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/somatic-duplex-umi.yaml

to go beyond 1%, also specify `use_lowfreq_filter: false`

Also, I am not sure what happens with freebayes etc, we tried with mutect2 and vardict.

Sergey
