### ISSUE TITLE
Unable to install bcbio (bcbio_nextgen.py not found)

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3651]
[install.error.txt](https://github.com/bcbio/bcbio-nextgen/files/8713780/install.error.txt)
We tried installing bcbio on 17th May 2022 (SGT), and encountered this issue:

FileNotFoundError: [Errno 2] No such file or directory: '/rfs-storageservice/GIS/Projects/LOCCG/apps/bcbio/v129/anaconda/bin/bcbio_nextgen.py': '/rfs-storageservice/GIS/Projects/LOCCG/apps/bcbio/v129/anaconda/bin/bcbio_nextgen.py'

**Comment by kokyriakidis** [comment]
I am not able to install it with conda. Please try this:

```
wget https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python3 bcbio_nextgen_install.py [bcbio_path] --tooldir=[bcbio_tools_path] --nodata --mamba
```

**Comment by naumenko-sa** [comment]
this: https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/bcbio_nextgen_install.py#L135
should help with such issues.
