### ISSUE TITLE
Somatic tumor only variant calling pipeline with UMIs step by step

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3655]
Hi!

In the "Somatic tumor only variant calling pipeline with UMIs step by step" found in this link (https://bcbio-nextgen.readthedocs.io/en/latest/contents/internals.html) the first command does some kind of trimming to reads.

```
trimming 2p from reads: trim_ends: [2,0,2,0], indexing:
```

Is this mandatory? Why do we have to trim 2bp from the reads? (I have already trimmed adapter sequences)

**Comment by gabeng** [comment]
This depends on the UMI design. Most manufacturers introduce a variable number of bases between UMI and insert or they have UMI of different length. To deal with that you extract a fixed number of bases for the UMI and trim the rest.

**Comment by kokyriakidis** [comment]
So, it is better to not do any adapter trimming, and then follow what bcbio does with 2p trimming?

**Comment by gabeng** [comment]
Without knowing your particular UMI setup, I would generally say that you should (in this order)
* De-multiplex and trim sequencing adapters from the end of reads,
* Extract UMIs,
* Trim remaining bases from the start of reads, if this is necessary.

If you are using off-the-shelf UMI, the manufacturer should provide suitable instructions (IDT, Agilent, Twist do).

**Comment by gabeng** [comment]
If you have the time, you could process one sample and perform alignment (no consensus or variant calling). Review the BAM file in IGV. If you see 2 soft-clipped bases at the start of many reads, you should trim them. Otherwise it is not necessary.
