### ISSUE TITLE
How to get the runtime of each caller when I use multiple caller in yaml file?

### ISSUE THREAD

**Issue by LeiHaoa** [bcbio/bcbio-nextgen#3660]
Hi,
Is there any way to get the runtime of each caller when I use multiple callers in the YAML file? 
for example, I use the following caller `somatic: [strelka2, mutect2, vardict]` to call somatic variants, but I can not get the runtime of each caller through log files, is there any suggestions to get the runtime??

**Comment by naumenko-sa** [comment]
Hi @LeiHaoa !

To benchmark, you may run one sample and parse the bcbio-nextgen-commands.log.
You will see when the particular tool starts, and when the next command starts. This way you may calculate the run time.

Sergey

**Comment by LeiHaoa** [comment]
Hi,
Got it! Thanks for your reply!

Liehaoa
