### ISSUE TITLE
Is STAR-fusion currently available in the pipeline? 

### ISSUE THREAD

**Issue by EvaPang2022** [bcbio/bcbio-nextgen#3665]
Hi, may I know whether STAR-fusion is included in the current pileline to call gene fusion?

FYI:
STRA-fusion:
paper: https://europepmc.org/article/ppr/ppr32296
github: https://github.com/STAR-Fusion/STAR-Fusion/wiki

Thank you in advance!

**Comment by naumenko-sa** [comment]
Hi @EvaPang2022 !
Sorry  - I missed your question.
We don't support STAR-fusion, fusion detection in bcbio is available with [oncofuse, pizzly, ericscript, arriba] with arriba being the most tested and validated.
SN

**Comment by EvaPang2022** [comment]
Well noted. Thank you.
