### ISSUE TITLE
curl: (60) SSL certificate problem when downloading bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz

### ISSUE THREAD

**Issue by eylenth** [bcbio/bcbio-nextgen#3676]
Hello

I try to update to bcbio software version to 1.2.9, but it fails every time when it tries to download the bioconductor-genomeinfodbdata package
I have tried this now several times, but it keeps failing at this error message.

I have also tried to define the SSL_CERT_FILE environment variable before executing the bcbio_nextgen_install.py script, but it keeps failing 
I have also tried to configure the proxy environment and the capath environment in $HOME/.curlrc, but it didn't work either.

when I try to download the https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz files with wget or a curl interactively, then it is working fine.

So I guess that the environment variables/configuration  of SSL and/or the Proxy server of my server environment is "gone" for some reason. 
I'm not sure, but I think when the post-link script starts, it does not inherits the proxy/SSL environment of my server configuration.

can the post-link script be modified somewhere where I can configure the correct proxy and ssl settings?
Or is there another solution ?

**Version info**
bcbio 1.2.9

**To Reproduce**

```
export SSL_CERT_FILE=/etc/key.pem && python
scripts/bcbio_nextgen_install.py --tooldir=/tools/eb/software/bcbio/1.2.9-foss-2020b --aligners bwa --aligners star --nodata --isolate -u stable /data/prod/Tools/bcbio/1.2.9
```

**Log files (could be found in work/log)**
it is a snippet of the log file where it is failing
```
========================= Novoalign information ===========================================
Novoalign is installed. Documentation installed in
/data/prod/Tools/bcbio/1.2.9/anaconda/share/doc/novoalign

Commercial use requires a license; contact sales@novocraft.com.
License also adds multi-threading and other features.
Once you have a license file, run novoalign-license-register to install it.

Licensing information from Novocraft website:
--------------------------------------------------------------------------------------------
======================== End of novoalign information ======================================

done
ERROR conda.core.link:_execute(732): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.7-r41hdfd78af_2'.
Rolling back transaction: ...working... done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.7-r41hdfd78af_2
location of failed script: /data/prod/Tools/bcbio/1.2.9/anaconda/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 74c82f26111062a9ceb3c5331088cd56:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by naumenko-sa** [comment]
Hi @eylenth !

It just passed for me (I ran with with `--mamba`)

```
+ bioconductor-genomeinfodb                                   1.30.0  r41hdfd78af_0           bioconda/noarch             4MB
+ bioconductor-genomeinfodbdata                                1.2.7  r41hdfd78af_2           bioconda/noarch             8kB
```
The error seems not related to solving, but rather the way curl checks certificates (use EU servers to get the certificate?)
I could only suggest:

```echo insecure >> $HOME/.curlrc```

SN

**Comment by gabeng** [comment]
Hi @naumenko-sa,

just curious: did you do a fresh install from scratch? I am still stuck with this error: https://github.com/bcbio/bcbio-nextgen/issues/3661#issuecomment-1219290902

**Comment by eylenth** [comment]
hi @naumenko-sa 
Suddenly it worked for some reason.

I did not even performed the following command:
`echo insecure >> $HOME/.curlrc`

So I guess that the certificate was working at a certain point. Or I did a refresh of my current terminal session at the last successful install.

if someone else is ever having the same issue,
you can try the following options
`echo cacert=/etc/key.pem >> $HOME/.curlrc`
or add the following variable before you install the latest version of bcbio:
`export SSL_CERT_FILE=/etc/key.pem`
