### ISSUE TITLE
Empty tmpcbl/ref-transcripts.gtf created while building mm39 genome

### ISSUE THREAD

**Issue by daisysdan** [bcbio/bcbio-nextgen#3694]
Version info
- bcbio version: 1.2.8
- OS name and version: Linux Cluster CentOS7

To reproduce:

- Download mm39 reference genome files from GENCODE:
```
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M31/gencode.vM31.chr_patch_hapl_scaff.basic.annotation.gtf.gz
gunzip gencode.vM31.chr_patch_hapl_scaff.basic.annotation.gtf.gz

wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M31/gencode.vM31.chr_patch_hapl_scaff.basic.annotation.gff3.gz
gunzip gencode.vM31.chr_patch_hapl_scaff.basic.annotation.gff3.gz
```
Both the gtf and gff3 files contain require fields: exon, transcript_id and gene_id

- Exact bcbio command used to set up the custom genome: 
I tried using either the gtf or the gff files but both didn't work and gave the same error 

```
#!/bin/bash
#BSUB -q bigmem
#BSUB -n 4
#BSUB -R rusage[mem=64000]
#BSUB -o out.%J
#BSUB -N

module load python

/data/klengellab/tools/bcbio/anaconda/bin/bcbio_setup_genome.py -c 4 -f /data/klengellab/tools/bcbio/genomes/Mmusculus/mm39_2023/gencode.vM31.transcripts.fa -g /data/klengellab/tools/bcbio/genomes/Mmusculus/mm39_2023/gencode.vM31.chr_patch_hapl_scaff.basic.annotation.gtf -n Mmusculus -b mm39 -i star --buildversion Ensembl_108

/data/klengellab/tools/bcbio/anaconda/bin/bcbio_setup_genome.py -c 4 -f /data/klengellab/tools/bcbio/genomes/Mmusculus/mm39_2023/gencode.vM31.transcripts.fa --gff3 -g /data/klengellab/tools/bcbio/genomes/Mmusculus/mm39_2023/gencode.vM31.basic.annotation.gff3 -n Mmusculus -b mm39 -i star --buildversion Ensembl_108 
```

Log File:

[out.txt](https://github.com/bcbio/bcbio-nextgen/files/10486000/out.txt)

It seems like the ref-transcripts.gtf in the tmpcbl directory is just empty. 

Thank you so much for all your help in advance and I really appreciate it!

**Comment by naumenko-sa** [comment]
Hi @daisysdan !

With -g you need to pass a **genome** reference, not transcriptome.fa.

SN

**Comment by naumenko-sa** [comment]
Please feel free to re-open if that is not solving the case.
