### ISSUE TITLE
Unable to install on M1 mac 

### ISSUE THREAD

**Issue by alasfar-lina** [bcbio/bcbio-nextgen#3696]
Hello everyone
I have been trying to install bcbio on an M1-Mac Studio 
I used the basic installation commands and it did not work.
I have midified the python script to install the latest miniconda with arm64  I got the following error:

PackagesNotFoundError: The following packages are not available from current channels:

  - libgcc-ng 

Although I have gcc installed via  homebrew. 

Is there a way to pypass that ?
Thank you in advance

**Comment by naumenko-sa** [comment]
@alasfar-lina !
Unfortunately, bcbio is not working on Mac.
SN
