### ISSUE TITLE
subset of chromosome regions bed file

### ISSUE THREAD

**Issue by TSL-RamKrishna** [bcbio/bcbio-nextgen#3697]
Firstly, apology for dropping a question as issue here. I am seeking an answer from any expert.

My question is, how is the subset of chromosome region defined or identified that is used in the mutect2 command with -L option.
For example: -L work/mutect2/chr9/30003371_3000337105-**chr9_32407110_61191660**-regions.bed

Here, in the subset of bed region, the start is 32407110 and end is 61191660. How is the start and end selected?

There are many regions in the bed file, the first region starts at 32407110 and the last region ends at 61191660.
I am trying to figure out how this bed file is produced as well.
Any help here, please?

**Comment by naumenko-sa** [comment]
Hi @TSL-RamKrishna !

These regions are formed for parallelization (and could be processed in parallel with bcbio/ipython).
Please look here: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/bam/callable.py#L182

SN
