### ISSUE TITLE
Question on parrallelization with callable regions

### ISSUE THREAD

**Issue by nvnieuwk** [bcbio/bcbio-nextgen#3704]
Hi, awesome work here!

I have a small question (mainly out of curiosity). Why don't you filter out the `NO_COVERAGE` regions from the BED file created with mosdepth? Seems a bit redundant to also pass these regions to the parallelization. I am probably missing something here (hence my question here). 

Thanks in advance!
-Nicolas

**Comment by naumenko-sa** [comment]
Hi @nvnieuwk !
I think NO_COVERAGE regions are used to create parallelization breakpoints (to make sure a parallelization breakpoint is not created in the middle of a CALLABLE region).
SN

**Comment by nvnieuwk** [comment]
Hi thanks for the answer! It's clear to me now :)
