### ISSUE TITLE
IBM Power9 (ppc64le) support

### ISSUE THREAD

**Issue by um-pdavila** [bcbio/bcbio-nextgen#3708]
Hi,

Has anyone been able to install bcbio-nextgen on IBM ppc64le?  Is there an installation script compatible with ppc64le?

I'm trying to modify the bcbio_nextgen_install.py to run on ppc64le.

Best,
Pedro

**Comment by naumenko-sa** [comment]
I have not heard that anybody ran it on Power9, 
however, if the server is Linux based, why not?
