### ISSUE TITLE
Scalpel InDel calling support

### ISSUE THREAD

**Issue by mjafin** [bcbio/bcbio-nextgen#428]
Looks like vcf support has been added to Scalpel recently: http://sourceforge.net/p/scalpel/code/ci/master/tree/

Opening this ticket while I'm looking into testing Scalpel and integrating it within bcbio, bear with me

**Comment by zhaoming159753** [comment]
Hi mjafin ,
I have a question? could scalpel use for WGS(not WES) of Tumor/Normal sample detecting somatic indels?

**Comment by chapmanb** [comment]
It does work on WGS samples as well, but is quite slow since Scalpel is primarily developed on exomes. We use it in cases where we need indels, but also recommend the VarDict variant caller included in bcbio which calls indels as well as Scalpel and runs much quicker. Hope this helps.

**Comment by lbeltrame** [comment]
In data venerdì 9 ottobre 2015 07:32:12 CEST, Brad Chapman ha scritto:

> also recommend the VarDict variant caller included in bcbio which calls
> indels as well as Scalpel and runs much quicker. Hope this helps.

Can it be used as indelcaller? I found scalpel to be extremely slow even for 
targeted sequencing analyses.

**Comment by chapmanb** [comment]
Luca -- VarDict calls indels as part of the standard calling. You don't use it as `indelcaller` but as its own separate caller under `variantcaller`. We're still working on a post with the latest filtering results, but it does as well at MuTect on SNPs and equivalent or better than Scalpel on Indels so is a good all around caller:

https://github.com/bcbio/bcbio.github.io/blob/master/_posts/2015-10-05-vardict-filtering.md
