### ISSUE TITLE
Automated install fails with lumpy even though the file is downloaded

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#490]
From the output:

```
==> Installing speedseq dependency: lumpy-sv
==> Downloading https://github.com/arq5x/lumpy-sv/releases/download/0.2.2.2/lumpy-sv-0.2.2.2.tar.gz
######################################################################## 100,0%
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
==> Trying a full download
######################################################################## 100,0%
Error: Failed to download resource "lumpy-sv"
Download failed: https://github.com/arq5x/lumpy-sv/releases/download/0.2.2.2/lumpy-sv-0.2.2.2.tar.gz
```

As you can see, brew reports a completed download, but it fails nevertheless.

**Comment by lbeltrame** [comment]
I've noticed this is an issue in case of intermittent connectivity (my cluster suffers from this, but as I said, donated resource....) for git checkouts, because in this case it'll download and fail almost every time, in particular for big checkouts like wham.

**Comment by chapmanb** [comment]
Luca;
Sorry about the continued issues. I've been trying to make some of the bigger downloads like wham smaller by pre-compiling so we don't need to do the whole git recursive clone. Hopefully the latest helps some, but not sure what else to suggest other than retries in these cases. Hope this helps some.
