### ISSUE TITLE
methylation analysis pipelines?

### ISSUE THREAD

**Issue by saketkc** [bcbio/bcbio-nextgen#618]
Brad,

Any plans to incorporate methylome analysis pipelines? I am thinking of using `bcbio-nextgen` architecture to come up with one. Wondering if it would be a duplication of efforts?

However, I am not sure if this is a 'wishlisted' feature from the community.

**Comment by lpantano** [comment]
Hi @saketkc,

I am implementing some code for RRBS data. For now it is outside bcbio, but with a very similar structure so it should be easy to integrate it in the future. I just wanted to follow up with you to know if you have any update from your side. @jnhutchinson's pipeline is based on trim_galore, bismark and bissnp with some middle steps for filtering and bam cleaning. I don't know if you are using the same tools or completely different tools?

thanks in advance!

**Comment by saketkc** [comment]
Hi @lpantano,

Unfortunately I did not make a headstart with this. I do use the same tools, but outside bcbio. They are implemented in python too, but do not follow bcbio structure at all.

**Comment by lpantano** [comment]
Thanks for the feedback. If we end up implementing in bcbio will post here. And maybe from that it would be easier to have your comments for best practices. 
Right now is here: https://github.com/lpantano/ASMfinder. Still not functional, hope to get it working during this week. It has all the parallelization with ipython (same way bcbio has).
