### ISSUE TITLE
tabix Error [E::hts_idx_push] chromosome blocks not continuous

### ISSUE THREAD

**Issue by inti** [bcbio/bcbio-nextgen#624]
Hi @chapmanb ,
I think I tracked down this error message which I reported before on #613 .
It turns out that what happens is exactly what the message says ... 

Briefly, the pipeline sorts the bed file by chromosome and position. However, for some reason they are not sorted properly on the chromosome name. Using the sort command of the pipeline I am getting this which is not sorted properly by chromosome, which means that "chromosome blocks not continuous"

```
[ipedroso@jimi work]$ sort -k1,1 -k2,2n 1_2014-09-26_populus_trichocarpa_diversity_1-sort-callable-callableblocks.bed | grep scaffold_104 
scaffold_1040   1586    2955
scaffold_104    0       242
scaffold_1040   566     606
scaffold_1040   709     1271
scaffold_1040   3113    5047
scaffold_1040   5177    6391
scaffold_1040   6502    13319
scaffold_104    2774    3373
scaffold_104    14249   16134
scaffold_104    16283   16356
scaffold_104    16478   42093
scaffold_1043   0       203
scaffold_1043   342     551
scaffold_1043   867     985
scaffold_1043   1182    2397
scaffold_1043   2509    3187
scaffold_1043   3553    11938
scaffold_1043   12773   12835
scaffold_104    421     456
scaffold_104    3529    4705
scaffold_104    4825    4939
scaffold_104    5546    5668
scaffold_104    5904    7718
scaffold_104    42225   44057
scaffold_104    44182   44766
scaffold_104    68438   68580
scaffold_104    68726   69439
scaffold_1047   105     559
scaffold_104    73523   73694
scaffold_104    75867   75954
scaffold_1047   677     2510
scaffold_1047   2634    2982
scaffold_1047   3364    12767
scaffold_1047   12871   13201
scaffold_104    8097    8805
```

I found here https://www.biostars.org/p/64687/ that using the  V option on the sort would solve the problem

```
[ipedroso@jimi work]$ sort -k1,1V -k2,2n 1_2014-09-26_populus_trichocarpa_diversity_1-sort-callable-callableblocks.bed | grep scaffold_104 
scaffold_104    140844  142121
scaffold_104    142240  145935
scaffold_104    146082  146515
scaffold_1040   566     606
scaffold_1040   709     1271
scaffold_1040   1586    2955
scaffold_1040   3113    5047
scaffold_1040   5177    6391
scaffold_1040   6502    13319
scaffold_1043   0       203
scaffold_1043   342     551
scaffold_1043   867     985
scaffold_1043   1182    2397
scaffold_1043   2509    3187
scaffold_1043   3553    11938
scaffold_1043   12773   12835
scaffold_1047   105     559
scaffold_1047   677     2510
scaffold_1047   2634    2982
scaffold_1047   3364    12767
scaffold_1047   12871   13201
```

and it actually works :), see example below

```
[ipedroso@jimi work]$ sort -k1,1 -k2,2n 1_2014-09-26_populus_trichocarpa_diversity_1-sort-callable-callableblocks.bed > bed.bed
[ipedroso@jimi work]$ bgzip -c bed.bed > bed.bed.gz
[ipedroso@jimi work]$ tabix -f -p bed bed.bed.gz 
[E::hts_idx_push] chromosome blocks not continuous
tbx_index_build failed: bed.bed.gz
```

and with the V option added

```
sort -k1,1V -k2,2n 1_2014-09-26_populus_trichocarpa_diversity_1-sort-callable-callableblocks.bed > bed.bed
bgzip -c bed.bed > bed.bed.gz
tabix -f -p bed bed.bed.gz 
```

The BioStart post says that it may not work on all sort installations so I am not sure how this will work on every installation.

**Comment by baroslava** [comment]
Hello,
I have received the same error message when i have tried to index bam file. The bam file have been made by CrossMap from hg19 bam file to hg38. I have overcome trouble with headers, but the final bam file cannot be indexed for proper use. Still getting message [E::hts_idx_push] chromosome blocks not continuous. Any suggestions? Thanks. B

**Comment by chapmanb** [comment]
Is this referring to usage/indexing with bcbio? If you're having a general problem with CrossMap or samtools indexing the htslib ((http://www.htslib.org/) or CrossMap folks (http://crossmap.sourceforge.net/#contact) would be more able to help. My guess is you need to sort the BAM file after running CrossMap.

**Comment by baroslava** [comment]
I have tried to sort bam file after CrossMap. No help at all.

**Comment by genecell** [comment]
It's a little strange here, my sort version is 8.22 and only `sort -k 1,1 -k2,2n `works for me, rather than`sort -k 1,1V -k2,2n `:
```
sort (GNU coreutils) 8.22
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Haertel and Paul Eggert.
```

**Comment by jingydz** [comment]
$ tabix -p vcf xxx.PASS.mac1.vcf.gz
[E::hts_idx_push] Chromosome blocks not continuous
tbx_index_build failed: xxx.PASS.mac1.vcf.gz

How should I operate on a VCF file?

**Comment by jingydz** [comment]
I have resolved this issue.

zcat xxx.PASS.vcf.gz |grep "^#" >xxx.PASS.vcf.gz.header
zcat xxx.PASS.vcf.gz |grep -v "^#" >xxx.PASS.vcf.gz.record
sort -k 1,1V -k2,2n xxx.PASS.vcf.gz.record >xxx.PASS.vcf.gz.record.sort
cat xxx.PASS.vcf.gz.header xxx.PASS.vcf.gz.record.sort |bgzip -c >xxx.PASS.sort.vcf.gz
tabix -p vcf xxx.PASS.sort.vcf.gz
